### ISSUE TITLE
Working only for 1st message.

### ISSUE THREAD

**Issue by koolkarni** [evollu/react-native-fcm#1]
I have added following code in my  main file:

- (void)applicationDidEnterBackground:(UIApplication *)application {
//  [[FIRMessaging messaging] disconnect];
  NSLog(@"Disconnected from FCM");
}

//add this
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)notification {
  [[NSNotificationCenter defaultCenter] postNotificationName: FCMNotificationReceived
                                                      object:self
                                                    userInfo:notification];
  
}

//add this
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)notification fetchCompletionHandler:(void (^)(UIBackgroundFetchResult))handler {
  [[NSNotificationCenter defaultCenter] postNotificationName:FCMNotificationReceived
                                                      object:self
                                                    userInfo:notification];
  handler(UIBackgroundFetchResultNoData);
}

the notification is shown only once when app runs for 1st time after installation

**Comment by evollu** [comment]
Can you provide more details about your issue? eg. your notification payload.
Did you add [FIRApp configure] in appDelegate.m?

**Comment by koolkarni** [comment]
Yes, I have added the same 


@import Firebase;

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions{
  **[FIRApp configure];**
  [[FBSDKApplicationDelegate sharedInstance] application:application
                           didFinishLaunchingWithOptions:launchOptions];
  

  NSURL *jsCodeLocation;

**Comment by evollu** [comment]
I can't reproduce it in my application. Are you using data payload or notification payload?

**Comment by evollu** [comment]
@koolkarni haven't got updated from you for a while. Have you figured out the issue?

**Comment by koolkarni** [comment]
@evollu Sorry for late reply ,I get the notification on emulator but when i run on real mobile it dosent show anything

**Comment by koolkarni** [comment]
anyways thanks for help.I will solve the issue and write the details here :)

**Comment by evollu** [comment]
hmm interesting. I thought ios emulators can't get notification. I do get notifications on iphones though

**Comment by evollu** [comment]
closing due to no response
