### ISSUE TITLE
Refresh token argument is wrong in documentation

### ISSUE THREAD

**Issue by gorangajic** [evollu/react-native-fcm#10]
in documentation you have 
```
     this.fcmTokenLsnr = DeviceEventEmitter.addListener('FCMTokenRefreshed', (token) => {
```
but instead of the `token:string` object is received instead `{ token: token }`

as you can see 
https://github.com/evollu/react-native-fcm/blob/8ffcac97c597c1039c5d5b3db6819e2f2c43f42e/android/src/main/java/com/evollu/react/fcm/FIRMessagingModule.java#L91

I have noticed this only on `android` not sure for `ios`

**Comment by evollu** [comment]
ios has the same issue :)
readme updated
