### ISSUE TITLE
Local notification is not showing in Android Oreo 

### ISSUE THREAD

**Issue by vaibhgupta09** [evollu/react-native-fcm#1002]
My Paylod
 FCM.presentLocalNotification({
      title:'Welcome to Reno',
      body: "Enjoy Discount Upto 50 Percent off",
      priority: "high",
      show_in_foreground: true,
      local: true,
      channel: "any_id"
    });

**Comment by nazrdogan** [comment]
+1

**Comment by KalumDog** [comment]
+1

**Comment by moulie415** [comment]
Looks like its not working if your targetSDKVersion is set to higher than 25
#698

**Comment by evollu** [comment]
have you registered channels correctly?

**Comment by vaibhgupta09** [comment]
@evollu how to register it?

**Comment by evollu** [comment]
https://github.com/evollu/react-native-fcm/blob/master/Examples/simple-fcm-client/app/App.js#L38

**Comment by christianchown** [comment]
I got caught out by this too - can we add @amallo's note to the README?

**Comment by evollu** [comment]
added a comment to the example project
