### ISSUE TITLE
failed to post notification on channel 'default'

### ISSUE THREAD

**Issue by Ailton265** [evollu/react-native-fcm#1004]
Hi I'm working with this library and I'm testing notification but it is not woking. it appear me this error message. Can anyone help me?
thank you.
![screenshot_1532000016](https://user-images.githubusercontent.com/17340733/42951238-a93bd864-8b6d-11e8-9cf3-f84fbc1337d5.png)

**Comment by evollu** [comment]
have you registered notification channel? there is an extra piece of code you need to put in
https://github.com/evollu/react-native-fcm/blob/master/Examples/simple-fcm-client/app/App.js#L38

**Comment by Ailton265** [comment]
@evollu thank you, it is working now 👍
