### ISSUE TITLE
Execution failed for task ':app:transformClassesWithMultidexlistForDebug'. > com.android.build.api.transform.TransformException: Error while generating the main dex list.

### ISSUE THREAD

**Issue by bashirpour** [evollu/react-native-fcm#1005]
>Execution failed for task ':app:transformClassesWithMultidexlistForDebug'.
> com.android.build.api.transform.TransformException: Error while generating the main dex list.

**Comment by abdullateef97** [comment]
@bashirpour have you been able to solve this issue how did you solve it
