### ISSUE TITLE
Samsung S8+ Android 8.0 Background FCM Push - Android Robot Icon

### ISSUE THREAD

**Issue by VansonLeung** [evollu/react-native-fcm#1009]
RN version: 0.50.3
RN FCM version: 16.0.0

Issue: 
Tested with other Android phone is OK.
Tested with Samsung S8+ 
  - Foreground FCM => Have valid icon
  - Background FCM => Shows Android Robot icon

![whatsapp image 2018-08-02 at 12 44 13 pm](https://user-images.githubusercontent.com/1129695/43563142-41cd85b0-9653-11e8-8946-9393c7241358.jpeg)

**Comment by evollu** [comment]
"Background FCM" is it remote notification?

**Comment by VansonLeung** [comment]
yes, remote notification

**Comment by evollu** [comment]
have you added default icon in manifest file? or add "icon" prop in notification payload?

**Comment by VansonLeung** [comment]
seems fixed by using a proper notification icon (black / white PNG)
