### ISSUE TITLE
Package installed from npm/yarn seems to be outdated

### ISSUE THREAD

**Issue by windhamwong** [evollu/react-native-fcm#1013]
Looking into the src code, i.e. android/src/build.gradle, seems to have a big difference to the one in the repository. The version I installed from yarn is outdated and the version of Firebase-core and Firebase-Messaging do not match at all. (The version I got is using the same version number of both packages, however, the working versions should be e.g. 16.0.1 and 17.1.0)
Since I don't know how to push an update to the public listing, I create this issue for this instead.

**Comment by evollu** [comment]
since you create PR, I'm closing this
