### ISSUE TITLE
FCM.setBadgeNumber not working

### ISSUE THREAD

**Issue by alekhurst** [evollu/react-native-fcm#103]
When attempting to use `FCM.setBadgeNumber(25)`, it throws an error: `RNFIRMesssaging.setBadgeNumber was called with 0 arguments, but expects 1`.

I initially assumed that in `index.js` I needed to change

```
FCM.setBadgeNumber = () => {
    RNFIRMessaging.setBadgeNumber();
}
``` 

to

```
FCM.setBadgeNumber = (n) => {
    RNFIRMessaging.setBadgeNumber(n);
}
```

Which actually solved the error... but did not behave correctly (no badge number was set)

**Comment by evollu** [comment]
looking into it

**Comment by evollu** [comment]
I did the same fix and can see the badge being set correctly
NOTE: it is an iOS only function

**Comment by evollu** [comment]
check the master branch

**Comment by alekhurst** [comment]
Cool, will do. Thanks!

**Comment by evollu** [comment]
@alekhurst is it working?

**Comment by alekhurst** [comment]
Yep, works great!
