### ISSUE TITLE
When application is in background

### ISSUE THREAD

**Issue by Amit2530** [evollu/react-native-fcm#1032]
When application is in background and when notification is received after that we click on that notification to navigate the particular screen but it the navigation is not working on,

FCM.getInitialNotification().then(notif => {
            console.log("Click from background", notif);
            setTimeout(() => {
                this.props.navigation.navigate('LoginScreen');
            }, 500)
});

It is giving error that 'undefine navigate property' ??

what is the proper way to navigate to the different screen when click on notification and application is in background?

which method will get call when application is in background and notification received ?

**Comment by evollu** [comment]
when app is in background, notification is triggered though listener callback.
`undefine navigate property` sounds like unrelated issue
