### ISSUE TITLE
what version gradle for   react-native-fcm 15.0.2

### ISSUE THREAD

**Issue by herarya** [evollu/react-native-fcm#1036]
hi, what version gradle for `react-native-fcm 15.0.2`, i install 

```java
 configurations.all {
            resolutionStrategy.eachDependency { DependencyResolveDetails details ->
                def requested = details.requested
                if (requested.group == 'com.google.android.gms') {
                    details.useVersion '12.0.1'
                }
                if (requested.group == 'com.google.firebase') {
                    details.useVersion '12.0.1'
                }
            }
        }
```
still not working in android, ios work

When openning an issue, please include following information for better support

1. What version of RN and react-native-fcm are you running?
2. What device are you using? (e.g iOS9 emulator, Android 6 device)?
3. Is your app running in foreground, background or not running?

**Comment by evollu** [comment]
what error are you getting?
are you using other firebase packages?

**Comment by herarya** [comment]
hi, @evollu  im using 
`"react-native-fcm": "15.0.2",`

gradle

```java
compile project(':react-native-fcm')
compile 'com.google.firebase:firebase-core:10.0.0'
compile 'com.google.firebase:firebase-crash:10.0.0'
```
this dont error, but "FCM.on(FCMEvent.Notification" not fire

thanks, sorry my bad english
