### ISSUE TITLE
why createNotificationChannel is not in index.d.ts?

### ISSUE THREAD

**Issue by BatDroid** [evollu/react-native-fcm#1037]
react-native-fcm: 16.1.0
i had a problem in android 8 which didn't receive push notification. it worked when i sent the `"channel":"default"` from server. i found somewhere that this method is needed in client side:
```
FCM.createNotificationChannel({
            id: 'default',
            name: 'Default',
            description: 'default',
            priority: 'high'
 });
```
now its working fine but why is it deleted from the index.d.ts?

**Comment by evollu** [comment]
just missed it. will add
