### ISSUE TITLE
getInitialNotification() returning error

### ISSUE THREAD

**Issue by malinthe** [evollu/react-native-fcm#104]
Updated to 2.0.1 today and when I tried to use `FCM.getInitialNotification()` app returns the following error:

`Cannot convert argument of type class
android.content.Intent`

Does anyone have the same issue?

![screenshot_20160914-133930](https://cloud.githubusercontent.com/assets/1997002/18504602/c1722370-7a80-11e6-929f-db1dc63a9b6f.png)

**Comment by sibelius** [comment]
I can confirm this

**Comment by sibelius** [comment]
@evollu I think `Intent` is not serializable https://github.com/evollu/react-native-fcm/blob/master/android/src/main/java/com/evollu/react/fcm/FIRMessagingModule.java#L53

**Comment by evollu** [comment]
looking into this

**Comment by evollu** [comment]
fixed with v2.0.2

**Comment by malinthe** [comment]
Seems to be fixed with v2.0.2
