### ISSUE TITLE
requestPermissions always resolves on iOS 9.x

### ISSUE THREAD

**Issue by CptFabulouso** [evollu/react-native-fcm#1046]
1. What version of RN and react-native-fcm are you running?
"react-native": "0.57.0",
"react-native-fcm": "16.2.3"
2. What device are you using? (e.g iOS9 emulator, Android 6 device)?
iOS 9.3 emulator
3. Is your app running in foreground, background or not running?
foreground

how to handle permissions on iOS < 10? The requestPermissions function is always immediately resolved and therefore granted. I found no info or warning about this behavior in the documentation, so I don't know if this desired or a bug?

**Comment by evollu** [comment]
iOS 9 doesn't give you feedback if the user has accepted or not so it is immediately resolved.
