### ISSUE TITLE
Better docs for FCM.getInitialNotification().then()

### ISSUE THREAD

**Issue by sibelius** [evollu/react-native-fcm#106]
What is the data returned from `getInitialNotification()`?

When I click my push notification on android, it returns only:

`{ opened_from_tray: 1, fcm: { action: null } }`

while in foreground it receives my `body` payload without `opened_from_tray` on android

**Comment by evollu** [comment]
you should receive `body` when you click notification too if you define it in payload.
no `opened_from_tray` when android in foreground is expected behavior

**Comment by sibelius** [comment]
docs looks good,

I still have the same error on android: `{ opened_from_tray: 1, fcm: { action: null } }` no payload data
