### ISSUE TITLE
FIRMessagingModule is not abstract and does not override abstract method onActivityResult

### ISSUE THREAD

**Issue by LucasBassetti** [evollu/react-native-fcm#107]
<pre>
<code>
:react-native-fcm:processReleaseJavaRes UP-TO-DATE
:react-native-fcm:compileReleaseJavaWithJavac
.../node_modules/react-native-fcm/android/src/main/java/com/evollu/react/fcm/FIRMessagingModule.java:33: error: FIRMessagingModule is not abstract and does not override abstract method onActivityResult(int,int,Intent) in ActivityEventListener
public class FIRMessagingModule extends ReactContextBaseJavaModule implements LifecycleEventListener, ActivityEventListener {
       ^
.../node_modules/react-native-fcm/android/src/main/java/com/evollu/react/fcm/FIRMessagingModule.java:186: error: method does not override or implement a method from a supertype
    @Override
    ^
Note: .../node_modules/react-native-fcm/android/src/main/java/com/evollu/react/fcm/FIRMessagingModule.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
:react-native-fcm:compileReleaseJavaWithJavac FAILED
</code>
</pre>

I had a branch where the android app was working fine. Suddenly, when I returned to this branch and tried run the android app this error appears.

Anybody knows how to solve that?

**Comment by LucasBassetti** [comment]
Sorry. It seems like that I installed a new release of `react-native-fcm`. When a downgrade do `1.0.16` works again.

**Comment by ssomnoremac** [comment]
Really, I got this same error on RN33 RNfcm2.1.1

**Comment by pfeodrippe** [comment]
@ssomnoremac same error as you

**Comment by holyxiaoxin** [comment]
I got this error using RN33, upgraded to `2.3.0` and it works.
