### ISSUE TITLE
Execution failed for task ':react-native-fcm:verifyReleaseResources'. > com.android.ide.common.process.ProcessException: Failed to execute aapt

### ISSUE THREAD

**Issue by 12ahsanali34** [evollu/react-native-fcm#1085]
Before openning an issue
1. Reproduce it with the example project in this repo.
2. If you can't receive iOS notification, make sure you can receive notification using quickstart-ios project provided by Firebase team

When openning an issue, please include following information for better support

1. What version of RN and react-native-fcm are you running?
2. What device are you using? (e.g iOS9 emulator, Android 6 device)?
3. Is your app running in foreground, background or not running?

**Comment by kapil708** [comment]
hi i am having same issue
build error 
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

Package
===============
`"dependencies": {
    "native-base": "^2.8.1",
    "qs": "^6.5.2",
    "react": "16.3.1",
    "react-native": "0.55.3",
    "react-native-app-intro-slider": "^1.0.1",
    "react-native-banner-carousel": "^1.0.3",
    "react-native-device-info": "^0.25.1",
    "react-native-fcm": "^16.2.4",
    "react-native-image-picker": "^0.27.1",
    "react-native-loading-spinner-overlay": "^1.0.1",
    "react-native-modalbox": "^1.6.0",
    "react-navigation": "^2.18.0"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "babel-preset-react-native": "4.0.1",
    "jest": "23.6.0",
    "react-test-renderer": "16.3.1"
  }`

config
=============
`compileSdkVersion 26
    buildToolsVersion "26.0.2"

    defaultConfig {
        applicationId "com.dealjeeto"
        minSdkVersion 16
        targetSdkVersion 26
        versionCode 5
        versionName "1.0.4"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }`

Device : Nexus 5x API 27
