### ISSUE TITLE
"undefined is not an object" ANDROID PROBLEM

### ISSUE THREAD

**Issue by luisfuertes** [evollu/react-native-fcm#109]
Hi, i try to install your component.

On iOS all works fine, but on Android when i call `FCM.requestPermissions();` or `FCM.getFCMToken().then(token => {}})`

Error: 
`undefined is not an object (evaluating 'RNFIRMessaging.requestPermissions')`

I have this component installed previously but i dont think its relevant
https://github.com/evollu/react-native-firebase-analytics

PD: I have `import FCM from 'react-native-fcm';`

![media-20160919](https://cloud.githubusercontent.com/assets/18212615/18638426/66ed35e8-7e90-11e6-861d-cbceb827e059.png)

**Comment by besarthoxhaj** [comment]
👍  having the same problem.

we ran `react-native link` and `console.log(FCM)` shows us the object attributes. As soon as we call one we get an `undefined is not an object`.

Any suggestions?

**Comment by sibelius** [comment]
U r probably not linking the android project in a correct way

**Comment by besarthoxhaj** [comment]
@sibelius yes it probably is that - although we ran the usual react-native link command. Any suggestions for how to double check successful linking?

**Comment by luisfuertes** [comment]
Project compile, and i did all steps on readme... I think it is linking correctly

**Comment by sibelius** [comment]
```java
public class MainApplication extends Application implements ReactApplication {
    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
          new FIRMessagingPackage()
      );
    }
}
```

**Comment by sibelius** [comment]
clean project on android studio and try to build again

**Comment by besarthoxhaj** [comment]
I am getting the below error when I run `react-native run-android`. Could this be part of the problem?

```
google-services plugin could not detect any version for com.google.android.gms or com.google.firebase, default version: 9.0.0 will be used.
please apply google-services plugin at the bottom of the build file.
```

Btw thanks for the help!!

**Comment by luisfuertes** [comment]
@sibelius  Lol! My bad! Thanks! I havnt it. What i have to import to add this?
´´´
public class MainApplication extends Application implements ReactApplication {
    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
          new FIRMessagingPackage()
      );
    }
}
´´´

**Comment by sibelius** [comment]
android studio can help fix import stuff

`import com.evollu.react.fcm.FIRMessagingPackage;`

**Comment by luisfuertes** [comment]
O true, sorry, my bad habit of use Atom for all xd Thanks!

**Comment by besarthoxhaj** [comment]
Fixed, just went through everything again and had no problems second time around.

Thanks!

**Comment by luisfuertes** [comment]
On android Notifications from Firebase console arrive, but dont give Token and dont call Component method to receive notifications. But with app closed or in background the notifications arrive correctly :s

Some idea?

**Comment by mypark** [comment]
react-native link doesn't seem to correctly add the code to MainApplication.java - why is that?

**Comment by nicolasdanelon** [comment]
same question that @mypark here! any ideas?

**Comment by gaboesquivel** [comment]
I have the same problem with  `react-native@0.45.1` and `react-native-fcm@7.1.0`

There's no `getPackages` method to override in this version AFAIK 
https://github.com/facebook/react-native/blob/0.45-stable/ReactAndroid/src/main/java/com/facebook/react/ReactActivity.java

```
import android.os.Bundle;
import com.facebook.react.ReactActivity;
import com.cboy.rn.splashscreen.SplashScreen;
import android.content.Intent;

public class MainActivity extends ReactActivity {

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
      return "ComponentName";
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
      SplashScreen.show(this);  
      super.onCreate(savedInstanceState);
    }

    @Override
    public void onNewIntent (Intent intent) {
      super.onNewIntent(intent);
        setIntent(intent);
      }
}

```

Any ideas ?

**Comment by saraztr** [comment]
@sibelius thank you. Finally, it works!
