### ISSUE TITLE
(iOS) Undefined is not an object when calling RNFIRMessaging.requestPermissions()

### ISSUE THREAD

**Issue by nilswloka** [evollu/react-native-fcm#110]
First of all thanks for the great library. We had no troubles getting it work for the Android version. However, after following the instructions for integrating it with our iOS app, we ran into the `Undefined is not an object` error.

I followed the instructions given in the readme file and still am running into this error when executing `react-native run-ion`. From the looks of it, the XCode workspace is set up correctly:

**Libraries:**
![image](https://cloud.githubusercontent.com/assets/46620/18670362/d3c4839c-7f3f-11e6-8772-883611432d95.png)

**Cocoapod:**
![image](https://cloud.githubusercontent.com/assets/46620/18670402/ff04d1ec-7f3f-11e6-8e88-233b5bb18500.png)

**Linking:**
![image](https://cloud.githubusercontent.com/assets/46620/18670419/2074c40e-7f40-11e6-8296-047072072fb4.png)

Also, `AppDelegate.m` is modified according to the instructions and compiles without an error. Is there anything I'm missing? Do you have any advice for debugging this?

**Comment by nilswloka** [comment]
Update: Interestingly, I don't get the error when building and running the application from XCode. It just happens when using `react-native run-ios`.

**Comment by sibelius** [comment]
this is related to using cocoapods

in xcode u use xcworkspace, `react-native run-ios` uses xcodeproject

**Comment by nilswloka** [comment]
@sibelius I don't think that's true anymore. The command line client is explicitly referring to the xcworkspace file. Also, the build succeeds. It's just that I'm getting a red box when running the application.

**Comment by evollu** [comment]
may be the module wasn't linked well. Do you still get red box is you run `run-ios`?

**Comment by nilswloka** [comment]
Yes, I do. I am resorting to running it from XCode right now, but still wonder what the issue might be.

**Comment by sibelius** [comment]
@evollu we can close this, as it is working fine on xcode

**Comment by the-simian** [comment]
I know this got closed but: Hey I am running into the same issue, do any of you know how to actually run this via `react-native run-ios` ? I'd like to have that working also.

**Comment by evollu** [comment]
it is linking issue. try to figure out what is wrong in xcode then you can run `react-native run-ios`

**Comment by sibelius** [comment]
@the-simian check it out the example of this PR: https://github.com/evollu/react-native-fcm/pull/152

**Comment by mikemcelligott** [comment]
Same problem here, getting "undefined is not an object (evaluating '_reactNativeFcm.FCM.requestPermissions')".  App builds from both the command line and xcode (once I stopped trying to use cocoapods).  I'm not proficient enough with XCode to know how to resolve a linking issue - it looks to me like all of the libraries and frameworks required are included.

<img width="678" alt="screen shot 2017-02-08 at 2 20 34 pm" src="https://cloud.githubusercontent.com/assets/487946/22753343/d294cb92-ee09-11e6-9b86-05c67f5fd70e.png">

**Comment by mikemcelligott** [comment]
My mistake, the JS import syntax is new to me and I was importing the default export incorrectly.
