### ISSUE TITLE
trouble receiving data messages on ios when running in background

### ISSUE THREAD

**Issue by jcharbo** [evollu/react-native-fcm#112]
Hi, I'm using RN 33 and fcm 2.1.0.  I am unable to receive any messages on IOS when my app is running in the background.  I am able to receive all messages when the app is in the foreground and notifications show up in IOS as well.  They also show up in IOS when the app is in the background but I cannot get any messages to come through into the app when the app is in the background.
thanks

**Comment by siemya** [comment]
#116 same problem

**Comment by evollu** [comment]
can you add break point to handler in app delegate?
can you share your code in app delegate.m?

**Comment by evollu** [comment]
discuss in #116
