### ISSUE TITLE
FCM.presentLocalNotification is undefined

### ISSUE THREAD

**Issue by jitenderchand1** [evollu/react-native-fcm#119]
I am trying to show notification in android app.  Following event is triggering when I am receiving notification. I have used FCM.presentLocalNotification({}) inside but I am getting error **undefined not a function**. I console FCM object but did not found many function which is described in github

```
this.notificationUnsubscribe = FCM.on('notification', (notif) => {
  FCM.presentLocalNotification({
           id: "UNIQ_ID_STRING",                               
            title: "My Notification Title",                     
            body: "My Notification Message",               
            sound: "default", 
            .....         
    })
});
```

**Comment by evollu** [comment]
are you having the latest version v2.1.1?

**Comment by jitenderchand1** [comment]
I am running RN < 0.33.0 so as document suggested I am using v1.1.0. However when I am running following command then it is pointing to v1.1.1 which is giving error

npm install react-native-fcm then it is pointing to v1.1.1

error
```

/Users/jitendra/Desktop/hostmakerco/ops-mobile/node_modules/react-native-fcm/android/src/main/java/com/evollu/react/fcm/FIRMessagingModule.java:30: error: FIRMessagingModule is not abstract and does not override abstract method onActivityResult(int,int,Intent) in ActivityEventListener
public class FIRMessagingModule extends ReactContextBaseJavaModule implements LifecycleEventListener, ActivityEventListener {
       ^
/Users/jitendra/Desktop/hostmakerco/ops-mobile/node_modules/react-native-fcm/android/src/main/java/com/evollu/react/fcm/FIRMessagingModule.java:158: error: method does not override or implement a method from a supertype
    @Override
    ^
Note: /Users/jitendra/Desktop/hostmakerco/ops-mobile/node_modules/react-native-fcm/android/src/main/java/com/evollu/react/fcm/FIRMessagingModule.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
:react-native-fcm:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-fcm:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

**Comment by evollu** [comment]
use specific version "1.1.0" rather than "^1.1.0"

**Comment by jitenderchand1** [comment]
I changes "react-native-fcm": "^1.1.0" to "react-native-fcm": "1.1.0" but still not able to get it working. I am getting only few methods in FCM object.

![screen shot 2016-09-22 at 9 24 30 am](https://cloud.githubusercontent.com/assets/19687185/18736642/9644af2a-80a6-11e6-8a00-1338028e459f.png)

**Comment by sibelius** [comment]
U need to upgrade RN to 33 to use the latest version that includes local notification on RN-FCM

**Comment by evollu** [comment]
right... Sorry I don't have time to maintain different RN version support

**Comment by dg92** [comment]
hi @evollu , I am in the same problem but 
"react-native": "^0.32.0",
"react-native-fcm": "^1.0.15"

Now i cannot upgrade my react native as it will break other module. Please help me out. I am getting same object as @jitenderchand1.

**Comment by evollu** [comment]
you can use 1.1.0

**Comment by dg92** [comment]
@evollu  Still giving error. 
using this code 
  FCM.on('notification', (notif) => {
      console.log('notif on foreground', notif);
      console.log('checking fcm', FCM);
![screen shot 2016-10-06 at 7 58 46 am](https://cloud.githubusercontent.com/assets/17122343/19138545/c344107a-8b9a-11e6-92be-0ef2c4a1cc82.png)

      FCM.presentLocalNotification({
        title: 'My Notification Title',                     // as FCM payload
        body: 'My Notification Message',                    // as FCM payload (required)
        sound: 'default',                                   // as FCM payload
        priority: 'high',                                   // as FCM payload
        click_action: 'New',                             // as FCM payload
        number: 10,                                         // Android only
        ticker: 'My Notification Ticker',                   // Android only
        auto_cancel: true,                                  // Android only (default true)
        large_icon: 'ic_launcher',                           // Android only
        icon: 'ic_notification',                            // as FCM payload
        big_text: 'Show when notification is expanded',     // Android only
        sub_text: 'This is a subText',                      // Android only
        color: 'red',                                       // Android only
        vibrate: 300,                                       // Android only default: 300, no vibration if you pass null
        tag: 'some_tag',                                    // Android only
        group: 'group',                                     // Android only
        my_custom_data:'my_custom_field_value',             // extra data you want to throw
        lights: true                                      // Android only, LED blinking (default false)
      });
![screenshot_20161006-075609](https://cloud.githubusercontent.com/assets/17122343/19138516/81778cbc-8b9a-11e6-88ed-a3498e82b5a4.png)

**Comment by dg92** [comment]
@evollu package json

    "react-native": "^0.32.0",
    "react-native-fcm": "1.1.0",

**Comment by evollu** [comment]
local notification is only supported in v2.

**Comment by dg92** [comment]
for V2 i need RN 33?

**Comment by evollu** [comment]
yes

**Comment by dg92** [comment]
@evollu I need foreground notification and for that i need local notification, is there any other work around ?

I can't upgrade to RN 33

**Comment by evollu** [comment]
you may use another local notification library. why do you stuck with old RN? ask the blocking repo to upgrade or fork it yourself. It is easy

**Comment by dg92** [comment]
ok. Thanks
