### ISSUE TITLE
error states that I need to add "remote notification" to Info.plist

### ISSUE THREAD

**Issue by ssomnoremac** [evollu/react-native-fcm#120]
here is the 5th error message I've received trying to install this module. This first 4 I was able to resolve. using RN33 with fcm2.1.0
```
2016-09-21 15:15:57.781 Hyr[46044:5282187] You've implemented -[<UIApplicationDelegate> application:didReceiveRemoteNotification:fetchCompletionHandler:], but you still need to add "remote-notification" to the list of your supported UIBackgroundModes in your Info.plist.
2016-09-21 15:15:57.806 Hyr[46044:5282187] Could not locate configuration file: 'GoogleService-Info.plist'.
2016-09-21 15:15:57.825 Hyr[46044:5282187] *** Terminating app due to uncaught exception 'com.firebase.core', reason: '[FIRApp configure] could not find a valid GoogleServices-Info.plist in your project. Please download one from https://console.firebase.google.com/.'
```

My GoogleService file is there next to `Info.plist`

**Comment by omair100** [comment]
In xcode did you import the GoogleService file?  I had issues until i imported the file via xcode.

**Comment by sibelius** [comment]
U should add this to ur app capability, please follow all README instructions

**Comment by ssomnoremac** [comment]
it's sitting right there where it's supposed to. Isn't the first error the problem?

**Comment by evollu** [comment]
@ssomnoremac in xcode, click project file->Capabilities, turn on local notification capabilities

**Comment by ssomnoremac** [comment]
awesome! thanks, I'm trying to install over again with the new `README` . If I get an error about `@import UserNoticiations` in `RNFIRMesssaging.m` is it likely my cocopods didn't install enough packages?

**Comment by ssomnoremac** [comment]
@evollu , saw your commit just now. I added the `UserNotifications` import to `AppDelegate.h` but I still get the above error. On RN33 and RNfcm@2.2.0. Should I use master?

**Comment by ssomnoremac** [comment]
resolved both, same error. @omair100 is importing the GoogleService file the same and dragging the file into xcode or are you talking about something else?

**Comment by evollu** [comment]
possible to share your project?

**Comment by ssomnoremac** [comment]
no, I can't unfortunately. There isn't a clear reason why 

    @import UserNotifications
 could be not found.

**Comment by evollu** [comment]
are you using xcode 8?

**Comment by ssomnoremac** [comment]
7.3

**Comment by evollu** [comment]
that is the reason.
new import is only available in xcode
i suggest you upgrade to support iOS 10
otherwise you need go down to lower package version

**Comment by ssomnoremac** [comment]
great, thanks so much for the quick response.

**Comment by cristovao-trevisan** [comment]
You can also drag the GoogleService file into your project in Xcode
