### ISSUE TITLE
warning: meta method 'UILocalNotification:' in category conflicts with same method from another category

### ISSUE THREAD

**Issue by bourgois** [evollu/react-native-fcm#124]
With the latest version (2.2.0) of FCM and RN 0.33.0 I now have both RCTPushNotificationManager and RNFIRMessaging that refer to UILocalNotification.

I was wondering if I should remove PushNotificationIOS from RN as it isn't mentioned in the doc?

**Comment by evollu** [comment]
you should only keep one of them. 
this repo provides most of RCTPushNotificationManager provides
