### ISSUE TITLE
Typo in the documentation?

### ISSUE THREAD

**Issue by nodegin** [evollu/react-native-fcm#125]
Hello, I found that in the documentation:

```diff
+ -(void)application:(UIApplication *)application didReceiveLocalNotification:(UILocalNotification *)notification 
+ {
+   [[NSNotificationCenter defaultCenter] postNotificationName:FCMLocalNotificationReceived object:self userInfo:notification.userInfo];
+ }
```

having `FCMLocalNotificationReceived`, which XCode warns me with an error.

![20](https://cloud.githubusercontent.com/assets/8536244/18765678/53775bc2-8149-11e6-85d4-94059ecac30c.png)

and I have search this repository for [FCMLocalNotificationReceived](https://github.com/evollu/react-native-fcm/search?utf8=%E2%9C%93&q=FCMLocalNotificationReceived) and no results were found but [FCMNotificationReceived](https://github.com/evollu/react-native-fcm/search?utf8=%E2%9C%93&q=FCMNotificationReceived&type=Code)

I'm not sure is this a typo or not, please correct me if I was wrong..

**Comment by evollu** [comment]
document outdated, fixed
note: Shared steps instruction is changed also, code for local notification handler is there
