### ISSUE TITLE
Show head-up notification when app is killed or in background

### ISSUE THREAD

**Issue by jitenderchand1** [evollu/react-native-fcm#127]
Right now only notification icon shown in notification bar but it did not pop up. I am sending notification using google FCM

**Comment by evollu** [comment]
that is an issue with Firebase SDK for now. they don't set priority to high.
You can send a data notification and create a local notification if you have to have it before firebase team fixes it. Some native code will be required

**Comment by mmazzarolo** [comment]
Any news on this issue? 👍
