### ISSUE TITLE
ios Build Failure (no known instance method for selector 'appData')

### ISSUE THREAD

**Issue by nertilzhuri** [evollu/react-native-fcm#128]
Greetings,

After upgrading __react-native-fcm__ to version **2.2.0** the ios build fails with 3 errors which are described in the screenshots below, even removing and reinstalling the library still fails the same way:

The errors all are from RNFIRMessaging.m

<img width="751" alt="screenshot at sep 25 20-55-20" src="https://cloud.githubusercontent.com/assets/12595516/18817515/8fc1a87e-8362-11e6-818f-7a4181b168a4.png">

<img width="742" alt="screenshot at sep 25 20-55-37" src="https://cloud.githubusercontent.com/assets/12595516/18817516/92c22ac6-8362-11e6-9281-9cc228285bf2.png">

<img width="746" alt="screenshot at sep 25 20-56-15" src="https://cloud.githubusercontent.com/assets/12595516/18817517/952713a8-8362-11e6-8abb-1ab836a22c75.png">

Notes:
react-native version: "^0.33.0"
react version: "15.3.1"
Testing on iOS 10 simulator
Android version is working 

Thank you

**Comment by magrinj** [comment]
I had the same problem, and the problem is because you don't update Firebase in your pod installation, just go in `ios` folder and run `pod update`, don't forget to apply the new change in `AppDelegate.m` and `AppDelegate.h`

**Comment by nertilzhuri** [comment]
I forgot about the Firebase, thank you.

For anyone who is not using **pod** for firebase just re-download the Firebase files and add those to the project again.

**Comment by willoughby** [comment]
Im getting this error after linking, I can do a build with the firebase pod with no problems, after running react-native link i get the errors above.

**Comment by magrinj** [comment]
Did you run `pod install` in the ios folder ?

**Comment by willoughby** [comment]
Yea, like i said I could import all of the firebase libs with no problem and run my app, The problem was as soon as I linked this project. In the end I installed firebase manually and it worked.

**Comment by magrinj** [comment]
Sound strange, you open `.xworkspace` file ?

**Comment by willoughby** [comment]
Yep,

**Comment by magrinj** [comment]
Hmm, can you put what your pod file look like here please :)

**Comment by willoughby** [comment]
I created this when I had issues. https://github.com/evollu/react-native-fcm/issues/134

**Comment by magrinj** [comment]
Ok, I wait for your Podfile, hope the problem came from that, I don't have any other ideas for the moment ^^

**Comment by tioback** [comment]
I had the same issue as @willoughby 

Podfile is as plain as it gets..

    # Uncomment this line to define a global platform for your project
    # platform :ios, '9.0'
    
    target 'MagicApp' do
      # Uncomment this line if you're using Swift or would like to use dynamic frameworks
      # use_frameworks!
    
      # Pods for MagicApp
      pod 'Firebase/Messaging'
    
      target 'MagicAppTests' do
        inherit! :search_paths
        # Pods for testing
      end
    
    end

**Comment by richarddlu** [comment]
I had the same error. It was solved by executing pod update inside the iOS project folder.

**Comment by simaattar** [comment]
it may sound silly, but for me reopening the project did the trick!
