### ISSUE TITLE
Firebase Dynamic Links is not working after updating the pods

### ISSUE THREAD

**Issue by mrithula-ancy** [evollu/react-native-fcm#129]
Hi,
 I updated the pods to get the new Firebase messaging pod files that support FIRMessagingDelegate and I lost the resource files (GINInviteResources.bundle, GPPACLPickerResources.bundle) for the dynamic links. I guess we need the resource files for the dynamic links to work. Can someone help me on this. 

Thanks,
Mrithula

**Comment by evollu** [comment]
did Firebase remove it on purpose?

**Comment by sibelius** [comment]
@mrithula-ancy did u solve ur problem?

**Comment by mrithula-ancy** [comment]
yes I did.

**Comment by sibelius** [comment]
Can we close this?
