### ISSUE TITLE
Handling push notification

### ISSUE THREAD

**Issue by meni-cherbakovsky** [evollu/react-native-fcm#13]
@evollu, is there any way to get an actual push notification on android devices?
Currently, it looks like this package handles only the connection with FCM. Another package you have, react-native-gcm-push-notification, or the package react-native-push-notification let you create a notification too but unfortunately they use GCM.
Any thoughts?

Thanks

**Comment by evollu** [comment]
FCM is the successor of GCM, they provide the exact same functionality. react-native-gcm-push-notification is no longer actively maintained.
You can send actual push notification to both IOS and Android devices, using the same payload as you do for GCM. Just change the post destination to FCM api endpoint.

**Comment by meni-cherbakovsky** [comment]
Thanks @evollu for the quick reply.
Do you recommend using react-native-push-notification in order to send actual push notification?

**Comment by evollu** [comment]
I recommend using this library for push notification and react-native-push-notification for local notification.

**Comment by meni-cherbakovsky** [comment]
Could you please guide me how to use this library for push notifications? I used your code sample and I managed to get a notification whenever I sent if from FCM. But I was missing the actual notification in my device. Is there any way to achieve this or this is what you call "local notification"?

**Comment by evollu** [comment]
I assume "actual notification" refers to a banner showing from the top. You can only see the banner when app is not running or in background.
local notification means the app initiating an system notification locally, where server is not involved.

Does this answer your question?

**Comment by meni-cherbakovsky** [comment]
Well, kind of. The thing is that I want to get a notification from a server and then show it as the banner at the top of the device (like other common apps). So server is involved here + an actual notification need.
How could I achieve this thing?
Thx again

**Comment by evollu** [comment]
fcm should do this for you. and the payload sent to fcm server looks like
```
{
  "to":"some_device_token",
  "content_available": true,
  "notification": {
      "title": "hello",
      "body": "yo"
  }
}
```

**Comment by meni-cherbakovsky** [comment]
I followed this package documentation and managed to get my device token through FCM.getFCMToken() method. Then, I went to FCM console and sent a message manually, giving the FCM registration token I have. I managed to see the notification object sent from FCM console in FCM.on('notification'). Besides that, I didn't get any actual notification at the top of my device. The question here is whether I have to do something with the notification object I got in order to pop it up as a banner, or like you said, FCM should it this for me - if so, it does not work for me.

**Comment by evollu** [comment]
I just tried on my iphone and it works.
Is your app running in background or kill when you send out notification? Is it android or IOS?

**Comment by meni-cherbakovsky** [comment]
It's an android emulator and the app is in the foreground. AFAIK this should work on an android emulator. Am I right?

**Comment by evollu** [comment]
the banner won't show when the app is in foreground. move it to background or kill it then you can see banner

**Comment by meni-cherbakovsky** [comment]
Simple as that. It worked, thanks a lot! :)
