### ISSUE TITLE
Notification handler not being called on clicking a local notification

### ISSUE THREAD

**Issue by lukefanning** [evollu/react-native-fcm#130]
@evollu Hey, I needed to display notifications even in the foreground for an app I'm working on so I made use of `presentLocalNotification()`. This works fine and popups up a notification while the app is in the foreground. However on clicking it I can't seem to retrieve the extra data that I've added to it. The notification handler isn't called at all. I've tried:

- Adding & removing `click_action` (same `click_action` I've used for push notifications)
- Adding my extra data inside of a `data` object and outside of it

I'm using RN 0.33 and react-native-fcm 2.0.3
I'm running the app on an Android 6 device.
The app is running in the foreground.

If I present the local notif and then put the app into the background, clicking the notification does bring the app back to the foreground (but notification handler still isn't called). Am I missing something?

**Comment by evollu** [comment]
since you are using v2 now, try update to latest version
however, presenting local notification while app is in foreground is not a suggested behavior for iOS and probably android. (you can not achieve this at all in iOS 9 and I'm blocking this in android in v2.2).
have you considered building a modal/overlay/toast instead of notification?

**Comment by lukefanning** [comment]
Yeah doesn't appear in the foreground at all now that I've upgraded to 2.2.0. I'm going to close this anyway as you're probably right about using some kind of overlay within the app itself.

**Comment by evollu** [comment]
cool

**Comment by maxsong92** [comment]
@evollu Does that mean I'm expected to show notification like this?

```
FCM.on('notification', (notif) => {
  FCM.presentLocalNotification({})
})
```

I am trying to show a popup notification like below:

1. App is in the background: show a popup notification. Facebook does this but Instagram only puts the notification in the system tray.
2. App is in the foreground: show a popup notification like above

**Comment by evollu** [comment]
this only solves the problem when app is live. you need to add another message listener to show banner when app is not running
