### ISSUE TITLE
getFCMToken() returns null and don't know how to refresh

### ISSUE THREAD

**Issue by tarr11** [evollu/react-native-fcm#131]
I'm trying my first build, and I've configured all of the various build files.  When I call:

```
    FCM.getFCMToken().then(token => {
      console.log("FCM:" + token)
      // store fcm token in your server
    });
```

it returns null.  

One thing i noticed in my build is this message:
```
could not detect any version for com.google.android.gms or com.google.firebase, default version: 9.0.0 will be used.
please apply google-services plugin at the bottom of the build file.
Incremental java compilation is an incubating feature.
```

I did put the google services at the bottom.  However, it still builds with no errors.
 
I've also looked at issue #79 but I do not have any other dependencies on GMS in my build.

Not sure where to go from here?

**Comment by tarr11** [comment]
FYI, I also checked on this method:
```
    this.refreshUnsubscribe = FCM.on('refreshToken', (token) => {
      console.log("FCM3:" + token)
      // fcm token may not be available on first load, catch it here
    });

```

But this never gets called.

**Comment by sibelius** [comment]
android or ios?

**Comment by tarr11** [comment]
android

**Comment by tarr11** [comment]
Debugging from Android Studio, this is in the logs:

```
W/InstanceID/Rpc: Failed to resolve REGISTER intent, falling back
W/InstanceID/Rpc: Both Google Play Services and legacy GSF package are missing
D/com.evollu.react.fcm.FIRMessagingModule: Firebase token: null
```

**Comment by tarr11** [comment]
Here's my AVD Emulator

![image](https://cloud.githubusercontent.com/assets/369807/18843271/e5eba6cc-83cc-11e6-89b7-410105ee2ab1.png)

**Comment by sibelius** [comment]
push notification only works on real devices, on iOS and Android

**Comment by tarr11** [comment]
It works (at least, I can get a token) if I use a Google APIs CPU

http://stackoverflow.com/questions/14536595/how-to-download-google-play-services-in-an-android-emulator

![image](https://cloud.githubusercontent.com/assets/369807/18851632/a9f0d4e2-83f1-11e6-8e3d-2b8b0ccf8ebf.png)
