### ISSUE TITLE
opened_from_tray getting wrong result

### ISSUE THREAD

**Issue by alidawud** [evollu/react-native-fcm#133]
**opened_from_tray** is **0** when I click on the banner in foreground

React-Native: 0.33
Device: iOS 10
App running in foreground

**Comment by evollu** [comment]
hmm, how did you manage to show banner when app in foreground?

**Comment by alidawud** [comment]
That's new feature in iOS 10

**Comment by alidawud** [comment]
didReceiveNotificationResponse Will be triggered when I click on banner in foreground

**Comment by evollu** [comment]
I'm assuming you are building that notification with native code. you can add a flag yourself to identify this special notification. I'm currently relying on app status to decide the flag. I'm open to other solutions

**Comment by alidawud** [comment]
Yes I ended up by adding flag.  Just want to see if there are better solutions

**Comment by evollu** [comment]
this feature will be only available for iOS10 right? How do you support iOS 9?

**Comment by alidawud** [comment]
I don't need a head up banner in foreground. So if there is no one in iOS9 I have no plan to add.

My issue was since iOS10 already have head up banner, I wish when I click on. I'll be able to do some actions in the notification listener. So I added my own flat to distinguish between receive notification and click on notification in foreground status.

**Comment by evollu** [comment]
cool
