### ISSUE TITLE
Question - White icon in android

### ISSUE THREAD

**Issue by omair100** [evollu/react-native-fcm#135]
Hi

I have a question regarding the white icon problem in android -- i am sending messages using firebase console (remote notification).  I wanted to know if it's possible to have different icon for notification then the launcher.  Currently the only way for me to change notification icon that works is to change the launcher icon but i want to keep the launcher icon as it is and have a separate notification icon.  Is this possible to achieve if so how?

Best Regards

**Comment by sibelius** [comment]
pass a custom icon inside `notification` part of the payload

```js
const payload = {
   data: {},
   notification: {
       icon: 'ic_notification',
       color: 'green',
    }
}
```

**Comment by omair100** [comment]
Does that work if you send it though firebase console?  I am sure i already tried that but will try again...will let you know?

**Comment by sibelius** [comment]
no, it does not work though firebase console

**Comment by BogdanHossu** [comment]
I am trying even to send to cURL but looks like the icon its not changing ...

**Comment by evollu** [comment]
problem seems solved
