### ISSUE TITLE
getFCMToken undefined?

### ISSUE THREAD

**Issue by BogdanHossu** [evollu/react-native-fcm#136]
Please include following information for better support

What verion of RN and react-native-fcm are you running?
0.33

What device are you using? (e.g iOS9 emulator, Android 6 device)?
Android Simulator

When launching the app im getting a console warning "Possible Unhandled Promise Rejection (id: 0) undefined is not an object (evaluating RNFIRMessaging.getFCMToken). Is there a problem with linking?

**Comment by sibelius** [comment]
there is a problem with linking

**Comment by BogdanHossu** [comment]
Can it be fixed somehow?

**Comment by sibelius** [comment]
yep, just follow the readme instructions for android and ios

check ur MainActivity.java
