### ISSUE TITLE
Build Error: Missing google-services.json file

### ISSUE THREAD

**Issue by mykelaballe** [evollu/react-native-fcm#139]
react-native : 0.32
react-native-fcm : 1.1.0
emulator : Android
![image](https://cloud.githubusercontent.com/assets/22584900/19028398/28d68d70-896e-11e6-8b2e-7badf92aa788.png)

**Comment by willoughby** [comment]
Have you downloaded it and placed it in your android/app folder?

**Comment by mykelaballe** [comment]
hmm i just followed the installation guide of this repo and i cant seem to find that google-services json file. so does that mean that i have to download it manually? if so, where?

btw tnx for the reply much appreciated since this is just my very first github involvement. more power to u

**Comment by willoughby** [comment]
No worries. Yes you need to download a configuration from from Firebase. I assume you linked your android app?

To Fetch the configuration file: 
You need go to your project settings (left menu > click the cog  > project settings)

From there you should see a tab called Cloud Messaging,

**Comment by sibelius** [comment]
@evollu u can close this
