### ISSUE TITLE
Android dependency conflict [DexException]

### ISSUE THREAD

**Issue by andresusanto** [evollu/react-native-fcm#14]
Hi @evollu, thanks for providing this awesome module!

I have a project that used `react-native-google-signin` module. When I added your project (`react-native-fcm`), the project couldn't be compiled and produced the following errors:

```
Error:Gradle: Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/measurement/AppMeasurementContentProvider;

Error:Gradle: Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2
```

I have tried to use `multiDexEnabled true`, however it produces even more conflicts.

Do you have any suggestion to solve this issue? By the way, the `react-native-google-signin` was able to work with `react-native-gcm-push-notification`.

Thanks anyway.

**Comment by evollu** [comment]
looks like this has something to do with gradle or google play library. fcm is depending on 9.0.1 Google service while the other library is depending on 8.+

can you try cleaning the build, update gradle too and play service library?

**Comment by andresusanto** [comment]
Wow, thanks for the insight!
I just updated the google play service from the other library to 9.01 and removed `play-services-measurement`. Now they can work together.

Thanks again!
