### ISSUE TITLE
npm link break?

### ISSUE THREAD

**Issue by tarr11** [evollu/react-native-fcm#142]
Trying to link react-native-fcm, recieve an error:

Repro: clone this repo:  https://github.com/tarr11/fcm_bug

`git clone git@github.com:tarr11/fcm_bug.git`
`cd fcm_bug`
`npm install`
(succeeds)

`react-native link react-native-fcm`
expect success, instead  receive:
```
rnpm-install info Android module react-native-fcm is already linked 
rnpm-install ERR! It seems something went wrong while linking. Error: Expected "/*", "//" or "{" but "<" found. 
Please file an issue here: https://github.com/facebook/react-native/issues
```

**Comment by evollu** [comment]
https://github.com/facebook/react-native/issues/10032
does this help?

**Comment by tarr11** [comment]
You mean `npm uninstall rnpm -g` ?

No, still happens

**Comment by tarr11** [comment]
Feels like it's related to this https://github.com/CocoaPods/CocoaPods/issues/1275

**Comment by tarr11** [comment]
This solved it for me.  Kind of ugly but it works.  

https://github.com/CocoaPods/CocoaPods/issues/1275#issuecomment-22391200
