### ISSUE TITLE
[andriod] RNFIRMessaging.getBadgeNumber() is not a function

### ISSUE THREAD

**Issue by colorfulberry** [evollu/react-native-fcm#145]
* ENV

```RN: 0.33.0, react-native-fcm: 2.3.0, iOS10, Android 6```

* ERROR
```
[IOS] FCM.getBadgeNumber() is correct
[andriod] FCM.getBadgeNumber() throw  RNFIRMessaging.getBadgeNumber() is not a function
```
Then as i see the source code, under [Android] I can't find the define of these two function ` RNFIRMessaging.getBadgeNumber(),  RNFIRMessaging.setBadgeNumber()`

**Comment by sibelius** [comment]
badgeNumber is only for ios

on android u should try this: https://github.com/zo0r/react-native-push-notification#set-application-badge-icon

**Comment by colorfulberry** [comment]
@sibelius  Thanks
