### ISSUE TITLE
Application crashes when going to background

### ISSUE THREAD

**Issue by mykelaballe** [evollu/react-native-fcm#146]
RN: 0.32
FCM: 1.1.0
Emulator: Genymotion, Android 6

![image](https://cloud.githubusercontent.com/assets/22584900/19269028/9683e12e-8fea-11e6-83f7-eb151c59aff8.png)

![image](https://cloud.githubusercontent.com/assets/22584900/19269051/ae65b9fc-8fea-11e6-97f8-c383139a6bcb.png)

As you can see in my screenshots, first in componentDidMount i attached a handler in AppState, second photo is present a local notification using FCM. When i go to background app stops working. Help would really be appreciated

**Comment by evollu** [comment]
local notification is only supported in v2.
