### ISSUE TITLE
How to use click_action?

### ISSUE THREAD

**Issue by mykelaballe** [evollu/react-native-fcm#147]
Guys really need help on this one. How exactly does one make use of click_action? where to put it?

**Comment by tioback** [comment]
Whatever string you put there, you can later use to decide what action you want to call.

Say you have ["asdf", "qwer", "zxcv"] as click actions that can be sent by the server.

On your handler do something like:

    FCM.on("notification", notif => {
      switch (notif.click_action) {
        case "asdf": console.log("Do whatever asdf should do, like a background update that the user doesn't need do know about"); break;
        case "qwer": console.log("Do whatever qwer should do, like show a notification banner"); break;
        case "zxcv": console.log("Do whatever zxcv should do, like open the app and show an image to the user"); break;
      }
    });

Still, there's a [note on the README](https://github.com/evollu/react-native-fcm#behaviour-when-sending-notification-and-data-payload-through-gcm) that tells you to avoid using click_action for this.

**Comment by mykelaballe** [comment]
tnx so much for the reply. i posted 3 questions only 1 got answered hehe

**Comment by tioback** [comment]
Check the README, it says right there that click actions should go on `AndroidManifest.xml` and as a key/value pair for your payload.
