### ISSUE TITLE
FCM in Ignite

### ISSUE THREAD

**Issue by mykelaballe** [evollu/react-native-fcm#148]
Just a question. Can I use this module with Ignite? Ignite has react-native-push-notification, so i was just thinking that this issue #146 might be related to incompatibiilty or might be conflicting with Ignite's integration of react-native-push-notification

**Comment by evollu** [comment]
I haven't tried yet but I think you can. You will need to change some settings in your main project to make disable the react-native-push-notification feature and enable this
