### ISSUE TITLE
Cannot get Badge Number on Android

### ISSUE THREAD

**Issue by tioback** [evollu/react-native-fcm#149]
I called `FCB.getBadgeNumber()` and got the following message: 

    E/ReactNativeJS: undefined is not a function (evaluating 'RNFIRMessaging.getBadgeNumber()')

I'm running RN 0.34.1, react-native-fcm 2.3.0, on a Motorola XT1069 with Android 6.0.
My app was running on the foreground.

I searched the source inside react-native-fcm's android folder, but couldn't find any mention of the word "badge".

Here's my FCM control component:

    import React, { Component } from "react";
    import FCM from "react-native-fcm";
    import uuid from "react-native-uuid";
    export default class PushController extends Component {
      componentDidMount() {
        FCM.requestPermissions();
        FCM.getFCMToken().then(token => {
          console.log("TOKEN (getFCMToken)", token);
        });
        this.notificationUnsubscribe = FCM.on("notification", notif => {
          console.log("Notification", notif);
          let { title, body } = notif;
          FCM.getBadgeNumber().then(number => {
            FCM.presentLocalNotification({
                  id: uuid.v4(),
                  title,
                  body,
                  sound: "default",
                  priority: "normal",
                  click_action: "ACTION",
                  number: number + 1,
                  icon: "appLogo",
                  vibrate: 300,
                  lights: true,
                  show_in_foreground: true
              });
          });
        });
        this.refreshUnsubscribe = FCM.on("refreshToken", token => {
          console.log("TOKEN (refreshUnsubscribe)", token);
        });
      }
      componentWillUnmount() {
        this.refreshUnsubscribe();
        this.notificationUnsubscribe();
      }
      render() {
        return null;
      }
    }

**Comment by sibelius** [comment]
@tioback related to https://github.com/evollu/react-native-fcm/issues/145

check my answer here: https://github.com/evollu/react-native-fcm/issues/145#issuecomment-252633192

getBadgeNumber is iOS only

**Comment by tioback** [comment]
Thanks, @sibelius, I just sent PR #152 that mentions this in the README.
Later I'll see if I can do something about providing this feature for Android, too.
