### ISSUE TITLE
Build Failed: No matching client found for package name 'com.firechat' (firechat is my app name)

### ISSUE THREAD

**Issue by mdrajib001** [evollu/react-native-fcm#150]
Windows, Android App,
RN version:  0.35.0
react-native-fcm Version: 2.3.0

Using my device as emulator.  The app was okay before configuration. Do I need to add my Firebase app name somewhere?  Please help.

Best Regards,
Rajib

**Comment by tioback** [comment]
Check the package you used for your Firebase service and the one you're using for your java classes, they have to match.

**Comment by mdrajib001** [comment]
Hi,
Thank you very much for your reply. But I didn't understand what you mean. I have install firebase using "npm install firebase --save" command. I didn't change any java code without what is mentioned in this repository. 
Which java class I have to change? Can you please explain a bit?

**Comment by tioback** [comment]
I'm not using firebase locally, I used [online](http://console.firebase.google.com).

What I meant for you to do is check the package your `MainActivity.java` and `MainApplication.java` are at. It has to be the same that is mentioned throughout your code.

For instance, `AndroidManifest.xml` has a property `package` in the `manifest` tag that also has to match the FCM config.

On iOS, your bundle id should also match the said package.

Android FCM config can be found in your `google-services.json` file.
iOS FCM config can be found in your GoogleService-Info.plist.

**Comment by mdrajib001** [comment]
I have deleted my current firebase app as it's name was different than my package name. So created new one with same id of app. Now build problem solved. 
I am sending notification from firebase console but it is not showing in my app. do I need to put additional code in my app to show notification from firebase?

**Comment by machintoch1227** [comment]
It's Solved By Me 15/11/2017
Seeing My Video:
https://www.youtube.com/watch?v=ePRcf_IgKc0&feature=youtu.be
Thanks For Watching...

**Comment by Bhavnaharitsa** [comment]
> # It's Solved By Me 15/11/2017
> Seeing My Video:
> https://www.youtube.com/watch?v=ePRcf_IgKc0&feature=youtu.be
> Thanks For Watching...

Thanks a lot, helped a lot! :D

**Comment by machintoch1227** [comment]
> 
> Thanks a lot, helped a lot! :D

You are welcome

**Comment by machintoch1227** [comment]
> 
> 
> > # It's Solved By Me 15/11/2017
> > Seeing My Video:
> > https://www.youtube.com/watch?v=ePRcf_IgKc0&feature=youtu.be
> > Thanks For Watching...
> 
> Thanks a lot, helped a lot! :D

You are welcome! Thank you so much
