### ISSUE TITLE
Scheduling local notifications on Android does not work with ISO date string

### ISSUE THREAD

**Issue by ghuh** [evollu/react-native-fcm#158]
When attempting to schedule local notifications, it does not work on Android (both simulator and actual devices) if an IOS date is used (`new Date().toISOString()`).  However, it does work on iOS (both simulator and actual devices).

The workaround is to use `new Date().getTime()` which works on both Android and iOS.

**Comment by sibelius** [comment]
I think `new Date().getTime()` makes more sense than `toISOString()`

**Comment by ghuh** [comment]
That may be but it is currently documented that both work.  So the fix could be a simple as adjusting the documentation if that is the way people would like to go.

**Comment by sibelius** [comment]
could u please update the docs then?

**Comment by ghuh** [comment]
@evollu is that your preference?

**Comment by evollu** [comment]
I'm using React's built in date converter. I guess the android converter doesn't support ISO string

**Comment by evollu** [comment]
readme updated
