### ISSUE TITLE
iOS app not receiving notifications when in background.

### ISSUE THREAD

**Issue by micopc** [evollu/react-native-fcm#160]
Hi,

The iOS app is not receiving notifications when in background. If i reopened the app the notification is received via FCM.on('notification'), but the notification doesn't appear on the notification center when the app is in background.

Using react-native 0.33 and react-native-fcm 2.3.0
Using Iphone 6 and Ipad 3 with iOS 9.3.5. Working fine in Android.

I've already created development and production certificates, I've tried sending the notification via pusher and it works, so the certificates are alright. I added Push Notifications Capabilities and Background Mode in xcode. I tried adding breakpoints and didReceiveRemoteNotification is triggered but only when the app is opened again.

**Comment by sibelius** [comment]
please double check ur configs in the example of this PR: https://github.com/evollu/react-native-fcm/pull/152

**Comment by sresant** [comment]
I am also seeing these issues on my Iphone 6s device on version 9.3.5.  I am using react-native 0.36 and react-native-fcm 2.3.0

**Comment by sibelius** [comment]
@micopc can u close this?

**Comment by evollu** [comment]
close due to inactivity
