### ISSUE TITLE
Build fails for many reasons

### ISSUE THREAD

**Issue by bernatfortet** [evollu/react-native-fcm#163]
**Using:**
react: 15.3.2
react-native: 0.35.0
react-native-fcm: 2.3.2
XCode 8
ios10 Emulator
CocoaPods 1.0.1

These are the errors I get:
<img width="1440" alt="screen shot 2016-10-15 at 9 50 03 am" src="https://cloud.githubusercontent.com/assets/390010/19413000/b8d437c6-92bd-11e6-8714-ca177508cd8c.png">

Also, I've tried without cocoapods and can't get it to work.
Also, I've tried with and without cocoapods on a fresh RN project and it gives me compilation errors right off the bat.

Thanks!

**Comment by bernatfortet** [comment]
I've done a couple things and the error has changed:
- `pod update`
- `Product > Clean`
- Removed a virtual folder on my project folder that was named "Frameworks" and had two missing links

And then it worked!

But now I get stuck in here:

<img width="1440" alt="screen shot 2016-10-15 at 10 08 27 am" src="https://cloud.githubusercontent.com/assets/390010/19413066/55c328a2-92bf-11e6-89e4-4b7bc59be34c.png">

**Comment by nicholasstephan** [comment]
I ran into exactly this error. I figured out it was a missing `GoogleService-Info.plist` causing the problem. Are you sure you have that file in your project? - My 2c.

**Comment by bernatfortet** [comment]
@nicholasstephan Thank you! That fixed it.

I had it in the folder but it was not referenced.
