### ISSUE TITLE
use APNS to get token

### ISSUE THREAD

**Issue by mykelaballe** [evollu/react-native-fcm#165]
![image](https://cloud.githubusercontent.com/assets/22584900/19450175/fcefb506-94da-11e6-940c-505b4f101119.png)

What does the above photo exactly mean? does that mean for Android apps i can get my token from Firebase while IOS apps i can get from APNS? If so, how? Quite confusing already since the name of the this module is **react-native-fcm** in the first place

**Comment by sibelius** [comment]
the token is the one provided by FCM (Firebase), under the hood it still uses APNS token

**Comment by mykelaballe** [comment]
thanks a lot for the quick response

**Comment by mykelaballe** [comment]
does that mean FCM communicates to APNS?

**Comment by sibelius** [comment]
yep, under the hood

**Comment by sibelius** [comment]
@mykelaballe can we close this?
