### ISSUE TITLE
IOS APNS token is null

### ISSUE THREAD

**Issue by mykelaballe** [evollu/react-native-fcm#166]
RN: 0.32
FCM: 1.1.0
platform: IOS

![whatsapp image 2016-10-18 at 23 51 04](https://cloud.githubusercontent.com/assets/22584900/19485759/a0e1626e-958e-11e6-9fd7-e37c8dca02f7.jpeg)

**Comment by sibelius** [comment]
the push notification is working?

**Comment by mykelaballe** [comment]
no its not, weve already setup the apns certicate and other config

**Comment by sibelius** [comment]
u should upload all certificates (dev and prod) to firebase

make sure `data` and `notification` on push notification payload is correct

**Comment by sibelius** [comment]
please follow this example: https://github.com/evollu/react-native-fcm/pull/152

**Comment by mykelaballe** [comment]
actually even sending from Firebase console cannot receive the push. How to set the `data` and `notification` payloads in Firebase console?

**Comment by bernatfortet** [comment]
Same problem here

I've uploaded both certificates to Firebase:
<img width="972" alt="screen shot 2016-10-22 at 1 48 37 pm" src="https://cloud.githubusercontent.com/assets/390010/19623263/b23f7f50-985e-11e6-92eb-a4135df85b83.png">


I have all certificates ready:
<img width="743" alt="screen shot 2016-10-22 at 2 00 06 pm" src="https://cloud.githubusercontent.com/assets/390010/19623297/ea8132cc-985f-11e6-9a07-f4803eb0b70e.png">

I also have the push notification stuff in order:
<img width="669" alt="screen shot 2016-10-22 at 2 00 25 pm" src="https://cloud.githubusercontent.com/assets/390010/19623298/f6faac5e-985f-11e6-9c6b-8e659707fee5.png">

I still get the same error:
`Failed to fetch APNS token Error Domain=com.firebase.iid Code=1001 "(null)"`

**Comment by evollu** [comment]
@bernatfortet just want to locate the issue. 
1. Have you requested permission in iOS app?
2. Can you try FCM's iOS starter pack to test all the setup are correct?

**Comment by bernatfortet** [comment]
I'll check it 1. and 2. out

But now it's working... So I'm not sure what happened.

**Comment by sibelius** [comment]
@mykelaballe can we close this?

**Comment by ExPHAT** [comment]
I am having this issue too 😕

**Comment by Mikmik5** [comment]
No, still not working here as well

**Comment by evollu** [comment]
@Mikmik5 can you elaborate?

**Comment by yannickoo** [comment]
@evollu I think I'm experiencing the same issue since push notifications work on real devices when using the debug version / TestFlight version but not for the App Store version. I could also retrieve the Firebase token for the user but when trying to send something to them it didn't work.

Both certificates are uploaded in the Firebase backend and are valid.

**Comment by yannickoo** [comment]
You should try to revoke and recreate your certificates – https://github.com/firebase/quickstart-ios/issues/207#issuecomment-272152606 🎉

**Comment by xhidnoda** [comment]
any updates?

i found this in other forums:

If you use Firebase, you have to add in:

With "FirebaseAppDelegateProxyEnabled": NO

TestFlight:
-(void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken {
[[FIRInstanceID instanceID] setAPNSToken:deviceToken type:FIRInstanceIDAPNSTokenTypeSandbox];
}

Production:
-(void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken {
[[FIRInstanceID instanceID] setAPNSToken:deviceToken type:FIRInstanceIDAPNSTokenTypeProd];
}

With "FirebaseAppDelegateProxyEnabled": YES.....in theory this is not necessary..

OTHER SOLUTION..???

Using the correct Project and Target Build Settings as mentioned in This link.
And revoking the existing push certificates and creating a new one completely, and then uploading the new certificate's .p12 file to the Firebase Console.

**Comment by yannickoo** [comment]
@xhidnoda you don't need to set the APNS token manually. It's enough to leave the proxy enabled, Firebase will handle that automatically 😇

**Comment by evollu** [comment]
@yannickoo 👍

**Comment by stefanocapitanio** [comment]
+1
