### ISSUE TITLE
[iOS10] permissions fail

### ISSUE THREAD

**Issue by ssomnoremac** [evollu/react-native-fcm#169]
RN35 and fcm2.3.2
ios 6splus running iOS10
app running in foreground
(also using Auth0 lock)

So close to having the library running on both platforms. Thank you for all the support. On iOS however, when the app first attempts to ask permission, it seems, it suddenly crashes.  

Looks like it's at RNFIRMessaging.m inside the -setBridge method at

```
// For iOS 10 data message (sent via FCM)
  [[FIRMessaging messaging] setRemoteMessageDelegate:self];    <-----------------
```
```
2016-10-19 17:04:42.280: <FIRMessaging/INFO> FIRMessaging library version 1.2.0
2016-10-19 17:04:42.282320 hyrwork[7085:11625329] *** Assertion failure in -[GIPReachability startWithCompletionHandler:](), googlemac/iPhone/Shared/Net/GIPReachability.m:119
2016-10-19 17:04:42.284326 hyrwork[7085:11625329] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'GIPReachability should be used from the main thread'
```

**Comment by ssomnoremac** [comment]
Ahh, I found it. I was following [tribeez example](https://github.com/antoinerousseau/tribeez/blob/master/ios/tribeez/AppDelegate.m) a bit too closely and ended up with two `return YES` statements, the first of which prevented the`[FIRApp configure]` from happening. I'm cross-platform now! And A LOT more familiar with the iOS side of things now.

**Comment by ignivaravinderrikhi** [comment]
@ssomnoremac Hey I am facing same issue 

"react-native": "0.47.0",
"react-native-fcm": "9.3.0"

and 

FirebaseAnalytics 4.0.2
FirebaseCore 4.0.4 
FirebaseInstanceID 2.0.0
FirebaseMessaging 2.0.0

After successful installation I use 
FCM.requestPermissions()

To ask for permissions after the pop up appears the app suddenly crashes . 
Can you please elaborate your solution I am unable to resolve it .

Thank you

**Comment by evollu** [comment]
@ignivaravinderrikhi check you xcode log see the crash reason.

**Comment by skasanibanyan** [comment]
https://github.com/evollu/react-native-fcm/issues/690

@ignivaravinderrikhi Same issue here. Any solution you have got?

**Comment by skasanibanyan** [comment]
@ignivaravinderrikhi I have the same issue. Any solution u have got?
https://github.com/evollu/react-native-fcm/issues/690

Tried testing with AdHoc provision profile as well and we are still facing the same issue
