### ISSUE TITLE
[iOS] issue with foreground and background notif

### ISSUE THREAD

**Issue by good2hear** [evollu/react-native-fcm#170]
RN 0.34 , react-native-fcm 2.3.2
tested from iphone 5s with iOS 10 

Hi there, I've tested receiving notification for foreground and background on ios
but having some issue with both 
### foreground:

It works fine (receive message right away) for the first time I install the app on the phone.
But then when I make some changes on code and run it again from xcode, messages are not received right away for the first time; they are received when I reopen the app (after pressing home button) and from then they work fine. 
If I delete the app on the phone and install again, it works fine 
### background:

When message was sent from firebase console, push msg shows up on device 
but when it was sent from server, push msg won't show up (it goes to FCM.on('notification') in code and prints console log from there though)

any comments will be appreciated!

**Comment by dragfire** [comment]
+1
I'm having the same issue.
Payload does not contain `gcm.message_id`.

**Comment by sibelius** [comment]
@dragfire  check this https://github.com/evollu/react-native-fcm#behaviour-when-sending-notification-and-data-payload-through-gcm

> NOTE: it is recommended not to rely on data payload for click_action as it can be overwritten (check this).

@good2hear  can we close this ?

**Comment by good2hear** [comment]
@sibelius yeap! thanks for reply!
