### ISSUE TITLE
Error: "didReceiveRemoteNotification:fetchCompletionHandler: but the completion handler was never called"

### ISSUE THREAD

**Issue by bourgois** [evollu/react-native-fcm#173]
What version of RN and react-native-fcm are you running?
RN 0.35
react-native-fcm 2.3.2
FirebaseMessaging 1.2.0 

What device are you using?
iphone 6plus with ios 9.3.3

My issue is that if I am in the background and receive a notification, I click, it opens the application in foreground and I get: "didReceiveRemoteNotification:fetchCompletionHandler: but the completion handler was never called"

My ios code is like in the readme:
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(nonnull NSDictionary *)userInfo fetchCompletionHandler:(nonnull void (^)(UIBackgroundFetchResult))completionHandler{
  [[NSNotificationCenter defaultCenter] postNotificationName:FCMNotificationReceived object:self userInfo:userInfo];
  completionHandler(UIBackgroundFetchResultNoData);
  }

My RN code is:
componentDidMount() {
    this.notificationUnsubscribe = FCM.on('notification', (notif) => {
      console.log('Notif:', JSON.stringify(notif));
      if (notif.action && notif.action === 'refresh') {
        console.log("Entering in notification: on refresh");
        this._onRefresh();
      }
    });

I don't even get the  "console.log('Notif:', JSON.stringify(notif));"....
It works on Android!

Any ideas what could be the issue?
I tried updating to latest firebase but then I break everything due to this issue: https://github.com/evollu/react-native-fcm/issues/143#issuecomment-252178914
And the solution proposed seems to break other pods... So I am not looking forward upgrading!

Thanks :)

**Comment by bourgois** [comment]
More infos: on an iphone 6 with ios 10, I get a similar error BUT FCM.on does work !
The message in this case is:
"Warning: UNUserNotificationCenter delegate received call to -userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler: but the completion handler was never called."

**Comment by sibelius** [comment]
you should use `FCM.getInitialNotification().then(notif=>console.log(notif));` to get the notification when ur app is in background

**Comment by evollu** [comment]
@bourgois is this issue still happening?

**Comment by bourgois** [comment]
No. I was able to move to 2.5.3. Don't really know what solved the issue, but thanks!
