### ISSUE TITLE
iOS FCM.getFCMToken() returns undefined for token

### ISSUE THREAD

**Issue by KBepo** [evollu/react-native-fcm#174]
As said in title, after following instructions, and successfully implementing in android app, tried it for iOS aswell. Followed instructions for iOS and managed to build it successfully but when using:

`FCM.getFCMToken().then(token => {
            console.log(token);
        });`

For output in console I get 'undefined'. I would really appreciate if someone could help me because I get no errors and everything works fine.

I'm using xcode 8.0 and react native 0.35.0. The only thing I didn't try yet was to enable in capabilities "push notifications" (not sure if it would impact token generation) which I will try tomorrow but that would be last thing that came on my mind.

So if someone has had similar issue and resolved it I would really appreciate it. Thanks in advance.

**Comment by KBepo** [comment]
Hello once again,

Tracked down the issue as it shows only on iOS v10.0. On 9.3 I can get token. But firebase console returns that the token is invalid. I get no other error what so ever

**Comment by KBepo** [comment]
Got that sorted out aswell. Now i'm getting no errors in firebase console but still not receiving notifications. Don't know what's problem. Followed all instructions and repeated steps.

**Comment by joshloo** [comment]
@kBepo , may I know what did you do to sort it out? I have similar problem.

**Comment by KBepo** [comment]
@joshloo : my browser was parsing it wrong the token was actually okay. Parsed it manually and got it correct

**Comment by MaheshNandam** [comment]
@evollu ,

Even I'm facing this issue with FCM.getFCMToken() is undefined token value, please look into this issue.
My Package:
		"react": "16.0.0",
		"react-native": "0.50.4",
		"react-native-fcm": "^10.0.3",

**Comment by evollu** [comment]
@MaheshNandam try the Firebase's example project and see if you can get token.
mostly it is just glitch from firebase?

**Comment by MaheshNandam** [comment]
Updated the AppDelegate.h and AppDelegate.m files from https://github.com/evollu/react-native-fcm#shared-steps, working fine.

Thank you @evollu.

**Comment by evollu** [comment]
cool
