### ISSUE TITLE
RNFIRMessaging has no setter or ivar for its bridge, which is not permitted

### ISSUE THREAD

**Issue by danawhite** [evollu/react-native-fcm#175]
After installing the library, I am encountering the following error which has me stuck:

**RNFIRMessaging has no setter or ivar for its bridge, which is not permitted.**

After a quick Google search, I came across what seems to be a similar, unresolved issue with your react-native-gcm-android library. 

I looked into the setBridge method, but cannot seem to figure out the root of the issue. Any idea as to what could be the cause of the error? Thanks.

RN@0.34.1 
react-native-fcm@2.3.2
Devices: iOS 10 simulator, iPhone 6
App is running in foreground

**Comment by evollu** [comment]
it is possible that setBridge function threw an error. Can you add break point in the setBridge function and see that happens?
