### ISSUE TITLE
Support DeleteInstanceId?

### ISSUE THREAD

**Issue by tarr11** [evollu/react-native-fcm#176]
I have a situation where, when a user logs out from my app, I would like it to deregister in Firebase.

It looks like there's a method here for this?

https://firebase.google.com/docs/reference/android/com/google/firebase/iid/FirebaseInstanceId.html#deleteInstanceId()

Would it be possible for FCM to support this feature of Firebase?

**Comment by evollu** [comment]
I think `deleteToken` is a better fit here. Thoughts?
