### ISSUE TITLE
Batchno Is not properly updating

### ISSUE THREAD

**Issue by rengasahusoft** [evollu/react-native-fcm#178]
Hi 
I am using fcm version 4.3.2
React native 0.34.1
Ios 10

Whenever new notification arrives batch no is not updating it is always one
i use this `FCM.setBadgeNumber();` to set batchno configuration

**Comment by evollu** [comment]
Are you saying when notification arrives, the badge number doesn't increment automatically?
Yes you have to manually update badge number in AppDelegate remote notification handler function. That is by Apple's design

**Comment by rengasahusoft** [comment]
@evollu Can you help me setup exact obj c code for batch no. Is it documented?

**Comment by evollu** [comment]
http://stackoverflow.com/questions/6424938/apple-push-notification-badge-number
