### ISSUE TITLE
 error: cannot find symbol  - new FIRMessagingPackage(getIntent())

### ISSUE THREAD

**Issue by Przemocny** [evollu/react-native-fcm#18]
Hey, i want to use your react-native-fcm in my app. 
there are only react-native and your react-native-fcm. 
I made all steps from readme, but i cant build app.
paste error:

../../../MainActivity.java:47: error: cannot find symbol
            new FIRMessagingPackage(getIntent())
                ^
  symbol:   class FIRMessagingPackage
  location: class MainActivity

**Comment by aitorMarrero** [comment]
Add import com.evollu.react.fcm.FIRMessagingPackage; in the top of MainActivity

**Comment by evollu** [comment]
rnpm show add this import automatically. @Przemocny is your issue solved?

**Comment by Przemocny** [comment]
solved
