### ISSUE TITLE
Question - Get user's location on remote notification

### ISSUE THREAD

**Issue by kevando** [evollu/react-native-fcm#180]
First off, this package is awesome.

I am wondering if I can run some react-native code when a user gets a remote notification. Am I able to run something from the FCM library when `didReceiveRemoteNotification` gets called?

**Comment by kevando** [comment]
This function gets called when I do a remote push and the app is open:

```FCM.on('notification', (notif) => { // push some user data to my server```


I would like the ability to run a react-native function like this when the app is closed. Is that possible? Am I going about this in the wrong way?

**Comment by evollu** [comment]
you can't run JS code when app is closed. I suggest building it in native code if the notification is that advanced

**Comment by kevando** [comment]
Thats the thing, I am able to run js code when the app is closed when I track the user's location using this library

https://github.com/transistorsoft/react-native-background-geolocation

But it sucks because that is a huge permission ask from the user, especially when I don't need background tracking. I just want to know their location when I send them a push notification.

**Comment by evollu** [comment]
took a look at the repo you referred. It only works when app is in background rather than not running at all. Is this what you want?

**Comment by kevando** [comment]
Forgive my ignorance, I know very little about native code.

I'm creating a [game](http://giphy.com/gifs/3oz8xs9inPd1sPN3cA) where users fire 'missiles' at each other, essentially guessing where the other person is. So as I see it, I only need to know the user's location at the moment they get fired at (so I can determine if the aggressor guessed correctly).

Does that make sense? I may be going about this a totally wrong way.

**Comment by evollu** [comment]
what happens if user killed app? You can't access GPS anyhow if the app is not running at all

**Comment by kevando** [comment]
hmm. I only have 5 testers, so I guess that just never happened. If they kill the app, I suppose I would lose that gps access.

**Comment by evollu** [comment]
if you only want to use GPS info in background, you can send notification with only data property, then in JS code fetch GPS and build local notification

**Comment by sibelius** [comment]
@kevando how did u solved ur problem?

**Comment by kevando** [comment]
@sibelius I had to enable background location tracking to get this to work.

**Comment by evollu** [comment]
i guess it is the only solution
