### ISSUE TITLE
Token generated in simulator but undefined for device

### ISSUE THREAD

**Issue by KBepo** [evollu/react-native-fcm#184]
Hello.

Had problems with generating token on different platforms but got it sorted out.

Problem which I'm facing now is that when running my code on simulator I get normal token on every iPhone and every iPad, but once I archive it and install it on device i get undefined for token.

I'm using react native 0.35.0 and iOS 9.3.5.

Any help would be highly appreciated.

Best regards.

**Comment by sibelius** [comment]
u should ask fro permission

**Comment by KBepo** [comment]
@sibelius I did ask for permission with:
`FCM.requestPermissions();`

**Comment by KBepo** [comment]
Looks like i got this sorted out by implementing firebase with non cocoapod approach.
