### ISSUE TITLE
Getting notifications but they aren't showing trough notification center

### ISSUE THREAD

**Issue by KBepo** [evollu/react-native-fcm#185]
Please include following information for better support

What verion of RN and react-native-fcm are you running?
0.35.0
latest

What device are you using? (e.g iOS9 emulator, Android 6 device)?
iPad mini 9.3.5

Is your app running in foreground, background or not running?
Both

Advanced:
Have you tried adding break point in native handlers to see if message gets delivered?
It does get delivered.

So. I've been able to send notifications but they aren't showing in notification center. Once I press home button and app goes to background console output says disconnected from FCM and once I enter application I get connected to FCM. I've sent notification trough Postman and firebase returned success. I did manage to catch notifcation on reopening app and when in foreground but for some reason I don't get them in notification center.

Any help would be highly appreciated! Thanks in advance.

**Comment by frmrgr** [comment]
I faced the same behaviour when I forgot to configure push notifications in the app. That is:
1) create APNS certificates,
2) upload p12 files to Firebase console in messaging tab,
3) actually turn on Push stuff in XCode and itunes.
I don't know why app received data from firebase at all, but it did, without notification in status bar.

**Comment by KBepo** [comment]
Yeah tnx for your input I already solved my problem but forgot to close it.

**Comment by almadsen** [comment]
Having same problem, so what do you mean by - actually turn on Push stuff in itunes?

**Comment by frmrgr** [comment]
@almadsen It's googlable, step 12 [here](http://quickblox.com/developers/How_to_create_APNS_certificates).

**Comment by almadsen** [comment]
You mean iTunes connect I guess.
But still, I  believe I've got all my ducks in a row, but still no push notifications.

**Comment by savioseb** [comment]
I misunderstood `FirebaseAppDelegateProxyEnabled ` and set it to `NO` which blocked notifications from showing up

**Comment by George-Tony** [comment]
@frmrgr how did you resolved "I don't know why app received data from firebase at all, but it did, without notification in status bar."  I'm having the same issue in iOS 11.2.1 and XCode 9
