### ISSUE TITLE
Background notifications management

### ISSUE THREAD

**Issue by EmaSciacca** [evollu/react-native-fcm#187]
React native 0.34
react-native-fcm 2.3.0
Real android device with 5.1 OS version (Lollipop)

Hi,

I would like to achieve the following thing:

When the application is running in background and the user receives multiple notifications, if he/she opens the app again without pressing any banner, each banner should disappear and the app should be updated based on the data received through the notifications.
Is there a possible way to achieve this?

Now if I open the app without pressing one banner (just taking it from background to foreground) no banner disappears and the app does not update.

**Comment by evollu** [comment]
try `cancelAllLocalNotifications`

**Comment by EmaSciacca** [comment]
Your solution works only if the app is closed. When the app is in background I have the same behaviour. How can I call `cancellAllLocalNotifications` when the app is resumed?

**Comment by EmaSciacca** [comment]
Sorry, I resolved using AppState. However, I can clean all banners but I cannot figure out how to retrieve notifications data when the app is in background or is closed. Is there a way to achieve that?

**Comment by evollu** [comment]
you can call `getScheduledLocalNotifications` and it returns a promise.
However, you have to write native code to handle when app is not running at all.

**Comment by evollu** [comment]
close due to inactivity
