### ISSUE TITLE
EXC_BAD_INSTRUCTION error.

### ISSUE THREAD

**Issue by Arkanine** [evollu/react-native-fcm#188]
Hello,
When I add [FIRApp configure]; to AppDelegate.m file I get 
thread 1: EXC_BAD_INSTRUCTION (code=EXC_i386_INVOP, subcode=0x0) in main.m
error:

![screen shot 2016-11-08 at 19 51 25](https://cloud.githubusercontent.com/assets/5641601/20110370/cd446afe-a5ec-11e6-929b-3668954a0ada.png)

RN - 0.32.1
react-native-fcm - 2.3.2

Please help me figure out what is the cause of this error.

**Comment by tcpickard94** [comment]
+1  RN - 0.36.1 though

**Comment by evollu** [comment]
@Arkanine please let me know if your issue is fixed

**Comment by Arkanine** [comment]
@tcpickard94 thank you, this helps me to fix error!
@evollu issue resolved. Thank you for the great module!

**Comment by sibelius** [comment]
@Arkanine can we close this?

**Comment by Arkanine** [comment]
@sibelius sure, you can close it.

**Comment by anthonyjuan** [comment]
Hi, I've added it the GoogleService-Info.plist manually, but I still get the error. Is it because I have two GoogleService-Info.plist ? I got two GoogleService-Info.plist one for GoogleSignIn and the other is for fcm

**Comment by evollu** [comment]
@anthonyjuan the latest plist should contain info for both fcm and GoogleSignIn.
