### ISSUE TITLE
[Android] FIRMessaging is not available

### ISSUE THREAD

**Issue by aakashlpin** [evollu/react-native-fcm#19]
Getting the error - `undefined is not an object (evaluating FIRMessaging.initialData)`

Any cues on getting this going?

**Comment by aakashlpin** [comment]
FWIW, here's the repo. Any help appreciated! :) https://github.com/Cheapass/droid/commit/5a97e7b4c6e2ce6ecb37098d22168d723e8eefa3

**Comment by aakashlpin** [comment]
Got it working! Never mind :)

**Comment by Tiagojdferreira** [comment]
What was your problem ? I am having the same issue when building on emulator, but not when doing an assembleRelease

**Comment by aakashlpin** [comment]
@Tiagojdferreira in my case it was due to the presence of 2 conflicting adb versions (I had installed Genymotion at first and Android Studio later).

However, I encountered it again when integrating with https://github.com/alinz/react-native-share-extension 

I had to do this to make it work then - 
```
if (FIRMessaging) {
  FCM.initialData = FIRMessaging.initialData;
  FCM.initialAction = FIRMessaging.initialAction;
}
```

**Comment by antoinerousseau** [comment]
I don't have conflicting adb versions and I'm not using the share extension, but I do have this issue, `FIRMessaging` remains undefined in my app...
Any idea?
Here is my build:

```
Building and installing the app on the device (cd android && ./gradlew installDebug...
google-services plugin could not detect any version for com.google.android.gms or com.google.firebase, default version: 9.0.0 will be used.
please apply google-services plugin at the bottom of the build file.
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:react-native-fcm:compileLint
:react-native-fcm:copyReleaseLint UP-TO-DATE
:react-native-fcm:preBuild UP-TO-DATE
:react-native-fcm:preReleaseBuild UP-TO-DATE
:react-native-fcm:checkReleaseManifest
:react-native-fcm:preDebugAndroidTestBuild UP-TO-DATE
:react-native-fcm:preDebugBuild UP-TO-DATE
:react-native-fcm:preDebugUnitTestBuild UP-TO-DATE
:react-native-fcm:preReleaseUnitTestBuild UP-TO-DATE
:react-native-fcm:prepareComAndroidSupportAppcompatV72301Library UP-TO-DATE
:react-native-fcm:prepareComAndroidSupportRecyclerviewV72301Library UP-TO-DATE
:react-native-fcm:prepareComAndroidSupportSupportV42321Library UP-TO-DATE
:react-native-fcm:prepareComFacebookFrescoDrawee0110Library UP-TO-DATE
:react-native-fcm:prepareComFacebookFrescoFbcore0110Library UP-TO-DATE
:react-native-fcm:prepareComFacebookFrescoFresco0110Library UP-TO-DATE
:react-native-fcm:prepareComFacebookFrescoImagepipeline0110Library UP-TO-DATE
:react-native-fcm:prepareComFacebookFrescoImagepipelineBase0110Library UP-TO-DATE
:react-native-fcm:prepareComFacebookFrescoImagepipelineOkhttp30110Library UP-TO-DATE
:react-native-fcm:prepareComFacebookReactReactNative0291Library UP-TO-DATE
:react-native-fcm:prepareComGoogleAndroidGmsPlayServicesBasement921Library UP-TO-DATE
:react-native-fcm:prepareComGoogleAndroidGmsPlayServicesTasks921Library UP-TO-DATE
:react-native-fcm:prepareComGoogleFirebaseFirebaseAnalytics921Library UP-TO-DATE
:react-native-fcm:prepareComGoogleFirebaseFirebaseAnalyticsImpl921Library UP-TO-DATE
:react-native-fcm:prepareComGoogleFirebaseFirebaseCommon921Library UP-TO-DATE
:react-native-fcm:prepareComGoogleFirebaseFirebaseCore921Library UP-TO-DATE
:react-native-fcm:prepareComGoogleFirebaseFirebaseIid921Library UP-TO-DATE
:react-native-fcm:prepareComGoogleFirebaseFirebaseMessaging921Library UP-TO-DATE
:react-native-fcm:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:react-native-fcm:prepareReleaseDependencies
:react-native-fcm:compileReleaseAidl UP-TO-DATE
:react-native-fcm:compileReleaseRenderscript UP-TO-DATE
:react-native-fcm:generateReleaseBuildConfig UP-TO-DATE
:react-native-fcm:generateReleaseAssets UP-TO-DATE
:react-native-fcm:mergeReleaseAssets UP-TO-DATE
:react-native-fcm:generateReleaseResValues UP-TO-DATE
:react-native-fcm:generateReleaseResources UP-TO-DATE
:react-native-fcm:mergeReleaseResources UP-TO-DATE
:react-native-fcm:processReleaseManifest UP-TO-DATE
:react-native-fcm:processReleaseResources UP-TO-DATE
:react-native-fcm:generateReleaseSources UP-TO-DATE
:react-native-fcm:processReleaseJavaRes UP-TO-DATE
:react-native-fcm:compileReleaseJavaWithJavac UP-TO-DATE
:react-native-fcm:extractReleaseAnnotations UP-TO-DATE
:react-native-fcm:mergeReleaseProguardFiles UP-TO-DATE
:react-native-fcm:packageReleaseJar UP-TO-DATE
:react-native-fcm:compileReleaseNdk UP-TO-DATE
:react-native-fcm:packageReleaseJniLibs UP-TO-DATE
:react-native-fcm:packageReleaseLocalJar UP-TO-DATE
:react-native-fcm:packageReleaseRenderscript UP-TO-DATE
:react-native-fcm:packageReleaseResources UP-TO-DATE
:react-native-fcm:bundleRelease UP-TO-DATE
:react-native-vector-icons:compileLint
:react-native-vector-icons:copyReleaseLint UP-TO-DATE
:react-native-vector-icons:preBuild UP-TO-DATE
:react-native-vector-icons:preReleaseBuild UP-TO-DATE
:react-native-vector-icons:checkReleaseManifest
:react-native-vector-icons:preDebugAndroidTestBuild UP-TO-DATE
:react-native-vector-icons:preDebugBuild UP-TO-DATE
:react-native-vector-icons:preDebugUnitTestBuild UP-TO-DATE
:react-native-vector-icons:preReleaseUnitTestBuild UP-TO-DATE
:react-native-vector-icons:prepareComAndroidSupportAppcompatV72301Library UP-TO-DATE
:react-native-vector-icons:prepareComAndroidSupportRecyclerviewV72301Library UP-TO-DATE
:react-native-vector-icons:prepareComAndroidSupportSupportV42321Library UP-TO-DATE
:react-native-vector-icons:prepareComFacebookFrescoDrawee0110Library UP-TO-DATE
:react-native-vector-icons:prepareComFacebookFrescoFbcore0110Library UP-TO-DATE
:react-native-vector-icons:prepareComFacebookFrescoFresco0110Library UP-TO-DATE
:react-native-vector-icons:prepareComFacebookFrescoImagepipeline0110Library UP-TO-DATE
:react-native-vector-icons:prepareComFacebookFrescoImagepipelineBase0110Library UP-TO-DATE
:react-native-vector-icons:prepareComFacebookFrescoImagepipelineOkhttp30110Library UP-TO-DATE
:react-native-vector-icons:prepareComFacebookReactReactNative0291Library UP-TO-DATE
:react-native-vector-icons:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:react-native-vector-icons:prepareReleaseDependencies
:react-native-vector-icons:compileReleaseAidl UP-TO-DATE
:react-native-vector-icons:compileReleaseRenderscript UP-TO-DATE
:react-native-vector-icons:generateReleaseBuildConfig UP-TO-DATE
:react-native-vector-icons:generateReleaseAssets UP-TO-DATE
:react-native-vector-icons:mergeReleaseAssets UP-TO-DATE
:react-native-vector-icons:generateReleaseResValues UP-TO-DATE
:react-native-vector-icons:generateReleaseResources UP-TO-DATE
:react-native-vector-icons:mergeReleaseResources UP-TO-DATE
:react-native-vector-icons:processReleaseManifest UP-TO-DATE
:react-native-vector-icons:processReleaseResources UP-TO-DATE
:react-native-vector-icons:generateReleaseSources UP-TO-DATE
:react-native-vector-icons:processReleaseJavaRes UP-TO-DATE
:react-native-vector-icons:compileReleaseJavaWithJavac UP-TO-DATE
:react-native-vector-icons:extractReleaseAnnotations UP-TO-DATE
:react-native-vector-icons:mergeReleaseProguardFiles UP-TO-DATE
:react-native-vector-icons:packageReleaseJar UP-TO-DATE
:react-native-vector-icons:compileReleaseNdk UP-TO-DATE
:react-native-vector-icons:packageReleaseJniLibs UP-TO-DATE
:react-native-vector-icons:packageReleaseLocalJar UP-TO-DATE
:react-native-vector-icons:packageReleaseRenderscript UP-TO-DATE
:react-native-vector-icons:packageReleaseResources UP-TO-DATE
:react-native-vector-icons:bundleRelease UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72301Library UP-TO-DATE
:app:prepareComAndroidSupportRecyclerviewV72301Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV42321Library UP-TO-DATE
:app:prepareComFacebookFrescoDrawee0110Library UP-TO-DATE
:app:prepareComFacebookFrescoFbcore0110Library UP-TO-DATE
:app:prepareComFacebookFrescoFresco0110Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipeline0110Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipelineBase0110Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipelineOkhttp30110Library UP-TO-DATE
:app:prepareComFacebookReactReactNative0291Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesBasement921Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesTasks921Library UP-TO-DATE
:app:prepareComGoogleFirebaseFirebaseAnalytics921Library UP-TO-DATE
:app:prepareComGoogleFirebaseFirebaseAnalyticsImpl921Library UP-TO-DATE
:app:prepareComGoogleFirebaseFirebaseCommon921Library UP-TO-DATE
:app:prepareComGoogleFirebaseFirebaseCore921Library UP-TO-DATE
:app:prepareComGoogleFirebaseFirebaseIid921Library UP-TO-DATE
:app:prepareComGoogleFirebaseFirebaseMessaging921Library UP-TO-DATE
:app:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:app:prepareTribeezReactNativeFcmUnspecifiedLibrary UP-TO-DATE
:app:prepareTribeezReactNativeVectorIconsUnspecifiedLibrary UP-TO-DATE
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:processDebugGoogleServices
Parsing json file: /Users/antoine/Sites/tribeez/android/app/google-services.json
:app:generateDebugResources
:app:mergeDebugResources UP-TO-DATE
:app:bundleDebugJsAndAssets SKIPPED
:app:processArmeabi-v7aDebugManifest UP-TO-DATE
:app:processArmeabi-v7aDebugResources UP-TO-DATE
:app:processX86DebugManifest UP-TO-DATE
:app:processX86DebugResources UP-TO-DATE
:app:generateDebugSources UP-TO-DATE
:app:processDebugJavaRes UP-TO-DATE
:app:compileDebugJavaWithJavac UP-TO-DATE
:app:compileDebugNdk UP-TO-DATE
:app:preDexDebug UP-TO-DATE
:app:dexDebug UP-TO-DATE
:app:validateDebugSigning
:app:packageArmeabi-v7aDebug UP-TO-DATE
:app:zipalignArmeabi-v7aDebug UP-TO-DATE
:app:assembleArmeabi-v7aDebug UP-TO-DATE
:app:packageX86Debug UP-TO-DATE
:app:zipalignX86Debug UP-TO-DATE
:app:assembleX86Debug UP-TO-DATE
:app:compileDebugSources UP-TO-DATE
:app:assembleDebug UP-TO-DATE
:app:installDebug
Installing APK 'app-x86-debug.apk' on 'Google Nexus 5X - 6.0.0 - API 23 - 1080x1920 - 6.0'
Installed on 1 device.

BUILD SUCCESSFUL

Total time: 21.7 secs

This build could be faster, please consider using the Gradle Daemon: http://gradle.org/docs/2.4/userguide/gradle_daemon.html
Starting the app on 192.168.56.101:5555 (adb -s 192.168.56.101:5555 shell am start -n net.tribeez/.MainActivity)...
Starting: Intent { cmp=net.tribeez/.MainActivity }
```

**Comment by antoinerousseau** [comment]
OK got it working, had to manually add `new FIRMessagingPackage(),` to my `MainApplication.java` (with `import com.evollu.react.fcm.FIRMessagingPackage;`)

Don't know why `rnpm link` didn't add this one...

**Comment by andfs** [comment]
I'm not able to import FIRMessagingPackage to my MainApplication.java

I got this error:
MainApplication.java:19: error: package com.evollu.react.fcm does not exist
import com.evollu.react.fcm.FIRMessagingPackage;

Can anyone help me?

**Comment by devekoperiOS** [comment]
@andfs I have the same problem. Let me know if you get any solution.

**Comment by andfs** [comment]
@devekoperiOS I've forgot to do this:

react-native link react-native-fcm

**Comment by devekoperiOS** [comment]
Kalpeshs-MacBook-Air:DNTAndroidApp kparikh1984$ react-native run-android
Starting JS server...
Running adb reverse tcp:8081 tcp:8081
Could not run adb reverse: spawnSync adb ENOENT
Building and installing the app on the device (cd android && ./gradlew installDebug...
Incremental java compilation is an incubating feature.
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:react-native-fcm:preBuild UP-TO-DATE
:react-native-fcm:preReleaseBuild UP-TO-DATE
:react-native-fcm:compileReleaseNdk UP-TO-DATE
:react-native-fcm:compileLint
:react-native-fcm:copyReleaseLint UP-TO-DATE
:react-native-fcm:checkReleaseManifest
:react-native-fcm:preDebugAndroidTestBuild UP-TO-DATE
:react-native-fcm:preDebugBuild UP-TO-DATE
:react-native-fcm:preDebugUnitTestBuild UP-TO-DATE
:react-native-fcm:preReleaseUnitTestBuild UP-TO-DATE
:react-native-fcm:prepareComAndroidSupportAppcompatV72301Library UP-TO-DATE
:react-native-fcm:prepareComAndroidSupportRecyclerviewV72301Library UP-TO-DATE
:react-native-fcm:prepareComAndroidSupportSupportV42321Library UP-TO-DATE
:react-native-fcm:prepareComFacebookFrescoDrawee0110Library UP-TO-DATE
:react-native-fcm:prepareComFacebookFrescoFbcore0110Library UP-TO-DATE
:react-native-fcm:prepareComFacebookFrescoFresco0110Library UP-TO-DATE
:react-native-fcm:prepareComFacebookFrescoImagepipeline0110Library UP-TO-DATE
:react-native-fcm:prepareComFacebookFrescoImagepipelineBase0110Library UP-TO-DATE
:react-native-fcm:prepareComFacebookFrescoImagepipelineOkhttp30110Library UP-TO-DATE
:react-native-fcm:prepareComFacebookReactReactNative0310Library UP-TO-DATE
:react-native-fcm:prepareComFacebookSoloaderSoloader010Library UP-TO-DATE
:react-native-fcm:prepareComGoogleAndroidGmsPlayServicesBase900Library UP-TO-DATE
:react-native-fcm:prepareComGoogleAndroidGmsPlayServicesBasement900Library UP-TO-DATE
:react-native-fcm:prepareComGoogleAndroidGmsPlayServicesTasks900Library UP-TO-DATE
:react-native-fcm:prepareComGoogleFirebaseFirebaseAnalytics900Library UP-TO-DATE
:react-native-fcm:prepareComGoogleFirebaseFirebaseAnalyticsImpl900Library UP-TO-DATE
:react-native-fcm:prepareComGoogleFirebaseFirebaseCommon900Library UP-TO-DATE
:react-native-fcm:prepareComGoogleFirebaseFirebaseCore900Library UP-TO-DATE
:react-native-fcm:prepareComGoogleFirebaseFirebaseIid900Library UP-TO-DATE
:react-native-fcm:prepareComGoogleFirebaseFirebaseMessaging900Library UP-TO-DATE
:react-native-fcm:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:react-native-fcm:prepareReleaseDependencies
:react-native-fcm:compileReleaseAidl UP-TO-DATE
:react-native-fcm:compileReleaseRenderscript UP-TO-DATE
:react-native-fcm:generateReleaseBuildConfig UP-TO-DATE
:react-native-fcm:generateReleaseAssets UP-TO-DATE
:react-native-fcm:mergeReleaseAssets UP-TO-DATE
:react-native-fcm:generateReleaseResValues UP-TO-DATE
:react-native-fcm:generateReleaseResources UP-TO-DATE
:react-native-fcm:mergeReleaseResources UP-TO-DATE
:react-native-fcm:processReleaseManifest UP-TO-DATE
:react-native-fcm:processReleaseResources UP-TO-DATE
:react-native-fcm:generateReleaseSources UP-TO-DATE
:react-native-fcm:compileReleaseJavaWithJavac UP-TO-DATE
:react-native-fcm:extractReleaseAnnotations UP-TO-DATE
:react-native-fcm:mergeReleaseProguardFiles UP-TO-DATE
:react-native-fcm:packageReleaseRenderscript UP-TO-DATE
:react-native-fcm:packageReleaseResources UP-TO-DATE
:react-native-fcm:processReleaseJavaRes UP-TO-DATE
:react-native-fcm:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
:react-native-fcm:transformClassesAndResourcesWithSyncLibJarsForRelease UP-TO-DATE
:react-native-fcm:mergeReleaseJniLibFolders UP-TO-DATE
:react-native-fcm:transformNative_libsWithMergeJniLibsForRelease UP-TO-DATE
:react-native-fcm:transformNative_libsWithSyncJniLibsForRelease UP-TO-DATE
:react-native-fcm:bundleRelease UP-TO-DATE
:react-native-push-notification:preBuild UP-TO-DATE
:react-native-push-notification:preReleaseBuild UP-TO-DATE
:react-native-push-notification:compileReleaseNdk UP-TO-DATE
:react-native-push-notification:compileLint
:react-native-push-notification:copyReleaseLint UP-TO-DATE
:react-native-push-notification:checkReleaseManifest
:react-native-push-notification:preDebugAndroidTestBuild UP-TO-DATE
:react-native-push-notification:preDebugBuild UP-TO-DATE
:react-native-push-notification:preDebugUnitTestBuild UP-TO-DATE
:react-native-push-notification:preReleaseUnitTestBuild UP-TO-DATE
:react-native-push-notification:prepareComAndroidSupportAppcompatV72311Library UP-TO-DATE
:react-native-push-notification:prepareComAndroidSupportRecyclerviewV72301Library                                                                              UP-TO-DATE
:react-native-push-notification:prepareComAndroidSupportSupportV42321Library UP-TO-DATE
:react-native-push-notification:prepareComFacebookFrescoDrawee0110Library UP-TO-DATE
:react-native-push-notification:prepareComFacebookFrescoFbcore0110Library UP-TO-DATE
:react-native-push-notification:prepareComFacebookFrescoFresco0110Library UP-TO-DATE
:react-native-push-notification:prepareComFacebookFrescoImagepipeline0110Library                                                                               UP-TO-DATE
:react-native-push-notification:prepareComFacebookFrescoImagepipelineBase0110Library                                                                           UP-TO-DATE
:react-native-push-notification:prepareComFacebookFrescoImagepipelineOkhttp30110Library                                                                        UP-TO-DATE
:react-native-push-notification:prepareComFacebookReactReactNative0310Library UP-TO-DATE
:react-native-push-notification:prepareComFacebookSoloaderSoloader010Library UP-TO-DATE
:react-native-push-notification:prepareComGoogleAndroidGmsPlayServicesBase780Library                                                                           UP-TO-DATE
:react-native-push-notification:prepareComGoogleAndroidGmsPlayServicesGcm780Library                                                                            UP-TO-DATE
:react-native-push-notification:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:react-native-push-notification:prepareReleaseDependencies
:react-native-push-notification:compileReleaseAidl UP-TO-DATE
:react-native-push-notification:compileReleaseRenderscript UP-TO-DATE
:react-native-push-notification:generateReleaseBuildConfig UP-TO-DATE
:react-native-push-notification:generateReleaseAssets UP-TO-DATE
:react-native-push-notification:mergeReleaseAssets UP-TO-DATE
:react-native-push-notification:generateReleaseResValues UP-TO-DATE
:react-native-push-notification:generateReleaseResources UP-TO-DATE
:react-native-push-notification:mergeReleaseResources UP-TO-DATE
:react-native-push-notification:processReleaseManifest UP-TO-DATE
:react-native-push-notification:processReleaseResources UP-TO-DATE
:react-native-push-notification:generateReleaseSources UP-TO-DATE
:react-native-push-notification:compileReleaseJavaWithJavac UP-TO-DATE
:react-native-push-notification:extractReleaseAnnotations UP-TO-DATE
:react-native-push-notification:mergeReleaseProguardFiles UP-TO-DATE
:react-native-push-notification:packageReleaseRenderscript UP-TO-DATE
:react-native-push-notification:packageReleaseResources UP-TO-DATE
:react-native-push-notification:processReleaseJavaRes UP-TO-DATE
:react-native-push-notification:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
:react-native-push-notification:transformClassesAndResourcesWithSyncLibJarsForRelease                                                                          UP-TO-DATE
:react-native-push-notification:mergeReleaseJniLibFolders UP-TO-DATE
:react-native-push-notification:transformNative_libsWithMergeJniLibsForRelease UP-TO-DATE
:react-native-push-notification:transformNative_libsWithSyncJniLibsForRelease UP-TO-DATE
:react-native-push-notification:bundleRelease UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72311Library UP-TO-DATE
:app:prepareComAndroidSupportRecyclerviewV72301Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV42321Library UP-TO-DATE
:app:prepareComFacebookFrescoDrawee0110Library UP-TO-DATE
:app:prepareComFacebookFrescoFbcore0110Library UP-TO-DATE
:app:prepareComFacebookFrescoFresco0110Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipeline0110Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipelineBase0110Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipelineOkhttp30110Library UP-TO-DATE
:app:prepareComFacebookReactReactNative0310Library UP-TO-DATE
:app:prepareComFacebookSoloaderSoloader010Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesBase900Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesBasement900Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesGcm900Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesIid900Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesTasks900Library UP-TO-DATE
:app:prepareComGoogleFirebaseFirebaseAnalytics900Library UP-TO-DATE
:app:prepareComGoogleFirebaseFirebaseAnalyticsImpl900Library UP-TO-DATE
:app:prepareComGoogleFirebaseFirebaseCommon900Library UP-TO-DATE
:app:prepareComGoogleFirebaseFirebaseCore900Library UP-TO-DATE
:app:prepareComGoogleFirebaseFirebaseIid900Library UP-TO-DATE
:app:prepareComGoogleFirebaseFirebaseMessaging900Library UP-TO-DATE
:app:prepareDNTAndroidAppReactNativeFcmUnspecifiedLibrary UP-TO-DATE
:app:prepareDNTAndroidAppReactNativePushNotificationUnspecifiedLibrary UP-TO-DATE
:app:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:processDebugGoogleServices
Parsing json file: /Users/kparikh1984/Downloads/DNT/DNTAndroidApp/android/app/google-services.json
:app:generateDebugResources
:app:mergeDebugResources UP-TO-DATE
:app:bundleDebugJsAndAssets SKIPPED
:app:processDebugManifest UP-TO-DATE
:app:processDebugResources UP-TO-DATE
:app:generateDebugSources UP-TO-DATE
:app:compileDebugJavaWithJavac UP-TO-DATE
:app:compileDebugNdk UP-TO-DATE
:app:compileDebugSources UP-TO-DATE
:app:prePackageMarkerForDebug
:app:transformClassesWithDexForDebug UP-TO-DATE
:app:mergeDebugJniLibFolders UP-TO-DATE
:app:transformNative_libsWithMergeJniLibsForDebug UP-TO-DATE
:app:processDebugJavaRes UP-TO-DATE
:app:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
:app:validateDebugSigning
:app:packageDebug UP-TO-DATE
:app:zipalignDebug UP-TO-DATE
:app:assembleDebug UP-TO-DATE
:app:installDebug
Installing APK 'app-debug.apk' on 'Google Nexus 6P - 6.0.0 - API 23 - 1440x2560 - 6.0' for app:debug
Installed on 1 device.

BUILD SUCCESSFUL

Total time: 27.533 secs

This build could be faster, please consider using the Gradle Daemon: https://docs.gradle.org/2.10/userguide/gradle_daemon.html
/bin/sh: adb: command not found
Starting the app (adb shell am start -n com.dntandroidapp/.MainActivity...
Kalpeshs-MacBook-Air:DNTAndroidApp kparikh1984$

**Comment by devekoperiOS** [comment]
I am not familiar with android environment. Please let me know if you are looking for anything else.

**Comment by devekoperiOS** [comment]
Its got linked. Now I am stuck at getting token.

**Comment by andfs** [comment]
So you're luckier than I. My app crashes and closes

**Comment by romanmandryk** [comment]
I had the same issue when trying to use FCM from iOS share extension. I didn't find reason why FIRMessaging is undefined, but this is the fix which at least prevents the app/extension crash - 
https://github.com/evollu/react-native-fcm/pull/86

**Comment by andfs** [comment]
@romanmandryk I'm not using IOS share extensions. My app crashes in android. But I'll try your solution and I'll give a feedback. I hope that you solution could resolve my problem too. 
thank you so much @romanmandryk

**Comment by antoinerousseau** [comment]
Make sure you follow the full README. the `link` commands adds code to `app/build.gradle`, `settings.gradle` and `MainApplication.java`, and then you need to add extra lines manually to `app/build.gradle`, `build.gradle` and `AndroidManifest.xml` (my final commit looks like [this](https://github.com/antoinerousseau/tribeez/commit/0f40d70ef34049dafb7b6ec2dd50779750298620#diff-7ae5a9093507568eabbf35c3b0665732))

**Comment by antoinerousseau** [comment]
@PoojaVM sorry that project is not public anymore. have a close look at the README you should be fine.

**Comment by PoojaVM** [comment]
@antoinerousseau , I have followed all the steps from README and have made sure to try every solution provided for this particular issue. Still I get the same issue of FIRMessaging being undefined.
Anyway, thanks for letting me know.
