### ISSUE TITLE
PushNotificationIOS?

### ISSUE THREAD

**Issue by almadsen** [evollu/react-native-fcm#190]
Am I supposed to do the instructs on PushNotificationIOS first or does this run without that?
Cause I'm getting loads of errors on compile.

----------------------------------------------
RN: 0.37
iPhone 6, iOS 10 
What verion of RN and react-native-fcm are you running?
What device are you using? (e.g iOS9 emulator, Android 6 device)?
Is your app running in foreground, background or not running?

**Comment by evollu** [comment]
this runs without that
