### ISSUE TITLE
Include of non-modular header inside framework module #2

### ISSUE THREAD

**Issue by btoueg** [evollu/react-native-fcm#194]
The proposed solution for #143 breaks my other pods.

The right fix is probably http://stackoverflow.com/a/28552525/1435156:

 - the location of the imports needs to be changed by the library owner

**Comment by evollu** [comment]
will do

**Comment by ssomnoremac** [comment]
@btoueg, #143 also breaks my other pods but the "right fix" doesn't fix it for me. What needs to be done beyond changing the boolean? I'm not clear on the SO post as I'm not an iOS person.

**Comment by btoueg** [comment]
@ssomnoremac Reverting that https://github.com/evollu/react-native-fcm/commit/bb17da237f9caf737bbda0c9fba4391f0ee0cf51 fixes the issue
@evollu I don't understand what I am losing by commenting this line

My pod:
```
  pod 'Firebase/Messaging', '~> 3.9.0'
  pod 'Firebase/Core', '~> 3.9.0'
  pod 'Firebase/Crash', '~> 3.9.0'
```

**Comment by MatthieuPeyrot** [comment]
I have done a pod update Firebase. Since then i have four "Include of non-modular header inside framework module." and FIRNmessaging.h not found.

I try use_framework in the podfile but it's broking all my other pods.
I try "the right fix", it doesn't work for me as well.

This is blocking for us for now we can't upgrade firesbase anymore...

**Comment by evollu** [comment]
I'm moving the module import into .m file and hope it will fix your issue
try to use branch `fix-194`
note that you need to add
`@import Firebase` in your appDelegate

**Comment by MatthieuPeyrot** [comment]
Still the same for me, the same error.

**Comment by evollu** [comment]
did you remove `use_framework`?

**Comment by MatthieuPeyrot** [comment]
yes because it's broking my other pod

**Comment by evollu** [comment]
do you have any public repo that I can debug with? I'm not using cocoapod in my project

**Comment by evollu** [comment]
seems like use_frameworks! is necessary for swift projects. So is it possible for you to change other pods to support frameworks?

**Comment by MatthieuPeyrot** [comment]
i build an exemple  :
https://github.com/MatthieuPeyrot/Firetest.git

i'm not using swift.

**Comment by the-simian** [comment]
@evollu If you are still looking for an example of a repo this breaks, see this : https://github.com/transistorsoft/react-native-background-geolocation/issues/174

**Comment by the-simian** [comment]
Here is another relevant thread: https://github.com/ParsePlatform/ParseFacebookUtils-iOS/issues/2

**Comment by ssomnoremac** [comment]
try setting this to yes:
```
CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES = YES
```
in the RNFIRMessaging.xcodeproj build settings

**Comment by MatthieuPeyrot** [comment]
it's working when we set yes the CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES 
in react-native-fcm/ios/RNFIRMessaging.xcodeproj

**Comment by evollu** [comment]
@MatthieuPeyrot so adding this flag solves the issue? are you using the master code or fix-194 branch?

**Comment by MatthieuPeyrot** [comment]
yes on the master code , i just set yes to the flag , and it's work.

**Comment by grabcode** [comment]
Setting the flag works for me too. Context: I'm using React Native 0.36.0, with react-native-firebase-analytics 0.36.0.

![screen shot 2017-01-26 at 11 53 57 am](https://cloud.githubusercontent.com/assets/1523620/22316031/717fe1a2-e3be-11e6-9415-c0d110dd9aa3.png)

Also, @evollu, you want to update the README.md because the Firebase settings needs to be stored into `ios/GoogleService-Info.plist`, as oppose to `ios/googleServices-info.plist`.

**Comment by evollu** [comment]
Latest code has been switched to use header file so you don't need to set the flag anymore.
However that has a dependency of 0.40 react native

**Comment by evollu** [comment]
Closing this as it is solved in latest code

**Comment by btoueg** [comment]
Looking at https://github.com/evollu/react-native-fcm/blob/master/ios/RNFIRMessaging.xcodeproj/project.pbxproj#L211 it looks like it's been resolved by flagging `Allow non-modular imports` to true rather than fixing header files

Issue is fixed anyway, thanks !
