### ISSUE TITLE
[ios] Not receiving notifications at all.

### ISSUE THREAD

**Issue by almadsen** [evollu/react-native-fcm#195]
RN: 0.37
react-native-fcm: 2.3.3
iPhone 6  iOS10
Running in foreground and background

I'm not really sure what I'm doing wrong here but I'm not getting any notifications altogether.

Anyone having a project, which is working in the sense of receiving notifications sent from FCM control panel, laying about and is interested in sharing it for pointers in which direction Should go to make it work at all?

**Comment by evollu** [comment]
can you investigate by
1. try native firebase cloud messaging example to make sure you've set up certificates correctly?
2. make sure you have requested permission before receiving notification?
3. curl to fcm api endpoint with specific fcm token and check their response error?

**Comment by evollu** [comment]
close due to inactivity
