### ISSUE TITLE
UILocalNotification deprecated in 10.0.1

### ISSUE THREAD

**Issue by evollu** [evollu/react-native-fcm#196]
I wonder if any of you have encountered error like this:
when setting title for local notification in iOS 10.0.1 the app crashes. Seems Apple introduced another way of creating notifications

**Comment by sibelius** [comment]
@evollu this is the error I'm getting on 10.1

https://github.com/evollu/react-native-fcm/issues/218

**Comment by evollu** [comment]
fixed
