### ISSUE TITLE
Multiple Message in Single Notification Tab - Merge (QUESTION)

### ISSUE THREAD

**Issue by faavictoriano** [evollu/react-native-fcm#197]
React Native Version: v30
react-native-fcm: v1.0.16
Running on Android Device
Running Foreground and background

I would like to ask on how to merge in one notification tab if the sender sent 2 or more message.
If you see the image attached there's 2 notification tab from same sender, i would like to merge in one notification tab in single sender. Thanks

![merge](https://cloud.githubusercontent.com/assets/17818408/20475066/be4d712c-b004-11e6-9987-a00f437b5bc7.jpg)

**Comment by evollu** [comment]
try create notification with same ID?
or delete the old notification by id

**Comment by sibelius** [comment]
@evollu related to this: https://github.com/evollu/react-native-fcm/issues/218#issuecomment-266431726

**Comment by evollu** [comment]
it is related to grouping #259
