### ISSUE TITLE
Dismiss notifications

### ISSUE THREAD

**Issue by iury** [evollu/react-native-fcm#199]
Is the a way to dismiss all the app's push notifications when it become active?

**Comment by evollu** [comment]
cancelAllLocalNotifications

**Comment by iury** [comment]
oh, I thought that one only dismissed local notifications and not pushed ones.
I will try later, thanks for your help

**Comment by sibelius** [comment]
@iury is this solved?

**Comment by iury** [comment]
yes, you may close it

**Comment by windydang26** [comment]
hey @evollu, i use cancelAllLocalNotifications then NotificationType.WillPresent but seem cancelAllLocalNotifications not working. where incorrect?

**Comment by evollu** [comment]
@windydang26 what are you trying to achieve?
