### ISSUE TITLE
Icons do not work on Android

### ISSUE THREAD

**Issue by aindeev** [evollu/react-native-fcm#20]
The `icon` parameter is not being properly set by Firebase 

It tries to set the launcher icon as the backup but that fails as well. During my testing the icon was set to a random system icon like `pause` or `stop`. 

I setup my own services with firebase and then the `icon` property was being read properly.

**Comment by evollu** [comment]
can you share a screenshot of random system icon?

**Comment by evollu** [comment]
if you see a white square in grey circle, it is caused by lolipop requiring a pure white icon. A colorful one will be show as white square. One way around this is setting target version to be lower

**Comment by evollu** [comment]
@aindeev any updates?
