### ISSUE TITLE
working project setup link broken

### ISSUE THREAD

**Issue by java99** [evollu/react-native-fcm#200]
your demo link is now broken

https://github.com/antoinerousseau/tribeez 

please provide another sample project if possible

btw: what is : "replace "fcm.ACTION.HELLO" by the click_action you want to match". 
Which functionality is this? sample?

**Comment by sibelius** [comment]
@evollu can we get this PR in https://github.com/evollu/react-native-fcm/pull/152?

@java99 try the example of this PR: https://github.com/evollu/react-native-fcm/pull/152

**Comment by java99** [comment]
Thank you for your new sample project.

I have a question: could you please elaborate on how to send a push notification to a group of devices? (from a client or from a server - either is possible)

In your sample project I only get local notifications for send data and send data with notification. (first button has no effect). Nowhere on the internet there was anything related to fcm doing so. Only configuring a fcm server system does that, right?

I wonder why no one has the need to send push notifications from one device to other devices. Imagine a chat - i want to notify all people in the group. How to do that?

Please drop us a simple statement , thank you very much!

**Comment by evollu** [comment]
I'm waiting for merge conflict to be solved

**Comment by sibelius** [comment]
@java99 check this out: https://github.com/evollu/react-native-fcm/tree/master/Examples/simple-fcm-client

can u close this?
