### ISSUE TITLE
[Android] Notification from FCM is empty object in callback

### ISSUE THREAD

**Issue by Intelli32** [evollu/react-native-fcm#204]
Hi, I am slowly getting a hang of this but I have encountered a problem which I cannot understand.

When app is in foreground and i send a notification using FCM console I only receive an empty object as the callback parameter for this function:

```
this.notificationUnsubscribe = FCM.on('notification', (notif) => {
      // here "notif" is an empty object
});
```

However if I press the notification banner, the app opens and the "notif" parameter is the object I would expect. What am I doing wrong?

This is in my AndroidManifest.xml:
```
      <receiver android:name="com.evollu.react.fcm.FIRLocalMessagingPublisher"/>
      <!-- react-native-fcm notification services -->
      <service android:name="com.evollu.react.fcm.MessagingService">
        <intent-filter>
          <action android:name="com.google.firebase.MESSAGING_EVENT"/>
        </intent-filter>
      </service>
      <service android:name="com.evollu.react.fcm.InstanceIdService" android:exported="false">
        <intent-filter>
          <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
        </intent-filter>
      </service>
```

Details:
React Native: 0.36.1
react-native-fcm: 2.3.2

**Comment by Intelli32** [comment]
So it seems like the message you send needs a `data` property in the payload or otherwise it will be empty. And since I could not specify the payload with the Firebase Cloud Message Console it showed up empty.

**Comment by evollu** [comment]
foreground only received data property. all notification properties will be ignored and swallowed by the SDK.
