### ISSUE TITLE
Android not receiving notification instantly  

### ISSUE THREAD

**Issue by pankaj-ag** [evollu/react-native-fcm#208]
RN - 0.38.0
RNFC - 2.3.3
Device - Android

Status code is 200 but not receiving the notification immediately. Its taking too much time to show. Even in the examples.

**Comment by evollu** [comment]
this is probably Firebase's problem. Or perhaps you can set priority to high to reduce the time

**Comment by pankaj-ag** [comment]
Yes. I fixed the issue by adding  
  android:enabled="true"
  android:exported="true"
in my messaging service

**Comment by evollu** [comment]
will add to read me

**Comment by evollu** [comment]
hmm I looked up the document, these value are default to be true
https://stuff.mit.edu/afs/sipb/project/android/docs/guide/topics/manifest/service-element.html
