### ISSUE TITLE
google-play-services dependency clash

### ISSUE THREAD

**Issue by JesperLekland** [evollu/react-native-fcm#210]
RN 0.38 - Android devices (emulator/real device)

Having a dependency to ` 'com.google.firebase:firebase-core:9.+'
    &  'com.google.firebase:firebase-messaging:9.+'` is considered bad practice (the '+' specifically). This causes a build problem when used in conjunction with the latest react-native-maps that has a dependency to `'com.google.android.gms:play-services-base:9.4.0' & 
 'com.google.android.gms:play-services-maps:9.4.0'`. This causes a "duplicate .zip entrty" somehow.

**Comment by evollu** [comment]
it is their problem that lock users using 9.4.0
the SDK is 10.0.1 now. ask them to change?

**Comment by Gentlee** [comment]
ok so changing
    compile "com.google.android.gms:play-services-base:9.4.0"
    compile 'com.google.android.gms:play-services-maps:9.4.0'
to
    compile "com.google.android.gms:play-services-base:9.+"
    compile 'com.google.android.gms:play-services-maps:9.+'
in react-native-maps can help

**Comment by evollu** [comment]
actually better change it to 10.+

**Comment by JesperLekland** [comment]
using the "wildcard" '+' is considered bad practice in Android development since it does not guarantee compatibility between minor versions. Try to open the project in Android Studio and you'll immediately see a warning for the '+' usage @evollu

**Comment by evollu** [comment]
as a third party utility module, I don't want to declare what version of play-service to use. There can only be one version of play-services for the whole solution (otherwise it won't compile or it will crash run time). user should declare the version in their main project.

**Comment by JesperLekland** [comment]
@evollu I guess you're right, this should be considered a problem in the Android gradle system. Thanks for your time @evollu. Will close this issue with the comment that aligning the play services versions of your third party modules will probably make the appDex (or duplicate zip entry) go away.
