### ISSUE TITLE
Same as react-native-push-notification ?

### ISSUE THREAD

**Issue by hugohow** [evollu/react-native-fcm#214]
Hello,

I'm not sure what is the difference between react-native-fcm an react-native-push-notification. 
The last one seems adaptable with fcm https://github.com/zo0r/react-native-push-notification/issues/290

**Comment by sibelius** [comment]
different, this uses firebase cloud messaging

not GCM nor apple push system

**Comment by evollu** [comment]
this repo has better local notification support for iOS with repeat interval
also this repo depends on Firebase Cloud message which is introduced in play-service 9. It will replace old GCM library. Integration is slightly different
