### ISSUE TITLE
Undefined FCM Token In ios

### ISSUE THREAD

**Issue by pankaj-ag** [evollu/react-native-fcm#216]
RN - 0.38.0
RNFC - 2.3.3
Device - Android

Android is working fine but in IOS i am getting **undefined** **token** with 
**FCM.getFCMToken().then(token => {
     console.log("TOKEN (getFCMToken)", token);
   }**

**Comment by kevando** [comment]
Do you still get undefined even after user accepts permissions?

You need to have `FCM.requestPermissions();` before you get the token.

**Comment by sibelius** [comment]
@pankaj-ag any progress on this?

**Comment by pankaj-ag** [comment]
Yes I have fixed this by enabling secure http in my project's **entitlements file**.

**Comment by ethan37** [comment]
@pankaj-ag Did you mean disabling https ?

**Comment by georgi-kovachev** [comment]
@pankaj-ag can you let me know what is the setting?

**Comment by pankaj-ag** [comment]
I enabled **push notifications** and **keychain sharing**  in the **capabilities** section and then i was able to get the token.

**Comment by fmelp** [comment]
@pankaj-ag can you copy and paste your entitlements file please? thanks!
