### ISSUE TITLE
How to make sure we're using latest sdk in android?

### ISSUE THREAD

**Issue by atlanteh** [evollu/react-native-fcm#217]
We have a bug that firebase team said they solved in latest version.
In ios we have podfile to check what version we run against..but in android it seems a little more complicated with the gradle dependencies..
If we're using latest react-native-fcm, how do we make sure we also use latest firebase messaging?

**Comment by sibelius** [comment]
@atlanteh check this http://stackoverflow.com/questions/28683327/how-to-check-if-gradle-dependency-has-new-version/28683488#28683488

this is not a problem with this package

please open this question on StackOverflow

**Comment by atlanteh** [comment]
So if I understand correctly, then the firebase dependency is imported by gradle in your component's build.gradle:

> compile 'com.facebook.react:react-native:+'
compile 'com.google.firebase:firebase-core:+'

and the plus sign tells gradle that you request the latest firebase version so if we don't have latest code this means we need to check gradle, or that there's some problem with our code..
Am I correct?

**Comment by sibelius** [comment]
Just check this section https://github.com/evollu/react-native-fcm#android-configuration

> compile 'com.google.firebase:firebase-core:10.0.1' //this decides your firebase SDK version

**Comment by atlanteh** [comment]
Ok, thx.
