### ISSUE TITLE
FirebaseApp not initialized

### ISSUE THREAD

**Issue by rengasahusoft** [evollu/react-native-fcm#219]
Hi
I am using fcm version 2.3.2
React native 0.39
Ios 10

I get this error android

![screenshot_2016-12-06-15-11-24](https://cloud.githubusercontent.com/assets/19145173/20921610/fa6ac7c8-bbca-11e6-980c-7c1a091cb4eb.png)

**Comment by razvan-tudosa** [comment]
I have the same error. Have you manage to solve it yet?

**Comment by aubreywahl** [comment]
had the same problem! You just have to install react-native-fcm, do react-native link, and then follow the instructions here:
https://github.com/evollu/react-native-fcm#android-configuration

**Comment by razvan-tudosa** [comment]
I had so many problems setting up the Push Notifications and tried out so many things that ultimately it worked out somehow, too bad I don't really know what fixed this particular issue.

**Comment by razvan-tudosa** [comment]
I remember putting the `apply plugin: 'com.google.gms.google-services'` in the `android/app/build.gradle` right after the `apply plugin: "com.android.application"` line, being an issue for me.
I had to put it instead at the bottom of the file or at least after declaring `dependencies`.

**Comment by aubreywahl** [comment]
@razvan-tudosa  i think it's pretty easy to copy/paste the configurations in the wrong spot, so that's probably the issue. I also had to update my android SDK, google play services, etc to get it to work.

**Comment by razvan-tudosa** [comment]
I also had some issues with `react-native-maps` whose dependencies were colliding with fcm's. 
I had a wonderful day altogether!

**Comment by sibelius** [comment]
@rengasahusoft could u upgrade to latest version?

do u still have this issue? can we close this?

**Comment by razvan-tudosa** [comment]
Personally I do not have this issue anymore.

**Comment by evollu** [comment]
cool
