### ISSUE TITLE
FCM token is null

### ISSUE THREAD

**Issue by honneygoyal** [evollu/react-native-fcm#22]
FCM.getFCMToken().then(token => {
      console.log(token)
      // store fcm token in your server
    });

In console Null is printed.(For ANDROID didn't tried on IOS)

**Comment by gorangajic** [comment]
Have you tried on the real device?

**Comment by honneygoyal** [comment]
Yes it is working on real device!!
The problem was i didn't had google play serivce installed in Genymotion.
Thank you @gorangajic .
