### ISSUE TITLE
Example app from README is gone

### ISSUE THREAD

**Issue by robinschaaf** [evollu/react-native-fcm#220]
Hello - the example app at https://github.com/antoinerousseau/tribeez listed in README is no longer available.  (looked at the contributor's other repos and didn't see anything else that looked like the same)

**Comment by sibelius** [comment]
here is the example: https://github.com/evollu/react-native-fcm/tree/master/Examples/simple-fcm-client

@robinschaaf can u add a PR to remove this link from the README?

**Comment by robinschaaf** [comment]
@sibelius Sure thing.
