### ISSUE TITLE
Can I schedule local notification and receive it when app is closed?

### ISSUE THREAD

**Issue by chertpong** [evollu/react-native-fcm#224]
I've already try to schedule a notification when app is in foreground and background, it works fine.
but when I close the app, it doesn't wake my app and show notification.
have I done anything wrong?
``` javascript
FCM.scheduleLocalNotification({
      fire_date: moment().add(30,'seconds').toDate().getTime(),
      id: '1111',
      body: 'hello',
      repeat_interval: 'minute',
      count: 3,
      show_in_foreground: true
    });
```
react-native version: 0.33
react-native-fcm: 2.5.0
android: 5.11

**Comment by chertpong** [comment]
it was my fault. I'm using Xiaomi and it has some security function that preventing my app from autostarting itself.

**Comment by zvoncha** [comment]
I am experiencing same issue on Xiaomi when app is in background. Did you solve the issue and how?

**Comment by chertpong** [comment]
@zvoncha Oh, it was 2 months ago, if my memory is good enough. Then, this will be correct solution.
Open Security > Autostart, then select your app and switch on.
please let me know if it can help you

**Comment by zvoncha** [comment]
Thanks @chertpong .

This solved issue.
