### ISSUE TITLE
Can't receive push notification banner on Android.

### ISSUE THREAD

**Issue by kristikristo** [evollu/react-native-fcm#225]
I'm struggling to show the received push notification banner on Android. The notification is received on FCM.on('notification') and I invoke a local notification from that, but when the app is closed/killed, and push notifications come, they are not being displayed as a banner, nor in notification centre.

When the app is in foreground, it works fine with invoking local notification with content from push notification.

Any idea what can I do to solve this?

RN: 0.38.0
react-native-fcm: 2.5.1

Android device on emulator, also on real device (Samsung S6 Edge).

When using debugger, the notification is being delivered, it just look like its silent and not showing the banner.. :S

Thanks in advance

**Comment by stefanwuest** [comment]
Hi @kristikristo, I'm having the same problem. Have you solved it? This may be a duplicate or related to  #182

**Comment by evollu** [comment]
possible dup. reopen if needed
