### ISSUE TITLE
[Update Documentation] - Error Failed to fetch APNS token Error Domain=com.firebase.iid Code=1001 (null)

### ISSUE THREAD

**Issue by TimonSotiropoulos** [evollu/react-native-fcm#229]
I just wanted to suggest an update to the documentation as I have struggled with this issue for the last few hours. 

If you have set the FirebaseAppDelegateProxyEnabled to NO in your info.plist file of your xcode project, you need to specifically set the APNSToken for your Firebase Instance otherwise your app will not receive push notifications as all. You just need to add the following method to your App Delegate:
```
- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken {
  
    // for production
    [[FIRInstanceID instanceID] setAPNSToken:deviceToken type:FIRInstanceIDAPNSTokenTypeProd];
    // for development
    // [[FIRInstanceID instanceID] setAPNSToken:deviceToken type:FIRInstanceIDAPNSTokenTypeSandbox];
}
```
This was outlined in one of the comments from this SO question -> http://stackoverflow.com/questions/37458530/firebase-when-receive-push-notification-did-not-receive-the-popup?rq=1 

Thanks!

**Comment by yannickoo** [comment]
What about this here which automatically set the token type:

```
- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken {
  NSLog(@"APNs token retrieved: %@", deviceToken);

  #if DEBUG
    [[FIRInstanceID instanceID] setAPNSToken:deviceToken type:FIRInstanceIDAPNSTokenTypeSandbox];
  #else
    [[FIRInstanceID instanceID] setAPNSToken:deviceToken type:FIRInstanceIDAPNSTokenTypeProd];
  #endif
}
```

**Comment by yannickoo** [comment]
@evollu can you give some input here? I have mentioned this issue over in #226

**Comment by evollu** [comment]
@TimonSotiropoulos this is clearly state on FCM tutorial. Perhaps I will add a link to that.
@yannickoo I thought it works for you already.

BTW, iOS emulator can't get APNS token

**Comment by yannickoo** [comment]
_@evollu I'm currently struggling with background and remote notifications but local notifications work fine._

**Comment by evollu** [comment]
@yannickoo what device are you using?

**Comment by yannickoo** [comment]
@evollu a real 📱 with iOS 10.2 installed.

**Comment by evollu** [comment]
can you check your xcode log and see if there is log about firebase token? You shouldn't get `Error Failed to fetch APNS token `

**Comment by TimonSotiropoulos** [comment]
@evollu Hmmm, I can't seem to find where it states that in the README docs. Maybe it would be easier if you split out the legacy tutorials into different READMEs? Anyways only a suggestion, if you think it works fine then no problem. I don't have any issues getting this to work atm. Great stuff!

**Comment by evollu** [comment]
@TimonSotiropoulos read me updated. closing this

**Comment by yannickoo** [comment]
@evollu I have disabled `FirebaseAppDelegateProxyEnabled` so maybe this could be the reason for my issue.

**Comment by evollu** [comment]
there is a link to tutorial in readme. You can follow that.
Why do you disable it?

**Comment by yannickoo** [comment]
I guess this was a leftover from my debugging results, everything is working fine now 😇
