### ISSUE TITLE
Pod install - Unknown command: `Firebase/Messaging`

### ISSUE THREAD

**Issue by ahmed1490** [evollu/react-native-fcm#23]
<img width="640" alt="screenshot" src="https://cloud.githubusercontent.com/assets/623510/16419245/43232ffc-3d4d-11e6-88e8-a1ed75b90e93.png">

**Comment by gorangajic** [comment]
The way I have done this is by editing `ios/Podfile`
```
cd ios
pod init
```
open `ios/Podfile` and then add 
```
pod 'Firebase/Messaging'
```

inside your project

my Podfile look like this
```
target 'AwesomeProject' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Predict
  pod 'Firebase/Messaging'

  target 'AwesomeProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```
and then type `pod install`

**Comment by ahmed1490** [comment]
it happens to be stuck on..

<img width="705" alt="screenshot" src="https://cloud.githubusercontent.com/assets/623510/16421585/d1030ee8-3d55-11e6-8cad-7bb4f63bd22d.png">

**Comment by gorangajic** [comment]
same thing happend to me 😄 
try something from here http://stackoverflow.com/questions/23755974/cocoapods-pod-install-takes-forever

**Comment by ahmed1490** [comment]
I dont have existing pods.
looks like I need to wait :D
http://stackoverflow.com/a/21852985/2134720

**Comment by ahmed1490** [comment]
it worked. Only one thing was missing : Patience :D
