### ISSUE TITLE
Module 'FirebaseCore' not found when building project

### ISSUE THREAD

**Issue by martinarroyo** [evollu/react-native-fcm#230]
I have recently upgraded an app from 2.2.0 to 2.5.1 and I have stumbled upon the following error when building `RNFIRMessaging.m`: `Module 'FirebaseCore' not found` when trying to `@import FirebaseCore;`.

Oddly enough, if I replace that line with `@import Firebase;` the build succeeds and the push notifications work. I could also reproduce this issue on a newly created RN application.

I have tested this on React Native 0.39.1, the version of the package is 2.5.1 and I am using CocoaPods 1.1.1. Tested on an iPad Mini.

Have I missed some configuration step, or is this a known issue?

**Comment by sibelius** [comment]
Upgrade firebase native code

**Comment by martinarroyo** [comment]
@sibelius Thank you for your reply. Can you please elaborate a bit more? I followed the steps described in the README file in a clean setup, so I am afraid I do not know what you mean. I also checked the Firebase iOS setup, only to find that the required import is actually `Firebase` and not `FirebaseCore`: https://firebase.google.com/docs/ios/setup#initialize_firebase_in_your_app

**Comment by sibelius** [comment]
U need to download the latest firebase sdk, or run an update/upgrade on cocoapods

**Comment by martinarroyo** [comment]
Apparently that was the issue. I ran `pod update` and `pod repo update` and now it builds correctly. Thanks!

**Comment by lucasbento** [comment]
I just had the same problem, solved it by updating Firebase SDK.

**Comment by arunshan** [comment]
I did `pod update` and `pod redo update` but I am unable to get rid of that error.

**Comment by levsero** [comment]
I'm getting this error when trying to install using the 'Non Cocoapod approach'. Have downloaded the sdk from https://firebase.google.com/docs/ios/setup, the versions are `core 4.8.1`/`messaging 2.0.8`.

**Comment by WundrApp** [comment]
Same here.  I updated manually (I'm not using cocoapods) and couldn't make it work. Still have the issue. Using ReactNative 50

**Comment by ramilushev** [comment]
Any solutions? I'm using latest versions of everything and still `Module 'FirebaseCore' not found`

**Comment by WundrApp** [comment]
@ramilushev I was updating from RN36 to RN50. I solved this by updating the Firebase SDK as mentioned by sibelus. For some reason (I have not the one who implemented it in the first place) I had my framework files in another directory than ios/Frameworks. I deleted the old files and put the new ones in ios/Frameworks and it worked

**Comment by SuperDisk** [comment]
@ramilushev I finally got this to work by replacing the 3 lines in the file with these:

```
#import <FirebaseCore/FirebaseCore.h>
//import FirebaseCore;
#import <FirebaseMessaging/FirebaseMessaging.h>
//import FirebaseMessaging;
//import FirebaseInstanceID;
#import <FirebaseInstanceID/FirebaseInstanceID.h>
```

Not really sure what significance this has, but at least my project builds now.

**Comment by evollu** [comment]
@SuperDisk it is looking by header file vs looking by module.
Perhaps you Firebase modules are not in the module search path

**Comment by uditchandhoke1912** [comment]
Getting this " 'FirebaseCore/FIRApp.h' file not found " even after doing pod update and pod repo update. Any solutions??

**Comment by evollu** [comment]
@somsin can you share an example project with your issue?

**Comment by irajwani** [comment]
Hi, are there any updates on this issue as I'm facing the problem of Module Firebase not found. Then I used the suggested workaround by [Peter](https://github.com/haggholm/react-native-fcm/commit/1538cceb088781610721ce07ef0a7a0ce8a0101a) and now that I'm only trying to import FirebaseCoreMessaging and two others, the app won't build due to the issue this thread is based on. I'm integrating rn-fcm without cocoapods by the way.

**Comment by rachnakhatnawlia** [comment]
![Screenshot 2022-07-15 at 6 08 36 PM](https://user-images.githubusercontent.com/108512827/179224613-baafd3a5-0a8c-41b9-b119-f7dc0125bcd9.png)
in my case i added :
use_frameworks! :linkage => :static

and commented :
use_flipper!()

as shown in images

**Comment by fukemy** [comment]
@rachnakhatnawlia why u commented use_flipper while using React native ?
