### ISSUE TITLE
getFCMToken returns undefined in IOS

### ISSUE THREAD

**Issue by ethan37** [evollu/react-native-fcm#234]
RN 0.39 running in IOS10 simulator. Also tried with RN 0.33 but got same result.

Requesting permissions and sending data from client to server work (request returns code 200), yet i can't getFCMToken and FCM.on('refreshToken') to log the client token. Local notification also doesn't work.

Interesting alerts in the console:
- "Remote notifications are not supported in the simulator" 
- "found no keychain client entitlements"

Any help is greatly appreciated!

**Comment by sibelius** [comment]
> "Remote notifications are not supported in the simulator"

push only works on real device

> "found no keychain client entitlements"

u need GoolgeService-Info.plist

**Comment by ethan37** [comment]
@sibelius GoogleService-Info.plist is there. Is there anything that i have to edit in my project's **entitlements** file which wasn't specified in the readme?

![fcm](https://cloud.githubusercontent.com/assets/21972444/21231381/5e91153a-c2e8-11e6-96a4-0fbac55cf337.png)

**Comment by sibelius** [comment]
u need to have a valid xcode account as well and .entitlements file

**Comment by ethan37** [comment]
@sibelius  Thank you! It worked amazingly! 👍  💯 

Shouldn't this be specified anywhere in the readme?

**Comment by sibelius** [comment]
@ethan37 send a PR to improve the README and the docs

**Comment by ethan37** [comment]
@sibelius https://github.com/evollu/react-native-fcm/pull/239 :)

**Comment by sibelius** [comment]
tks

**Comment by psgganesh** [comment]
You guys just put food for me on my table :), thank you very much, wish i could just contribute at-least via money, if not code; a link to donate would help 🥇

**Comment by MaheshNandam** [comment]
@evollu ,

Facing the same issue as FCM.getFCMToken() is giving undefined token value, please look into this issue ASAP.
My Package:
"react": "16.0.0",
"react-native": "0.50.4",
"react-native-fcm": "^10.0.3",
