### ISSUE TITLE
unregister device/remove token

### ISSUE THREAD

**Issue by Porizm** [evollu/react-native-fcm#236]
react native: 0.39.0
react-native-fcm: 2.4.3
device: both
background & foreground 

hello,

I am trying to unregister fcm notification when the user signs out of his account inside the app.

I don't see any method such as unregister device or remove token...

Thank you in advance :)

**Comment by sibelius** [comment]
@Porizm just deleted the token in ur backend (this is not a good idea).

**Comment by Porizm** [comment]
it wont work if he signed out while he's offline.

**Comment by ethan37** [comment]
@Porizm I'm facing the same issue, 2 possibile solutions:

-Only allow user to log out while he's online. Send request to api.example.com/userID/logout   ->  remove token from backend/database   ->  respond 20). If response == 200, logout() else don't logout.
-Allow user to log out anytime. Send request to backend. If response != 200, store a boolean somewhere (asyncstorage? redux store?) and retry the request as soon as internet connection is available again. I don't think this is pretty though.

The ideal solution would be something like FCM.getNewToken().

How did you guys implement this?

**Comment by Porizm** [comment]
@ethan37 Thanks Ethan.

I think the first solution is the best one for now.
Anyway he doesn't need to sign out offline, because the app is useless without the net.

**Comment by ethan37** [comment]
@Porizm I've opted for the first solution too. 
Can we close this issue, since it's not strictly dependant on react-native-fcm?

**Comment by viv3kk** [comment]
I am also stuck in this situation. My scenario : 
Step 1) User A - log into app and receive notifications.
Step 2) User A - logs out of app and still receive notifications.
Step 3) User B - log into app (same mobile) and receive notifications for both A and B.

I cannot change the subscriber id and want to remove  subscriber id of user A on logout.
