### ISSUE TITLE
Error: Unable to build with error "Undefined symbols for architecture x86_64"

### ISSUE THREAD

**Issue by polovi** [evollu/react-native-fcm#237]
react-native-cli: 2.0.1
react-native: 0.39.2
react: 15.4.1
Firebase sdk: 3.11.0
Xcode: 8.2 (8C38)

building iOS version stoped with errors:

`
Undefined symbols for architecture x86_64:
  "_deflate", referenced from:
      +[NSData(GTMZlibAdditionsPrivate) gtm_dataByCompressingBytes:length:compressionLevel:mode:error:] in GoogleToolboxForMac(GTMNSData+zlib_133a1619f6f498b1872062af2031468a.o)
  "_deflateEnd", referenced from:
      +[NSData(GTMZlibAdditionsPrivate) gtm_dataByCompressingBytes:length:compressionLevel:mode:error:] in GoogleToolboxForMac(GTMNSData+zlib_133a1619f6f498b1872062af2031468a.o)
  "_deflateInit2_", referenced from:
      +[NSData(GTMZlibAdditionsPrivate) gtm_dataByCompressingBytes:length:compressionLevel:mode:error:] in GoogleToolboxForMac(GTMNSData+zlib_133a1619f6f498b1872062af2031468a.o)
  "_inflate", referenced from:
      +[NSData(GTMZlibAdditionsPrivate) gtm_dataByInflatingBytes:length:isRawData:error:] in GoogleToolboxForMac(GTMNSData+zlib_133a1619f6f498b1872062af2031468a.o)
  "_inflateEnd", referenced from:
      +[NSData(GTMZlibAdditionsPrivate) gtm_dataByInflatingBytes:length:isRawData:error:] in GoogleToolboxForMac(GTMNSData+zlib_133a1619f6f498b1872062af2031468a.o)
  "_inflateInit2_", referenced from:
      +[NSData(GTMZlibAdditionsPrivate) gtm_dataByInflatingBytes:length:isRawData:error:] in GoogleToolboxForMac(GTMNSData+zlib_133a1619f6f498b1872062af2031468a.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

**Comment by ethan37** [comment]
See my PR https://github.com/evollu/react-native-fcm/pull/239 . Rebuild your schemes.

**Comment by polovi** [comment]
Remove/add schema didn't work for me but adding `libz.tbd` what i found in your linked issue help

**Comment by ethan37** [comment]
Can this be closed? Maybe we should include to add libz.tbd in the fix documentation PR

**Comment by evollu** [comment]
seems to be a firebase document issue? I don't remember where I got it but libz.tbd is in my solution too
