### ISSUE TITLE
google-services plugin could not detect any version for com.google.android.gms

### ISSUE THREAD

**Issue by ahmed1490** [evollu/react-native-fcm#24]
google-services plugin could not detect any version for com.google.android.gms or com.google.firebase, default version: 9.0.0 will be used.
please apply google-services plugin at the bottom of the build file.

<img width="988" alt="screenshot" src="https://cloud.githubusercontent.com/assets/623510/16426451/5a37ac6a-3d69-11e6-811e-79c0bd2de88b.png">

The other error is related to react-native-maps which I am still trying to figure out

**Comment by gorangajic** [comment]
> Try update your SDK and google play service

**Comment by ahmed1490** [comment]
I am sorry. Not sure. How do you do this?
This is the first time I am running android emulator

**Comment by gorangajic** [comment]
It's done with `Android SDK Manager` you can start it thought Android Studio or if you have android sdk tools in your path you can type `android` or directly it's located in the `/sdk/tools/android`
I think that you need to install or update `Google Play services`

**Comment by ahmed1490** [comment]
posting for any one else who needs it.
gonna try this

<img width="702" alt="screenshot" src="https://cloud.githubusercontent.com/assets/623510/16435524/ee15e212-3d96-11e6-9335-a32369016cd2.png">

**Comment by ahmed1490** [comment]
doesnt complain about this error anymore. Still unable to run android simulator though

**Comment by yuenanto** [comment]
@ahmed1490: Make sure to check **Google Repository** as well.

**Comment by evollu** [comment]
@ahmed1490 looks like the issue is resolved. please reopen if you still have issue with this

**Comment by vokhuyet** [comment]
the same problem with me when i install fcm with react native maps
