### ISSUE TITLE
getInitialNotification is empty

### ISSUE THREAD

**Issue by ethan37** [evollu/react-native-fcm#243]
getInitialNotification() returns {} after opening the app  by clicking a local notification. How to solve?

Running in IOS simulator in debug mode.

**Comment by sibelius** [comment]
try on real device, it does not work on simulator

**Comment by evollu** [comment]
does the initial notification have any content in data payload?

**Comment by ethan37** [comment]
@evollu nope nothing only an empty object {} . Do you have the same behaviour on the simulator??

**Comment by evollu** [comment]
oh since it is emulator, I assume it is local notification?

**Comment by ethan37** [comment]
@evollu Yes, unluckily I don't have a physical device to test this package on at the moment.
This is what i tried:
- run FCM.presentLocalNotification(data) and notification pops up with data.
- close app from multitasking
- click on previous notification, FCM.getInitialNotification() returns empty object literal.

Does the same happen to you on the simulator?

**Comment by evollu** [comment]
it shouldn't be. let me see what is going on. ios only?

**Comment by ethan37** [comment]
I don't know about Android, I've only tested Ios :(

**Comment by ethan37** [comment]
After looking into it a little bit more, I found some recurring errors in the console.
This one deserves more attention, happens when i press a notification with app closed/not running in background:
'''
SpringBoard[515] <Error>: *** -[__NSCFCalendar rangeOfUnit:startDate:interval:forDate:]: date cannot be nil
	Future exception.
	A few of these errors are going to be reported with this complaint, then further violations will simply be ignored.
	Here is the backtrace where this occurred this time (some frames may be missing due to compiler optimizations):
	(
		0   CoreFoundation                      0x00000001167b0ef3 -[__NSCFCalendar rangeOfUnit:startDate:interval:forDate:] + 115
    ...
'''

This one seems to happen everytime i click on a notification:
'''
[DataStore] Could not load data at /Users/devmachine/Library/Developer/CoreSimulator/Devices/8A771825-6A90-41DB-AE60-05993F3AA106/data/Library/SpringBoard/PushStore/com.ghostalk.ios.pushstore
'''

**Comment by evollu** [comment]
looks helpful. this error doesn't show up when you have app running in background?

**Comment by ethan37** [comment]
Yes, sorry, I don't think these two alerts are related to this issue :(

**Comment by evollu** [comment]
@ethan37 fixed in 2.5.5. Please test it out

**Comment by ethan37** [comment]
@evollu You just saved me countless hours of work (and possibly even my life) ❤
