### ISSUE TITLE
[Android] Set default notification icon for all local notifications

### ISSUE THREAD

**Issue by ssomnoremac** [evollu/react-native-fcm#244]
RN@37

I'm clueless as to how to set the default notification icons on Android for my app regardless of if I send a data payload or handle the notification in-app. Having a hard time finding this anywhere. Hoping you can set this in Manifest but it doesn't seem that easy for some reason.

Tried this:

```
<meta-data
                android:name="com.google.firebase.messaging.default_notification_icon"
                android:resource="@drawable/ic_launcher" />
```

didn't work, white square, every time, for a long time now.

**Comment by evollu** [comment]
right. it doesn't work. you need to create an special icon for it.

**Comment by ssomnoremac** [comment]
@evollu , I created one for all drawable folders, called it. ic_stat_onesignal_default.png  but what else needs to be done for it to show? Thanks!

**Comment by evollu** [comment]
in payload add "icon": "ic_stat_onesignal_default"

**Comment by ssomnoremac** [comment]
I'm trying to get it to work with a "notification" payload sent to FCM servers, not "data". Some of our beta testers are showing that there is an icon getting displayed so there must be way to do this.

**Comment by evollu** [comment]
yes, the icon attribute is in notification payload

**Comment by ssomnoremac** [comment]
Been trying that for hours now, no luck. Always get a white square. Android 6. I have the icon and others I've been trying in `android/app/src/main/res/drawable-****dpi/` folders. They are pngs and the right sizes. Also have a folders for debug `android/app/src/debug/res/drawable-****dpi/`

**Comment by evollu** [comment]
is your icon white with transparent background?

**Comment by ssomnoremac** [comment]
no, that could be it. Let me try that. Thanks for hanging with me.

**Comment by ssomnoremac** [comment]
@evollu , you're a lifesaver, I read the sentence in the README but because I've saw icons from our tester that had colors, I didn't believe it.  But they were probably not > lollipop
