### ISSUE TITLE
Can't receive messages from FireBase

### ISSUE THREAD

**Issue by hoangdoan267** [evollu/react-native-fcm#246]
I tried to send messages from my FireBase but nothing happened. Is there anything else that I have to do after follow README tutorial? I already had APNs Certificate and a provisioning profile for my App ID.

Thanks for supporting me.

**Comment by ethan37** [comment]
Running or device or simulator? Can you successfully log your token with FCM.getToken() ?

**Comment by hoangdoan267** [comment]
When I ran on simulator, I could log my token, but in my iOS device, I could not.

**Comment by ethan37** [comment]
Did it return undefined? Did you enable the required capabilites (**Keychain sharing**, *background modes* > **remote notifications** and **push notifications**)?

**Comment by hoangdoan267** [comment]
- On device, it return undefined.
- On Xcode Simulator, it return undefined.
- But on React Native Debugger, it return the string of my Token.
I have enabled all of the required capabilities.  
May I have to follow settings from firebase (https://firebase.google.com/docs/cloud-messaging/ios/client) or just follow your tutorial?

**Comment by ethan37** [comment]
@hoangdoan267 With React Native Debugger do you mean the terminal console?

**Comment by hoangdoan267** [comment]
@ethan37  I mean JS Remote Debugging https://facebook.github.io/react-native/docs/debugging.html which could show us the log on browser like Chrome

**Comment by ethan37** [comment]
@hoangdoan267 Oh, i understand! And you can log into the chrome debugger only while running the app in the simulator?

**Comment by hoangdoan267** [comment]
@ethan37 Yep

**Comment by ethan37** [comment]
@hoangdoan267 Did you enable the permissions with FCM.requestPermissions() ?

**Comment by ethan37** [comment]
@hoangdoan267 https://github.com/evollu/react-native-fcm/issues/184 This looks like the same issue, this guy solved it by installing with the non cocopoad approach

**Comment by hoangdoan267** [comment]
Yes, of course, I had enabled the permission and I installed firebase with the non cocoapod approach.

**Comment by ethan37** [comment]
Oh... sorry to hear that. Maybe try reinstalling with cocoapod?? Otherwise I'm out of solutions, @sibelius or @evollu might help you with this

**Comment by evollu** [comment]
are you testing with the app running foreground?
if yes, you can receive notification without any permission or push notification cert because it is done through websocket

If you are testing with app in background/closed
1. ios emulator won't receive any push notification, only device can
2. the behavior should be the same with debugger running or not. can you verify the behavior again?
3. can you check log in xcode to see if Firebase SDK throws any error?

**Comment by ethan37** [comment]
@hoangdoan267 https://github.com/evollu/react-native-fcm/issues/258 check this

**Comment by hoangdoan267** [comment]
@ethan37  I had reset my project and followed the README exactly, and it worked! Thanks for supporting me.
