### ISSUE TITLE
Troubles with app running in foreground. Simple alert is not shown.

### ISSUE THREAD

**Issue by nezaidu** [evollu/react-native-fcm#247]
RN:
```
"react-native": "^0.38.0"
```
FCM:
```
"react-native-fcm": "^2.4.0"
```
Android 6.1. Galaxy s3 LTE.
App is running in foreground.

So what seems to be the problem. If app is running in foreground, 
```
FCM.on("notification", callback);
```
is triggered. But it is triggered too early, so if i try to show alert in callback, sometimes it's not being shown. Steps to reproduce:
1) Listen to notification. Put 
```
alert("HI!");
```
in your callback.
2) Run app. 
3) Press home.
Open app from your home screen. It will trigger notification with intent
```
android.intent.action.MAIN
```
. Repeat until you don't see an alert.

I tried 
```
console.warn(Date.now());
```
, and i learned that problem is that there is a delay between callback is triggered and an actual
opening of the app. Maybe that alert is not shown is related to the UI thread, like it is able to run simple logic but not ready yet to add a node to the tree (i am not quite familiar with architecture of android, sorry. by node i mean an alert). 
What seemed to me to fix the problem:

```
 // it means app was opened from tray while being in foreground.
 // if app was opened from background, currentstate will be background
 // if from background, it will be active
  if (notification.opened_from_tray && AppState.currentState != "active") {
    let callback = (currentAppState) => {
      if (currentAppState == "active") {
        alert("HI!");
        AppState.removeEventListener('change', callback);
      }
    };

    AppState.addEventListener('change', callback);

  } else {
    alert("HI!");
  }
```
If app is opened from tray, wait till it is actually opened, like for real opened, and only then show an alert. If it is already opened, simply show an alert.

**Comment by evollu** [comment]
glad you figured it out. I will leave the behavior as is right now because seems this is caused by limitation on Alert API. If some one finds navigation or writing to db having trouble I will fix it.
