### ISSUE TITLE
Do we require *Sender ID* for fcm integration, if 'yes' then how to integrate "Sender ID" in my code.

### ISSUE THREAD

**Issue by jvarshaprdxn** [evollu/react-native-fcm#248]
I'm using React-Native version 0.35.0

**Comment by stefanwuest** [comment]
It's in the google-services.json which should be placed in the android/app directory.

**Comment by jvarshaprdxn** [comment]
Thanks, It works for me ;)

**Comment by ethan37** [comment]
Can you close this?
