### ISSUE TITLE
Receiving Notification When app is active

### ISSUE THREAD

**Issue by rengasahusoft** [evollu/react-native-fcm#249]
Hi Guys

i use React Native 0.30
and fcm  : 2.3.2

I am listening to this event and i get notification even when app is active (both ios and Android)

```
FCM.on('notification', notif => {
      _notificationHelper(respond,notif);
    });
```

Any idea how to solve this ? Is there any config i need to add in my server side?

**Comment by ethan37** [comment]
Send data-only payload in notification from your server. From FCM.on("notification"), intercept notification. Here, check if your app is active or background through AppState (https://facebook.github.io/react-native/docs/appstate.html). If app is in background, throw local notification through FCM.presentLocalNotificatioN() with your remote notification data. :)

**Comment by rengasahusoft** [comment]
Thanks for Helping Me 
But I found very straight forward way. Notification object has open_from_prop which is 1 and true when notification opened from tray in android and ios respectively

when open from tray
`open_from_prop = true` in ios
`open_from_prop=1` in android

When not
`open_from_prop = 0` in ios
`open_from_prop=undefined` in android

**Comment by ethan37** [comment]
Oh, I misunderstood your issue! I'm glad you solved :+1:

**Comment by ethan37** [comment]
@rengasahusoft Just out of curiosity, which version of react-native-fcm are you using? That object key should be called "opened_from_tray"

**Comment by rengasahusoft** [comment]
@ethan37 Yes  object key should be called "opened_from_tray" and I am using version 2.3.2

**Comment by alxvallejo** [comment]
Can someone explain what the tray is? if it's the iOS notification tray for instance than every notification should be opened by the tray... I get multiple notif logs on a notification and initially opened_from_tray is zero (when _notificationType is remote_notification) and then it console logs another notif as opened_from_tray: true when _notificationType is "notification_response". I have no idea where the documentation is for this and it seems this repo's documentation is out of date.
