### ISSUE TITLE
Attempting to assign weaker access privileges; was public

### ISSUE THREAD

**Issue by derdav3** [evollu/react-native-fcm#25]
This is more a FYI: When initiating a new Project and implementing your Readme step by step I got this issue:
`/MainActivity.java:34: error: onNewIntent(Intent) in MainActivity cannot override onNewIntent(Intent) in ReactActivity
    protected void onNewIntent(Intent intent){
                   ^
  attempting to assign weaker access privileges; was public
1 error
:app:compileDebugJavaWithJavac FAILED`

**Comment by magrinj** [comment]
I had the same issue the prototype method change since react-native <= 0.27:

So for something higher than react-native 0.27:

```java
    @Override
    public void onNewIntent(Intent intent) {
        super.onNewIntent(intent);
        setIntent(intent);
    }
```

and for the olds versions:
```java
    @Override
    protected void onNewIntent(Intent intent) {
        super.onNewIntent(intent);
        setIntent(intent);
    }
```

```
protected -> public
```

**Comment by evollu** [comment]
@magrinj thanks
