### ISSUE TITLE
"FCM.presentLocalNotification" is not working in Android

### ISSUE THREAD

**Issue by jvarshaprdxn** [evollu/react-native-fcm#250]
I am using "react-native": "^0.35.0"  and   "react-native-fcm": "^2.5.5"

Notifications are coming, When app running in a background 
but when app is in a foreground, not getting any notification.  

What I have done:

**step 1** :
this.notificationUnsubscribe = FCM.on("notification", notif => {
      console.log("notificationUnsubscribe=====>", notif); 
     /**this console gives me:
    {
       fcm: {
          action: null,
          body: "My message",
          color: null,
          icon: null,
          tag: null,
          title: "My title"
       },
       message: "My message"
    }
**/

**step 2**
/* then called  presentLocalNotification */
this.sendRemote(notif);  //====> this method defined below
}

sendRemote(notif) {
    console.log('when app in foreground send noti', notif);
   
    FCM.presentLocalNotification({
                    body: notif.fcm.body
                    priority: "high",
                    title: notif.fcm.title
                    sound: "default",
                    show_in_foreground: true,
                    tag:"CHAT"
                });
  }

I expected that this will give me notification, when app running in a forground but **its not working**
and also I observed that "presentLocalNotification" not getting triggered.

I also reffered issue no: #140 but still not got the solution

**Comment by evollu** [comment]
@jvarshaprdxn `I observed that "presentLocalNotification" not getting triggered.` can you elaborate that?
@GaryLengkong notification doesn't show up could be some notification attribute you pass throw error. try the simplest notification?

**Comment by avishayil** [comment]
Same here on `presentLocalNotification`, no banner shows when app is on foreground, even though I passed the `show_in_foreground: true` property.

**Comment by alexdohmen** [comment]
+1
RN: 0.41, fcm: 6.0.2

my code is something like this:
const notificationListener = FCM.on(FCMEvent.Notification, async (notif) => {
    if (notif.local_notification) {
        return
    }
    if (notif.opened_from_tray) {
        return
    }

    FCM.presentLocalNotification({
      title: notif.title,
      body: notif.body,
      priority: "high",
      click_action: notif.click_action,
      show_in_foreground: true,
      local: true
    })
})

**Comment by jvarshaprdxn** [comment]
**Following code works for me, Hence closing this issue**

```
FCM.on("notification", notif => {
      if(notif.fcm && notif.fcm.body) {
          /* Create local notification for showing in a foreground */
          FCM.presentLocalNotification({
             body: notif.fcm.body,
             priority: "high",
             title: notif.fcm.title,
             sound: "default", 
             "large_icon": "ic_launcher",// Android only
             icon: "ic_launcher",
             "show_in_foreground" :true, /* notification when app is in foreground (local & remote)*/
             vibrate: 300, /* Android only default: 300, no vibration if you pass null*/
             "lights": true, // Android only, LED blinking (default false)
             status: notif.status
         });
      }
}

**Comment by slibbyprdxn** [comment]
Nice work @jvarshaprdxn on behalf of the @prdxn team.

**Comment by apurvaaggarwal** [comment]
thanks @jvarshaprdxn 
It also worked for me
FCM.on(FCMEvent.Notification, notif => {
           if(notif.fcm && notif.fcm.body) {
               console.warn(‘here’)
               /* Create local notification for showing in a foreground */
               FCM.presentLocalNotification({
                  body: notif.fcm.body,
                  priority: “high”,
                  title: notif.fcm.title,
                  sound: “default”,
                  “large_icon”: “ic_launcher”,// Android only
                  icon: “ic_launcher”,
                  “show_in_foreground” :true, /* notification when app is in foreground (local & remote)*/
                  vibrate: 300, /* Android only default: 300, no vibration if you pass null*/
                  “lights”: true, // Android only, LED blinking (default false)
                  status: notif.status
              });
           }
     })

**Comment by xemasiv** [comment]
react-native@0.50.4
react-native-fcm@13.1.0

Following fixed it for me:

* Using `classpath 'com.google.gms:google-services:3.2.0'` on project-level `build.gradle`
* Using `compile 'com.google.firebase:firebase-core:11.8.0'` on app-level `build.gradle`
* Adding `compile 'com.google.firebase:firebase-messaging:11.8.0'` on app-level `build.gradle`
