### ISSUE TITLE
How to Mute the local Notification

### ISSUE THREAD

**Issue by renganatha10** [evollu/react-native-fcm#252]
I need to how to mute the Local Notification

i am bypassing the property `sound:'default'` but still i get the sound
```
  FCM.presentLocalNotification({
            title,
            body,
            message: 'hi',
            questionId: 1,
            ref: 'ref',
            type: 'Support',
            show_in_foreground: true,
          });
```

**Comment by evollu** [comment]
having sound is the default behavior. if you want to mute it, a PR is welcomed. possibly by passing ''?

**Comment by yakirbu** [comment]
Still no way to mute foreground notifications?

**Comment by pewh** [comment]
Already passing '' on sound, then no notification overall. Adding blank mp3 as a sound, I expected to no sound, but the reality is it still show notification sound but for 0.25 second, then silent immediately; which produce weird notification sound.

**Comment by evollu** [comment]
@pewh use latest version and don't set sound property. it should be silent

**Comment by pewh** [comment]
Ah yes, it's work now :beers:
