### ISSUE TITLE
Don't have local notification sound on Android

### ISSUE THREAD

**Issue by cstd** [evollu/react-native-fcm#253]
I'm using:
"react": "15.4.1",
"react-native": "0.39.2",
 "react-native-fcm": "^2.5.5"

In local notification, when i set { sound: "default" }, have no sound, i must remove "sound" parameter, it works. When i use custome sound, such as { sound: "custome.mp3" }, have no sound with local notification (i see this line "failed to open android.resource://com.../0" in android studio log), but remote notification works well with same config?!?

How can i use custome sound with local notification?

**Comment by evollu** [comment]
@cstd fix published in master branch. can you test it out?

**Comment by evollu** [comment]
fixed in 2.5.6
