### ISSUE TITLE
Stop Receiving Notification

### ISSUE THREAD

**Issue by minhchu** [evollu/react-native-fcm#254]
I'm using react-native 0.37.0, react-native-fcm 2.5.5, on a real device (android lolipop). My app receives notifications from FCM successfully but I dont know how to stop receiving notifications. I tried:  
```
FCM.cancelAllLocalNotifications()
```
but it didnt work.
Do you have any ideas?

**Comment by nezaidu** [comment]
```
const listener = FCM.on("notification", handleNotification.bind(this, dispatch));
// to unsubscribe
listerner();
```

**Comment by minhchu** [comment]
It doesnt work either :(

**Comment by ethan37** [comment]
You have to delete your token from your server side database/store

**Comment by evollu** [comment]
cancelAllLocalNotifications only deletes local notifications.
to not receiving remote notification, you should stop it on server side (just don't send it).

**Comment by otoinsa** [comment]
FCM.cancelAllLocalNotifications() does not work either in this case

**Comment by evollu** [comment]
@otoinsa can you elaborate?

**Comment by ShankarMaraka** [comment]
Is this issue solved?

**Comment by ShankarMaraka** [comment]
The local notifications are not cancelled for the notification tray when using 
FCM.cancelAllLocalNotifications()

**Comment by evollu** [comment]
@ShankarMaraka `FCM.removeDeliveredNotification()`
