### ISSUE TITLE
IOS FCM.getInitialNotification() is always return null 

### ISSUE THREAD

**Issue by pankaj-ag** [evollu/react-native-fcm#256]

**Comment by ethan37** [comment]
null or undefined?

**Comment by evollu** [comment]
can you provide details?

**Comment by pankaj-ag** [comment]
I have fixed it. I was not using the id key in my notification payload. I think it should be written somewhere in docs.

**Comment by ethan37** [comment]
@pankaj-ag I will include this in the next revision of the docs, where did you include your id key in the FCM payload, in the **notification** object or in the **data** object?

**Comment by evollu** [comment]
a pull is welcome

**Comment by ethan37** [comment]
@evollu will do in a couple days
