### ISSUE TITLE
react-native run-ios failing

### ISSUE THREAD

**Issue by ahmed1490** [evollu/react-native-fcm#26]
I have no clue as to what the issue is related to

<img width="1265" alt="screenshot" src="https://cloud.githubusercontent.com/assets/623510/16469599/38ff025c-3e52-11e6-82e6-698a91caea1c.png">

**Comment by ahmed1490** [comment]
and I do have the libs linked.

<img width="630" alt="screenshot" src="https://cloud.githubusercontent.com/assets/623510/16469687/a30da158-3e52-11e6-8188-385c3961e3cd.png">

**Comment by derdav3** [comment]
Any luck with this? facing the same..

**Comment by robbalian** [comment]
+1. Subscribe

**Comment by gorangajic** [comment]
I think that I have figured this one out. 
- You need to add `$(inherited)` in Build Settings => Other Linker Files https://cloudup.com/czZy1ucd1Ta
- Also you need to include Cocoa Pods in your project Right Click => add Files to project and add `ios/Pods/Pods.xcodeproj` https://cloudup.com/cqkiHU-piMx

**Comment by gorangajic** [comment]
More info here https://guides.cocoapods.org/using/troubleshooting#installing-cocoapods

**Comment by derdav3** [comment]
@gorangajic I quickly tried it with a fresh project and got these:

'Undefined symbols for architecture x86_64:
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__init(char const*, unsigned long)", referenced from:
      ___23-[RCTJSCExecutor setUp]_block_invoke.146 in libReact.a(RCTJSCExecutor.o)
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()", referenced from:
      ___23-[RCTJSCExecutor setUp]_block_invoke.146 in libReact.a(RCTJSCExecutor.o)
  "std::terminate()", referenced from:
      ___clang_call_terminate in libReact.a(RCTJSCExecutor.o)
  "operator delete[](void*)", referenced from:
      -[RCTJSCExecutor dealloc] in libReact.a(RCTJSCExecutor.o)
      executeRandomAccessModule(RCTJSCExecutor*, unsigned int, unsigned long, unsigned long) in libReact.a(RCTJSCExecutor.o)
      readRAMBundle(std::__1::unique_ptr<__sFILE, int (*)(__sFILE*)>, RandomAccessBundleData&) in libReact.a(RCTJSCExecutor.o)
      RandomAccessBundleData::~RandomAccessBundleData() in libReact.a(RCTJSCExecutor.o)
  "operator new[](unsigned long)", referenced from:
      executeRandomAccessModule(RCTJSCExecutor*, unsigned int, unsigned long, unsigned long) in libReact.a(RCTJSCExecutor.o)
      readRAMBundle(std::__1::unique_ptr<__sFILE, int (*)(__sFILE*)>, RandomAccessBundleData&) in libReact.a(RCTJSCExecutor.o)
  "___cxa_begin_catch", referenced from:
      ___clang_call_terminate in libReact.a(RCTJSCExecutor.o)
  "___gxx_personality_v0", referenced from:
      -[RCTJavaScriptContext initWithJSContext:onThread:] in libReact.a(RCTJSCExecutor.o)
      -[RCTJavaScriptContext init] in libReact.a(RCTJSCExecutor.o)
      -[RCTJavaScriptContext invalidate] in libReact.a(RCTJSCExecutor.o)
      RCTNSErrorFromJSError(RCTJSCWrapper*, OpaqueJSContext const*, OpaqueJSValue const*) in libReact.a(RCTJSCExecutor.o)
      +[RCTJSCExecutor runRunLoopThread] in libReact.a(RCTJSCExecutor.o)
      -[RCTJSCExecutor init] in libReact.a(RCTJSCExecutor.o)
      -[RCTJSCExecutor context] in libReact.a(RCTJSCExecutor.o)
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)'

**Comment by evollu** [comment]
@derdav3 looks like the error is related to react itself?

**Comment by evollu** [comment]
@derdav3 @ahmed1490 looks like you are running with react-native cli? If so, try open `.xcworkspace` not `.xcproject` and run in xcode

**Comment by ahmed1490** [comment]
I am gonna try this @evollu and let you know

**Comment by dnish** [comment]
@evollu Just opened the .xcworkspace and tried to build the app, getting 8 errors:

```
Apple Mach-O Linker Error Group
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__init(char const*, unsigned long)", referenced from:

  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()", referenced from:

  "std::terminate()", referenced from:

  "operator delete[](void*)", referenced from:

  "operator new[](unsigned long)", referenced from:

  "___cxa_begin_catch", referenced from:

  "___gxx_personality_v0", referenced from:

clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by evollu** [comment]
@dnish is the build target your react native project?
can you find out what module is throwing this error?

**Comment by dnish** [comment]
@dnish Don't know if you got the edited post, the only file I can see is <code>libReact.a</code>. I'm using React Native 0.28

**Comment by evollu** [comment]
Well I don't get much information here. I assume you are seeing a project structure similar to mine. You should choose the first scheme to build your project.
<img width="1440" alt="screen shot 2016-07-06 at 2 11 51 pm" src="https://cloud.githubusercontent.com/assets/9213224/16629450/b7d56d4c-4383-11e6-986d-1a576e4f1fb0.png">
Try pick target RNFIRMessaging and `cmd+B` to build the library.

**Comment by evollu** [comment]
Perhaps I haven't done react-native upgrade for a long long time. let me upgrade and see
`Since 0.26.0-rc, you must add -lc++ to the Other flags in the xcode project.`

**Comment by dnish** [comment]
I'll reset my project and try every step again, maybe I did a mistake.

**Comment by dnish** [comment]
@evollu The error happens directly after <code>pod install</code>, without adding react-native-fcm.

**Comment by evollu** [comment]
Are you adding `$(inherited)` in `Linking->Other Linker flags`?

**Comment by dnish** [comment]
Yep, I've added it but it is still failing.

**Comment by evollu** [comment]
error: The sandbox is not in sync with the Podfile.lock.
can you update cocoapod to lastest and run pod install again? I remember the pod requires cocoapod>1 or something like that.

**Comment by dnish** [comment]
I've just installed it for the plugin yesterday, it is on version 1.0.1

**Comment by evollu** [comment]
It looks like a cocoaPods issue. All I can do is google for you...
try this? http://stackoverflow.com/questions/21366549/errorthe-sandbox-is-not-in-sync-with-the-podfile-lock-after-installing-res

**Comment by dnish** [comment]
@evollu Yeah thanks, that's all not working. I've reverted my project via git and the error occurs directly after doing <code>pod install</code>, even without any plugin added in the podfile. I'll figure this out the next days. So it has nothing to do with the fcm plugin.

**Comment by derdav3** [comment]
@dnish pls keep me updated if you found the solution... I'm sitting in the same boat

**Comment by evollu** [comment]
@dnish thanks for all the information. 
BTW I'm running pod 1.0.0

**Comment by evollu** [comment]
hey guys, if you want to try without cocoapods, the `nopod` branch should work. Follow https://firebase.google.com/docs/ios/setup last section to integrate frameworks

**Comment by evollu** [comment]
new version has been pushed to npm. If you can't get pod to work, just import framework files

**Comment by ahmed1490** [comment]
I will try this tonight

**Comment by evollu** [comment]
let's figure this on gitter. should be configuration issue

**Comment by evollu** [comment]
@ahmed1490 @derdav3 are you able to give it another try?

**Comment by ahmed1490** [comment]
The repo read me is a bit unclear to me: `FirebaseAnalytics.framework` I already imported it from firebase site. Do I need to override with the project's version?

**Comment by ahmed1490** [comment]
Facing this..

<img width="1242" alt="screenshot" src="https://cloud.githubusercontent.com/assets/623510/16824590/54cb1d2e-496d-11e6-8a3b-c6b8fd2e2992.png">

"react-native": "^0.28.0",

I added the libs:
<img width="257" alt="screenshot" src="https://cloud.githubusercontent.com/assets/623510/16824599/7004dc1a-496d-11e6-8a43-1a660a788f5d.png">

and 

<img width="572" alt="screenshot" src="https://cloud.githubusercontent.com/assets/623510/16824617/939f9e4e-496d-11e6-9f7c-787431e817b8.png">

and did `npm i --save react-native-fcm` & `react-native link`

I also have the file:
<img width="623" alt="screenshot" src="https://cloud.githubusercontent.com/assets/623510/16824637/bc8c0586-496d-11e6-90db-2a275f28cbc8.png">

**Comment by evollu** [comment]
oh they added the missing framework file. I will update readme.

**Comment by evollu** [comment]
the error log seems to be cut off

**Comment by ahmed1490** [comment]
@evollu thats the last line of error log. Next line is just by usual bash prompt

**Comment by ahmed1490** [comment]
So the simulator starts without error but..there is no FCM registered it seems.
Nothing logged on console.

source code.
https://github.com/ahmed1490/igniteFCM/commit/5ba627eb505fffaeab0ab253861121af2caa6936

**Comment by evollu** [comment]
I will pull your code and take a look

**Comment by evollu** [comment]
@ahmed1490 you need to add Firebase.h into your project
it is in the README of FCM zip

**Comment by ahmed1490** [comment]
oh yes! @evollu 
I added the firebase.h now. The build succeeds but the app refuses to start. It opens and closes from splash screen. weird behaviour. Any hints?

![ignitefcm](https://cloud.githubusercontent.com/assets/623510/16853499/d4d6ebfc-4a0c-11e6-8c37-a67367195493.gif)

**Comment by evollu** [comment]
check your nslog
i got '[FIRApp configure] could not find a valid GoogleServices-Info.plist in your project.

**Comment by ahmed1490** [comment]
I appreciate you help so much!
how and where can I check this nslog?  Also I added this now (i did add earlier. not sure where it disappeared). Still the result is same.

I feel this `react-native run-ios` works too fast for me. I dont know if its skipping something

**Comment by ahmed1490** [comment]
@evollu Thank you for walkine me through. 

Is this the log panel you talking about?

<img width="1236" alt="screenshot" src="https://cloud.githubusercontent.com/assets/623510/16856409/3683e73a-4a1a-11e6-89b0-a86797dd51cf.png">

And.. Yaaay I got the notification finally But one small issue..

i am not sure what is that "e".. but the title of the message is not delivered. Is it this way on ios?

<img width="530" alt="screenshot" src="https://cloud.githubusercontent.com/assets/623510/16856424/4646b008-4a1a-11e6-8676-0332ff6ad589.png">

<img width="1236" alt="screenshot" src="https://cloud.githubusercontent.com/assets/623510/16856441/547faddc-4a1a-11e6-8598-02c321895ae3.png">

**Comment by ahmed1490** [comment]
edited comment ^

**Comment by ahmed1490** [comment]
That was a message label I was assuming as message body!

My mistake.. everything is good :D Thank you veery much!! appreciate it :)

**Comment by evollu** [comment]
cool

**Comment by ahmed1490** [comment]
Gonna try andriod tommorrow :)

**Comment by chaodoze** [comment]
fwiw, I ran into the same problem as @derdav3, and after googling and some trial and error, this worked for me:
1) open <app>.xcworkspace
2) In xcode, under "Build Settings", make sure the target is <app>Tests (not the app itself), search for "Other Linker Flags" and add "-lc++" to the Other Linker Flags settings
![otherviews_and_googrn_xcodeproj_and_hipchat](https://cloud.githubusercontent.com/assets/51853/17119049/7691ed66-5278-11e6-8d4a-736fc3eb0ced.png)

**Comment by ppsreejith** [comment]
In case someone else faces this issue, adding the GoogleServices-Info.plist file through the project navigator helped

**Comment by yolosaucisson** [comment]
Same problem with "can't found a valid GoogleService-Info.plist" :(

**Comment by mattijauhiainen** [comment]
Seems like just copying the GoogleService-Info.plist to the project folder is not enough. Instead you need to open the project in xcode, open the file-tree in the left, and then drag'n'drop the GoogleService-Info.plist to the project folder from finder 😶  Once you that xcode will popup a window, make sure you tick the 'Copy if necessary' option.
