### ISSUE TITLE
FCM.on() should return an unsubscribe object method instead of a function

### ISSUE THREAD

**Issue by ethan37** [evollu/react-native-fcm#260]
Don't you think it would be better if FCM.on() returned an "unsubscribe" object method instead of returning a function, directly?

This way, people could do this 
```
this.notificationListener = FCM.on("notification", callback)
this.notificationListener.unsubscribe()
```

It's way easier to understand and looks cooler! :)
If you agree i can make PR

**Comment by sibelius** [comment]
returning an object was good in OO languages

returning a function is the best way of doing this on functional style programming

redux does this as well - https://github.com/reactjs/redux/blob/master/src/createStore.js#L101

this take an advantage of closure, u just need to get used to it

**Comment by sibelius** [comment]
```jsx
const unsubscribe = FCM.on('', () => {})
unsubscribe();
```

isn't clear enough?

**Comment by ethan37** [comment]
@sibelius It's not really clear until you actually look into the index.js file and see what's happening

**Comment by ethan37** [comment]
@sibelius I'm reviewing the docs in order to make them a bit more clear, since there are unnecessary or missing pieces of information at the moment and it can be really confusing, and this issue came up to my mind...

anyway I will still be personally using the current version because i'm running RN 0.33, but it would be better/easier to understand for future users if we can change this... 

or I can clarify this on readme.md, since it could break compatibility for those who update or use older versions based on new docs and i completely agree on this!!!

@evollu what do you think?

**Comment by sibelius** [comment]
maybe we could break documentation in multiples files as react-native-router-flux did

https://github.com/aksonov/react-native-router-flux/tree/master/docs

**Comment by evollu** [comment]
@sibelius good idea. The readme is huge now
@ethan37 speak of versioning, we can rely on release tagging. so doc for v2.5 will be under tag v2.5

**Comment by ethan37** [comment]
@sibelius awesome! breaking the documentation into smaller pieces will be a good thing. I'll make a PR soon

**Comment by ethan37** [comment]
@evollu What about this issue? Should we make the change or not?

**Comment by evollu** [comment]
yes sure

**Comment by ethan37** [comment]
Cool! 👍

**Comment by ethan37** [comment]
https://github.com/evollu/react-native-fcm/pull/262 :)
