### ISSUE TITLE
Receiving notifications in the console but turning into a notifcation on the device

### ISSUE THREAD

**Issue by hosusan6** [evollu/react-native-fcm#264]
Sorry this is probably an incredibly simple question but i am receiving the notification in the console as per the example. But i cant see a method to display the console logged notification as a notification rather than in the console?

**Comment by ethan37** [comment]
FCM.presentLocalNotification() also behavior depends on type. of payload (notification or data)  and app running in foreground or background

**Comment by hosusan6** [comment]
thanks

**Comment by ethan37** [comment]
@hosusan6  can you close this?
