### ISSUE TITLE
Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by signorekai** [evollu/react-native-fcm#266]
RN: 0.39.0
react-native-fcm: 2.5.6

I'm unable to build my project after following all the steps on the readme. Log reads:

`Undefined symbols for architecture arm64:
  "_inflate", referenced from:
      +[NSData(GTMZlibAdditionsPrivate) gtm_dataByInflatingBytes:length:isRawData:error:] in GoogleToolboxForMac(GTMNSData+zlib_133a1619f6f498b1872062af2031468a.o)
  "_deflate", referenced from:
      +[NSData(GTMZlibAdditionsPrivate) gtm_dataByCompressingBytes:length:compressionLevel:mode:error:] in GoogleToolboxForMac(GTMNSData+zlib_133a1619f6f498b1872062af2031468a.o)
  "_inflateEnd", referenced from:
      +[NSData(GTMZlibAdditionsPrivate) gtm_dataByInflatingBytes:length:isRawData:error:] in GoogleToolboxForMac(GTMNSData+zlib_133a1619f6f498b1872062af2031468a.o)
  "_deflateInit2_", referenced from:
      +[NSData(GTMZlibAdditionsPrivate) gtm_dataByCompressingBytes:length:compressionLevel:mode:error:] in GoogleToolboxForMac(GTMNSData+zlib_133a1619f6f498b1872062af2031468a.o)
  "_inflateInit2_", referenced from:
      +[NSData(GTMZlibAdditionsPrivate) gtm_dataByInflatingBytes:length:isRawData:error:] in GoogleToolboxForMac(GTMNSData+zlib_133a1619f6f498b1872062af2031468a.o)
  "_deflateEnd", referenced from:
      +[NSData(GTMZlibAdditionsPrivate) gtm_dataByCompressingBytes:length:compressionLevel:mode:error:] in GoogleToolboxForMac(GTMNSData+zlib_133a1619f6f498b1872062af2031468a.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

Any help would be greatly appreciated!!

**Comment by signorekai** [comment]
I fixed this by just using CocoaPods.

**Comment by rizasif** [comment]
@signorekai can please explain how to use cocoapods to resolve this issue?

**Comment by signorekai** [comment]
Wish I could help, but what I did was to simply install using CocoaPods
instead of manually installing. Check the docs for instructions on
CocoaPods installation.

**Comment by firhat** [comment]
> @signorekai can please explain how to use cocoapods to resolve this issue?

I fix it with by Right Click the Library folder and Add File to <Project Name> to. Add RNFIRMessaging.xcodeproj, there should should be under node_modules/react-native-fcm/ios.
Make sure you see libRNFIRMessaging.a under Link Binary With Libraries under Build Phases tab. If no, drag the file under RNFIRMessaging.xcodeproj under Library folder into there.
