### ISSUE TITLE
question: is "background fetching" supported in iOS

### ISSUE THREAD

**Issue by npomfret** [evollu/react-native-fcm#268]
I notice that the docs have the following code for iOS:

```
+ - (void)application:(UIApplication *)application didReceiveRemoteNotification:(nonnull NSDictionary *)userInfo fetchCompletionHandler:(nonnull void (^)(UIBackgroundFetchResult))completionHandler{
+   [[NSNotificationCenter defaultCenter] postNotificationName:FCMNotificationReceived object:self userInfo:userInfo];
+   completionHandler(UIBackgroundFetchResultNoData);
+ }
```

I'm wondering why the line `completionHandler(UIBackgroundFetchResultNoData);` is here? 

I want to implement some _background fetching_ code on receipt of a remote push notification.  I would have thought it was necessary to call the completion handler after my JS fetching code is complete.  If the completion handler is called immediately (as above) I would have thought the OS would not give my JS code any time to run.  Is this not the case?

**Comment by evollu** [comment]
Yes, current implementation is not optimal, but JS code still seems to get triggered. Can you verify.
The correct solution would be follow [PushNotificationIOS](https://github.com/facebook/react-native/blob/master/Libraries/PushNotificationIOS/RCTPushNotificationManager.m)'s implementation.
I can do it when I'm free. Pull request is welcome

**Comment by evollu** [comment]
done in v6.0.2
