### ISSUE TITLE
Best way to handle vibrations/sounds when receiving notification?

### ISSUE THREAD

**Issue by arao456** [evollu/react-native-fcm#27]
Hi!

Sorry if this is out of scope of this package, but what is the best way to make an android device vibrate or play a sound when a notification comes in? Is this something that should be implemented in `onMessageReceived` within `MessagingService.java`? Or is this in the scope of firebase rather than RN?

**Comment by gorangajic** [comment]
When sending message using firebase api you can specify sound

https://firebase.google.com/docs/cloud-messaging/http-server-ref#notification-payload-support

**Comment by arao456** [comment]
That seems to work! Closing for now!
