### ISSUE TITLE
Handling of special characters: preprocessing the notifications before display

### ISSUE THREAD

**Issue by ksegla** [evollu/react-native-fcm#271]
Hi all
Thanks for the great work!
Is there a way to decode the special characters (é, à etc. crucial stuff for French speaking people) in the notification?
I encode the special characters before sending them to the FCM web api. When FCM returns the notification, I need to decode the string.
Thanks

RN 0.34.1
Android 5.1 device
App running in background

**Comment by evollu** [comment]
I'm not sure I understand your question. Can you send notification with é and display correctly?

**Comment by ksegla** [comment]
If I directly send special characters in the text, I never receive anything. It seems that, unsurprisingly, fcm itself (the api at https://fcm.googleapis.com/fcm/send) does not handle it and requires an utf encoding.

So I encode the message and sends it. Problem is that what is then displayed as notification is the encoded version. Not user-friendly. I need to decode the message before displaying the notification.

**Comment by evollu** [comment]
Does it not work in both OS or just Android?

The best solution is report issue to Firebase team. isn't é part of UTF-8?
or you can do "data" message and in FCM.on callback present a local notification. However if user kills iOS app the callback won't be called.

**Comment by ksegla** [comment]
Sorry, I meant uri encoding, not utf. And yes, I will report this to Firebase. Not everyone uses English :)
For now, I'm focused on Android, so your work around may be enough for the time being.
Thanks

**Comment by evollu** [comment]
why would you put message title/body in uri encode? shouldn't them be in POST payload?

**Comment by ksegla** [comment]
They are in the POST payload. I got the code from SO. It is server side (AWS Lambda) and looks like below. (I curated it so there may be some small typos/mistakes)

var sendNotification = function(token, msg, user) {
        let body = {
                "to":token,
                "data": {                
                    badge: 1,
                "custom_notification": {
                    "body": msg, //here is where special characters just mess up stuff
                    "title": user.firstName, //I guess here too special characters wouldn't go well
                    "priority":"high",
                    "show_in_foreground": true,
                    "picture": user.picture
                }
            }}
            _send(JSON.stringify(body), "notification");
        });
  }
  
var _send = function(body, type) {
    var options = {
      hostname: 'fcm.googleapis.com',
      path: '/fcm/send',
      method: 'POST',
      headers: {
      		"Content-Type": "application/json",
      		"Content-Length": parseInt(body.length),
            "Authorization": "key=" + SERVICE_KEY
      }
    };
    var req = https.request(options, function(res) {
      console.log('Status: ' + res.statusCode);
      console.log('Headers: ' + JSON.stringify(res.headers));
      res.on('data', function (body) {
        console.log('Body: ' + body);
      });
    });    
    req.on('error', function(e) {
      console.log('problem with request: ' + e.message);
    });    
    // write data to request body
    req.write(body);
    req.end();
}

**Comment by evollu** [comment]
I just tested with é by sending payload though postman, it works fine. I suggest you use some http library like axios, you life will be easier making http request.

**Comment by ksegla** [comment]
ok. Will check. Thanks!
