### ISSUE TITLE
"React/RCTBridgeModule.h" not found

### ISSUE THREAD

**Issue by grmmph** [evollu/react-native-fcm#272]
RNFIRMMesseging.h failed to load dependency "React/RCTBridgeModule.h".

Help!

**Comment by grmmph** [comment]
Ok seems like the right input should be
`"RCTBridgeModule.h"` for all the the deps under `React` module.

**Comment by khanghoang** [comment]
@evollu should I make a PR for this?

**Comment by grmmph** [comment]
Seems like this is a common issue with many react-native packages.

**Comment by evollu** [comment]
What RN and fcm version are you using?

**Comment by grmmph** [comment]
react-native-cli: 1.2.0
react-native: 0.37.0
react-native-fcm: 4.0.1

**Comment by evollu** [comment]
use v2.5.6, check readme

**Comment by khanghoang** [comment]
@evollu my bad, I didn't read the readme file carefully.
