### ISSUE TITLE
App crashes after updating AppDelegate.m

### ISSUE THREAD

**Issue by grmmph** [evollu/react-native-fcm#273]
After modifying `AppDelegate.m`, I get the following error `libc++abi.dylib: terminating with uncaught exception of type NSException`
for the line `return UIApplicationMain(argc, argv, nil, NSStringFromClass([AppDelegate class]));` in `main.m`.

**Comment by grmmph** [comment]
Ok this was due to not including the `GoogleService-Info.plist` in my iOS project.

**Comment by pentarex** [comment]
Thank you for coming back and telling where the issue is. It sure did saved me a lot of time :)
