### ISSUE TITLE
Android - Small White Icon Issue

### ISSUE THREAD

**Issue by jnrepo** [evollu/react-native-fcm#274]
What I'm trying to do is format the notification icons for React Native Android and is running into an issue where a small white square will appear on the notification banner (screenshot).

<img width="384" alt="screen shot 2017-01-15 at 5 31 09 pm" src="https://cloud.githubusercontent.com/assets/5111058/21968386/f7f47bae-db48-11e6-9bc3-529a10fcd95f.png">

This is what I'm sending remotely

```
data: {
        key: 'major',
        another_one: 'another value',
        custom_notification: {
            title: 'Title of your push notification',
            body: 'Body of your push notification',
            icon: 'icon_small',
            large_icon: 'ic_launcher',
            show_in_foreground: true
        },
    }
```

It's strange because on top bar the icon will show correctly, however, when you roll down the notifications and look at the banner there is a white square instead. I've tried changing the icon to different sizes and no luck. When I change the `icon` value being sent to `ic_launcher`, it will show up with no color. Is there something I missed? Anyone else running into this issue?

When icon is set to `ic_launcher`:
<img width="382" alt="screen shot 2017-01-15 at 5 40 57 pm" src="https://cloud.githubusercontent.com/assets/5111058/21968494/fe911a52-db49-11e6-88af-5ed47f8b96ad.png">
<img width="391" alt="screen shot 2017-01-15 at 5 41 16 pm" src="https://cloud.githubusercontent.com/assets/5111058/21968495/02d6fd16-db4a-11e6-8548-4f9dea87675a.png">

**What verion of RN and react-native-fcm are you running?**
RN: 0.40.0
react-native-fcm: 4.0.0

**What device are you using? (e.g iOS9 emulator, Android 6 device)?**
Android - Galaxy S5

**Is your app running in foreground, background or not running?**
Issue shows up on each of these states.

**Comment by evollu** [comment]
perhaps that icon has to be white with transparent background? just like the icon limitation after lolipop

**Comment by evollu** [comment]
@jnrepo any updates?

**Comment by evollu** [comment]
close due to inactivity
