### ISSUE TITLE
Randomly stop receiving notifications

### ISSUE THREAD

**Issue by baldurpan** [evollu/react-native-fcm#277]
RN 0.39.2
Android 6 / 5.1
iOS 10.2

Been noticing this strange issue, reported by different users in both iOS and Android.
It seems like the devices stop showing notifications at some point but start again after you clear the old notifications. This doesn't seem to make much sense and I don't have much else to go on.
Has anyone else experienced this?

**Comment by yannickoo** [comment]
I have also experienced this issue, check https://github.com/firebase/quickstart-ios/issues/207#issuecomment-272152606 – recreating certificates could help :)

**Comment by baldurpan** [comment]
@yannickoo But doesn't that issue stop all notifications? My problem seems more random. Sometimes (or usually) works, sometimes not.

**Comment by yannickoo** [comment]
Oh sorry I got this wrong. This sounds totally weird :/

**Comment by bingle87** [comment]
I am having sort of a similar issue like this one. I used to get all firebase notifications on iOS, now i just get some. My topic 'topics/notification' just stopped working. While other topics consistently works. It all work on android, but this issue exists for iOS. Were you able to solve this?

**Comment by evollu** [comment]
if you can reproduce with SDK example, open an issue to FCM team

**Comment by baldurpan** [comment]
Ok, been doing some more testing. This is not so random and is Android only.
It seems like Android just stops receiving new notifications when tray has reached 50 notifications.

Not quite sure why this is, but I did some digging and found a possible suspect. 

`private static final int MAX_PACKAGE_NOTIFICATIONS = 50;`

Code found here:
https://android.googlesource.com/platform/frameworks/base/+/f76a50c/services/java/com/android/server/NotificationManagerService.java

Now the question is if there is something missing on this side?

**Comment by evollu** [comment]
Possible. Can you ask firebase team about it?

**Comment by bingle87** [comment]
I also found that iOS notifications were unreliable when the device was usb loaded with the app. I had to use test flight and then I started getting consistent notifications for iOS.

**Comment by baldurpan** [comment]
50 notifications in the tray seems to be some global limit in Android, so this is not an issue.
Tested in other apps and behaviour seems to be the same.
Closing this.

**Comment by TheBachelor** [comment]
Same here for iOS. I have the same notification sent to both Android & iOS. Android always receives them and iOS does for a while (maybe a week or 2) then suddenly stops until I go to firebase and manually send to the device. This also doesn't work at first, then it starts to work when I send my second notification.

**Comment by evollu** [comment]
it sounds like firebase service issue. @TheBachelor

**Comment by TheBachelor** [comment]
So there's nothing I can do? @evollu

**Comment by evollu** [comment]
try reproduce with their native example project and send their support an email.
This library is bridging data AFTER notification is delivered so delay of notification doesn't have anything to do with this lib.

**Comment by TheBachelor** [comment]
Oh I see. Thanks @evollu
