### ISSUE TITLE
Turn on/off notifications

### ISSUE THREAD

**Issue by gplopes** [evollu/react-native-fcm#283]
Hey folks,

I'm trying to find a way to turn on/off the notification. Is it possible? According to the doc, I could unsubscribeFromTopic and subscribeToTopic, could I do this for all the msg coming from the server?

Thank you.

**Comment by evollu** [comment]
probably not

**Comment by aubreywahl** [comment]
@evollu Can you elaborate on what you mean by that? Are you asking us to implement this behavior, or does it already exist in the module?

**Comment by evollu** [comment]
It is not in this module
Why not store a flag on server side?

**Comment by aubreywahl** [comment]
Yeah I think that's definitely the way to go. Thanks!

**Comment by gplopes** [comment]
Hey guys, thanks for taking the time. That was the way I did (saving a flag on the server-side). 
I just thought it would be possible and easy to access the settings of the device.

**Comment by evollu** [comment]
closing this. feel free to reopen if you think necessary
