### ISSUE TITLE
[Android] App crashes when close

### ISSUE THREAD

**Issue by priyesh9875** [evollu/react-native-fcm#285]
RN: 0.40
React native fcm: 5.0.0
Device: Android 7.1 cyanogen(Real)

When `back` button is pressed, system gives error saying `App keeps stopping`
In console, I am getting `Object is not a function (evaluating 'this.notificationUnsubscribe()')`
 
In componentDidMount, I am doing `this.notificationUnsubscribe = FCM.on(...)`

When I remove this.notificationInsubscribe(), then no errors. But I doubt that it will drain my battery.

**Comment by evollu** [comment]
the syntax has changed, check latest readme and release tab
