### ISSUE TITLE
'RNFIRMessaging.h' file not found

### ISSUE THREAD

**Issue by almadsen** [evollu/react-native-fcm#286]
I'm getting a 'RNFIRMessaging.h' file not found.
I've tried to install a few different way, well in different order and all that but still I get this message.
If anyone (for which it's working) could do a screen capture video of installing it the right way, that would be a tremendous help.

I even tried linking by adding $(SRCROOT)/../node_modules/react-native-fcm/ios to header search paths but the I got 14 new errors
Or if someone have some general pointer what to look out for, how to fix this linking problem or whatever's wrong here.

RN: 0.40.0
react-native-fcm: 5.0.0
Simulator: iOS9 & 10 / iPhone 6
Build fails so app not running at all

![skarmavbild 2017-01-26 kl 09 24 29](https://cloud.githubusercontent.com/assets/1423040/22325668/6e7c8bae-e3af-11e6-98ef-1451745dd3c5.png)

**Comment by ethan37** [comment]
Same issue! what's goin on?

**Comment by ethan37** [comment]
I never had this problem until this evening...

**Comment by ethan37** [comment]
Reinstalling with ```npm install react-native-fcm@<DESIDERED-VERSION> --save``` and react-native link fixed it for me

**Comment by evollu** [comment]
@almadsen is it recursive? also can you see it in your xcode solution?

**Comment by Kottidev** [comment]
![image](https://cloud.githubusercontent.com/assets/12915009/22424692/e818d5f8-e6f7-11e6-897e-48f548c42390.png)

RN: 0.40.0
react-native-fcm: 6.0.1
Simulator: iOS 10 / iPhone 6s Plus

**Comment by albinhubsch** [comment]
@Kottidev @ethan37 @evollu 
Add this line to the header search paths in Build Settings, xcode `$(SRCROOT)/../node_modules/react-native-fcm/ios`

**Comment by Kottidev** [comment]
i think with RN 0.40 we don't need to add path

**Comment by albinhubsch** [comment]
@Kottidev So may it be, but it solved this same issue for me earlier today when I installed this package.

**Comment by evollu** [comment]
react-native link should add the search path for you.
@albinhubsch can this issue be closed?

**Comment by albinhubsch** [comment]
@evollu I do think so. This issue does not seem to be a problem directly related to react-native-fcm. 

For futher troubleshooting. Try my fix mentioned above and also make sure to check out issues like this one [link](https://github.com/facebook/react-native/issues/12042). Also make sure to rebuild the project and check you schemes.

**Comment by evollu** [comment]
cool
