### ISSUE TITLE
Notification returns undefined

### ISSUE THREAD

**Issue by albinhubsch** [evollu/react-native-fcm#290]
RN 0.40
iOS 10, device and emulator, running in foreground

So I can send notifications to my devices successfully. But when listening `FCM.on(FCMEvent.Notification, (notif) => { console.log(notif) });` notif is undefined!? So the event handler is working and fires when notification is received but the notif is undefined. Any ideas? Thanks.

**Comment by mahm** [comment]
I fixed it this PR #292

**Comment by albinhubsch** [comment]
@mahm Thanks mate! you just saved me a bunch of time today! cheers 🥇

**Comment by evollu** [comment]
fixed
