### ISSUE TITLE
Documentation on usage outdated?

### ISSUE THREAD

**Issue by albinhubsch** [evollu/react-native-fcm#293]
RN 0.40
iOS 10.2

Ok, so I'm trying to get this to work. In the documentation, usage section, it says you can switch on notification type to determine if it is a local or remote notification `switch(notif._notificationType)`. This is not possible as it crashes due to undefined data in the notification. What is the updated/new way to do this?

It can be worth mentioning that I had problems with the returned notification being completely undefined, solved by #292

**Comment by evollu** [comment]
right, bug fixed and published
