### ISSUE TITLE
ClassNotFoundException com.evollu.react.fcm.InstanceIdService

### ISSUE THREAD

**Issue by arpu** [evollu/react-native-fcm#3]
any idea what is missing? 

E/AndroidRuntime(19958): java.lang.RuntimeException: Unable to instantiate service com.evollu.react.fcm.InstanceIdService: java.lang.ClassNotFoundException: Didn't find class "com.evollu.react.fcm.InstanceIdService" on path: DexPathList[[zip file "/data/app/com.zib100-1/base.apk"],nativeLibraryDirectories=[/data/app/com.zib100-1/lib/arm, /vendor/lib, /system/lib]]
E/AndroidRuntime(19958): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2776)
E/AndroidRuntime(19958): 	at android.app.ActivityThread.access$1800(ActivityThread.java:155)
E/AndroidRuntime(19958): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1400)
E/AndroidRuntime(19958): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(19958): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(19958): 	at android.app.ActivityThread.main(ActivityThread.java:5343)
E/AndroidRuntime(19958): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(19958): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(19958): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
E/AndroidRuntime(19958): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
E/AndroidRuntime(19958): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.evollu.react.fcm.InstanceIdService" on path: DexPathList[[zip file "/data/app/com.zib100-1/base.apk"],nativeLibraryDirectories=[/data/app/com.zib100-1/lib/arm, /vendor/lib, /system/lib]]
E/AndroidRuntime(19958): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime(19958): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
E/AndroidRuntime(19958): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
E/AndroidRuntime(19958): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2773)
E/AndroidRuntime(19958): 	... 9 more
E/AndroidRuntime(19958): 	Suppressed: java.lang.ClassNotFoundException: com.evollu.react.fcm.InstanceIdService
E/AndroidRuntime(19958): 		at java.lang.Class.classForName(Native Method)
E/AndroidRuntime(19958): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
E/AndroidRuntime(19958): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
E/AndroidRuntime(19958): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
E/AndroidRuntime(19958): 		... 11 more
E/AndroidRuntime(19958): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
W/ActivityManager(  838):   Force finishing activity 1 com.zib100/.MainActivity

**Comment by arpu** [comment]
hm changed the Androidmanifest
but now i get this 
 undefined is not an object (evaluating 'FIRMessaging.requestPermissions')

**Comment by LucasBassetti** [comment]
Same problem. Anybody knows how to solve that?

**Comment by ssmlee04** [comment]
Same problem..

**Comment by edy** [comment]
same here.

@arpu what did you change in your manifest?

**Comment by edy** [comment]
solved!

`android/app/build.gradle`: add `compile project(':react-native-fcm')`
`android/settings.gradle`: add
```
include ':react-native-fcm'
project(':react-native-fcm').projectDir = new File(rootProject.projectDir, '../node_modules/react-ative-fcm/android')`
```

**Comment by narychen** [comment]
@edy You '../node_modules/react-ative-fcm/android' is missing 'n' in react-native.
And it takes me an hour to find out what's wrong with gradle build error
'Error:Configuration with name 'default' not found.'
