### ISSUE TITLE
Example not working.

### ISSUE THREAD

**Issue by komorebi-san** [evollu/react-native-fcm#300]
CD into **simple-fcm-client** and ran npm install. 

When run react-native run-ios, a lot of files are not found.

```
/Volumes/FLASHDRIVE/React-Native/simple-fcm-client/node_modules/react-native/Libraries/Image/RCTImageViewManager.h:10:9: fatal error: 'React/RCTViewManager.h' file not found

/Volumes/FLASHDRIVE/React-Native/simple-fcm-client/node_modules/react-native/Libraries/Geolocation/RCTLocationObserver.h:10:9: fatal error: 'React/RCTEventEmitter.h' file not found
#import <React/RCTEventEmitter.h>
```

There are other missing files too.

**Comment by nilaybrahmbhatt** [comment]
same issue please help

**Comment by evollu** [comment]
it depends on RN v40+, update node modules

**Comment by nilaybrahmbhatt** [comment]
@evollu  
`"react": "^15.4.2",
   "react-native": "^0.41.2",
    "react-native-fcm": "^6.0.2"`
still not working

**Comment by evollu** [comment]
pull latest from master branch, updated scheme to build react first. should solve your build problem.

**Comment by komorebi-san** [comment]
@evollu  thank you for your reply.

I have pull a master and the build succeeded.
However, now i have a "FirebaseConstant.js" file missing instant. In which in  the.gitingore you have "app/FirebaseConstants.js"

I believe it is confidential. Can you advise what it `FirebaseConstants.KEY ` referring to? Is it the API_KEY?

**Comment by komorebi-san** [comment]
@evollu I got the server key using the following:

http://stackoverflow.com/questions/37427709/firebase-messaging-where-to-get-server-key

However, I am when I press "Send Notification" button, nothing happens. When I run in debug mode, I got the following response:

![screen shot 2017-02-09 at 7 18 08 pm](https://cloud.githubusercontent.com/assets/8327827/22781309/eacec110-eefc-11e6-8545-4ff8784824bb.png)

Am I missing something? What should be the appropriate response?

**Comment by sibelius** [comment]
@komorebi-san could u send a PR with a server example in node, so we can make sure server and app is working fine

**Comment by cfournel** [comment]
@komorebi-san i ran into the same kind of problem before, if you have a 200 from firebase, it means your request is okay even if your notification title / description is empty. Could you please provide the json you sent to firebase just to make sure its okay ? Another way to make sure it s not client side related, do you receive notifications by using firebase console ? if not, your app is not correctly setup to receive notifications.

**Comment by komorebi-san** [comment]
@cfournel 

Thank your answer. I did not change any off the `FirebaseClient.js `from the example. And I can see that the following is the send body:
```

  sendData(token) {
    let body = {
    	"to": token,
      "data":{
    		"title": "Simple FCM Client",
    		"body": "This is a notification with only DATA.",
    		"sound": "default",
    		"click_action": "fcm.ACTION.HELLO",
    		"remote": true
    	},
    	"priority": "normal"
    }
```
I have tried to send notifications using firebase console, however, I am not able to 
send nor receives. 

![screen shot 2017-02-10 at 2 32 49 pm](https://cloud.githubusercontent.com/assets/8327827/22816596/e4ce7700-ef9d-11e6-9a0c-7af20de155ba.png)

I have done the settings mentioned in the readme file, and also rebuilding the program via xcode. 

Can you let me know how do I make sure that the "Token" that I received is correct? 

@sibelius I am only working and learning from the example provided first.

**Comment by cfournel** [comment]
@komorebi-san looks like you re not sending the right token for your phone, since it failed.

Could you please confirm that : 

- You correctly setup firebase module into firebase module with cocoa pods on your ios code
- You correctly setup react native fcm code to grab your phone token code according to your firebase api key.


once you verified this, try again the firebase console with a fresh phone token (tipcally copied from react native console log) and past it to the firebase console to send a notification. it should be not fail anymore. then you could focus on your own notifications system

**Comment by evollu** [comment]
is the issue resolved?

**Comment by evollu** [comment]
close due to inactivity
