### ISSUE TITLE
Is all notifications removed when you update the app from playstore?

### ISSUE THREAD

**Issue by kenma9123** [evollu/react-native-fcm#302]
I have a very basic question for this scenario. I have an app with notification feature using this library. I published it to playstore. Then I pushed an update to it. Playstore detects the update. I updated the app. Is all the notifications(including scheduled ones) will be removed or stays?

**Comment by evollu** [comment]
Update will not clear notifications in IOS. I haven't used an android phone but assume it will be the same case. Check stackoverflow?

**Comment by kenma9123** [comment]
Does all notification stores in one place? Because I've been using `react-native-push-notification` before and it has scheduled notification using that library(in fact it's working just fine) then I decided to shift with this library. So when I execute `getScheduledLocalNotifications` will it gets the notifications from the old library?

**Comment by evollu** [comment]
try it. We are using same approach but with different constants.
for iOS you will def get something. for Android as we might be storing data into different keys, so not likely.
But if you call clearAllNotification and reschedule, it should clear old notifications scheduled by react-native-push-notification

**Comment by kenma9123** [comment]
To my curiosity, I tried to set a scheduled notification to the old app. Then the first schedule notification fires. I updated the app, I should expect the next notification to fire but I received the new notification from the updated app(yes I assigned a scheduled notification to this on load). It seems when you update an app it will remove all notifications from that same package name or something. I'm not sure but the old notifications were not firing since.

**Comment by evollu** [comment]
I'm assuming you are putting code in `componentDidMount()` in root component? It will be called very time you launch the app. which should be the cause that your old notification being cancelled

**Comment by kenma9123** [comment]
Actually that's what I wan't. I want to clear out notifications on the old app whenever I switch to this library. I don't want my users get notified twice. I think this answer my question anyway. Thank you for the inputs I was able to solve the problem :) closing it now.

**Comment by evollu** [comment]
cool
