### ISSUE TITLE
iOS 10 app receives js notification with open_from_tray flag when in a foreground edge case

### ISSUE THREAD

**Issue by JaxGit** [evollu/react-native-fcm#304]
Environment:
RN 0.38.0, rnfcm 2.5.6, iPhone 6S

Expected:
Given an iOS app which has been opened, not been minimised and not fallen into background,
when the tray has been dragged down open and covered on the app,
and a new notification has arrived,
Then the app should behave the same as it receives a notification in foreground.

Actual:
Javascript notification listener instantly receives a notification with open_from_tray flag just like an notification has been clicked and the app resumes from background.

Reason:
When the tray covers on the app and a notification arrives, willPresentNotification will get fired as the app is in foreground, however applicationState is already UIApplicationStateInactive like the most case in background. 

Solution:
For v2.5.6, It needs another flag "received_in_foreground" for this foreground edge case.
I've created a working commit with the fix for v2.5.6 in my fork https://github.com/JaxGit/react-native-fcm/commit/7b94da8cf42a57f60931b5af41111055bd18fe45

However it seems to have changed a lot in the following versions (like a "will_present_notification" type could possibly be used to handle this in v6.0.1) and the current example project is only compatible with rnfcm 4.0.0, so I'lll just leave these as a reference for those who are able to test with different versions, cheers.

**Comment by evollu** [comment]
yeah I think someone will get the problem so I introduced these flags.
I'm curious why a lot of people stays at RN<0.40

**Comment by JaxGit** [comment]
For us, we have to ensure the stability of our working product and it usually takes considerable effort to upgrade RN and make sure every libraries to catch up with.

**Comment by evollu** [comment]
I think forking the 2.5.6 version is the only way for you.
