### ISSUE TITLE
Updating my iOS app from a non-RN & non-FCM version

### ISSUE THREAD

**Issue by baldurpan** [evollu/react-native-fcm#307]
Having this annoying issue. I currently have a running app that uses both APNS and GCM and lately I've been making a new version based on RN and Firebase FCM. Everything has been going quite good so far, until I added my new app to Apple's TestFlight.
All the users that install the new version start getting double notifications. That is, they still also get the notification from the old app because the device token doesn't seem to be unregistering after the update.

- Has anyone else had this issue?
- Could this be only in TestFlight upgrades? (Don't really dare to deploy to production just to try)
- Is there any way to get the APNs token that the FCM is using so I could unregister it on my server end manually?

**Comment by evollu** [comment]
try delete the app and reinstall?

**Comment by baldurpan** [comment]
Wel, we ended up just telling all our users to logout and login again to get rid of the double notifications. So issue avoided rather than resolved. :)
Closing this.
