### ISSUE TITLE
Error loading application: Native module FIRMessagingModule

### ISSUE THREAD

**Issue by SeuJota** [evollu/react-native-fcm#308]
Hello, I followed the steps to use on android, but when I run the device, I get the following message:

![e22ed93c-5197-4588-832b-77906a74d185](https://cloud.githubusercontent.com/assets/1598228/22764693/5acc49a6-ee53-11e6-9631-cdf9e257d959.jpeg)

I am using RN 0.34.1 and react-native-fcm 2.5.6

**Comment by attilaaronnagy** [comment]
I think this is your problem.

for latest RN, use latest
for RN < 0.40.0, use v2.5.6
for RN < 0.33.0, you need to user react-native-fcm@1.1.0
for RN < 0.30.0, you need to use react-native-fcm@1.0.15

**Comment by LeusTom** [comment]
I had the same issue. Check your MainApplication.java if the "new FIRMessagingPackage()" is not include twice in the getPackages methode. 

It seems that the documentation ask to add it and the "npm link" add it too ;)
