### ISSUE TITLE
android:enabled and android:exported on service in AndroidManifest.xml

### ISSUE THREAD

**Issue by stuartlangridge** [evollu/react-native-fcm#311]
`"dependencies": {"firebase": "^3.6.8", "react": "15.4.2", "react-native": "0.41.2", "react-native-fcm": "^6.0.2"}`

Testing on an Android 6 emulator, I was having no luck receiving notifications directly targeted at the device. However, I then read http://stackoverflow.com/a/39197197/1418014 which says "I had the same problem and it is solved by defining enabled, exported to true in my service", i.e.,

`<service android:name="com.evollu.react.fcm.MessagingService" android:enabled="true" android:exported="true">`

in `AndroidManifest.xml`. I now see notifications arrive instantly as expected. However, I don't know what this means, whether it's a good idea, whether rn-fcm should do it, or anything :) So this may be something that you may want to investigate.

**Comment by evollu** [comment]
ideally they should be true by default. Could be some issue with config? I will add it to read me anyway. Thanks
