### ISSUE TITLE
large_icon not work if the app in backgound

### ISSUE THREAD

**Issue by speamy** [evollu/react-native-fcm#317]
If the app open is the large_icon in the Notification

but Background notification is the large_icon not working

please help

```    
   FCM.requestPermissions();

    FCM.on('notification', (notif) => {
      if (notif.fcm && !notif.fcm.action){

        x = {
          body: notif.fcm.body,
          priority: "high",
          title: notif.fcm.title,
          sound: "default",
          color: "#ef5350",
          show_in_foreground: true,
          icon: "ic_launcher",
          large_icon: notif.large_icon,
          lights: true,
          vibrate: 300,
          extra: notif.extra
        }

        FCM.presentLocalNotification(x);
      }

      if(notif.opened_from_tray){
        open(notif.id)
      }

    });

**Comment by speamy** [comment]
This is my log if the app is in the background:

`02-18 15:18:46.928  1243  5796 D NuPlayerDriver: notifyListener_l(0xb50a8d80), (1, 0, 0), loop setting(0, 0)
02-18 15:18:46.928  4262  5795 D MediaPlayer: setSubtitleAnchor in MediaPlayer
02-18 15:18:46.931  1482  4819 I MediaFocusControl:  AudioFocus  requestAudioFocus() from uid/pid 10020/4262 clientId=android.media.AudioManager@9b45459 req=3 flags=0x0
02-18 15:18:46.931  1243  1707 D NuPlayerDriver: start(0xb50a8d80), state is 4, eos is 0
02-18 15:18:46.931  1243  5796 I GenericSource: start
02-18 15:18:46.935  1243  5801 I MediaPlayerService: MediaPlayerService::getOMX
02-18 15:18:46.935  1243  5801 I OMXClient: MuxOMX ctor
02-18 15:18:46.936  1240  1700 I OMXMaster: makeComponentInstance(OMX.google.vorbis.decoder) in mediacodec process
02-18 15:18:46.952  1240  1240 E OMXNodeInstance: setConfig(4d80075:google.vorbis.decoder, ConfigPriority(0x6f800002)) ERROR: Undefined(0x80001001)
02-18 15:18:46.953  1243  5801 I ACodec  : codec does not support config priority (err -2147483648)
02-18 15:18:46.953  1243  5801 I MediaCodec: MediaCodec will operate in async mode
02-18 15:18:46.959  1243  5799 D AudioTrack: Client defaulted notificationFrames to 11264 for frameCount 22528
02-18 15:18:46.960  1243  5796 D NuPlayerDriver: notifyListener_l(0xb50a8d80), (6, 0, 0), loop setting(0, 0)
02-18 15:18:46.994  1235  1254 D AudioFlinger: mixer(0xa6883500) throttle end: throttle time(11)
02-18 15:18:47.005  1235  1254 D AudioFlinger: mixer(0xa6883500) throttle end: throttle time(11)
02-18 15:18:47.017  1235  1254 D AudioFlinger: mixer(0xa6883500) throttle end: throttle time(11)
02-18 15:18:47.028  1235  1254 D AudioFlinger: mixer(0xa6883500) throttle end: throttle time(11)
02-18 15:18:47.040  1235  1254 D AudioFlinger: mixer(0xa6883500) throttle end: throttle time(11)
02-18 15:18:47.052  1235  1254 D AudioFlinger: mixer(0xa6883500) throttle end: throttle time(11)
02-18 15:18:47.081  1235  1254 D AudioFlinger: mixer(0xa6883500) throttle end: throttle time(11)
02-18 15:18:47.243  1235  1254 D AudioFlinger: mixer(0xa6883500) throttle end: throttle time(1)
02-18 15:18:48.074  1243  5800 I NuPlayerDecoder: [audio] saw output EOS
02-18 15:18:48.103  1235  1254 D AudioFlinger: mixer(0xa6883500) throttle end: throttle time(1)
02-18 15:18:48.561  1235  1254 D AudioFlinger: mixer(0xa6883500) throttle end: throttle time(1)
02-18 15:18:48.648  1243  5796 D NuPlayerDriver: notifyListener_l(0xb50a8d80), (2, 0, 0), loop setting(0, 0)
02-18 15:18:48.649  1482  4817 I MediaFocusControl:  AudioFocus  abandonAudioFocus() from uid/pid 10020/4262 clientId=android.media.AudioManager@9b45459
`

**onMessageReceived is not triggered because `Log.d(TAG, "Remote message received");` is not in the Log**





_My AndroidManifest.xml:_

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.myapp"
    android:versionCode="1"
    android:versionName="1.0">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-feature android:name="android.hardware.camera" android:required="false"/>
    <uses-feature android:name="android.hardware.camera.autofocus" android:required="false"/>
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
    <uses-sdk
        android:minSdkVersion="16"
        android:targetSdkVersion="22" />

    <application
      android:name=".MainApplication"
      android:allowBackup="true"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:theme="@style/AppTheme">
      <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id"/>
           <receiver android:name="com.evollu.react.fcm.FIRLocalMessagingPublisher"/>
      <receiver android:enabled="true" android:exported="true"  android:name="com.evollu.react.fcm.FIRSystemBootEventReceiver">
        <intent-filter>
          <action android:name="android.intent.action.BOOT_COMPLETED"/>
          <action android:name="android.intent.action.QUICKBOOT_POWERON"/>
          <action android:name="com.htc.intent.action.QUICKBOOT_POWERON"/>
          <category android:name="android.intent.category.DEFAULT" />
        </intent-filter>
      </receiver>

      <service android:name="com.evollu.react.fcm.MessagingService" android:enabled="true" android:exported="true">
        <intent-filter>
          <action android:name="com.google.firebase.MESSAGING_EVENT"/>
        </intent-filter>
      </service>

      <service android:name="com.evollu.react.fcm.InstanceIdService" android:exported="false">
        <intent-filter>
          <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
        </intent-filter>
      </service>

      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:launchMode="singleTop">

        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>

        <intent-filter>
            <action android:name="fcm.ACTION.HELLO" />
            <category android:name="android.intent.category.DEFAULT" />
        </intent-filter>

      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>

</manifest>
`

**Comment by vincent-the** [comment]
the same problem under android!

/cc @evollu

**Comment by akajack** [comment]
For `presentLocalNotification` the parameter `large_icon` must be a string, like `icon` parameters.
Example:

          icon: "ic_launcher",
          large_icon: "ic_notification",

The `ic_notification` icon must be in the `mipmap` folder.
You can find the icon specifications in the [official guide](https://developer.android.com/guide/practices/ui_guidelines/icon_design_status_bar.html)

**Comment by akajack** [comment]
Same problem myself too

**Comment by akajack** [comment]
I found solution here: [https://medium.com/@Miqubel/mastering-firebase-notifications-36a3ffe57c41](https://medium.com/@Miqubel/mastering-firebase-notifications-36a3ffe57c41)

This article suggests this:
> don’t use the “notification” message payload and use “data” instead.

In fact, changing the call I do (removing the `notification` parameter), both `icon` and `large_icon` parameters works.

**Comment by evollu** [comment]
right. notification message is handled by Firebase SDK and they have limited feature.
large_icon only works with data

**Comment by devbriguy** [comment]
Hi @akajack I tried the data payload request with`big_text` set in the `custom_notification` and I still see the notification in the system tray as the without BigTextStyle. Any pointers in getting that working?

**Comment by devbriguy** [comment]
Hi @akajack again. I was mistaken. I was able to find out that if you drag down on the notification in the system tray the `big_text` appears. FYI notification is not expanded by default.
