### ISSUE TITLE
Can I display a banner in sleep mode?

### ISSUE THREAD

**Issue by allenkim67** [evollu/react-native-fcm#319]
react-native:  0.41.2,
react-native-fcm: 6.0.3
android

Is it possible to show a banner in sleep mode?

I'm using custom_notification so I can see the banner when my app is running in the background. But in sleep mode I can't see a banner (but I can hear a notification sound). There were some posts that seemed to imply that this isn't something that's supported but I wasn't 100% sure. So I just want to ask if this is possible using just this library.

**Comment by evollu** [comment]
Do you know how to do it with native code? An example will be helpful since I don't know android notification feature much.

**Comment by dino115** [comment]
Hi, we had trouble with this too.
Check the notification settings of your android device, some custom androids deactivate this by default. For example, on xiaomi devices you have to activate notifications on the lock screen explicitly in your device settings.
Then it works with the custom_notification feature as well. (newest rn and rn-fcm version)

**Comment by evollu** [comment]
Thanks for the clarification. I will close this for now
