### ISSUE TITLE
Android release build fails due to ads ID missing.

### ISSUE THREAD

**Issue by Naoto-Ida** [evollu/react-native-fcm#320]
I'm getting the following error on Android release builds:

```
D/FA: Unable to get advertising id: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.android.gms.ads.identifier.AdvertisingIdClient$Info.getId()' on a null object reference: com.google.android.gms.internal.zzaua.zzfG(Unknown Source)
```

I followed the setup instructions for Android.
I have no intentions of supporting AdMob, so I want to resolve this error without enabling AdMob.

**Comment by evollu** [comment]
This library doesn't rely on AdMob. Are you sure it is caused by this repo?
