### ISSUE TITLE
IOS :- Receive notification payload twice when app is in foreground.

### ISSUE THREAD

**Issue by prince8verma** [evollu/react-native-fcm#321]
I implemented RNF for both android and ios, it is working fine in both platforms, as i tested my app in  ios simulator then the app received notification payload only once, but in iphone it receives  notification payload twice with same "gcm.message_id".

documentation for ios payload is outdated, in simulator i receives the notification payload as mention in docs, but in distribution, in iphone, it receives notification payload as 
 {
   "aps" : {
       "alert" : {
            "body" : "great match!",
            "title" : "Portugal vs. Denmark",
          },
      "badge" : 1,
      "customKey" : "customValue"
    }
}

update this info ASAP, 
provide me the solution for the above problem.

**Comment by evollu** [comment]
are these 2 notification exactly the same? Does one of them have extra flags?
Are you testing with app running in foreground?

**Comment by prince8verma** [comment]
Yeah, these two notifications are exactly same with same gcm.message_id..
And this happenning only when app is in foreground.
So at now i had implemented the check for same gcm.message_id, which solved the problem

**Comment by prince8verma** [comment]
Provide the solution for this asap, i managed this now, but i need a permanent solution.
or do you think my solution is fine.

**Comment by evollu** [comment]
hmm i think the reason is that one message comes from FCM socket channel and one comes from regular APN push notification. To verify that, you can add break points in appdelegate.m's notification related hooks. If I'm right, there should be only 1 tigger when you use real device and 0 when you use emulator.
can you try that?

**Comment by evollu** [comment]
@prince8verma let me know if you still have issue with this
