### ISSUE TITLE
Help us to know about changes in Latest(6.0.3) version

### ISSUE THREAD

**Issue by rengasahusoft** [evollu/react-native-fcm#324]
So I updated the React Native and React native fcm

## IOS
  - I followed the ReadME to and Made changes, I tried to run my app on ios Simulator after updating for the first time, app crashed. Then i tried with device, some how app is running.
  - I am developing Chat app so when i am in thread i need to receive the Notification of someother thread , so i was using `FCM.presentLocalNotification`  to present the local Notification, But after updating I was receiving Two Notificaiton Now, So i removed the Local Notificaiton. Now it works fine.

## Android
 - I have attached the Image of what error i am getting after adding  
   `compile 'com.google.firebase:firebase-core:10.0.1' ` in `app/build.gradle`
- I am Not getting LocalNotification At all

Couldn't debug Since it all involves lots of Native code

<img width="1269" alt="screen shot 2017-02-20 at 1 59 57 pm" src="https://cloud.githubusercontent.com/assets/19145173/23117335/39fedbe6-f775-11e6-956f-15e7f2daf096.png">

Help Me regarding what are all the changes Have been made

**Comment by sibelius** [comment]
please follow readme to setup the native part

**Comment by tamhv** [comment]
Should be `compile 'com.google.firebase:firebase-messaging:10.2.0'` instead of `firebase-core`!
I can only made it works on real devices, not emulator, both android and ios.

**Comment by rengasahusoft** [comment]
@tamhv Thanks. Let me try

Does Local Notification works for you in android ?

**Comment by tamhv** [comment]
I tried this code
```
FCM.presentLocalNotification({
      id: 'UNIQ_ID_STRING',                               // (optional for instant notification)
      title: 'My Notification Title',                     // as FCM payload
      body: 'My Notification Message',                    // as FCM payload (required)
      sound: 'default',                                   // as FCM payload
      priority: 'high',                                   // as FCM payload
      click_action: 'ACTION',                             // as FCM payload
      badge: 10,                                          // as FCM payload IOS only, set 0 to clear badges
      number: 10,                                         // Android only
      ticker: 'My Notification Ticker',                   // Android only
      auto_cancel: true,                                  // Android only (default true)
      large_icon: 'ic_launcher',                           // Android only
      icon: 'ic_launcher',                                // as FCM payload, you can relace this with custom icon you put in mipmap
      big_text: 'Show when notification is expanded',     // Android only
      sub_text: 'This is a subText',                      // Android only
      color: 'red',                                       // Android only
      vibrate: 300,                                       // Android only default: 300, no vibration if you pass null
      tag: 'some_tag',                                    // Android only
      group: 'group',                                     // Android only
      my_custom_data: 'my_custom_field_value',             // extra data you want to throw
      lights: true,                                       // Android only, LED blinking (default false)
      show_in_foreground: true                            // notification when app is in foreground (local & remote)
    })
```
Result: (with a sound)
![screen shot 2017-02-20 at 6 03 07 pm](https://cloud.githubusercontent.com/assets/5440638/23122559/4807a868-f797-11e6-8e9c-2cbf09428802.png)
![screen shot 2017-02-20 at 6 03 24 pm](https://cloud.githubusercontent.com/assets/5440638/23122572/4ef6c8fc-f797-11e6-8783-e39698d88738.png)

**Comment by evollu** [comment]
@tamhv I like your font 👍 
@rengasahusoft is your issue solved?

**Comment by roshangm1** [comment]
I am getting this error:
react native - 0.42.3
react native fcm - ^6.2.3
