### ISSUE TITLE
_OBJC_CLASS_$_FIRMessaging", referenced from in iOS Xcode 8

### ISSUE THREAD

**Issue by gagancdac** [evollu/react-native-fcm#326]
Hello to All,

I am integrating firebase cloud messaging framework for my iOS app for push notification implementation. I install the cocoa pod file and it is successfully installed on the mac.
Now i opened the MessagingExample.xcworkspace file of messaging sample app code.

But write now i am facing issue regarding the frameworks, it shows me:

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_FIRMessaging", referenced from:
      objc-class-ref in ViewController.o
      objc-class-ref in AppDelegate.o

Please help me and get me out of this issue. For more clarification screenshot is attached.

Thanks in Advance:)

![screen shot 2017-02-22 at 10 10 16 am](https://cloud.githubusercontent.com/assets/25945296/23197574/395a55c6-f8e7-11e6-9a6a-69ed1efed443.png)

**Comment by evollu** [comment]
looks like build target issue?
Can you try the example project in the repo?

**Comment by evollu** [comment]
close due to inactivity

**Comment by Sreekanth1995** [comment]
I got the same error as above, please help
