### ISSUE TITLE
notification receives but doesn't appear on Ios 10.2  

### ISSUE THREAD

**Issue by siemya** [evollu/react-native-fcm#327]
@evollu Hey, 

i am using version 2.5.6.

This is my backend request object;

```
{
  to: "XXXX"
  notification: {
    body: "notification",
    sound: 'default'
  },
  priority: "high",
  show_in_foreground: true,
  content_available: true
}
```
        
and this is the object i log inside `didReceiveRemoteNotification`;

```
{ 
 aps: 
   { 
    alert: 'notification',
     sound: 'default',
     'content-available': '1' 
  },
  opened_from_tray: 0,
  'gcm.message_id': '0:1487863844312842%6b84bc066b84bc06' 
}
```

İt works under ios 10, but doesn't appear on ios 10.2, both in foreground and background.

**Comment by evollu** [comment]
can you put "show_in_foreground" in "data"?
```
{
  to: "XXXX"
  notification: {
    body: "notification",
    sound: 'default',
    priority: "high"
  },
  data: {
    show_in_foreground: true,
  }
  content_available: true
}
```

**Comment by siemya** [comment]
i did but no changes...

**Comment by evollu** [comment]
my phone is 10.2.1 and it works fine. here is my payload
```
{
    "to":"xxxx",
    "content_available": true,
    "notification": {
        "title": "hello",
      "body": "yo",
        "click_action": "123"
    },
    "data": {
    	"show_in_foreground": true,
        "a": 1
    },
  "priority": "high"
  }
```

**Comment by jo2010** [comment]
@evollu if I send message from firebase notification console UI, how do I set show_in_foreground ? I tried the custom data section, but didn't help.

**Comment by jo2010** [comment]
@evollu  sorry, ignore it. I misunderstood

**Comment by lucidvision** [comment]
Hi, this problem is still happening for devices with ios 10 and above and using react native fcm  version 2.5.6.

I receive the notification in FCM.on, but it doesn't pop up in tray or when app is in background.

**Comment by lucidvision** [comment]
@evollu Can you confirm that version 2.5.6 works on ios 10.2+?

I'd like to know if it's a problem with my configuration or if I'll need to update to the latest version of react-native-fcm to receive the notifications.

**Comment by evollu** [comment]
close due to inactivity

**Comment by mykelaballe** [comment]
was this solved? im having this problem in ios version 10+. RN version 0.34.0 and FCM version 2.5.6. the notification can be received but not displayed

**Comment by jaimecorrea** [comment]
Same problem here, it works well in all iOS version but in 10.2 is not...
