### ISSUE TITLE
FCM.getFCMToken returns undefined (ios 9.2)

### ISSUE THREAD

**Issue by AppliKeySolutions** [evollu/react-native-fcm#331]
"react-native-fcm": "^6.0.3",
"react-native": "~0.41.0"

I did all of installations steps from README. Build succeed. Tested on iphone 5s (on ios 9.2).

FCM.requestPermissions();
FCM.getFCMToken().then(token => {
   // token is undefined             
});

**Comment by krishbhattacharyya** [comment]
I am facing same problem for some devices. But when I open the app again it returns token.

**Comment by bernatfortet** [comment]
Same issue here

**Comment by evollu** [comment]
it could take a while for Firebase to get the token. Rely on token refresh event for getting latest token

**Comment by MaheshNandam** [comment]
@evollu ,

Facing the same issue as FCM.getFCMToken() is giving undefined token value, please look into this issue ASAP.
My Package:
"react": "16.0.0",
"react-native": "0.50.4",
"react-native-fcm": "^10.0.3",

**Comment by mymai91** [comment]
same issue
