### ISSUE TITLE
Determined enabled iOS push notification types

### ISSUE THREAD

**Issue by YarGnawh** [evollu/react-native-fcm#335]
RN 0.39.2 , RN FCM 2.5.1 on iOS9+ devices

Is there a method to determine which notifications types are enabled? This is for the "Settings" page within my app. Is there a method that bridges the "enabledRemoteNotificationTypes" method?

**Comment by evollu** [comment]
you can use react-native's PushNotificationIOS to check.
currently this repo doesn't have the bridging
