### ISSUE TITLE
tvOS support?

### ISSUE THREAD

**Issue by foggy1** [evollu/react-native-fcm#336]
Hi, not having an issue, just a question:

Are there any plans to support tvOS?  I know that Firebase proper technically only supports iOS, Web, and Android, but given that react native mostly works on tvOS and it really is just iOS 10 code right now, is there any work being done on this?  I think the only thing (that I can tell) that is an issue is the particular hooks used in the native iOS code.

**Comment by evollu** [comment]
TVOS uses an SDK slightly different from phone OS so I don't know. It will support as long as Firebase native SDK supports it
