### ISSUE TITLE
FCM pricing

### ISSUE THREAD

**Issue by anton-aleksandrov** [evollu/react-native-fcm#340]
According to [this](https://firebase.google.com/pricing/):
> Included Free Analytics, App Indexing, Authentication, **Cloud Messaging**, Crash Reporting, Dynamic Links, Invites, Notifications & Remote Config

Are there any additional costs? I do not intend to use firebase db or any other services atm. FCM can be used independently from all other Firebase services, right? I don't have to use their authentication or db or whatever else to be able to send Push Notifications to individual users without any limits. Right?

Also, check out a typo in "new issue guidelines":
> What **verion** of RN and react-native-fcm are you running?

**Comment by sibelius** [comment]
FCM is free

**Comment by evollu** [comment]
thanks @sibelius
