### ISSUE TITLE
FCM.on('notification') is not being called 

### ISSUE THREAD

**Issue by janaka120** [evollu/react-native-fcm#341]
RN 0.38 , RN FCM 2.5.6 on Android 6, device Samsung Galaxy A5 

If the app is in background or killed, when I clicked on notification, App was opened but FCM.on('notification') is not being called.

**Comment by antti-rauhala** [comment]
+1

Notification listener is called when user clicks notification on iOS device. On Android, callback is not called when user clicks notification.

My configuration was: RN 0.41.0, RN FCM 6.1.0. Android 6.0.1, device Samsung Galaxy S7.

**Comment by emretekince** [comment]
+1

**Comment by MichaelDanielTom** [comment]
+1, was anyone able to figure this out? Having the same problem on Android.

**Comment by vincent-the** [comment]
+1

**Comment by emretekince** [comment]
I solved. Use this:

`FCM.getInitialNotification().then(notif=>console.log(notif));`

**Comment by MichaelDanielTom** [comment]
Hey Guys,
I solved the problem for me: In my MainActivity.java, I had overridden onNewIntent, but forgot to call super. Adding the super call solved the problem, and handler in FCM.on(FCMEvent.Notification, handler) is now called when a user taps on the notification while the app is in the background.

`    
@Override
public void onNewIntent(Intent intent) {
    super.onNewIntent(intent);
    this.setIntent(intent);
}
`

**Comment by evollu** [comment]
seems problem is solved. please reopen if it is not the case

**Comment by malangaveuday** [comment]
cocoapods
Firebase (5.3.0)
FirebaseMessaging (3.0.2)
FirebaseInstanceID (3.1.1) 

npm
"react-native-fcm": "^16.1.0"

`
FCM.on(FCMEvent.Notification, notif => {
   console.log('notification from firebase', notif);
})
`
This listener not invoking when I am opening schedule notification from the notification bar in iOS.

**Comment by malangaveuday** [comment]
@evollu I have tried for both scenario first app in the background and second app killed, but on both times not able to listen to notification opening event.

**Comment by evollu** [comment]
@malangaveuday can you try the example project and see if it works?
