### ISSUE TITLE
Notification handler err issue

### ISSUE THREAD

**Issue by danielwilson8654** [evollu/react-native-fcm#343]
Issue : console.error('Notification handler err', err)
Summary: 
react-native-cli: 2.0.1
react-native: 0.40.0
react-native-fcm": "^6.1.0",
I'm testing on Android device 6.0.1
The app is running in Foreground
I can share the project if needed.

**Comment by leobeosab** [comment]
Bump, same issue here.

**Comment by leobeosab** [comment]
The issue seems to extend from line 33 in PushController.js
`if (Platform.OS == 'ios')`
where Platform is not defined I commented this out and it worked. I'll update this when I find out what to import for Platform to work.

**Comment by danielwilson8654** [comment]
I also tried both solutions, it but the problem still remains.

**Comment by leobeosab** [comment]
You're welcome I added a pull request to fix the issue for new users.

**Comment by nilaybrahmbhatt** [comment]
same issue here...

**Comment by evollu** [comment]
@nicolasdanelon it means your notification callback throws an error

**Comment by sukumardv3101** [comment]
same issue here...
