### ISSUE TITLE
Get APNS token?

### ISSUE THREAD

**Issue by patrickdevivo** [evollu/react-native-fcm#347]
I apologize if this is covered somewhere, but I couldn't find it in the docs / other issues.

I was wondering if it's possible to use this library to get the APNS token as well as the FCM token. I'd like to use both FCM and Mixpanel to send notifications, Mixpanel requires the APNS token.

**Comment by sibelius** [comment]
it is not possible, u need to use react-native-push-notification

**Comment by patrickdevivo** [comment]
OK, thank you

**Comment by sibelius** [comment]
@patrickdevivo u should open an issue on mixpanel, so they can accept FCM tokens as well

**Comment by patrickdevivo** [comment]
I believe they are planning that integration, I will see if there's an on going discussion about it. @sibelius thanks for the help!
