### ISSUE TITLE
Msg is received but red screen with unknown file

### ISSUE THREAD

**Issue by alexe100** [evollu/react-native-fcm#348]
Hi! Great component...

RN: 0.42
react-native-fcm@6.1.0
iOS 9.3

The app receives push motifs in background well and when in foreground at the time of push notify reception I see the red screen attached. I tried to find the main.jsbundle but not found. It seems that the app executing in iPad (development stage) is dependent or linked to the private IP of the host computer that has installed the app in the iPad... When I dismiss the red screen I see the alert I have in the FCM.on(FCMEvent.Notification, async (notif) =>   event handler.
![image](https://cloud.githubusercontent.com/assets/11243158/23774660/b09f2ddc-051c-11e7-9e6b-71efacf24b40.png)

Thanks a lot

Imo

**Comment by antoniuschan99** [comment]
I had this issue, this one worked:

https://github.com/evollu/react-native-fcm/issues/343

**Comment by orphnahk** [comment]
i had the same issue. when app is minimized or closed, it' ok, I followed #343 but not work.
![screenshot_1490691417](https://cloud.githubusercontent.com/assets/19589099/24397096/75134eb2-13cf-11e7-8d0b-b8fa9ea5d56d.png)

**Comment by evollu** [comment]
duplicate
