### ISSUE TITLE
[IOS] Error with Setup

### ISSUE THREAD

**Issue by alexanderniebuhr** [evollu/react-native-fcm#35]
Hey,

If I try to use this package, and try to write [FIRApp configure]; I get an error that this command is undefined.

Any Ideas or suggestions?

Thanks
Alex

**Comment by evollu** [comment]
can you bring a screenshot of error?
Have you added the import on the top?

**Comment by alexanderniebuhr** [comment]
<img width="1400" alt="fcm" src="https://cloud.githubusercontent.com/assets/15894713/16658739/b66f48c6-4467-11e6-886c-ef567678a815.png">

As you see on the screenshot I got more errors today.
I added the Framework with this Documentation [Firebase Official](https://firebase.google.com/docs/ios/setup#frameworks)

Because I am not allowed to use pod.

Hope you could help me

**Comment by evollu** [comment]
since the build can't even recognize `FIRApp`, can you check if the library is linked to the project in Build Phase?

**Comment by alexanderniebuhr** [comment]
<img width="775" alt="fcm 2" src="https://cloud.githubusercontent.com/assets/15894713/16659188/589d446c-4469-11e6-8b11-64fe2ed9d6ac.png">

As I can see (screenshot) everything is linked correctly?

**Comment by evollu** [comment]
not using cocoapod seems be a good idea given the issues we've encountered lately. Let me try this approach a bit more and get back to you

**Comment by alexanderniebuhr** [comment]
<img width="1018" alt="fcm 3" src="https://cloud.githubusercontent.com/assets/15894713/16659362/f32c1e5e-4469-11e6-8c2f-e1d0c2822f6e.png">

I got rid of two from the errors with the rnpm linking again. Now its just the '[FIRApp configure];' error seen above. 

Thanks, hope we will find a fix soon ;)

**Comment by evollu** [comment]
question: How did you make RNFIRMessaging compile? It complains
`'FirebaseAnalytics/FirebaseAnalytics.h' file not found`

**Comment by evollu** [comment]
for your issue, try add `#import "firebase.h"` on the top

**Comment by alexanderniebuhr** [comment]
I even didn't get it to compile. Get the same error as you.
Even if I add the Import, I get the error. See my first Screenshot in this issue :(

**Comment by evollu** [comment]
I see :(

**Comment by alexanderniebuhr** [comment]
Well actually, the `[FIRApp configure];` is not the problem, if I start compiling the error is going away and the only error left is: 
<img width="516" alt="fcm 4" src="https://cloud.githubusercontent.com/assets/15894713/16659994/decccc62-446c-11e6-8424-49c8d0ff48fa.png">

**Comment by evollu** [comment]
try pulling another Firebase.h file into the library project?

**Comment by alexanderniebuhr** [comment]
What do you mean?

**Comment by alexanderniebuhr** [comment]
I still have the Problem with RNFIRMessaging

**Comment by evollu** [comment]
working on it

**Comment by evollu** [comment]
@alexanderniebuhr I'm still getting `'FirebaseAnalytics/FirebaseAnalytics.h' file not found`. Do you have FirebaseAnalytics.framework?

**Comment by alexanderniebuhr** [comment]
Nop. As I said I used official Firebase Documentation with the following [SDK](https://dl.google.com/firebase/sdk/ios/3_3_0/Firebase.zip) provided by them

**Comment by evollu** [comment]
For analytics, did you just move 4 files into project?

**Comment by alexanderniebuhr** [comment]
I moved the 4 in the Analytics folder and the 2 in the Messaging folder to my project

**Comment by evollu** [comment]
can you share your project? I just can't get working

**Comment by alexanderniebuhr** [comment]
Nob sorry. Its not possible :( 

Any other Ideas for fixing

**Comment by evollu** [comment]
try changing `react-native-fcm/ios/RNFIRMessaging.h` change to `#import "Firebase.h" and add a Firebase.h file in the project

**Comment by alexanderniebuhr** [comment]
Still getting following error:

<img width="516" alt="fcm 4" src="https://cloud.githubusercontent.com/assets/15894713/16663855/0e48b44a-447e-11e6-8300-3d44fd8387ae.png">

**Comment by evollu** [comment]
have you added he Firebase.h file in the project (RNFIRMessaging.xcodeproj)?

**Comment by alexanderniebuhr** [comment]
Yep after compiling failed now:

<img width="460" alt="fcm 5" src="https://cloud.githubusercontent.com/assets/15894713/16663974/83633e08-447e-11e6-9cba-fc280cbb7627.png">

**Comment by evollu** [comment]
the same issue as I have. Need to find out where this header file is located

**Comment by alexanderniebuhr** [comment]
Ok thanks :/ 

Hope this will be fixed soon

**Comment by evollu** [comment]
If you have time could you help me look for it? Since your main project can find it somehow

**Comment by alexanderniebuhr** [comment]
I'll try my best, and will post any news here.

**Comment by evollu** [comment]
done!

**Comment by alexanderniebuhr** [comment]
Great to hear :) What is the fix?

**Comment by evollu** [comment]
Simple fix is adding search path in the RNFIRMessaging, both header and framework. I'm trying another way which embed Firebase frameworks into this repo

**Comment by alexanderniebuhr** [comment]
Ok great I am up to the cool fix coming out soon as an update here :)

**Comment by evollu** [comment]
no..it is not a good idea to put frameworks there.. I will post the fix in another branch and you can test it out

**Comment by alexanderniebuhr** [comment]
Well .. Thanks, but you also just could make a little manual for the fix. :)

**Comment by evollu** [comment]
I'm leaving the cocoapod route myself too so that the project is much cleaner and straight forward. so just wait couple more minutes

**Comment by alexanderniebuhr** [comment]
Thats fine :) I am very happy you found a way. 

True story. But since I did experience very very very bad stuff with cocoa pod I am now on my way to actually control everything manually

**Comment by evollu** [comment]
try nopod branch

**Comment by alexanderniebuhr** [comment]
Thanks, I will have a look

**Comment by alexanderniebuhr** [comment]
HM :( Sorry that I still have an error:

<img width="1120" alt="fcm 6" src="https://cloud.githubusercontent.com/assets/15894713/16666763/5c3087f4-4489-11e6-9bf2-0a1ebd362192.png">

Am I doing anything wrong?

**Comment by evollu** [comment]
The zip file is missing a framework file. I pull it from cocoapod. Any way i can share it for download?

**Comment by alexanderniebuhr** [comment]
That would be great. I really don't know why the Official SDK zip is missing one :(

**Comment by alexanderniebuhr** [comment]
Why you not include the framework file in the 'nopod' branch under an folder 'frameworks'?

**Comment by evollu** [comment]
pushed

**Comment by alexanderniebuhr** [comment]
GREAT!! Don't get the error anymore :) :D

But ... Now I have this problem :(

<img width="699" alt="fcm 7" src="https://cloud.githubusercontent.com/assets/15894713/16667344/48b0b034-448c-11e6-8a0a-513e2ce55fbd.png">

But in my directory under .../ios/ I added the file from Firebase Console

**Comment by evollu** [comment]
you need to download info.plist from firebase console.
you need to go to xcode project settings=>Capabilities=>Background Modes => enable remove notifications

**Comment by alexanderniebuhr** [comment]
Ok strange... I've done that, but needed to restart Xcode :O Now I am curious if sending an message from console will work

**Comment by evollu** [comment]
ok. keep in mind that ios emulators don't not support push notification

**Comment by alexanderniebuhr** [comment]
Yeah I know that, but I am not Sure if my APN Certificate will work :/

**Comment by alexanderniebuhr** [comment]
Ok my certificates are wrong :/

Could you please tell me my error. I have done anything according to the following introduction:

https://firebase.google.com/docs/cloud-messaging/ios/certs

**Comment by evollu** [comment]
I can't see your console :)
I remember I downloaded a profile and converted to .p12 before uploading to gcm.

**Comment by alexanderniebuhr** [comment]
<img width="702" alt="fcm 9" src="https://cloud.githubusercontent.com/assets/15894713/16667945/21a1dfa6-448f-11e6-987c-88f05d2f29cc.png">

Forgot the screenshot :O (FACEPALM)
Yeah I did this too with the certificate

**Comment by alexanderniebuhr** [comment]
I don't get it do run :(

I just want to use Firebase Analytics and Notification (push) for my app :/ Why is this so complicated :O

**Comment by evollu** [comment]
1. that token can be used for data notification, just not associated with any APN i guess
2. Disconnecting from FCM when going background is suggested by google, you should get data notification once you resume

**Comment by evollu** [comment]
are you having android project?

**Comment by alexanderniebuhr** [comment]
Ok. I am not sure if my problem is clear.

I need to use Push Notifications for my Project. As such I don't know why I am not getting any Push Note to my iPhone 6.

Is something wrong with my certificates. (Seen in the last Screenshot)?

Any Ideas or Suggestions?

Nop Android is still in Development and not in a state for testing

**Comment by evollu** [comment]
If device is registered correctly, you should get a token. I don't see it in screenshot
How did you close/kill the app when you test notification?

**Comment by alexanderniebuhr** [comment]
Here my console, is this all correct?:
<img width="699" alt="fcm 10" src="https://cloud.githubusercontent.com/assets/15894713/16677600/e65ad1de-44d7-11e6-8b7f-c693d3893a80.png">

I just open my App and push the Homebutton, to put App in background.

**Comment by alexanderniebuhr** [comment]
And in saying that Firebase Analytics does Work for me. So in my Firebase console I am able to see some analytics data. But I can't get the Firebase Push Notification to work

**Comment by evollu** [comment]
Just tried I can send and show notification.
Can you try sending notification target all device under ios project?

**Comment by alexanderniebuhr** [comment]
I've done both. With the FCM Token for my device, and with the target all device. 

I don't now. What am I doing wrong :(

**Comment by evollu** [comment]
Can you check if the app is blocking notification? Did you see the prompt that ask permission for notification? Try reinstall?

**Comment by alexanderniebuhr** [comment]
I'll try reinstall. But I allowed my App for Notification, yeah I did see the prompt.

I have no Idea :(

**Comment by alexanderniebuhr** [comment]
Not still no working. But what could be the Problem?

Just checking if you use the same setup than me :)

Were have you put the Usage code from you Install Guide?
What React-Native Settup are you running 'Release or Debug' sheme?
What Signing 'Developer or Distribution'?

**Comment by evollu** [comment]
signing is developer. But I may have used production App Push Service cert to generate .p12 file

**Comment by evollu** [comment]
Going to sleep now. good luck

**Comment by alexanderniebuhr** [comment]
Ok same Setup here. I actually have an important meeting here. So hope we can fix this tomorrow. :(

**Comment by alexanderniebuhr** [comment]
So after some mature Meetings with my lead senior dev, cto and ceo. I still can't get the notifications to work :(

Any Ideas or Suggestions for my problem?

**Comment by evollu** [comment]
hey can you join gitter of this repo? The issue conversation is too long and it is not related to the issue now

**Comment by alexanderniebuhr** [comment]
Done

**Comment by evollu** [comment]
configuration issue, check gitter
