### ISSUE TITLE
Getting notifications in console but no popups.

### ISSUE THREAD

**Issue by antoniuschan99** [evollu/react-native-fcm#350]
Hey, I am receiving local notifications in XCode logger. But the popups (banners and stuff) don't appear. Very strange. Any ideas? Also, I am using ios 9.3.5 since my iPad is old.

The logger below is fired from FCM.on(FCMEvent.Notification), but nothing happens at  FCM.presentLocalNotification().

Also not getting remote notifications

{ notification: 
   { title: 'Notification Alert',
     sound: 'default',
     show_in_foreground: 'true',
     click_action: '123',
     e: '1',
     sound2: 'default',
     body: 'test' },
  collapse_key: 'XXXXXXXXXXX',
  opened_from_tray: 0,
  _notificationType: 'remote_notification',
  _completionHandlerId: 'XXXXXXXXXXX',
  from: 'XXXXXXXXXXXX',
  finish: [Function: finish],
  _finishCalled: true }

(I changed the values to XXXXXXX for some)

**Comment by antoniuschan99** [comment]
Background only works for now. I had restarted the iPad after install and also removed the swizzle from info.plist and then readded it: FirebaseAppDelegateProxyEnabled

Foreground still does not work for some reason. In console it says it connects to firebase but then another message saying it could not connect to firebase because it's already connected.

The issue with FCM.presentLocalNotification is still there. Nothing happens.

**Comment by evollu** [comment]
foreground iOS notification banner is only available iOS>10.

**Comment by jasan-s** [comment]
I set the key FirebaseAppDelegateProxyEnabled to NO and still I don't get any banners . I'm using iOS 10.3.2
