### ISSUE TITLE
could not find google.firebase

### ISSUE THREAD

**Issue by anbublacky** [evollu/react-native-fcm#351]
I'm using react native version 0.40, and followed the read me from this repo and i'm getting the following error when i try to run react-native run-android

could not find any matches for com.google.firebase:firebase-messaging:+ as no versions of com.google.firebase:firebase-messaging are available.

I have no clue what is the source for this error. I searched everywhere and i couldnt debug this problem.

**Comment by anbublacky** [comment]
Updating the Google play services to 39 and google repository to 44 (versions which were available at this time), fixed my issue.

**Comment by evollu** [comment]
cool

**Comment by GrishmaM** [comment]
im facing the same issue, my Google play services version is 46 and google repository is 58
