### ISSUE TITLE
Could not find a valid GoogleService-Info.plist

### ISSUE THREAD

**Issue by AurelienPillevesse** [evollu/react-native-fcm#353]
## Description
I installed Firebase/Messaging thanks to Pod.
So I add "pod 'Firebase/Messaging'" in my Podfile.
But everytime I build and run my app on my phone. I have an error that's in the title so the app stops running instantly.

I followed the tutorial and add my certs to the GoogleService-Info.plist file before downloaded it.
I added my plist file in the ios folder and in ios/my-app-name folder to try but always the same problem.

If someone can help me.
Thanks! 

## Device

RN: 0.42
Running on iOS 5S
App can't run

## Update
Problem solved.

**Comment by timomeh** [comment]
@AurelienPillevesse Could you tell us how you solved that problem? :) Would be very helpful for people having the same problem.

**Comment by timomeh** [comment]
For anyone else having that issue: You can't simply put the GoogleServices-Info.plist in the ios project directory. You need to drag it into the xcode project navigator, so the file is included in the build. See http://stackoverflow.com/a/31299917
