### ISSUE TITLE
(iOS) Undefined is not an object when calling RNFIRMessaging.requestPermissions() 

### ISSUE THREAD

**Issue by yakirbu** [evollu/react-native-fcm#355]
Android version works great. However, after following the instructions for integrating it with my iOS app, I ran into the Undefined is not an object error. 

(iOS) Undefined is not an object when calling RNFIRMessaging.requestPermissions()

**Comment by antti-rauhala** [comment]
Should it be
`FCM.requestPermissions();` ?

**Comment by yakirbu** [comment]
@antti-rauhala 
Why do you mean? RNFIRMessaging.requestPermissions() is the error that I get when I open the app, it's not a code that I wrote, in Android everything works well though.

**Comment by antti-rauhala** [comment]
OK it was the error you get when you call FCM.requestPermission(). Can't say then..double check all iOS instructions, also "Xcode post installation steps"

**Comment by MaxToyberman** [comment]
try going to the project navigator in Xcode choose your project -> Libraries ->RNFIRMessaging -> Products and drag libRNFIRMessaging.a to Build Phases -> Link Binary with libraries

**Comment by yakirbu** [comment]
I solved by opening a new iOS project, so as for now I"ll mark it as closed.

**Comment by pqhoang** [comment]
I have a problem in RNFIRMessaging.requestPermissions in libraby RN-FCM
i used RN v 0.46.3 and RN-FCM 10.0.3

![screen shot 2018-05-04 at 09 27 21](https://user-images.githubusercontent.com/18663563/39610993-55f5133a-4f7e-11e8-89d9-753ce3752bdf.png)

**Comment by evollu** [comment]
@pqhoang mostly it is integration issue. maybe you haven't linked this repo correctly in iOS project. Try compare your project with example
