### ISSUE TITLE
Can't get local notifications to work on iOS

### ISSUE THREAD

**Issue by dht** [evollu/react-native-fcm#356]
I am trying to get local notifications to work on iOS. It is not shown on all states:
background, foreground, locked screen

I followed the installation procedure twice, once on my project and once on an empty project. This is the method I invoke:

    FCM.scheduleLocalNotification({
        fire_date: (new Date().getTime() + inSeconds * 1000),      //RN's converter is used, accept epoch time and whatever that converter supports
        id: 'ABCD',    //REQUIRED! this is what you use to lookup and delete notification. In android notification with same ID will override each other
        title,
        body,
        sound: "default",
        priority: "high",
        show_in_foreground: true,
        local: true,
    })

This method gets fired:
 -(void)application:(UIApplication *)application didReceiveLocalNotification:(UILocalNotification *)notification 

But the notification is not shown.

**Comment by alxvallejo** [comment]
first of all, you should specify in the title that this is a scheduled notification. Second, why did you close this issue?

**Comment by dht** [comment]
I am not sure. I think it was because I couldn't reproduce what solved it.
