### ISSUE TITLE
to pod or not to pod

### ISSUE THREAD

**Issue by evollu** [evollu/react-native-fcm#36]
With recent issues opened regarding ios integration, I'm thinking about supporting projects not using cocoapods.
Pro of not using it
1. There is no extra workspace file and `react-native run-ios` will be working again
2. Less issue on installation
Cons
1. Official docs recomends cocoapods
2. Updating framework is more intrusive

Looks like supporting both of the approach is not possible, so what do you think?

**Comment by alexanderniebuhr** [comment]
No cocoapods

But why not two branches?

**Comment by evollu** [comment]
@alexanderniebuhr there will be a main branch which has versioning

**Comment by evollu** [comment]
good news! nopod branch works for cocoapod project

**Comment by ahmed1490** [comment]
I am for easy onboarding and complex upgrades vs tricky onboading easy upgrades. > no-pods

Worst case, while upgrading is.. I remove the dependency (should not be an issue to reverse changes if the onboarding was clear) and then install the latest version.

**Comment by ahmed1490** [comment]
`good news! nopod branch works for cocoapod project`
- what does that mean?

**Comment by evollu** [comment]
it means the new version will support both integration approach
