### ISSUE TITLE
ios token undefined

### ISSUE THREAD

**Issue by fmelp** [evollu/react-native-fcm#361]
Hi there,

Getting undefined for the token (FCM.getToken()) in both simulator and device. Changed the capabilities to include Keychain Sharing and Push Notifications, but still no luck. Also tried all the obvious things such as uninstalling and reinstalling the app. Any advice? Thanks!

**Comment by danirbt** [comment]
Facing the same issue....

**Comment by DaniAkash** [comment]
You need to execute `FCM.requestPermissions();` to prompt the user to allow push notifications before you can get the token with `FCM.getToken()`

**Comment by Matus-Stastny** [comment]
I have the same issue. I executed `FCM.requestPermissions()` before getting token -`FCM.getToken()` but token is still undefined.

**Comment by DaniAkash** [comment]
Probably token wasn't available at the first time u used `FCM.getToken()`, try writing this refresh Handler which will get the token as soon as it's available

```js
FCM.on(FCMEvent.RefreshToken, (newToken) => {
    // incase token not available on first load.
    token = newToken;
});
```

Also make sure you imported `import FCM, {FCMEvent} from 'react-native-fcm'`

**Comment by Matus-Stastny** [comment]
Still not working. I have also tried official example project: https://github.com/evollu/react-native-fcm/tree/master/Examples/simple-fcm-client which uses solution @DaniAkash recommended but I still have an undefined token.

**Comment by mahesh-beehively** [comment]
Same here! |)

**Comment by Matus-Stastny** [comment]
My FB config in `AppDelegate.m` was unreachable, so my bad. It works now. 
Make sure that your: 
```
[FIRApp configure];
+   [[UNUserNotificationCenter currentNotificationCenter] setDelegate:self];
```
is executed if you have the same issue.

**Comment by evollu** [comment]
looks like issue solved

**Comment by bhatti-waqas** [comment]
I am facing issue . I get the token but when try to send push it says invalid token.. :(

**Comment by MaheshNandam** [comment]
@Matus-Stastny,

Facing the same issue as FCM.getFCMToken() is giving undefined token value, please look into this issue ASAP.
My Package:
"react": "16.0.0",
"react-native": "0.50.4",
"react-native-fcm": "^10.0.3",

**Comment by vixita-jarvisbitz** [comment]
> My FB config in `AppDelegate.m` was unreachable, so my bad. It works now.
> Make sure that your:
> 
> ```
> [FIRApp configure];
> +   [[UNUserNotificationCenter currentNotificationCenter] setDelegate:self];
> ```
> 
> is executed if you have the same issue.

Solved by useing this solution, Thanks
