### ISSUE TITLE
[question] Sending messages to topics

### ISSUE THREAD

**Issue by bardu** [evollu/react-native-fcm#364]
Does this library support sending messages to topics?

https://firebase.google.com/docs/cloud-messaging/android/topic-messaging

**Comment by atlanteh** [comment]
instead of opening this issue you could have simply make a simple search for the word "topic" in this module's landing page and discover that it does. would probably take you less time.

**Comment by laurion** [comment]
I only see subscribing / unsubscribing. Is there a way to also SEND a message to a topic? @bardu @atlanteh

**Comment by atlanteh** [comment]
It supports registering to topics. You can't send notification messages from any client sdk as you need to suply the server key which should only be known to you.
