### ISSUE TITLE
Notification handler err issue

### ISSUE THREAD

**Issue by orphnahk** [evollu/react-native-fcm#366]
i push notification from firebase console When app is opening,so app crashes. When app is minimized or closed, it's ok. i found that: comment await someAsyncCall function inside  FCM.on() , error has gone but nothing happen too.

```
if(notif.local_notification){
       //this is a local notification
}
if(notif.opened_from_tray){
      //app is open/resumed because user clicked banner
}
//await someAsyncCall();
if(Platform.OS ==='ios'){
```

Does anyone know why?

![screenshot_1490691417](https://cloud.githubusercontent.com/assets/19589099/24397096/75134eb2-13cf-11e7-8d0b-b8fa9ea5d56d.png)

react-native-cli: 2.0.1
react-native: 0.40.0
react-native-fcm": "^6.1.0",
I'm testing on Android device 5

**Comment by Gknoblau** [comment]
I also have this issue

**Comment by ribbon-xx** [comment]
Same as above, any clues for that issue?

**Comment by maraujop** [comment]
same problem here

**Comment by rahulverma0508** [comment]
Getting the same issue. Tried on emulator as well as device .

**Comment by Gknoblau** [comment]
I think I figured it out. Platform needs to be imported. 

import { Platform } from 'react-native'

**Comment by maraujop** [comment]
I've found out, that basically if the code that you place for handling a notification is somehow broken, it ends up in a <a href="https://github.com/evollu/react-native-fcm/blob/14e44e789ef802023f84119f84577d4f0ffd3f7f/index.js#L132">react-native-fcm try / catch</a> that prompts this error, but it rarely means a bug in react-native-fcm itself

**Comment by evollu** [comment]
yes I make that try catch so that errors can be found immediately. May be I should be more clear about the error message?
@orphnahk please reopen if your issue is not resolved

**Comment by novotny** [comment]
@orphnahk I have the same issue. Please how did you fix it? Thanks

**Comment by Norfeldt** [comment]
You have to delete both `async` from `FCMEvent.Notification, async notif => {` and `someAsyncCall()`  from the code.

**Comment by justuseapen** [comment]
What is the expected use case for someAsyncCall() if it's not implemented/necessary?

**Comment by evollu** [comment]
You should be able to use async function in callback.

**Comment by CHARITH1995** [comment]
this.notificationListener2 = FCM.on(FCMEvent.Notification,(notif) => {
          var data = notif;
          var dataNotif = notif;
          try {
            if (Platform.OS === 'android') {
              if (dataNotif.custom_notification) {
                var data = dataNotif;
                console.log('notificationListener new',JSON.stringify(data))
                Alert.alert(
                  data.title,
                  data.body,
                  [
                    {text: 'Cancel', onPress: () => console.log('Cancel Pressed'),style: 'cancel',},
                    {text: 'View', onPress: () => this.openNotificationTargetWindow(data)},
                  ],
                  {cancelable: false},
                );
              }
            }
          //someAsyncCall();
          }catch(err){
            //alert(err)
          }
        });
