### ISSUE TITLE
Clarification on when the App is Closed/Killed/Exited

### ISSUE THREAD

**Issue by jnrepo** [evollu/react-native-fcm#369]
react-native-fcm: 6.1.0
react-native: 0.42.0
device: iPhone 6 (iOS 10)
app state: not running

Hi, I just wanted clarification on when the app is not running. In my application the badge number will go up correctly in every state, but when the app is not running. Would there be a way to bump up the badge number here? Would the code have to be in native iOS?

Currently the code I have to move up the badge number is all in JavaScript.

Thanks in advanced!

**Comment by evollu** [comment]
When app is killed, you have to rely on the badge payload inside push notification. Which means your server has to keep track of badge count on each device.
If you don't care when user killed the app and just want to update when app is not running, you can use iOS native code to bump up the badge count. There are couple examples online. However, user kills app all the time so I don't think it is a valid fallback
