### ISSUE TITLE
Need some help

### ISSUE THREAD

**Issue by aureldev** [evollu/react-native-fcm#370]
Hi everyone,
this is not an issue, but it may will help other people like me.
I'm newbie in react native, and mobile development too. I'm building an app with firebase and I'd like to people receiving notifications when they receive a message, and get comments ... Some basics notification I guess! But I clearly don't vizualise the steps I need to do.
I can send notifications from firebase, my app catch it with the basic example (just when the app is in foreground) but this doesnt work when I try to send a local notification by adding it on a button

I get a response with "unauthorized" in the <title>

. I'm using redux too,

Where should I initialize the PushControler component ? In the provider and put my token in my reducer ?
Should I have my main serveur or firebase can handle push notifications ?
When a user send a message, so I have to send also the message as a notification for the other device ?
Have I to know the tokens of others user ?

**Comment by evollu** [comment]
If you are trying to build a chat app, then yes you will need a backend server, and user Firebase's api rather than the console. The server will receive message from user, find firebase id for recipient and fire notification request to Firebase server.
I'm not sure how you get the "unauthorized" alert, but most likely it is config issue

**Comment by aureldev** [comment]
I made something, quit silly I guess but it worked, I store the token on the firebase database, and add an action to update it whenever it changes. Then I send the notification with that token to the user, is that the good way to do it ?

**Comment by evollu** [comment]
yes, looks like the right way.

**Comment by aureldev** [comment]
thanks you! What is the differences between sendNotificationWithData and sendNotification ? I didn't tried to test those different methods, so lets ask for it now ahah

**Comment by evollu** [comment]
they are just functions defined in https://github.com/evollu/react-native-fcm/blob/master/Examples/simple-fcm-client/app/FirebaseClient.js
official docs explains this https://firebase.google.com/docs/cloud-messaging/concept-options

Although this repo lets you handle notifications without writing native code, it is better to read official docs for usage and understand how notification works in general.
