### ISSUE TITLE
How to make ongoing notification?

### ISSUE THREAD

**Issue by pewh** [evollu/react-native-fcm#371]
My use case is: notification always stay until Bluetooth connection is off. How to do it with this repo?

**Comment by evollu** [comment]
I would implement a banner style UI view because this sound like a warning/instruction message rather than a notification?

**Comment by pewh** [comment]
Like google maps notification when driving. It show dynamic text. The picture is below

https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTigCQCO5BROVYp1LSAdV0Jbshv7SXyM4ujsLT6DLrsR00Szed9VMA9Cwus

**Comment by pewh** [comment]
Hello, any news about this?

**Comment by evollu** [comment]
for android, if you use the same ID for notification, it should update the existing one. However, i don't think FCM provides an ID property, so you should try local notification or `custom_notification` with `id` field

**Comment by pewh** [comment]
Okay thank you. Let me try to use `custom_notification`.

By the way, is there any property that has actions (which is not auto dismiss) like the picture I've upload above? Let's say it has 3 actions, when I click, it shouldn't dismiss notification, but trigger other action.

**Comment by evollu** [comment]
that is advanced feature, not available yet

**Comment by evollu** [comment]
@pewh have you figured out ongoing notif?

**Comment by pewh** [comment]
Unfortunately, no. I can't make it work, so I cancel to implement ongoing notif in my project.

**Comment by motiazu** [comment]
@pewh This is not really how these features are implemented in Android.
Take a look at [Foreground Services](https://developer.android.com/guide/components/services.html#Foreground)

**Comment by pewh** [comment]
I think it's possible by chaining `.setOngoing(true)` to notification builder (https://github.com/evollu/react-native-fcm/blob/master/android/src/main/java/com/evollu/react/fcm/FIRLocalMessagingHelper.java#L86). I see the answer on https://stackoverflow.com/a/14187092/1163092, it's possible by add modify function like `public void sendNotification(Bundle bundle, bool ongoingMode)`, but unfortunately I'm still newbie on Java.

**Comment by dev-hamid** [comment]
so how can i use ongoing ??
i don't find any thing about it in the docs

**Comment by evollu** [comment]
@dev-hamid `ongoing: true`

**Comment by hruthik46** [comment]
> @dev-hamid `ongoing: true`

no its not working its still the same
