### ISSUE TITLE
Notifications don't work on Android when app is running in background

### ISSUE THREAD

**Issue by jmeyers91** [evollu/react-native-fcm#372]
What version of RN and react-native-fcm are you running? **0.41.2 (cli 2.0.1)**
What device are you using? (e.g iOS9 emulator, Android 6 device)? **LG G5**
Is your app running in foreground, background or not running? **Background**

Advanced:
Have you tried adding break point in native handlers to see if message gets delivered?
can share a project with issue?
**I tried adding a breakpoint to the notification listener in JavaScript, but it is never executed.**

When my app is running in the background and a push notification is received and pressed, the app either crashes or launches without firing a `notification` event. Notifications work fine when the app is in the foreground or closed.

**Comment by alexustinovsm** [comment]
@jmeyers91 It works. If you look at source code, you could see (for Android) that library got processing of push notification  on its self while your app (JS) in the background. You just need to send correct content through FCM server.

**Comment by evollu** [comment]
if app crashes, can you share crash log? or share an app to reproduce the issue?

**Comment by razvan-tudosa** [comment]
I am experiencing the same issue. When app is in background I receive Push Notification. I tap on it, app opens but the `notification` event does not get triggered. If app is in foreground the event gets triggered when I receive a Push Notification.

```
FCM.on(FCMEvent.Notification, (notif) => {
        console.log(notif)

        if (notif.opened_from_tray) {
          // do stuff
        }
      })
```
I am doing this in a `componentDidMount()`. Anyone has any ideas where I can look further?

**Comment by razvan-tudosa** [comment]
I found the solution to my problem.
in **AndroidManifest.xml** file I forgot to add a line:

```diff
<activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:theme="@style/SplashTheme"
        android:screenOrientation="portrait"
+       android:launchMode="singleTop"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize">
```

After putting that line everything worked as is should on Android too.

**Comment by jmeyers91** [comment]
@razvan-tudosa That fixed the issue for me as well. Thanks. Closing.
