### ISSUE TITLE
check permissions and requestPermissions again

### ISSUE THREAD

**Issue by atlanteh** [evollu/react-native-fcm#373]
Is there any way to check if the user has granted or rejected the permissions? I want to instruct the user what to do in case he accidentally rejects the permissions.
Also, let's say the user rejected the permissions, any way to ask for permissions again?
I see in [react-native-push-notification#ios-only-methods](https://github.com/zo0r/react-native-push-notification#ios-only-methods) that they have a "abandonPermissions" method. maybe we can use it?

**Comment by tmpethick** [comment]
I have attempted a first stab at it here: https://github.com/wakiewakie/react-native-fcm

I've pulled most of it from the implementation of PushNotificationIOS in react-native. It's currently working but you should know the following:

* An addition method is required in your `AppDelegate.m` (its also provided in the updated README)
```
+ - (void)application:(__unused UIApplication *)application didRegisterUserNotificationSettings:(UIUserNotificationSettings *)notificationSettings
+ {
+   [RNFIRMessaging didRegisterUserNotificationSettings:notificationSettings];
+ }
```

* `requestPermissions` now returns a promise on iOS which resolves to a dictionary similarly to PushNotificationIOS (e.g. `{alert: true, ...}`)

**Comment by evollu** [comment]
@tmpethick do you mind creating pull request for this feature? It will be useful.
@atlanteh yes you can just import PushNotificationIOS and use their method for checking/abandoning permission.

**Comment by atlanteh** [comment]
Thx guys 👍

**Comment by gabriel** [comment]
@tmpethick would be nice to get this in here, can you pull request?

**Comment by tmpethick** [comment]
Sure, even though it's not ideal: it still requests for all permissions. PR coming up 👍
