### ISSUE TITLE
is react-native-fcm compatible with GCM

### ISSUE THREAD

**Issue by tugorez** [evollu/react-native-fcm#375]
I'm using react-native 43.1, and I'm trying to implement push notifications with amazon SNS but it appears to not be working. 
The message that is generated by SNS Will be of the form:
```javascrip
{
    "GCM": "{ \"data\": { \"message\": \"test message\" } }"
}
```
is react-native-fcm cabaple of handling this response?

**Comment by evollu** [comment]
i don't think so. The ID for GCM is different from FCM.
Can you confirm with firebase team?
