### ISSUE TITLE
android build fails (Configuration with name 'default' not found)

### ISSUE THREAD

**Issue by uriva** [evollu/react-native-fcm#379]
Hi, I followed instructions and got the following error:

```
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > Configuration with name 'default' not found.

```

**Comment by uriva** [comment]
I rest my project in various ways and now it's working...

**Comment by iiitmahesh** [comment]
@uriva  how do solved this. I have same problem.

**Comment by uriva** [comment]
I don't know exactly what I did that solved it, a series of resetting and trying to repeat the docs instructions again.
