### ISSUE TITLE
iOS configuration using CocoaPods

### ISSUE THREAD

**Issue by ibratoev** [evollu/react-native-fcm#380]
I just finished configuring this module for CocoaPods and I used a different but simpler approach. I hit several issues with the documented approach in the Readme. I am not sure if this is 'the right' way as it seems there are multiple ways to integrate a react-native module. Here are the steps I used with notes on the differences from the Readme:

* Installed using `npm install react-native-fcm --save`.
* After `react-native link react-native-fcm`, I **reverted the changes made to the iOS project**.
* Added the following line to my Podfile: `pod 'react-native-fcm', path: '../node_modules/react-native-fcm'`.
* I **did not uncomment "use_frameworks!" line in the podfile**. This caused multiple other modules to fail.
* I called `pod install --repo-update`.
* I followed the Shared Steps: https://github.com/evollu/react-native-fcm#shared-steps
* I did not follow the Xcode post installation steps as they were not needed, except adding the following capabilities: Push Notifications and Background Modes > Remote notifications.

What do you think about this approach?

**Comment by evollu** [comment]
@ibratoev yes, with latest code people shouldnt need to uncomment "use_framework!".
Do you mind creating a pull request to update the docs? I personally am not using the cocoapod approach so some working documentation will be very helpful

**Comment by geekvijay** [comment]
@ibratoev,
i am using following react native version
```
"react": "^15.4.2",
"react-native": "^0.41.2",
``` 
and in your approach, when i did `pod install --repo-update` it installed following dependancy along with React (0.11.0)

```
Analyzing dependencies
Fetching podspec for `react-native-fcm` from `../node_modules/react-native-fcm`
Downloading dependencies
Installing Firebase (3.15.0)
Installing FirebaseAnalytics (3.7.0)
Installing FirebaseCore (3.5.2)
Installing FirebaseInstanceID (1.0.9)
Installing FirebaseMessaging (1.2.2)
Installing GoogleToolboxForMac (2.1.1)
Installing Protobuf (3.2.1)
Installing React (0.11.0)
Installing react-native-fcm (6.2.0)
Generating Pods project
Integrating client project
```

its is causing the problem. did you faced such problem problem ?

**Comment by ibratoev** [comment]
@geekvijay,
The problem is that you use React-Native from the cocoapods repo. In your podfile you should reference react-native from your local node_modules. To do that you should have something like that in your podfile:
```  
pod 'React', subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTCameraRoll',
    'RCTGeolocation',
    'RCTImage',
    'RCTNetwork',
    'RCTPushNotification',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'RCTLinkingIOS',
  ], path: '../node_modules/react-native'
```

You can read here more information about using React-Native with CocoaPods: http://facebook.github.io/react-native/releases/0.43/docs/integration-with-existing-apps.html#react-native-framework

**Comment by ibratoev** [comment]
@evollu, 
I will send you a PR to remove the "use_frameworks!" note. 
About the CocoaPods setup, I am not sure how standard is that. I looked into some other react-native modules and it is not well documented anywhere. I think this is something that can be improved in react-native. I will not send a PR for that for now to not make a mess.
One more thing, why is the **Keychain Sharing** capability required?

**Comment by evollu** [comment]
use_frameworks! is remove in readme
I don't remember why Keychain Sharing is required. perhaps it is optional. Try and let me know
