### ISSUE TITLE
Cannot read property 'RefreshToken' of undefined

### ISSUE THREAD

**Issue by daywong1119** [evollu/react-native-fcm#390]
Hi, I got exception as soon as I added the FCM SDK and get it launched.

Versions: 
"react-native-fcm": "^2.5.6",
"react-native": "0.39.2",

Device:
ios 10.3 emulator

X Code
````
// ADDED
[FIRApp configure];
[[UNUserNotificationCenter currentNotificationCenter] setDelegate:self];


// ADDED

- (void)userNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification withCompletionHandler:(void (^)(UNNotificationPresentationOptions))completionHandler
{
  [[NSNotificationCenter defaultCenter] postNotificationName:FCMNotificationReceived object:self userInfo:notification.request.content.userInfo];
  if([[notification.request.content.userInfo valueForKey:@"show_in_foreground"] isEqual:@YES]){
    completionHandler(UNNotificationPresentationOptionAlert | UNNotificationPresentationOptionBadge | UNNotificationPresentationOptionSound);
  }else{
    completionHandler(UNNotificationPresentationOptionNone);
  }
  
}

- (void)userNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void (^)())completionHandler
{
  NSDictionary* userInfo = [[NSMutableDictionary alloc] initWithDictionary: response.notification.request.content.userInfo];
  [userInfo setValue:@YES forKey:@"opened_from_tray"];
  [[NSNotificationCenter defaultCenter] postNotificationName:FCMNotificationReceived object:self userInfo:userInfo];
}

//You can skip this method if you don't want to use local notification
-(void)application:(UIApplication *)application didReceiveLocalNotification:(UILocalNotification *)notification {
  [[NSNotificationCenter defaultCenter] postNotificationName:FCMNotificationReceived object:self userInfo:notification.userInfo];
}

- (void)application:(UIApplication *)application didReceiveRemoteNotification:(nonnull NSDictionary *)userInfo fetchCompletionHandler:(nonnull void (^)(UIBackgroundFetchResult))completionHandler{
  [[NSNotificationCenter defaultCenter] postNotificationName:FCMNotificationReceived object:self userInfo:userInfo];
  completionHandler(UIBackgroundFetchResultNoData);
}
````

JS Code: 

````import FCM, {FCMEvent, RemoteNotificationResult, WillPresentNotificationResult, NotificationType} from 'react-native-fcm';

componentDidMount() {
  // push Notification
  FCM.requestPermissions(); // for iOS
  FCM.getFCMToken().then(token => {
    console.log('>>>> get FCM token:', token);
  });

  refreshTokenListener = FCM.on(FCMEvent.RefreshToken, (token) => {
    console.log('>>>> refreshTokenListener FCM token:', token);
  });

  notificationListener = FCM.on(FCMEvent.Notification, async (notif) => {
    
  });
}
````
// ERRORS
ExceptionsManager.js:63 Cannot read property 'RefreshToken' of undefined
Unhandled JS Exception: Cannot read property 'RefreshToken' of undefined

**Comment by MaxToyberman** [comment]
did you run react-native link react-native-fcm ? @daywong1119

**Comment by MaxToyberman** [comment]
try going to the project navigator in Xcode choose your project -> Libraries ->RNFIRMessaging -> Products and drag libRNFIRMessaging.a to Build Phases -> Link Binary with libraries

**Comment by daywong1119** [comment]
@MaxToyberman  Yes, I did that.

**Comment by daywong1119** [comment]
@MaxToyberman  no luck, I can get the FCM token by ` FCM.getFCMToken()`, seems only `FCMEvent ` instance is null

**Comment by MaxToyberman** [comment]
@daywong1119 try putting 'refreshToken'  instead of FCMEvent.RefreshToken

**Comment by daywong1119** [comment]
@MaxToyberman  Great! It works well after replacing with `refreshToken` . Thanks

**Comment by MaxToyberman** [comment]
@daywong1119 this happens because in version 2.5.6 there is no `FCMEvent`. I'm happy to help.

**Comment by shaheerakhlaq** [comment]
I am getting error

undefined is not an object (evaluating 'RNFIRMessaging.requestPermissions')
requestPermissions
    D:\Shaheer\RND\NodeJS\reactnativefcm\node_modules\react-native-fcm\index.js:62:24
componentDidMount
    D:\Shaheer\RND\NodeJS\reactnativefcm\app\PushController.js:12:4
<unknown>
    D:\Shaheer\RND\NodeJS\reactnativefcm\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1658:23
measureLifeCyclePerf
    D:\Shaheer\RND\NodeJS\reactnativefcm\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1610:15
<unknown>
    D:\Shaheer\RND\NodeJS\reactnativefcm\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1657:33
notifyAll
    D:\Shaheer\RND\NodeJS\reactnativefcm\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:2121:107
close
    D:\Shaheer\RND\NodeJS\reactnativefcm\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:2138:8
closeAll
    D:\Shaheer\RND\NodeJS\reactnativefcm\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1412:101
perform
    D:\Shaheer\RND\NodeJS\reactnativefcm\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1388:52
batchedMountComponentIntoNode
    D:\Shaheer\RND\NodeJS\reactnativefcm\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:2004:24
perform
    D:\Shaheer\RND\NodeJS\reactnativefcm\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1382:99
batchedUpdates
    D:\Shaheer\RND\NodeJS\reactnativefcm\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:2077:139
batchedUpdates$1
    D:\Shaheer\RND\NodeJS\reactnativefcm\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1456:61
renderComponent
    D:\Shaheer\RND\NodeJS\reactnativefcm\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:2032:45
render
    D:\Shaheer\RND\NodeJS\reactnativefcm\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:3258:46
renderApplication
    D:\Shaheer\RND\NodeJS\reactnativefcm\node_modules\react-native\Libraries\ReactNative\renderApplication.js:34:4
run
    D:\Shaheer\RND\NodeJS\reactnativefcm\node_modules\react-native\Libraries\ReactNative\AppRegistry.js:117:10
runApplication
    D:\Shaheer\RND\NodeJS\reactnativefcm\node_modules\react-native\Libraries\ReactNative\AppRegistry.js:191:26
__callFunction
    D:\Shaheer\RND\NodeJS\reactnativefcm\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:306:47
<unknown>
    D:\Shaheer\RND\NodeJS\reactnativefcm\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:108:26
__guard
    D:\Shaheer\RND\NodeJS\reactnativefcm\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:269:6
callFunctionReturnFlushedQueue
    D:\Shaheer\RND\NodeJS\reactnativefcm\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:107:17

**Comment by PoojaVM** [comment]
Getting the same issue. Anyone got any solution?
