### ISSUE TITLE
Build Fails: duplicate symbol _FCMNotificationReceived

### ISSUE THREAD

**Issue by AndrewHenderson** [evollu/react-native-fcm#391]
What version of RN and react-native-fcm are you running?
6.2.3
React Native version 0.42.2

What device are you using? (e.g iOS9 emulator, Android 6 device)?
iOS10 simulator iPhone 7
Is your app running in foreground, background or not running?
Build Fails

```
duplicate symbol _FCMNotificationReceived in:
    /Users/andrewhenderson/Library/Developer/Xcode/DerivedData/socadv-fcshdnjvildlyrfwryomcumibvva/Build/Products/Debug-iphonesimulator/libRNFirebase.a(RNFirebaseMessaging.o)
    /Users/andrewhenderson/Library/Developer/Xcode/DerivedData/socadv-fcshdnjvildlyrfwryomcumibvva/Build/Products/Debug-iphonesimulator/libRNFIRMessaging.a(RNFIRMessaging.o)
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by sat11p** [comment]
I'm facing the same issue in Xcode. Please see the error below. Any help or suggestion would be appreciated at the earliest as stuck on it since long time ago.

duplicate symbol _FCMNotificationReceived in:
    /Users/Satish/Library/Developer/Xcode/DerivedData/MyClinic-begoijqpikvccsbfxtollvobmybf/Build/Products/Debug-iphonesimulator/libRNFirebase.a(RNFirebaseMessaging.o)
    /Users/Satish/Library/Developer/Xcode/DerivedData/MyClinic-begoijqpikvccsbfxtollvobmybf/Build/Products/Debug-iphonesimulator/libRNFIRMessaging.a(RNFIRMessaging.o)
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by evollu** [comment]
I haven't seen this before. hope this helps
http://stackoverflow.com/questions/12988987/duplicate-symbols-for-architectures-in-xcode

**Comment by AndrewHenderson** [comment]
@sat11p You might want to check out http://invertase.io/react-native-firebase. I'm using that now.
