### ISSUE TITLE
How to custom icon color

### ISSUE THREAD

**Issue by nhuthan** [evollu/react-native-fcm#394]
Hi,

I don't know how to custom icon color, don't see any option for that. What i am missing?

**Comment by nhuthan** [comment]
Sorry, i found it. Thanks

**Comment by mamartin** [comment]
@nhuthan can you share how you did it?

**Comment by nhuthan** [comment]
Hi @mamartin 
All you need is:
- place a png image (should be a mono image) to android resource folder
- set icon image name and icon color to payload

And it should working
![image](https://user-images.githubusercontent.com/12423709/32305292-49f095c6-bfa7-11e7-8fc9-5b203d765e29.png)

![image](https://user-images.githubusercontent.com/12423709/32305433-1c86b9e8-bfa8-11e7-8c3e-bdca07e1723e.png)

**Comment by nhuthan** [comment]
use this tool to generate notification icons (and other icons if you need)
https://romannurik.github.io/AndroidAssetStudio/index.html

**Comment by mamartin** [comment]
thanks for reply! Just found out you can specify default notification color by adding 

`<meta-data
        android:name="com.google.firebase.messaging.default_notification_color"
        android:resource="@color/primary" />`

to AndroidManifest.xml
