### ISSUE TITLE
App not received notification in background (ios & android)

### ISSUE THREAD

**Issue by niros001** [evollu/react-native-fcm#396]
Hi i use react "~15.4.1", react-native "0.42.0" react-native-fcm "^6.2.1" (and "Firebase/Messaging" via pod)
I do all the installation steps and follow the usage but i can get notifications only if the app is open.
any idea?

**Comment by henrykapostel** [comment]
On the previous version, it works well, but after I updated the RN version - react "16.0.0-alpha.6", react-native "0.43.3", react-native-fcm "^6.2.0", App doesn't receive notification.

**Comment by niros001** [comment]
Work on android.
On ios still the same problem.

**Comment by evollu** [comment]
have you uploaded APNS cert to firebase?
are you using a real device?

**Comment by cfournel** [comment]
Same problem here, works great on all android devices,  ios < 10,  but not on ios 10.3.1, no push received.

**Comment by evollu** [comment]
@cfournel any other iOS 10 version? like 10.1? It have been working for me for iOS10

**Comment by cfournel** [comment]
@evollu I didn't test on 10.1 yet, sorry

**Comment by cfournel** [comment]
bump
