### ISSUE TITLE
Image in notification.(Android + IOS)

### ISSUE THREAD

**Issue by ycpatel813** [evollu/react-native-fcm#397]
Hi I found this is a very useful library for Push notification. 
But i need to display Image in notification is it possible?

Yes, then give me some direction to go for.
Question also at here:
http://stackoverflow.com/questions/43648746/how-to-set-image-in-notification-in-react-native

Thanks.

**Comment by evollu** [comment]
looks like android has NotificationCompat.BigPictureStyle style.
you can change FIRLocalMessagingHelper.java to include that logic.
pull request is welcomed

**Comment by evollu** [comment]
it is done in v7
