### ISSUE TITLE
React/RCTBridgeModule.h not found after completing Xcode post installation steps

### ISSUE THREAD

**Issue by gwitteveen** [evollu/react-native-fcm#398]
App was running/building fine, but after completing the Xcode post installation step below I got several errors in my build.

> In Xcode menu bar, select Product > Scheme > Manage schemes. Select your project name Scheme then click on the minus sign ― in the bottom left corner, then click on the plus sign + and rebuild your project scheme.

All libraries seem to give errors on  `#import <React/RCTBridgeModule.h>`. Deleting and adding the scheme again wasn't enough to get the project to build again.

steps in this link however fixed it for me:
http://stackoverflow.com/questions/41477241/react-native-xcode-upgrade-and-now-rctconvert-h-not-found

Not sure if the issue is specific for my project, I misunderstood the last step, if the last Xcode post installation step is unnecessary or the instruction is rather incomplete.
 
using with RN 0.42.3

**Comment by Fantasim** [comment]
Same problem

**Comment by evollu** [comment]
yes this solution I'm using as well. I will add it to readme.

**Comment by kirill-zhukov** [comment]
The issue may happen if you have React reference in your pod files. Try not to use pods for ReactNative modules since they normally have a native library inside corresponding node_module
