### ISSUE TITLE
[android] initialNotification

### ISSUE THREAD

**Issue by gorangajic** [evollu/react-native-fcm#4]
is there a way we can get `initialNotification` payload like on ios when user click on notification?
I have found in the firebase api that there is a way to specify activity using `click_action` and handle new activity but I am not sure how to implement that because I am not that much familiar with Android development
```
<intent-filter>
  <action android:name="OPEN_ACTIVITY_1" />
  <category android:name="android.intent.category.DEFAULT" />
</intent-filter>
```
btw thank you for this awesome module

**Comment by evollu** [comment]
let me take a look

**Comment by evollu** [comment]
@gorangajic please check the master code. You should be about to get activity in both platform using `initialAction` and `initialData` now.
Check out readme about how to and known issues

**Comment by evollu** [comment]
I haven't published the change yet. Please let me know if you have other thoughts

**Comment by gorangajic** [comment]
Thank you for the feature and the quick response ❤️ 

I have tested and it works great
