### ISSUE TITLE
RN 0.29 android config

### ISSUE THREAD

**Issue by sorenburon** [evollu/react-native-fcm#40]
With the latest changes, the getPackages method has been moved to an application class, and are no longer in the main activity. As such, this call is no longer possible: 

`new FIRMessagingPackage(getIntent())`

How do I set up react-native-fcm on android when using RN 29?

**Comment by evollu** [comment]
working on it

**Comment by evollu** [comment]
1.0.12 released, please try it out.
`new FIRMessagingPackage(getIntent())` is no longer needed

**Comment by evollu** [comment]
UPDATE: still working on it. React native is trying to prevent modules from fetch and store activity data in constructor. So I should follow the direction and provide initial data in another way

**Comment by evollu** [comment]
UPDATE: new fix pushed please try

**Comment by sorenburon** [comment]
I can build now, which is great 👍  

However, FCM.getToken() returns null in the promise.

Logcat output:

> 07-12 04:26:49.111  2772  2817 W InstanceID/Rpc: Failed to resolve REGISTER intent, falling back
> 07-12 04:26:49.112  2772  2817 W InstanceID/Rpc: Both Google Play Services and legacy GSF package are missing

> ...

> 07-12 04:26:59.118  2772  2845 D FirebaseInstanceId: background sync failed: MISSING_INSTANCEID_SERVICE, retry in 20s
> 07-12 04:26:55.891  2772  2812 D com.evollu.react.fcm.FIRMessagingModule: Firebase token: null

### My setup:
**App build.gradle**
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.2'
        classpath 'com.google.gms:google-services:3.0.0'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}

```

**Manifest**

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="..."
    android:versionCode="1"
    android:versionName="1.0">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.VIBRATE" />

    <uses-sdk
        android:minSdkVersion="16"
        android:targetSdkVersion="22" />

    <application
        android:name=".MainApplication"
        android:allowBackup="true"
        android:label="@string/app_name"
        android:icon="@mipmap/ic_launcher"
        android:theme="@style/AppTheme">
        <activity
            android:name=".MainActivity"
            android:label="@string/app_name"
            android:screenOrientation="portrait"
            android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
            android:launchMode="singleTop" >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
            <intent-filter>
                <action android:name="fcm.ACTION.HELLO" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </activity>
        <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
        <service android:name="com.evollu.react.fcm.MessagingService">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT"/>
            </intent-filter>
        </service>

        <service android:name="com.evollu.react.fcm.InstanceIdService" android:exported="false">
            <intent-filter>
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
            </intent-filter>
        </service>
    </application>

</manifest>
```

Also added the following to MainActivity
```
@Override
    public void onNewIntent(Intent intent){
        setIntent(intent);
    }
```

and of course it is added to getPackages in MainApplication, and the downloaded and added the google-services.json file to the project.

**Comment by yuenanto** [comment]
@evollu: It still bugs with RN 0.29.
Please check below the compatibility table.

| FCM | getIntent()* | RN 0.28 | RN 0.29 |
|:---:|:---:|:---:|:---:|
| 1.0.9 | :white_check_mark: | :white_check_mark: | :x: |
| 1.0.9 | :x: | :x: | :x: |
| 1.0.13 | :white_check_mark: | :x: | :x: | :x: |
| 1.0.13 | :x: | :white_check_mark: | :x: |

*This column refers to the presence of `getIntent()` in `new FIRMessagingPackage()`

**:x: for RN versions means that the build failed

A screenshot when the build fails:
![image](https://cloud.githubusercontent.com/assets/9156092/16766665/a54b69c6-483b-11e6-8c08-d362664faf3f.png)

**Comment by evollu** [comment]
you still need to follow the upgrade instructions in rn 0.29 https://github.com/facebook/react-native/releases

**Comment by yuenanto** [comment]
@evollu: Oh right, I completely missed it, thank you !
Works fine (Build + Notifications) when following the RN 0.29 upgrade instructions.

As it also works for @sorenburonn we can close the issue :)
