### ISSUE TITLE
(Android) sound doesn't work on remote notification when application is in background or not running

### ISSUE THREAD

**Issue by imarem** [evollu/react-native-fcm#400]
Hi @evollu 

I'm tring to make a sound when recive notification.

I send:
{
  "notification":{
    "title":"Notification title",  
    "body":"Notification body"
    "sound": "default",
  },
   "priority":"high",
   "to":"my_token"
}

I recive de notification but never play any sound.

I'm running on Android 7 with a real device with 
react-native-fcm@2.5.6
react-native@0.39

Is it possible to do this case or am I doing something wrong?

Thanks for advance.

**Comment by evollu** [comment]
it will make sound if you don't pass sound property. default one.
if you want to customize it, you can put a resource into it and pass the filename. search how native android does it

**Comment by imarem** [comment]
never mind, it was my mistake. I can reproduce sound now.

Thanks for the quickly response
