### ISSUE TITLE
Example app, sendNotification & Send Notification With Data doesn't show notification but has tone, sendData works?? 

### ISSUE THREAD

**Issue by kh1990** [evollu/react-native-fcm#401]
Using the example app, I can get the notification to show up with only sendData. Behaviour described as below: 

In the foreground: 
Simulator: 

- sendNotification: Tone
- sendData: tone + data notification
- sendNotificationWithData:  Tone + data notification (BUT no notification text)

iphone 6plus: 

- sendNotification: No response
- sendData: notification display 
- sendNotificationWithData: No response 

version of react-native-fcm: @6.2.3

if I change the 'notification' to 'data' in the body section, then the notification will display. Anyone know why that is? (e.g. see below)
`  
   sendNotification(token) {
       const body = {
         to: token,
         data: {
                title: 'Simple FCM Client',
                body: 'This is a notification with only NOTIFICATION.',
                sound: 'default',
                click_action: 'fcm.ACTION.HELLO',
         },
         priority: 'normal'
       };
       this._send(JSON.stringify(body), 'notification');
    }
`

**Comment by hatuan** [comment]
I have same problems too

version of react-native-fcm: @6.2.3

**Comment by kh1990** [comment]
So I missed the part of the documentation that actually explained this issue: 

> Behaviour when sending notification and data payload through GCM

When user clicks notification to launch the application, you can get that notification by calling FCM.getInitialNotification. (NOTE: reloading javascript or resuming from background won't change the value)

When app is running in background (the tricky one, I strongly suggest you try it out yourself)

IOS will receive notificaton from FCMNotificationReceived event

if you pass content_available flag true, you will receive one when app is in background and another one when user resume the app. more info
if you just pass notification, you will only receive one when user resume the app.
you will not see banner if notification->body is not defined.
Android will receive notificaton from FCMNotificationReceived event

if you pass notification payload, it will receive data when user click on notification
if you pass data payload only, it will receive data when in background
e.g. fcm payload looks 

> like:...

**Comment by evollu** [comment]
let me know if you think it is still an issue
