### ISSUE TITLE
Why is vibrate key taking in a double?

### ISSUE THREAD

**Issue by holyxiaoxin** [evollu/react-native-fcm#402]
https://github.com/evollu/react-native-fcm/blob/a164f490c3eb10812bb855d848c124aaf04a8acc/android/src/main/java/com/evollu/react/fcm/FIRLocalMessagingHelper.java#L159

@evollu 
Why is vibrate taking in a double instead of an integer? If that is the case, README should be updated: vibrate to 300.0 instead of 300.

**Comment by evollu** [comment]
just because DEFAULT_VIBRATION is a long so it can be defaultValue without conversion.
plus passing 300 in javascript seems to work fine
