### ISSUE TITLE
FCMEvent.Notification not firing on android after successful click_action

### ISSUE THREAD

**Issue by foggy1** [evollu/react-native-fcm#409]
Using rn 0.43.2 and "react-native-fcm": "^6.1.0"

iOS is perfectly fine, absolutely no issues.

Android, however, has been incredibly mysterious.

Using the proper click_action, I am able to launch the app.

```
      "notification"=>{
        "title"=> "Simple FCM Client",
        "body"=> "This is a notification with NOTIFICATION and DATA (NOTIF).",
        "sound"=> "default",
        "click_action"=> "fcm.ACTION.HELLO"
      },
```

Any combination of notification and data and this click action will successfully open our app when you press the item in the tray.  Same goes for when I pass a custom_notification within the data itself.

But although touching the notification banner opens the app, it NEVER fires off the notification event, so I can't hook into it to do anything useful.

```
app.notificationListener = FCM.on(FCMEvent.Notification, async (notif) => {
    console.log('ahhhhh notif', notif)
```

That console log literally never fires when opening the app from a banner when the app is in the background or the foreground.  I know getInitialNotification is its own beast for when the app has not been launched at all, but I haven't even worried about that yet because when the app is in the background, touching the banner will open it: it just doesn't get inside of this callback, rendering all the data I'm passing back in the notification useless.  Here's the relevant part of my android manifest:

```
<activity
        android:name=".MainActivity"
        android:launchMode="singleTop"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:screenOrientation="portrait"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
       <intent-filter>
         <action android:name="fcm.ACTION.HELLO" />
         <category android:name="android.intent.category.DEFAULT" />
       </intent-filter>
```

Why isn't the callback being fired off if the click_action is launching the main activity?  Am I missing a step here?
EDIT: To be super clear, even with data and custom notif, this still doesn't work correctly for me.

```
        'to': user.fcm_token,
        'data' => {
          "custom_notification": {
            'title'  => 'Test title',
            'body'  => 'Test body',
            'color' => '#00ACD4',
            'priority' => 'high',
            'show_in_foreground' => true,
            'click_action' => "fcm.ACTION.HELLO"
          },
        },
```
i.e. this code also 1. opens the app on click but 2. does not fire off the notification call back, whether opened from background OR foreground.

**Comment by foggy1** [comment]
UGH, please close this!

```
    @Override
    public void onNewIntent(Intent intent) {
        super.onNewIntent(intent);
        this.setIntent(intent);
    }
```

Make sure you super here if another library asks you to manually override onNewIntent in MainActivity.java!

**Comment by M3po** [comment]
How did you manage to get that working I tried to add onNewIntent and I did everything you did, but i just can't get it to fire off the notification event from the background (on_click).
