### ISSUE TITLE
[Android] Package com.evollu.react.fcm does not exist

### ISSUE THREAD

**Issue by xuansontrinh** [evollu/react-native-fcm#41]
I installed the package react-native-fcm on my project and my project cannot compile. It keeps alerting that com.evollu.react.fcm.FIRMessagingPackage does not exist.
How to fix this problem?
I am using RN 0.28.0 .
Any help is appreciated.

**Comment by yuenanto** [comment]
Same issue as #40 
Use `new FIRMessagingPackage()` instead of `new FIRMessagingPackage(getIntent())`

**Comment by xuansontrinh** [comment]
I do not think that is the case. Because in MyActivity it has new FIRMessagingPackages() already. I think something is wrong with the auto linking with rnpm. Do you know how to manually link this package?

**Comment by xuansontrinh** [comment]
Eventually, rnpm does not link enough. I have to manually link in settings.gradle and app build.gradle to get it to work. Problem solved. I will close this issue here.

**Comment by devekoperiOS** [comment]
@xuansontrinh how did you link build.gradle and settings.gradle?

**Comment by xuansontrinh** [comment]
@devekoperiOS  
- In `settings.gradle` add this:
`include ':react-native-fcm'
project(':react-native-fcm').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-fcm/android')`
- In `build.gradle` in `app` add this: `compile project(':react-native-fcm')` in the `dependencies`

**Comment by devekoperiOS** [comment]
Thank you. Its got linked. Now I want to retrieve token. I am getting null. Can you please let me know how to get that?

**Comment by xuansontrinh** [comment]
@devekoperiOS  The token you get may be null at the beginning, so you have to add listener to get the event refresh token just like the document of evollu:
`FCM.on('refreshToken', (token) => {
      console.log(token)
      // fcm token may not be available on first load, catch it here
    });`

**Comment by devekoperiOS** [comment]
Following is my code:
componentDidMount()
{
  if(Platform.OS === 'ios')
    FCM.requestPermissions(); // for iOS

  
  FCM.getFCMToken().then(token => {
    console.log(token)
    // store fcm token in your server
    if(token != null)
      this.storeDeviceIDAPI(token);
   });

  this.notificationUnsubscribe = FCM.on('notification', (notif) => {
    // there are two parts of notif. notif.notification contains the notification payload, notif.data contains data payload
  });

  this.refreshUnsubscribe = FCM.on('refreshToken', (token) => {
    console.log("ttttttttttttt========="+token);
    // fcm token may not be available on first load, catch it here
  });

  FCM.subscribeToTopic('/topics/foo-bar');
  FCM.unsubscribeFromTopic('/topics/foo-bar');

}

**Comment by xuansontrinh** [comment]
did you miss brackets in `FCM.getFCMToken().then(token => {
console.log(token)
// store fcm token in your server`
It should be `FCM.getFCMToken().then(token => {
console.log(token)
// store fcm token in your server`
If that is not the problem, I don't think I can figure out what is because the way you use is similar to the way I use.
Moreover, you dont need to use the `if (Platform ...` because evollu already create an empty function for `requestPermissions()` in Android.

**Comment by devekoperiOS** [comment]
Ok. I corrected brackets. It was typo. Thank you for looking it and helping.
