### ISSUE TITLE
Don't receive the notifications

### ISSUE THREAD

**Issue by cfontana0** [evollu/react-native-fcm#411]
Hi @evollu ! Your plugin looks great! Thanks for that work.

I'm developing an RN application for iOS, and I want to implement the push notifications.
However, I'm having the following problem: I did all the steps of the tutorial and it looks like everything works fine. I don't have any error on the JS console and the Xcode console.

The following commands work fine:
```
    FCM.requestPermissions()

    FCM.getFCMToken().then(token => {
      console.log('TOKEN', token) // store fcm token in your server
    })

    FCM.getInitialNotification().then((notif) => {
      console.log('NOTIF2', notif)
    })
```
And I see in the JS console the following entries:
```
TOKEN eUDMtL4X5fc:APA91bH1ymI5Vm_Zpv3E1lq67aw0Jdxt0wLzbNAGx-c34a1qGRXVfESvuz4eicEEvtZSzNWUyAFknC0EGaCqBQgRvEEMSqOkx7Yf4h5NxUZ9YTWqKBzqSha0OsVIn6KLdqpeFN_yuMlu

NOTIF2 undefined
```

However, I go to the Firebase web console and I try to send a new message:
https://console.firebase.google.com/u/1/project/name_of_project/notification

The problem is that I don't receive the notification on my phone. I tried to send it to all the devices, but it doesn't work.
Besides, if I use the `TOKEN` value that I get from `FCM.getFCMToken()`, Firebase indicates me that the status of the message is `Failed`.

I tested it with the application in the foreground, background, and closed, but I never receive the notification.

It looks like it is a problem related to the integration with Firebase, but it is odd because I get a `TOKEN`.

The following are the libraries that I'm using
```
"react": "15.4.1",
"react-native": "0.39.2"
"react-native-fcm": "^6.2.3",
```
And you can see my package.json here: https://gist.github.com/cfontana0/42e51b912a1564fec400c6e4dc97d3a3

I performed all my tests on an iPhone 6, with iOS 10.3.2. And I'm sure that the app has permissions to receive the push notifications.

I tried to add some `NSLog` lines into my `AppDelegate.m` file, but I don't see those logs lines:
Check out my `AppDelegate.m` file: https://gist.github.com/cfontana0/b15e91863e31db073a02ae5c448762a7

This is my Xcode Console: https://gist.github.com/cfontana0/239d35eb2b5c2446c84e79b98b4bde18

Any help will be great!

Thanks,
Carlos

**Comment by evollu** [comment]
Have you uploaded your APNS certificate on Firebase?

`Firebase indicates me that the status of the message is Failed.`
There should be a reason in firebase's response.

**Comment by cfontana0** [comment]
Sorry it was that! Thanks!
