### ISSUE TITLE
[iOS] Build fail when rebuilding the scheme

### ISSUE THREAD

**Issue by sergiofraile** [evollu/react-native-fcm#415]
Hi there,

This is a comment rather than an issue to improve the documentation from the README file.

On the "Xcode post installation steps", it's mentioned to remove the scheme and add it again so it rebuilds. It turns out my project wasn't compiling on Xcode (neither command line) any more after that. When the project is originally created, the scheme includes the build of React, which is not included by default when adding the scheme again.

KazuyaHara solution in this issue did work for me:
https://github.com/luggit/react-native-config/issues/86

In any case this is my system information:

RCT: 16.0.0-alpha.6
RN: 0.44.0
RN-FCM: 6.2.3
Issue detected on:
   Xcode 8.3.2
   macOS: 10.12.5
App not compiling

**Comment by evollu** [comment]
you don't have to do that anymore. I've removed from readme.
please reopen the issue if you have more question
