### ISSUE TITLE
subscribeToTopic not Working

### ISSUE THREAD

**Issue by tarikhagustia** [evollu/react-native-fcm#416]
i have try this command
`FCM.subscribeToTopic('/topics/food');` or `FCM.subscribeToTopic('news');`
but in firebase console the list of topic not show, any idea to check subscribe working or Not ?

**Comment by cmedinasoriano** [comment]
I just did a few tests and yes it is working.  It can take up to 24 hrs to show up in Firebase Console,  mine took almost 1 hr to appear.

**Comment by tarikhagustia** [comment]
what the return of function ? i got null ,
thx

**Comment by cmedinasoriano** [comment]
That is correct, it is null.  If you look at the function signature in `react-native-fcm/index.js` you will see that it is not supposed to return anything.

**Comment by tarikhagustia** [comment]
oke works fine, take 2 days to appears on console, 👍 
thanks

**Comment by cmedinasoriano** [comment]
Great! Shouldn't you close this issue?
