### ISSUE TITLE
FCMEvent undefined

### ISSUE THREAD

**Issue by djohnkirby** [evollu/react-native-fcm#418]
Here's the snippet of my code that's failing:

FCM.getFCMToken().then(registerPushToken)
    this.refreshUnsubscribe = FCM.on(FCMEvent.RefreshToken, registerPushToken)
    debugger
    this.notificationUnsubscribe = FCM.on(FCMEvent.Notification, (notif) => {
      if (notif.opened_from_tray) {
        // User has clicked on a notification
        processNotification(notif)
        return
      }
      if(notif.local_notification){
        return
      }

I am running the import up top.

import FCM, {
  FCMEvent, RemoteNotificationResult, WillPresentNotificationResult, NotificationType
} from 'react-native-fcm'

FCM is clearly being imported, but somehow FCMEvent remains undefined.

RN v0.39.0
rn-fcm v2.5.6

**Comment by evollu** [comment]
v2.5.6 doesn't have constant defined. please use stirng
'FCMTokenRefreshed' and 'FCMNotificationReceived'
