### ISSUE TITLE
[IOS] The app crash at start

### ISSUE THREAD

**Issue by KarlosQ** [evollu/react-native-fcm#419]
I'm using RN 0.43.2, iOS 5s (10.2) Simulator and Xcode 8.2.1.

I do well the installation steps but the app crash in iOS (I try using pod and in other copy of my project using without pod and nothing).

1. `npm install react-native-fcm --save`
2. `react-native link react-native-fcm`
3. edit Podfile and add `pod 'Firebase/Messaging'`
4. edit AppDelegate.h
5. edit AppDelegate.m
6. I enable the necessary **Capabilities**
7. In **Manage schemes** I remove and add the scheme of my project I do double click, click in Build and I add React and projectTest. And put in order React -> project -> projectTest.

![screen shot 2017-05-25 at 14 06 28](https://cloud.githubusercontent.com/assets/15233913/26451863/0d032164-415e-11e7-9ad6-c8ff2993b206.png)

 I put the GoogleService-Info.plist file into project/ios/project/. 

But I can't do this run.

![screen shot 2017-05-25 at 15 29 14](https://cloud.githubusercontent.com/assets/15233913/26452155/28bec60a-415f-11e7-8a0f-80e0794e1c3f.png)

**Comment by Youngdi** [comment]
I got the same issue. The tricky thing is that in my case it has the problem on both ios simulator and real ios device, but only my simulator can still receive a message from firebase cloud message. Could anyone help? thank y'all.

Xcode version: 8.3.2
React-native: 0.44.0
React: 16.0.0-alpha.6
react-native-fcm: 6.2.3

**Comment by felipemartim** [comment]
I'm having the same issue on iOS.

**Comment by felipemartim** [comment]
This comment solved it for me.
https://github.com/evollu/react-native-fcm/issues/322#issuecomment-281678346

**Comment by Youngdi** [comment]
@felipemartim: No, it doesn't work for me. And also I can't get a token when I first start the app both on simulator and device.

Here is a error log:
2017-05-28 12:10:36.460 TakeItOver[2263:15817] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[RNFIRMessaging messaging:didRefreshRegistrationToken:]: unrecognized selector sent to instance 0x608000228a40'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010d7a5b0b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010c2c2141 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010d815134 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x000000010d72c840 ___forwarding___ + 1024
	4   CoreFoundation                      0x000000010d72c3b8 _CF_forwarding_prep_0 + 120
	5   TakeItOver                          0x000000010b363e91 -[FIRMessaging defaultInstanceIDTokenWasRefreshed:] + 175
	6   CoreFoundation                      0x000000010d744c2c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
	7   CoreFoundation                      0x000000010d744b29 _CFXRegistrationPost + 425
	8   CoreFoundation                      0x000000010d744892 ___CFXNotificationPost_block_invoke + 50
	9   CoreFoundation                      0x000000010d708162 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1826
	10  CoreFoundation                      0x000000010d7072c1 _CFXNotificationPost + 673
	11  Foundation                          0x000000010be4e9af postQueueNotifications + 856
	12  CoreFoundation                      0x000000010d74b717 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	13  CoreFoundation                      0x000000010d74b687 __CFRunLoopDoObservers + 391
	14  CoreFoundation                      0x000000010d7305c8 __CFRunLoopRun + 856
	15  CoreFoundation                      0x000000010d730016 CFRunLoopRunSpecific + 406
	16  GraphicsServices                    0x0000000112421a24 GSEventRunModal + 62
	17  UIKit                               0x000000010fd4a0d4 UIApplicationMain + 159
	18  TakeItOver                          0x000000010b2cdf0f main + 111
	19  libdyld.dylib                       0x000000010f02065d start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

Here is my file structure:
![2017-05-28 12 15 04](https://cloud.githubusercontent.com/assets/8704781/26526078/fc33000e-439f-11e7-9841-b439ffa82b6b.png)

**Comment by vinayr** [comment]
I had the same issue. It looks like there are breaking changes in new version of Firebase pod (4.0.0).
https://firebase.google.com/support/release-notes/ios#4.0.0

After downgrading it to previous version it works fine for me.
```
  #pod 'Firebase/Messaging'
  pod 'Firebase/Messaging', '3.17.0'
```

**Comment by Youngdi** [comment]
@vinayr : Thank you, my problem solved!

**Comment by holyxiaoxin** [comment]
What about Non Cocoapod approach? Is there a way to download previous version?

**Comment by KarlosQ** [comment]
Thanks @felipemartim ! Now start fine 👍

**Comment by MingLoan** [comment]
great, good finding, solve my problem

**Comment by cooperka** [comment]
I got this crash as well; this library doesn't yet support the new FCM v4 on iOS, so I've opened an issue for it here: https://github.com/evollu/react-native-fcm/issues/422.

**Comment by tolgaduzenli** [comment]
Hi,
My ios app is already released to the apple store but we have one crash problem while ios-app is opening at the beginning. After installed from apple store,
1- install app
2- open app,
3- asking Notification permission to allow
4- and then crash is happening. (%90 devices)

Firebase/Crash report shows error like this;
NSInvalidArgumentException: -[RNFIRMessaging messaging:didRefreshRegistrationToken:]: unrecognized selector sent to instance.

Tried many things; moved GoogleService-Info.plist file under another group folder or used new method in RNFIRMessaging.m
[[FIRMessaging messaging] setDelegate:self];
But still it is same.

"react-native": "0.43.3",
"react-native-fcm": "^6.2.3"

This is only happening on IOS, any suggestion?

**Comment by philjoseph** [comment]
@tolgaduzenli we had the exact same issue (same stack trace) with this configuration (RN and RN-FCM versions) and with an upgrade of react-native-fcm to version 7.0.0, we've resolved that crash that keeps us busy (too) many days.
I wonder if there is a way in npm to alert users that a version requires immediate attention, but I believe that most users with pre-7 version will hit this painful issue and would love to be notified.

**Comment by tolgaduzenli** [comment]
Thanks @philjoseph it works now.

**Comment by christianchown** [comment]
Just in case anyone finds their way to this issue (as I did) with a more recent setup, I encountered this issue with:

- react-native@0.55.4
- react-native-fcm@15.0.2

The issue arose due to me referencing legacy Firebase Cocoapods in my Podfile:

```
pod 'Firebase/Core', '4.0.0'
pod 'Firebase/Messaging', '4.0.0'
```
The fix was to match them to the version from https://github.com/evollu/react-native-fcm/blob/master/Examples/simple-fcm-client/ios/Podfile.lock (4.9.0)

**Comment by jedt** [comment]
There were breaking changes recently with firebase https://firebase.google.com/support/releases We fixed this by installing the latest cocoapod version by removing the 4.0.0

```
pod 'Firebase/Core' #,'4.0.0'
pod 'Firebase/Messaging'
```

**Comment by VijayPatel91** [comment]
No need to remove or downgrade cocoa pod version. It seems their is old instruction for FCM integration in react native.
Simply in `AppDelegate.h`
**Step : 1**    `#import "RNFIRMessaging.h"`
**Step : 2**    add `FIRMessagingDelegate`

in `"AppDelegate.m"`
**Step : 3**    add below code in `didFinishLaunchingWithOptions` method 

`UNUserNotificationCenter *center = [UNUserNotificationCenter currentNotificationCenter];
  UNAuthorizationOptions options = UNAuthorizationOptionAlert + UNAuthorizationOptionSound + UNAuthorizationOptionBadge;

 // [[UNUserNotificationCenter currentNotificationCenter] setDelegate:self];
  [UNUserNotificationCenter currentNotificationCenter].delegate = self;
  
  // Objective-C
  [center requestAuthorizationWithOptions:options
                        completionHandler:^(BOOL granted, NSError * _Nullable error) {
                          if (!granted) {
                            NSLog(@"Something went wrong");
                          }
                          else {
                            [FIRMessaging messaging].delegate = self;

                            dispatch_async(dispatch_get_main_queue(), ^{
                              [FIRApp configure];
                            });


                          }
      }];`


**Step : 4**    Replace `didRefreshRegistrationToken` method with
`-(void)messaging:(FIRMessaging )messaging didRefreshRegistrationToken:(NSString )fcmToken {
  
  NSLog(@"%@", fcmToken);
} `

Build the app.
