### ISSUE TITLE
[Android] Unexpected behavior in inactive state 

### ISSUE THREAD

**Issue by kunal95** [evollu/react-native-fcm#42]
When in inactive state, I get the same notification twice if send "notification" from fcm. And no notification at all if I use "data". And if I use both data and notification, I get the same notification twice. I am using [react-native-push-notification](https://github.com/zo0r/react-native-push-notification) as well to show local notifications. Could that be the reason? And where can I override this? I think there is something wrong with my [AndroidManifest.xml](http://pastebin.com/cEciFJMu)

Simply, I want to show banner notification (local notification) even when the app is killed. Like other normal apps.

Thanks

UPDATE: I also found out that if I inlcude react-native-push-notification and react-native-fcm libraries in the same page then there is no icon in banner notification.

**Comment by evollu** [comment]
you don't need any other libraries to show the banner. fire base SDK will show the banner for you if you pass notification object in payload. that is the beauty of it.
if you pass data only, application will receive data but no banner will be created.

**Comment by evollu** [comment]
@kunal95 you can pass some attributes in notification object to config icon, sound etc. I'm not sure about screen awake and 'active' state.
Perhaps you can add a broadcast receiver to handle these extra stuff?
