### ISSUE TITLE
Support for iOS SDK v4

### ISSUE THREAD

**Issue by cooperka** [evollu/react-native-fcm#422]
The Firebase iOS SDK v4.0.0 was [released earlier this month](https://firebase.google.com/support/release-notes/ios#4.0.0) and has quite a few breaking changes.

I've tried upgrading already (using `pod update`) and most things still seem to work just fine, except for one crash on startup described in this issue: https://github.com/evollu/react-native-fcm/issues/419 (`-[RNFIRMessaging messaging:didRefreshRegistrationToken:]: unrecognized selector sent to instance`).

This library should be updated to support FCM v4, and in the meantime the README should probably also be updated to recommend staying on v3 for now (I'd be happy to submit a PR later next month to help with this, but currently am quite busy). Thanks for the great library!

**Comment by cooperka** [comment]
Looks like there's a PR up already to fix the crash mentioned: https://github.com/evollu/react-native-fcm/pull/421

**Comment by cooperka** [comment]
Solved in https://github.com/evollu/react-native-fcm/releases/tag/v7.0.0, thanks!

**Comment by philjoseph** [comment]
I just upgraded to v7 (I was concern to upgrade to latest since it's a project that must be delivered) and it fixed the crash we had at startup.
