### ISSUE TITLE
FCM.setBadgeNumber() crashes app iOS

### ISSUE THREAD

**Issue by cmedinasoriano** [evollu/react-native-fcm#429]
Hi,  I am trying to use `FCM.setBadgeNumber(0);` but it crashes the app in both iOS device and simulator.  It is giving me an error in **ios/RNFIRMessaging.m**
`RCT_EXPORT_METHOD(setBadgeNumber:_ (NSInteger*) number)`
`{`
`  [RCTSharedApplication() setApplicationIconBadgeNumber:*number]; // <---- crashes (line 389)`
`}`

react-native-fcm 7.0.0
RN 0.44.0
React 16.0.0-alpha.6
iOS 10.2

Thanks in advance for any help.

**Comment by UbermenschJO** [comment]
+1

**Comment by xxsnakerxx** [comment]
```obj-c
RCT_EXPORT_METHOD(setBadgeNumber: (NSInteger*) number)
{
  if (number) {
    [RCTSharedApplication() setApplicationIconBadgeNumber:*number];
  }
}
```

but not sure that is the best solution

**Comment by cmedinasoriano** [comment]
Thanks for that but I also found a workaround...

`RCTSharedApplication().applicationIconBadgeNumber = number;`

But I am also not sure this is the best solution.

**Comment by anback** [comment]
@cmedinasoriano solution above is also the one in the react native repo see: https://github.com/facebook/react-native/blob/master/Libraries/PushNotificationIOS/RCTPushNotificationManager.m#L302

**Comment by cmedinasoriano** [comment]
Thanks for that! Then I think I will stay with that one...  I should close this issue then, thanks everyone!!!
