### ISSUE TITLE
Multiple notifications

### ISSUE THREAD

**Issue by xuansontrinh** [evollu/react-native-fcm#43]
Can anyone give me an example about how to retrieve multiple notifications' data? 
When using `FCM.initialData`, it seems to get only the data of the notifcation you've just clicked.

**Comment by xuansontrinh** [comment]
If I use Android, I can catch the messages from Firebase, then show it (as indicated in Firebase docs) and I can use BroadcastReceiver and a database to store data from multiple notifications and access it from React Native environment. The thing is I may have to make my app work on iOS too and therefore I want to have a more effective way to handle this situation. Did I state my question in the wrong way?

**Comment by xuansontrinh** [comment]
I checked again and again and I realized that the notification data I got seemed to be partial and missing or something when I did not click on every notification. I still don't know why. Maybe you are right, even the native cannot handle this. I tried to create an app like a messenger, but without this function, it maybe a long way for me to create that kind of app. If you have some alternative ways, please let me know. I will appreciate it very much. Thank you for your contribution with this package.

**Comment by evollu** [comment]
I would either do background sync or sync on resume.
The data carried by banners a just for reference like what screen to show. don't rely on the payload in it

**Comment by evollu** [comment]
closing this, reopen if you want to discuss more
