### ISSUE TITLE
Is fcm.requestPermissions() iOS only?

### ISSUE THREAD

**Issue by bexoss** [evollu/react-native-fcm#433]
I am trying to add your component, and there was an example code like 

`FCM.requestPermissions() // for iOS`

Is that method iOS only? Then how should Android user turn on push notif?

**Comment by patlux** [comment]
https://github.com/evollu/react-native-fcm/blob/master/android/src/main/java/com/evollu/react/fcm/FIRMessagingModule.java#L67-L69

On android it's not necessary to allow push notifications.
