### ISSUE TITLE
Android: run code when app is killed

### ISSUE THREAD

**Issue by JulioC** [evollu/react-native-fcm#435]
I'm trying to run some code when I receive a notification with my app killed. I haven't got any success on my Android app (I'm not targeting IOS yet).

I've setup a `fetch` call to a log server directly on my `index.android.js` file, just to log if the app is being launched. I've also puts logs on `FCM.getInitialNotification` promise and `FCMEvent.Notification` event. Neither of these logs get called when I send notifications with the app closed (I close it by swiping it away from "Recent Screens").

To send the notifications, I'm using `fcm-node` package, with the following configuration:

```js
const message = { 
    to: registrationToken,
    data: {
        my_data: "test",
    },
};
```

Sending push notifications with the property `notification` (and its `title` and `body`) set will show in the device, with the app in background or killed.

The package versions I'm using are listed below.

```json
{
   "react": "16.0.0-alpha.6",
    "react-native": "0.44.0",
    "react-native-fcm": "^7.0.0",
}
```

**Comment by zkrige** [comment]
I'm getting the same problem and I've figured out why.

`registerMessageHandler()` is only invoked when the app is run, not when the app is backgrounded. this means that `sendOrderedBroadcast(i, null);` in `onMessageReceived` never calls the broadcast receiver, because the broadcast receiver is not registered yet

**Comment by baba43** [comment]
So this is not supported right now?

**Comment by beeglebug** [comment]
I've just hit this exact problem. I can see the `Remote message received` log from `MessagingService.java` which shows the notification has hit the device, but then nothing more happens.

I'm presuming this library is supposed to handle receiving notifications when the app is closed? If so, how has this ever worked? It seems like a fairly fundamental issue...

**Comment by zkrige** [comment]
Still no update on this? This is an important use case for background data messages

**Comment by bhosle-git** [comment]
Facing the same issue here - notifications work fine when app is in foreground or background.
But not able to get it working when app is killed (swipe away from "recent apps" screen)

**Comment by rtman** [comment]
@evollu can you comment on this?

**Comment by evollu** [comment]
There is no way to trigger JS code when app is killed for now. But you should be able to run some native code.
For iOS it is easy, you can added some code to in appdelegate.js
For android you need to hook on some intents. MessageReceiver will be called. Some change can be made there to broadcast an intent, and have some code to listen that intent.

**Comment by rtman** [comment]
@evollu do you have any references on how to get this implemented? I feel this is a must for a production app so I'll have to try and get it working.

Do you have any interest in providing a guide on how to do it and merging it into the guide for react-native-fcm?

**Comment by evollu** [comment]
@JulioC It does the same thing as we do as far as I know.
Notification Actions is something new, but shouldn't wake up JS when app is killed.
Can you post a reference here?

@rtman It will be purely server side implementation. When your server sends out a notification to a user, it calculates the badge count and save it to user table. When user clears notification on the phone, the app sends a request to server to clear the badge count. Let me know if you find a better implementation.

**Comment by JulioC** [comment]
@evollu when using the library, any notification received when the app is on background (in android), a new instance of javascript app is created and the same code you use for the UI is executed, but nothing is shown. 

I don't know about the details, but I believe [these lines](https://github.com/zo0r/react-native-push-notification/blob/7a6cf604d95eac45e34235c352639647d2b43dc9/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationListenerService.java#L64-L74) are the one responsible for executing the javascript code. They use [ReactInstanceManager.createReactContextInBackground](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/ReactInstanceManager.java#L304-L324)

**Comment by evollu** [comment]
@JulioC great finding. I will see if I can do similar things. But still it may be available for only android

**Comment by evollu** [comment]
@JulioC released in v7.5.0. Now android can trigger JS code when app is killed.

**Comment by zkrige** [comment]
FWIW. ios implementation seems to work ok. If app is killed, data packets are received and processed by application

**Comment by evollu** [comment]
@zkrige thanks for your update. I haven't tested that scenario. Good to know that it works

**Comment by rtman** [comment]
@evollu Nice! 

Other than updating to the latest version, are there new steps that need to be taken to enable this feature?

**Comment by evollu** [comment]
nope

**Comment by bhosle-git** [comment]
hi.. 

> released in v7.5.0. Now android can trigger JS code when app is killed.

update to latest version of Android? (what's the v7.5.0 of?).. 


> For android you need to hook on some intents. MessageReceiver will be called. 
> Some change can be made there to broadcast an intent, and have some code to listen that intent.

about the above - any reference implementation of what is needed here? (is it all native code or do i need some RN / js changes as well)..

thanks

**Comment by evollu** [comment]
v7.5.1 is the version of this repo. doesn't require any particular android version.
you can ignore the 2nd part now. You can just write logic in JS callbacks

**Comment by bhosle-git** [comment]
Great! I'll try that - thanks for the quick updates!

**Comment by bhosle-git** [comment]
just a quick update - upgraded to 7.5.1 and it worked like a charm! thanks again :)

**Comment by evollu** [comment]
not sure about this. isn't jest suppose to mock out your react-native-fcm module?

**Comment by bhosle-git** [comment]
didn't need to mock out react-native-fcm earlier, and looks like the change (between 6.2.3 and 7.5.1) is causing this:

line 3 in node_modules/react-native-fcm/index.js
const EventEmitter = new NativeEventEmitter(NativeModules.RNFIRMessaging);

anyways.. jest mocking should fix this.. will try that. thanks.

**Comment by evollu** [comment]
ok cool
closing this as the issue should be fixed

**Comment by bhosle-git** [comment]
Cool.. Was about to update here that it is working after mocking out
react-native-fcm..

Thanks again for the quick responses here!

**Comment by karthikpala** [comment]
Receiving push notification when app is killed is not working in latest version 8.0.0. Is there any change I should do. Please let me know.
BTW I am receiving `D/MessagingService: Remote message received` in logcat but the app is not opening and callback of FCMNotificationReceived is not called.

**Comment by karthikpala** [comment]
`handler.post(new Runnable() {
            public void run() {
                // Construct and load our normal React JS code bundle
                ReactInstanceManager mReactInstanceManager = ((ReactApplication) getApplication()).getReactNativeHost().getReactInstanceManager();
                ReactContext context = mReactInstanceManager.getCurrentReactContext();
                // If it's constructed, send a notification
                Log.d(TAG, "context"+context);
                if (context != null) {
                    context.sendOrderedBroadcast(message, null);
                } else {
                    // Otherwise wait for construction, then send the notification
                    mReactInstanceManager.addReactInstanceEventListener(new ReactInstanceManager.ReactInstanceEventListener() {
                        public void onReactContextInitialized(ReactContext context) {
                            Log.d(TAG, "context-1"+context);
                            context.sendOrderedBroadcast(message, null);
                        }
                    });
                    if (!mReactInstanceManager.hasStartedCreatingInitialContext()) {
                        // Construct it in the background
                        Log.d(TAG, "context-2"+context);
                        mReactInstanceManager.createReactContextInBackground();
                    }
                }
            }
        });`
While checking from the logs, the context is null when the app is killed. Is this the reason why the callback is not being called?

@evollu Please help

**Comment by Vetalyo** [comment]
Does anybody found how to run app after dropped from process on iOS ?

**Comment by Keksike** [comment]
I'm still having this error when trying to run tests with Jest:
```
Invariant Violation: Native module cannot be null.

  at invariant (node_modules/fbjs/lib/invariant.js:44:15)
  at new NativeEventEmitter (node_modules/react-native/Libraries/EventEmitter/NativeEventEmitter.js:32:1)
  at Object.<anonymous> (node_modules/react-native-fcm/index.js:3:18)
```

**Comment by Keksike** [comment]
@bhosle-git can you provide your mock-fix for Jest?

**Comment by bhosle-git** [comment]
Hi @Keksike 

sorry - didn't see your comment earlier. 
I just added the following in __mocks__/react-native-fcm.js

thanks
AB

const fcm = jest.mock('react-native-fcm')
fcm.getFCMToken = () => new Promise((resolve, reject) => { resolve() });
fcm.FCMEvent = {
    Notification: 'FakeNotification'
};
fcm.on = jest.fn();
fcm.getInitialNotification = () => new Promise((resolve, reject) => { resolve() }); 

module.exports = fcm;

**Comment by sfm2222** [comment]
@bhosle-git  I'm not getting notification data when app is in background. Tried doing it but it didnt helped can you suggest what should I do? I'm sending notification from C# code

 {
    	to: "fcm_token",
    	notification: {
    		body: "your order is okay",
    		title: "Brg - Your order"
    	}, 
data:{
body: "your order is okay",
    		title: "Brg - Your order", 
type="newentry"
}
    }
I'm receiving notification on ios. I'm performing some actions in FCM.on(FCMEvent.Notification, notif => { method.

this.notificationListener = FCM.on(FCMEvent.Notification, async (notif) => { is only called when iOS app is in foreground not in background. When opening app clicked from notification this is never called.
