### ISSUE TITLE
[Android] Send notification with no sound

### ISSUE THREAD

**Issue by motiazu** [evollu/react-native-fcm#441]
Hi
I'm sending a notification (Android only at the moment) with the same id which causes it to keep updating it's text. I noticed the API doesn't allow me to send a null sound. The current implementation will use the default sound if I don't choose one, and will not display the notification if I use a non-existent sound file name. And the code will never `setSound(null)`.

It is important for me to send the notification with no sound when I'm only updating it's text, this way it also doesn't pop over things and takes more attention than I want it to.

Is there a specific reason the API doesn't allow that? Will anyone oppose to me adding it?

**Comment by douglasjunior** [comment]
Same problem here.

**Comment by douglasjunior** [comment]
I sent a Pull Request, please, upvote #517.
