### ISSUE TITLE
Notification not showing up with icon - Android

### ISSUE THREAD

**Issue by KeKsBoTer** [evollu/react-native-fcm#444]
Hallo,
I'm running my app on Android with react 16.0.0-alpha.12 and react-native 0.44.0 and  react-native-fcm 7.0.3.

If the app runs in the foreground and a notification comes in the notification is displayed and the sound is played.
As soon as I set the "icon" property to "ic_launcher" the notification is no longer displayed and only the sound is played.

**Comment by Alessia958** [comment]
hi, any update?

**Comment by evollu** [comment]
seems to be an old issue.
make sure your icon file is only white and transparent

**Comment by evollu** [comment]
closing this as it is pretty old
