### ISSUE TITLE
Can not set icon

### ISSUE THREAD

**Issue by KeKsBoTer** [evollu/react-native-fcm#445]
Hallo,
I am runing react 16.0.0-alpha.12, react-native 0.44.0 and react-native-fcm 7.0.3 on Android

Everything is working fine but I can not set the notification icon.
If I use "icon": "ic_launcher" I only see a white rectangle as icon. (runing in foreground and background)
I can only change the "large_icon" to "ic_launcher", but this only works in foreground.

I fail to change the icon for background notifications.

Thanks for your help!

**Comment by mickamy** [comment]
@KeKsBoTer 
According to my observation, small icon is hardcoded in [here](https://github.com/evollu/react-native-fcm/blob/master/android/src/main/java/com/evollu/react/fcm/FIRLocalMessagingHelper.java#L104-L107).
So, mipmap resource which named `ic_launcher` will be used as small icon.
(I have not tested just read it, so I could be wrong)

Is there anybody who could set icon for notification with this lib?

**Comment by SelaO** [comment]
Did anyone manage to fix this?

**Comment by namxam** [comment]
Yeah, having the same issue right now

**Comment by namxam** [comment]
Ok, I still have an issue, as I only see a generic android icon. But in your case it sounds as if you haven't specified any transparency in your icon. From what I have read the last hours, background notifications do not support setting a coloured icon. You need to specify an icon with an outline and you can set a highlight colour.

**Comment by evollu** [comment]
as @namxam said, icon has to be an outline. it is working as desired

**Comment by namxam** [comment]
@evollu I guess this issue could be closed then
