### ISSUE TITLE
Topic messages

### ISSUE THREAD

**Issue by jokeronaldo** [evollu/react-native-fcm#447]
Is there a way to subscribe an user to a topic? I mean, the user subscribes to a topic and the event only looks for that topic where user is in.

User is subscribed in some topic and FBM will only receive messages from specific topic. If it's possible with this lib? Can you provide some example code?

Thank you =)

**Comment by jokeronaldo** [comment]
A

**Comment by jokeronaldo** [comment]
Well, I see something in *usage* and may it helps me, but, why not doc all avaliable API methods?

Thank you again.

**Comment by mohamed-alashry** [comment]
how do you subscribe to a topic, I found nothing in the usage.
any help would be appreciated.

**Comment by evollu** [comment]
@mohamed-alashry `FCM.subscribeToTopic`.

**Comment by mohamed-alashry** [comment]
thanks. it would be more helpful if it would be in the documentation though.
