### ISSUE TITLE
App Receive multiple notifications when I send only one

### ISSUE THREAD

**Issue by matheusnpenna** [evollu/react-native-fcm#453]
This is my code:
this.notificationListener = FCM.on(FCMEvent.Notification, async (notif) => {
      if (notif.local_notification) {
        //this is a local notification        
      }
      if (notif.opened_from_tray) {
        //app is open/resumed because user clicked banner
        this.startListener();  
        Actions.Index();
      }
      this.showLocalNotification(notif);
    });

 showLocalNotification(notif) {
    FCM.presentLocalNotification({
      title: notif.title,
      body: notif.body,
      priority: "default",
      large_icon: "ic_launcher",
      icon: "ic_launcher",
      click_action: notif.click_action,
      vibrate: 0,
      show_in_foreground: true,
      local: true,
      sound: "sound6",
      number: 1,
    });
  }
![eduzz bug](https://user-images.githubusercontent.com/19397224/27653412-56beb21a-5c15-11e7-9b68-f51e93c5a859.jpg)

**Comment by ciscoinc** [comment]
just getting this too, I reduce from 3 to 2 notifications by removing the contentavailable flag

**Comment by rodrigoxavier** [comment]
Are you trying to show a scheduled notification? 
I've faced a problem like this and solve it by do not call the method "showLocalNotification". When you schedule a local notification the app will show it at the time scheduled.
Otherwise, try to comment the line "this.showLocalNotification(notif);" in your code and maybe the loop will stop.

Hope helpe someone.

**Comment by Xaeonn** [comment]
Are you using any other libraries that have the ability to present notifications? I had this issue while using intercom as their library was also importing fcm in javaland.

**Comment by rochapablo** [comment]
+1

**Comment by evollu** [comment]
you are calling `this.showLocalNotification(notif);` inside notification handler, which will create a new notification when you receive a notification.

**Comment by matheusnpenna** [comment]
How can I mark this issue like a fixed?
