### ISSUE TITLE
White square icon on android

### ISSUE THREAD

**Issue by EdmundMai** [evollu/react-native-fcm#458]
https://stackoverflow.com/questions/44845797/firebase-cloud-messaging-how-to-set-the-notification-icon-on-android#44846227

I set up the drawable folder like so:

<img width="346" alt="androidmanifest_xml_-_bananaclient_-____documents_src_banana-client_android_" src="https://user-images.githubusercontent.com/1857068/27736112-ac618f5c-5ddd-11e7-93b8-ca6d4aa97e22.png">

I was suspecting that it might be because my icon had colors, so I downloaded a random image on the web that is white with no background:

<img width="619" alt="notification_icon_png_and_drawable-hdpi_and_downloads" src="https://user-images.githubusercontent.com/1857068/27736383-e9a0f6d6-5dde-11e7-83d5-8c203f1b01b4.png">

And I've also set the default icon in my AndroidManifest.xml file:

>       <meta-data
>         android:name="com.google.firebase.messaging.default_notification_icon"
>         android:resource="@drawable/notification_icon" />

And here I'm setting the icon field to `notification_icon`: https://developers.google.com/cloud-messaging/http-server-ref#downstream-http-messages-json (p.s. I'm aware that's GCM, but it works. I'm receiving the notification with everything besides the icon)

What am I missing? All I see is a white square inside a grey circle.

This is my backend code: ```Pushex.push(%{title: user.name, body: "message goes here", badge: 1, sound: "default", icon: "notification_icon"}, to: user.fcm_token, using: :gcm)``` (https://github.com/tuvistavie/pushex)

**Comment by diegorodriguesvieira** [comment]
+1

**Comment by EdmundMai** [comment]
@diegorodriguesvieira fixed it...

Fixed it... this is so stupid. Was inspired by this answer:
https://stackoverflow.com/a/28387744/1555312

I made my notification icon my app icon:

    <meta-data
        android:name="com.google.firebase.messaging.default_notification_icon"
        android:resource="@mipmap/ic_launcher" />

And then the magic line in `android/app/build.gradle`...

    defaultConfig {
        targetSdkVersion 20 // this has to be < 21
        ...
    }

Hope I save hours of someone else's life

**Comment by rajaishwary** [comment]
@EdmundMai but what if I have published my app with targetSdkVersion greater than 20 before.
Play Store does not allow to push lower targetSdkVersion if upper targetSdkVersion already pushed before.

**Comment by damathryx** [comment]
@rajaishwary  how did you fix it ? I am facing same problem

**Comment by rajaishwary** [comment]
@damathryx to fix this issue, you need to add the white icon with transparent background.

Changes in AndroidManifest.xml [in application level]

      <meta-data
        android:name="com.google.firebase.messaging.default_notification_icon"
        android:resource="@mipmap/icon"
      />
      <meta-data android:name="com.google.firebase.messaging.default_notification_color"
        android:resource="@color/orange" 
      />

... and add white logo with transparent background in res.

![image](https://user-images.githubusercontent.com/7762321/31878744-b3556124-b7f8-11e7-9762-1fd557b3c104.png)

sample icon image. It should be like below:
![image](https://user-images.githubusercontent.com/7762321/31878787-d745e9dc-b7f8-11e7-8a6c-2ac3bd3585ee.png)


My compile and target sdk versions.
![image](https://user-images.githubusercontent.com/7762321/31878891-38f6dd94-b7f9-11e7-9952-4291c7103f62.png)

Hope it will help you and feel free to ask if it doesn't work for you.

**Comment by hanpanpan200** [comment]
@EdmundMai 

Hi I don't think change API version is a good way, since android 5.0, google notification icon can only have two colors: transparent and white.

So to follow google's guide, it's better that you change the your notification icon.

**Comment by manuTro** [comment]
@rajaishwary this is not working for mi.. what is your targetSDKversion?

**Comment by Hayko985** [comment]
My code not worked even when I added 

`<meta-data
    android:name="com.google.firebase.messaging.default_notification_icon"
    android:resource="@mipmap/icon"
  />`
  `<meta-data android:name="com.google.firebase.messaging.default_notification_color"
    android:resource="@color/orange" 
  />`
 
But when I moved the icon from mipmap to drawable and change the mipmap to drawable in meta-data, that worked.

Now it is something like this.
`<meta-data
    android:name="com.google.firebase.messaging.default_notification_icon"
    android:resource="@drawable/icon"
  />`
  `<meta-data android:name="com.google.firebase.messaging.default_notification_color"
    android:resource="@color/orange" 
  />`


Hope it helps someone.
Regards.
