### ISSUE TITLE
[android] heads-up notification

### ISSUE THREAD

**Issue by kayrules** [evollu/react-native-fcm#46]
How to show heads-up notification on android?
I am using the following payload from fcm.

```
{
    to: <deviceToken>,
    priority: 'high',
    data: {
        custom_data_key: 'custom_data_value'
    },
    notification: {
        title: 'Push notification test',
        body: message,
        click_action: 'fcm.ACTION.HELLO',
        sound: 'default'
    }
}
```

**Comment by evollu** [comment]
haven't experimented with this yet. let me try

**Comment by evollu** [comment]
opened a ticket to fcm. will keep you updated

**Comment by peterpme** [comment]
@evollu did you happen to see this?
https://stackoverflow.com/questions/37458530/firebase-when-receive-push-notification-did-not-receive-the-popup

We may have to key on `didReceiveNotification`

no popup will occur if the app is in the foreground either, only background

**Comment by evollu** [comment]
no. the didReceiveNotification...withHandler is enough.
are you not having banner for iOS? ios should work perfectly

**Comment by evollu** [comment]
@peterpme is your problem solved?

**Comment by evollu** [comment]
@kayrules 
all supported feature is [here](https://firebase.google.com/docs/cloud-messaging/http-server-ref#notification-payload-support) for now. They've added a feature request but don't know when it will be available
So if you need head up display, send notification with `data` only and create notification locally is the only way for now.

**Comment by kayrules** [comment]
Noted and thanks @evollu

**Comment by hoiheart** [comment]
If i send only data, head up notification works fine
but, can`t recieve notification if i killed app
Could you give me a solution to head up notification for all status?
(status : foreground, background, killed)

**Comment by evollu** [comment]
what is your payload

**Comment by hoiheart** [comment]
Payload
![image](https://cloud.githubusercontent.com/assets/25652218/22769123/0fff2d90-eeca-11e6-87ff-1e5f2a57208d.png)

Android platform
![image](https://cloud.githubusercontent.com/assets/25652218/22769111/febf884a-eec9-11e6-9686-59ae5d68ea14.png)

Result (foreground, background, killed)
![image](https://cloud.githubusercontent.com/assets/25652218/22769178/5bf8d6ce-eeca-11e6-83ff-ef9de47fc098.png)

**Comment by evollu** [comment]
for android only:
```
payload = {
      to: 'gcm',
      data: { 
          custom_notification: {
              title: message.title,
              body: message.body,
              icon: NOTIFICATION_ICON,
              color: NOTIFICATION_COLOR,
              priority: 'high',
             id: message.id,
             group: message.group
      } }
    };
```

**Comment by hoiheart** [comment]
This works well!
Thank you so much :)

**Comment by rtman** [comment]
@hoiheart @evollu 

Is this still working? Because when I try the above payload I get 

Error: Messaging payload contains an invalid value for the "data.custom_notification" property. Values must be strings.

I have tried switching everything to strings and it still says this.

```
				var payload = {
				      'data': {
				          	'custom_notification': {
				            	'title': 'title',
				              	'body': 'body',
				              	'priority': 'high',
				              	'id': 'id',
				      } }
				  };
```

Is custom_notification still valid? It looks like it is not working anymore.

**Comment by seanadkinson** [comment]
Same issue for me... says that "data.custom_notification" isn't valid.

**Comment by seanadkinson** [comment]
Looking through the source code, I see this:

```

    public void buildLocalNotification(RemoteMessage remoteMessage) {
        if(remoteMessage.getData() == null){
            return;
        }
        Map<String, String> data = remoteMessage.getData();
        String customNotification = data.get("custom_notification");
        if(customNotification != null){
            try {
                Bundle bundle = BundleJSONConverter.convertToBundle(new JSONObject(customNotification));
                FIRLocalMessagingHelper helper = new FIRLocalMessagingHelper(this.getApplication());
                helper.sendNotification(bundle);
            } catch (JSONException e) {
                e.printStackTrace();
            }

        }
    }
```

Looks like it may need to just be a JSON string... will try `JSON.stringify` on the `custom_notification` value.

**Comment by rtman** [comment]
@seanadkinson 

Hey I saw this too just yesterday.

I think part of my problem was that I was using admin.messaging to send notifications and it does not allow nested objects. However I might try your idea about json.stringify on the nested object.

I noticed yesterday in the example code that there is a whole other method for sending notifications using fetch and http are you using this method or admin.messaging?

_Sent from my Google Nexus 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by evollu** [comment]
Firebase should stringify nested object itself automatically.
Is it a breaking change then?

**Comment by rtman** [comment]
Hey @evollu 

I spoke to firebase support and they said this:

> As far as I know, there are no changes in the structure of the payloads in FCM and 2-level JSON is not supported. 

So they seem to think nested objects have never been supported.

I was using admin.messaging to send my payload. I also wasn't JSON.stringifying the payload. Could this be the issue?

**Comment by rtman** [comment]
Just tried to JSON.stringify the payload with admin.messaging() and can confirm that it does not work.

**Comment by rtman** [comment]
OK I can confirm that this does work still but only with fetch send function in the example. It does not work with admin.messaging.

Here is what I am doing:

```
    _send(body, type) {
        let headers = new Headers({
            "Content-Type": "application/json",
            "Content-Length": parseInt(body.length),
            "Authorization": "key=" + firebaseConstants.KEY
        });

        fetch(firebaseConstants.API_URL, { method: "POST", headers, body })
            .then(response => {
                console.log("Send " + type + " response", response)
                switch (response.status) {
                    case 500: console.error('Some server error'); break;
                    case 401: console.error('Unauthorized'); break;
                    // ...
                }
                if (response.ok) {
                    return response;
                } else {
                    // push error further for the next `catch`, like
                    return Promise.reject(response);
                    // or another way
                    throw Error(response.statusText);
                }
            })
            .catch(error => {
                console.log("Error sending " + type, error)
            });
    }

```
Here is my payload:
```

            let body = {
                "to": this.friend.token,
                "data": {
                    "custom_notification": {
                        "body": message.text,
                        "title": this.friend.name,
                        "color":"#00ACD4",
                        "priority":"high",
                        "id": id,
                        "show_in_foreground": true,
                        "sound": "default",
                        "click_action": "fcm.ACTION.OPEN_NOTIFICATION",
                        "vibrate": 300,
                        "lights": true,
                        uid: this.friend.uid
                    }
                },
                "priority": "high",
                "click_action": "fcm.ACTION.OPEN_NOTIFICATION"
            }
            //"icon":"ic_launcher",
            //"large_icon": "ic_launcher",

            this._send(JSON.stringify(body), "data");
```

**Comment by seanadkinson** [comment]
@rtman Just getting back to trying it out, but I don't think you'd stringify the entire payload, just the `custom_notification` value object.  Going to do some testing now though.

I am using `admin.messaging` btw

**Comment by seanadkinson** [comment]
@evollu Yeah, they aren't stringify-ing automatically anymore I guess.

@rtman I can confirm that `JSON.stringify` on the `custom_notification` value DOES work using `admin.messaging`.

**Comment by rtman** [comment]
@seanadkinson 

So you did this?

```
				var payload = {
				      'data': {
				          	JSON.stringify('custom_notification': {
				            	'title': 'title',
				              	'body': 'body',
				              	'priority': 'high',
				              	'id': 'id',)
				      } }
				  };
```

**Comment by seanadkinson** [comment]
No.  Just the value of `custom_notification`.  See updates to README in this PR: #525

**Comment by rtman** [comment]
Ah ok I see now.

Any thoughts on which is better to use? Admin messaging or fetch?

_Sent from my Google Nexus 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by seanadkinson** [comment]
Functionally the same (as far as I know), but if you are using typescript, the `admin.messaging` has all the types available for nice auto-complete and static validation.

**Comment by rtman** [comment]
Cool, I have noticed that the fetch is reliably much faster to show a notification too.

I wonder how it will work with offline situations when I implement that in the future, but I'll cross that bridge when I get to it!

_Sent from my Google Nexus 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
