### ISSUE TITLE
libRNFIRMessaging.a in red

### ISSUE THREAD

**Issue by abhitheawesomecoder** [evollu/react-native-fcm#460]
No matter which version of react-native-fcm I am trying its always showing libRNFIRMessaging.a in red 
I tried react-native-fcm@2.1.1
I am using IOS 9
App is giving Build Failed 
![screen shot 2017-07-03 at 11 36 42 am](https://user-images.githubusercontent.com/3944526/27780137-df27c218-5fe4-11e7-93c2-208a8f67e40f.png)

**Comment by abhitheawesomecoder** [comment]
fixed

**Comment by mchandleraz** [comment]
@abhitheawesomecoder it's considered good etiquette to include information about how you solved your problem, rather than just saying you fixed it. Imagine the time you'd have saved if someone had posted the solution after they experienced it themselves :)

**Comment by mvanroon** [comment]
@abhitheawesomecoder I'd really like to know how you fixed it
