### ISSUE TITLE
Background notification from backend only gives the notification object but no notificaiton

### ISSUE THREAD

**Issue by MarkoVk95** [evollu/react-native-fcm#476]
What version of RN and react-native-fcm are you running?
Latest

What device are you using? (e.g iOS9 emulator, Android 6 device)?
Android emulator and phone 6.0

Is your app running in foreground, background or not running?
The problem is on background

**The notification gets delivered both on Bbackground and Foreground but on Background it wont give me a notification on my system tray too,only a notification message on console that i show below.
The notifications through FCM dashboard work fine ,i receive both the message and the push notification on the system tray while on background.**

Here is the notif objecft from the Notification event  :

> Object {vibrationPattern: "[0,1000]", fcm: Object, collapse_key: null, google.message_id: "0:1500980623509228%4c657867f9fd7ecd", articleId: "444444"…}
> articleId:"444444"
> badge:"1"
> body:"My body texxxxt"
> breakingNews:"1"
> collapse_key:null
> fcm:Object
>     __proto__:Object
>     finish:function finish(result)
> from:"372190800011"
> google.message_id:"0:1500980623509228%4c657867f9fd7ecd"
> google.sent_time:1500980623471
> icon:"bigicon"
> image:"www/img/bigicon.png"
> title:"My title texxxxtt"
> vibrationPattern:
> "[0,1000]"
> __proto__:Object

**Comment by MarkoVk95** [comment]
This is my AndroidManifest.xml

```
> <manifest xmlns:android="http://schemas.android.com/apk/res/android"
>     package="NotImportant"
>     android:versionCode="1"
>     android:versionName="1.0">
> 
>     <uses-permission android:name="android.permission.INTERNET" />
>     <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
> 
>     <uses-sdk
>         android:minSdkVersion="16"
>         android:targetSdkVersion="22" />
> 
>     <application
>       android:name=".MainApplication"
>       android:allowBackup="true"
>       android:label="@string/app_name"
>       android:icon="@mipmap/ic_launcher"
>       android:theme="@style/AppTheme">
> 
>     <service android:name="com.evollu.react.fcm.MessagingService" android:enabled="true" android:exported="true">
>       <intent-filter>
>          <action android:name="com.google.firebase.MESSAGING_EVENT"/>
>       </intent-filter>
>     </service>
> 
>     <service android:name="com.evollu.react.fcm.InstanceIdService" android:exported="false">
>     <intent-filter>
>        <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
>      </intent-filter>
>     </service>
> 
>       <activity
>         android:name=".MainActivity"
>         android:label="@string/app_name"
>         android:launchMode="singleTop"
>         android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
>         android:windowSoftInputMode="adjustResize">
>         
>         <intent-filter>
>             <action android:name="android.intent.action.MAIN" />
>             <category android:name="android.intent.category.LAUNCHER" />
>         </intent-filter>
> 
>          <intent-filter>
>           <action android:name="fcm.ACTION.HELLO" />
>           <category android:name="android.intent.category.DEFAULT" />
>         </intent-filter>
> 
>       </activity>
>       <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
>     </application>
> 
> </manifest>
> 
```

**Comment by karthikpala** [comment]
I am also facing same issue, could you please let me know why this is closed?
