### ISSUE TITLE
Badges don't work on Samsung devices on Android 7

### ISSUE THREAD

**Issue by mgoforth** [evollu/react-native-fcm#477]
@evollu I recently ran into some issues regarding badging on Android, specifically Samsung devices on Android 7.

The issues seem to have been addressed in [Shortcut Badger](https://github.com/leolin310148/ShortcutBadger) v1.1.14, but currently we're only targeting v1.1.10.  I've done _some_ local testing on a Galaxy S6 and S8 and everything seems to be working as expected.

Would you consider updating the Shortcut Badger dependency?

**Comment by evollu** [comment]
released 7.4.0 with 1.1.17
