### ISSUE TITLE
Popup not working when the app is killed or running in background Android

### ISSUE THREAD

**Issue by venkat-waran** [evollu/react-native-fcm#481]
This is the payload im sending
{
 "to":"",
  "content_available": true,
  "notification": {
      "title": "hello",
      "body": "yo",
      "click_action": "fcm.ACTION.OPEN_NOTIFICATION",
      "show_in_foreground": true,
      "content_available": true
  },
   "custom_notification": {
   	"content_available": true,
        "title" : "Test title",
        "body" : "Test body",
        "color": "#00ACD4",
        "priority": "high",
        "show_in_foreground": true,
        "click_action": "fcm.ACTION.OPEN_NOTIFICATION"
   },
  "data": {
      "extra":"juice"
  },
  "priority": "high"
}

**When the app is in foreground its working fine. But when the app is in background or killed. Im getting the Notification but the tray or popup is not coming. Im stuck with this.**

**Comment by ravi06mishra** [comment]
I am having the same problem.

**Comment by PARAGJYOTI** [comment]
Same problem here ... 
And Custom notification also doesnot work . Just gives the sound , but nothings there . No icon , no popup.

**Comment by venkat-waran** [comment]
I found the solution for android. 
Send the payload like this:

`{
"to":"",
 "data": {
    "custom_notification": {
      "body": "test body",
      "title": "test title",
      "color":"#00ACD4",
      "priority":"high",
      "icon":"ic_launcher",
      "id": "id",
      "show_in_foreground": true,
      "sound": "default",
      "large_icon": "ic_launcher",
      "click_action": "fcm.ACTION.OPEN_NOTIFICATION",
      "vibrate": 300, 
      "lights": true
	}
  },
"priority": "high",
"click_action": "fcm.ACTION.OPEN_NOTIFICATION"
}`

**Comment by rtman** [comment]
@venkat-waran 

I am getting this error when I try to use custom_notification nested in the data object of my payload:

Error: Messaging payload contains an invalid value for the "data.custom_notification" property. Values must be strings.

Can you let me know if the above payload is still working for you?

**Comment by venkat-waran** [comment]
Yeah its working. Can you share your payload?

**Comment by rtman** [comment]
Hey! @venkat-waran 

Sure, my payload is very similar to what you are using, I even tried what you are using but it complained about several of the keys such as 'to', 'priority', 'custom_notification'

Here is the one I am currently trying:

```
				var payload = {
			        'data': {
			          	'custom_notification': {
				            	'title': 'title',
				              	'body': 'body',
				              	'priority': 'high',
				              	'id': 'id',
				      	}
					}
				};
```

If you are able to use custom_notification object nested in the data object, I'm not seeing what I'm doing wrong here. Thanks for the help in advance by the way!

**Comment by rtman** [comment]
I just tried this other payload direct from the react-native-fcm docs:

```
				var payload = {
				  "to":"FCM_TOKEN",
				  "data": {
				    "type":"MEASURE_CHANGE",
				    "custom_notification": {
				      "body": "test body",
				      "title": "test title",
				      "color":"#00ACD4",
				      "priority":"high",
				      "id": "id",
				      "show_in_foreground": true
				    }
				  }
				};
```

I get a similar error:
 Error: Messaging payload contains an invalid "to" property. Valid properties are "data" and "notification".

It's odd because the firebase cloud messaging docs specifically say you can use a "to" property. Not sure whats going on here.

**Comment by rtman** [comment]
@venkat-waran 
Hey can you share your payload that is working? I'm still trying to figure this out and its driving me kinda crazy. I don't understand how you could be able to use custom_notification but I cannot.

This payload you're using is used with cloud functions right? Do you send your payload like this?

```
				admin.messaging().sendToDevice(receiverData.token, payload, options).then((response) => {

					console.log("Successfully sent message - Response", JSON.stringify(response))
				}).catch(function(error) {
				    console.log("Error sending message stringify:", JSON.stringify(error));
				});
```

thanks
