### ISSUE TITLE
how does refreshToken work?

### ISSUE THREAD

**Issue by bhosle-git** [evollu/react-native-fcm#482]
Hi,

I'm trying to understand how the refresh-token flow works.. I see the following code snippet in the tutorial about registering a listener for the RefreshToken, but have not been able to test it.. 

 this.refreshTokenListener = FCM.on(FCMEvent.RefreshToken, (token) => {
            console.log(token)
            // fcm token may not be available on first load, catch it here
        });

Also, who detects that the token needs to be refreshed? (or should I periodically refresh the token?)
(any documentation on the above would also be great)

thanks
Amit

-------------------

I'm not checking this repo every day since it is fairly stable now. If you have found a bug or need immediate attention please [AT]me

Please include following information for better support

What version of RN and react-native-fcm are you running?
What device are you using? (e.g iOS9 emulator, Android 6 device)?
Is your app running in foreground, background or not running?

Advanced:
Have you tried adding break point in native handlers to see if message gets delivered?
can share a project with issue?

**Comment by evollu** [comment]
https://firebase.google.com/docs/cloud-messaging/android/client#monitor-token-generation
FCM changes refresh token from time to time for some reason.

**Comment by sibelius** [comment]
everytime the user install your app again it will change the token

I think we can close this

**Comment by HAMPLENI** [comment]
Here is some documentation on when the onTokenRefresh event handler will be hit:

https://firebase.google.com/docs/reference/android/com/google/firebase/iid/FirebaseInstanceIdService
