### ISSUE TITLE
can I emulate FCM.getBadgeNumber in Android? Or get an event when the notification is received?

### ISSUE THREAD

**Issue by nicolasdanelon** [evollu/react-native-fcm#486]
Hi have a question for you @evollu 
I'm almost done with a react native app, using your plugin react-native-fcm and I really need a way to hook me when the user receive a push notification.

So if this is method is not available in Android:

```javascript
FCM.setBadgeNumber(1);
FCM.getBadgeNumber().then(number => number)
```

can I hook my code somewhere over here?
```javascript
this.notificationListener = FCM.on(FCMEvent.Notification, async (notif) => {
// here ?
});
```
```
react-native-fcm: 6.1.0
react-native: 0.41.2
```

I'm running the app in Ganymotion with android 6.0.0 and a real device: Sony X performance with Android 7.1.0

The message is actually delivered. From FireBase and locally.

**Comment by evollu** [comment]
these badge functions are available for some android devices. Some manufactures adds badge feature but devices from Google like Nexus may not have it.

I assume you want to use that function to do incremental badge count. Yes, you can do this with Android with the latest release of the repo. But this method is not reliable for iOS.

**Comment by nicolasdanelon** [comment]
I can try with [react-native-android-badge](https://www.npmjs.com/package/react-native-android-badge) but I need an alternative solution to hook me, any idea?

**Comment by evollu** [comment]
I don't quite get you.
```
FCM.setBadgeNumber(1);
FCM.getBadgeNumber().then(number => number)
```
is available for android in this repo.

**Comment by nicolasdanelon** [comment]
and this will work if the manufactures has added the feature, right?

**Comment by evollu** [comment]
right

**Comment by nicolasdanelon** [comment]
thanks!

**Comment by nicolasdanelon** [comment]
sorry but.. following the example in the readme, where should I call the FCM.setBadgeNumber() ?

**Comment by evollu** [comment]
anywhere you want to update the badge

**Comment by nicolasdanelon** [comment]
ok... but in the FCM object have we a FCM.alreadyReceived()? or something? I need a hook in order to show or hide things in my app. I need a point in the component **before** the push notification rendering

**Comment by evollu** [comment]
if you want to handle badge when you just received a notification
```
this.notificationListener = FCM.on(FCMEvent.Notification, async (notif) => {
// yes, put here
   let existing = await FCM.getBadgeNumber()
   await FCM.setBadgeNumber(existing+1)
});
```

**Comment by nicolasdanelon** [comment]
awesome, thanks!

**Comment by nicolasdanelon** [comment]
sorry to bother you, but your code is adding the badge when I open the push notification, not when it's received :(

**Comment by evollu** [comment]
i guess you killed the app? you need to put FCM.on(FCMEvent.Notification) outside of component lifecycle if you want to handle it when app is killed

**Comment by nicolasdanelon** [comment]
haha this work for me also

```xml
     <service android:name="com.blahblahblah.MessagingService" android:enabled="true" android:exported="true">
       <intent-filter>
         <action android:name="com.google.firebase.MESSAGING_EVENT"/>
       </intent-filter>
     </service>
```
```java
public class MessagingService extends com.evollu.react.fcm.MessagingService {

    private static final String TAG = "FinGuruMessagingService";

    @Override
    public void handleBadge(RemoteMessage remoteMessage) {
        BadgeHelper badgeHelper = new BadgeHelper(this);
        if (remoteMessage.getData() == null) {
            return;
        }

        Map data = remoteMessage.getData();
        if (data.get("badgeIncrement") == null) {
            return;
        }

        int oldBadgeCount = badgeHelper.getBadgeCount();
        badgeHelper.setBadgeCount(oldBadgeCount + 1);
    }
}
```

**Comment by evollu** [comment]
yeah this is what I suggested at the first place

**Comment by bkitduy** [comment]
How can you solved that on iOS platform when app killed?

**Comment by evollu** [comment]
@bkitduy you are saying when user swipe away the app? you can't

**Comment by bkitduy** [comment]
I mean when app iOS killed, how can I get notification and show badge on icon

**Comment by evollu** [comment]
no you can't. when iOS app is killed by user you can't launch background processing. You will need to send badge count though notification
