### ISSUE TITLE
Application get open when notification received while the app is not in the background

### ISSUE THREAD

**Issue by Jaafar-abusair** [evollu/react-native-fcm#492]
My problem is the application get open when notification received while the app is not in the background, if the application already running but in the background, it will stay in the background which is expected.
when the app not running, it shouldn't get open after receive notification, only should open when click on notification.

What version of RN and react-native-fcm are you running? ^7.5.1
What device are you using? (e.g iOS9 emulator, Android 6 device)? emulator 7.1.1
Is your app running in foreground, background or not running? foreground

Advanced:
Have you tried adding break point in native handlers to see if message gets delivered?
can share a project with issue?

**Comment by horacehylee** [comment]
+1 The app just opened when received notification

**Comment by evollu** [comment]
can you reproduce with the example app?

**Comment by peteroid** [comment]
I got this issue on my rn 0.46 project which is using react native navigation.  And my rn-fcm version is 10+.

**Comment by horacehylee** [comment]
I resolved this issue, I am using wix/react-native-navigation.
Please refer to this, if you are also using wix/react-native-navigation.
https://wix.github.io/react-native-navigation/#/android-specific-use-cases?id=compatibility-with-headlessjs

**Comment by peteroid** [comment]
@horacehylee Thanks so much. You've saved my days.

**Comment by stonecold123** [comment]
Yes, that method `Navigation.isAppLaunched` still works in React 0.53. I have switched back from react-native-firebase after finding this solution.

**Comment by fukemy** [comment]
any solution now? Thanks
