### ISSUE TITLE
Question: any side-effect of using singleTask?

### ISSUE THREAD

**Issue by pewh** [evollu/react-native-fcm#495]
Hello,

I'm newbie Android. I've see react-native-fcm setup from Android, and it mentions to using `android:launchMode="singleTop"`. By the way, my project is integrating with deep-link, which mentions to using `singleTask` (https://facebook.github.io/react-native/docs/linking.html). I'm curious, is there any side-effect from FCM if I using `singleTask`? Thank you.

**Comment by mcorner** [comment]
One reason why it isn't clear if singleTask or singleTop is the right answer: https://github.com/BranchMetrics/react-native-branch-deep-linking/issues/65

**Comment by evollu** [comment]
looks like singleTask is the one to go even with FCM

**Comment by evollu** [comment]
@mcorner can you change it to singleTask and verify everything runs fine?

**Comment by evollu** [comment]
why do I feel singleInstance the one to go?

**Comment by mcorner** [comment]
singleTask seems to work fine for FCM, but my testing was quick and just in my own app.

**Comment by evollu** [comment]
here is a good explaination
https://blog.mindorks.com/android-activity-launchmode-explained-cbc6cf996802

FCM should be working fine for all mode except standard

**Comment by evollu** [comment]
I've updated readme. @pewh in short, you can use singleTask. reopen if FCM blows up
