### ISSUE TITLE
FIRMessaging.requestPermissions undefined

### ISSUE THREAD

**Issue by OFranke** [evollu/react-native-fcm#5]
Hi,
I'm getting some errors when I included your sample code. What am I missing here?

![screenshot_20160604-142918](https://cloud.githubusercontent.com/assets/12813089/15799569/532ca788-2a61-11e6-999e-04bcea8820a7.png)

**Comment by evollu** [comment]
looks like the native module is not linked properly. Did you do rnpm link? Can you see if native module package is called?

**Comment by OFranke** [comment]
do you mean npm link? is "r" a typo?
If so, I've run it, yes. How can I check if the package is getting called? Do I need to add the package to the package list here?

    @Override
    protected List<ReactPackage> getPackages() {
        return Arrays.<ReactPackage>asList(
            new MainReactPackage(),
            new RNSimpleAlertDialogPackage(),
            new ReactNativeMapboxGLPackage()
        );

**Comment by evollu** [comment]
it is not a typo. https://www.npmjs.com/package/rnpm
install globally and run `rnpm link react-native-fcm`. It will link native code into your android/ios solutions

**Comment by OFranke** [comment]
Got it to work + you teached me that there is such a cool thing like rnpm! thanks a lot! :)

**Comment by evollu** [comment]
👍

**Comment by nasir03082409229** [comment]
'requestPermissions' of undefined I m getting same error , i already link react-native-fcm
