### ISSUE TITLE
Receiving my own notification

### ISSUE THREAD

**Issue by ifalldev** [evollu/react-native-fcm#500]
Hi, thank you for the great package!

Everything is running fine about `subscribeToTopic` and im receiving notification from `fcm`, even on foreground - only iOS.

My trouble is that every time i send a message a notification pop up in the screen. I tried to stop the receiving on foreground but no success.

So, how can i block notifications triggered by my own messages in `FCM.on()` - or somewhere else? I'm already sending the owner in the payload but i couldn't find a function that 'kills' the current notification.

Or, if it is simpler, how could i stop to show notifications in the foreground?

payload:
```
{
  data: { remote: 'true', writerId, category, group },
  notification: { title: 'test', body: `${writerName}: ${message}` }
}
```

**Comment by ifalldev** [comment]
Hello there,

I found a workaround which fixed it.

I changed the validation `if (Platform.OS==='ios')` to `if (Platform.OS==='ios' && writerId !== userId && group !== groupId)`.

`group` and `writedId` i tooke from payload, `userId` and `groupId` are parameters to the action that calls `FCM.on(FCMEvent.Notification)`.

**Comment by shekharskamble** [comment]
@ifalldev - how did you block the code inside FCM.on? were you showing local notification inside FCM.on? can you share some example... thanks...

**Comment by ifalldev** [comment]
@shekharskamble, sorry i dont understood what you want to know. Are you receiving the notification about your own action (eg you send a message and receive a notification about it)?

If is it your trouble, i just did that validation `(Platform.OS==='ios' && writerId !== userId && group !== groupId)`, wich means verify before show the notification if it is my own action. I put metatada (`writerId` and `groupId`) on the notification and used that to validate.

**Comment by shekharskamble** [comment]
@ifalldev - "Are you receiving the notification about your own action (eg you send a message and receive a notification about it)?" YES

"which means verify before show the notification if it is my own action".  
"verify before show the notification" - How did you achieve this?  are you showing local notification upon receiving remote notification in FCM.on?

Is it possible to share the code sample of an entire condition (Platform.OS==='ios' && writerId !== userId && group !== groupId) with showing the notification?

Thank you very much...

**Comment by ifalldev** [comment]
Being honest I did not remember in detail how we solve this issue. But going deeper in the `commits` log I figured out what has happened.

In fact that approach did not fix the problem 100%, we noticed - with time and use - some inconsistence about delivering the notification to the user, so we deactivated the foreground notification to iOS (android fg notification did not work by default, if you want that you need to setup some things in java core).

But if you really need the foreground notification I believe the way is to validate the notification received before dispatch it as local.

```
FCM.on(FCMEvent.Notification, notif => {
      const { category, group, writerId } = notif;

      if (notif.local_notification) return;

      if (notif.opened_from_tray) {
        if (notif.category) {
          firebase.database().ref(`categories/${category}/groups/${group}`).once('value')
            .then(snapshot => {
              Actions.chat({ grupo: snapshot.val(), title: snapshot.val().groupName });
            });
        } else {
          firebase.database().ref(`/groups/${group}`).once('value')
            .then(snapshot => Actions.chat({ grupo: snapshot.val(), title: snapshot.val().groupName }));
        }
        return;
      }

      
      if (Platform.OS === 'ios') {
        switch (notif._notificationType) { //eslint-disable-line
          case NotificationType.Remote:
            notif.finish(RemoteNotificationResult.NewData); 
            break;
         case NotificationType.NotificationResponse:
           notif.finish();
           break;
        case NotificationType.WillPresent:
          notif.finish(WillPresentNotificationResult.All); 
      
          break;
        default:
          break;
       }
    }
});

FCM.on(FCMEvent.RefreshToken, token => {
    dispatch({
      type: TOKEN_UPDATED,
      payload: token
    });
  });
}
```
It means that the secret is to wrap `if (Platform.OS === 'ios') {...}` with some validation logic, or put some validation logic inside it, once that block controls the action about notification. To do that you can use the parameter sent by FCM (on my case we called it `notif` - as you can see it in here: `FCM.on(FCMEvent.Notification, notif => { const { category, group, writerId } = notif; ...}`).

I hope that could help you!

**Comment by shekharskamble** [comment]
Does notif.finish(); prevent notification from showing? if yes then does it only work for iOS? I dont see any documentation for this...

**Comment by ifalldev** [comment]
It was in the `readme` file, [as you can see here](https://github.com/evollu/react-native-fcm/commit/09e9e4a6f883fdef7cd0ac70417f933c58b08194#diff-04c6e90faac2675aa89e2176d2eec7d8L308).

The poor documentation is the hardest part of working with `FCM` ;(

**Comment by ifalldev** [comment]
@shekharskamble, check it out #554

**Comment by shekharskamble** [comment]
@ifalldev - thanks a lot

**Comment by shekharskamble** [comment]
@ifalldev - it seems support for notif.finish is only for iOS and not for android....

**Comment by ifalldev** [comment]
@shekharskamble - yeah only iOS need that custom setup, android build everything by itself.

So, have android side foreground notif? If the answer still is no, you should only setup iOS fg notif, right?

**Comment by evollu** [comment]
@ifalldev @shekharskamble 
some clarification:
1. those notif.finish custom code is optional. if you don't call finish or return anything, the library handles it for you https://github.com/evollu/react-native-fcm/blob/master/index.js#L145
2. calling `finish` tells iOS system that you are done with your background work. it is nice to have because iOS times your background process. But not doing it won't cause your notification not showing.

@ifalldev maintaining the documentation is a pain for me as there are so many edge use cases. Let me know if there is any place that can be improved.
