### ISSUE TITLE
Silent push notification in a closed React Native app

### ISSUE THREAD

**Issue by AlexBlagodaryov** [evollu/react-native-fcm#507]
Have a question about silent push notification in React Native app. 
In our app we send data about an event in push notification. I want to use silent push notification to update data in the app that is closed. Is it possible for the closed app to receive the silent push notification? How to implement it into the React Native code? In other words, how to transfer the silent notification data into the React Native for the closed app? Any instructions, documentations, and links will be great to have.

RN version 0.45.1
content_available is set to true

**Comment by lfallet** [comment]
It seems you need to use remote notification, without showing any local notification to the user.

AFAIK, for simple processing the javascript listener `this.notificationListener = FCM.on(FCMEvent.Notification, ` is enough; for complex operations you can extend `didReceiveRemoteNotification `
When your app receives the remote notif, you can process specific actions in the background (network calls...)

**Comment by karthikpala** [comment]
Is there any update on this. @evollu said [here](https://github.com/evollu/react-native-fcm/issues/435)  that after update to v7.5.1 this is supposed to work, but the code is not calling the callback on FCMEvent.Notification when the app is closed.

**Comment by AlexBlagodaryov** [comment]
I have checked the solution suggested by @lfallet.
I started the following iOS realization for Swift: https://www.raywenderlich.com/156966/push-notifications-tutorial-getting-started

This suggestion did not work. 
When the app is closed, and push notification is received , then any handler does not work. I checked this in the code, by showing local notification.

All the suggested solutions from Stackoverflow end up using didReceiveRemoteNotification with fetchCompletionHandler But it does NOT work as I said earlier.

Guys, if you know what I do incorrectly, or you had the problem as well and can recommend the working example of this problem, I would be grateful for any help, advise or link.

BTW there is a comment from @evollu about the iOs.
https://github.com/evollu/react-native-fcm/issues/435#issuecomment-319081391

**Comment by evollu** [comment]
what OS is not working? It should work for Android and iOS (except when app is killed by user)

**Comment by AlexBlagodaryov** [comment]
Thank you for the comment. 
Handlers are not called on iOS when the app is killed (closed)  by user. There are sources where they say : 
didReceiveRemoteNotification with fetchCompletionHandler should be called but they are not. If it is the normal behavior for the iOS, then is there any documentation  that proves that.

**Comment by evollu** [comment]
https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623013-application
```
However, the system does not automatically launch your app if the user has force-quit it. In that situation, the user must relaunch your app or restart the device before the system attempts to launch your app automatically again.
```

**Comment by AlexBlagodaryov** [comment]
Thank you for your answer and for the link, probably this issue can be closed.

**Comment by Vetalyo** [comment]
@evollu, is this impossible now to start up in background when push arrives ? 
I tried to add `"content_available": true` but it does not helped. 

Also I tried different version of plugin: 8, 9.1.2 and also v7.5.1 as **bhosle-git** advised in this thread
https://github.com/evollu/react-native-fcm/issues/435
and nothing happens after dropped the app from process.
I tested on iOS: 10.33
react-native: 0.47.2

**Comment by evollu** [comment]
@Vetalyo if user drops app from process, then yes, it is impossible. reference
https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623013-application
```
However, the system does not automatically launch your app if the user has force-quit it. In that situation, the user must relaunch your app or restart the device before the system attempts to launch your app automatically again.
```
 If user restarted their phone, app should be waken automatically.

**Comment by Vetalyo** [comment]
**evollu**, thank you!

**Comment by JillevdW** [comment]
This is possible with VOIP notifications; this is a capability you can register for. These notifications can wake the application, even if it has been force quit.
