### ISSUE TITLE
Can I use this with react-native-system-notification?

### ISSUE THREAD

**Issue by peterpme** [evollu/react-native-fcm#51]
Hey,

So after getting everything working last night, I was curious how you get the actual notification to show up. Is that when you use a library like react-native-system-notification?

Did you get any compatibility issues with it since it supports GCM and not FCM?

Thanks again!

**Comment by evollu** [comment]
FCM should create notification for you. there is no need to use another library unless you need something FCM can't do (like adding a media control)

**Comment by evollu** [comment]
if you are wondering why heads up notification doesn't show up, I have opened a ticket to Firebase

**Comment by peterpme** [comment]
Hey, thanks for the quick response! 

Oh ok, so I don't need to use a library like `react-native-system-notification` to get it to show up?

When I sent a push notification from Firebase console, I saw my console.log go through, but nothing happened.

I'm assuming this is the same problem you're having right now, right?

**Comment by evollu** [comment]
you should have a notification icon on the status bar.

**Comment by peterpme** [comment]
Oh ok, makes sense! I do see the notification icon, but I don't see a message.

I'm assuming this is related to the ticket you've created right?

Thanks!

**Comment by evollu** [comment]
right.

**Comment by peterpme** [comment]
Thanks again!
