### ISSUE TITLE
getAPNSToken always returns null except right after registration 

### ISSUE THREAD

**Issue by willlaserlike** [evollu/react-native-fcm#510]
I'm using the RN 46 and react-native-fcm 7.5.1. Everything works for me in terms that I can get the fcmToken and I can send push messages to ios devices withe the fcmToken. But I'm having trouble to get the apns token from this library. 

I have code like this
  FCM.getFCMToken()
    .then((token) => {console.log('token '+token);})
  FCM.getAPNSToken()
    .then((apnstoken) => {console.log('apnstoken  '+apnstoken);})

For the first time app runs and receives user's permissions for notification, the apnstoken is a valid string. Once the app is killed  and restarted, it always gives undefined value for apnstoken.

**Comment by willlaserlike** [comment]
I found out what happened. 
1. [FIRMessagein messaging].APNSToken is supposed to be used for setting the apns token, not reading it. So it's always empty except right after Firebase set it when Firebase gets a new apns token from the system call. To trigger this system call, we need to call [application registerForRemoteNotifications].

2. APNSToken is not a NSString. It's a NSData bytes. And it cannot be converted into a string with NSUTF8StringEncoding. We have to convert it into a hex string and then pass back to javascript side. 
Current code (return null even if it has a NSData value)
`    
resolve([FIRMessaging messaging].APNSToken);
`
Working code (return a hex string)
`
  NSData *apnsTokenData = [FIRMessaging messaging].APNSToken;
  const char *data = [apnsTokenData bytes];
  NSMutableString *token = [NSMutableString string];
  for (NSUInteger i = 0; i < [apnsTokenData length]; i++) {
    [token appendFormat:@"%02.2hhX", data[i]];
  }
   resolve([token copy]);
`

**Comment by evollu** [comment]
fixed
