### ISSUE TITLE
Does the sendToDevice() admin method work ?

### ISSUE THREAD

**Issue by mackenziemance** [evollu/react-native-fcm#514]
does the sendToDevice() method work or can you only send to topics. I'm receiving notifications in the background fine with sendToTopic()

It looks like it's being sent succsessfully but nothing is recived

<img width="728" alt="screen shot 2017-08-17 at 8 05 55 pm" src="https://user-images.githubusercontent.com/24738013/29438878-a1f7c43a-8387-11e7-8707-725ab3f40f3b.png">

**Comment by ShawnYcx** [comment]
Did you figure out what the issue was?
