### ISSUE TITLE
Building Failed on Xcode

### ISSUE THREAD

**Issue by guoliang1206** [evollu/react-native-fcm#516]
Build failed on Xcode

Manual install Firebase SDK

RN Version:0.47.1

![2017-08-21 5 17 03](https://user-images.githubusercontent.com/12846676/29512416-baf08174-8694-11e7-99fd-d7a19c43f13a.png)

**Comment by guoliang1206** [comment]
I have tried install FireBase SDK with cocoapods just now, same error.

**Comment by guoliang1206** [comment]
@evollu is it a problem with header search paths?
![2017-08-21 6 56 17](https://user-images.githubusercontent.com/12846676/29516294-73ecaf6a-86a2-11e7-9ed8-c29716abe6d4.png)

**Comment by yolosaucisson** [comment]
I have the same problem...
Fix please? :(

**Comment by guoliang1206** [comment]
@yolosaucisson  accept update your pod
in your pod file `platform:'9.0'` or higher, 
then execute`pod outdated`
`pod update`
