### ISSUE TITLE
Redirect on specific page when click on notification

### ISSUE THREAD

**Issue by ranashahidbashir** [evollu/react-native-fcm#521]
@evollu is there any why we redirect on a specific page when click on notification from tray??

**Comment by ajayrawat12** [comment]
Yeah , even i am looking for this.

**Comment by evollu** [comment]
you can use "action" attribute, and handle navigation on notification callback

**Comment by evollu** [comment]
is `this.props.navigator.replacePrevious({name:"Settings"});` gets called correctly?

**Comment by ranashahidbashir** [comment]
@evollu  yes its called.

**Comment by evollu** [comment]
try a timeout. Perhaps the navigation doesn't work when app is not fully opened

**Comment by ranashahidbashir** [comment]
@evollu  you mean .i called this line after some time duration e.g 1000 ms ??or some thing else
this.props.navigator.replacePrevious({name:"Settings"});

**Comment by evollu** [comment]
yes.

**Comment by ranashahidbashir** [comment]
ok i will try that.

**Comment by ranashahidbashir** [comment]
Hi @evollu thanks for your help problem are fixed by using the setTimeout function in notification opened_from_tray block. Again thanks


**Sample Code**

`redirect(){ this.props.navigator.push({name:"DetailPage", data:this.state.pageData[1]}); }`

`





`this.notificationListener` = FCM.on(FCMEvent.Notification, notif => {
  console.log("Notification recived", notif);
  if(notif.local_notification){
     console.log("Notification recived local", "local notification");

      if(notif.opened_from_tray){

         console.log("Notification recived local ", "opened from tray");

        setTimeout(() => {

        //    console.log('setting page call!'); 
        console.log('this is props',props);
          this.redirect()
          // this.props.navigator.push({name:"Sports"});
        //  // this.props.navigator.push({name:'DetailPage',data:Data});
        }, 5000);

         //this.props.navigator.push({name:"Settings"});

      }
    
    return;
  }
  if(notif.opened_from_tray){

     console.log("Notification recived tray ", "opened from tray");
     //this.props.navigator.replacePrevious({name:"Settings"});
    return;
  }

  if(Platform.OS ==='ios'){
          //optional
          //iOS requires developers to call completionHandler to end notification process. If you do not call it your background remote notifications could be throttled, to read more about it see the above documentation link.
          //This library handles it for you automatically with default behavior (for remote notification, finish with NoData; for WillPresent, finish depend on "show_in_foreground"). However if you want to return different result, follow the following code to override
          //notif._notificationType is available for iOS platfrom
          switch(notif._notificationType){
            case NotificationType.Remote:
              notif.finish(RemoteNotificationResult.NewData) //other types available: RemoteNotificationResult.NewData, RemoteNotificationResult.ResultFailed
              break;
            case NotificationType.NotificationResponse:
              notif.finish();
              break;
            case NotificationType.WillPresent:
              notif.finish(WillPresentNotificationResult.All) //other types available: WillPresentNotificationResult.None
              break;
          }
  }`

**Comment by Thadeu** [comment]
Using wix/react-native-navigation

```
if (notif.opened_from_tray) {        
        setTimeout(() => {
          this.props.navigator.push({
            screen: 'User.Chat',
            title: 'Perguntar ao vendedor',
            passProps: {
              currentProduct: notif.message.product,
              sender: notif.message.sender,
              recipient: notif.message.recipient
            }
          })
        }, 1000)

        return
      }
```

**Comment by saikiranoptisol** [comment]
where you will write this redirection method. If i write in App.js it will be called only when app launches. it wont call during background/foreground state. how to do that please help me in this scenario
