### ISSUE TITLE
Multiple Lines and Picture

### ISSUE THREAD

**Issue by mykelaballe** [evollu/react-native-fcm#523]
1. Using local push notification, how can i use embedded image assets in push notification? something like this:
```
FCM.presentLocalNotification({
    ...,
    picture: require("path/to/image.png")
})
```

2. How to make push display the body in multiple lines?

![image](https://user-images.githubusercontent.com/22584900/29722239-9baec54e-89f2-11e7-853a-5b5df62e1a77.png)

**Comment by stsiushkevich** [comment]
I need to display body in multiple lines too...

**Comment by stsiushkevich** [comment]
I have found an approach on android: big_text: body

**Comment by evollu** [comment]
1. you can put image in mipmap and do "picture: your_image.png"
2. big_text has been implemented.

**Comment by evollu** [comment]
let me know if it doesn't work

**Comment by sidd123456** [comment]
@evollu no it still coming in single line

**Comment by evollu** [comment]
@sidd123456 you need to pull down the notif to see multiple lines
