### ISSUE TITLE
ios notification not received but sent from api successfully.

### ISSUE THREAD

**Issue by niranjan-b-prajapati** [evollu/react-native-fcm#526]
Hi,

Following are the versions:

react: 16.0.0-alpha.6,
react-native: 0.44.0,
react-native-fcm: ^7.2.0,

I have tested on iphone 6 ios 10.3.2

Following is the code in appdelegate.m:

```
#import "RNFIRMessaging.h"
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [FIRApp configure];
  [[UNUserNotificationCenter currentNotificationCenter] setDelegate:self];
  
  NSURL *jsCodeLocation;

  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];

  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"high_furtados_appv2"
                                               initialProperties:nil
                                                   launchOptions:launchOptions];
  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}

- (void)userNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification withCompletionHandler:(void (^)(UNNotificationPresentationOptions))completionHandler
{
  NSLog(@"willPresentNotification %@",notification);
  [RNFIRMessaging willPresentNotification:notification withCompletionHandler:completionHandler];
}
- (void)userNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void (^)())completionHandler
{
  NSLog(@"didReceiveNotificationResponse %@",response);
  [RNFIRMessaging didReceiveNotificationResponse:response withCompletionHandler:completionHandler];
}

- (void)application:(UIApplication *)application didReceiveRemoteNotification:(nonnull NSDictionary *)userInfo fetchCompletionHandler:(nonnull void (^)(UIBackgroundFetchResult))completionHandler{
    NSLog(@"didReceiveRemoteNotification %@",userInfo);
    [RNFIRMessaging didReceiveRemoteNotification:userInfo fetchCompletionHandler:completionHandler];
}

//You can skip this method if you don't want to use local notification
- (void)application:(UIApplication *)application didReceiveLocalNotification:(UILocalNotification *)notification {
    [RNFIRMessaging didReceiveLocalNotification:notification];
}
```

Following is the code in react-native project:

```
FCM.requestPermissions();
FCM.subscribeToTopic('all');
FCM.getFCMToken().then(token => {
            console.log('getFCMToken :::: ', token);
            // store fcm token in your server
            if (token) {
                global.pushToken = token
            }
            console.log('getFCMToken global.pushToken ::: ', global.pushToken);
 });
this.notificationListener = FCM.on(FCMEvent.Notification, async (notif) => {
            console.log('notificationListener notif ::: ', notif);
            let notificationIos = typeof notif == 'string' ? JSON.parse(notif) : notif;
            let notificationIosBody = {};
            try {
                notificationIosBody = notificationIos.notification.body;
            } catch (e) {
                try {
                    notificationIosBody = notificationIos.aps.alert.body;
                } catch (e) {
                    console.log("Format Error!");
                }
            }

            // there are two parts of notif. notif.notification contains the notification payload, notif.data contains data payload
            if (notif.local_notification) {
                //this is a local notification
            }
            if (notif.opened_from_tray) {
                //app is open/resumed because user clicked banner
                console.log('notificationListener notif.opened_from_tray ::: ', notif);
                if (Platform.OS === 'ios') {
                    if (notificationIosBody) {
                        Alert.alert('Notification', notificationIosBody,
                            [
                                { text: 'OK', onPress: () => { } },
                            ]);
                    }
                }
            }


            if (Platform.OS === 'ios') {
                 if (notificationIosBody) {
                    Alert.alert('Notification', notificationIosBody,
                        [
                            { text: 'OK', onPress: () => { } },
                        ]);
                }
            }
            else if (Platform.OS === 'android') {
                if (notif.fcm.body) {
                    Alert.alert('Notification', notif.fcm.body,
                        [
                            { text: 'OK', onPress: () => { } },
                        ]);
                }
            }
        });
this.refreshTokenListener = FCM.on(FCMEvent.RefreshToken, (token) => {
            console.log('refreshTokenListener ::: ', token);
            // fcm token may not be available on first load, catch it here
            if (token) {
                global.pushToken = token
            }
            console.log('refreshTokenListener global.pushToken ::: ', global.pushToken);
        });
```
I have added all the packages as mentioned in readme file for nonpod configuration.

I am not getting any logs which are added in appdelegate.m file.

The notifications are not getting received in ios only when app is open and also when app is closed or in background.

I have also added following in info.plist:

```
<key>FirebaseAppDelegateProxyEnabled</key>
	<false/>
```

**Comment by guns2410** [comment]
Having same issue

**Comment by luisfuertes** [comment]
[Here](https://github.com/evollu/react-native-fcm/issues/291) @evollu said that FirebaseAppDelegateProxyEnabled must be on YES, can you check it with YES value?

**Comment by niranjan-b-prajapati** [comment]
@luisfuertes Earlier the  FirebaseAppDelegateProxyEnabled entry was not there in info.plist and what i read was by default if the entry is not there the value is YES. At that time also the notifications were not getting received. So i tried by setting it as No as someone suggested on stackoverflow.  @evollu  Can you please help me out with this weird issue.

**Comment by evollu** [comment]
It could be payload being invalid.
Is notification callback getting called?

**Comment by niranjan-b-prajapati** [comment]
@evollu Thanks for replying. We have actually created new project with RN  0.44 as we want to upgrade react-native from 0.34 to 0.44, the old react-native project is still working and the notifications works fine in the old source code on IOS. Its this new project which is having problems in ios, as android notifications are received properly. The backend code is same as the notifications getting triggered on api calls.

**Comment by luisfuertes** [comment]
Im having the same issue to.

With old build of my app with react-native-fcm 6.2.3 it works, i understand all firebase console config its ok.

But yesterday i update react-native-fcm to v7.5.1, did pod update add FirebaseAppDelegateProxyEnabled = NO on plist and now pus donesnt work...

My versions now:
`"react-native-fcm": "7.5.1"`
` "react-native": "0.43.3"` 

Maybe pod update install a firebase-sdk too recent for version 7.5.1 of react-native-fcm?

**Comment by evollu** [comment]
try reregister the device? could FCM token get changed?
I'm using RN 0.44 as well and thing looks fine to be.
Will test with latest firebase SDK later but it shouldn't matter

**Comment by niranjan-b-prajapati** [comment]
@evollu Ok Will try that thing also, But what i did to test was took the push token i received in ios app and went to firebase console and tried to test notification using token, but still the notification was not received but was send successfully from firebase console.

**Comment by evollu** [comment]
BTW, you can update to 9.1.0. It should be compatible with 0.44

**Comment by luisfuertes** [comment]
And with 0.43.3?

**Comment by evollu** [comment]
yes

**Comment by niranjan-b-prajapati** [comment]
@evollu  Ok will try and get back to you on same.

**Comment by luisfuertes** [comment]
Ok im trying with v9.1.0 and did pod update again.

FirebaseAppDelegateProxyEnabled must be setted to YES or NO?

**Comment by evollu** [comment]
keep it YES

**Comment by luisfuertes** [comment]
Not works for me, app fail on firebase console

**Comment by luisfuertes** [comment]
AppDelegate code:
``` 
#import "AppDelegate.h"
#import "RNFIRMessaging.h"

#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  NSURL *jsCodeLocation;

  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];

  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"myapp_app"
                                               initialProperties:nil
                                                   launchOptions:launchOptions];
  
  //AÑADIDO FIREBASE MESSAGING
  [FIRApp configure];
  [[UNUserNotificationCenter currentNotificationCenter] setDelegate:self];
  //FIN FIREBASE MESSAGING
  
  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}

// AÑADIDO FCM
- (void)userNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification withCompletionHandler:(void (^)(UNNotificationPresentationOptions))completionHandler
{
     [RNFIRMessaging willPresentNotification:notification withCompletionHandler:completionHandler];
}

- (void)userNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void (^)())completionHandler
{
  [RNFIRMessaging didReceiveNotificationResponse:response withCompletionHandler:completionHandler];
}

 //You can skip this method if you don't want to use local notification
 -(void)application:(UIApplication *)application didReceiveLocalNotification:(UILocalNotification *)notification {
  [RNFIRMessaging didReceiveLocalNotification:notification];
}

- (void)application:(UIApplication *)application didReceiveRemoteNotification:(nonnull NSDictionary *)userInfo fetchCompletionHandler:(nonnull void (^)(UIBackgroundFetchResult))completionHandler{
  [RNFIRMessaging didReceiveRemoteNotification:userInfo fetchCompletionHandler:completionHandler];
}
// FIN FCM

@end
``` 

plist
``` 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>es</string>
	<key>CFBundleDisplayName</key>
	<string>MyApp</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>$(PRODUCT_NAME)</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>1.0.9</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>com.mycompany.myapp</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>com.mycompany.myapp</string>
			</array>
		</dict>
	</array>
	<key>CFBundleVersion</key>
	<string>109</string>
	<key>FirebaseAppDelegateProxyEnabled</key>
	<true/>
	<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>whatsapp</string>
	</array>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
	</dict>
	<key>NSCameraUsageDescription</key>
	<string>¿Da permiso para acceder a la cámara?</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string></string>
	<key>NSPhotoLibraryAddUsageDescription</key>
	<string>¿Da permiso para almacenar el vídeo en el carrete?</string>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>¿Da permiso para acceder al carrete?</string>
	<key>UIAppFonts</key>
	<array>
		<string>Entypo.ttf</string>
		<string>EvilIcons.ttf</string>
		<string>FontAwesome.ttf</string>
		<string>Foundation.ttf</string>
		<string>Ionicons.ttf</string>
		<string>MaterialCommunityIcons.ttf</string>
		<string>MaterialIcons.ttf</string>
		<string>Octicons.ttf</string>
		<string>SimpleLineIcons.ttf</string>
		<string>Zocial.ttf</string>
	</array>
	<key>UIBackgroundModes</key>
	<array>
		<string>remote-notification</string>
	</array>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIRequiredDeviceCapabilities</key>
	<array>
		<string>armv7</string>
	</array>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
	</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<true/>
</dict>
</plist>
```

**Comment by evollu** [comment]
I think `fails` means firebase failed to push, rather than the device failed to handle

**Comment by luisfuertes** [comment]
Ye but yesterday all works, dont know why fail now, i will try now with old build of my app with v6.2.3. Same firebase console config. I think it works

**Comment by luisfuertes** [comment]
Yes, it works with old build, same firebase console config :(
![captura de pantalla 2017-08-29 a las 12 48 28](https://user-images.githubusercontent.com/18212615/29817498-84900e68-8cb8-11e7-8617-20903e2aa0df.png)

**Comment by luisfuertes** [comment]
Ok now im trying on iPad.

In firebase console push set as sent, but dont received it on iPad
![captura de pantalla 2017-08-29 a las 12 55 41](https://user-images.githubusercontent.com/18212615/29817747-79c37d48-8cb9-11e7-880b-d1380b164033.png)

**Comment by evollu** [comment]
let me verify on my device

**Comment by luisfuertes** [comment]
I delete ios Pods folder and Podfile, reinstall pods and now all notif fail on firebaseconsole , but project compile and device give FCM token

**Comment by evollu** [comment]
so it has to do with FCM SDK?

**Comment by luisfuertes** [comment]
who knows

**Comment by luisfuertes** [comment]
I delete all pods config, generate new app certificates and install 9.1 and now all works fine... 

Old build only works with old certificate, and new app with new certificate, the bundle id is the same and dont know why it happening.

Thanks for support @evollu

**Comment by evollu** [comment]
certificate you mean the json object download from firebase console right?

**Comment by evollu** [comment]
@niranjan-b-prajapati let me know if @luisfuertes 's finding works for you

**Comment by luisfuertes** [comment]
Not, certificate the .p12 file, ios push certificate. Dont know why the old certificate doesnt works with news builds

**Comment by niranjan-b-prajapati** [comment]
@evollu sorry yesterday couldn't work on it as there was no electricity i will try it now, @luisfuertes New certificates means ? only apns ceritifcate or ?development, distribution certificate also from apple developer console ? Please enlighten me on the certificate thing till then will update reac-native-fcm to 9.1.0

**Comment by luisfuertes** [comment]
I update push dev and push prod p12 certificate, re init pod with FirebaseMessaging and install react-native-fcm 9.1.0 with same config and all works ok now

**Comment by niranjan-b-prajapati** [comment]
the ios certificate on firebase console what we add .p12 file is exported from apns certificate installed on our system. So do we need to create new apns certificate and change that ? Also there is some keys section available in developer apple console should we use that ? And will changing new apns keys will affect the existing users who are using apps on old source code as they will be getting updates soon of new app build with new react-native source codes. @evollu  @luisfuertes  please put some light on this.

**Comment by evollu** [comment]
if it is .12 related, it shouldn't affect existing user. it is more of Firebase-iOS communication getting impacted

**Comment by niranjan-b-prajapati** [comment]
so if i create key instead of apns certificate and use in app it will not affect existing users ? Can you please explain " it is more of Firebase-APNS communication getting impacted" thing.

**Comment by evollu** [comment]
hmm..forget about it. Perhaps you need to test that.

**Comment by niranjan-b-prajapati** [comment]
Ok I am using firebase 4.0.4 sdk files do i need to update them to latest version available ?

**Comment by jaysig** [comment]
Any updates on this? I have followed all of the instructions, but I can never get a notification to appear. It does send from the API though.

**Comment by olieidel** [comment]
Here are my findings so far:
iOS 10.3.3, RN 0.46.4
- When sending a push notification, FCM HTTP API return `success`
- Sending from the Firebase web interface also return success
- No notification callback is called on client
- Most likely, the message never arrives on the client
- Resetting APN key or .p12 certificates in Firebase doesn't help

My best guess would be that there is a server-side problem between the Firebase and APN servers. 

This may be related: https://github.com/firebase/quickstart-ios/issues/273

**Comment by olieidel** [comment]
Quick Update:
I implemented React Natives PushNotificationIOS for my app and it has the same problem! I am getting a token but not receiving any messages. Even weirder, my older version with firebase (in production) works - but not in development. I suspect it is some certificate-related issue and has nothing to do with this package.

**Comment by natashache** [comment]
I'm having the similar issue. I'm able to get device token from my app. Sending messages from both node.js backend and from firebase notifications console indicates that message has been sent successfully. But it doesn't show up on the mobile app. App capacities, etc have been configured exactly as in the readme of react-native-fcm. 

And the strange part is that it was working yesterday. But not today. And I haven't changed anything in the app. So frustrated right now!

**Comment by olieidel** [comment]
@natashache this really does sound like a backend problem on the side of Apple. I just reverted to a commit in my project which worked yesterday and it doesn't work any more!
I hope this is one of those problems which fix themselves over night..

**Comment by natashache** [comment]
@olieidel will let you know if it fixes itself. Though I'm getting messages from other apps with no problem. If someone has insight on this, please share.

**Comment by olieidel** [comment]
**Relevant discussions:**
Apple Developer Forums thread:
- https://forums.developer.apple.com/thread/86282

Stackoverflow questions in the last 24hrs:
- https://stackoverflow.com/questions/46027717/development-push-notifications-suddenly-stop-working-but-test-flight-push-notif
- https://stackoverflow.com/questions/46023739/push-notification-sandbox-stopped-working

**Comment by vrgimael** [comment]
I had the some problem but this morning I received all my delayed test notifications together (they had the correct timestamp though) and now notifications seem to be working fine again

**Comment by natashache** [comment]
Just tried again. Still not receiving messages :(

**Comment by olieidel** [comment]
@natashache it's working for me again, too. I filed a bug report with Apple and 2 hours later it was resolved (probably unrelated though, haha).

**Comment by natashache** [comment]
I have followed this guide to debug https://firebase.googleblog.com/2017/01/debugging-firebase-cloud-messaging-on.html. I made a curl call directly through APNs and the notification showed up on my phone with no problem. 

But when I made a curl call through FCM, I was not able to get the message on phone, though the response from firebase said the message has been sent and I didn't get any error messages. 
{"multicast_id":5824867483593933267,"success":1,"failure":0,"canonical_ids":0,"results":[{"message_id":"0:1504535298633785%0007825f0007825f"}]}

I again tried sending messages via firebase notification console. Still no dice. But the console says message has been sent successfully.

**Comment by evollu** [comment]
can you verify that p12 file is correct?
also can you show your payload? invalid payload will result notification not showing

**Comment by natashache** [comment]
@evollu I'm using APNs authentication key, not p12 file. 

The curl command:
```
curl --header "Content-Type: application/json" \
--header "Authorization: key=AU...the rest of your server key...s38txvmxME-W1N4" \
https://fcm.googleapis.com/fcm/send \
-d '{"notification": {"body": "Hello from curl via FCM!", "sound": "default"},
"priority": "high",
"to": "gJHcrfzW2Y:APA91...the rest of your FCM token...-JgS70Jm"}'
```
As you can see the payload is nothing special.

Also tried sending with notification console. 

It was working two days ago and then stopped working. Haven't changed a thing.

**Comment by evollu** [comment]
try include a title?
.p12 file is used by FCM so try upload that file in firebase console again?

**Comment by MrPeproni** [comment]
@niranjan-b-prajapati I am getting `Failed to grant permission` with request permission. Did you manage to do that? If yes, please let me know how.

Thanks

**Comment by niranjan-b-prajapati** [comment]
@MrPeproni i never got that kind of issue. Sorry @evollu couldn't reply on the issue as i was assigned some other issues to fix first. I am yet to implement and check whatever solutions given above will try setup in new blank project and check with fresh certificate and keys. As still the notifications are not getting received on react-upgraded build but working fluently on old setup. Thanks @olieidel  @natashache @luisfuertes @jaysig @vrgimael for reporting this issue atleast came to know many people are facing the issue on latest source while old ones are working perfectly.

**Comment by niranjan-b-prajapati** [comment]
@evollu I have created new react-native project with same version as above 0.44.0 and set up fcm only for ios using apns key instead of certificate and tested using the fcm console for single device by using the fcm token received in app and logged the notification json data in notificationListener function. I have successfully received the notification json data in the newly created project.

But when i tried sending notification to single device using fcm token received in the above mentioned react-native upgraded project where i am getting issue of notification not getting received, i have not received any notification.

Is this happening due to apns certificate? Main thing i am wondering is why it is happening as the same fcm project with same apns certificate and all settings is working fine in my old react-native project on version 0.34 and same thing doesn't work on 0.44 where whole code is updated. 

Request you to assist me as we have created separate bundle id for testing environment and production, and very much afraid to change apns certificate, as if i change apns certificate in testing environment then will have to change same in production environment, how can i solve the issue without changing the apns certificate.

**Comment by evollu** [comment]
did you update firebase SDK?

**Comment by niranjan-b-prajapati** [comment]
used same 4.1.0 in both latest test project where notification working and the upgraded project in which i am facing issue.

**Comment by evollu** [comment]
can you ask Firebase team if they know anything about it?

**Comment by niranjan-b-prajapati** [comment]
Ok can you point me in right direction how can i contact them ?

**Comment by evollu** [comment]
https://firebase.google.com/support/

**Comment by niranjan-b-prajapati** [comment]
@evollu Following is the response from the firebase:

Firebase does not officially support react-native yet. Based on the cause of the issue, it seems that you experienced it after upgrading your react-native to a newer version. I suggest that you ask the issue in developer communities like StackOverflow or in the link you've provided as it's currently outside of our scope of support. However, if you could replicate the issue using the native languages (Objective-C/Swift, Android/Java), please let me know and I'd be happy to assist here.

very much worried what to do now in these scenario.

**Comment by niranjan-b-prajapati** [comment]
I tried deleting app and running again and checked using fcm console single device using fcm token received in app, Also i tried by removing the fcm sdk and adding it again to check if this might solve issue, but all in vain. notification send from console but not receive in app.

**Comment by evollu** [comment]
@niranjan-b-prajapati your finding means the notification has never made to your phone so it is not caused by react native or this lib. 
Deleting the app and reinstalling will give the device a new FCM token. are you using the new token?
if so, it means your token from SDK 4.1.0 doesn't work with the console. What I would do is downgrade to SDK 4.0.4 and check if it will work again.

**Comment by paomosca** [comment]
hey @evollu i falling in the same exact situation, i tried the curl call directly to apns and it works, then i tried the curl by firebase and the results is 

{"multicast_id":5351961100343884262,"success":1,"failure":0,"canonical_ids":0,"results":[{"message_id":"0:1506010515803885%bd25912cbd25912c"}]}%   

but no message on device:

the version of firebase pod i'm using is:

Using Firebase (4.2.0)
Using FirebaseAnalytics (4.0.3)
Using FirebaseCore (4.0.7)
Using FirebaseInstanceID (2.0.3)
Using FirebaseMessaging (2.0.3)
Using GoogleToolboxForMac (2.1.1)
Using Protobuf (3.4.0)
Using nanopb (0.3.8)

any hints? how to downgrade to 4.0.4?

**Comment by natashache** [comment]
@paomosca do you have 
```
<key>FirebaseAppDelegateProxyEnabled</key>
<true/>
```
in your `info.plist`? I had the same problem and that was what solved it for me.

**Comment by paomosca** [comment]
@natashache i tried with true and false values, but nothing changed. 
i even tried to delete and create p12 certs and p8 keys too, but nothing.

(RN version 0.47.2 & react-native-fcm 9.1.0, but also i have the same problem with 9.3.0)

**Comment by evollu** [comment]
@paomosca what's your payload to firebase?

**Comment by paomosca** [comment]
`curl --header "Content-Type: application/json" \
--header "Authorization: key=SERVER_KEY" \
https://fcm.googleapis.com/fcm/send \
-d '{"notification": {"body": "Hello from curl via FCM", "title":"test", "sound": "default"},
"priority": "high",
"to": "FCM_DEVICE_TOKEN"}'`

very basic

**Comment by evollu** [comment]
@paomosca payload looks right. try uninstall the app and get a new FCM token? is remoteNotification method in AppDelegate.m getting called at all?

**Comment by paomosca** [comment]
i already tried several times. the remotenotification method never fires. 
i just tried to use 4.0.4 version of the Firebase SDK and is not working either. 

I thought was a bug of firebase system, maybe related to ios 11 update, but if you can make it work, this is not possible.

**Comment by evollu** [comment]
could be...can you try ios 10 then? I haven't tried 10

**Comment by paomosca** [comment]
ok i've some news. today i created a clean project with new bundle id, new certs and new app on Firebase,
using: 
"react-native": "0.48.3",
"react-native-fcm": "^9.3.0"

i can handle correctly push notifications. 

the project i was testing yesterday was using also the firebase sdk module
"firebase": "^4.3.1" to access firebase database & auth capabilities 

it is possible this is generating some conflicts?

**Comment by evollu** [comment]
@paomosca so you say you used same firebase SDK, but new project just works?
there shouldn't be any conflicts between react-native-fcm and react-native
not sure about react-native vs firebase SDK but not likely

**Comment by paomosca** [comment]
@evollu i'm getting crazy, because i linked "firebase": "^4.4.0" on the working project, and it still working. 
then i changed all the libs on the "not working" project, and i changed the bundle id to be the same of the working one.... but... still not working....

is a really weird situation... i'm thinking to move my code from not working to working project... but it will require some time... i'll let you know if i can make it works.

**Comment by paomosca** [comment]
@evollu 
ok i found a step to reproduce the failure 100%. 

use "react-native": "0.48.3" (but also with 0.47.*)
"react-native-fcm": "^9.3.0"

run your example: simple-fcm-client

it will work with all the examples 
now npm i -S firebase it will install "firebase": "^4.4.0"

clean and reinstall.

the project won't send the push anymore (in log you can see the sending from client correctly but not the received).

tested on iphone 5s ios 10.2

i hope it will help to investigate where is the problem, now i'm pretty sure there is some conflict between react-native-fcm and firebase SDK

**Comment by evollu** [comment]
wait. why are you installing javascript sdk?
you should be using iOS and Android SDK

**Comment by paomosca** [comment]
i had a working app using firebase (js sdk) for database & react-native-fcm for push, it was working correctly until the last month, when it stopped without any change. 
i'm using firebase js sdk because is way simpler to use than integrating native SDKs on both platform.

**Comment by evollu** [comment]
@paomosca This repo doesn't call any firebase JS library method and isn't designed to work with JS library.

I looked at the firebase js sdk implementation and it is hooking on registration and message callback as well. so there might be a conflict both sdk trying to handle it. possible 2 fcm tokens are issued? did you call any js sdk messaging method?

anyway, if you want to send simple notification which firebase SDK provides, you can just use that SDK. If you want complex feature, perhaps you need to find a way to have this 2 sdk work together. perhaps ask https://github.com/firebase/firebase-js-sdk what did they do in v4.4.0?

**Comment by nielskrijger** [comment]
Had the same issues as described above; receiving no notifications. Took me more than a day without getting anywhere.

Eventually downloaded the example project and it worked; with the same .p8 key file and same project ID on firebase.

After looking through the differences, as it turned out, in my main project the Podfile.lock was not included. When I copied the Podfile.lock from the example project into my main project it worked.

I think it has to do something with the FirebaseInstanceId peerdependency.

Just to analyze the issue I fixed the Pods to their respective versions in Podfile and removed the Podfile.lock again:

```
pod 'Mixpanel', '~> 3.2'
pod 'Firebase/Core', '4.0.0'
```

which generated the following Podfile.lock:

```
PODS:
  - Firebase/Core (4.0.0):
    - FirebaseAnalytics (= 4.0.0)
    - FirebaseCore (= 4.0.0)
  - Firebase/Messaging (4.0.0):
    - Firebase/Core
    - FirebaseMessaging (= 2.0.0)
  - FirebaseAnalytics (4.0.0):
    - FirebaseCore (~> 4.0)
    - FirebaseInstanceID (~> 2.0)
    - GoogleToolboxForMac/NSData+zlib (~> 2.1)
  - FirebaseCore (4.0.0):
    - GoogleToolboxForMac/NSData+zlib (~> 2.1)
  - FirebaseInstanceID (2.0.3)
  - FirebaseMessaging (2.0.0):
    - FirebaseAnalytics (~> 4.0)
    - FirebaseCore (~> 4.0)
    - FirebaseInstanceID (~> 2.0)
    - GoogleToolboxForMac/Logger (~> 2.1)
    - Protobuf (~> 3.1)
  - GoogleToolboxForMac/Defines (2.1.1)
  - GoogleToolboxForMac/Logger (2.1.1):
    - GoogleToolboxForMac/Defines (= 2.1.1)
  - GoogleToolboxForMac/NSData+zlib (2.1.1):
    - GoogleToolboxForMac/Defines (= 2.1.1)
```

Now notifications no longer worked!

Whereas the example projects shows:

```
PODS:
  - Firebase/Core (4.0.0):
    - FirebaseAnalytics (= 4.0.0)
    - FirebaseCore (= 4.0.0)
  - Firebase/Messaging (4.0.0):
    - Firebase/Core
    - FirebaseMessaging (= 2.0.0)
  - FirebaseAnalytics (4.0.0):
    - FirebaseCore (~> 4.0)
    - FirebaseInstanceID (~> 2.0)
    - GoogleToolboxForMac/NSData+zlib (~> 2.1)
  - FirebaseCore (4.0.0):
    - GoogleToolboxForMac/NSData+zlib (~> 2.1)
  - FirebaseInstanceID (2.0.0):
    - FirebaseCore (~> 4.0)
  - FirebaseMessaging (2.0.0):
    - FirebaseAnalytics (~> 4.0)
    - FirebaseCore (~> 4.0)
    - FirebaseInstanceID (~> 2.0)
    - GoogleToolboxForMac/Logger (~> 2.1)
    - Protobuf (~> 3.1)
  - GoogleToolboxForMac/Defines (2.1.1)
  - GoogleToolboxForMac/Logger (2.1.1):
    - GoogleToolboxForMac/Defines (= 2.1.1)
  - GoogleToolboxForMac/NSData+zlib (2.1.1):
    - GoogleToolboxForMac/Defines (= 2.1.1)
  - Mixpanel (3.2.1)
  - Protobuf (3.4.0)
```

The only difference I see are the following lines:

```
  - FirebaseInstanceID (2.0.0):
    - FirebaseCore (~> 4.0)
```

If that is included it works for me. FirebaseInstanceID 2.0.3 wouldn't work whatever I did.

**Comment by evollu** [comment]
there is a known FCM bug for FirebaseInstanceID 2.0.1-2.0.3. lock pod version to 2.0.0 for now

**Comment by fredbt** [comment]
Is this fixed now? We're having a similar issue here, which does not seem to be fixed by locking FirebaseInstanceID to 2.0.0: we get the token for IOS, etc, but never gets notifications that our server sends to FCM. After we go to the Firebase console and send one notification to this specific token, then all the other messages that we had sent before get somehow "flushed" in a single batch.

So, it seems like that sending one message from the firebase triggers the release of other messages.

LMK if I should open a new issue for this.

**Comment by evollu** [comment]
sounds like a question for firebase team.

**Comment by MrPeproni** [comment]
Guys!

Notifications are working on both platform for me. I have fixed it earlier but didn't update here. Just got comment's notification of this issue and checked many of the users are getting issue with this package.

**Comment by ducpt2** [comment]
+ 1 same issue. I try using onesignal to push notification and it work. May be you right @evollu , can you update the news here, when the issue is end?

**Comment by philjoseph** [comment]
I am using react-native-fcm and the firebase JS SDK 3.9.0 and have a similar issue
- my iOS app register a new token (after reinstalling)
- First notifications goes through ok.
- Second notification got this error in the FCM response `"error":{"code":"messaging/invalid-registration-token","message":"Invalid registration token provided. Make sure it matches the registration token the client app receives from registering with FCM."}`
- Third and further notifications will get this error in the FCM response: `"error":{"code":"messaging/registration-token-not-registered","message":"The provided registration token is not registered. A previously valid registration token can be unregistered for a variety of reasons. See the error documentation for more details. Remove this registration token and stop using it to send messages."`

It seems like there is a refresh token event I do not catch but I do have a listener: 

    const refreshTokenListener = FCM.on(FCMEvent.RefreshToken, (token) => {
        // fcm token may not be available on first load, catch it here
        registerFCMToken(token);
    });

Any idea why my token is loosing its correctness and how I could catch the refresh event? Note that is was working perfectly few weeks ago

**Comment by evollu** [comment]
@philjoseph introduced a fix in v13.1.0 which will delay FCMEvent.RefreshToken event to be handled by JS.
To be safe, you can store users fcm token locally and compare with getFCMToken() every time user launches the app

**Comment by philjoseph** [comment]
@evollu I've tried to upgrade to 13.1.0 and hit #790.

**Comment by nsuryanarayanareddyn** [comment]
any solution for this issue ???

**Comment by gotozainishaikh** [comment]
@natashache  thanks for your advice my issue resolved.

**Comment by gotozainishaikh** [comment]
> @paomosca do you have
> 
> ```
> <key>FirebaseAppDelegateProxyEnabled</key>
> <true/>
> ```
> 
> in your `info.plist`? I had the same problem and that was what solved it for me.
thanks for your advice
