### ISSUE TITLE
Prevent banner from display

### ISSUE THREAD

**Issue by vvusts** [evollu/react-native-fcm#527]
Is it possible to avoid showing notification banner if app is in foreground?
I am trying to show Alert dialog instead notification banner when app is in foreground.

```
FCM.scheduleLocalNotification({
      fire_date: ...,
      id: ...,
      body: ...,
      show_in_foreground: false
  })
```

show_in_foreground - doesn't change anything.
I actually use AppState to check in 'FCM.on' if app is in foreground.
But in this case I want just to show Alert not both.
Any idea about this?

**Comment by evollu** [comment]
what OS are you referring to?

**Comment by vvusts** [comment]
iOS and Android.
I would like to avoid timers.
And scheduled notification is great place I just need option to get notification but don't show banner.

**Comment by evollu** [comment]
it shouldn't. let me try to reproduce

**Comment by evollu** [comment]
I tried following and the banner doesn't show up in android
```
FCM.scheduleLocalNotification({
      id: 'test',
      fire_date: new Date().getTime() + 5000,
      title: 'test',
      body: 'test'
    });
```

**Comment by vvusts** [comment]
I am testing on IOS for now. But just to confirm that you understand what I want.
You don't get banner, but this function is fired 
`FCM.on(FCMEvent.Notification, async (notif) => {`
So I can show alert from it?

**Comment by evollu** [comment]
yes. it should be the case.

**Comment by vvusts** [comment]
Ok I will test android now.
But on IOS I get in that function I check if app is in foreground I I display Alert.alert('', '') 
But I get and alert and notification banner at the top of the screen.
I am using v7.5.1 on RN 44.3

**Comment by vvusts** [comment]
On android it work as expected.
But on iPhone I am getting banner on top.

**Comment by evollu** [comment]
In readme you will see
```
case NotificationType.WillPresent:
                  notif.finish(WillPresentNotificationResult.All) //other types available: WillPresentNotificationResult.None
                  break;
```

finish with  WillPresentNotificationResult.None

**Comment by vvusts** [comment]
Yes, that solve the issue. Thanks :)
