### ISSUE TITLE
FCM.getAPNSToken  return empty string

### ISSUE THREAD

**Issue by perlo27** [evollu/react-native-fcm#528]
Hi! i'm using
 "react-native-fcm": "^9.1.0"
 "react-native": "^0.44.2"
 IOS 10 devise, all needed Capabilities in xCode are turend On, certs are ok.
My AppDelegate.h, AppDelegate.m looks exactly the same as in this repo example folder,
in code  

FCM.getAPNSToken().then(token => {
      console.log("APNS TOKEN (getFCMToken)", token);
    });

token value is empty string.

also

FCM.on(FCMEvent.RefreshToken, token => {
      console.log("TOKEN (refreshUnsubscribe)", token);
      //this.props.onChangeToken(token);
    });

seems that event does not fire at all. (no console log message in 2 minutes)

any guess?
thanks

**Comment by evollu** [comment]
have you called request permission?
what does FCM.getFCMToken() return?

**Comment by perlo27** [comment]
Yeah,  FCM.requestPermissions() is called in componentDidMount() at first.
FCM.getFCMToken() returns token like : d_9n5jIwY6A:APA91bFjqEaceW9-ZLuGNLcyr4pzbwpjuWi1vkn428OzIdnA_9uwcyVWxEvzp-0GKZIE-6KyL1e_y9JQd22XImBF6T9rU6cYZ67GTj0WXct-yp_u4bIMGfkzBcDPtEwZUvasr0VdyQHx

**Comment by perlo27** [comment]
is any additional information i can provide to help?

**Comment by evollu** [comment]
I'm getting null from [[FIRMessaging messaging] APNSToken] as well.
@tjlian616 do you have any idea?

**Comment by perlo27** [comment]
Ok, the problem was FCM.getAPNSToken() runs right after FCM.requestPermissions(), so aplication didn't get permissions for push notifications when method runs. Changing 
componentDidMount -> async componentDidMount
and  FCM.requestPermissions(); -> await FCM.requestPermissions();
solved problem for me

**Comment by evollu** [comment]
ah.. ok
closing this then

**Comment by TaraSinghDanu** [comment]
@evollu  I am getting this as apnsToken D5EF82146C37BF3B0C8CAD157172B802E86EF585B7D06CF8F09D5C7D09FA9AC9
