### ISSUE TITLE
Url as icon in android app

### ISSUE THREAD

**Issue by jjdp** [evollu/react-native-fcm#529]
Can you catch the remote notif in the android fcm source code and not display it, is there something like that in the fcm library? I'd like to build a local notif instead of remote so I can show a url instead of the app icon. 

Currently just using local notifs but when the app is killed, it's kinda sad just showing the icon from the drawable.
Would be great for messaging apps. Any help would be welcome. @evollu

**Comment by evollu** [comment]
you can use "custom_notification"

**Comment by jjdp** [comment]
custom notification works when app is killed?

**Comment by jjdp** [comment]
im getting this on logging but no "custom_notifications is called even on foreground" 

![a](https://user-images.githubusercontent.com/5244520/29820209-59fba980-8cf6-11e7-90c6-91363b33f906.png)

**Comment by evollu** [comment]
can you debug native Android? You can add break point in MessagingService.java to see if `buildLocalNotification` is called correctly

**Comment by jjdp** [comment]
will do. is the local notif implementation device agnostic, not working on my zenfone 5? ill debug on geny/android emulator tomorrow.

**Comment by evollu** [comment]
should be.

**Comment by jjdp** [comment]
this is weird. this gives me null

```
Map<String, String> data = remoteMessage.getData();
String customNotification = data.get("custom_notification");
```

yet i set it on my payload

**Comment by jjdp** [comment]
oh the keys in the data map in mine is `push_id, data, and time` so that's why it can't find the "custom_notification".

does `getData()` return only the objects(custom_notification, etc2.) usually ?

**Comment by evollu** [comment]
I use `https://fcm.googleapis.com/fcm/send` endpoint and this is my whole payload that works.
```
{
"to":"cj8QQNbvZm8:APA91bGZNRcQIi68jZSxTYsobPSCW4EcFBCULI-NzUco1cjXnw5oBA4qRPZZtZYVviZwF6-LqudhPakLOUczG6p1L9xlgu7fA2pSE-P-D_jbjn6RiUZrWwkyL7xdFzxSRBlOgTNaW4xu",
"content_available":true,
"data":{
  "custom_notification": {
      "title": "title", "body":"aaa", "icon":"ic_notif", "sound": "default"
   }
}
}
```

If you are using Firebase console, try make custom_notification as JSON string. perhaps the console filters out non-string values?

**Comment by jjdp** [comment]
ah it's because the way our server constructs the payload. should we perhaps add a recursive search for "custom_notification"? not sure if that's ideal. opinions?

see this line if you want [parse-server-push-adapter](https://github.com/parse-server-modules/parse-server-push-adapter/blob/master/src/GCM.js#L129)

**Comment by evollu** [comment]
I don't get you `recursive search for "custom_notification"`

**Comment by jjdp** [comment]
nvm. it's better to follow the standard format
