### ISSUE TITLE
How to get Remote Notifications with Image ?

### ISSUE THREAD

**Issue by nilaybrahmbhatt** [evollu/react-native-fcm#532]
I'm not checking this repo every day since it is fairly stable now. If you have found a bug or need immediate attention please [AT]me

Please include following information for better support

What version of RN and react-native-fcm are you running?
What device are you using? (e.g iOS9 emulator, Android 6 device)?
Is your app running in foreground, background or not running?

Advanced:
Have you tried adding break point in native handlers to see if message gets delivered?
can share a project with issue?

**Comment by evollu** [comment]
if you mean showing images in android notification, there is a field `big_picture`. it is in readme
