### ISSUE TITLE
How can i get Remote Notification with image ??

### ISSUE THREAD

**Issue by nilaybrahmbhatt** [evollu/react-native-fcm#533]
Working on,
I want to get a notification sent from firebase console with an image.
i successfully get simple text notifications.

Like 
https://i0.wp.com/androidbash.com/wp-content/uploads/2016/08/PushNotifyResult3.gif?resize=437%2C679

RN  - 0.47.1
React-native-fcm - 8.0

**Comment by evollu** [comment]
use `custom_notification` and set `picture` in it

**Comment by nilaybrahmbhatt** [comment]
I passed customer notification like this 

```
var message = {
          registration_ids: tokens,
          notification: {
              title: 'Your Order Status Changed ',
              body: 'Your Delfoo Order Status has been changed',
              
          },
          data: {
            custom_notification: JSON.stringify({
              body: 'Message body',
              title: 'Message title',
              priority:"high",
              icon:"ic_notif",
              title: "test title",
              color:"#00ACD4",
              big_picture:'https://image.path.com/data/apps/app-home2.png',
              picture:'https://image.path.com/data/apps/app-home2.png',
              image:'https://image.path.com/data/apps/app-home2.png',
              show_in_foreground: true
            })
          }
        }
```
i also tried to pass withour json stringify

**Comment by evollu** [comment]
`custom_notification` can't be used together with `notification`

**Comment by nilaybrahmbhatt** [comment]
then how can i use it? please provide an example to understand

**Comment by evollu** [comment]
```
var message = {
          registration_ids: tokens,
          data: {
            custom_notification: JSON.stringify({
              body: 'Message body',
              title: 'Message title',
              priority:"high",
              icon:"ic_notif",
              title: "test title",
              color:"#00ACD4",
              big_picture:'https://image.path.com/data/apps/app-home2.png',
              picture:'https://image.path.com/data/apps/app-home2.png',
              image:'https://image.path.com/data/apps/app-home2.png',
              show_in_foreground: true
            })
          }
        }
```
You can't share the same payload as iOS anymore though

**Comment by wwwdata** [comment]
@evollu this solution is working fine for me. However, I only see the picture when I expand the notification. Is it also possible to display the image in the smaller notification view that is not expanded? Like in this screenshot here: 
![screen shot 2017-11-22 at 16 49 55](https://user-images.githubusercontent.com/818880/33136515-b2ccc8e0-cfa5-11e7-9f43-c0b6b1f5ba6d.png)

**Comment by wwwdata** [comment]
I found out that you can just set the `large_icon` to an image url, than it displays like the hangouts screenshot with an image to the right side. Exactly what I wanted :)

**Comment by Ethan0007** [comment]
@evollu just want to ask on how can i implement using .net? I'm following your object structure before sending it to fcm but i get nothing in notifications.
