### ISSUE TITLE
How to get all push notification ? (question)

### ISSUE THREAD

**Issue by kholiavko-roman** [evollu/react-native-fcm#534]
How to get all push notification ?
I need this option because I find a problem, for example I have 4 unreaded push notification with extra data in each of it. I clicked on one of it (on second for exaple), my app is opened I wrote to some state it, and I see on screen only this message (second), but another third I can`t see. 
How to get all unreaded push notification? Is it possible ? Because I found only method to clear all push notification: `FCM.removeAllDeliveredNotifications()`

`this.notificationListener = FCM.on(FCMEvent.Notification, async (notif) => { 
// save 'notif' to state 
});
`

**Comment by evollu** [comment]
there is no method for getting unread notification as far as I know.
One solution might be saving the notification into a local db when it arrives.
What is your use case?

**Comment by kholiavko-roman** [comment]
> One solution might be saving the notification into a local db when it arrives.
Can you tell me, please, how to save it in local db when message arrives ?

I make some little chat with customers in my app, and on push notification I read extra data from it, save to state and render it. And

**Comment by kholiavko-roman** [comment]
As I know I can execute code only when user tap on notificaton, how to save it to db, I don`t know

**Comment by evollu** [comment]
the JS on('notification') callback should be executed when notification arrives even when app is closed (there is an exception in iOS though so it is not quite reliable)

I would save these extra data on server side and fetch it when user opens the app. This is most reliable

**Comment by kholiavko-roman** [comment]
@evollu , did you mean this callback ?
`this.notificationListener = FCM.on(FCMEvent.Notification, async (notif) => { .... });`

I tested it, and it works only when I tapped on notification. On both platform.

**Comment by evollu** [comment]
try add `content_available: true` in your notification payload

**Comment by kholiavko-roman** [comment]
Thank you @evollu! You are very helped me!

**Comment by kholiavko-roman** [comment]
@evollu, when I first find the solution for this, that was for Android and it works fine. But I forget to check it on iOS: `content_available: true ` and it doesn't bring up to background when app dropped from processes.
Checked on iOS: 10.3.3

> I would save these extra data on server side and fetch it when user opens the app. This is most reliable
Can't use it because I count new messages on client side and show it on badge. I can't set badge value from server because server have no idea about unread message count.

**Comment by evollu** [comment]
@kholiavko-roman https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623013-application
`However, the system does not automatically launch your app if the user has force-quit it. In that situation, the user must relaunch your app or restart the device before the system attempts to launch your app automatically again.`

I guess you have to design the server to know about the count.

**Comment by kholiavko-roman** [comment]
@evollu, Ok! Thank you for helping!
