### ISSUE TITLE
How is the custom_notification payload showing notifications? 

### ISSUE THREAD

**Issue by rtman** [evollu/react-native-fcm#535]
@evollu @seanadkinson

I am using the `custom_notification` payload and the `fetch` send method. I have a use case where I want the notification to not be presented if the user is currently in the chat window. Before when I was using a regular `data` payload, notifications were presented with `FCM.presentLocalNotification` and I would check if the message was read and then if it was I wouldn't call `FCM.presentLocalNotification`.

However now with a `custom_notification` payload, `FCM.presentLocalNotification` is no longer used to present the notification, and as far I can tell there is no call back to present the notification. Or is there? Any ideas on how I can achieve the above with the `custom_notification` payload scenario?

Thanks.

**Comment by rtman** [comment]
Ok upon digging around in the react-native-fcm files I see there is this java function in `MessagingService.java`

```
    public void buildLocalNotification(RemoteMessage remoteMessage) {
        if(remoteMessage.getData() == null){
            return;
        }
        Map<String, String> data = remoteMessage.getData();
        String customNotification = data.get("custom_notification");
        if(customNotification != null){
            try {
                Bundle bundle = BundleJSONConverter.convertToBundle(new JSONObject(customNotification));
                FIRLocalMessagingHelper helper = new FIRLocalMessagingHelper(this.getApplication());
                helper.sendNotification(bundle);
            } catch (JSONException e) {
                e.printStackTrace();
            }

        }
    }
```

Is there any way to temporarily disable this based on code from react native? Or atleast pass some props to it so that I can modify the if statement to `customNotification != null && messageRead != true`?

I'm not a native programmer so I don't know the way here unfortunately.

**Comment by evollu** [comment]
OK. Your problem is that when notification arrives, the JS callback doesn't get triggered right?
I should send an event on notification arrival.

**Comment by rtman** [comment]
Oh interesting, well I'm not sure how that event is received in react-native. How do I listen for that event?

**Comment by evollu** [comment]
`FCM.on(FCMEvent.Notification`

**Comment by rtman** [comment]
Ah ok, so the JS callback is working fine, I'm using that to listen for the notification but I don't see any way to put a conditional statement after that to determine if the received notification should be shown. Below is what I was doing before which is no longer working.

```
     this.notificationListner = FCM.on(FCMEvent.Notification, notif => {
        this.chatRef = this.getRef().child('chat/' + this.generateChatId(notif));
        this.chatRef.child(notif.chatKey).once('value', (snapshot) => {
          if(snapshot.val().read === false) {
            this.showLocalNotification(notif);
          } else if(snapshot.val().read === true){
            //FCM.cancelLocalNotification(notif..uid)
            FCM.removeDeliveredNotification(notif..uid);
          }
        });
      });
```
Because now with custom_notification `this.showLocalNotification` isn't needed since the notification is presented automatically on the listener receiving it. 

```
     this.notificationListner = FCM.on(FCMEvent.Notification, notif => {
        if(notif.custom_notification){
          try {
            notif.custom_notification = JSON.parse(notif.custom_notification); 
          } catch (ex) {
            console.error(ex);
          }

        this.chatRef = this.getRef().child('chat/' + this.generateChatId(notif));
        this.chatRef.child(notif.custom_notification.chatKey).once('value', (snapshot) => {
          if(snapshot.val().read === false) {
            //this.showLocalNotification(notif);
          } else if(snapshot.val().read === true){
            //FCM.cancelLocalNotification(notif.custom_notification.uid)
            //FCM.removeDeliveredNotification(notif.custom_notification.uid);
          }
        });
      });
```

Any idea on how I could achieve this?

**Comment by olieidel** [comment]
Try using the keys `high_priority` and `show_in_foreground` in your `custom_notification` payload. With some combination of those you can modify the display behaviour of custom notifications.

**Comment by rtman** [comment]
@olieidel 

I think you're misunderstanding my use case. I only want the notification to no be presented​ when in the chat screen where the message is marked read. In all other screens I want the heads up notification to display normally.

_Sent from my Google Nexus 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by olieidel** [comment]
I think you're misunderstanding my advice :D set `high_priority` and / or `show_in_foreground` to false so that your notification does not automatically display when your app is active. Handle the notification in your app and check your navigation state, then display a local notification if needed.

**Comment by rtman** [comment]
Hah that's definitely possible!

Ok so what you're saying is that if I set the right combo of those two settings then I can get  `fcm.presentLocalNotification` to handle the foreground notifications right? If so that sounds doable!

_Sent from my Google Nexus 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by rtman** [comment]
Ok I got it working thanks a lot @olieidel  for the advice :)

I set `show_in_foreground: false` for my custom_notification payload on the notification types I wanted to not show in the chat window. Then in the `PushController` I checked if it was false within the `FCM.on(FCMEvent.Notification` then performed a check to see if  the `AppState` was active and if the message is read. The notifications in background and killed app states aren't handled by `this.showLocalNotification` so they are always shown and it Works great!

**Comment by Louies89** [comment]
hi @evollu, @rtman  and @olieidel 
I am trying to show only one notification when many notification are received.
I tried to store the number of notification are coming as a increment counter [this](https://github.com/evollu/react-native-fcm/blob/240ea4682d7d372882466ece0d848c51f0f06c41/Examples/simple-fcm-client/app/Listeners.js#L24) of code, so that if the counter is more than 1, then I will cancel the previous notification and show a new single notification like whatsapp does.

But this part of code is not called when app is killed. So my logic is not working.

Kindly help me...

**Comment by evollu** [comment]
@Louies89 if you are doing this for iOS, your callback won't be called if you force kill your app.
for Android, it should work. or you can assign same Id for each notification

**Comment by Louies89** [comment]
@evollu Just after asking the question, this using same ID trick came to my mind, and I am able to handle it nicely.
Thank you for the advice :) :+1:
