### ISSUE TITLE
Failed to grant permission ios 10.3.1

### ISSUE THREAD

**Issue by MrPeproni** [evollu/react-native-fcm#537]
i am trying to use this code in iOS 10.3.1 but gettint error of failed to grant permissions:

```
componentDidMount(){
 if(Platform.OS === 'ios'){
   FCM.requestPermissions({badge: false, sound: true, alert: true});
      try {
        console.log("[Push] requestPermissions");
        const values = await FCM.requestPermissions({badge: false, sound: true, alert: true});
        console.log(values);
      } catch(err){
        console.log("[Push] requestPermissions error: " + err);
        return;
      }
 }
}
```

![simulator screen shot 04-sep-2017 12 52 01 pm](https://user-images.githubusercontent.com/25629063/30015774-dd1fada2-916f-11e7-950e-836c8bb14918.png)

**Comment by MrPeproni** [comment]
@evollu can you please look at this issue?

**Comment by evollu** [comment]
do you see things like `Error in application:didFailToRegisterForRemoteNotificationsWithError: remote notifications are not supported in the simulator`

**Comment by evollu** [comment]
debug RNFIRMessaging.m line 288 to see what exactly is the error

**Comment by MrPeproni** [comment]
checked all the files but didn't work. As per your knowledge what can be the issue?

**Comment by evollu** [comment]
declining request will cause rejection. check your phone settings to see anything strange

**Comment by MrPeproni** [comment]
PushNotificationIOS's request permission is working fine. But FCM not.

http://facebook.github.io/react-native/releases/0.48/docs/pushnotificationios.html#pushnotificationios

**Comment by evollu** [comment]
yeah the implementation is a bit different. FCM request permission differently in iOS10.

**Comment by MrPeproni** [comment]
yes i am working in ios 10.3.1 so what is different with ios 10? I just spent 6hrs to debug this issue but didn't get success

**Comment by evollu** [comment]
have you tried adding that breaking point and check the value of `*error`?

**Comment by MrPeproni** [comment]
no.. how to do that and where?

**Comment by MrPeproni** [comment]
can you give me your discord id? if you have one

**Comment by evollu** [comment]
I don't have one. debug in xcode, find Libraries->RNFIRMessaging.xcodeproj->RNFIRMessaging.m, add a breakpoint in line 288. Run the app through xcode

**Comment by MrPeproni** [comment]
Trying... are you available now?

**Comment by MrPeproni** [comment]
@evollu Added a breakpoint and this is what i got. Please have a look at below screenshot

![img_8184 png](https://user-images.githubusercontent.com/25629063/30045415-d62342e0-9221-11e7-9c4a-10860df7a1b1.png)

**Comment by evollu** [comment]
it means your RN version in xcode doesn't match your JS bundle. Usually it is caused by 1. rn upgrade 2. you are running a packager for another app

**Comment by MrPeproni** [comment]
@evollu what does that mean?

2. you are running a packager for another app

**Comment by MrPeproni** [comment]
@evollu i am trying to upgrade rn but getting this issue... Please help.

![screen shot 2017-09-06 at 5 41 17 pm](https://cdn.discordapp.com/attachments/324873632465551370/354855283702628362/Screen_Shot_2017-09-06_at_10.37.36_AM.png)

**Comment by MrPeproni** [comment]
@evollu upgraded to 0.48 RN. Still getting this issue

**Comment by evollu** [comment]
why would adding a break point giving you a different error?
which line is throwing?

**Comment by jeroenbourgois** [comment]
I have the same issue, the first time the OS popup is shown when you deny the access and then call the `requestPermission` again, it fails.

I added the breakpoint to the code and the `granted` bool is 'NO'. The code just checks the 'YES' case:

```
    if(granted){
      resolve(nil);
    } else{
      reject(@"notification_error", @"Failed to grant permission", error);
    }
```

I do not know the actual values of `granted`, but if they were YES | NO | NIL we could update the if/else accordingly?

**Comment by evollu** [comment]
@jeroenbourgois do you know in which case it will be nil?
I assume NO means user declined the request

**Comment by jeroenbourgois** [comment]
Indeed that makes sense. I do not know how the bridge works, but by using the catch I managed to covers the different scenario's.

**Comment by evollu** [comment]
perhaps I will add a note in documentation

**Comment by jeroenbourgois** [comment]
Ok. I think this can be closed.

**Comment by natashache** [comment]
@jeroenbourgois not completely getting your point. If user presses cancel for the first time, `requestPermissions` will fail in the future. You used the catch clause to handle it? How?

**Comment by evollu** [comment]
grant permission prompt can be asked only once in my experience. then user has to go to settings to change it manually.

try catch around `requestPermissions` is just capturing the error so you can move on in the code.

It is weird that your phone setting is on while requestPermissions fails. did you give all the permissions or just partial? have you tried new install?

**Comment by natashache** [comment]
@evollu I only have `FCM.requestPermissions();` in the code for requesting permission. I assume it's asking for all permissions. And in the phone's setting it shows permission's granted for badge, sound, alert (so all the permissions). In the app, I do not get an error, but rather a warning that says 'failed to grant permission', as in @MrPeproni's screen shot above.

**Comment by evollu** [comment]
@natashache please debug in xcode, add breakpoint at here
https://github.com/evollu/react-native-fcm/blob/master/ios/RNFIRMessaging.m#L286

check the detail error for failure

**Comment by jeroenbourgois** [comment]
@natashache like @evollu says, the actual OS (on iOS) modal is only shown once, after that it returns the choice the user made; being acknowledged or rejected the notifications. In the code, you can dispatch the `requestPermissions` Promise. It will only resolve when the user accepted the permissions, it will reject if the user denied.

In our code, we handle it this way:

    // on a specific 'why notifications' screen
    FCM.requestPermissions()
          .then(e => dispatch(turnOnPushNotifications()))
          .catch(() => dispatch(turnOffPushNotifications()))
     
    // in a 'notification controller' which listens to AppState changes and on ComponentDidMount
    PushNotificationIOS.checkPermissions(
        (permissions: IOsPermissionState) => {
          if (permissions.alert === 1 || permissions.badge === 1 || permissions.sound === 1) {
            dispatch(turnOnPushNotifications())
          } else {
            dispatch(turnOffPushNotifications())
          }
        })

For now we only handle the iOS part since our Android app is not targeted for runtime notifications. This might change soon though.... I hope this helps!

**Comment by evollu** [comment]
an PR to port PushNotificationIOS.checkPermissions into this repo is welcomed BTW

**Comment by natashache** [comment]
Thanks @evollu @jeroenbourgois. After adding the catch block the warning is no longer showing and the notifications (mysteriously) started coming in. Let's hope it stays that way.
