### ISSUE TITLE
Non correct linking instruction

### ISSUE THREAD

**Issue by cherniv** [evollu/react-native-fcm#54]
As said in installation instructions: 

> Run react-native link react-native-fcm

but when i did it i got error:

> rnpm-link info Linking react-native-fcm android dependency 
> rnpm-link ERR! It seems something went wrong while linking. Error: path must be a string 
> Please file an issue here: https://github.com/rnpm/rnpm/issues 
> /PROJECT_PATH/node_modules/promise/lib/done.js:10
>       throw err;
>       ^
> 
> TypeError: path must be a string
>     at TypeError (native)
>     at Object.fs.openSync (fs.js:584:18)
>     at Object.fs.readFileSync (fs.js:431:33)
>     at applyPatch (/PROJECT_PATH/node_modules/react-native/local-cli/rnpm/link/src/android/patches/applyPatch.js:6:29)
>     at registerNativeAndroidModule (/PROJECT_PATH/node_modules/react-native/local-cli/rnpm/link/src/android/registerNativeModule.js:23:3)
>     at /PROJECT_PATH/node_modules/react-native/local-cli/rnpm/link/src/link.js:43:5
>     at process._tickCallback (node.js:406:9)
>     at Function.Module.runMain (module.js:449:11)
>     at startup (node.js:141:18)
>     at node.js:933:3
> 

So i did it like:
`react-native link 'react-native-fcm'`
And it worked fine

**Comment by evollu** [comment]
I don't have that issue. what rn version are you running?
