### ISSUE TITLE
FCM.getInitialNotification() doesn't work when user kill app

### ISSUE THREAD

**Issue by MrPeproni** [evollu/react-native-fcm#544]
@evollu Below code is working when app is open in background. After killing app i am getting notifications but below code doesn't work. I want to redirect user to a specific page when user come to app through notification:

```
componentWillMount(){
    FCM.getInitialNotification().then(notif=> {
      console.log(notif);
    });
}
```

**Comment by evollu** [comment]
don't put it in component life cycle if you want to handle it when app is killed

**Comment by pewh** [comment]
So, where does it should be? I have no clue :/

**Comment by evollu** [comment]
e.g. right under your imports

**Comment by pewh** [comment]
Did you mean outside of class scope? If yes, then how can I access redux props, let's say if currentRole is admin in redux, when this function is outside of class?

**Comment by evollu** [comment]
you have a place where you declare redux store right?
like `const store = createStoreWithMiddleware(reducer);`
then you can do `store.dispatch(someAction());`

However I think it is better than have 2 notification listeners. one for handling notification when app is a live, another just to do fetch data etc when app is killed

**Comment by pewh** [comment]
This is my root render:
```
return (<Provider store={this.store}>
        <App />
      </Provider>)
```

and inside `<App />`, wrapped with use @connect, and `componentWillMount` have `FCM.getInitialNotification().then...`.

Do you mean that I use something like `this.store.dispatch(someAction())`?

**Comment by evollu** [comment]
yep
