### ISSUE TITLE
Comparability with react-native-navigation ? 

### ISSUE THREAD

**Issue by kholiavko-roman** [evollu/react-native-fcm#547]
Hello! Thanks for you work, plugin is amazing!

I have one problem after migrating my app to [react-native-navigation](https://github.com/wix/react-native-navigation) - If I removed app from process, and received push notificaiton, app started and becomes to foreground. The problem similar to [this issue](https://github.com/wix/react-native-navigation/issues/1799)
Can you help me to fix it? if this react-native-navigation bug ?

**Comment by luthfidc03** [comment]
is send local notification working?

**Comment by kholiavko-roman** [comment]
Yes, local notification working as well. When I received it, application does not started.

**Comment by evollu** [comment]
what does `Navigation.startSingleScreenApp` do?
It is possible what happened is 
- notification comes and android wakes up JS thread and JS thread creates a new Activity and brings it foreground.

Solution would be not calling startSingleScreenApp rather calling some function just doing navigation

**Comment by kholiavko-roman** [comment]
`startSingleScreenApp` this is enter point in to the app, I think there is no different way to do this.

> notification comes and android wakes up JS thread and JS thread creates a new Activity and brings it foreground.

I assume exactly same happened. 
Maybe FCM have some functions to detected app started normally or starting by push ?

**Comment by evollu** [comment]
nope. why would you startSingleScreenApp on notification?
when app is alive, you shouldn't need to start a new screen
when app is killed, you should build an activity either

**Comment by kholiavko-roman** [comment]
> nope. why would you startSingleScreenApp on notification?
I dont use `startSingleScreenApp` on notification, it is my main file. And when push notificaiton arrives, it started this file, and `startSingleScreenApp` called.

**Comment by evollu** [comment]
hmm...ok. so you are using that to manager routes rather than react-native's main screen?

try check the status of the app, it might be background if it is waken by notification

**Comment by kholiavko-roman** [comment]
> hmm...ok. so you are using that to manager routes rather than react-native's main screen?

Between another page I switching using `resetTo `method, or `push`

```
this.props.navigator.resetTo({
          screen: "somePage"
});

this.props.navigator.push({
          screen: "somePage"
});
```

> try check the status of the app, it might be background if it is waken by notification

You mean checking background or foreground using `AppState ` ?

**Comment by kholiavko-roman** [comment]
I tried `AppState`, it return true, when app started on push arrives.

**Comment by kholiavko-roman** [comment]
I can not found a solution to detect that app started form background..
And If I remove payload data than fired push in background, I cannot normally work with new data (I need to set up badge, and to save data from push notification into storage)

**Comment by kholiavko-roman** [comment]
I discovered, that when app started normally, or (app closed from process) and push received - app becomes to foreground, callback that catches push notification, fires with [this data:]
![Data from my usual notification.](http://joxi.ru/V2VnQnQsxXJVn2.jpg)

In case when push received - callback shows only which data ( data that send directly from push, does not shows)

Data from my usual notification.
![Data from my usual notification.](http://dl4.joxi.net/drive/2017/09/08/0005/3103/338975/75/9be78057e5.jpg)

**Comment by evollu** [comment]
when notification arrives, you can use `resetTo` or `push` to navigate around as well. You just need to have a listener inside component lifecycle to just handle the navigation.

**Comment by sibelius** [comment]
I think we can close this, this is more related to react-native-navigation

you can have a component that render null, and have listeners on component lifecycle to deal with it

**Comment by kholiavko-roman** [comment]
Yes, its react-native-navigation difficult. Thanks for helping.
