### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by ElenaDiaz** [evollu/react-native-fcm#55]
I am having trouble integrating FCM in Android, it is working perfectly in IOS with this component.
But in Android I am getting this error:

`node_modules/react-native-fcm/android/src/main/java/com/evollu/react/fcm/FIRMessagingModule.java:159: error: method does not override or implement a method from a supertype
    @Override
    ^
`

Maybe there is any error in the README? Because there is a different config for RN0.28+ and RN <= 0.27, but both are identical.

![image](https://cloud.githubusercontent.com/assets/12825893/17054001/be9eb39c-4ffc-11e6-9a82-9a945d61a360.png)

Btw, I am using RN 0.28.0
Thank you for your help!

**Comment by evollu** [comment]
0.28 declare as public while 0.27 declare as protected

**Comment by evollu** [comment]
the error messaging throwing error is not related to the part you posted.
If you are using 0.27, please install 1.0.15, latest one only support RN 0.30.0+

You also need follow the instruction and add override function in MainActivity.java

**Comment by ElenaDiaz** [comment]
Thank you for your reply @evollu . I didn't realize the difference (public and protected).
I am using RN 0.28, so I override with the public method and I am using version 1.0.15.

Thanks!

**Comment by xotahal** [comment]
Followed the migration instructions from RN0.27 to RN0.30 but there is still this issue (using version 1.0.16 now but before I had 1.0.15) - `node_modules/react-native-fcm/android/src/main/java/com/evollu/react/fcm/FIRMessagingModule.java:159: error: method does not override or implement a method from a supertype @Override ^`

I tried new project (`react-native init awesome-project`) and it was working well. Any idea? Is there any cache? I've already done `gradlew clean`.

**Comment by evollu** [comment]
the project may cache react native project. I'm using android studio and I have to make the IDE to sync all dependencies again to make it work

**Comment by evollu** [comment]
@ElenaDiaz so is your problem solved?

**Comment by Roconda** [comment]
Got this error as well using RN 0.28.0 and FCM ^1.0.9

**Comment by Roconda** [comment]
Changed "react-native-fcm": "^1.0.9", to "react-native-fcm": "1.0.9". Everything seems to work now.

By default the npm install --save commands saves the version including the ^. This breaks older code bases.

**Comment by evollu** [comment]
@Roconda  without ^ it is not predictable what version is installed. you may just installed 1.0.16 version

**Comment by xotahal** [comment]
It pulled react native from jcenter instead of using version from `node_modules` - https://github.com/facebook/react-native/commit/84f82e5cdd06e1e4ed9ae0ebaf0dab57c5046f64

Maybe, it'll help :)

**Comment by evollu** [comment]
@xotahal can you dig into the source code of react native android and see how it defines activitylisterner? perhaps compare the newly initiated version?

**Comment by xotahal** [comment]
Everything works for me now. So it's ok. I had just set bad path to react native (because it was changed here https://github.com/facebook/react-native/commit/84f82e5cdd06e1e4ed9ae0ebaf0dab57c5046f64)

**Comment by evollu** [comment]
@xotahal 👍

**Comment by evollu** [comment]
@ElenaDiaz can I close the issue now

**Comment by ElenaDiaz** [comment]
Yes. Thanks!

**Comment by YanYanLun** [comment]
@xotahal thanks

**Comment by wiadev** [comment]
@xotahal I have same issue but can you tell me how you fixed?
```maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }```

**Comment by xotahal** [comment]
Just changed this path (as you did), clear node_modules, npm install and reinstall app.

**Comment by wiadev** [comment]
@xotahal 
```
removed node_modules
npm install
react-native run-android
```
but still getting the same error.

**Comment by xotahal** [comment]
It worked for me. You probably have another problem :/ Sorry
