### ISSUE TITLE
Scheduled local notification is presented immediately instead of on fire_date on iOS device

### ISSUE THREAD

**Issue by junshengpierre** [evollu/react-native-fcm#553]
Hi, I am unable to get scheduled local notification to present on the designated `fire_date` on actual iPhone devices in release mode. Instead, it is presented immediately after `FCM.scheduleLocalNotification` runs. It is working as expected on android devices and iOS emulators (both dev and release modes). 

I have verified that no other local notifications have been scheduled prior with

```javascript
FCM.getScheduledLocalNotifications()
  .then((notifications) => {
    Alert.alert('scheduled notifications', JSON.stringify(notifications)) // returns []
})
```

and that `fire_date` of the notification provided was correct with

```javascript
this.notificationListener = FCM.on(FCMEvent.Notification, async (notification) => {
  if (notification.local_notification) {
    Alert.alert('notification', JSON.stringify(notification))
  }
})
```

Any idea what could be wrong? Really appreciate any help. Thank you.

```javascript
FCM.getScheduledLocalNotifications()
      .then(notifications => {
        const syncReminders = notifications
          .filter((notification) => {
            return notification.id.indexOf('lastSyncTime') >= 0
          })
        if (syncReminders.length > 0) {
          syncReminders.forEach((syncReminder) => {
            FCM.cancelLocalNotification(syncReminder.id)
          })
        }
        const now = Date.now()
        const fireDate = new Date(now + 604800000).getTime()
        FCM.scheduleLocalNotification({
          fire_date: fireDate,
          id: `lastSyncTime-${now}`, // required: unique string id
          title: "Local notification title",
          body: "Local notification body",
          show_in_foreground: true,
          priority: 'high',
          repeat_interval: 'week'
        })
      })
```

react-native: 0.46.4
react-native-fcm: 6.2.3
Firebase: 3.17.0
Devices: iPhone 6, 6 plus (iOS 10.3)
App running in foreground/background

**Comment by evollu** [comment]
have no clue here...

**Comment by junshengpierre** [comment]
It seems to work only when fire_date is less than 1 week from the current time. `new Date(now + 604800000).getTime()` didn't work but `new Date(now + 604800000 -1).getTime()` worked.

**Comment by evollu** [comment]
good to know... can you find if Apple has some supporting docs?

**Comment by AugustoAleGon** [comment]
I still have the same issue!

**Comment by evollu** [comment]
@AugustoAleGon the issue seems to be resolved?

**Comment by AugustoAleGon** [comment]
I still looking for the solution. The app crash

**Comment by evollu** [comment]
app crashing is not what the original issue is talking about. Please open another issue.
as for the reason for crashing, it could be many reason. try get the crash log
