### ISSUE TITLE
ios foreground banner visible

### ISSUE THREAD

**Issue by Ongatkha** [evollu/react-native-fcm#554]
On foreground i have the same behaviour as on background,.

**Comment by Ongatkha** [comment]
Iwant to clarify, i receive both a notification_type :  response notif and one willpresentnotif
The first one starts automatically ,the second one shows the banner first.
Is this normal behaviour?
@evollu

**Comment by evollu** [comment]
it is expected a notification firing multiple times. you can rely on "opened_from_tray" to differentiate them

**Comment by Ongatkha** [comment]
@evollu but on foreground i receive also one that has a banner one that fires a notification of type response_notification that i dont need because i dont want ot show banner while on foreground.

**Comment by evollu** [comment]
are you having `notif.finish(WillPresentNotificationResult.All)`?
change it to `WillPresentNotificationResult.None`

**Comment by Ongatkha** [comment]
@evollu 
I have the code from the doc
   //notif._notificationType is available for iOS platfrom
      switch(notif._notificationType){
        case NotificationType.Remote:
          notif.finish(RemoteNotificationResult.NewData) //other types available: RemoteNotificationResult.NewData, RemoteNotificationResult.ResultFailed
          break;
        case NotificationType.NotificationResponse:
          notif.finish();
          break;
        case NotificationType.WillPresent:
          notif.finish(WillPresentNotificationResult.All) //other types available: WillPresentNotificationResult.None
          break;
      }
    }

I am going to change it and tell the results.
So on background i get a notif that when i click i see its of type response_notification and on foreground i get one that fires automaticlly of type willpresentnotif and also a banner one that when i click it gives a notification of type response_notif.
If i put WillPresentNOtificationResult.none i'll get rid of the banner one from foreground?

**Comment by evollu** [comment]
right. or you can skip implementing the switch statement at all. WillPresentNotificationResult.None is default

**Comment by evollu** [comment]
seems resolved
