### ISSUE TITLE
IOS issue: "opened_from_tray" is always undefined for local notification

### ISSUE THREAD

**Issue by stsiushkevich** [evollu/react-native-fcm#555]
RN: 0.42.0
react-native-fcm: 7.4.0
IPhone 5 black, IOS 10.2.1

I get a remote notification when an app is in the foreground. Then I send a local notification based on the defined information from remote notification to show it in a tray. When I tap on notification(in foreground) from the tray I receive it to the listener, but I haven't "opened_from_tray" flag!!! But on Android I have it!!! I use alert to debug this case. How can I fix this trouble?

When I receive the remote notification in background and tap on it in the tray I have "opened_from_tray": 1 - all right.

**Comment by evollu** [comment]
well this sounds like a bug.
try adding "opened_from_tray" in your local notification payload for now.

**Comment by stsiushkevich** [comment]
Cheers!!! Thak you! It works correctly! Why was this code be missed?

**Comment by evollu** [comment]
cause I missed it ;) Will push the fix

**Comment by evollu** [comment]
published as 9.2.0
