### ISSUE TITLE
Android Issue - when the app is killed, the callback function not triggered when click on notification

### ISSUE THREAD

**Issue by melkayam92** [evollu/react-native-fcm#558]
Hey,

In Android, when the i click on the notification and the App is killed, the callback function doesn't triggered. 

I did follow all the steps, and all the other staff works good - when the app is in foreground/background the callback triggered fine.

Code:

`FCM.on(FCMEvent.Notification, async notif => {
//Not triggered when user click, but does trigger when receive notification (When app killed)
  if (notif.opened_from_tray) {

    console.log(`user clicked on notification`);
  }
});`

RN version: "0.48.3"
react-native-fcm version: "9.1.0"
device: Android nexus 5x emulator.
App is killed - not running.

Advanced:
The message does delivered, and i see the logs - but when click the notification it's like everything reset.

**Comment by evollu** [comment]
did you put your handler outside of component?

**Comment by melkayam92** [comment]
yes, that what's causing the problem?

**Comment by evollu** [comment]
oh. your issue is when you open the app by clicking the notification, you don't see the notif?
THAT notif that launchers the application will be in await FCM.getInitialNotification()

**Comment by melkayam92** [comment]
Thanks, its working great!

Awesome library!

**Comment by evollu** [comment]
cool
