### ISSUE TITLE
Screen redirection from closed app

### ISSUE THREAD

**Issue by Gigasz** [evollu/react-native-fcm#559]
I receive the notification with a redirect string, which with I make a switch and redirect to the desirable screen. It works when app is open or in background, but when it's closed it just open the app and the action get lost.

I'm using react-native-router-flux.

Can anybody help me?

**Comment by evollu** [comment]
try getting the notif from `getInitialNotificaiton`

**Comment by evollu** [comment]
possible dup of #558
