### ISSUE TITLE
Couldn't get it to work with react-native-push-notification

### ISSUE THREAD

**Issue by ranjithnori** [evollu/react-native-fcm#56]
Since its clearly mentioned on the home page that notifications do not appear when the app is in foreground on android, I chose to trigger notifications locally in that particular case using react-native-push-notification@1.0.7(I'm using react-native@0.27.2).

I can not get it to work with react-native-fcm. My gradle builds fail with the following error. Please help!

```
Error:Execution failed for task ':app:processDebugResources'.
> Error: more than one library with package name 'com.google.android.gms'
```

**Comment by evollu** [comment]
it might because the packages requires different gms version
try add
```
dependencies {
   compile ('com.google.android.gms:play-services-gcm:9.2.0') {
        force = true; 
   } 
}
```
in android/app/build.gradle to force the gcm version

**Comment by ranjithnori** [comment]
Thanks for the quick response! It worked well :)
How did you suggest the exact version number ?

I tried 9.2.1 and it didn't work.

**Comment by evollu** [comment]
i think it depends on your play sevice library.
