### ISSUE TITLE
getInitialNotification is null if app is closed and opened from banner. Additional data in custom_notification

### ISSUE THREAD

**Issue by CptFabulouso** [evollu/react-native-fcm#560]
What version of RN and react-native-fcm are you running?
"react-native": "0.46.4",
"react-native-fcm": "^9.1.0",

What device are you using? (e.g iOS9 emulator, Android 6 device)?
android device nexus 5x

Is your app running in foreground, background or not running?
1) Iam not able to achieve this behaviour:
If app is closed (not running) and I receive notification, I want to show the notification and then be able to know, if the app was opened by clicking the banner, or app icon. I also expect to know if the banner was clicked when app is opened / in background, but that works fine (except the second question part below).

I send custom_notification payload to fcm according to docs, so after receiving silentNotification (with no notification payload) I let this package to build a local notification. But in both cases, whether I open the app by clicking the notification banner or app icon I get null value returned from FCM.getInitialNotification(). Does anybody know how to achieve the expected behaviour? I have spend too much time looking for answer here, but with no luck.

2) Also I noticed that after clicking banner and receiving second notification with opened_from_tray value, I lost any additional data I send with originial notification, to make it really clear, I send:

```
{
  "to":"FCM_TOKEN",
  "data": {
    "custom_notification": {
      "body": "test body",
      "title": "test title",
      "color":"#00ACD4",
      "priority":"high",
      "icon":"ic_notification",
      "show_in_foreground": true
    },
   "someOtherData":"data", //this gets lost
   "someEvenMoreOtherData":"data2", //this gets lost
  }
}
```

after clicking the banner I receive:
```
body:"test body",
color:"#00ACD4",
fcm:{action: null},
icon:"ic_notification",
opened_from_tray:1,
priority:"high",
show_in_foreground:true,
title:"test title",
```
so just what is in custom_notification, so should I send my additional data also in custom_notification? 

also my manifest file

```
<application
      android:name=".MainApplication"
      android:allowBackup="true"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:theme="@style/SplashTheme">
      <activity
        android:name=".MainActivity"
        android:launchMode="singleTop"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
        <!-- FCM START-->
        <intent-filter>
            <action android:name="fcm.ACTION.HELLO" />
            <category android:name="android.intent.category.DEFAULT" />
        </intent-filter>
        <!-- FCM END-->

      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />

      <!-- FCM START -->
        <service android:name="com.evollu.react.fcm.MessagingService" android:enabled="true" android:exported="true">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT"/>
            </intent-filter>
        </service>

        <service android:name="com.evollu.react.fcm.InstanceIdService" android:exported="false">
            <intent-filter>
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
            </intent-filter>
        </service>

        <receiver android:name="com.evollu.react.fcm.FIRLocalMessagingPublisher"/>
        <receiver android:enabled="true" android:exported="true"  android:name="com.evollu.react.fcm.FIRSystemBootEventReceiver">
          <intent-filter>
              <action android:name="android.intent.action.BOOT_COMPLETED"/>
              <action android:name="android.intent.action.QUICKBOOT_POWERON"/>
              <action android:name="com.htc.intent.action.QUICKBOOT_POWERON"/>
              <category android:name="android.intent.category.DEFAULT" />
          </intent-filter>
        </receiver>
</application>
```

**Comment by evollu** [comment]
Q1: the notification goes to intialNotification only if you LAUNCH the app by click the notif. If the app is running, it will go to Notification callback.
Q2: yes, the data gets lost. put it inside "custom_notification"

**Comment by CptFabulouso** [comment]
Thank you for your response.

Q1: OK, maybe Iam confused when the app is opened and when it is launched, but anyway, I log the notification callback and I don't see it, what I see is the app reload in debugger and the receive of notification is logged, the callback is not).

what I do:
close the app (by swiping it out from running applications on phone)
send the notification
open it from banner

could setting click_action help? (I am not in control of server side of the application and cannot just set it). If yes, should it go into custom_notification or outside?

Also this is my root component, where I guess the callback should be catched in the FCMEvent.Notification method with opened_from_tray value

```
FCM.on(FCMEvent.Notification, async (notif) => {
	console.log("FCMEvent.Notification", notif)
    // there are two parts of notif. notif.notification contains the notification payload, notif.data contains data payload
    if(notif.local_notification){
    	console.log("local_notification")
    }
    if(notif.opened_from_tray){
    	console.log("opened_from_tray")
    }
});

FCM.on(FCMEvent.RefreshToken, (token) => {
    console.log(token)
    // fcm token may not be available on first load, catch it here
});

const store = createStore(reducers, {}, applyMiddleware(ReduxThunk) )

class Root extends Component {

	render() {
		const store = createStore(reducers, {}, applyMiddleware(ReduxThunk) )
		console.disableYellowBox = true

		return (
			<Provider store = {store}>
				<RootScreen />
			</Provider>
		);
	}
}
```

**Comment by evollu** [comment]
can you show me your FCM.getInitialNotification() code?

**Comment by CptFabulouso** [comment]
right now there is just console log
This code is in my RootScreen in componentDidMount. Where is RootScreen in my app can be seen in code above. I tried to move it into Root component in componentDidMount and also outside of component, but value of notif is always null.

```
FCM.getInitialNotification().then(notif=>{
     console.log("getInitialNotification", notif)
});
```

**Comment by evollu** [comment]
android should always have something in initial notif. have no clue now

**Comment by CptFabulouso** [comment]
ok, I tried to create new app, set up everything and it works, so I have to find out where is the problem within my app. Closing this, will post here if I find what was causing it.

**Comment by CptFabulouso** [comment]
alright I have localized the problem. In my project Iam using splashscreen, I've seen an issue where the splashscreen problem was discussed, but he used another activity for it, I am not, Iam just modifeing app theme a little, so my project is set up this way.

in my manifest file (the whole manifest is above)
```
<application
      android:name=".MainApplication"
      android:allowBackup="true"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:theme="@style/SplashTheme"> //my modified theme
```

values/styles.xml
```
<style name="SplashTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="android:colorPrimaryDark">@color/statusbar</item> 
        <item name="colorPrimaryDark">@color/statusbar</item>
        <item name="android:windowBackground">@drawable/background_splash</item>
    </style>
```

drawable/background_splash.xml
```
<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">

    <item
        android:drawable="@color/splascreen_background"/>

    <item>
        <bitmap
            android:gravity="fill"
            android:src="@mipmap/splashscreen"
            />
    </item>

</layer-list>
```

The splashscreen bitmap is jpg picture ranging in size from mdpi: 720 x 480 up to xxxhdpi 1920 × 1280, my device xxhdpi uses 1440 × 960 picture. I guess the picture load time messes up with the initial load somehow, because if I replace the splashscreen picture with something much smaller (like app icon), the getInitialNotification method works fine. Splashscreen is 129 kB big (icon 5kb), so the difference is big, but I think it should not matter? I've tried if android likes png better, but he does not. 

Another weird behaviour I've now noticed is that if I click the notification banner or app icon quickly after the banner is shown, the getInitialNotification returns expected values, otherwise it's null. 

any ideas why this happens?

**Comment by evollu** [comment]
I may have some clue now.

source code
https://github.com/evollu/react-native-fcm/blob/master/android/src/main/java/com/evollu/react/fcm/FIRMessagingModule.java#L57-L65

You see it calls `getCurrentActivity` to get current running activity. Can you check what is the activity when you call it.
Perhaps it is running the splash screen's activity so you get nothing.

**Comment by CptFabulouso** [comment]
So I put a log into getCurrentActivity
```
public void getInitialNotification(Promise promise){
        Activity activity = getCurrentActivity();
        Log.e("ACTIVITY", activity.getLocalClassName());
        if(activity == null){
            promise.resolve(null);
            return;
        }
        promise.resolve(parseIntent(getCurrentActivity().getIntent()));
}
```
and in case I close the app, send notification and try to open the app, it gives me null error. And I can now also see why getInitialNotification in JS returns null, because it is returned here in the promise
```
if(activity == null){
            promise.resolve(null);
            return;
}
```
it would be weird, if any other activity would run, I don't have any other activity in my app, just MainActivity.

**Comment by CptFabulouso** [comment]
After some more testing, the null value may have something to do with remote debugger being on and moving the JS execution away from device (or whatever happens). If I console.warn the notif value with debugger off then the value is as expected.

With debugger on a hacky solution is to move the getInitialNotification deepeer in my project structure or leave it where it is and put it inside timeout (1000ms). But I find it weird that inside componentDidMount, the application is not truly fully loaded and returns null activity.

One more thing that could also have been causing the problem before is that I noticed I had one wrongly named file in one of my mipmap folders for splashscreen.

**last question please**, if I open app from banner, the fcm.action value in notif is null, if I set the click_action in my custom_notification, this is where it would show right?

**Comment by evollu** [comment]
for you last question:  right.

for your wierd bug, can you try replace the code with following?

`
Activity activity = getReactApplicationContext().getCurrentActivity();
        if(activity == null){
            promise.resolve(null);
            return;
        }
        promise.resolve(parseIntent(activity.getIntent()));
`

**Comment by CptFabulouso** [comment]
Tried it, but the behavior is the same as before

**Comment by CptFabulouso** [comment]
And to further describe the behaviour

```
1) I remove the app from running application
   a) send the notification
      1) after notification appears I run the application from app icon -> initial notif is null
         a) remove the app from running application
         b) run it from app icon -> notif is as expected
      2) after notification appears I run the application from banner -> initial notif is null
         a) remove the app from running application
         b) run it from app icon -> notif is as expected
   b) do NOT send notification
      1) run application from app icon -> notif is as expected
```

so it is only after the first run of application after notification is recieved that this problem occures.

**Comment by evollu** [comment]
I may have clue now. We call `mReactInstanceManager.createReactContextInBackground();` in `MessagingService.java` to wake up app to handle notification when notif arrives. This creates a context but doesn't create activity.

**Comment by CptFabulouso** [comment]
It does when it is received, but on banner click callback is not called.

**Comment by evollu** [comment]
ok then it is not related to `mReactInstanceManager.createReactContextInBackground();`
I have no idea why the activity is null now

**Comment by Ashoat** [comment]
I am having this issue as well. I am using [`react-native-splash-screen`](https://github.com/crazycodeboy/react-native-splash-screen), which has its own launch Activity: `SplashActivity`.

```java
public class SplashActivity extends AppCompatActivity {

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    Intent intent = new Intent(this, MainActivity.class);
    startActivity(intent);
    finish();
  }

}
```

The issue is that `MessagingService` is sending its `Intent` message to `SplashActivity`, which then starts `MainActivity`, and the message is lost. The solution is simple: just add the following line to `SplashActivity` after the intent is constructed:
```java
intent.putExtras(this.getIntent());
```

This copies over the "extras" from `MessagingService`'s intent over to the new `MainActivity` intent, enabling `FIRMessagingModule` to later extract these extras and send them across the bridge to JavaScript.

**Comment by evollu** [comment]
@Ashoat I'm using that as well.
That SplashActivity is not the main activity for the app
you can see their document that it just calls `SplashScreen.show(this);  // here` to show up that activity to cover main activity

**Comment by ishigamii** [comment]
@Ashoat Thanks a lot for this. it was just what I was missing 💯
