### ISSUE TITLE
sub_text not showing when the application is in background

### ISSUE THREAD

**Issue by roberto-rodriguez** [evollu/react-native-fcm#568]
sub_text value not showing when the application is in background.
(It do shows when the application is in foreground)

Thanks!!

**Comment by evollu** [comment]
I don't have this issue

**Comment by roberto-rodriguez** [comment]
Can you please share an example of the request you are sending?

**Comment by roberto-rodriguez** [comment]
Hi Evollu,
I still have the problem, sending exactly the same message with sub_text field, when the app is in foreground, it shows, when it is in background, it does not.

This is the msg I am sending:

{
	"notification": {
		"title": "Welcome to MyApp",
		"body": "Dear Mr Smith, we are pleased to",
		"sub_text": "have you as a new customer.",
		"subText": "have you as a new customer.",
		"show_in_foreground": true,
		"priority": "high"
	},
	"data": {
		"custom_notification": {
			"title": "Welcome to MyApp",
			"body": "Dear Mr Smith, we are pleased to",
			"sub_text": "have you as a new customer.",
			"subText": "have you as a new customer.",
			"show_in_foreground": true,
			"priority": "high"
		}
	},
	"to": "MOBILE_TOKEN_HERE"
}

Notice that I am sending the sub_text also as subText, just in case.

Please advise.

Also.. I am using sub_text as an alternative to have two lines in the message, (I have some logic in my server to split the message, the first 40 characters to the body and the rest to sub_text, please let me know if there is a better alternative for this)

Thanks for your support!!

**Comment by evollu** [comment]
remove notification payload. if `notification` existing, "custom_notification" will be ignore by Firebase when in background

**Comment by roberto-rodriguez** [comment]
Yes that fixed it. Don't have words to say thanks man.
You are awesome!!

**Comment by evollu** [comment]
cool
