### ISSUE TITLE
FIRMessagingModule.java doesn't compile

### ISSUE THREAD

**Issue by simlmx** [evollu/react-native-fcm#57]
FIRMessagingModule.java:159: error: method does not override or implement a method from a supertype.

Removing the line (which contains "@Override") seems to fix it.

**Comment by evollu** [comment]
have you checked #55 ? What RN version are you running?

**Comment by simlmx** [comment]
Yes I tried both protected and public. I'm running 0.29.

**Comment by evollu** [comment]
latest version only supports 0.30.0 above. Please use version 1.0.15

**Comment by simlmx** [comment]
I upgraded to 0.30.0 instead and it's working fine.

**Comment by evollu** [comment]
👍
