### ISSUE TITLE
iOS: Badge related notifications sound/vibrate issue

### ISSUE THREAD

**Issue by baldurpan** [evollu/react-native-fcm#570]
I was (seemingly) randomly getting notifications with no sound/vibration or no notification at all. This issue had me puzzled for a few months but I finally figured out the pattern.

When pushing notifications with a custom sound and a badge changing the app badge icon from anything to zero, you won't get any sound or vibration with the notification. 

Example test pushes with my custom sound.
```
// Works fine and gives the app icon a badge of 5
notification: {
  title: 'Message',
  body: 'Test 1',
  sound: 'cash.caf',
  badge: 5
}

// Gives a completely silent notification and removes the badge
notification: {
  title: 'Message',
  body: 'Test 2',
  sound: 'cash.caf',
  badge: 0
}

// Sound works again
notification: {
  title: 'Message',
  body: 'Test 3',
  sound: 'cash.caf',
  badge: 0
}
```

Same scenario (with default sound)
```
// Works fine and gives the app icon a badge of 5
notification: {
  title: 'Message',
  body: 'Test 1',
  sound: 'default',
  badge: 5
}

// Works fine and removes the badge
notification: {
  title: 'Message',
  body: 'Test 2',
  sound: 'default',
  badge: 0
}

// Still works fine
notification: {
  title: 'Message',
  body: 'Test 3',
  sound: 'default',
  badge: 0
}
```

I'm guessing this one has been around for a while since I've given up several times on figuring out what was going on.

Using:
react-native v0.48.3
react-native-fcm v9.1.0

**Comment by evollu** [comment]
is it local notification or remote?

**Comment by baldurpan** [comment]
Ah sorry. They are remote.

**Comment by evollu** [comment]
looks like it is `notification` property in remote notif, which is 100% handled by FCM SDK. you need to report an issue to them.

**Comment by evollu** [comment]
please reopen if you have more question

**Comment by baldurpan** [comment]
Got this response from Firebase support:

Thanks Baldur.

What version of iOS have you been testing on? We've tried on iOS 11 and were unable to reproduce it. Also, how the sound gets played should be controlled by iOS and not FCM. According to Apple's docs when a non-default sound can't be played, the default sound gets played instead. Can you try adding a breakpoint when you receive the notification and inspect userInfo dictionary to see what the "sound" value is?

**Comment by baldurpan** [comment]
@evollu I am unable to re-open issues unless I close them myself.

**Comment by evollu** [comment]
still it doesn't sound issue of this repo.
you can try to reproduce it using quickstart-ios from firebase. If it all works fine then we can take a look here.
I guess iOS just mute the notif when you set badge to 0?

**Comment by baldurpan** [comment]
No mute doesn't happen if you always use badge = 0, just when the badge changes to 0.
But ok, I'll check this further.
Thanks.
