### ISSUE TITLE
iOS app shows notifications when in background but not foreground.

### ISSUE THREAD

**Issue by AndrewMarkley** [evollu/react-native-fcm#572]
Issue (on iOS 9, all this works on android)
App is receiving remote notifications when not running and displaying them in notification bar. When app is in foreground it receives remote notifications but does not show the notification. When doing local notifications they show up in the notification list but it doesn't make any sounds or show the banner for a couple seconds.

For local notifications I call
```
FCM.presentLocalNotification({
      title: 'Local Notification Test',
      body: 'Look at that you can hit a button!', 
      priority: "high",
      sound: "notification",
      auto_cancel: true,
      vibrate: 300,
      lights: true,
      show_in_foreground: true,
      local: true,
      icon: "ic_notif",
      large_icon: "ic_launcher",
      color: "#497EE3"
    });
```
For remote notifications I'm sending this data:
```
{
  "data":{
     "screen":"dev"
  },
  "notification":{
     "title":"Remote Push Notification Test",
     "body":"This has been a test of XXXXXXX's remote push notification system.",
     "screen":"dev",
     "big_text":"This has been a test of XXXXXXX's remote push notification system.",
     "icon":"ic_notif",
     "largeIcon":"ic_notif_launcher",
     "click_action":null,
     "color":"#497EE3",
     "vibrate":300,
     "sound":"notification",
     "priority":"High",
     "badge":0
  },
  "registration_ids":[
     "XXXXXXXXXXX",
     "XXXXXXXXXXX"
  ]
}
```

my notification listener

```
this.notificationListener = FCM.on(FCMEvent.Notification, async (notif) => {
      console.log('we got a push notification!', notif);
      if(notif.local_notification){
        // this is a local notification
        // we aren't doing these yet, but actions can be triggered from here eventually
      } else if(notif.opened_from_tray){
        // app is open/resumed because user clicked banner
        const fun = NavigationActions[notif.screen];
        if(typeof fun === 'function') {
          eval(fun({ type: ActionConst.RESET }));
        }
      }

      if(Platform.OS ==='ios') {
        switch(notif._notificationType){
          case NotificationType.Remote:
            // other types available: RemoteNotificationResult.NewData, RemoteNotificationResult.ResultFailed
            notif.finish(RemoteNotificationResult.NewData)
            break;
          case NotificationType.NotificationResponse:
            notif.finish();
            break;
          case NotificationType.WillPresent:
            // other types available: WillPresentNotificationResult.None
            notif.finish(WillPresentNotificationResult.All)
            break;
        }
      }
    });
```

What version of RN and react-native-fcm are you running?
"react-native": "0.40.0",
"react-native-fcm": "9.1.0"

What device are you using? (e.g iOS9 emulator, Android 6 device)?
iOS 9 iPod touch

Is your app running in foreground, background or not running?
foreground

Advanced:
Have you tried adding break point in native handlers to see if message gets delivered?
can share a project with issue?

Yes, FCM.on(FCMEvent.Notification, async (notif) => console.log(notif)) always prints received notifications.

Am I missing something? I know I'm super close I just don't know what to try next to debug this issue.

**Comment by evollu** [comment]
iOS9 doesn't support showing notification when app is foreground. It starts from iOS 10

`sound: "notification"` try file name? like `notification.mp3`

**Comment by AndrewMarkley** [comment]
@evollu 
> iOS9 doesn't support showing notification when app is foreground
Shouldn't the remote notifications at least show up in the notifications list? The local ones do.

**Comment by evollu** [comment]
right I'm afraid that's system limitation. 
There are many stackoverflow questions already like this
https://stackoverflow.com/questions/30852870/displaying-a-stock-ios-notification-banner-when-your-app-is-open-and-in-the-fore

**Comment by muhammadmisbah** [comment]
iPhone6: iOS:11.4 app shows notifications when in background but not foreground. :/ have been trying for 2 days
