### ISSUE TITLE
New installation issues - randomly register or not

### ISSUE THREAD

**Issue by tobob** [evollu/react-native-fcm#576]
Hi, I'm using your lib to get notification, I'm getting them by using Firebase but I have problem
sometimes - randomly I have problem with registration of device on brand new installation (for example by removing app and reinstall it again) on devices

I did get 

```
Sending `FCMTokenRefreshed` with no listeners registered.
```

In my xcode logs and I can't get notification

I did put 

```
this.refreshTokenListener = FCM.on(FCMEvent.RefreshToken, (token) => {
  console.log('token received', token);
  Alert.alert('Alert', token);
});
```

inside index.ios.js before `AppRegistry.registerComponent('MyApp', () => app);`

but when this error comes I was not able to get notifications

my Podfile:

```
platform :ios, '9.0'

target 'App' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for App
  pod 'Firebase/Messaging'

  pod 'GoogleMaps'
  inherit! :search_paths
end

```

I did check 9.5.0, 9.4.0 and 9.3.0 and it occurs randomly on all versions
using react-native 0.46.4

I have 

```
  [FIRApp configure];
  [[UNUserNotificationCenter currentNotificationCenter] setDelegate:self];

```

Inside AddDelegate inside `- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions` before `return YES`

full logs from xcode:

```
2017-09-26 17:16:03.579 [info][tid:main][RCTCxxBridge.mm:186] Initializing <RCTCxxBridge: 0x16e2a660> (parent: <RCTBridge: 0x16e45390>, executor: (null))
2017-09-26 17:16:03.667 [warn][tid:main][RCTBridge.m:114] Class RCTCxxModule was not exported. Did you forget to use RCT_EXPORT_MODULE()?
2017-09-26 17:16:03.754 [info][tid:main][RCTRootView.m:302] Running application App ({
    initialProps =     {
    };
    rootTag = 1;
})
2017-09-26 17:16:06.461 [warn][tid:com.facebook.react.JavaScript] Warning: PropTypes has been moved to a separate package. Accessing React.PropTypes is no longer supported and will be removed completely in React 16. Use the prop-types package on npm instead. (https://fb.me/migrating-from-react-proptypes)
2017-09-26 17:16:06.833 [warn][tid:com.facebook.react.JavaScript] Warning: React.createClass is no longer supported. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement. (https://fb.me/migrating-from-react-create-class)
2017-09-26 17:16:07.488 [warn][tid:main][RCTEventEmitter.m:54] Sending `FCMTokenRefreshed` with no listeners registered.
2017-09-26 17:16:07.690 [warn][tid:com.facebook.react.JavaScript] Warning: Invalid argument supplied to oneOfType, expected an instance of array.
2017-09-26 17:16:07.736 [warn][tid:com.facebook.react.JavaScript] Warning: View.propTypes has been deprecated and will be removed in a future version of ReactNative. Use ViewPropTypes instead.
2017-09-26 17:16:07.795 [info][tid:com.facebook.react.JavaScript] register listener
2017-09-26 17:16:07.806 [info][tid:com.facebook.react.JavaScript] Running application "App" with appParams: {"rootTag":1,"initialProps":{}}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
```

**Comment by evollu** [comment]
It might be the refresh token is broadcasted before JS gets initialized?
Does `FCM.getFCMToken()` give you refreshed token?

**Comment by tobob** [comment]
yup, I get token, however using this token does not get me notifiaction on device, but I don't get error on Firebase console when trying to use this deviceToken

**Comment by evollu** [comment]
if you sent a notification to all devices in console, can the device receive it? want to confirm it gets registered with firebase correctly.

**Comment by tobob** [comment]
then I send to all devices I don't get notifications on this device with 'broken' token

**Comment by evollu** [comment]
sounds like the device isn't registered to firebase correctly. is swizzling working fine? you should see the swizzling log in xcode console. Have you granted right permission for notification?

**Comment by tobob** [comment]
I did request permisions in component that I render:

```
  async componentDidMount() {
    await FCM.requestPermissions();

    this.notificationListener = FCM.on(FCMEvent.Notification, async (notif) => {
      this.handleNotification(notif);
    });

    FCM.getInitialNotification().then((notif) => {
      if (Platform.OS === 'ios' && _.isObject(notif)) {
        notif.opened_from_tray = true;
      }
      this.handleNotification(notif);
    });
  }
```

I don't have any changes in Info.plist related with Firebase, however I don't get log about this "proxy" parametr

**Comment by tobob** [comment]
it turns out that in development mode - then we check for bundle to complete problem occurs offten

Now, I checking release version off app. 

I did event try to use FCM.deleteInstanceId() but then I'm not getting new token, is there is a method to reintialize Firebase?

**Comment by evollu** [comment]
@tobob reinstall the app

**Comment by tobob** [comment]
I did this about 75 times today

**Comment by tobob** [comment]
I know that after FCM.deleteInstanceId() I need to reinstall app, but this is not solution ;)

**Comment by evollu** [comment]
You will need to get a new firebase id and associate with APNS token after deleting the old one. It was done by swizzling and the repo doesn't bridge a method to get a new one. In short, don't use `FCM.deleteInstanceId()`

back to your original question, which is the refresh token getting called early. can you log it here https://github.com/evollu/react-native-fcm/blob/master/ios/RNFIRMessaging.m#L256 see what refresh token is?

**Comment by tobob** [comment]
I put breakpoint there, I get same token that I get by using getToken methods

**Comment by tobob** [comment]
but then I use this token I don't get notifications

**Comment by tobob** [comment]
also I get notification on `Sending `FCMNotificationReceived` with no listeners registered.` in react-native debugger

**Comment by evollu** [comment]
that's interesting, that mean you get the notification but it is not hook with JS listner

**Comment by tobob** [comment]
edit.. wait, it can be a clue

**Comment by tobob** [comment]
sorry, I probably open new app from notifiaction

**Comment by tobob** [comment]
but I see them then I open device logs

**Comment by tobob** [comment]
incoming message is for proxy slave that is *not* connected.

**Comment by evollu** [comment]
sorry I have no clue what those means or how to fix them.
still `Sending 'FCMNotificationReceived' with no listeners registered.` is more concerning. can you capture `[RNFIRMessaging didReceiveNotificationResponse:response withCompletionHandler:completionHandler];` in AppDelegate.m?

**Comment by evollu** [comment]
let's fix the global notification first. Looks like it is different from your original issue.

**Comment by tobob** [comment]
I put brakpoint on `[RNFIRMessaging didReceiveNotificationResponse:response withCompletionHandler:completionHandler];` and I did send global message to iOS devices, I get nothing, to check if breakpoint is working I did click into LocalNotification - and Xcode stops on this line, so I didn't get this remove notifications

**Comment by evollu** [comment]
so weird. your device is iOS10?

**Comment by tobob** [comment]
Yes, iPhone 5 with iOS10, I did test it agains iphone6plus and iphoneSE

**Comment by tobob** [comment]
I will check logs of device on app startup

**Comment by evollu** [comment]
you are using xcode 8 or 9? need to do a fix for 9 in appDelegate.m

also try to reproduce with quickstart-ios by firebase team. see if their native example works

**Comment by tobob** [comment]
Xcode 9, I did update 3 days ago

**Comment by tobob** [comment]
I did check it on quickstart-ios, it works smooth :P 🥇

**Comment by tobob** [comment]
what I think - this could be an issue with checking `Bundling 'index.ios.js'` to compleate

**Comment by tobob** [comment]
I did downgrade FirebaseInstanceID into 2.0.0 and I think it works better, I will let you know tommorow, I will check it agains other devices

**Comment by evollu** [comment]
there is a change need to be made in AppDelegate.m if you are using xcode 9 otherwise you should get a warning, did you fix it?

**Comment by tobob** [comment]
you mentioning about: https://stackoverflow.com/questions/41477241/react-native-xcode-upgrade-and-now-rctconvert-h-not-found ?

**Comment by evollu** [comment]
no I mean this guy
`- (void)userNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void (^)(void))completionHandler`

the type of completionHandler is changed

**Comment by tobob** [comment]
I did update this type but I don't see any changes, but maybe it will help in future, however downgrade to FirebaseDeviceId resolve my problems, even if I get `Sending `FCMTokenRefreshed` with no listeners registered.` when app is loading Im still able to get notifications on device

**Comment by tobob** [comment]
problem also occurs mostly in debugging env, when app is waiting for index.ios.js

**Comment by tobob** [comment]
solution for me:

```
  pod 'FirebaseInstanceID', "2.0.0"
```

**Comment by evollu** [comment]
@tobob can you explain what `pod 'FirebaseInstanceID', "2.0.0"` does? What is the default version coming with Messaging?

**Comment by tobob** [comment]
in spec I see that there is ~> 2.0

https://github.com/CocoaPods/Specs/blob/master/Specs/2/d/6/FirebaseMessaging/2.0.3/FirebaseMessaging.podspec.json

**Comment by evollu** [comment]
locking yourself in 2.0.0 may cause other problems. fire a bug to firebase?

**Comment by tobob** [comment]
Yesterday when I was looking around I found 
https://stackoverflow.com/questions/46391818/fcm-push-notifications-do-not-work-on-ios-11

I tired it, it works for me

**Comment by tobob** [comment]
@evollu I think that you can fire bug to firebase when more users will come with same problem and source of problem will be more known

**Comment by evollu** [comment]
Thanks for your link. looks like Firebase has already fixed the bug in coming release. For now we should lock version to 2.0.0 as you did

**Comment by antoinerousseau** [comment]
I still get a `Sending 'FCMTokenRefreshed' with no listeners registered.` with a fresh install, even with FirebaseInstanceID 2.0.4, and even though I have `FCM.on(FCMEvent.RefreshToken, (token) => {...})` directly in an included file (thus executing immediately)

**Comment by evollu** [comment]
@antoinerousseau it is possible that you get `Sending 'FCMTokenRefreshed' with no listeners registered.` because native sdk still runs before JS boots up.
You should get new token from `getFCMToken`

**Comment by antoinerousseau** [comment]
Yes it's working but that warning shouldn't show up

**Comment by evollu** [comment]
@antoinerousseau any PR that fixes this is welcomed. My idea is to move `[FIRApp configure]` into module init. but it could cause compatibility issue with other firebase rn modules

**Comment by antoinerousseau** [comment]
@evollu I tried but I couldn't find this warning in the source code (and I only know about JS dev)

**Comment by evollu** [comment]
In `InstanceIdService.java`, replace `onTokenRefresh` with following and try
```
@Override
    public void onTokenRefresh() {
        // Get updated InstanceID token.
        String refreshedToken = FirebaseInstanceId.getInstance().getToken();
        Log.d(TAG, "Refreshed token: " + refreshedToken);

        // Broadcast refreshed token

        Intent i = new Intent("com.evollu.react.fcm.FCMRefreshToken");
        Bundle bundle = new Bundle();
        bundle.putString("token", refreshedToken);
        i.putExtras(bundle);

        final Intent message = i;

        ReactInstanceManager mReactInstanceManager = ((ReactApplication) getApplication()).getReactNativeHost().getReactInstanceManager();
        ReactContext context = mReactInstanceManager.getCurrentReactContext();
        // If it's constructed, send a notification
        if (context != null) {
            context.sendOrderedBroadcast(message, null);
        } else {
            // Otherwise wait for construction, then send the notification
            mReactInstanceManager.addReactInstanceEventListener(new ReactInstanceManager.ReactInstanceEventListener() {
                public void onReactContextInitialized(ReactContext context) {
                    context.sendOrderedBroadcast(message, null);
                }
            });
        }
    }
```

**Comment by evollu** [comment]
can't do anything with iOS now

**Comment by suhabaobaid** [comment]
Hey! Any updates with Sending 'FCMTokenRefreshed' with no listeners registered warning?

**Comment by evollu** [comment]
@suhabaobaid it might happen when you just start the device because the token refreshed before react is ready. but when you call getFCMToken again in javascript it should return the new token

**Comment by EduardJS** [comment]
@evollu so what you're saying is that we shouldn't worry about that warning ?

**Comment by evollu** [comment]
@EduardJS yes. as long as you only see the warning on launch
