### ISSUE TITLE
Notifications not received if app is in the background iOS 11

### ISSUE THREAD

**Issue by gurmukhp** [evollu/react-native-fcm#577]
@evollu 

RN: 0.48.4
react-native-fcm: 9.5.0

What device are you using? iPhone 7+ iOS 11

Notifications are received (but not shown) when app is in foreground.

When app is in background, no notifications are received. However they are received when the app is bought into the foreground.

```
FCM.on(FCMEvent.Notification, async (notif) => {
  console.log('got a notification', );
});
```

Sample message:
```
notification: {
    title:"Remote Push Notification Test",
    body:"This has been a test of XXXXXXX's remote push notification system.",
    screen:"dev",
    big_text:"This has been a test of XXXXXXX's remote push notification system.",
    icon:"ic_notif",
    largeIcon:"ic_notif_launcher",
    color:"#497EE3",
    vibrate:"300",
    sound:"notification",
    priority:"High",
    badge:"0"
}
```
```
{
  contentAvailable: true,
  priority: 'high'
}
```

- .p8 file is uploaded to Firebase console.
- Background fetch and background mode is enabled in xCode.
- Notifications are enabled and set to temporary in settings.
- App has been reinstalled many times

UPDATE
I've checked out the quickstart which worked immediately! The problem was with the callback handler for iOS 11.

```
- (void)userNotificationCenter:(UNUserNotificationCenter *)center
didReceiveNotificationResponse:(UNNotificationResponse *)response
#if defined(__IPHONE_11_0)
         withCompletionHandler:(void(^)(void))completionHandler {
#else
         withCompletionHandler:(void(^)())completionHandler {
#endif
```

**Comment by evollu** [comment]
great.. will update

if there other `#if defined(__IPHONE_11_0)`?

**Comment by evollu** [comment]
done
