### ISSUE TITLE
android getInitialNotification error

### ISSUE THREAD

**Issue by kirillpisarev** [evollu/react-native-fcm#578]
Hi! After update to react-native-fcm 9.6.0 i get this error on android device (android 5.1):

<img src="https://user-images.githubusercontent.com/1886908/30905309-19ffdd18-a37d-11e7-8917-c8de967f263a.png" width="60%" />

tmp workaround is to change FIRMessagingModule code:

```
if(activity == null || activity.getIntent().getAction().equals("android.intent.action.MAIN")){
     promise.resolve(null);
     return;
}
```
to 

```
if(activity == null || activity.getIntent().getAction() == null || activity.getIntent().getAction().equals("android.intent.action.MAIN")){
    promise.resolve(null);
    return;
}
```

I am not a strong android developer and i don't know why `activity.getIntent().getAction()` could be null so i will not create PR cuz i think that the problem is deeper.

RN version is 0.44.0 if it matters

**Comment by evollu** [comment]
that's a bug, will fix it ASAP

**Comment by evollu** [comment]
fixed v9.6.1

**Comment by kirillpisarev** [comment]
Thank you for the quick response and great lib! Could you please look at my the comment to your [commit](https://github.com/evollu/react-native-fcm/commit/de31a2c12962a73110851ed4a8796fc390435fe6#diff-c04acb3238c7458755defae08932ece4R306)

**Comment by evollu** [comment]
you are right..
