### ISSUE TITLE
ios 10 only receive notification on foreground but not on background, ios 8 nothing happen both foreground and background

### ISSUE THREAD

**Issue by nhuthan** [evollu/react-native-fcm#579]
any one has problem like me?

**Comment by evollu** [comment]
can you reproduce with example project?

**Comment by nhuthan** [comment]
i tried with your example but not success.
i changed team, googleservice-info.plist, firebase api key, created apn key, profile, app id... but cannot receive notification (ios 10.2) both background and foreground (show_in_foreground = true).
local notification working fine, remote notification send success but not receive:
`Send notification response Response {type: "default", status: 200, ok: true, statusText: undefined, headers: Headers, …}
Send data response Response {type: "default", status: 200, ok: true, statusText: undefined, headers: Headers, …}`

**Comment by evollu** [comment]
you are using actual device right?

**Comment by nhuthan** [comment]
yes sure, i run on my iphone 6.
when i log response.json() it look like
![image](https://user-images.githubusercontent.com/12423709/30945066-1028030c-a426-11e7-8031-41311422eda7.png)

i tried make a breakpoint on willPresentNotification but it not stop here. Also i get a warning on didReceiveNotificationResponse, what wrong?
![image](https://user-images.githubusercontent.com/12423709/30945170-c9291cb0-a426-11e7-8f2e-5181a81b51b4.png)

**Comment by evollu** [comment]
ahh, you need to fix the method. I've updated the correct method in readme. it is xcode 9 change

**Comment by nhuthan** [comment]
i've updated AppDelegate.m like latest readme's change but still not receive notification.
in xcode log i get `FIRMessaging Remote Notifications proxy enabled, will swizzle remote notification receiver handlers. Add "FirebaseAppDelegateProxyEnabled" to your Info.plist and set it to NO`. Should i set it to NO?
I tried send notification via firebase console to app fcm token but nothing happen.
![image](https://user-images.githubusercontent.com/12423709/30947537-8be44416-a434-11e7-8a6b-52230e9c264a.png)

**Comment by evollu** [comment]
don't set it to be NO

sent 0 might mean you haven't registered successfully?

**Comment by nhuthan** [comment]
i tried quickstart-ios by firebase, it working fine.

**Comment by nhuthan** [comment]
i removed all profiles and let xcode manage them automatic and  now example is woking.
i tried same thing for my app but still not work on background mode :(

**Comment by evollu** [comment]
So if example is working, it should be some setup up issue.
`ic_notification` did you add corresponding file?
if you try with the bare minimum notification does it work?

**Comment by evollu** [comment]
check this
https://github.com/firebase/quickstart-ios/issues/327#issuecomment-331782299

**Comment by nhuthan** [comment]
it's helpful for me

thank you very much
