### ISSUE TITLE
How can I access the notification data

### ISSUE THREAD

**Issue by miczed** [evollu/react-native-fcm#58]
Hi

First of all I'd like to thank you for developing this project! I am currently getting started with react-native / firebase development and so far I am amazed by the amount of available open source code and the community.

However since I am only getting started I am quite confused with the whole push notification / FCM concept.

I followed [this](https://facebook.github.io/react-native/docs/pushnotificationios.html) tutorial and the one in the readme of this repo. I am able to send notifications from the firebase console and they are displayed as a notification on the **iPhone** but only if the app is **running in the background**. 
- How can I access the content of the notification when the user clicks on a notification? 
- Or when the app is running in the foreground?
- Do I need to use the [PushNotificationIOS](https://facebook.github.io/react-native/docs/pushnotificationios.html) methods / events?
- What does "IOS will receive notificaton from FCMNotificationReceived event" mean? 
- How can I set the "content_available" flag to true in the Firebase Console?

I've read the readme and had a look at your code sample but couldn't figure it out on my own.
Any help or a link for further reading would be highly appreciated.

Thanks,
Michael

**Comment by evollu** [comment]
- How can I access the content of the notification when the user clicks on a notification?
If app is closed, you will get it in initialData, if app is open/in background, you will get it through notification listener

- Do I need to use the PushNotificationIOS methods / events?
no, FCM handles for you

- What does "IOS will receive notificaton from FCMNotificationReceived event" mean?
it means here ```FCM.on('notification'```

- How can I set the "content_available" flag to true in the Firebase Console?
there is an `advanced` panel

**Comment by miczed** [comment]
Thank you evollu for your response.

I implemented  `FCM.on('notification',this._onNotification);` and tried to log the notification to the console which didn't work. The function is called and I am passing `notif` as a parameter however if I am trying to access `notif.data` or `notif.notification` I am getting `undefined`. 

    _onNotification(notif) {
        console.log('Got Notification!');
        console.log(notif.data);
        console.log(notif.notification);
    }

I am sorry if I am getting something wrong but some example code would really help me or is there another documentation somewhere?

**Comment by evollu** [comment]
console.log(notif) to see what is inside. Data structure is different from your payload sent to FCM server

**Comment by miczed** [comment]
Ok, that did the trick, thank you very much! I could access the data with `notif.aps.alert.title` and `notif.aps.alert.body`.

One more question: How and when can I access `FCM.initialData`? 
I tried to log it to the console in my `componentDidMount()` function but I am getting `undefined`.

**Comment by evollu** [comment]
it contains data when you init the application by **clicking push notification**

**Comment by evollu** [comment]
if you want to add some logic based on notification, use `data` object or `click_action` field. Don't rely on title and body because Android version doesn't supply that

**Comment by miczed** [comment]
Ok, thanks again and thanks for the information about `data` and `click_action`.

So when my app is closed and I click on a notification the app is opened and I can access the data. But what happens when the user opens the app after he got a notification but **doesn't actually click on the notification**? Is there a way to catch that case too?

**Comment by evollu** [comment]
nope :)
what are you trying to do with the notification?

**Comment by miczed** [comment]
I need to send a message to the user whenever some event on the server happens and the user should be able to read the message even when he opens the app without clicking on the notification. 

So basically the following is possible:

- Display the message when the app is in the foreground
- Display the message when the app is in the background and the user clicks on the notification
- Display the message when the app was closed and the user clicks on the notification

and the following isn't:

- Display the message when the app was closed and is opened by clicking on the app icon

So in the latter case the information is lost?

**Comment by evollu** [comment]
I don't know any app is doing the last case. If you have received multiple notifications regarding messages, which message do you show then? What if user cleared all notifications before opening the app?

**Comment by miczed** [comment]
I thought apps like WhatsApp / Telegram are doing it like this but I guess they have some additional logic running in the app to fetch the data from the server. I thought I could send all the data over push notifications but obviously that's not possible.

So the data from the notification is actually lost when the user deletes it or opens the app without clicking it? Sounds kinda strange to me but if it is that way then I'll need to find another way to inform my user in the app itself after opening it.

**Comment by evollu** [comment]
right, that is the case. You can consider using background sync

**Comment by studiobrain** [comment]
Pardon the interruption!  By the way, excellent package, and much appreciated!  

I am having a similar issue, so I wanted to bring some of my own experiences to maybe shed some new light.

currently via Android:
```componentDidMount() {
    FCM.on('notification', (notif) => {
      console.log(notif)  //{ Item: 'cool', Another: 'cooler' }
    })
  }``` 
logs only the custom data (key/value pairs).  Is it not possible to retrieve the `Message text` and `Message label` via Android?  

I am using only `react-native log-android` for logs, so possibly it doesnt give all of the params from `notif`?  Also, I am only receiving the log, no push notification received, but that could be due to  running in develop mode (device plugged in) and not as an actual application.  Any direction or point of reference you can offer is greatly appreciated, so thanks in advance and thanks for the hard work!

**Comment by evollu** [comment]
it is possible only when app is in foreground, otherwise no. Notification data is processed by FCM and gone.

**Comment by studiobrain** [comment]
Thanks for the quick response!  I have the app in the foreground but the log is still only the portion sent from firebase advanced options/custom data.  Is there a way to grab: `onMessageReceived()` response, or is there something more I am missing?

**Comment by evollu** [comment]
I didn't expose them to JavaScript because I didn't find usage of it. you can get it in message.getNotification().getTitle()

**Comment by evollu** [comment]
@studiobrain if you need it, a pull is welcomed

**Comment by studiobrain** [comment]
Sorry, I got caught up in another project (day job stuff).  I would be glad to.  Let me get it out to you.  I havent been able to get the title or body via:
`
javascript
@Override
    public void onMessageReceived(RemoteMessage remoteMessage) {
        Log.d(TAG, "Remote message received");
        Intent i = new Intent("com.evollu.react.fcm.ReceiveNotification");
        i.putExtra("title", remoteMessage.getNotification().getTitle());
         i.putExtra("body", remoteMessage.getNotification().getBody());
        sendOrderedBroadcast(i, null);
    }
`

**Comment by evollu** [comment]
that looks good. can you put the parse logic into module.java file and put the information into the fcm property together with action?

**Comment by studiobrain** [comment]
Are you referencing:
```javascript
getReactApplicationContext().registerReceiver(new BroadcastReceiver() {
            @Override
            public void onReceive(Context context, Intent intent) {
            if (getReactApplicationContext().hasActiveCatalystInstance()) {
                RemoteMessage message = intent.getParcelableExtra("data");
                WritableMap params = Arguments.createMap();
                if(message.getData() != null){
                    Map data = message.getData();

most notably:
```javascript
Map data = message.getData();

**Comment by sajjad26** [comment]
Hi, I am using this with ReactNative 0.31 on Android and the `FCM.on('notification', (notif) => { console.log(notif) })`
is simply not working at all, i have tried in with app in the background, foreground or killed. However the FCM.initialData seems to be working as it receives the data when the app is not in foreground and the notification is clicked. This is my manifest file, please point me in the right direction if I am doing something wrong.
```xml
<!-- React Native FCM -->
        <intent-filter>
          <action android:name="fcm.ACTION.HELLO" />
          <category android:name="android.intent.category.DEFAULT" />
        </intent-filter>
        <service android:name="com.evollu.react.fcm.MessagingService">
          <intent-filter>
            <action android:name="com.google.firebase.MESSAGING_EVENT"/>
          </intent-filter>
        </service>
        <service android:name="com.evollu.react.fcm.InstanceIdService" android:exported="false">
          <intent-filter>
            <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
          </intent-filter>
        </service>
        <!-- React Native FCM END -->
```
```javascript
componentDidMount(){
    var self = this;
    FCM.getFCMToken().then(token => {
      console.log(token) // works
    });
    FCM.on('notification', (notif) => { console.log(notif) }); // does not work
    console.log(FCM.initialData); // works
  }
```

**Comment by evollu** [comment]
@sajjad26 `FCM.on('notification'` only gets triggered when you have `data` property. I assume you are sending with firebase console which only has `notification` property by default?

**Comment by sajjad26** [comment]
@evollu no I am sending the extra data from the advanced tab in the firebase console. Plus I was using gcm push notifications before and I have a bunch of those tokens, Will those old tokens work with firebase or not, off topic but just asking since you are the expert :)

**Comment by evollu** [comment]
sorry for so late reply. GCM token are different from FCM token.
closing this. reopen if you have further questions

**Comment by kaberibasu** [comment]
I dont know what i am doing wrong, but I am not getting any data when i click on notification in android.
My setting is-
`FCM.requestPermissions(); // for iOS
        FCM.getFCMToken().then(token => {
            let tokenData: FirebaseToken = {
                firebaseToken: token
            };
            storeFireBaseToken(tokenData).then((done) => {
            });
            console.log(token);
            // store fcm token in your server
        });
        FCM.getInitialNotification().then(notif => {
            // for android only
            console.log(notif);

        });

        this.notificationListener = FCM.on(FCMEvent.Notification, async (notif) => {
            // there are two parts of notif. notif.notification contains the notification payload, notif.data contains data payload
            if (notif.local_notification) {
                // iOS only
                // this is a local notification
            }
            if (notif.fcm) {
                FCM.presentLocalNotification({                               // (optional for instant notification)
                    title: notif.senderName,                     // as FCM payload
                    body: notif.fcm.body,                    // as FCM payload (required)
                    sound: "default",                                   // as FCM payload
                    priority: "high",                                   // as FCM payload// Android only, LED blinking (default false)
                    show_in_foreground: true                                 // notification when app is in foreground (local & remote)
                });
            }
        });
        this.refreshTokenListener = FCM.on(FCMEvent.RefreshToken, (token) => {
            console.log(token);
            // fcm token may not be available on first load, catch it here
        });`

When I recieve notification, I get a call here "FCM.on(FCMEvent.Notification, async (notif)" and in notif i get data. have to implement this-
`FCM.presentLocalNotification({                               // (optional for instant notification)
                    title: notif.senderName,                     // as FCM payload
                    body: notif.fcm.body,                    // as FCM payload (required)
                    sound: "default",                                   // as FCM payload
                    priority: "high",                                   // as FCM payload// Android only, LED blinking (default false)
                    show_in_foreground: true                                 // notification when app is in foreground (local & remote)
                });` to show a local notification when ap is foreground.

But when user clicks on the notification, whether the app is in BACKGROUND or FOREGROUND or KILLED, i get a call in getInitialNotification, and in its callback, i get no data.
@evollu please tell me what I am doing wrong.

**Comment by MbF-Sathya** [comment]
how can i access the response data in react native android 

`firebase.messaging().onMessage((message) => {
                    alert(2)
                    console.log(message);
                    AsyncStorage.setItem('xxxxId', message._data.xxxxId.toString());
                    setTimeout(() => {
                        Actions.screeThree({type:'replace'});
                    }, 500);
                });`

**Comment by evollu** [comment]
`firebase.messaging()` you are using react-firebase-stack?

this is how to listen on events using this library.
```
FCM.on(FCMEvent.Notification, (notif)=>{
  //logic
}
```

**Comment by MbF-Sathya** [comment]
@evollu did you see my stack link... for android is this right method to handle data? for iOS its coming exactly what i expect....

**Comment by evollu** [comment]
@MbF-Sathya this library is `react-native-fcm`, not `react-native-firebase`

**Comment by MbF-Sathya** [comment]
@evollu so i am using react-native-firebase npm
can i get any reference for this?

**Comment by evollu** [comment]
@MbF-Sathya https://github.com/invertase/react-native-firebase

**Comment by prasanthyejje** [comment]
i'm using [https://github.com/evollu/react-native-fcm](url) for FCM. Now i am able to receive notifications but i want to prevent the notifications displaying in mobile notification bar ..how Can i do this..
please help me @evollu

**Comment by evollu** [comment]
@prasanthyejje what OS

**Comment by prasanthyejje** [comment]
@evollu 
Targeting Mobile OS: Android
RN version:0.51
My PC :Windows7, 64 bit,
Dependencies: compile 'com.google.firebase:firebase-core:11.8.0'

**Comment by evollu** [comment]
if you want to not showing the banner, you can set `priority: 'low'`
if you don't want it to show in notification tray, I don't know... perhaps delete it after you receive it?

**Comment by prasanthyejje** [comment]
thanks @evollu for your response . And one more thing is I'm not able to catch the notification event when the app is in dead state.(now receiving the notifications when app is in background and foreground state),
please help me to solve this issue..

**Comment by evollu** [comment]
yes, though `sound` property

**Comment by Keyur-Rao** [comment]
Issue: I was getting remoteData from messaging().getInitialNotification() and messaging().setBackgroundHandler() also not register.
solution: https://github.com/react-native-firebase, @react-native-firebase/messaging is conflict with https://github.com/notifee i simplly remove notifee module and it's works for me..
