### ISSUE TITLE
Notification is not removed using removeDeliveredNotification on Android

### ISSUE THREAD

**Issue by madox2** [evollu/react-native-fcm#586]
Notification is not removed from notification center when `tag` property is specified:
```javascript
FCM.presentLocalNotification({
  id: 'some_id', // (optional for instant notification)
  title: 'My Notification Title', // as FCM payload
  body: 'My Notification Message', // as FCM payload (required)
  tag: 'some_tag', // Android only
  show_in_foreground: true,
})
// ...
FCM.removeDeliveredNotification('some_id')
```

It works fine without `tag` property. If this is not a bug, it would be nice to state it in documentation.

**Comment by evollu** [comment]
it is a bug. seems tag is part of the id

**Comment by madox2** [comment]
@evollu since notification id can be any string, I find it also redundant. However removing tag support might be breaking change if somebody use it.

**Comment by evollu** [comment]
it will release it as v10 and state breaking change in release. It is buggy today anyway

**Comment by evollu** [comment]
released v10
