### ISSUE TITLE
ios 8 foreground not show banner, android background not show banner

### ISSUE THREAD

**Issue by nhuthan** [evollu/react-native-fcm#587]
ios 10 working properly but ios 8 foreground and android (7) background only show on tray not show banner. 
Please guide.

payload:
`notif = {
   id = 123,
   title = "title",
   content = "content",
   badge = 1
}

payload = {
   collapse_key = "xxx",
   time_to_live = 864000,
   content_available = true,
   notification =
   {
      id = notif.Id,
      color = "#66BB6A",
      title = notif.title,
      body = notif.content,
      icon = "ic_notification",
      priority = "high",
      show_in_foreground = true,
      content_available = true,
      badge = notif.badge,
      sound = "default",
   },
   data = notif,
   registration_ids = [token array],
   priority = "high",
};`

**Comment by evollu** [comment]
iOS <= 9  doesn't show foreground banner when remove notification comes. system limit
Android doesn't show banner because FCM doesn't support it. you have to use "custom_notification", check readme

**Comment by nhuthan** [comment]
@evollu 
I using custom_notification in data and remove notification in payload now it work ok in foreground and background but not work when app killed. Should i send both payload, one for notification and one for custom_notification?

**Comment by nhuthan** [comment]
i tried, if send both will not show banner in background
