### ISSUE TITLE
Is tray notification click works still on Android?

### ISSUE THREAD

**Issue by chrusart** [evollu/react-native-fcm#588]
After doing 'filter out notification event from clicking icon' the intent is not send anymore,
action is the same for clicking the app icon and the notification banner in notifications tray.
Normally when user clicks the notification i should get it in app, right?

Is it the same for you or it's my side?

1. RN 0.48.3
2. Android 7
3. app running in background

Only difference is in intent flags.
icon clicked: (0x10600000), whatever, there is a notification in tray or not
FLAG_ACTIVITY_NEW_TASK
FLAG_ACTIVITY_BROUGHT_TO_FRONT
FLAG_ACTIVITY_RESET_TASK_IF_NEEDED
notification clicked: (0x14400000)
FLAG_ACTIVITY_NEW_TASK
FLAG_ACTIVITY_CLEAR_TOP
FLAG_ACTIVITY_BROUGHT_TO_FRONT

**Comment by chrusart** [comment]
Ok, when you run app using launcher icon, there is no notification data in intent (extra or other stuff)
```{"opened_from_tray":1,"fcm":{"action":"android.intent.action.MAIN"},"profile":0} ```
, when user clicks notification on tray there is a notification data in intent extra (at least for me).
For me somehow app opened from icon have this "fcm" stuff which shouldn't be there, it not comes from firebase, right? have to go home now, will look at weekend at it a little.

**Comment by nhuthan** [comment]
add click action to payload and AndroidManifest.xml help me resolve problem

![image](https://user-images.githubusercontent.com/12423709/31046054-21958388-a61c-11e7-8d5f-7682c2b599bf.png)


![image](https://user-images.githubusercontent.com/12423709/31046059-3e279dba-a61c-11e7-8a0a-7ec9721ed437.png)

**Comment by evollu** [comment]
@chrusart when you click banner, the action is `null` rather than `android.intent.action.MAIN` so it shouldn't filter out user click action

**Comment by evollu** [comment]
bring back main intent in v9.7.1

**Comment by chrusart** [comment]
Yeah, I'm using Samsung.

**Comment by Uysim** [comment]
I don't know why we close this issue. I still face the same issue

**Comment by sivadurgar3** [comment]
There is other way to provide click action for the notification.
You could use PendingIntent and get the notification in your launcher activity.

**Comment by Johncy1997** [comment]
![screenshot from 2019-01-21 18-06-39](https://user-images.githubusercontent.com/25324938/51475061-538cef80-1da7-11e9-8440-9a09c7cff7f0.png)
I am getting notification is not defined error under getInitialNotification() method.The body&title are undefined in notification
