### ISSUE TITLE
getInitialNotification is not firing on android 7.0

### ISSUE THREAD

**Issue by kirillpisarev** [evollu/react-native-fcm#589]
Hello! 
In `FIRMessagingModule` in `getInitialNotification` method you filter intents by "android.intent.action.MAIN" action to cut off false positive calls. But on samsung galaxy s8 when I launch my app by pressing a notification from the firebase I get null in this method in js. I don't know why but on this phone `intent.getAction().equals("android.intent.action.MAIN")` is true.

RN 0.44.0
android 7.0

**Comment by chrusart** [comment]
Similar?
#588

**Comment by kirillpisarev** [comment]
yes you right
