### ISSUE TITLE
Firebase sdk dependencies

### ISSUE THREAD

**Issue by mizinin** [evollu/react-native-fcm#59]
Is it necesery to add `compile "com.google.firebase:firebase-core:9.2.1"` or `compile 'com.google.firebase:firebase-messaging:9.2.1'` in build.gradle?
Same question for react-native-firebase-analytics.

Thanks.

**Comment by mizinin** [comment]
I asked the question because got this:
`google-services plugin could not detect any version for com.google.android.gms or com.google.firebase, default version: 9.0.0 will be used.
please apply google-services plugin at the bottom of the build file.`

**Comment by evollu** [comment]
does adding it removing the warning?
I have crash report compile with specific version in gradle myself

**Comment by holyxiaoxin** [comment]
I did add those.

**Comment by evollu** [comment]
@mizinin are you good if I close the issue?

**Comment by mizinin** [comment]
I added `compile "com.google.firebase:firebase-core:9.2.1"` to build.gradle. fcm and analytics works well and project compiles without any warning
