### ISSUE TITLE
Invalid headers paths in iOS causing build error in RN > 0.47

### ISSUE THREAD

**Issue by dotansimha** [evollu/react-native-fcm#593]
Issue caused when using RN > 0.47 and using new `CxxBridge` instead of `BatchedBridge`. 

The issue was noticed here before in https://github.com/evollu/react-native-fcm/issues/524 

The actual issue is the defined headers path of the XCode project.

The current implementation uses: 
https://github.com/evollu/react-native-fcm/blob/master/ios/RNFIRMessaging.xcodeproj/project.pbxproj#L226-L228

But it MUST be:
```
					"$(SRCROOT)/../../react-native/React/**",
					"$(SRCROOT)/../../../node_modules/react-native-fcm/ios/**",
					"$(SRCROOT)/../../../node_modules/react-native-firestack/ios/**",
```

Otherwise, it's not possible to compile for RN > 47 with the new bridge. 

The actual solution was first introduced by Facebook team as a solution for the same error with another package: https://developers.facebook.com/bugs/111079162900447/ (See the comment by Xiao Liang)

Verified it now on my project, with XCode 11, MacBook High Sierra, iOS >= 10, RN 0.48.4 (and 0.40-rc6).

**Comment by evollu** [comment]
i'm not 100% understand the fix. is that adding `"$(SRCROOT)/../../../node_modules/react-native-fcm/ios/**"`?

**Comment by dotansimha** [comment]
And removing  `"$(SRCROOT)/../../../ios/**",` @evollu

**Comment by evollu** [comment]
all the imports here is not to include react-native-fcm but to include header file from Firebase SDK. 

however since the repo now relies on frameworks itself we can remove `$(SRCROOT)/../../../ios/**` in header search path

**Comment by evollu** [comment]
@dotansimha can you try master branch and see if it solves your issue?

**Comment by dotansimha** [comment]
@evollu 
Not sure why, now I am getting this errors:
![image](https://user-images.githubusercontent.com/3680083/31064823-b820a012-a748-11e7-8985-613019744249.png)

When trying to run on a device / simulator / archive...

**Comment by dotansimha** [comment]
Removing `$(SRCROOT)/../../../ios/**` from the framework path and pointing it to: `$(SRCROOT)/../../../ios/Pods` (recursive) works.

**Comment by dotansimha** [comment]
@evollu 
I managed to use the latest release of the package from NPM, using the podspec, instead `react-native link`:
```
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'react-native-fcm', :path => '../node_modules/react-native-fcm'
``` 

Somehow, when the project is loaded via Pod project, everything is fine...

**Comment by evollu** [comment]
i removed $(SRCROOT)/../../../ios/** from header search path so it shouldn't search for it anymore. are you using the master's branch? no any released npm version

**Comment by dotansimha** [comment]
I tried the master, but it looks like we need to remove `$(SRCROOT)/../../../ios/**` from the Frameworks search path as well

**Comment by evollu** [comment]
updated master, check?

**Comment by dotansimha** [comment]
Thanks @evollu !
