### ISSUE TITLE
Number is not showing up in local notification on Android

### ISSUE THREAD

**Issue by madox2** [evollu/react-native-fcm#596]
I am using local notifications and I want to set android only property number (e.g. `number: 10`). I suppose it should display the number in bottom-right corner of notification, but it does not. It does not work when app is running both in foreground and background.

RN: 0.42.3
react-native-fcm: 9.7.0 
Running on Android device 6.0.1

**Comment by evollu** [comment]
it is a bug will fix

**Comment by evollu** [comment]
@madox2 fixed in master branch. Can you verify?

**Comment by madox2** [comment]
@evollu I can confirm that it's working on Andoroid with master branch. Thank you for such prompt feedback and fix!

**Comment by evollu** [comment]
released in v10
