### ISSUE TITLE
Way to get notifications from tray when app is opened?

### ISSUE THREAD

**Issue by sujayjaju** [evollu/react-native-fcm#597]
1. RN 0.48 RN-FCM 9.7.2
2. Device: Android Emulator and Android 5 Mobile
3. App running in background

[Question]
If I have a notification in the tray and I open the app without clicking on the notification - is there a way to read the notifications in the tray? Right now the notification stays in the tray.

**Comment by ShongSu** [comment]
Have you try call `removeAllDeliveredNotifications` in `FCM.on(FCMEvent.Notification`

**Comment by sujayjaju** [comment]
I will try that - but I need to process those notifications (read their data) before dismissing those.

**Comment by evollu** [comment]
dup of #306

**Comment by PreethaRajakumar** [comment]
remove notification section  and add   "content_available": true....it will work
I have  attached my code
{
  
     "to":"yyyyyyyyyyyyyyyy",

  "content_available": true,
  "data":{
    "badge":3,
          "custom_notification": {
              "body": "test",
              "sound": "default",
              "priority": "high",
              "show_in_foreground": true
            },
            "title":"Alert"
  }

}
