### ISSUE TITLE
Not getting notification in app

### ISSUE THREAD

**Issue by Sarita-tnex** [evollu/react-native-fcm#598]
React-native version of App is 0.47.1
react-native-fcm version :9.7.2
Not getting notification in any state of app  in ios App.
Device: Iphone 6
Followed all the steps for installation using cocopod  approach.
Uploaded APN Push certificates on Firebase project also .

 import FCM, { FCMEvent, RemoteNotificationResult, WillPresentNotificationResult, NotificationType } from 'react-native-fcm';
FCM.requestPermissions(); // for iOS
this.notificationListener = FCM.on(FCMEvent.Notification, (notif) => {
  if (notif.local_notification) {
        //this is a local notification
      }
      if (notif.opened_from_tray) {
        //app is open/resumed because user clicked banner

      }
      //await someAsyncCall();

      if (Platform.OS === 'ios') {
        //optional
        //iOS requires developers to call completionHandler to end notification process. If you do not call it your background remote notifications could be throttled, to read more about it see the above documentation link. 
        //This library handles it for you automatically with default behavior (for remote notification, finish with NoData; for WillPresent, finish depend on "show_in_foreground"). However if you want to return different result, follow the following code to override
        //notif._notificationType is available for iOS platfrom
        switch (notif._notificationType) {
          case NotificationType.Remote:
            notif.finish(RemoteNotificationResult.NewData) //other types available: RemoteNotificationResult.NewData, RemoteNotificationResult.ResultFailed
            break;
          case NotificationType.NotificationResponse:
            notif.finish();
            break;
          case NotificationType.WillPresent:
            notif.finish(WillPresentNotificationResult.All) //other types available: WillPresentNotificationResult.None
            break;
        }
      }
    });
    this.refreshTokenListener = FCM.on(FCMEvent.RefreshToken, (token) => {
      console.log(token)
      // fcm token may not be available on first load, catch it here
    });

**Comment by evollu** [comment]
can you reproduce with example project?

**Comment by titusjoyson** [comment]
I am facing the same issue but i was able to receive notification in android device but in ios device the controle is not even going inside the function ` FCM.on(FCMEvent.Notification, (notif) =>`  function

React-native version 0.47.1
react-native-fcm version 9.7.2

Firebase SDKs version

           CocoaPod           | Version
----------------------------- | -------
Firebase                      | 4.2.0
FirebaseAnalytics             | 4.0.3
FirebaseAuth                  | 4.2.0
FirebaseCore                  | 4.0.7
FirebaseCrash                 | 2.0.2
FirebaseDatabase              | 4.0.3
FirebaseDynamicLinks          | 2.1.0
FirebaseInstanceID            | 2.0.3
FirebaseInvites               | 2.0.1
FirebaseMessaging             | 2.0.3
FirebasePerformance           | 1.0.5
FirebaseRemoteConfig          | 2.0.3
FirebaseStorage               | 2.0.2
GTMOAuth2                     | 1.1.5
GTMSessionFetcher             | 1.1.11
Google-Mobile-Ads-SDK         | 7.24.0
GoogleAPIClientForREST        | 1.3.0
GoogleSignIn                  | 4.1.0
GoogleToolboxForMac           | 2.1.1
Protobuf                      | 3.4.0
leveldb-library               | 1.18.3
nanopb                        | 0.3.8

can you help @evollu

**Comment by Sarita-tnex** [comment]
@evollu 

I reproduced this Issue in Examples/simple-fcm-client example of react-native-fcm.This Issue also reproduces on below versions for ios.However I am getting local Notofication and recieving token from FCM but not getting remote notifications
 "react-native": "^0.47.2",
    "react-native-fcm": "^9.6.2"

Devices tested Iphone 5s and Iphone 6

**Comment by thomas-oo** [comment]
Same issue. Iphone 7 with iOS 11. FCM.on is not being called when I send a remote notification while the app is in foreground. The notification payload has notification, data, priority=high, and badge=1. Furthermore, sending the same notification payload works is received and displayed when the app is in the background.

**Comment by Sarita-tnex** [comment]
**Issue Resolved**
When we do pod install  for firebase then in Pod folder there is no Firebase folder which consists of Firebase.h file which is there in sample example of react-native-fcm when I manually added the Firebase folder in Xcode Workspace then it worked

Also I noticed that in sample app pod file consists of pod 'Firebase/Messaging' but I used  pod 'FirebaseMessaging' as given in Read me.
 In my case notifications worked for all cases background ,foreground and killed state

**Comment by evollu** [comment]
if you have issue with iOS try FirebaseInstanceID 2.0.0 rather than 2.0.1-2.0.3

**Comment by RuiDamiao** [comment]
"react-native": "^0.50.1",
"react-native-fcm": "^14.0.1"
Not getting notification in any state of app in ios App. In Android is working fine.
Device: Iphone 6 Emulator
Followed all the steps for installation using cocopod approach.
Uploaded APN Push certificates on Firebase project also .

The app is running and has no errors.
I don't know what to do anymore. Any help would be appreciated.

**Comment by evollu** [comment]
@RuiDamiao ios emulator doesn't get remote notification.

**Comment by RuiDamiao** [comment]
@evollu is it only possible to test if it works on an iphone?

**Comment by evollu** [comment]
yes

**Comment by Mogust** [comment]
in my case i can get notification when i send a push notif from console.firebase, but when i send from my web platform i dont get any notification, the status of send is succed, maybe anyone have solution ? :D
