### ISSUE TITLE
Question - How to replace multiple notifications with a single one?

### ISSUE THREAD

**Issue by tss101** [evollu/react-native-fcm#605]
Hi,

Many thanks for working on such a great framework! I've managed to get react-native-fcm working (react-native version 0.48.4) with remote notifications, both on iOS and Android devices (versions from iOS 9-11, Android 5-8), when the app is in foreground, background and not-running. 

Sometimes it turns out I send multiple notifications to the user before they check them. And I was wondering if it's possible to replace multiple notifications with a single one, saying that there's multiple updates? This would ideally work in background, when the app is not running, and when it's been killed by the user (is that the same as not running?).

This is the format of the remote notifications I'm sending:

iOS:
```
{
            title: title,                     
            body: body,                    
            sound: "default",                                   
            priority: "high",
            show_in_foreground: showinfg   
}
```

Android:
```
{
            "custom_notification": {
                "body": body,
                "title": title,
                "icon":"ic_notif",
                "priority":"high",
                "sound":"default",
                "show_in_foreground": showinfg
                }
}
```

**Comment by tss101** [comment]
Actually collapse_key seems to be what I'm looking for

references:
https://github.com/evollu/react-native-fcm/issues/94
https://stackoverflow.com/questions/39782438/can-fcm-notification-on-android-overwrite-previous-one

**Comment by evollu** [comment]
or you can pass same `id` property, it should override the old one

**Comment by tss101** [comment]
Oh cool thanks, does the `id` property work for iOS and Android, and for remote notifications?

**Comment by evollu** [comment]
may be not for iOS. but sure for custom_notification

**Comment by tss101** [comment]
many thanks will give it a try
