### ISSUE TITLE
Notifications are always received even after unmount

### ISSUE THREAD

**Issue by HusseinReda** [evollu/react-native-fcm#610]
This is for android experience, I'll explain the problem in further details:

The FCM Handler component is being rendered in LaunchScreen (in order to be able to pass the navigator). The LaunchScreen is only rendered if the user is signed in.

The notification is required to be sent only if the user logged in because of a navigation logic which is should be fired when the notification is opened from tray, which is dependent on user's data. That's why it's rendered in the Launch screen.

My main problem is that the notification is received even after the user is logged out,or to be more generic, even if the user is signed out and the app is closed (not force close, but swiping it out from running applications), and I made sure that the FCM component is unmounted, and by which removing the listener.

Can you please advice why is this happening?

This is the code for the FCM handler component:
```
import {Platform} from 'react-native'
import React, { Component } from 'react'
import { connect } from 'react-redux'
import FCM, {FCMEvent, RemoteNotificationResult, WillPresentNotificationResult, NotificationType} from 'react-native-fcm'

class FCMService extends Component {
  constructor(props) {
    super(props)
  }

  componentDidMount() {

    this.notificationListener = FCM.on(FCMEvent.Notification, async (notif) => {

      if(notif.local_notification){
        //this is a local notification
      }

      // app is open/resumed because user clicked banner
      if(notif.opened_from_tray){
        // logic for navigating to another screen
      }

      this.refreshTokenListener = FCM.on(FCMEvent.RefreshToken, (token) => {
        // update token in server
    });

    FCM.getInitialNotification().then(notif=>{
      // logic for handling initial notification
    });

    this.requestPermissions()

    this.initToken()
  }

  componentWillUnmount() {
    FCM.removeAllDeliveredNotifications()
    this.notificationListener.remove();
    this.refreshTokenListener.remove();
    console.log("component un-mounted")
  }

  requestPermissions = () => {
    FCM.requestPermissions({badge: false, sound: true, alert: true}).then(()=>console.tron.log('granted')).catch(()=>console.tron.log('notification permission rejected'))
  }

  initToken = async () => {
    const latestFcmToken = await FCM.getFCMToken().then(token => {
      return token
    });

    // logic for saving sending token to server
  }

  render(){
    return null
  }
}
export default connect(mapStateToProps, mapDispatchToProps)(FCMService)
```

This is the message being sent from the server
```
{
    :data => {
        :custom_notification => {
                         :title => "Notification tytle",
                          :body => "Notification body",
            :show_in_foreground => true,
                         :sound => "default",
                    :navigation => {
                :to_screen => "CertainScreenInApp",
                   :params => {
                    :first_attr => "first_value"
                }
            }
        }
    }
}
```

**Comment by evollu** [comment]
ok. you don't want to show the banner at all when user is not logged in? Since you only need notification when application is running, you can use pure `data` payload and build local notification when you receive notification

**Comment by HusseinReda** [comment]
Thanks for the advice. 
Actually I want the notifications to be received when the app in the background also. 

I'm wondering about a strange behavior that I don't understand, which is even after commenting out the FCM event listener, the app still receives notifications when I send it in the format shown above, why is this happening? Is it something related to the core package of the FCM or is it related to the type of the message sent? 

One last thing, shouldn't the message I'm sending - in the format given above - be considered as 'pure data' message? Or the 'custom notification' attribute changes its behavior?

**Comment by evollu** [comment]
@HusseinReda it is custom_notification. This repo will build a local notification automatically if you send custom_notification.

You will receive notification when app is in background if you send pure data message

**Comment by HusseinReda** [comment]
If I send a pure data notification, will it be shown automatically in the mobile tray when the app is in the background or it will be only received in the app and I shall handle it with local notification?

**Comment by evollu** [comment]
if you send a pure data with custom_notification, then it will show up automatically.
otherwise you will need to build a local notification yourself

**Comment by HusseinReda** [comment]
Thanks for your reply, here's what I've concluded, and please let me know if I'm wrong:

Given the fact that I've the listener in the first screen the user sees when he logs in, here's what is happening : 

- If I sent a **pure data notification** (having only **'data'** as a key in the hash), it will be handled (event is fired in the listener) only if the app is in **foreground** or **background**, on the other hand, the event listener won't be triggered if the app is **closed**.

- If I sent a **pure notification** one (having only **'notification'** as a key in the hash), it will 
**only** pop up in the tray if the app is in **background** or **closed**, and in both cases it **doesn't** trigger the listener.

- If I sent a message containing both **data** and **notification**, a notification will pop up in the tray if the app is in **background** or **closed**, and the data will be handled (triggered the event listener) **ONLY** if the app is in **foreground**.

Summing up, here's my new questions ( and sorry for being talkative, I just wanted everything to be as clear as possible) : 
1. The problem I'm facing is that **background** is common if I sent data only or notification only, and when tried to have both, data didn't trigger the event listener when the app is in background, how can I solve this to have data handled when the app is in the background and foreground or notification shown in when the app is in background or closed?
2. The second weird issue is that when I send a pure **data** one when the app is closed, I noticed that it caused to somehow start the app, not full start, but some actions related to the startup and async storage are fired, and when I opens the app it misbehave, as it was started somehow abnormally, and that doesn't happen if i **force closed the app**. Why is this happening and how it shall be solved ?? As this is a big issue and may cause the app to misbehave.

This is the data msg I send:
```
{
	data: {
		x: y
    }
}
```
This is the notification msg I send:
```
{
	notification: {
		title: "Title",
		body: "Body",
		sound: "default"
	}
}
```
And this is the combined one:
```
{
	data: {
		x: y
	},
	notification: {
		title: "Title",
		body: "Body",
		sound: "default"
	}
}
```

**Comment by evollu** [comment]
your 3rd point of understanding is not right. when you send both, `data` part will be stripped away by FCM when you are in background, thus not triggering JS handler. My suggestion is not use android notification part at all as it is so unpredictable.

when you receive data issue when application is closed, it wakes up your app and initiates your JS (all your code will be executed except component won't be mounted). So you need to move some of your code into componentDidMount of root component to avoid unexpected change.

In your particular case, what I would do is have JS handler inside componentDidMount of root component and only send data notification. Inside the callback it checks if user has logged in.

**Comment by HusseinReda** [comment]
Sorry for the delay in getting back to you.
Concerning the "waking up of the app" issue when a notification is received, I already have a JS handler for the FCM service (similar to PushController.js in the example in the repo here), I've commented all the code in it, didn't import it in any other component, in other words, nothing in the app is using anything related to the notifications, except for just the setup ( as in the readme before the Usage section).

I've sent a notification from the server, and it's received and the app woke up too ! How/Why is this happening?

**Comment by evollu** [comment]
can you reproduce with the example app? just to make sure there is no other 3rd party lib causing the wake up

**Comment by jqn** [comment]
@HusseinReda -The way I'm handling push notifications is, when the user signs out I unsubscribe them. Push notifications will be delivered regardless of the state of your app since the server doesn't know the user is logged out. I'm using pusher and their api has an endpoint to subscribe and unsubscribe the user. 

To add to this conversation and it might be a similar issue, when the app is in the background and a user taps on the notification banner the push notification lingers even after the notification was viewed - this is for android - I'm not sure is this is by design or a bug:

![screen shot 2017-11-17 at 10 04 08 am](https://user-images.githubusercontent.com/9710893/32959382-b25477c6-cb7e-11e7-85ef-100b80a51785.png)

**Comment by HusseinReda** [comment]
@jqn yes exactly, I've solved the issue by activating and deactivating the attached device to the user in the backend, so I'm sending only to the active devices.

I believe the issue can be closed now, thanks to @evollu and everyone for helping.
