### ISSUE TITLE
It seems something went wrong while linking

### ISSUE THREAD

**Issue by edwinwongnetccentric** [evollu/react-native-fcm#614]
RN version: 0.41.2
Device: Nexus 5 Android 6.0.1 API 23

I have problem when I run "react-native link react-native-fcm" 
![image](https://user-images.githubusercontent.com/27198513/31576409-b76dffa0-b12c-11e7-91d3-5f19bf05684c.png)

this is my directory 
![image](https://user-images.githubusercontent.com/27198513/31576432-48a9e97a-b12d-11e7-8731-4330d1d798bb.png)

does it have any side effect?

**Comment by evollu** [comment]
looks like linking failed. I don't know why.
Make sure this line is added 
https://github.com/evollu/react-native-fcm/blob/master/Examples/simple-fcm-client/android/app/src/main/java/com/google/firebase/quickstart/fcm/MainApplication.java#L28

**Comment by edwinwongnetccentric** [comment]
I manage to solve it by rename netccentric.PitchDuck to netccentric > Pitchduck folder and move the java files into the Pitchduck folder.

![image](https://user-images.githubusercontent.com/27198513/31594357-feb89506-b266-11e7-8bc4-69f83bfd8600.png)

Anyway thanks!
