### ISSUE TITLE
Not receiving push notification in android.

### ISSUE THREAD

**Issue by codesinghanoop** [evollu/react-native-fcm#615]
Thanks for this library and it's really beautiful work.

What is happening with me ?
I integrated this library successfully despite react-native-maps was integrated already. I used the example code from this repo and i'm getting notification in the emulator from where i created the notification and not receiving notification to all other registered devices. When i created the notification from the firebase console i was able to see notification in all the registered devices. Below you can see the code. Any help would be appreciated.

if(Platform.OS === 'android'){
      body = {
        "to": token,
				"content_available": true,
      	"data":{
			"custom_notification": {
				"title": "Simple FCM Client",
				"body": "This is a notification with only NOTIFICATION.",
				"sound": "default",
				"priority": "high",
				"group": "GROUP", 
				"id": "id",
				"show_in_foreground": true
        	         }
    		},
    		"priority": "high"
      }
    }

1. What version of RN and react-native-fcm are you running?
RN: 0.48.4
react-native-fcm: ^10.0.2
2. What device are you using? (e.g iOS9 emulator, Android 6 device)?
android device - Nexus emulator 6
3. Is your app running in foreground, background or not running?
app running in foreground/background

**Comment by evollu** [comment]
if you can receive FCM notification sent through console, then potentially something is wrong with build the notification. one suspect is that you are not using "icon" field.
If you can debug android device, set breakpoint here and see if you get error or missed some resource.
https://github.com/evollu/react-native-fcm/blob/master/android/src/main/java/com/evollu/react/fcm/SendNotificationTask.java#L46

**Comment by codesinghanoop** [comment]
Thanks @evollu for such a fast reply. Below is the debug result.

<img width="1206" alt="screen shot 2017-10-17 at 12 19 39 am" src="https://user-images.githubusercontent.com/13526746/31629432-39e6a4d2-b2d1-11e7-8e19-df354e3b7008.png">

**Comment by codesinghanoop** [comment]
Adding icon field in the payload doesn't work as well. Waiting for your response.

**Comment by evollu** [comment]
can you step through the function?

**Comment by codesinghanoop** [comment]
Thanks @evollu for helping me and i'm grateful to you for the concern, i have resolved the issue and now i'm getting push notification. I want to share the solution so that if anyone else stuck in here. Yesterday i was going through the firebase documentation and i saw i can use "registration_id" key instead of "to" key, what "to" key does is it sends the notification to one device token as it accepts only string value and "registration_id" accepts array of token. I also came to know that "to" can accepts the topic messaging where all the devices which are subscribed to a topic will receive a push notification. After subscribing a device to a topic please don't hope for getting the topic name immediately into the console, it would take an hour or two to reflect in the firebase console. This all i learned through this lib. Though i'm receiving push notification successfully however, i'm also getting an alert which states "Failed to send notification, check error log" anyways i don't care about this until i'm receiving notification 👍 .

Please @evollu correct me if i'm wrong anywhere and sorry it was my fault. Keeping the hard work going.

**Comment by evollu** [comment]
@codesinghanoop glad you figured it out.
`Failed to send notification, check error log` is shown when the response is not expect (I never test the verification logic with topic notification so probably that's why).

**Comment by vhuytdt** [comment]
![image](https://user-images.githubusercontent.com/18238875/33013730-a1ca00b0-ce17-11e7-9a94-eba5e2041ec3.png)
how to sovle my problem :(

**Comment by evollu** [comment]
check your android log. It will have the https response error from firebase.

**Comment by vhuytdt** [comment]
I try to push notification from console Firebase by fragment. In App, Notification not show.
when back home and try it again, it work.

**Comment by pewh** [comment]
Have you remove "group" in fcm payload then try again?
