### ISSUE TITLE
Missing iOS registerForRemoteNotifications

### ISSUE THREAD

**Issue by adamaccent** [evollu/react-native-fcm#617]
I'm not sure if this is implicit in the use of FCM, but I've found this piece of code was missing when setting up the iOS platform:

```
- (void) application:(UIApplication *)application didRegisterUserNotificationSettings:(UIUserNotificationSettings *)notificationSettings
{
    [application registerForRemoteNotifications];
}
```

Specifically, because the app wasn't doing `[application registerForRemoteNotifications];` it never received any notification from the Firebase Console.

Should the line above be in the [documentation](https://github.com/evollu/react-native-fcm/blob/master/README.md)?

**Comment by adamaccent** [comment]
Apologies, it seems this was a red herring. It looks like it's actually pushing notifications to iOS using single device tokens, but doesn't work for user segment.

**Comment by evollu** [comment]
someone mentioned that there could be a delay between registration and being included in user segment.
speaking of didRegisterUserNotificationSettings. yes, normally you will need to do that. But Firebase SDK does swizzling for you.
