### ISSUE TITLE
error building iOS

### ISSUE THREAD

**Issue by TranHanHieu** [evollu/react-native-fcm#618]
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by evollu** [comment]
this doesn't provide any useful information. it is the line above it that tells you the error

**Comment by TranHanHieu** [comment]
![screen shot 2017-10-19 at 08 51 29 4](https://user-images.githubusercontent.com/19732500/31750517-d5d663fc-b4aa-11e7-860c-d1bea5c453a7.png)
I using:
"react": "16.0.0-alpha.12",
"react-native": "0.48.1",
"react-native-fcm": "^10.0.2",
podfile install success

**Comment by wodCZ** [comment]
Same issue here, fixed by manually adding `libGoogleToolboxForMac.a` under `Linked Frameworks and Libraries`.

**Comment by evollu** [comment]
right you need to link the missing library

**Comment by evanjmg** [comment]
Getting the same thing. I've pod installed Firebase Messaging and it works fine on the simulator (the npm package), I get asked if I want to enable push notifications etc. But, I can't find GoogleToolbox in Linked Frameworks and Libraries
