### ISSUE TITLE
Using only the Android part of this library

### ISSUE THREAD

**Issue by Kuzmin** [evollu/react-native-fcm#62]
Hello,

I wanted to use FCM for my messaging needs on Android, but retain APN for Apple since it's officially supported by the React Native team. This works for me if I just avoid all the steps for Apple installation, but it still feels a bit uneasy since I'm not entirely familiar with React Native internals, and so I feel like some code from FCM might still be running in the background.

Could you clarify this? I think it would be useful to also have in the Readme since I believe there are more than me who will use this only on Android. 😄 

Thanks!
Alexander

**Comment by evollu** [comment]
you can link android solution, use `react-natlive link react-native-fcm android`

**Comment by evollu** [comment]
@Kuzmin is your problem solved?

**Comment by Kuzmin** [comment]
Oh yeah! I think I was thinking more that "this should be added explicitly to the readme", but maybe this is an obvious feature of React Native that I should have been aware of!

My bad! Thanks for the help!
