### ISSUE TITLE
Cannot disable vibration on Android

### ISSUE THREAD

**Issue by madox2** [evollu/react-native-fcm#620]
I want to disable vibration in local notification. According to documentation I should pass `null` to `vibration` property. However when passing `null` vibration is still enabled. I have managed to disable vibration by `vibration: 0`. If this is expected behaviour, documentation should be updated.

RN: 0.42.3
react-native-fcm: 10.0.0
Running on Android device 6.0.1

**Comment by evollu** [comment]
readme updated. it should be 0
