### ISSUE TITLE
[Android] Not Receive Push notification when app is killed

### ISSUE THREAD

**Issue by fokoz** [evollu/react-native-fcm#622]
When my app is killed, I don't receive any push notification even in the tray,
but when in background or foreground it is fine.

I also tested sending from firebase console it is the same.

Note: it is fine with samsung android 5.0

1. What version of RN and react-native-fcm are you running? **0.48, 10.0.2**
2. What device are you using? (e.g iOS9 emulator, Android 6 device)? **Android 6, Vivo**
3. Is your app running in foreground, background or not running? **Not running**

**Comment by evollu** [comment]
`Vivo`. I wonder if they have custom notification permission.

**Comment by fokoz** [comment]
Thank you for the flash response,
How to request the permission ?

Thank you.

**Comment by fokoz** [comment]
@evollu it is fine on samsung device(android 5)

**Comment by evollu** [comment]
@fokoz Every chinese manufacture customize their own differently. Baidu it?

**Comment by fokoz** [comment]
I found interesting link https://stackoverflow.com/questions/41277671/clear-recent-apps-wipe-the-apps-memory-and-my-receiver-stopped-working/41360159#41360159

**Comment by evollu** [comment]
yes. there is an asus one as well
I'm closing this as it is a manufacture specific issue.
But any PR or solution that solves is welcomed
