### ISSUE TITLE
Cannot detect clicking on bundled notification

### ISSUE THREAD

**Issue by plaa** [evollu/react-native-fcm#625]
Android 7.0+ automatically [bundles notifications](https://developer.android.com/guide/topics/ui/notifiers/notifications.html#bundle) if four or more notifications are sent by the same app.

If a user clicks on a bundled notification (instead of swiping it open and clicking an individual notification), there seems to be no way to find out the app was opened by clicking the notification.

Tested on Samsung Galaxy S6 / Android 7.0 device, the notification payload from `getInitialNotification` when clicking a bundled notification:

    {"opened_from_tray":1,"fcm":{"action":"android.intent.action.MAIN"}}

When opening using app icon:

    {"opened_from_tray":1,"fcm":{"action":"android.intent.action.MAIN"},"profile":0}

I'm unsure what the "profile" field is, and it's not present when running a debug build on Nexus 5X API 26 emulator. Could it be as a workaround to distinguish the cases?

We're not explicitly using notification bundling, instead Android is automatically bundling separate notifications.  (Is explicit bundling of separately scheduled local notifications supported by react-native-fcm?)

Tested using react-native 0.46.4 and react-native-fcm 10.0.3 and 7.0.3.  Exact same results whether starting from background or not running state.

**Comment by evollu** [comment]
try use different "id" fields to avoid bundling

**Comment by plaa** [comment]
We are setting different ids for each notification, that does not prevent the automatic bundling. The automatic bundling is desired for us, but we'd want to know when the app is started by clicking the bundle.

**Comment by evollu** [comment]
played a little with Android Oreo but it doesn't bundle for me. How did you do that?
I used local notification though

**Comment by evollu** [comment]
OK. I'm able to produce bundled notification.
But there is nothing that is passed to the app through Intent. Not even the number of the notifications. So I can't do anything about it. Just treat as user opened as tapping the app icon?

**Comment by plaa** [comment]
I was a bit worried that's the case. I'm not sure is there some additional info available if the bundling has been done explicitly instead of automatically.

**Comment by evollu** [comment]
I passed `group` and it seems to prevent the bundling behavior.
