### ISSUE TITLE
Expand local notifications right inside the app on dragging down

### ISSUE THREAD

**Issue by ranjithnori** [evollu/react-native-fcm#626]
Local notifications expand right inside the notification tray on dragging down currently. Can we make them expand right inside the app ?

**Versions:**

React Native: 0.45.1
react-native-fcm: 10.0.3

**Device details:** 

Device name: Samsung Galaxy J2
Model Number: SM-J200G
Android Version: 5.1.1

In my case, I trigger a local notification when the app is in foreground.

**Comment by evollu** [comment]
no, because notification is system level.

If you want to show something like notification inside app, just build an animated view. There are libraries for this as well
