### ISSUE TITLE
Can't access payload data in on "FCMEvent.Notification" which is called when app is in foreground

### ISSUE THREAD

**Issue by sandeepkasani** [evollu/react-native-fcm#629]
I am trying to access payload data in FCM message and perform some actions in the react-native code. I see the payload data in the JS console.log when the app is not running or in the background. 
**FCM.getInitialNotification()** is called in this scenario and it works good.
The response is
**{
  "opened_from_tray": 1,
  "fcm": {
    "action": "android.intent.action.MAIN"
  },
  "collapse_key": 121233313,
  "google.message_id": "#$$#$@$22411231",
  "from": "321331231312313",
  "google.sent_time": 1509370108938,
  "key1": "1",
  "key2": "true",
  "key3": "true"
}**

But i can't see the payload data when the app is in foreground.  The response is 
**{"opened_from_tray":1,"fcm":{"action":null}}** The key value pairs and other details are missing

The code for the foreground
```
FCM.on(FCMEvent.Notification,this._onNotification);
_onNotification(notif) {
      console.log("notification details: ", notif);
  }
```

**Comment by evollu** [comment]
what is you payload for the notification

**Comment by sandeepkasani** [comment]
Remote. 
Using firebase console advanced options for now.

**Comment by evollu** [comment]
it might be stripped off by FCM.
add breakpoint here https://github.com/evollu/react-native-fcm/blob/master/android/src/main/java/com/evollu/react/fcm/MessagingService.java#L27
see if the message has extra data

**Comment by sandeepkasani** [comment]
We have debugged the android code. We see that the payload before the notification is raised whether the app is in background or foreground or killed. In the screenshot below, the payload data is an array of size 1 with a value 14. 
![screen shot 2017-11-02 at 6 42 12 pm](https://user-images.githubusercontent.com/10723554/32327803-ce994010-bffd-11e7-83ca-79db1d0ddac5.png)

Below is the screenshot of the firebase console and the key-value payload
![screen shot 2017-11-02 at 6 46 05 pm](https://user-images.githubusercontent.com/10723554/32327895-243d6c08-bffe-11e7-85cf-b641ff8b865f.png)

**Comment by evollu** [comment]
this class is not the one inside react-native-fcm project. Did you add your own receiver?

**Comment by sandeepkasani** [comment]
That was the problem. I first integrated firebase as per firebase guide and on top of it added react-native-fcm plugin. As per the firebase guide, I added the receiver.

I removed the that service and it works fine now :)
Keep up the good work :)

**Comment by evollu** [comment]
cool
