### ISSUE TITLE
"RNFIRMessaging.h" file not found.

### ISSUE THREAD

**Issue by jondbm** [evollu/react-native-fcm#63]
This is the same issue I think that was previously closed here, but is still a problem:
https://github.com/evollu/react-native-fcm/issues/21

Following the instructions exactly, even adding the library manually, I've tried everything but the project never sees the RNFIRMessaging.h file and the build fails every time.

Are there missing steps in the documentation, perhaps? I'm using Cocoapods, and I can see the Firebase Messaging library in my app, everything appears in the right place, but it can't see it on build.

**Comment by jondbm** [comment]
cpsiaki figured it out here:
https://github.com/evollu/react-native-fcm/issues/21#issuecomment-236192491

I needed to add '$(SRCROOT)/../node_modules/react-native-fcm/ios' to header search paths in build settings. That seemed to work. Perhaps should be added to the troubleshooting list?

**Comment by hjJunior** [comment]
I've added but I still with the problem :( 
is there anything that I can try to solve it?
