### ISSUE TITLE
The library doesn't add dependency for GoogleApiAvailability 

### ISSUE THREAD

**Issue by andyalbert** [evollu/react-native-fcm#630]
The dependencies added (mainly for **Android**) has nothing as `com.google.android.gms:play-services-base:11.4.2` which is important in case the device doesn't have or have old Google play service, so what will happen in case this happens?

**Comment by evollu** [comment]
I'm curious about that as well. but so far thing has been working fine for me.

**Comment by andyalbert** [comment]
what I mean was that, does the library has any checking for the availability of the Google play service? as it may crash if it tries to work and it's not available.

**Comment by evollu** [comment]
no it doesn't. it should though.

**Comment by evollu** [comment]
add following code in your MainActivity.java and things should be good.

```
public boolean checkGooglePlayServicesAvailable() {
        GoogleApiAvailability googleApiAvailability = GoogleApiAvailability.getInstance();
        int status = googleApiAvailability.isGooglePlayServicesAvailable(this);
        if(status != ConnectionResult.SUCCESS) {
            if(googleApiAvailability.isUserResolvableError(status)) {
                googleApiAvailability.getErrorDialog(this, status, 2404).show();
            }
            return false;
        }
        return true;
    }

    @Override
    protected void onResume() {
        super.onResume();
        checkGooglePlayServicesAvailable();
    }
```
