### ISSUE TITLE
Push Notification not able to receive in Kill State

### ISSUE THREAD

**Issue by URvesh109** [evollu/react-native-fcm#635]
Hi,
you did excellent work of custom notification in android, it is awesome.

"react-native": "0.49.3",
"react-native-fcm": "^10.0.3",

this is my payload from POSTMAN

{
  "to":mytoken,
   "content_available": true,
  "data": {
      "custom_notification": {
      "body": "Hello urvesh how r you",
      "title": "This is notification",
      "priority":"high",
      "icon":"icon",
       "lights": true,
       "show_in_foreground": true
         }
       }
}

and status of my response

{
    "multicast_id": 5186096154991249446,
    "success": 1,
    "failure": 0,
    "canonical_ids": 0,
    "results": [
        {
            "message_id": "0:1509883929709513%d8a65b43f9fd7ecd"
        }
    ]
}

everything work as expected, but i didn't receive notification when app is in kill state

I have used this

// FCM.on(FCMEvent.Notification,async (notif)=>{
................................................
// });

 FCM.getInitialNotification().then(notif=>{
................................
        });

Kindly please suggest

**Comment by evollu** [comment]
you mean notification doesn't show up?

**Comment by URvesh109** [comment]
yes

**Comment by evollu** [comment]
have no clue here. can you reproduce on emulator?

**Comment by URvesh109** [comment]
hi,

I m using actual device, what should i reproduce?

**Comment by evollu** [comment]
run the app in an emulator. it can receive notifications. 
If it works, then it has to do something with the phone you are using. What brand are you using?

**Comment by URvesh109** [comment]
Coolpad note5 and i will try on other devices which i have along with
emulator and let you know.
thank you for help

**Comment by URvesh109** [comment]
Yes you are right. Some phone does not receive notifications and some does but why may I know the reason?

**Comment by URvesh109** [comment]
thks

On 07-Nov-2017 8:21 PM, "Libin Lu" <notifications@github.com> wrote:

some manufacture with custom android system will have notification
permissions. check that

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/evollu/react-native-fcm/issues/635#issuecomment-342506067>,
or mute the thread
