### ISSUE TITLE
[IOS] App is crashing after installed from apple store.

### ISSUE THREAD

**Issue by tolgaduzenli** [evollu/react-native-fcm#636]
Hi,
Our ios app is already released to the apple store but we have one crash problem while ios-app is opening at the beginning, after installed from apple store.
1- install app
2- open app
3- asking notification permission to allow
4- and then crash is happening. (%90 devices with different ios version. not only ios 11.)
_There is no problem to get notification to the devices._ 

Firebase/Crash report shows error;
**NSInvalidArgumentException: -[RNFIRMessaging messaging:didRefreshRegistrationToken:]: unrecognized selector sent to instance.**

Tried many things; moved GoogleService-Info.plist file under another group folder or used new method in RNFIRMessaging.m  `[[FIRMessaging messaging] setDelegate:self];`
But still it is same.

"react-native": "0.43.3",
"react-native-fcm": "^6.2.3"

Any suggestion?

**Comment by georgest** [comment]
I have the same issue. I use also react-native-fcm 6.2.3

**Comment by tolgaduzenli** [comment]
ok, I solved the problem with upgrade of react-native-fcm 7. Here is original comment [link](https://github.com/evollu/react-native-fcm/issues/419#issuecomment-342139832).

**Comment by VijayPatel91** [comment]
I fixed it by doing this step.
Simply in AppDelegate.h
Step : 1 #import "RNFIRMessaging.h"
Step : 2 add FIRMessagingDelegate

in "AppDelegate.m"
Step : 3 add below code in didFinishLaunchingWithOptions method

`UNUserNotificationCenter *center = [UNUserNotificationCenter currentNotificationCenter];
UNAuthorizationOptions options = UNAuthorizationOptionAlert + UNAuthorizationOptionSound + UNAuthorizationOptionBadge;

// [[UNUserNotificationCenter currentNotificationCenter] setDelegate:self];
[UNUserNotificationCenter currentNotificationCenter].delegate = self;

// Objective-C
[center requestAuthorizationWithOptions:options
completionHandler:^(BOOL granted, NSError * _Nullable error) {
if (!granted) {
NSLog(@"Something went wrong");
}
else {
[FIRMessaging messaging].delegate = self;

                        dispatch_async(dispatch_get_main_queue(), ^{
                          [FIRApp configure];
                        });


                      }
  }];`
Step : 4 Replace didRefreshRegistrationToken method with
`-(void)messaging:(FIRMessaging )messaging didRefreshRegistrationToken:(NSString )fcmToken {

NSLog(@"%@", fcmToken);
} `

Build the app.
