### ISSUE TITLE
[Android] App auto open it self after receiving push

### ISSUE THREAD

**Issue by fokoz** [evollu/react-native-fcm#637]
On Android, while app is not running (has been killed), after receiving push notification the app auto-opens by itself.

1. What version of RN and react-native-fcm are you running? **10.0.2**
2. What device are you using? (e.g iOS9 emulator, Android 6 device)? **Android 6, Vivo**
3. Is your app running in foreground, background or not running? **not running**

**Comment by evollu** [comment]
possibly caused by your navigation package. try reproduce with example project

**Comment by fokoz** [comment]
@evollu 
Hi,
I am using `react-native-navigation`, where to look, such `MainActivity` ?

Thank you.

**Comment by evollu** [comment]
perhaps this thread helps https://github.com/evollu/react-native-fcm/issues/547
