### ISSUE TITLE
presentLocalNotification not show on IOS 9 when app running in foreground

### ISSUE THREAD

**Issue by tieusangaka** [evollu/react-native-fcm#639]
![screen shot 2017-11-07 at 11 25 15 am](https://user-images.githubusercontent.com/8295187/32477191-efd639ae-c3ae-11e7-9773-149700332f23.png)
![screen shot 2017-11-07 at 11 24 28 am](https://user-images.githubusercontent.com/8295187/32477192-f09a66f8-c3ae-11e7-9014-6c2184b4ec23.png)

I push notification with IOS version 10 above all received when app running in foreground and background.
But with IOS 9 below . It not show Notify when app running in foreground although i have received notify in notifilistener FCM.on(FCMEvent.Notification, notif => {}
How to show notify with IOS 9 use presentLocalNotification?
Thanks for support.

**Comment by evollu** [comment]
can't do with iOS 9. system limit
https://stackoverflow.com/questions/40371125/push-local-notification-when-app-foreground-in-swift-ios-8-9
