### ISSUE TITLE
Missing sound and vibration from notifications

### ISSUE THREAD

**Issue by EduardJS** [evollu/react-native-fcm#641]
Hello gents !

I don't actually have any issues with this module, everything works just fine. The only problem is that my notifications are "silent" ( as in no sound or vibration ). I also added `sound: 'default'` to the payload, hoping for a fix, but ... nothing fixes.

Anyone having faced the same issue before ? Any ideas ? I'm just using the sample payload, with the simplest stuff: badge, text and sound.

Regards!

**Comment by evollu** [comment]
what's your system and payload? local or remote? did you check your phone setting if it mutes notification?

**Comment by EduardJS** [comment]
Ahh sorry, seems like my last part of the post didn't go through, was on mobile.

I'm running:
iOS 11.1 ( iPhone 7 )
Notification is Remote
Regarding settings, I've checked them ... 

Payload: 
```javascript
const payload = {
	notification: {
		body: `${lang[type]} ${username}`,
		sound: 'default',
		badge: '1',
	}
}
```
