### ISSUE TITLE
non removable notification

### ISSUE THREAD

**Issue by vendramini** [evollu/react-native-fcm#642]
Is possible to create an non removable notification? I did a search and I found answers like this: https://stackoverflow.com/questions/13427204/non-removable-notification

So, I supposed to use `ongoing: true` on `FCM.presentLocalNotification` object parameter, but it still removable (tested on Android 6).

Thanks for the excellent library, guys.

**Comment by evollu** [comment]
is this line getting called?
https://github.com/evollu/react-native-fcm/blob/61cbaca2719d7a03a48d2eaa17c65b5a08199846/android/src/main/java/com/evollu/react/fcm/SendNotificationTask.java#L77

**Comment by vendramini** [comment]
My react-native-fcm was outdated, I really sorry about that.

Is there some way to take control of all packages using on project? I mean, to know if some is outdated.

Closing this issue, thanks.

**Comment by evollu** [comment]
you can run yarn/npm outdated to check if any of your package is outdated
