### ISSUE TITLE
Enable or disable FCM push notifications by toggle button from application settings (Android)

### ISSUE THREAD

**Issue by azamkth** [evollu/react-native-fcm#650]

**Comment by evollu** [comment]
how about set a flag on server?

**Comment by azamkth** [comment]
we have done on server but is there anyway to do on client side as well ?

**Comment by evollu** [comment]
you can only send data and build local notification yourself. then you can choose not to do anything locally

**Comment by azamkth** [comment]
@evollu it means notification tray will appear and when user will tap notification tray then I will not perform an action right?

**Comment by evollu** [comment]
I mean you can send data notification, which won't show anything to user but will trigger a callback in JS. you can decide whether to build a local notification in JS and show it to user

**Comment by n0umankhan** [comment]
Hey evollu i think you can close this issue now
