### ISSUE TITLE
using react-native-router-flux to redirect on Action_click ?

### ISSUE THREAD

**Issue by eng0mustafa** [evollu/react-native-fcm#655]
hello i would like to user react-native-router-flux to redirect when i click notification 
is there any way to do that please ??
thanks

**Comment by evollu** [comment]
yes. do navigation in notification callback. also check initial notification on startup.
also make sure to put routing logic in a timeout of ~100ms

**Comment by eng0mustafa** [comment]
thank you very much 
you mean i should put it in if(notif.opened_from_tray){} ??

**Comment by evollu** [comment]
yes

**Comment by eng0mustafa** [comment]
ok it works good now 
but only when app killed put it in getInitialNotification()
 and in foreground opened_from_tray()
where should i put it to run it when app in background mode please ?

**Comment by evollu** [comment]
when app in background, it should go to `FCM.on(FCMEvent.Notification`

**Comment by eng0mustafa** [comment]
thank you .. you are the best
now a get new issue 
when app killed put redirect in getInitialNotification()
but every time i run the app after killed it redirect even if there is no notification reached
how can i solve that please ?

this is code
`FCM.getInitialNotification().then(notif => {
      Actions.alert_show({notif.id_not});
      console.log("INITIAL NOTIFICATION", notif)
    });`

**Comment by evollu** [comment]
check the notif it self. usually you want to check the custom data in the notif and do corresponding action.

**Comment by amitbravo** [comment]
@eng0mustafa I want similar things with my app . I am using react-native-firebase and react-native-router-flux , are you capable to redirect to specific scene whether app is foreground or background , would you care to share a snippet how did you do that ?

**Comment by evollu** [comment]
@amitbravo there is an navigation example in the example project.
