### ISSUE TITLE
How can i prevent some specific notifications?

### ISSUE THREAD

**Issue by thaiminhlien** [evollu/react-native-fcm#662]
I want to detect notifications for custom data and decide whether to show the banner or to prevent it, but before I can detect the notification - the app shows a banner.
How can I block some messages what I want?

**Comment by evollu** [comment]
send data notification and then call presentLocalNotification when you receive it.

**Comment by thaiminhlien** [comment]
@evollu thanks for your reply!!! I did it and it is working fine.
