### ISSUE TITLE
Local Notification un-cancellable or custom action button??

### ISSUE THREAD

**Issue by sabbiu** [evollu/react-native-fcm#666]
I am using this package for local notification for now. I wanted to know the following things:

1.  Can the notification be created so that it cannot be cleared from the tray? It can only be cleared in program when the user taps it.
2. Is there a possibility to add an action button which onTapped runs a callback function?
3. Is there an event listener for when user clears the notification from the tray?

**Comment by evollu** [comment]
1. try `ongoing: true`
2. in theory possible, but not yet implemented. PR welcome
3. no
