### ISSUE TITLE
How can I clear all notification from tray?

### ISSUE THREAD

**Issue by KwangsubAhn** [evollu/react-native-fcm#669]
When openning an issue, please include following information for better support

1. What version of RN and react-native-fcm are you running? RN: 0.48.4 FCM: 9.6.2
2. What device are you using? Android
3. Is your app running in foreground, background or not running? running well

Question. 
Whenever do presentLocalNotification, my device produce a new icon on tray. But I would like to clear all tray icons when app is on. Is there a way to clear the icon which is generated from presentLocalNotification?

**Comment by KwangsubAhn** [comment]
FCM.removeAllDeliveredNotifications();

**Comment by TRIPTI-JAIN** [comment]
FCM.removeAllDeliveredNotifications() works for me
