### ISSUE TITLE
How to show only the latest presentLocalNotification on system tray when it gets multiple notification?

### ISSUE THREAD

**Issue by KwangsubAhn** [evollu/react-native-fcm#672]
When openning an issue, please include following information for better support

1. What version of RN and react-native-fcm are you running? RN: ^0.48.4 FCM: ^9.6.2
2. What device are you using? (e.g iOS9 emulator, Android 6 device)? Android
3. Is your app running in foreground, background or not running? Running well

whenever the device get messages, it triggers presentLocalNotification. But It shows all the notification on system tray which I want it be display only one latest notification. How can I solve it?

Here is my setting for the notification function
```
FCM.presentLocalNotification({
                  vibrate: vibrate,
                  title: senderFullName,
                  body: message,
                  priority: 'normal',
                  sound: 'default',
                  show_in_foreground: showInForeground,
                  badge: 0,
                  number: 0,  
});
```

**Comment by evollu** [comment]
`priority: 'high'`

**Comment by KwangsubAhn** [comment]
priority: 'high' didn't work for my devices so I just deleted the previous notifications by "FCM.removeAllDeliveredNotifications();" right before calling localNotification
