### ISSUE TITLE
IOS - Unable to build 

### ISSUE THREAD

**Issue by al-esok** [evollu/react-native-fcm#676]
1. What version of RN and react-native-fcm are you running?
    "react-native": "0.49.3",      "react-native-fcm": "^10.0.3",
2. What device are you using? (e.g iOS9 emulator, Android 6 device)?
   Iphone 6S Plus - Physical device
3. Is your app running in foreground, background or not running?
  Foreground

Error encountered:
In file included from /Users/imac1/Documents/REPOSITORY/MauritiusUnion/node_modules/react-native-fcm/ios/RNFIRMessaging.m:1:
/Users/imac1/Documents/REPOSITORY/MauritiusUnion/node_modules/react-native-fcm/ios/RNFIRMessaging.h:4:9: fatal error: 'FirebaseCore/FIRApp.h' file not found
#import <FirebaseCore/FIRApp.h>
        ^~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1

What is the correct way of installing it? Because from the instructions mentioned it is clearly not working.

**Comment by al-esok** [comment]
I also get those errors when I install the pods : 

/Users/imac1/Documents/REPOSITORY/MauritiusUnion/node_modules/react-native-fcm/ios/RNFIRMessaging.m:202:11: error: use of undeclared identifier 'FIRMessagingConnectionStateChangedNotification'
     name:FIRMessagingConnectionStateChangedNotification object:nil];
          ^
/Users/imac1/Documents/REPOSITORY/MauritiusUnion/node_modules/react-native-fcm/ios/RNFIRMessaging.m:206:35: error: no visible @interface for 'FIRMessaging' declares the selector 'setDelegate:'
        [[FIRMessaging messaging] setDelegate:self];
         ~~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~
/Users/imac1/Documents/REPOSITORY/MauritiusUnion/node_modules/react-native-fcm/ios/RNFIRMessaging.m:213:31: error: no visible @interface for 'FIRMessaging' declares the selector 'setShouldEstablishDirectChannel:'
    [[FIRMessaging messaging] setShouldEstablishDirectChannel:@YES];
     ~~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/imac1/Documents/REPOSITORY/MauritiusUnion/node_modules/react-native-fcm/ios/RNFIRMessaging.m:218:39: error: no visible @interface for 'FIRMessaging' declares the selector 'isDirectChannelEstablished'
    resolve([[FIRMessaging messaging] isDirectChannelEstablished] ? @YES: @NO);
             ~~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/imac1/Documents/REPOSITORY/MauritiusUnion/node_modules/react-native-fcm/ios/RNFIRMessaging.m:233:53: error: property 'APNSToken' not found on object of type 'FIRMessaging *'
    NSData * deviceToken = [FIRMessaging messaging].APNSToken;
                                                    ^
/Users/imac1/Documents/REPOSITORY/MauritiusUnion/node_modules/react-native-fcm/ios/RNFIRMessaging.m:244:38: error: property 'FCMToken' not found on object of type 'FIRMessaging *'
    resolve([FIRMessaging messaging].FCMToken);
                                     ^
/Users/imac1/Documents/REPOSITORY/MauritiusUnion/node_modules/react-native-fcm/ios/RNFIRMessaging.m:508:93: error: property 'isDirectChannelEstablished' not found on object of type 'FIRMessaging *'
    [self sendEventWithName:FCMDirectChannelConnectionChanged body:[FIRMessaging messaging].isDirectChannelEstablished ? @YES: @NO];
                                                                                            ^
/Users/imac1/Documents/REPOSITORY/MauritiusUnion/node_modules/react-native-fcm/ios/RNFIRMessaging.m:509:67: error: property 'isDirectChannelEstablished' not found on object of type 'FIRMessaging *'
    NSLog(@"connectionStateChanged: %@", [FIRMessaging messaging].isDirectChannelEstablished ? @"connected": @"disconnected");
                                                                  ^
8 errors generated.
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1

**Comment by evollu** [comment]
check if your `Link Binary with Libraries` has the `libRNFIRMessaging.a`
check if your pods are installed correctly and you are opening the xcworkspace rather than xcproject

**Comment by al-esok** [comment]
Yes the libRNFIRMessaging.a is there and it is the xcworkspace.

**Comment by al-esok** [comment]
![reac-native-fcm](https://user-images.githubusercontent.com/19201455/33542511-c4d6c734-d8ec-11e7-9d9b-ca3971c4f1e1.png)

**Comment by al-esok** [comment]
My bad.... 

This was all due to outdated pods.

After updating firebase core pod it worked.

Thanks for the support :)

**Comment by NirmalsinhRathod** [comment]
I had the same issue. I updated pods, libRNFIRMessaging.a is there and I opened xcworkspace. Still I am getting same issue.
