### ISSUE TITLE
FCM.on(FCMEvent.Notification, async (notif) is not triggered when I click notification from system tray

### ISSUE THREAD

**Issue by KwangsubAhn** [evollu/react-native-fcm#677]
When openning an issue, please include following information for better support

1. What version of RN and react-native-fcm are you running? ^0.48.4, ^9.6.2
2. What device are you using? (e.g iOS9 emulator, Android 6 device)? Android
3. Is your app running in foreground, background or not running? Both

I placed below code of FCM listener outside of component. It is triggered and received message well even the app is killed. When I receive a message, my app calls local push notification. And when I click the push notification when the app is killed, it opens the app. 

The issue is that, as I know the listener is supposed to catch the event when I click the notification from system tray. However the event is not triggered. (When I place the code of the listener inside component the event is triggered. This is weird thing)

What I want to do is when I click the notification from the system tray, I want to open specific component, but I don't know the best approach. Can anybody advice me?

```
FCM.on(FCMEvent.Notification, async (notif) => {
   if(notif.local_notification){
    //this is a local notification
  } 
  if(notif.opened_from_tray){
    console.log('opened from tray');
    //iOS: app is open/resumed because user clicked banner
    //Android: app is open/resumed because user clicked banner or tapped app icon
  }
});
```

**Comment by evollu** [comment]
when the app is killed when you open notification, the notif goes in `getInitialNotification`

**Comment by rlyshw** [comment]
I'm having the same issue, however I am using `getInitialNotification` as a promise and the `notif` object that is passed along the promise is always the same object, regardless of how I open the app (from notification or from home screen).

The resulting object is:
```json
{opened_from_tray: 1, fcm: {action:null}}
```

**Comment by evollu** [comment]
@rlyshw it shouldn't be the case. the example project should be working

**Comment by KwangsubAhn** [comment]
working perfect! Thank you!

**Comment by Uysim** [comment]
I still face this issue. Do you know how to fix it yet?
