### ISSUE TITLE
Question - Feature Support

### ISSUE THREAD

**Issue by mykelaballe** [evollu/react-native-fcm#678]
Does this support:
1. use local and remote images for banner icon
2. multiple lines

**Comment by evollu** [comment]
it should

**Comment by mykelaballe** [comment]
are they supported in version 2.5.6?

**Comment by evollu** [comment]
the is a bug with remote image in 2.5.6 because the http request can't be in main thread.
multiple lines is supported

there are many bug fixes after 2.5.6 so I suggest upgrade.
