### ISSUE TITLE
IOS push notification sounds and vibrates continuously (Without stopping)

### ISSUE THREAD

**Issue by Adetiwa** [evollu/react-native-fcm#682]
On my react native application, using FCM for push notification, I noticed that when a push notification comes on the foreground(IOS), it keeps vibrating and sounding continuously and annoyingly, and won't stop until I turn off my Data.This doesn't happen when the notification comes when the app is running in the background.Here is a code snippet of the XCODE configuration and Javascript configuration.

- (void)userNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification withCompletionHandler:(void (^)(UNNotificationPresentationOptions))completionHandler
{
  [RNFIRMessaging willPresentNotification:notification withCompletionHandler:completionHandler];
}

#if defined(__IPHONE_11_0)
- (void)userNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void (^)(void))completionHandler
{
    [RNFIRMessaging didReceiveNotificationResponse:response withCompletionHandler:completionHandler];
}
#else
- (void)userNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void(^)())completionHandler
{
    [RNFIRMessaging didReceiveNotificationResponse:response withCompletionHandler:completionHandler];
  }
#endif

//You can skip this method if you don't want to use local notification
-(void)application:(UIApplication *)application didReceiveLocalNotification:(UILocalNotification *)notification {
  [RNFIRMessaging didReceiveLocalNotification:notification];
}

- (void)application:(UIApplication *)application didReceiveRemoteNotification:(nonnull NSDictionary *)userInfo fetchCompletionHandler:(nonnull void (^)(UIBackgroundFetchResult))completionHandler{
  [RNFIRMessaging didReceiveRemoteNotification:userInfo fetchCompletionHandler:completionHandler];
}

     FCM.getFCMToken().then(token => {
       console.log("TOKEN (getFCMToken)", token);
       if(token !== '') {
        this.props.onChangeToken(this.props.user.userid, token, Platform.OS);
       }
     });

     if(Platform.OS === 'ios'){
       FCM.getAPNSToken().then(token => {
         console.log("APNS TOKEN (getFCMToken)", token);
         //this.props.onChangeToken(this.props.user.userid, token, Platform.OS);
         
       });
     }

     FCM.getInitialNotification().then(notif => {
       console.log("INITIAL NOTIFICATION", notif);
       /*FCM.presentLocalNotification({
         vibrate: 500,
         title: 'Welcome Back',
         body: 'Test Notification',
         big_text: 'i am large, i am large, i am large, i am large, i am large, i am large, i am large, i am large, i am large, i am large, i am large, i am large, i am large, i am large, i am large, i am large, i am large, i am large, i am large, i am large, i am large, i am large, i am large, i am large, i am large, i am large, i am large',
         priority: "high",
         sound: "bell.mp3",
         large_icon: "https://image.freepik.com/free-icon/small-boy-cartoon_318-38077.jpg",
         show_in_foreground: true
       });*/
     });

     this.notificationListener = FCM.on(FCMEvent.Notification, notif => {
       console.log("Notification", notif);
       FCM.presentLocalNotification({
         vibrate: 500,
         title: notif.header,
         body: notif.message,
         big_text: notif.longmessage,
         priority: "high",
         sound: "bell.mp3",
         large_icon: "ic_launcher",                           // Android only
         icon: "ic_launcher",
         click_action: "ACTION",                             // as FCM payload
        // badge: 10,                                          // as FCM payload IOS only, set 0 to clear badges
        // number: 10,                                         // Android only
        ///ticker: "My Notification Ticker",
        // large_icon: "https://image.freepik.com/free-icon/small-boy-cartoon_318-38077.jpg",
         show_in_foreground: true
       });
       if(notif.local_notification){
         
         return;
       }
       if(notif.opened_from_tray){
         return;
       }

       if(Platform.OS ==='ios'){
               //optional
               //iOS requires developers to call completionHandler to end notification process. If you do not call it your background remote notifications could be throttled, to read more about it see the above documentation link.
               //This library handles it for you automatically with default behavior (for remote notification, finish with NoData; for WillPresent, finish depend on "show_in_foreground"). However if you want to return different result, follow the following code to override
               //notif._notificationType is available for iOS platfrom
               switch(notif._notificationType){
                 case NotificationType.Remote:
                   notif.finish(RemoteNotificationResult.NewData) //other types available: RemoteNotificationResult.NewData, RemoteNotificationResult.ResultFailed
                   break;
                 case NotificationType.NotificationResponse:
                   notif.finish();
                   break;
                 case NotificationType.WillPresent:
                   notif.finish(WillPresentNotificationResult.All) //other types available: WillPresentNotificationResult.None
                   break;
               }
       }

       this.refreshTokenListener = FCM.on(FCMEvent.RefreshToken, token => {
         console.log("TOKEN (refreshUnsubscribe)", token);
         if(token !== '') {
           this.props.onChangeToken(this.props.user.userid, token, Platform.OS);
         }
         
       });

       // direct channel related methods are ios only
       // directly channel is truned off in iOS by default, this method enables it
       FCM.enableDirectChannel();
       this.channelConnectionListener = FCM.on(FCMEvent.DirectChannelConnectionChanged, (data) => {
         console.log('direct channel connected' + data);
       });
       setTimeout(function() {
         FCM.isDirectChannelEstablished().then(d => console.log(d));
       }, 1000);
     })

    } 
  }

**Comment by evollu** [comment]
you are calling `FCM.presentLocalNotification` in `FCM.on(FCMEvent.Notification, notif`, which if a infinite loop because local notification triggers the callback as well.

**Comment by rochapablo** [comment]
@evollu, but using Android should I keep the ```FCM.presentLocalNotification``` inside ```FCM.on(FCMEvent.Notification, notif```?

Because when I remove it stops to alert new messages.

**Comment by evollu** [comment]
what's your payload?

**Comment by rochapablo** [comment]
```
  {
    "body": "Boby test",
    "title": "Title test",
    "google.sent_time": 1512988245477,
    "from": "/topics/user-10",
    "google.message_id": "0:1...",
    "collapse_key": "com...",
    "fcm": {
      "action": null,
      "tag": null,
      "icon": null,
      "color": null,
      "body": "Boby test (fmc)",
      "title": "Title test (fmc)"
    }
  }
```

**Comment by evollu** [comment]
looks like you used basic firebase notification to send to android. right, there is no banner because firebase SDK only show notifications in the tray.
you need `custom_notification`. check readme
