### ISSUE TITLE
GoogleService-info.plist with different configurations

### ISSUE THREAD

**Issue by AstRonin** [evollu/react-native-fcm#684]
Is this library support using different configurations with different bundle identifier in **IOS**?

Now we have two configs **Debug** and **Release**. For example, I want to add new configuration **ReleaseCandidate**.
Bundle will be **com.example.releasecandidate**. So, I want create new **GoogleService-info.plist** for testing App separately of real App.

Please suggest, how I can use it?

**Comment by evollu** [comment]
You can either
1. create a new schema for releasecandidate and associate GoogleService-info.plist to that schema
2. replace your bundle name during build process, check out `plutil`

**Comment by AstRonin** [comment]
Thanks, 
But how I can associate GoogleService-info.plist to that schema? In that my actual problem...

**Comment by evollu** [comment]
there are multiple ways. 
on way is by clicking the file and check the target schema in right panel.
another way is choosing target schema when you drag and drop the file into project

you can google how to do it.

**Comment by AstRonin** [comment]
no..., I have only one target, but several schemes with different bundleID...
In google I found solutions with some changes in the code. But have we easy way using Xcode without disturbing a code?

**Comment by evollu** [comment]
confused. different scheme is different target. How does your `project->General` tab look like?

**Comment by AstRonin** [comment]
I do not need several targets... I use only one.
![som file](https://user-images.githubusercontent.com/2378239/33998332-a0d2cb00-e100-11e7-9617-d1e6d26ee781.png)

Bundle Id I changed in section **Build Settings**, filter -> Packaging -> Product Bundle Identifier

And for GoogleService-info I found this easy work solution:
https://medium.com/rocket-fuel/using-multiple-firebase-environments-in-ios-12b204cfa6c0

**Comment by evollu** [comment]
so that medium link solved your issue?

**Comment by AstRonin** [comment]
Yes, but will be good, if the library would had something similar from the box. On the other hand, I'm not a big expert in IOS, so maybe it has no sense...

**Comment by evollu** [comment]
this approach is similar to what I do and so far it works well
this is project level configuration so can't do much in this lib
