### ISSUE TITLE
TypeError: undefined is not a constructor (evaluating 'new Headers({ ... , ... })')

### ISSUE THREAD

**Issue by atpunk** [evollu/react-native-fcm#686]
"react": "16.0.0-alpha.3",
"react-native": "0.44.0",
"react-native-fcm": "^10.0.3",

Running on iPhone6 OS v10.2.1

I am able to receive remote notifications when using the Firebase console cloud messaging. However, I am unable to invoke the messages manually using the ios example code(firebaseClient.js)
```
let headers = new Headers({
          "Content-Type": "application/json",
          "Authorization": "key=" + FirebaseConstants.KEY
  	});```

**Comment by evollu** [comment]
have you replaced FirebaseConstants.KEY?

**Comment by atpunk** [comment]
Yes. Like your example, I am importing from FirebaseConstants.js.

**Comment by atpunk** [comment]
Then from the FirebaseConstants.js is have replaced the string with my own key.

**Comment by evollu** [comment]
Do you see alert saying send notification failed?

**Comment by atpunk** [comment]
No. It is unresponsive with the inclusion of **new Header**

**Comment by evollu** [comment]
unresponsive? meaning nothing shows up? then it means the notification has been sent to firebase successfully.

what is your sending payload?

**Comment by atpunk** [comment]
Unresponsive, meaning 
1.) I do not receive an Alert.alert that the KEY is wrong
2.) I do not receive an error that the notif did not send
3.) In my console.log, the message I get pertains the new Headers not being allowed to be a constructor.

If I set up the object like so...
```
let headers = {
  		"Content-Type": "application/json",
      "Authorization": "key=" + FirebaseConstants.KEY
  	};

		try {
			let response = await fetch(API_URL, { method: "POST", headers, body });
			console.log(response);
			try{
				response = await response.json();

				if(!response.success){
                                        console.log("RESPONSE SUCCESS?",response.success)
					Alert.alert('Failed to send notification, check error log')
				}
			} catch (err){
                                console.log("RESPONSE SUCCESS?",response.success)
				Alert.alert('Failed to send notification, check error log')
			}
		} catch (err) {
			Alert.alert(err && err.message)
		}
  }


```
I am then at least able to return the object in my console.log (response.success = undefined). It's seems that the **new Headers** is prevent the code from getting to the **try** method

**Comment by evollu** [comment]
That endpoint returns an xml instead of json so response.json() won't give you anything.
try `await response.text()` and see if you can get anything.

**Comment by atpunk** [comment]
<HTML>
<HEAD>
<TITLE>Unauthorized</TITLE>
</HEAD>
<BODY BGCOLOR="#FFFFFF" TEXT="#000000">
<H1>Unauthorized</H1>
<H2>Error 401</H2>
</BODY>
</HTML>

**Comment by atpunk** [comment]
```
YellowBox.js:71 Possible Unhandled Promise Rejection (id: 0):
TypeError: Headers is not a constructor
TypeError: Headers is not a constructor
    at FirebaseClient.send$ (http://192.168.27.139.xip.io:8081/index.ios.bundle?platform=ios&dev=true&minify=false:118806:18)
    at tryCatch (http://192.168.27.139.xip.io:8081/index.ios.bundle?platform=ios&dev=true&minify=false:24778:40)
    at Generator.invoke [as _invoke] (http://192.168.27.139.xip.io:8081/index.ios.bundle?platform=ios&dev=true&minify=false:24966:22)
    at Generator.prototype.(anonymous function) [as next] (http://192.168.27.139.xip.io:8081/index.ios.bundle?platform=ios&dev=true&minify=false:24803:21)
    at tryCatch (http://192.168.27.139.xip.io:8081/index.ios.bundle?platform=ios&dev=true&minify=false:24778:40)
    at invoke (http://192.168.27.139.xip.io:8081/index.ios.bundle?platform=ios&dev=true&minify=false:24836:20)
    at http://192.168.27.139.xip.io:8081/index.ios.bundle?platform=ios&dev=true&minify=false:24866:11
    at tryCallTwo (http://192.168.27.139.xip.io:8081/index.ios.bundle?platform=ios&dev=true&minify=false:14186:5)
    at doResolve (http://192.168.27.139.xip.io:8081/index.ios.bundle?platform=ios&dev=true&minify=false:14325:13)
    at new Promise (http://192.168.27.139.xip.io:8081/index.ios.bundle?platform=ios&dev=true&minify=false:14207:3)
```

This is the console.log I get when I attempt with the example code

**Comment by atpunk** [comment]
Does this have to do with my React and React-Native versions?

**Comment by evollu** [comment]
1. `Header is not a constructor` so you need to fix your code. check fetch library document
2. as you can see, you are getting 401 error from firebase so no notification.

nothing to do with versions

**Comment by atpunk** [comment]
Issue Solved.

I was unclear on which key to use in the FirebaseConstants.js

I was using my Web API Key when I actually needed my Project Settings->Cloud Messaging->Server Key.
