### ISSUE TITLE
Error: Argument list too long: recursive header  

### ISSUE THREAD

**Issue by jaysig** [evollu/react-native-fcm#688]
This error appears when I try to build my app. Any suggestions on how to fix it are appreciated.

Error: 
Showing All Messages
Argument list too long: recursive header expansion failed at .../node_modules/react-native-fcm/ios/../../../ios/Pods/React/node_modules/resolve/test/dotdot/abc.

1. What version of RN and react-native-fcm are you running?
"react-native": "^0.44.0",
"react-native-fcm": "^10.0.3"

2. What device are you using? (e.g iOS9 emulator, Android 6 device)?
iOS11

3. Is your app running in foreground, background or not running?
I can not start my app. I can not get the app to boot after upgrading fcm, my old version also no longer worked. I used the Cocoa Pods install method.

```
PodFile
target 'example' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Stripe
pod 'Stripe', '~> 11.2.0'
pod 'CodePush', :path => '../node_modules/react-native-code-push'
# Pods for CodePush
  # Your 'node_modules' directory is probably in the root of your project,
  # but if not, adjust the `:path` accordingly
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    # Add any other subspecs you want to use in your project
  ]
# Explicitly include Yoga if you are using RN >= 0.42.0
 pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
 pod 'FirebaseMessaging'

# inherit! :search_paths

end
```

![screenshot 2017-12-11 12 05 24](https://user-images.githubusercontent.com/4924440/33846233-a2aa10f6-de6b-11e7-9eb7-5917e0fbfcb6.png)

**Comment by evollu** [comment]
in RNFIRMessaging's project settings there are `framework search path` and `header search path` which includes /Pods with `recursive`, change it to `non-recursive` and try

**Comment by evollu** [comment]
ok the problem is you have React in your Pod folder, which introduce too deep path.
You have to use Pod to use react native?

**Comment by evollu** [comment]
@jaysig try master branch, it should work for you now

**Comment by jaysig** [comment]
I cleaned up my podfile to this
```
pod 'Stripe', '~> 11.2.0'
# Pods for CodePush
  # Your 'node_modules' directory is probably in the root of your project,
  # but if not, adjust the `:path` accordingly

# Explicitly include Yoga if you are using RN >= 0.42.0

 #pod 'Firebase/Core'
 pod 'FirebaseMessaging'

inherit! :search_paths
```
Then upgraded to latest version of rn-fcm but it errors at ```RNFIRMessaging.h' file not found```. I have it linked in the Link Binary with Libraries; so, any other suggestions?

**Comment by evollu** [comment]
you can do `npm install react-native-fcm@git://github.com/evollu/react-native-fcm#master`

**Comment by jaysig** [comment]
I just copied that and I get ```no matches found: react-native-fcm@git://github.com/evollu/react-native-fcm#master```

**Comment by evollu** [comment]
how does your Pods folder look like

**Comment by jaysig** [comment]
<img width="623" alt="screenshot 2017-12-12 13 41 56" src="https://user-images.githubusercontent.com/4924440/33904802-4e423692-df42-11e7-88aa-75c16421bb68.png">

I think it looks the same as yours

**Comment by evollu** [comment]
let me update the example and see

**Comment by jaysig** [comment]
As far I can tell, Pods folder has everything it should. I have tried the Podfile two ways

Error: Can't find RNFIRMessaging.h
```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'project' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'Firebase/Messaging'
  # Pods for Stripe
pod 'Stripe', '~> 11.2.0'
# Pods for CodePush
  # Your 'node_modules' directory is probably in the root of your project,
  # but if not, adjust the `:path` accordingly

inherit! :search_paths

end
```

Error: Can't find Firebase Core
```
target 'project' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Stripe
pod 'Stripe', '~> 11.2.0'
# Pods for CodePush
  # Your 'node_modules' directory is probably in the root of your project,
  # but if not, adjust the `:path` accordingly

  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'BatchedBridge', # Required For React Native 0.45.0+
    'Core',
    # Add any other subspecs you want to use in your project
  ]

inherit! :search_paths

  pod 'react-native-fcm', :path => '../node_modules/react-native-fcm'

end
```

**Comment by evollu** [comment]
can you create a public repo that has the issue? Can't reproduce here

**Comment by Ghostrick** [comment]
I am having this problem, too.

**Comment by evollu** [comment]
@Ghostrick can you try the master branch or provide a repo with this issue?

**Comment by jaysig** [comment]
I ended up just reverting everything backwards, and it works now. Not sure what happened by thanks again for your help.

**Comment by Luckygirlllll** [comment]
I have the same issue with react-native-fcm, how to fix that?
