### ISSUE TITLE
BundleIdentifier (Question)

### ISSUE THREAD

**Issue by KwangsubAhn** [evollu/react-native-fcm#689]
When opening an issue, please include following information for better support

1. What version of RN and react-native-fcm are you running? 0.48.4, 9.6.2
2. What device are you using? (e.g iOS9 emulator, Android 6 device)? iPhone SE (iOS9)
3. Is your app running in foreground, background or not running? yes

I have an app, which work perfectly fine in Android version. But I am not getting notification in iOS. It can get token but not able to send FCM message or getting notification. 

I am suspicious about my setting of BundleIdentifier. in 'GoogleService-Info.plist', BUNDLE_ID is set as com.mycompany but in 'Info.plist', CFBundleIdentifier is set as org.reactjs.native.example.$(PRODUCT_NAME:rfc1034identifier) which might be wrong. But The BundleIdentifier was set automatically so I am confused. Do I have to change the CFBundleIdentifier setting?

----

Also another question. in iOS to get push notification, do I have to put my app on testFlight so I can install the app on actual device and test the push notification? I was trying to test on simulator but it seems like impossible but putting the app on testFlight to test push notification seems inefficient too because I have to wait several days to get it approved?

**Comment by evollu** [comment]
yes you need to change CFBundleIdentifier  to match. `org.reactjs.native.example.$(PRODUCT_NAME:rfc1034identifier)` is just auto generated by react native.

you just need to install in real device.

**Comment by KwangsubAhn** [comment]
Thanks!
