### ISSUE TITLE
ios push notification setting is not shown after install the app

### ISSUE THREAD

**Issue by KwangsubAhn** [evollu/react-native-fcm#692]
Before openning an issue
1. Reproduce it with the example project in this repo.
2. If you can't receive iOS notification, make sure you can receive notification using quickstart-ios project provided by Firebase team

When openning an issue, please include following information for better support

1. What version of RN and react-native-fcm are you running? 0.48.4   9.6.2
2. What device are you using? (e.g iOS9 emulator, Android 6 device)? ios11  device
3. Is your app running in foreground, background or not running? running both

------------

I followed the instructions, and successfully archived my app and installed on my actual device. But push notification setting of the app in my device doesn't show up.

I have checked following. 
Xcode - [My App] -> Capabilities -> Push Notification (on), Background mode Remote Notification (on)
Also I checked that in Apple Development account, Provisioning Profile and App Id displaying Push Notification Enabled.

Did I missing something to enable Push Notification? Don't know what else I can investigate to do that.

Do I need to follow below link too?
https://facebook.github.io/react-native/docs/pushnotificationios.html#content

- Android version is working perfectly fine

**Comment by evollu** [comment]
have you add your app key in firebase?

**Comment by KwangsubAhn** [comment]
not sure exactly what app key means, but I created ios app in firebase console, and downloaded .plist file replacing to the folder.

**Comment by evollu** [comment]
in firebase 
SETTINGS->CLOUD MESSAGING->iOS app configuration
there is APNs Authentication Key

**Comment by KwangsubAhn** [comment]
Yes, I can see APNs Authentication Key is set. Is there anything to do with the Key?

**Comment by KwangsubAhn** [comment]
Just curious, my bundle id can be an issue for this. I set my my bundle id like 'com.mycompany' but I found that mostly it is set as 'com.mycompany.MyAppName'.

**Comment by evollu** [comment]
ok. they have to match

**Comment by KwangsubAhn** [comment]
Forgot to add
FCM.requestPermissions().then(()=>console.log('granted')).catch(()=>console.log('notification permission rejected'));
