### ISSUE TITLE
Not getting Push Notification iOS

### ISSUE THREAD

**Issue by KwangsubAhn** [evollu/react-native-fcm#693]
1. What version of RN and react-native-fcm are you running? 0.48.4 , 9.6.2
2. What device are you using? (e.g iOS9 emulator, Android 6 device)? iPhoneSe iOS11.1.1 
3. Is your app running in foreground, background or not running? 

I am trying to send a push notification from firebase console to my ios device but not getting it.

I have checked, I am getting FCM token, APNs token and also I turned on Push Notification setting in my device.

When I look into Firebase console Dashboard, I see active users which might be my device. But if I send a push notification and click the message, the graph said the message is sent to 0 person. APNs Auth Key is uploaded well too.

I am thinking it might be an issue of iOS version. does this library work well with iOS 11.1.1?

**Comment by evollu** [comment]
yes it should work.

try send to api endpoint?

**Comment by KwangsubAhn** [comment]
yes there is no problem with the iOS version but I mistook on my code side.

**Comment by DpkJacob** [comment]
@KwangsubAhn can you elaborate on how you solved the issue because i am facing sort of the same problem.
