### ISSUE TITLE
Android 8 Support

### ISSUE THREAD

**Issue by Jallynme** [evollu/react-native-fcm#698]
for Android 5 & 6 it's working fine but for Android 8 Device I cann't get any notification

**Comment by evollu** [comment]
what is your build target SDK? android 8?

**Comment by Jallynme** [comment]
Hi I use 26.0.0 for android 8

**Comment by evollu** [comment]
might have to do with new SDK broadcasting limitation.
are you using the latest version of react-native-fcm?

**Comment by evollu** [comment]
try change your target SDK to be 25.

**Comment by evollu** [comment]
well I've figured how to bridge the new change, but can't upgrade `com.android.support:support-core-utils` to >26 as the app crashes.

Any help to solve this problem is welcome.

**Comment by Jallynme** [comment]
I use latest version of react-native-fcm so thanks for update

**Comment by haggholm** [comment]
I successfully built and ran the sdk-26 branch and verified it on two images (SDK 25 and 27, before and after the API changes to ensure compatibility), after making some small fixes (https://github.com/evollu/react-native-fcm/pull/726). I didn’t see any crashes.

**Comment by evollu** [comment]
@haggholm Have you tried to use it together with other packages that uses firebase SDK like react-native-firebase? any resolution challenge?

**Comment by haggholm** [comment]
No, I don’t think the application uses Firebase except for this.

**Comment by haggholm** [comment]
@evollu I haven’t tried the example project—I’ll find a moment to do so, but when I was trying things out, I was somewhat urgently trying to get our own product running!

**Comment by evollu** [comment]
@haggholm if you want to target sdk 26 now you can use this `sdk-26` branch.
But there is risk as react-native itself may not fully support compiling against sdk 26.

**Comment by dashracer** [comment]
@evollu I've used `sdk-26` branch but the local notification not working

**Comment by evollu** [comment]
@dashracer did you register your notification channel?

**Comment by chanramadhan** [comment]
i'm send push use PHP

**Comment by evollu** [comment]
@chanramadhan have you set default notification channel for firebase notifications?

**Comment by chanramadhan** [comment]
@evollu i set High in my notification channel but not work in android 8 (Galaxy S8), can you help me?

**Comment by evollu** [comment]
@chanramadhan are you talking about remote notificaiton? if so, do you have this?
`<meta-data android:name="com.google.firebase.messaging.default_notification_channel_id" android:value="my_default_channel"/>`

**Comment by chanramadhan** [comment]
@evollu yes, i have this <meta-data android:name="com.google.firebase.messaging.default_notification_channel_id" android:value="my_default_channel"/>

in my androidmanifest. but not work in android 8

**Comment by colinwitkamp** [comment]
The below solution worked for me!
`channel` should be passed.
```
const notificationChannelId = 'my_notif_channel';

await FCM.createNotificationChannel({
    id: notificationChannelId,
    name: notificationChannelId,
    priority: 'max'
  });
...

FCM.presentLocalNotification({
   ..(notification parameters),
    channel: notificationChannelId
  })

```

**Comment by kaytee319** [comment]
**"FIXED"**
In your notification payload set "channel":

{
   "to":"fcm_token",
   "data": {
       "custom_notification": {
       "body": "Hey There",
       "title": "I am APP",
       "color":"#00ACD4",
       "priority":"high",
       "icon":"ic_notif",
       "channel": "default",
       "groupSummary": true,
       "show_in_foreground": true
       }
   }
}

**Comment by 404sand808s** [comment]
Thanks @kaytee319, for some reason this advice you just gave is extremely hard to find elsewhere on the interwebs!

**Comment by wmonecke** [comment]
Hey!
`.createNotificationChannel()` is not available on my FCM object. Do I need to upgrade?

**Comment by rajeshsmallarc** [comment]
Yes @wmonecke
