### ISSUE TITLE
Android - Windows - Ignite -  App sttuters if I use react-native-fcm and Remote JS Debugger at the same time

### ISSUE THREAD

**Issue by degroote22** [evollu/react-native-fcm#70]
Weird bug.
If I just import the this JS module onto my rn component and provide the lifehooks methods (exactly what the tutorial tells to do) AND turn on remote debugging the JS UI stutters a lot(switching 'views' take 5s).  Disabling each one (remote js debug on chrome or using the fcm module) makes the problem disappear.

Having this installed and linked and configured on the android specific files produces no effect.

I'm using Ignite and it has a lot of stuff besides React Native. I will try to replicate the issue on a clean build and try to determine what may be doing this.
For those who don't know, [Ignite ](https://github.com/infinitered/ignite)is a react-native boilerplate that comes with redux, navigator and a lot of other stuff installed.

**Comment by evollu** [comment]
I have similar issue. And I'm not using Ignite. Let me know if you find anything

**Comment by degroote22** [comment]
The issue doesn't happen on a real device. But it happens on both Android Studio and Genymotion emulators.

**Comment by evollu** [comment]
me too. have you tried using Firebase library without this react native module?

**Comment by sibelius** [comment]
@degroote22 is this still relevant?

**Comment by evollu** [comment]
pls reopen this this issue still exists

**Comment by degroote22** [comment]
I'm sorry guys but I've completely missed this notification. I'm going to give it a look on the next couple weeks and provide feedback here.
Thanks for the attention and please excuse me for not answering earlier.
