### ISSUE TITLE
App icon showing unread messages

### ISSUE THREAD

**Issue by rochapablo** [evollu/react-native-fcm#700]
1. What version of RN and react-native-fcm are you running?
```10.0.3```

2. What device are you using? (e.g iOS9 emulator, Android 6 device)?
```iOS 11 device```

3. Is your app running in foreground, background or not running?
```app running in foreground and background```

I don't know why, but since I start to implement ```react-native-fcm``` I'm getting this unread bullet, but I don't have those ten unread items.

![](https://i.imgur.com/RRAINSm.png)

**Comment by evollu** [comment]
do you have `number: 10` in your local or remote notification payload?

**Comment by rochapablo** [comment]
Oops, my bad, I was using

```
this.badge = data.badge || 10 // as FCM payload IOS only, set 0 to clear badges
```

By the way, when I open the app, shouldn't the badge update to 0 automatically? Do I have to send 0 every time otherwise wouldn't be cleaned?
