### ISSUE TITLE
[Android] exit app using exitApp() backhandler error "ExceptionsManager.js:63 this.notificationListener is not a function"

### ISSUE THREAD

**Issue by rusliabdulgani** [evollu/react-native-fcm#701]
when i use fcm and want to close app using exitApp() backhandler, then when app close, will get app stopped, and show error in debugger like this "ExceptionsManager.js:63 this.notificationListener is not a function"

**Comment by evollu** [comment]
my guess:
you have `this.notificationListener();` but it should be`this.notificationListener.remove();`

**Comment by rusliabdulgani** [comment]
thankssss it's works... before i think if i do notificationListener.remove() then all notification cannot run properly, but it's still works. thanks guru... :)
