### ISSUE TITLE
module 'FirebaseCore' not found on 11.0.1

### ISSUE THREAD

**Issue by jjdp** [evollu/react-native-fcm#704]
RN 0.51, RN-FCM 11.0.1

tried downloading new firebase libraries and replacing old ones in pods, clearing everything (xcode, node_modules, xcode derived data), relinking with reac-native-link nothing works

Note that I don't use cocoapods

Still give's me:

```
node_modules/react-native-fcm/ios/RNFIRMessaging.h: Analyzer skipped this file due to parse errors

node_modules/react-native-fcm/ios/RNFIRMessaging.h:4:9: fatal error: module 'FirebaseCore' not found
```

**Comment by evollu** [comment]
it is related to 11 update that I changed the header path.
What do you put your framework files

**Comment by jjdp** [comment]
$(PROJECT_DIR)/Pods non-recursive

**Comment by evollu** [comment]
i mean where are the files physically. it needs to be under `/ios/Frameworks`

**Comment by evollu** [comment]
copy answer from react-native-push-notification

You MainApplication is not correct. If you create a new react native project (with react-native init AwesomeProject) you'll see what it should look like. Basically you need to implement ReactApplication, the getPackages method need to be moved inside an anonymous inner ReactNativeHost:
```
public class MainApplication extends MultiDexApplication implements ReactApplication {

...

    private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
        @Override
        public boolean getUseDeveloperSupport() {
            return BuildConfig.DEBUG;
        }

        @Override
        protected List<ReactPackage> getPackages() {
            return Arrays.<ReactPackage>asList(
                    new MainReactPackage(),
                    ... you dependencies go here
            );
        }
    };
```

**Comment by jjdp** [comment]
oh i see. it's still in ios/Pods. shouldnt that be changed?

**Comment by evollu** [comment]
just updated the readme

**Comment by dooboolab** [comment]
@jjdp @evollu 
Having same issue. I don't understand this could someone help? I am using cocoapods (expo detached app)

**Comment by Jithinag007** [comment]
still error

**Comment by jjdp** [comment]
i have no idea. mine built when i moved to Frameworks. note that i don't use cocoapods

**Comment by evollu** [comment]
@dooboolab @Jithinag007 are you using cocoapods? please provide an example project that fails

**Comment by flyingxu** [comment]
I reverted to v10.0.3

**Comment by adesmet** [comment]
Thanks @flyingxu, that error seems fixed. Now I'm getting 'React/RCTEventEmitter.h' file not found, so back to scouting around for solutions :p

**Comment by Bernhard---H** [comment]
@evollu I created a very simple example app that fails to build, with react native 0.51.0 and react-native-fcm 11.2.0 
https://github.com/Bernhard---H/fcmTestApp

**Comment by evollu** [comment]
cool I will take a look

**Comment by evollu** [comment]
@Bernhard---H you installed react-native-fcm as a Pod project.
It is supposed to be linked as a Library
https://facebook.github.io/react-native/docs/linking-libraries-ios.html

**Comment by Titozzz** [comment]
I'm running in the same issue, i'll see what i can do @evollu

**Comment by Titozzz** [comment]
Got it, fixed it by using Cocoapods 1.4 and static_framework=true
Will submit a PR, if you guys can try it and tell me if this works

**Comment by evollu** [comment]
@Titozzz sounds great!

**Comment by drailanjohngss** [comment]
How to manually link react-native-fcm? 
I'm a cocoapods user. 
What have I done: 
1. npm install --save react-native-fcm 
2. react-native link react-native-fcm
3. added this to my podfile 
```
pod 'Firebase/Core'
pod 'Firebase/Firestore'
pod 'Firebase/Messaging'
pod 'react-native-fcm', :path => '../node_modules/react-native-fcm'

```
4. Run pod install
5. Run pod update
6. Run pod install --repo-update
7.  Imported the RNFIRMessaging.xcodeproj to xcode/libraries
8. imported the libRNFIRMessaging.a to Build Phases

What am I doing wrong?

**Comment by Bernhard---H** [comment]
@drailanjohngss I did this instead of manual linking:

0. move `Podfile` into a different directory
1. npm install --save react-native-fcm
2. react-native link react-native-fcm
2b. move `Podfile` back into the `ios` folder
3. add only this to my podfile:
```
    pod 'FirebaseMessaging'
```
4. Run pod install

and you're done

**Comment by drailanjohngss** [comment]
I have followed your steps @Bernhard---H  but now i'm getting this error:

``` Library not found for -iGoogleToolBoxForMac ```

**Comment by Bernhard---H** [comment]
@drailanjohngss I'm new to app development in general, so no idea what went wrong - maybe someone else can help?

**Comment by evollu** [comment]
`How to manually link react-native-fcm?`
check read me.

**Comment by drailanjohngss** [comment]
I have done manual linking but still can't get it to work, im getting the 
```
Library not found for -|GoogleToolBoxForMac 
```
error, please help. 

Steps I made: 
1. npm install --save react-native-fcm
2. Followed the manual linking: 
-Go to node-module/react-native-fcm/ios then copied the RNFIRMessaging.xcodeproj
-Pasted it on the Xcode/Libraries
-Go to Build Settings added 
```
$(SRCROOT)/../node_modules/react-native-fcm/ios
```
-Go to Build Phases, link binary with libraries found the libRNFIRMessaging.a
-Then go to ios/Podfile
-Added 
```
pod 'Firebase/Messaging'
```
-Then run pod install
-Then Build
-Then error appears. 

Help me please.

**Comment by ikhsanalatsary** [comment]
@Bernhard---H its works on me

**Comment by Stettinum** [comment]
@drailanjohngss, if you are using newest version of react-native-fcm try to add 4.0 version of firebase core: 

`pod 'Firebase/Core', '4.0.0'` this do the trick for me...
my cofig: 
```
  pod 'Firebase/Core', '4.0.0'
  pod 'Firebase/Messaging'
  pod 'react-native-fcm', :path => '../node_modules/react-native-fcm'
```

do that trick: 
#import <FirebaseCore/FirebaseCore.h>
//import FirebaseCore;
#import <FirebaseMessaging/FirebaseMessaging.h>
//import FirebaseMessaging;
//import FirebaseInstanceID;
#import <FirebaseInstanceID/FirebaseInstanceID.h>

in RNFIRMessaging.h

**Comment by damathryx** [comment]
@Stettinum 
```
  pod 'Firebase/Core', '4.0.0'
  pod 'Firebase/Messaging'
```

worked for me

**Comment by Stettinum** [comment]
@damathryx nice to hear that ;)
