### ISSUE TITLE
[question] Can you provide example for expo detached app?

### ISSUE THREAD

**Issue by dooboolab** [evollu/react-native-fcm#705]
I am not sure where to put GoogleService-Info.plist in expo detached project.
I've been suffering for this whole day and need help to integrate this library to expo detached project. Hope somebody can help me..
<img width="531" alt="2017-12-22 12 28 28" src="https://user-images.githubusercontent.com/27461460/34262215-0ee8c0dc-e6af-11e7-9b29-6f5c30f456df.png">

**Comment by evollu** [comment]
it doesn't matter where you put it physically. you need to make sure it gets copied into binary during build.
<img width="691" alt="screen shot 2017-12-21 at 10 31 41 am" src="https://user-images.githubusercontent.com/9213224/34262364-36a0dc74-e63a-11e7-886e-0e6cfb6698cc.png">

**Comment by dooboolab** [comment]
@evollu 
Thanks I've just done it and still can't resolve my problem.
```
FCM.getFCMToken().then((token) => {
  console.log(token);
})
```

token is always undefined.

**Comment by evollu** [comment]
check your native log in xcode. it should state what is wrong with firebase

**Comment by dooboolab** [comment]
@evollu
I've just tried it, and it just says undefined and nothing is showing related to firebase. If I am using cocoapods I don't need to do anything in xcode am I right? What I've just done is install FirebaseMessaging in podfile.

**Comment by dooboolab** [comment]
Nevermind. I just included below codes provided for without cocoapods support and it works fine now. Thanks for help.
