### ISSUE TITLE
ARRIVED TWO NOTIFICATION AND NOT ONE, duplicated!

### ISSUE THREAD

**Issue by Brhernann** [evollu/react-native-fcm#708]
Hi, i have a problem with FCM! when i send a notification,  two notification arrive to my mobile and not one, how? this is my code:

` this.notificationListener = FCM.on(FCMEvent.Notification, async notif => {
      this.setState({my_noty: notif}) if(notif.opened_from_tray){
        console.log('OPEN')
        FCM.setBadgeNumber(0); 
        this.FirebaseConnect(notif);
      }
      FCM.setBadgeNumber(1); 
      this.FirebaseConnect(notif);
    });
  }`

` componentWillUnmount() {
    this.notificationListener.remove();
}`

in AndroidManifest.xml:

`<service android:name="com.evollu.react.fcm.MessagingService" android:enabled="true" android:exported="true">
      <intent-filter>
        <action android:name="com.google.firebase.MESSAGING_EVENT"/>
      </intent-filter>
      </service>

    <service android:name="com.evollu.react.fcm.InstanceIdService" android:exported="false">
      <intent-filter>
        <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
      </intent-filter>
    </service> 

      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustResize"
        android:launchMode="singleTop">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>`

![foto](https://user-images.githubusercontent.com/18491638/34275253-3f8c5ab6-e67b-11e7-892a-b15a5129ec4d.jpeg)

Please help!

**Comment by evollu** [comment]
are you using the latest version of the package?

**Comment by Brhernann** [comment]
i use the version 7.4.0

**Comment by evollu** [comment]
try latest?

**Comment by Brhernann** [comment]
i updated to version 11 and the same problem :o

**Comment by evollu** [comment]
try reproduce with example project

**Comment by Brhernann** [comment]
i found the problem!, this is in AndroidManifest.xml, the notifications is duplicate because i have this lines that receive the notification and also has FCM

`      `

i removed this and now arrive only a one notification, thanks.
