### ISSUE TITLE
Build in IOS Error [ module UserNotifications not found ]

### ISSUE THREAD

**Issue by andaGS** [evollu/react-native-fcm#709]
i was install and run in ios, but there is error module UserNotifications not found

**Comment by evollu** [comment]
you need to build with latest SDK and xcode

**Comment by andaGS** [comment]
react-native: 0.44.0
xcode 7.2

is it possible to use this plugin?

**Comment by evollu** [comment]
@andaGS yes

**Comment by evollu** [comment]
@andaGS no. you need xcode 9
