### ISSUE TITLE
issue parsing notif getting object but getting error when trying to parse the json in "android" 

### ISSUE THREAD

**Issue by atul-forbinary** [evollu/react-native-fcm#710]
not able to parse notif object , i did Stringfy to get the json data but not able to fetch the value

**Comment by evollu** [comment]
please list your payload, os here.

**Comment by atul-forbinary** [comment]
sending notification for single device using token , failed from fcm ...????

**Comment by atul-forbinary** [comment]
please reply if you have any idea about the same ......
