### ISSUE TITLE
java.util.zip.ZipException: 

### ISSUE THREAD

**Issue by runeogod** [evollu/react-native-fcm#712]
Hello, i cant manage to start my app after installing FCM.

This is the error i have : 
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/google/android/gms/common/internal/zzd.class

Any idea?

Thanks,

Regards

**Comment by runeogod** [comment]
Seems to come from this :     compile 'com.google.firebase:firebase-core:10.0.1'
Maybe be present in expo.

Any way to isolate it ?

**Comment by evollu** [comment]
you need to resolve conflicts of dependency. some other libraries that you depends on relies on different version of firebase

**Comment by runeogod** [comment]
@evollu im using Expo, any idea how to handle the different version with this firebase? i tried some exclude but none worked

**Comment by evollu** [comment]
try this https://medium.com/@suchydan/how-to-solve-google-play-services-version-collision-in-gradle-dependencies-ef086ae5c75f

**Comment by runeogod** [comment]
Did what he said, now i have : 

> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/google/android/gms/internal/zzcn.class

its so depressing x)

**Comment by evollu** [comment]
looks like you haven't fixed all your conflicts

**Comment by runeogod** [comment]
@evollu I have removed entirely EXPO, now it successfully build, going to config it, i will feedback if it work .

Thanks
