### ISSUE TITLE
Build error on iOS (Non Cocoapod)

### ISSUE THREAD

**Issue by vinXpro** [evollu/react-native-fcm#713]
I using Non Cocoapod & put frameworks under ios/Frameworks folder.
Any Idea?

`Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_SKPaymentQueue", referenced from:
      objc-class-ref in FirebaseAnalytics(FIRAInAppPurchaseTransactionReporter_51b6624ff1330bf43a3ed7d9ba76e1ba.o)
  "_OBJC_CLASS_$_SKProductsRequest", referenced from:
      objc-class-ref in FirebaseAnalytics(FIRAProductsRequest_b9979194c8f29313114f911734ebc0e8.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by evollu** [comment]
link issue? have you put the frameworks into your project?

**Comment by vinXpro** [comment]
yes. I checked in xcode and its has been linked

**Comment by evollu** [comment]
try `rm -rf ~/Library/Developer/Xcode/DerivedData`?

**Comment by iMagdy** [comment]
I'm getting the same error, but for the `FirebaseAnalytics` part, if you add `#import "Firebase.h"` to the top of `AppDelegate.m` you'll end up with one error regarding `_OBJC_CLASS_$_RNFIRMessaging` like what I'm having now.

Any idea? @evollu 

![image](https://user-images.githubusercontent.com/611426/34411242-3a988080-ebde-11e7-9314-1d640f41d956.png)

**Comment by iMagdy** [comment]
I ran `react-native link ....` and `react-native unlink` again and it cleared the above issue!

Now I have this:

![image](https://user-images.githubusercontent.com/611426/34411621-7b051bd6-ebe0-11e7-9869-4fdbf9e97943.png)

**Comment by evollu** [comment]
https://stackoverflow.com/questions/10448589/this-target-might-include-its-own-product

**Comment by iMagdy** [comment]
Doing manual linking fixed the issue for me, it seem something wrong with react-native auto linking.

**Comment by evollu** [comment]
it has been not working for months

**Comment by vinXpro** [comment]
> rm -rf ~/Library/Developer/Xcode/DerivedData
this worked for me

**Comment by niocncn** [comment]
same here

**Comment by EstebanBP** [comment]
@vinXpro @niocncn 
Took me like 4 hours to fix this.
![captura de pantalla 2018-02-06 a las 13 56 47](https://user-images.githubusercontent.com/23704234/35860827-c6441f82-0b45-11e8-8198-f5ffb9954614.png)

**Comment by rohitgoyal** [comment]
Why is it necessary to add Storekit though? 
I don't have In-app purchases in my app.

**Comment by evollu** [comment]
I don't think StoreKit is the issue. the example project doesn't have that.
The original issue seems to be solved?
