### ISSUE TITLE
Pod init SSL certificate issue in iOS

### ISSUE THREAD

**Issue by MSSPL-PiyaleeMaiti** [evollu/react-native-fcm#715]
POD init Issue:
  1. While installing the fcm library and when we use to install via pod then we are getting SSL certificate issue.
  2. after searching the net we found that its due to if some certificate expires but in our case it's working and showing trusted. 
  https://stackoverflow.com/questions/18964175/how-to-fix-curl-60-ssl-certificate-invalid-certificate-chain/19706191#19706191 

![screen shot 2017-12-21 at 7 43 58 pm](https://user-images.githubusercontent.com/20696057/34383139-3b8ef186-eb39-11e7-88a0-846262e7d161.png)

1. RN - 0.44 and react-native-fcm - 6.2.3
2. iOS simulator

**Comment by evollu** [comment]
installing `FirebaseAnalytics` failed. so it is saying Google's ssl has issue (which is more likely your network has issue). perhaps use another network?

**Comment by MSSPL-PiyaleeMaiti** [comment]
@evollu  I have tested in two IMAC machine with same network router. In one machine it's working and on another machine it's not. 

**Are these configurations correct?**
**My system info:**
Os version - 10.12.6 Macos sierra
Node - 7.2.0
Npm- 5.0.4
Pod - 1.3.1
react-native-cli: 2.0.1
react: 16.0.0-alpha.6,
react-native: 0.44.0,
react-native-fcm: ^6.2.3
Xcode: 9.1

And please tell me about manual  pod install specific required version for me.

I want to know following for installing **react native fcm** with my **react native version 0.44**:

**firebase sdk version** = ?
**react-native-fcm version** = ?

**Comment by evollu** [comment]
you can use latest version for both.
as for ssl error, it has to do with your network. can't help here
