### ISSUE TITLE
[Android] No notification after device restarts OR after leaving device idle for a very long time

### ISSUE THREAD

**Issue by Kabangi** [evollu/react-native-fcm#721]
RN version:- 0.50
REACT-NATIVE-FCM Version: 11.0.1
Android device:- 7.0

When I start the application, I receive Push Notification in the app if it's running, or in the android notification bar if the app is running in background.

But if I restart the phone or leave it idle for hours, I cannot receive any notification anymore. I have to open the app for at least once to start receiving notifications again.

I have also tried to send notifications using Firebase console just to test if this is a case of silent payload issue and I receive the notifications just fine.

My payload looks like this:-
 ```
{
  "to":"FCM_TOKEN",
  "priority" : "high",
  "content_available" : true,
  "data": {
    "custom_notification": {
      "body": "test body",
      "title": "test title",
      "color":"#00ACD4",
      "priority":"high",
      "icon":"ic_notif",
      "group": "GROUP",
      "id": "id",
      "show_in_foreground": true
    },
    content: {
    }
  }
}
```

**Comment by evollu** [comment]
what brand android device are you using

**Comment by Kabangi** [comment]
Thanks for response am using:- TECNO CX Air android 7.0

**Comment by evollu** [comment]
are you using expo?

**Comment by Kabangi** [comment]
No

**Comment by evollu** [comment]
to clarify, your phone can receive remote notification just fine (using custom_notification) after reboot but can't have delayed notification?

**Comment by Kabangi** [comment]
Yes that's right remote notifications working just fine until I do a hard reboot. Works fine with quick reboot.

**Comment by evollu** [comment]
I think we are not one the same page. you mean following?

reboot | type | work
--- | --- | ---
no | custom_notification | yes
yes | custom_notification | no
yes | firebase standard notif | yes

**Comment by evollu** [comment]
@Kabangi any updates?

**Comment by Kabangi** [comment]
Sorry, took a break from work. 

Yes. Turns I had two issues on my end:-
1. I had missed sending title and body as part of custom_notification payload.
2. The devices I was testing on had another layer of protection against `WAKE_LOCK`. The protection being I had to add my app to protected list and also allow it to `auto-start` from another app that comes preinstalled on the device.

**Comment by EdwardQuixote** [comment]
@Kabangi How did you solve your second issue?
I'm currently facing the same problem for a critical App. A broadcast I'm having can't start a service and all I'm getting is `Auto-start Limit`.
