### ISSUE TITLE
Wake on Notification on Android

### ISSUE THREAD

**Issue by oiojin831** [evollu/react-native-fcm#722]
This might not be an issue...
I don't know where to ask this.
So I made my android push notification worked, however I want to wake my android devise screen on when I receive the push notification. I get sound and vibrate, I just need to turn on the screen.

I am a ios user, so it might not understand how android handles push notifications...
Please help me with this :D 
Thanks

**Comment by evollu** [comment]
priority: 'high' or 'max'
there could be an phone setting regarding waking up the screen as well

**Comment by oiojin831** [comment]
Thanks for the fast reply.
I tried with 'high' and 'max' but not working...
I enable every notification setting but still no luck..
I am using galaxy 6 with android 7.0
Don't I need to set Wake_ON? on android native code?
and just for more information this is may payload(using custom_notification)

    "custom_notification": {
      "body": "test body",
      "title": "test title",
      "color":"#00ACD4",
      "priority":"max",
      "icon":"ic_notif",
      "group": "GROUP",
      "id": "id",
      "sound": "default",
      "show_in_foreground": true,
      "content_available":true
    }

**Comment by evollu** [comment]
seems that is designed behavior of some device?
there is even an app for that Glimpse Notifications

**Comment by oiojin831** [comment]
I am sorry, It was ```wake_lock```
I read that if I want to wake the screen, I need to write a Native code to achieve this.

**Comment by evollu** [comment]
try add that permission and see. if it works then I will update readme

**Comment by oiojin831** [comment]
I added
```<uses-permission android:name="android.permission.WAKE_LOCK" />```
in ```android/app/src/main/AndroidManifest.xml``` and still no luck..

**Comment by evollu** [comment]
do you have any other device to try?

**Comment by oiojin831** [comment]
No, but I can try with the emulator.

**Comment by oiojin831** [comment]
I just tried with Pixel_API_27 and It's not working either.

**Comment by evollu** [comment]
quick question. how does other android apps perform? like facebook, do they wake up the screen?

**Comment by oiojin831** [comment]
Since I am ios user(never used android), I am not sure..
As far as I researched, usually android app doesn't wake up the screen.
However, message app like telegram or whatsapp might have settings that enabling wake up screen.

**Comment by oiojin831** [comment]
I found this stackoverflow answering how to wake up screen when push is coming

https://stackoverflow.com/questions/9631869/light-up-screen-when-notification-received-android

can anyone help me implementing this natively( or js if possible)

**Comment by evollu** [comment]
will do. and I will add a new property called `wake_screen`

**Comment by evollu** [comment]
published as v11.1.0

**Comment by Noitidart** [comment]
I am using 14.0.0 - mine is not waking. Do I need to include some permission?

**Comment by NinoMartino** [comment]
hello, I've checked that wake_screen is already in the source code, but how to use it? I already add wake_screen inside the payload, but still no luck.

**Comment by Noitidart** [comment]
@NinoMartino i also couldn't figure it out.
