### ISSUE TITLE
[Android] Scheduled notifications are not fired after rebooting the phone

### ISSUE THREAD

**Issue by germanst** [evollu/react-native-fcm#723]
RN version: 0.50.3 (same issue with 0.44.2)
Any Android devices

I schedule local notifications with FCM.scheduleLocalNotification(notification) and they works ok, but if I reboot the device, the notifications are not fired any more. If I use FCM.getScheduledLocalNotifications() after rebooting it returns the scheduled notifications, but they are not fired.
On iOS it works ok.

**Comment by evollu** [comment]
dup of https://github.com/evollu/react-native-fcm/issues/721

**Comment by evollu** [comment]
what devices have you tested

**Comment by evollu** [comment]
it could fail in 2 ways.
1. BOOT event is not fired correctly. 
2. BOOT event is fired but alarm is not set correctly.

let's troubleshoot 2 first. fire an event through adb `adb shell am broadcast -a android.intent.action.QUICKBOOT_POWERON`. 
it should trigger https://github.com/evollu/react-native-fcm/blob/master/android/src/main/java/com/evollu/react/fcm/FIRLocalMessagingHelper.java#L87
that that time you can verify if alarm is set correctly.

**Comment by germanst** [comment]
I'm testing this with a Moto G3, but I also tried with a Moto X and I think with a Samsung J7 2016 but I'm not sure.
I did the following: I scheduled a notification on my app and then run command `adb shell dumpsys alarm` and my notificationn is listed:

```
Batch{1adca39 num=1 start=1081175 end=1081175 flgs=0x1}:
    RTC_WAKEUP #0: Alarm{bb2a87e type 0 when 1514985600000 org.myapp.name}
      tag=*walarm*:org.myapp.name/com.evollu.react.fcm.FIRLocalMessagingPublisher
      type=0 whenElapsed=+11m40s114ms when=2018-01-03 10:20:00
      window=0 repeatInterval=0 count=0 flags=0x1
      operation=PendingIntent{9dc51df: PendingIntentRecord{53afe2c org.myapp.name broadcastIntent}}
```
Then I restarted my device, I run again `adb shell dumpsys alarm` and my app has no more that entry (scheduled date is not still in the past). In this point I did what soy said: `adb shell am broadcast -a android.intent.action.QUICKBOOT_POWERON` and the command line gave me this:
```
Broadcasting: Intent { act=android.intent.action.QUICKBOOT_POWERON }
Broadcast completed: result=0
```
I run again the command to get the alarms but my alamr doesn't appear.

My code to create schedules notifications is this:
```
createNotification(date){
		let notificationId = this.generateId();
		
		let notification = {
			id: notificationId,
			fire_date: date.getTime(),
			body: I18n.t('learn.modalTitle'),
			icon: "ic_notification",
			large_icon: "ic_launcher",
			show_in_foreground: true,
			priority: "high"
		};
		let notifCopy = Object.assign({}, notification);

		FCM.scheduleLocalNotification(notification);
		
		return notifCopy;
	}
```

**Comment by germanst** [comment]
Updated info: `onReceive` method from class `FIRSystemBootEventReceiver` is being executed when device restarts because I see 'FCMSystemBootReceiver: Received reboot event' in device's log

**Comment by evollu** [comment]
sounds like the schedule alarm failed.
are you able to debug from the breakline I mentioned earlier after `adb shell am broadcast -a android.intent.action.QUICKBOOT_POWERON`?
this command should fake a boot event and trigger setting alarms code again

**Comment by germanst** [comment]
I found the problem, it's on `sendNotificationScheduled` method from `FIRLocalMessagingHelper` class, in this part:
```
Long fireDate = Math.round(bundle.getDouble("fire_date"));
if (fireDate == 0) {
    Log.e(TAG, "failed to schedule notification because fire date is missing");
    return;
}
```
When a notification is created "manually" from the application it works ok, because `fire_date` is a `Double`, but the problem is when this part of code is called because of `android.intent.action.QUICKBOOT_POWERON`, in this case `fire_date` is a `Long`, so the result of 
`Long fireDate = Math.round(bundle.getDouble("fire_date"));`
 is always `0`.
My solution was changing that part of code by this:
```
Long fireDate = Math.round(bundle.getDouble("fire_date"));
if (fireDate == 0) {
	fireDate = bundle.getLong("fire_date");
		}

if (fireDate == 0) {
    Log.e(TAG, "failed to schedule notification because fire date is missing");
    return;
}
```
Now it works ok. I'll have to create a fork I think to be able to use this on my app. What do you think about this problem? could it depend on the device or this doesn't work for any device with android?

**Comment by evollu** [comment]
@germanst good catch. 

Try `Math.round(bundle.getDouble("fire_date", bundle.getLong("fire_date")))`

You are welcome to make a PR to fix this
