### ISSUE TITLE
duplicate notifications in android when the app is in background

### ISSUE THREAD

**Issue by Avanikothari22** [evollu/react-native-fcm#724]
I am running the app with RN version 0.47.0 and react-native-fcm version ^10.0.3. I have a root js file AppNavigator.js in which i hv handled loacal scheduled notifications.My Appnavigator.js is as follows:

import React, { Component } from 'react';
import { NetInfo, Alert, Platform } from 'react-native';
import FCM, {FCMEvent,
	RemoteNotificationResult,
	WillPresentNotificationResult,
	NotificationType} from 'react-native-fcm';
import { connect } from 'react-redux';
import App from './App';
import SnackBar from 'react-native-snackbar-dialog';
import {CONNECTION_CHANGE} from './actions/connection';
import {HEADLINE_ALL_TOPIC, HEADLINE_IMPORTANT_TOPIC} from './utility/Constants';
import  Validate from './utility/Validations';
export var AppObj = {};
var isConnected = false;
var isShowingAlert = false;
/**
 * FCM INIT...
 */

FCM.on(FCMEvent.Notification, async (notif) => {
    console.log('in on method:::::',notif);
    // there are two parts of notif. notif.notification contains the notification payload, notif.data contains data payload
    if(notif.local_notification){
      //this is a local notification
    }
    if(notif.opened_from_tray){
       // console.log('in on method::::: notif.opened_from_tray in component did mount ',notif);
        // if(Platform.OS === 'android'){
            if(notif.title==='Event in 15 minutes.'){
                // navigate to calendar screen
                //console.log('inside if  openned from tray in component did mount :::');
                Validate.getSessionEvent().emit('CALENDAR_EVENT_EMITTER',{ message: "hello from up here to calendar"});
            }else{
                // navigate to headlines screen
                Validate.getSessionEvent().emit('HEADLINES_EVENT_EMITTER',{ message: "hello from up here to headlines"});
            }
// }
    }

    if(Platform.OS === 'android'){
        console.log('inside android:::')
        if(notif.hasOwnProperty('fcm')){
            console.log('inside fcm has own property:::');
        FCM.presentLocalNotification({
            title: notif.fcm.title,
            show_in_foreground: true,
            body: notif.fcm.body,
            icon: notif.fcm.icon,
            color:notif.fcm.color,
            priority: 'high',
        });
    }
}

    if(Platform.OS ==='ios'){
     
        //optional
      //iOS requires developers to call completionHandler to end notification process. If you do not call it your background remote notifications could be throttled, to read more about it see the above documentation link.
      //This library handles it for you automatically with default behavior (for remote notification, finish with NoData; for WillPresent, finish depend on "show_in_foreground"). However if you want to return different result, follow the following code to override
      //notif._notificationType is available for iOS platfrom
      switch(notif._notificationType){
        case NotificationType.Remote:
          notif.finish(RemoteNotificationResult.NewData) //other types available: RemoteNotificationResult.NewData, RemoteNotificationResult.ResultFailed
          break;
        case NotificationType.NotificationResponse:
          notif.finish();
          break;
        case NotificationType.WillPresent:
        console.log('hello in here');
          notif.finish(WillPresentNotificationResult.All) //other types available: WillPresentNotificationResult.None
          break;
      }
    }
});
// FCM.on(FCMEvent.RefreshToken, (token) => {
//     console.log('Token Generated 1::', token);
//     // fcm token may not be available on first load, catch it here
// });

 //FCM INIT END

class AppNavigator extends Component {
	constructor(props) {
		super(props);
		AppObj = this;
	}
	
	componentWillMount(){
        
        NetInfo.isConnected.addEventListener(
			'change',
			AppObj.handleFirstConnectivityChange
		);
	}
	componentDidMount() {
        NetInfo.isConnected.fetch().then(_isConnected => {
			console.log('First, is ' + (isConnected ? 'online' : 'offline') + isConnected);
			isConnected = _isConnected;
			//AppObj.props.connectivityChange(_isConnected);
        });
        
        this.notificationListener = FCM.on(FCMEvent.Notification, async (notif) => {
            console.log('notiffff:: here', notif);
            // optional, do some component related stuff
        });
        
        FCM.getScheduledLocalNotifications().then(notif=>console.log("From scheduled Notif",notif));

        // iOS: show permission prompt for the first call. later just check permission in user settings
        // Android: check permission in user settings
        FCM.requestPermissions().then(()=>console.log('granted')).catch(()=>console.log('notification permission rejected'));
        
        FCM.getFCMToken().then(token => {
            console.log('token generated 2 ::', token);
          
        });
        FCM.setBadgeNumber(0);
        
        // initial notification contains the notification that launchs the app. If user launchs app by clicking banner, the banner notification info will be here rather than through FCM.on event
        // sometimes Android kills activity when app goes to background, and when resume it broadcasts notification before JS is run. You can use FCM.getInitialNotification() to capture those missed events.
        // initial notification will be triggered all the time even when open app by icon so send some action identifier when you send notification
        FCM.getInitialNotification().then(notif=>{
           console.log('notif', notif)
         
           
        });
    }
	

	isConnected() {
		return isConnected;
	}

	handleFirstConnectivityChange(_isConnected) {
		if(!_isConnected){ //#05B2B2
			SnackBar.show('INTERNET DISCONNECTED', {duration: 2000, textColor: '#05B2B2' });
			isShowingAlert = true;
		} else{
			if(isShowingAlert){
				SnackBar.show('INTERNET CONNECTED', {backgroundColor: '#05B2B2', duration: 2000, textColor: '#000' });
			}
		}
		isConnected = _isConnected;
		//AppObj.props.connectivityChange(_isConnected);
	}

	render() {
		return (
			<App/>
		);
	}

	componentWillUnmount() {
        // stop listening for events
        this.notificationListener.remove();
        
    }

}

export default connect(null)(AppNavigator);

And the file in which that contains the scheduling logic is:
function triggerSchedule(todaysEvents, preferenceObject){
    console.log('in trigger schedule !');
    if(todaysEvents.length !== 0) {
        scheduleNotifications(todaysEvents, preferenceObject);
    }
}

function scheduleNotifications(todaysEvents, preferenceObject){
    let now = new Date().getTime(); // Relying on local timezone. Otherwise the uck would uck me. 
    now+=1200000; // + 20 minutes for elapse.
    /* So that after scheduling, the very first notification that can be scheduled
        will be the one which falls after 20 minutes.
        to avoid notifications atleast till 5 minutes after scheduling.*/ 
    const events = todaysEvents;
    const useFulEvents = _.filter(events, (o) => {
        const inMillis = o.occurs_at.unixTimeStamp*1000;
        const test = moment(inMillis).isAfter(now);
        return test;    
   });
   const eventsToSchedule = getEventsPerPreference(useFulEvents, preferenceObject);
   fireSchedule(eventsToSchedule);
}

function getEventsPerPreference(events, pObject){
    if(pObject.publish_notifications){
        if(pObject.calendar_all){
            return events;
        } else {
            let eventList = events.slice(0,events.length);
            let calendarEvents = [];
            if(pObject.calendar_high){
                let data = _.filter(eventList, function (o) { return o.category.importance === 'high'; });
                calendarEvents = calendarEvents.concat(data)
            }
            if(pObject.calendar_low){
                let data = _.filter(eventList, function (o) { return o.category.importance === 'low'; });
                calendarEvents = calendarEvents.concat(data);
            }
            if(pObject.calendar_medium){
                let data = _.filter(eventList, function (o) { return o.category.importance === 'low'; });
                calendarEvents = calendarEvents.concat(data);
            }
            return calendarEvents;
        }
    }else{
        return [];
    }
}

function fireSchedule(events){
    console.log('Events 123', events.length);
  if(events.length!== 0){
    events.forEach((event) => {
        let countryName;
        if(isoCountries.hasOwnProperty(event.category.location)){
            countryName  = isoCountries[event.category.location];
        }
        const fireTime = (event.occurs_at.unixTimeStamp*1000) - 900000;
        
        FCM.scheduleLocalNotification({
            fire_date: fireTime,
            id: 'Calendar_Notification_'+fireTime+countryName+event.category.name,
            body: countryName+'- '+event.category.name,
            title: 'Event in 15 minutes.',
            priority:'high'
            
        });
    });
  }
}

**Comment by evollu** [comment]
seems you are calling `FCM.presentLocalNotification` in notification callback?

**Comment by kckunal2612** [comment]
Even I am getting duplicate notifications, even though I have followed the example given on the library's home page. First I thought it was a Firebase issue, but then I tested with 30-40 notifications, and got 2 for each payload that I sent from the server.

**Comment by AugustoAleGon** [comment]
I have the same problem still. Even from the firebase console. I got the notification twice. @evollu @riyaz942 Any idea?

**Comment by evollu** [comment]
make sure you don't call `FCM.presentLocalNotification` in notification callback

**Comment by AugustoAleGon** [comment]
```
  componentDidMount () {
    const {getPersonalChat, getChat} = this.props
    this.notificationListner = FCM.on(FCMEvent.Notification, notif => {
      if (Platform.OS === 'ios') {
              // optional
              // iOS requires developers to call completionHandler to end notification process. If you do not call it your background remote notifications could be throttled, to read more about it see the above documentation link.
              // This library handles it for you automatically with default behavior (for remote notification, finish with NoData; for WillPresent, finish depend on "show_in_foreground"). However if you want to return different result, follow the following code to override
              // notif._notificationType is available for iOS platfrom
        switch (notif._notificationType) {
          case NotificationType.Remote:
            notif.finish(RemoteNotificationResult.NewData) // other types available: RemoteNotificationResult.NewData, RemoteNotificationResult.ResultFailed
            break
          case NotificationType.NotificationResponse:
            notif.finish()
            break
          case NotificationType.WillPresent:
            notif.finish(WillPresentNotificationResult.All) // other types available: WillPresentNotificationResult.None
            break
        }
      }
      if (Platform.OS === 'android') {
        this.showLocalNotification(notif)
      }
    })

    this.refreshTokenListener = FCM.on(FCMEvent.RefreshToken, token => {
      console.log('TOKEN (refreshUnsubscribe)', token)
    })
    FCM.requestPermissions().then(
      () => console.log('granted')).catch(
        () => console.log('notification permission rejected'))

    FCM.getFCMToken().then(token => {
      console.log(token)
    }, (error) => {
      console.log('The token could not be generated! , ', error)
    })
    FCM.getInitialNotification().then(notif => {
      console.log('INITIAL NOTIFICATION', notif)
    }, (err) => {
      console.log('Initial Notifications can not be displayed! ', err)
    })
  }

  showLocalNotification (notif) {
    FCM.presentLocalNotification({
      title: notif.fcm.title,
      body: notif.fcm.body,
      priority: 'high',
      icon: 'ic_launcher_white',
      show_in_foreground: true,
      local: true
    })
  }

  componentWillUnmount () {
    this.notificationListner.remove()
    this.refreshTokenListener.remove()
  }
```

This is basically my code. Something interesting about what is happening. I configure the icon to be ic_launcher_white so one notification has my custom icon and the other one is with the default icon. What might happen?

**Comment by AugustoAleGon** [comment]
Any thoughts about this? If I comment the method `showLocalNotifications` still persists the dual notification.

**Comment by evollu** [comment]
if you provider `notification` in payload, FCM will create a notification for you. and your `showLocalNotifications` will create another one. That should example why you see 2 different notification.

I suggest using custom notification for android.

**Comment by AugustoAleGon** [comment]
@evollu You had right about the `AndroidManifest.xml` file. I did a migration from `react-native-push-notification` to FCM so I had all the settings of both libraries. Probably I had twice the id and the library sends notification twice. Thanks.

**Comment by AugustoAleGon** [comment]
@evollu By the way is the an option to turn off notification in foreground on iOS?

**Comment by evollu** [comment]
@AugustoAleGon 
https://github.com/evollu/react-native-fcm/blob/master/Examples/simple-fcm-client/app/Listeners.js#L54
do `notif.finish(WillPresentNotificationResult.None)`

**Comment by evollu** [comment]
haven't heard from @Avanikothari22 for a while. closing this

**Comment by abhaykumar1415** [comment]
I had to remove
`<receiver android:name="com.google.android.gms.gcm.GcmReceiver" android:exported="true" android:permission="com.google.android.c2dm.permission.SEND" > <intent-filter> <action android:name="com.google.android.c2dm.intent.RECEIVE" /> <category android:name="${applicationId}" /> </intent-filter> </receiver>
`
from AndroidManifest.xml
