### ISSUE TITLE
[Android]Remote Data & Notification not receiving 

### ISSUE THREAD

**Issue by jaysmoodge** [evollu/react-native-fcm#725]
Im very new to react-native so please bare with me =).
also thank you for this great  work.

I complied the example code to a new project and didn't change anything.

custom_notification works just fine. (sendRemoteNotification(token))

version
"react-native": "0.51.0",
"react-native-fcm": "^11.1.0"
Android Oreo
Xperia XZ

but when im firing remote data & remote notification with data.
i receive nothing and on postman.
![image](https://user-images.githubusercontent.com/35086221/34550832-f28c686c-f14e-11e7-8317-80f81d6cd51e.png)

My app is running in foreground, background or not running.

Should i just downgrade RN & RNFCM?
if so how can i downgrade RNFCM? 

Thank you man cheers!

**Comment by evollu** [comment]
the message doesn't trigger any callback?

**Comment by jaysmoodge** [comment]
yes didnt trigger any.

i tried what u suggest but still didnt kick my app,

ill try to dig deep. =) thanks.

**Comment by jaysmoodge** [comment]
hey Man, i figured it out.

its now kicking. there was no problem. i just added local notif.
![image](https://user-images.githubusercontent.com/35086221/34595861-37e2fa3a-f216-11e7-87a7-2348c72a3d9a.png)
u can close this one now.. Greate work man!
