### ISSUE TITLE
Fetch latest notification by selected FCM id

### ISSUE THREAD

**Issue by pewh** [evollu/react-native-fcm#728]
When openning an issue, please include following information for better support

1. What version of RN and react-native-fcm are you running? RN: ^0.48.4 FCM: ^9.6.2
2. What device are you using? (e.g iOS9 emulator, Android 6 device)? Android
3. Is your app running in foreground, background or not running? Running well

Let's say I push 2 notifications, first using `id` and later push without `id`. How to get previous message based on `id`?

`FCM.getInitialNotification()` only fetch latest notification. I'm seeking something like `FCM.getInitialNotification('chat')` that fetch latest notification with id = 'chat'. Thanks

**Comment by evollu** [comment]
clear a misunderstanding here
`FCM.getInitialNotification()` gets the notification that launch the application, not necessary the latest one.
there is no way to get all delivered notification.

if you are planning to use notification as "message queue", I suggest sync with server directly which is much reliable

**Comment by pewh** [comment]
thanks for the explanation
