### ISSUE TITLE
Remote with data notification not displaying badge number

### ISSUE THREAD

**Issue by jaysmoodge** [evollu/react-native-fcm#729]
everything works fine with custom, remote notification.
also local & schedule notification. But remote with data failed.

RN version : 5.0
RN-FCM: ^11.0
im doing something like this.

![image](https://user-images.githubusercontent.com/35086221/34606215-83004184-f249-11e7-9eb4-ff39466f1caa.png)

Cheers Thanks

**Comment by evollu** [comment]
you are testing with android or iOS?

**Comment by jaysmoodge** [comment]
im using android O , Xperia XZ

**Comment by evollu** [comment]
I wonder if Xperia supports badge itself. Have you tried setting badge directly?

**Comment by jaysmoodge** [comment]
yes it supports badge, actually when i call custom notification it displays the badge in app icon. also with send remote notification. 

but when i try remote with data it fails. 
note i didnt change much ur xample code.

**Comment by jaysmoodge** [comment]
Hi just downloaded ur example and reproduce, its not working too.

it only display a badge without a number.

**Comment by jaysmoodge** [comment]
Hi if found a work around through custom notification. =)

Thanks.

**Comment by shekharskamble** [comment]
@jaysmoodge - is it possible to share your custom notification payload? thanks..

**Comment by jaysmoodge** [comment]
sure.. il make a sample later.

**Comment by ctrlspcmac** [comment]
@shekharskamble 

something like this
"data":{custom_notification": {
		"title": "Simple FCM Client",
		"body": "Click me to go to detail",
		"sound": "default",
		"priority": "high",
             }
}.

you can try the working example.
to change badge u can try something like.

FCM.setBadge( badege => {
   FCM.getBadge()+=1;
}).
im not in my PC im just using my phone.

Hope it helps.

**Comment by shekharskamble** [comment]
@ctrlspcmac Thank you for the example to change the badge app needs to be running am I right?

**Comment by ctrlspcmac** [comment]
@shekharskamble not neccesarily, when the FCM works fine in your app.  when notif triggers the FCM.on(event.notif)....{
//change badge
FCM.setBadge( badege => {
FCM.getBadge()+=1;
}).
}

**Comment by ctrlspcmac** [comment]
u mean through payload? i think its possible , check the sample working
code. =)
