### ISSUE TITLE
[ ANDRIOD ] Notification heads-up and icon not showing

### ISSUE THREAD

**Issue by xxhenglyxx** [evollu/react-native-fcm#731]
RN: 0.50.3
RN-FCM: 11.1.0
Android: Sony Z1 ( real device )

I follow the instruction in this repo and also compare my android manifest with the example in this repo, It should not have any mistake, instead I did not have the ic_notif.png as the notification icon and instead using the ic_launcher.png app icon as my notification icon.
I am using the firebase-admin, admin.message api to send the push notification from my server. I can can get the notification but the heads up did not show, and when I am running in the foreground, notification did not popup but from the console, my phone was receiving the notification.

**Comment by evollu** [comment]
you can debug this function and see what is wrong
https://github.com/evollu/react-native-fcm/blob/master/android/src/main/java/com/evollu/react/fcm/SendNotificationTask.java#L48

**Comment by xxhenglyxx** [comment]
@evollu Ok I will try to debug it and come back here later

**Comment by xxhenglyxx** [comment]
@evollu I am sorry, I do not know how to debug the function. I tried logging some message in the function scope but got nothing inside the LogCat in android studio, which it should be logging some message out right if I put it there ?

**Comment by evollu** [comment]
`but from the console, my phone was receiving the notification.` you mean firebase console?

add breakpoint here and make sure this is called. If not, it means your notification is not delivered.
https://github.com/evollu/react-native-fcm/blob/master/android/src/main/java/com/evollu/react/fcm/MessagingService.java#L26

also can you provide your payload sent to server

**Comment by xxhenglyxx** [comment]
@evollu console I mean is the console from react native debugger, react developer tools console.

    // server - startup-init.js

    import * as FirebaseAdmin from 'firebase-admin';

    ...
    FirebaseAdmin
        .messaging ()
        .sendToDevice ( tokens, payload, options )
        .then( response => console.log( response ) )
        .catch ( error => console.log( error ) );

I do the push notification testing by calling the api and my own device token, fake payload and options for every 5 seconds interval.
Each time the api called, the response was successfully sent from my server console, and I could heard the notification sound and the blank icon on my phone, I can see the body and title that were being sent from my server. But I want the heads-up banner to show, which it did not, that was when my app is in background mode. In foreground, I also receive the notification, but it only appears in the react native debugger dev console, which what I want is also the heads-up to show even in foreground.

**Comment by evollu** [comment]
1. `blank icon`. your icon needs to be white/transparent only, otherwise it shows as a blank icon. it is stated in readme I think. Android Lollipop change
2. heads-up banner is not supported by FCM itself. use `custom_notification`. check readme

**Comment by xxhenglyxx** [comment]
@evollu I will make the icon white/transparent. About the custom_notification, I am not sure if doing this would work:

    const payload = {

        "data": {

            "custom_notification": JSON.stringify({
                "title": "Welcome to MyApp",
                "body": "Thanks to join MyApp",
                "sound": "default",
                "priority": "high",
                "show_in_background": true,
                "lights": true,
                "wake_screen": true
            })

        }

    };

    FirebaseAdmin
        .messaging ()
        .sendToDevice ( tokens, payload, options )
        ...

I also looked at this #46. At the bottom, does it said about the JSON.stringify object be done on the custom_notificaiotn value, so that the admin.message api would work ? If I do that, the server console output me an error results and the push notification did not sent.

**Comment by evollu** [comment]
you don't need `JSON.stringify`

**Comment by xxhenglyxx** [comment]
If no JSON.stringify, it will output this error on the server console.

     { code: 'messaging/invalid-payload', I20180109-22:16:29.046(7)?
        message: 'Messaging payload contains an invalid value for the "data.custom_notification" property. Values must be strings.' },

**Comment by evollu** [comment]
ok. keep JSON.stringify then.
`show_in_background` should be `show_in_foreground`

**Comment by xxhenglyxx** [comment]
@evollu  lol, I am sorry, it was show_in_foreground in my code, I retype those comment so little typo XD

**Comment by evollu** [comment]
`"priority": "high"` should make the banner to show up.
try debug this line and see what priority are you getting when receiving the notificaiton
https://github.com/evollu/react-native-fcm/blob/master/android/src/main/java/com/evollu/react/fcm/SendNotificationTask.java#L87

**Comment by xxhenglyxx** [comment]
I tried logging out like this:

    Log.d ( "BLOCK: ", "*************************" ):
    Log.d ( "PRIORITY: ", priority.toString () );
    Log.d ( "BLOCK: ", "*************************" );

but inside LogCat, i could only see the asterisk that I logged out, and did not see priority log out anywhere.

**Comment by evollu** [comment]
title and body logs out right?

**Comment by xxhenglyxx** [comment]
@evollu  I am sorry, I did not log out the title the body, but because from the top, you check if null it will return out from the function.

    if (intentClassName == null) {
            return null;
    }         
    if (bundle.getString("body") == null) {
            return null;
    }

but It did not so I think it will go through until the end of the funciton, But will will try log them out again to make sure everything is working fine.

**Comment by xxhenglyxx** [comment]
@evollu Yes, I tried logging out the body and title, it does show, but the priority does not.

**Comment by evollu** [comment]
it is weird because bundle should to have everything
```
{
            "title": "Welcome to MyApp",
            "body": "Thanks to join MyApp",
            "sound": "default",
            "priority": "high",
            "show_in_background": true,
            "lights": true,
            "wake_screen": true
        }
```

**Comment by xxhenglyxx** [comment]
@evollo I dunno if this works, but I comment out all the switch case of the priority, and directly set the notification priority to max, but it still did not work

**Comment by evollu** [comment]
can you reproduce in emulator. could it be a phone settings limit?

**Comment by xxhenglyxx** [comment]
@evollu I tried on emulator instead of real phone, and everything worked as expect. But that because I did this

    FCM.scheduleLocalNotification({
        fire_date: new Date().getTime () + 5000,
        id: "UNIQ_ID_STRING",
        body: "from future past",
        lights: true,
        wake_screen: true,
        priority: "high",
        sound: "default",
        large_icon: "ic_launcher",
        icon: "ic_launcher",
        color: "red"
    })

I think it is the problem with the firebase-admin package that I used on the server, the admin().message().sendToDevice ( tokens, payload, options ) api

**Comment by xxhenglyxx** [comment]
I also tried to do implement the FirebaseClient class same as inside the example folder on my server

    // firebase-client.js
    import { HTTP } from 'meteor/http';
    import firebase_config from '../../services/firebase-config';

    class FirebaseClient {

        send = async ( body, type ) => {

            let headers = {
                "Content-Type": "application/json",
                "Authorization": "key=" + firebase_config.api_key
            };

         try {

            let response = await HTTP.post ( firebase_config.api_url, { method: 'POST', headers, body } );

            try {

                response = await response.json ();

            } catch ( error ) {

                console.log ( `Firebase Message Send: ${ error }` );

            }

        } catch ( error ) {

            console.log ( `Firebase Client: ${ error }` );

        }

    }

    let firebaseClient = new FirebaseClient ();
    export default firebaseClient;

    // startup-init.js
    import firebaseClient from './firebase-client';

    .....

    const tokens = [ '....' ];
    const body = {

        "to": tokens,
        "data": {

            "custom_notification": {

                "title": "Greeting from MyApp",
                "body": "Thanks for joining MyApp",
                "sound": "default",
                "priority": "high",
                "show_in_foreground": true,
                "lights": true,
                "wake_screen": true

            }

        }

    }

    Meteor.setInterval(() => {

        firebaseClient.send ( JSON.stringify ( body ), "notification" );

    }, 10000);

So everything 10 seconds it will send out my test push notificaiton, but it did not and it log out these message in my server console:

    Firebase Client Error: Error: failed [401] <HTML> <HEAD> <TITLE>The request
    was missing an Authentication Key (FCM Token). Please refer to section &quot;
    Authentication&quot; of the FCM documentation, at https://firebase.google.com/docs/
    cloud-messaging/server.</TITLE> </HEAD> <BODY BGCOLOR="#FFFFFF" 
    TEXT="#000000"> <H1>The request was missing an Authentication Key (FCM TOKEN).
    Please, refer to section &quot;Authentication&qot; of the FCM documentation, at
    https://firebase.google.com/docs/cloud-messaging/server.</H1> <H2>Error 401</H2> <...

**Comment by evollu** [comment]
so seems your `firebase_config.api_key` has wrong value

**Comment by xxhenglyxx** [comment]
@evollu I just tested using Postman, it works as expected though :|

**Comment by evollu** [comment]
`The request was missing an Authentication Key (FCM Token)` means your header setting is wrong.

**Comment by xxhenglyxx** [comment]
@evollu the problem was not related to the package since the beginning. I already fixed the bug, by trying to removd all the quotation on the body that being passed in as argument in send method and also not doing the JSON.stringify, then pass it to meteor Http. So in theory I think meteor http already did the stringify for me.

    // change how the properties are being written in body that being pass in as argument,
    
    const body = {

        "to": tokens,
        "data": {

            "custom_notification": {

                "title": "Greeting from MyApp",
                "body": "Thanks for joining MyApp",
                "sound": "default",
                "priority": "high",
                "show_in_foreground": true,
                "lights": true,
                "wake_screen": true

            }

        }

    }

    // to like this

    const body = {

        to: tokens,
        data: {

            custom_notification: {

                title: "Greeting from MyApp",
                body: "Thanks for joining MyApp",
                sound: "default",
                priority: "high",
                show_in_foreground: true,
                lights: true,
                wake_screen: true

            }

        }

    }

    // and do not stringify it when pass to send

    firebaseClient.send ( body, "notification" ); // before it was .send( JSON.stringify ( body ), ... );

    // firebase-client.js
    // how things were being passed to meteor http

    const headers = {

        "Content-Type": "application/json",
        "Authorization": firebase_config.api_key

    };

    // ......

    const response = await Http.post ( firebase_config.api_url, { data: body, headers } );
