### ISSUE TITLE
[question] fcm token 

### ISSUE THREAD

**Issue by sibelius** [evollu/react-native-fcm#74]
FCM token is different from the token provided by https://github.com/zo0r/react-native-push-notification?

**Comment by evollu** [comment]
yes. it is different. They are using GCM token

**Comment by sibelius** [comment]
so, what should I do if I wanna move out from firebase someday?

**Comment by evollu** [comment]
good question. you can check with firebase team

**Comment by sibelius** [comment]
I'll contact them, thanks
