### ISSUE TITLE
Does this lib work with Amazon SNS?

### ISSUE THREAD

**Issue by batusai513** [evollu/react-native-fcm#746]
I'm working on a react-native app and we are using Amazon SNS as the messaging service, does this lib could work with Amazon SNS for IOS and android?

Thanks in advanced :)

**Comment by evollu** [comment]
I think most of the function works like `custom_notification` for android and local notifications. try it?

**Comment by batusai513** [comment]
@evollu I'm testing RN but i have another question, it is still necessary to do the entire firebase configuration for IOS even if i'm using Amazon SNS and not using FCM directly.

**Comment by evollu** [comment]
Yes. you still need to install firebase SDK otherwise it won't compile

**Comment by batusai513** [comment]
got it, everything is working as expected, thanks for your effort with this library and for taking the time to answer my questions, I'll close this issue.

Thanks Again.
