### ISSUE TITLE
Receive notification but not show pop-up in Android.

### ISSUE THREAD

**Issue by Donhv** [evollu/react-native-fcm#748]
I use code from Usage react-native-fcm and I have problem with receive notification with firebase:
- I have Receive notification from firebase,notification show in icon-tray  but not show popup.

But when I use FCM.localnotification it's show popup.
Who can help me?

Version RN: 0.51
device: both android 7.0 & genimotion: 7.0

**Comment by evollu** [comment]
you have to use `custom_notification` to see popup

**Comment by kasterlod** [comment]
I have a question. How should I set notification data if I want to popup notification on both platforms? If I send only 'notification' or 'notification' and 'custom_notification' in payload, notifs show on both platform but no popup on android. If I send only 'custom_notification' then popup notif shows in android but notif not arrived iOS.

**Comment by evollu** [comment]
@kasterlod my approach is saving user's phone platform in database and change accordingly.

**Comment by shekharskamble** [comment]
@evollu  - I am having the same issue here is my payload

var payload ={
                                data: {
                                    custom_notification: JSON.stringify({
                                        title: 'Test',
                                        body: 'User has a comment for you.',
                                        sound: 'default',
                                        badge: '1',
                                        show_in_foreground: true,
                                    })
                                }
                            }

**Comment by shekharskamble** [comment]
Got it working by adding priority: "high",  & content_available: true in payload
Thanks...

**Comment by kasterlod** [comment]
@shekharskamble Could you attach your full working payload object?

**Comment by shekharskamble** [comment]
@kasterlod 
var payload ={
                    data: {
                        custom_notification: JSON.stringify({
                            title: 'Some title',
                            body: 'Some body',
                            sound: 'default',
                            badge: '1',
                            priority: "high", 
                            show_in_foreground: true,
                            content_available: true
                        })
                    }
                }

**Comment by evollu** [comment]
@nes123 there is no unified way to make ios and android to show popup notification
