### ISSUE TITLE
[!] The target lionsclub-tvOSTests is declared twice.

### ISSUE THREAD

**Issue by sathishmscict** [evollu/react-native-fcm#753]
React Native configuration : 
    "react": "16.0.0",
    "react-native": "0.51.0",

Macs-iMac:ios mac$ pod install [Not working]
Analyzing dependencies
[!] The target `lionsclub-tvOSTests` is declared twice.

Podfile:
[Podfile.txt](https://github.com/evollu/react-native-fcm/files/1651132/Podfile.txt)

**Comment by kiarashws** [comment]
Open your newly created Podfile and remove multiple declarations.

**Comment by sathishmscict** [comment]
yes, am removed still same message raised.Restart the IDE then everything working fine...
