### ISSUE TITLE
Not Getting opened_from_tray on FCM.getInitialNotification() IOS

### ISSUE THREAD

**Issue by batusai513** [evollu/react-native-fcm#755]
Hi there

Is there a reason I'm not the `opened_from_tray` property in the `notif` object on the `FCM.getInitialNotification()` function when tapping the banner when the app is in killed state?
I've followed all the instructions to setup the app in IOS.

When openning an issue, please include following information for better support

1. What version of RN and react-native-fcm are you running?
`"react-native-fcm": "^11.3.1"`
2. What device are you using? (e.g iOS9 emulator, Android 6 device)?
IOS 10 device
3. Is your app running in foreground, background or not running?
Not running (Killed state)

**Comment by evollu** [comment]
if you get notification from `FCM.getInitialNotification() `, always treat it as `opened_from_tray:true`

**Comment by batusai513** [comment]
@evollu That means that is ok not to get `opened_from_tray:true` on the `notif` object?

**Comment by evollu** [comment]
@batusai513 only if it is from `FCM.getInitialNotification()`
if it is from notification callback, not having `opened_from_tray:true` means it is false

**Comment by batusai513** [comment]
@evollu on IOS i'm getting `FCM.getInitialNotification()` without the property `opened_from_tray`

**Comment by evollu** [comment]
yes it is fine
