### ISSUE TITLE
Package is being exported in MainApplication, but Intent is being handled by MainActivity

### ISSUE THREAD

**Issue by Alanz2223** [evollu/react-native-fcm#76]
I am trying to integrate react-native-fcm but receive the error #19  . I am the reason is that I am not exporting the FIRMessaging package on my MainApplication.java class. The problem is that the constructor also receives an intent obtained by getIntent() but the Intent is being caught by my MainActivity and not available in my MainApplication.java. Here are my two classes.

MainApplication.java

`public class MainApplication extends Application implements ReactApplication {`

 ` private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {`
  `  @Override
    protected boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }`

    `@Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage()
          //supposed to be - new FIRMessaging(getIntent()) 
      );
    }
  };`

  `@Override
  public ReactNativeHost getReactNativeHost() {
      return mReactNativeHost;
  }`
`}`

MainActivity.java

`public class MainActivity extends ReactActivity {`

   ` @Override
    public void onNewIntent(Intent intent)
    {
        super.onNewIntent(intent);
        setIntent(intent);
    }`

    `/**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "NavExp";
    }`
`}`

How do I export the FIRMessaging package and pass it the intent?

**Comment by Alanz2223** [comment]
The directions say to handle the intent on MainActivity.java, but the package is being exported from MainApplication.java?

**Comment by evollu** [comment]
for latest version of this repo, you don't need to handle new intent in MainActivity.java. Is it for people using with react native < 0.28

**Comment by sibelius** [comment]
I think u can close this
