### ISSUE TITLE
Open link in webview when click on notification (link in the message notification)

### ISSUE THREAD

**Issue by PhuongLV93** [evollu/react-native-fcm#762]
I need Open link in webview when click on notification (link in the message notification).
How to do it in react-native?
Help me!
Thanks!

**Comment by alexey-m-ukolov** [comment]
Your question has nothing to do with this library, you should post it to [StackOverflow](https://stackoverflow.com/).

**Comment by evollu** [comment]
you can search online about how to open a webview
if you are asking about how you handle logic when user click notification, check `opened_from_tray `
