### ISSUE TITLE
Can't detect when app open from a notification banner (Android, local notification)

### ISSUE THREAD

**Issue by gerdana2405** [evollu/react-native-fcm#763]
"react-native": "^0.50.4",
"react-native-fcm": "^11.2.0",
Android emulator.

Hi! I created notification http://ipic.su/img/img7/fs/kiss_19kb.1517324749.jpg,

then at file index.android.js I added 
http://ipic.su/img/img7/fs/kiss_37kb.1517325014.jpg,

And when notification appeared (app is closed) and I click on it, my app open but getInitialNotification method returns me http://ipic.su/img/img7/fs/kiss_5kb.1517325629.jpg

From manifest: 

        <meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@mipmap/ic_notif"/>
              <receiver android:name="com.evollu.react.fcm.FIRLocalMessagingPublisher"/>
              <receiver android:enabled="true" android:exported="true"  android:name="com.evollu.react.fcm.FIRSystemBootEventReceiver">
                  <intent-filter>
                      <action android:name="android.intent.action.BOOT_COMPLETED"/>
                      <action android:name="android.intent.action.QUICKBOOT_POWERON"/>
                      <action android:name="com.htc.intent.action.QUICKBOOT_POWERON"/>
                      <category android:name="android.intent.category.DEFAULT" />
                  </intent-filter>
              </receiver>

            <service android:name="com.evollu.react.fcm.MessagingService" android:enabled="true" android:exported="true">
                 <intent-filter>
                        <action android:name="com.google.firebase.MESSAGING_EVENT"/>
                 </intent-filter>
            </service>

           <service android:name="com.evollu.react.fcm.InstanceIdService" android:exported="false">
                <intent-filter>
                    <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
                </intent-filter>
           </service>

.....

 <activity android:name=".MainActivity"
                  android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
                  android:windowSoftInputMode="adjustPan"
                  android:launchMode="singleTop"
                  android:exported="true">
            <intent-filter android:label="filter_react_native">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="myapp" android:host="invitation" />
            </intent-filter>
            <intent-filter>
                <action android:name="NOTIFICATION" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </activity>

I need to detect when app opened from notification.

Please help me find what I do wrong?

**Comment by evollu** [comment]
first of all, you can use scheduled notification the same as presentLocalNotification. all fields are supported and notification will show up when time comes.

Check your FCM.on listener and see if your notification actually went there

**Comment by gerdana2405** [comment]
Thanks, it's helpful. FCM.on detect when notification show up. How detect when the user open app from notification? Maybe my intent-filter is wrong, or why getInitialNotification return action: null? 
Or maybe, I don't understand, how correct must work click_action.

**Comment by evollu** [comment]
@gerdana2405 there is `opened_from_tray` flag

**Comment by gerdana2405** [comment]
opened_from_tray return "1" anyway.

**Comment by evollu** [comment]
seems you are trying to figure out if user launched the app by clicking notification.
In that case `opened_from_tray` doesn't work, you can check if the initialNotification has any custom data you pass, e.g you can send a `notification_type` in `data` object

**Comment by gerdana2405** [comment]
Does custom data work with local notification? Can you give me an example?

**Comment by evollu** [comment]
https://github.com/evollu/react-native-fcm/blob/master/Examples/simple-fcm-client/app/App.js#L61

**Comment by gerdana2405** [comment]
there no example where custom data pass with local notification

**Comment by evollu** [comment]
localNotification itself is custom_data, you can put any item in it

**Comment by gerdana2405** [comment]
yes, but getInitialNotification don't return any data I pass

**Comment by evollu** [comment]
what does your getInitialNotification return?
what is your local notificaiton payload?

**Comment by gerdana2405** [comment]
FCM.scheduleLocalNotification({
                            fire_date: fire_date,
                            id: id,
                            body: body,
                            repeat_interval: "week",
                            click_action: 'fcm.ACTION.HELLO',
                            show_in_foreground: true,
                            sound: 'default',
                            priority: 'high',
                            title: "MyApp",                    
                            auto_cancel: true,                             
                            large_icon: "ic_launcher",                 
                            icon: "ic_launcher",                           
                            lights: true,
                            wake_screen: true,
                            ongoing: true,
                            data: {
                                notification_type: "REMINDER"
                            }
                        })

getInitialNotification: 
{ 
    fcm : { action : null }, 
    pened_from_tray : 1,
}

**Comment by evollu** [comment]
try move notification_type outside of `data`. I remember the serializer can't serialize object
```
{
... your existing properies,
notification_type: "REMINDER"
}

**Comment by gerdana2405** [comment]
It's object from scheduled list http://ipic.su/img/img7/fs/kiss_28kb.1519728253.jpg, and this from getInitialNotification, when I open an app from notification - http://ipic.su/img/img7/fs/kiss_7kb.1519728292.jpg

I used data: JSON.stringify({notification_type: "REMINDER"}).
Maybe I missed something else

**Comment by evollu** [comment]
just updated example. even object works
https://github.com/evollu/react-native-fcm/blob/master/Examples/simple-fcm-client/app/App.js#L91

you can trigger an scheduled notification. killed app. tap the notif. the initNotif field should contain all the data.

**Comment by gerdana2405** [comment]
I found the problem. I have SplashActivity and MainActivity, and my SplashActivity is MAIN and LAUNCHER. So my data never take up to MainActivity. Do you have an idea how to fix that?

**Comment by evollu** [comment]
ah..
I use react-native-splash-screen myself.

**Comment by gerdana2405** [comment]
I pass data to my  MainActivity :intent.putExtra("DATA", this.getIntent().getExtras());
        startActivity(intent);

**Comment by gerdana2405** [comment]
Is it possible to get list of fired notifications? Or I need to save them by myself?

**Comment by evollu** [comment]
it seems to be possible for Android
https://developer.android.com/reference/android/service/notification/NotificationListenerService.html#getActiveNotifications()
but not in this lib yet
