### ISSUE TITLE
[Question] Silent push notification

### ISSUE THREAD

**Issue by Shinichi52** [evollu/react-native-fcm#768]
hi,
I have a question about silent push notification.
In my example i tried to send data about an event in push notification. I want to use silent push notification to update data in the app that is closed or ran in backgroud. 
- On android it's working fire 
- On iOS, When the app is closed or ran in background, and push notification is received, then any handler does not work.
How to trigger to call javascript function on ios?
I'm sending notification object from my server
```javascript
{
        "to": <token>,
        "priority": "normal",
        "content-available": true,
        "time_to_live": 86400,
        "collapse_key": "new_message",
        "delay_while_idle": false,
        "data": {
            "your-key": "your-value"
        }
    }
```
1. "react-native-fcm": "^11.3.1"
2. Iphone 6S - iOS 10.3.1
3. background and not running

**Comment by evollu** [comment]
when app is killed, ios won't run your code, system design.

`On iOS, When the app is closed or ran in background, and push notification is received` how do you know notification is received if no code is run?

**Comment by Shinichi52** [comment]
@evollu 
> do you know notification is received if no code is run?
My intention is to push success.
> when app is killed, ios won't run your code, system design.
Thanks
