### ISSUE TITLE
XCode build error: -fobjc-weak is not supported on the current deployment target

### ISSUE THREAD

**Issue by rudyhuynh** [evollu/react-native-fcm#769]
React Native 0.50.4

I try to build and run `simple-fcm-client` but fail.
After 'pod install' success:
```
Analyzing dependencies
Downloading dependencies
Installing Firebase (4.7.0)
Installing FirebaseAnalytics (4.0.5)
Installing FirebaseCore (4.0.12)
Installing FirebaseInstanceID (2.0.7)
Installing FirebaseMessaging (2.0.7)
Installing GoogleToolboxForMac (2.1.3)
Installing Protobuf (3.5.0)
Installing nanopb (0.3.8)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 8 total pods installed.

[!] Automatically assigning platform `ios` with version `8.0` on target `SimpleFcmClient` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
```

Then press build and run button in XCode, I got this error:
<img width="1400" alt="xcodeerror" src="https://user-images.githubusercontent.com/17097854/35727886-46d8d0b4-083c-11e8-80f8-d21d6080e99f.png">

It works great on Android btw.

**Comment by l1v3** [comment]
Hey,

i just ran into the same problem. i fixed it for me by increasing the ios deployment target of the nanopb target to iOS 8.0 (its 4.3 per default).

Pods Project -> target: nanopb -> iOS Deployment Target: iOS 8.0

Hope this helps

**Comment by Leko** [comment]
I got the same error. It fixed by your comment. Thank you @l1v3

**Comment by rudyhuynh** [comment]
Thank you @l1v3 , it works

**Comment by gaultierq** [comment]
How can I add this fix to version control ?

**Comment by rudyhuynh** [comment]
#https://github.com/tnantoka/nanopb-podspec/commit/1ed8f56651ec6c1901996aab48f7dd7fd5ca7592

**Comment by VirtualVideoPassInc** [comment]
Change Pods -> TARGETS -> nanopb -> iOS Development Target to iOS8.0

**Comment by TieXiong** [comment]
Please change Pods -> TARGETS -> nanopb -> iOS Development Target to iOS8.0
Default value is 4.3

**Comment by thebylito** [comment]
Thank you @l1v3  , you are amazing!

**Comment by shubham56** [comment]
Thanks it works.
