### ISSUE TITLE
Could not locate configuration file: 'GoogleService-Info.plist'

### ISSUE THREAD

**Issue by pratomchaip** [evollu/react-native-fcm#775]
RN: 0.52.2
react-native-fcm: 11.3.1
device: iOS 11.2 iPhone8 Plus Simulator

When starting up the app, the app stops at the launch screen.

Looking in xCode's console, it says:
```Could not locate configuration file: 'GoogleService-Info.plist'.```

I downloaded the file from the Firebase Console and
... I have my GoogleService-Info.plist file under ```/ios/projectName/```

Has anyone else had this problem?

Do I have to tell the app where the GoogleService-Info.plist is?

**Comment by pratomchaip** [comment]
Ok, found the fix.

I had to manually add the GoogleService-Info.plist file into the "**Copy Bundle Resources**" list under **Target** > **Build Phases**

**Comment by evollu** [comment]
cool

**Comment by juanlet** [comment]
> Ok, found the fix.
> 
> I had to manually add the GoogleService-Info.plist file into the "**Copy Bundle Resources**" list under **Target** > **Build Phases**

That worked for me, thanks for sharing!!. I updated from xcode 10.2 to 11.3.1 and for my application to compile with xcode 11 I had to remove mostly the fonts from react-native-vector-icons from the **Copy Bundles Resources** section in **Target> Build Phases** and add  the GoogleService-Info.plist as well
