### ISSUE TITLE
deleteInstanceId() isn't revoking FCM Token

### ISSUE THREAD

**Issue by somoso** [evollu/react-native-fcm#776]
Versions used:

"react": "^15.4.2",
"react-native": "^0.42.0",
"react-native-fcm": "11.2.0"

Running on iPhone 6 (hardware) - I'm calling FCM.deleteInstanceId() but the token remains and the device remains registered to Firebase. I thought that the deleteInstanceId() command was suppose to revoke all tokens, at least according to [this](https://firebase.google.com/docs/reference/android/com/google/firebase/iid/FirebaseInstanceId.html#deleteInstanceId())?

What I'm trying to accomplish is a toggle to allow the user to disable/enable push notifications at will. Is this possible with the current library?

I've only tested it in the foreground and I'm still receiving notifications.

**Comment by evollu** [comment]
I'm not sure how Firebase's deleteInstanceId work. this repo is simply calling their API.
The could be a delay in API as well. And it seems to be hard to get a new instanceId again after you delete it in iOS.

My approach would be either 
1. set up a flag indicating if the user wants to block notification
2. subscribe/unsubscribe to topics and only push through topics

**Comment by somoso** [comment]
Well this is actually also what we are doing as of now, but notifications are still coming through. This is a sample of our code if you want to take a look and spot anything that could be dodgy (feel free to ask for more specific code):

```
new Promise((resolve, reject) => {
        Promise.all([
            AsyncStorage.removeItem("fcmToken"),
            FCM.unsubscribeFromTopic("/topics/aaa"),
            FCM.unsubscribeFromTopic("/topics/bbb"),
            FCM.unsubscribeFromTopic("/topics/everyone"),
            FCM.cancelAllLocalNotifications(),
            FCM.removeAllDeliveredNotifications(),
            FCM.deleteInstanceId(),
        ]).then(resolve).catch(reject)
    })  
```

**Comment by evollu** [comment]
in that case, try native firebase example and see if you reproduce it

**Comment by dhcmega** [comment]
Hi @somoso 
have you solved this? Unsubscribed users to topic still receives notifications.
thanks

**Comment by somoso** [comment]
Yes I have:

## Problem
What would happen when users logged into our app is the FCM token would be sent back to the server to register the FCM token with the user. As a user requirement, the user wanted to be able to send push notification messages to users. We would send the push notifications directly to a FCM token instead of a topic, which is why the above completely failed.

## Solution
To solve this, we changed the backend to modify an existing API to allow the FCM token to be deleted by that user when they tapped "Unsubscribe to notifications". Eventually we migrated away from sending messages to individual tokens to sending to topics as they allowed messaging across many users, and users would be able to get the notifications when they turned their phones back on (unlike sending direct to FCM token). As of which, the above worked fine as the users who were still being targeted directly could opt out, and the ones who got the topics would be unsubscribed as before (as shown in the code sample above).

And last but not least, we removed `FCM.deleteInstanceId()` because other bug reports seemed to show it was more of a "nuke push notifications forever until the user reinstalls the app" button rather than "can you kindly take me off your direct push notification list please?" API.

**Comment by TayfunCesur** [comment]
Hi guys. Anyone have a simple example for handle this issue? Still getting this problem. I have a settings page that contains an option for enable/disable notifications. Enable option works like charm, but disable option not working for below code and I have not found any other solution except 
  **FirebaseInsatnceId.getInstance().deleteInstanceId()**

My code (for unregister) is here;

    

                            FCM.deleteEntityFCMToken();
                            FCM.deleteInstanceId().then((data) => {
                                console.log('asdsad', data);
                            }).catch(error => {
                                console.log('UNREGISTER ERRROR', error);
                            })`
