### ISSUE TITLE
Is react-native-fcm.podspec working ?

### ISSUE THREAD

**Issue by btoueg** [evollu/react-native-fcm#777]
I don't see any reference to `react-native-fcm.podspec` file either in docs or example project.

When adding:
```ruby
pod 'react-native-fcm', path: '../node_modules/react-native-fcm'
```
 
to my Pod file I get the following error:

```
In file included from /Users/***/***/node_modules/react-native-fcm/ios/RNFIRMessaging.m:1:
/Users/***/***/node_modules/react-native-fcm/ios/RNFIRMessaging.h:4:9: fatal error: module 'FirebaseCore' not found
@import FirebaseCore;
 ~~~~~~~^~~~~~~~~~~~
1 error generated.
```
![image](https://user-images.githubusercontent.com/498190/35862106-b795eef2-0b4a-11e8-959b-4cede68ff86a.png)

The example project in this repo does not make use of the podspec
I'm using RN 0.51.0 and react-native-fcm@11.3.1 or react-native-fcm@12.0.0
No device involved since I can't complete build

**Comment by btoueg** [comment]
I was stuck because I've optimistically switched to `Podfile` for `react-native-fcm` by removing old reference of `Libraries/react-native-fcm`

For a moment I was struggling to get back to the old-fashioned `react-native link` style. I realized having a Podfile changes the behaviour of `react-native link` so I rename `Podfile` to `Podfile2` and re-run `react-native link react-native-fcm`. It's working again, **sigh**...

The problem still remains, I do not understand how you are supposed to leverage [react-native-fcm.podspec](https://github.com/evollu/react-native-fcm/blob/v12.0.0/react-native-fcm.podspec)

**Comment by alexey-m-ukolov** [comment]
In addition to _react-native-fcm_ pod you [should add](https://github.com/evollu/react-native-fcm#pod-approach) _Firebase/Messaging_ to your Podfile.

**Comment by btoueg** [comment]
@alexey-m-ukolov possibly, and I tried that, but it does not affect the issue by any bit

**Comment by alexey-m-ukolov** [comment]
Have you tried deleting Pods directory and Podfile.lock and reinstalling all pods? I've had similar issue and it helped along with adding both react-native-fcm and Firebase/Messaging to Podfile.

**Comment by btoueg** [comment]
@alexey-m-ukolov Yes I did

I provided an example to reproduce the error where you can observe that even if you try deleting Pods directory and Podfile.lock and reinstalling all pods, it still doesn't work.

You can find it here https://github.com/evollu/react-native-fcm/pull/778

**Comment by evollu** [comment]
@btoueg try latest version. There was a PR that fixes header search path in Pod approach

**Comment by btoueg** [comment]
@evollu the [repro](https://github.com/evollu/react-native-fcm/pull/778) is done on react-native-fcm@12.0.0 which is on par with master at the moment of writing

What latest version are you talking about?

**Comment by evollu** [comment]
@btoueg I got 
```
[!] The name of the given podspec `Yoga` doesn't match the expected one `yoga`
```
Have you tried fixing it
```
pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
```

**Comment by btoueg** [comment]
Hi @evollu thanks for looking this up

What version of react-native are you using?

On my repro repo, I'm on 0.51.0 which expects `yoga` to be all lowercase.

Make sure you delete your node_modules and Pods, because I do not have such error

**Comment by Mark2xv** [comment]
Seeing this same issue using Cocoapods at the very last version. Temporarily using a workaround by  by removing the `@import Firebase*` lines, replacing them with `#import <Firebase/Firebase.h>`.
