### ISSUE TITLE
[Android] Build failed ':react-native-fcm' could not be found

### ISSUE THREAD

**Issue by FerdinandvHagen** [evollu/react-native-fcm#78]
I'm unable to add react-native-fcm, react-native-firebase-analytics, react-native-firebase-crash-report to my app. iOS is fine but on Android I receive the following error:

```
* Where:
Build file '/Users/ferdinandvonhagen/GoStudentDev/mobile-app/android/app/build.gradle' line: 131

* What went wrong:
A problem occurred evaluating project ':app'.
> Project with path ':react-native-fcm' could not be found in project ':app'.
```

I followed the steps from the README.md. My React Native version is 0.30.0.

Anybody an idea how to solve this issue?

**Comment by FerdinandvHagen** [comment]
Line 131 is just: `compile project(':react-native-fcm')`

**Comment by FerdinandvHagen** [comment]
```
dependencies {
    compile project(':react-native-fcm')
    compile project(':react-native-firebase-analytics')
    compile project(':react-native-vector-icons')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
    compile project(':react-native-code-push')
    compile project(':react-native-firebase-crash-report')
}
```

**Comment by FerdinandvHagen** [comment]
Issue with not installing the Google Repository correctly

**Comment by tomsap85** [comment]
@FerdinandvHagen i'm having the exact same problem
i.e.
```
A problem occurred evaluating project ':app'.
> Project with path ':react-native-fcm' could not be found in project ':app'.
```
though it looks like my Google Repository is installed correctly
![image](https://cloud.githubusercontent.com/assets/8276211/26029632/6fc3d976-3842-11e7-9a82-eec737dcb562.png)

**Comment by shihabkaranchery** [comment]
i am having the exact same issue not fixed yet.....

![Uploading Screenshot from 2017-05-20 12-56-10.png…]()

**Comment by cubabit** [comment]
I am having this issue too. Please re-open it!

**Comment by shihabkaranchery** [comment]
@cubabit Thanks !!! its fixed....

**Comment by cyphire** [comment]
Thank you!!! Same problem with self installation of react-native-firebase...

**Comment by cnsimbe** [comment]
The way I solved this was by having this:
`compile 'com.google.firebase:firebase-core:10.0.1'`
`compile project(':react-native-fcm')`

Instead of this
`compile project(':react-native-fcm')`
`compile 'com.google.firebase:firebase-core:10.0.1'`

(ie require the firebase-core plugin before the react-native-fcm)

**Comment by TranVanThaiSon** [comment]
I had same problem and result think, i slove that :
in android/setting.gradle file
add 2 line below:
include ':react-native-firebase'
project(':react-native-firebase').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-firebase/android')
