### ISSUE TITLE
RNFIRMessaging.h:4:9: fatal error: 'Firebase.h' file not found

### ISSUE THREAD

**Issue by AkilLis** [evollu/react-native-fcm#784]
After last update which 13.1.0 it gives that error.

react-native: 0.51.0
react-native-fcm: 13.1.0
Real device: IPhone 5s.

**Comment by AkilLis** [comment]
https://github.com/evollu/react-native-fcm/commit/134404cc54d73ef4866489ded84108e69fd1ef3c

**Comment by fnicastri** [comment]
I have the same problem.
Solved for the moment revertingo to:
@import FirebaseCore;
@import FirebaseMessaging;		
@import FirebaseInstanceID;

**Comment by airman00** [comment]
I was a little confused at first, so hopefully this will help the next person.

When you install Firebase manually following the Readme, put all the .framework files AND Firebase.h inside  /ios/Frameworks  folder.  Not just inside Xcode explorer in the Frameworks folder. Actually in a real folder called Frameworks inside the ios folder of your project. i.e. you can open up Finder and see this Frameworks folder.

react-native-fcm is *specifically* looking for Firebase.h in ios/Frameworks. As you can see in the image below, react-native-fcm has the following for Header Search Paths: (notice the 2nd path)
![image](https://user-images.githubusercontent.com/2061485/36066511-c38baf4a-0e78-11e8-971c-0bff83d7d70a.png)

**Comment by matt-oakes** [comment]
I think this is broken when following the instructions in the README using Cocoapods installation. I believe this is because the import is looking for `Firebase.h`, but the file in `ios/Pods/Headers/Public` is called `FirebaseCore.h`.

**Comment by matt-oakes** [comment]
Following the instructions to manually link Firebase works fine.

**Comment by evollu** [comment]
@matt-oakes `Firebase.h` is under `/Pods/Firebase/Core/Sources` if you install through cocoapods

**Comment by matt-oakes** [comment]
@evollu I can't check now because I went down the non-Cocoapods route, but following the instructions in the README from a fresh project caused the same error as this issue reports.

**Comment by vonovak** [comment]
also having this issue, using cocoapods. @fnicastri' 's solution worked for me

**Comment by evollu** [comment]
@vonovak when you do `pod install` it should put header file there automatically. You don't need to do anything.

**Comment by vonovak** [comment]
@evollu unfortunately, then I'm getting 'FirebaseAnalytics/FirebaseAnalytics.h' file not found. Note that I'm not using the podspect file that comes with the repo, because otherwise pods install `React 0.11` in my dependencies.. Any idea? Thanks.

**Comment by evollu** [comment]
@vonovak yes, removing `use_frameworks!` should make it work. oh I remember some people were using swift and has to use module. I don't know if it has changed

**Comment by vonovak** [comment]
I had it in my project which uses swift for a long time, but now I removed
and building still works, so I kept it removed :)

**Comment by temitope** [comment]
had the same issue. i also removed the frameworks requirement and avoided the invasive manual process (as it will be harder to remember to do this if im building from scratch). thanks @evollu  and @vonovak

**Comment by wmonecke** [comment]
> @import FirebaseCore;
> @import FirebaseMessaging;
> @import FirebaseInstanceID;

Where exactly do I put this? I also stumbled on this error.

**Comment by evollu** [comment]
@wmonecke the example project is using cocoa pods integration, try compare your difference

**Comment by temitope** [comment]
@wmonecke no, i got it to work by removing the `use_frameworks!` line in the `Podfile` for iOS

**Comment by jaschaio** [comment]
@wmonecke you can add this in the `RNFIRMessaging.h` File replacing Line 3

**Comment by ehacinom** [comment]
If you don't want to manually link, you can try installing RNFirebase as a pod install directly:

`pod 'RNFirebase', :path => 'path/to/node_modules/react-native-firebase/ios'`

Changing or hardcoding `HEADER_SEARCH_PATHS` did not help me. When the error recurs, it's not necessary to `rm -rf node_modules` nor delete the pod file etc, I found it useful to clear the cache.
