### ISSUE TITLE
RNFIRMessaging.h:4:9: fatal error: module 'FirebaseCore' not found

### ISSUE THREAD

**Issue by Andrew-Shook** [evollu/react-native-fcm#787]
Manually linked fire base. Frameworks in the Framework folder. Honestly, I've spent the last hour googling and search the issues for fixes, but nothing's worked. Should I just use a pod file?

I've also tried changing  to the #import "Firebase.h" with no success.

**Comment by evollu** [comment]
try latest version

**Comment by evollu** [comment]
try latest version. it looks for Firebase.h file, which i suppose you copy over together with manual link as well.
Everything should be under Frameworks folder

**Comment by Andrew-Shook** [comment]
So I'm using 13.1.0, and still getting the same error. To clear things up, I put all frameworks from "Analytics" into the framework directory, then all the frameworks from the "Messaging" into the framework directory, and added the "Firebase.h" file to the app directory(its right next to my AppDelegate.h. Also, I unlinked and relinked the pack with react-native.

**Comment by evollu** [comment]
move `Firebase.h` to be under `ios/Frameworks/`

**Comment by Andrew-Shook** [comment]
LIke this:
![screen shot 2018-02-09 at 3 58 23 pm](https://user-images.githubusercontent.com/2798090/36049822-2916f6de-0db2-11e8-81e2-987081a2e538.png)

**Comment by evollu** [comment]
yep. are these files in right physical location as well?

**Comment by Andrew-Shook** [comment]
Here is the layout in the project navigator. This is the default that can when react-native created the app.

![screen shot 2018-02-09 at 4 08 12 pm](https://user-images.githubusercontent.com/2798090/36050179-788a92b0-0db3-11e8-8119-4bac1a9a26ee.png)
 is there any special linking I need to do once I imported the header file to the Frameworks folder?

**Comment by evollu** [comment]
you need to make sure the files are in `ios/Frameworks/` in your file system, not the project navigator

**Comment by Andrew-Shook** [comment]
OK, all the files are now in reactRoot/ios/Frameworks/ including the the firebase header file, and I'm getting the same error.

**Comment by evollu** [comment]
can you provide an example repo with the issue?

**Comment by ikhsanalatsary** [comment]
@evollu can add `firebase.h` with linking via pods?

**Comment by evollu** [comment]
@ikhsanalatsary pod install adds firebase.h automatically

**Comment by samernady** [comment]
i am encountring the same issue while using pods

**Comment by verbaleks** [comment]
Try to update gem to latest version. This helped for me.
And i use @import Firebase;

**Comment by evollu** [comment]
the latest version should fix all scenario. let me know if it doesn't work

**Comment by ikhsanalatsary** [comment]
@evollu this isn't added automatically. previously, I followed @Bernhard---H solution [704](https://github.com/evollu/react-native-fcm/issues/704) and as you mentioned `Firebase.h` is under `/Pods/Firebase/Core/Sources` if you install through cocoapods [784](https://github.com/evollu/react-native-fcm/issues/784). The directory Sources is not found in my Pods.
![screen shot 2018-03-20 at 10 02 28 am](https://user-images.githubusercontent.com/5897415/37633678-e670cf34-2c25-11e8-8ea6-c1c75a9c7068.png)

So, my solution is to add `Firebase` to my pods as below:
```
pod 'Firebase'
pod 'FirebaseMessaging'
```

and it works for me

**Comment by evollu** [comment]
doesn't `pod 'FirebaseMessaging'` depends on `pod 'Firebase'`? shouldn't installing `FirebaseMessaging` causing `Firebase` being installed together? wierd

**Comment by himanshukk81** [comment]
Hi All,

I got fatal error: module 'Firebase' not found in ../node_modules/react-native-fcm/ios/RNFIRMessaging.h:9:9. 

Any Idea ??

**Comment by evollu** [comment]
@himanshukk81 get the latest of the repo and check latest readme.
if issue still persist, create a public repo so I can reproduce.
