### ISSUE TITLE
How to implement payload in a Cross-platform App

### ISSUE THREAD

**Issue by rtman** [evollu/react-native-fcm#788]
@evollu Hi, thanks for all the good work on this package it works great.

I have a question about how to handle cross platform apps using react-native-fcm. 

So, android needs a payload using `custom-notification` and ios needs `notification`, that's all well and good but how do you determine what payload to send at the time of sending? Do I need to keep track of the OS that each user is using? I'm thinking I could have each user update the db with the current OS in use when the app is opened then use that information to send the correct payload.

Or is there another way?

**Comment by evollu** [comment]
that is what I'm doing. will be happy if there is another way

**Comment by rtman** [comment]
Ah ok well I'll go ahead with this until something better comes up! Thanks
