### ISSUE TITLE
where to set app Id and how to get device token?

### ISSUE THREAD

**Issue by devekoperiOS** [evollu/react-native-fcm#79]
FCM.getFCMToken() is returning null. Where to set app Id? Please help.

**Comment by degroote22** [comment]
I had an issue while running on Genymotion. How are you experiencing this problem? Please give more information

**Comment by devekoperiOS** [comment]
I am also running on Genymotion. It gives me null value. I want to store device token on my server.

**Comment by andfs** [comment]
I'm running on device, and when the code executes FCM.getFCMToken() the app crashes and close

**Comment by evollu** [comment]
on the first load, getFCMToken could be null. Listen on token refresh and you will get the token

**Comment by devekoperiOS** [comment]
I have tried to display token in refreshToken as below:
this.refreshUnsubscribe = FCM.on('refreshToken', (token) => {
    console.log("TOKEN========="+token);
    // fcm token may not be available on first load, catch it here
  });
But its not logging this line.

**Comment by evollu** [comment]
can you check your native log and see if it prints token? for android, I mean logcat

**Comment by devekoperiOS** [comment]
I checked my logs on terminal. Its not displaying. Is there any place where I need to set any key I mean form google console application registration. How this app is identified by fcm?

**Comment by evollu** [comment]
you need to include a json file downloaded from firebase console into your solution. check readme

**Comment by devekoperiOS** [comment]
I have added google-services.json  in android/app.

**Comment by evollu** [comment]
can you share your project? or can you post your logcat log?

**Comment by devekoperiOS** [comment]
sure

**Comment by devekoperiOS** [comment]
Kalpeshs-MacBook-Air:DNTAndroidApp kparikh1984$ react-native run-android
Starting JS server...
Running adb reverse tcp:8081 tcp:8081
Could not run adb reverse: spawnSync adb ENOENT
Building and installing the app on the device (cd android && ./gradlew installDebug...
Incremental java compilation is an incubating feature.
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:react-native-fcm:preBuild UP-TO-DATE
:react-native-fcm:preReleaseBuild UP-TO-DATE
:react-native-fcm:compileReleaseNdk UP-TO-DATE
:react-native-fcm:compileLint
:react-native-fcm:copyReleaseLint UP-TO-DATE
:react-native-fcm:checkReleaseManifest
:react-native-fcm:preDebugAndroidTestBuild UP-TO-DATE
:react-native-fcm:preDebugBuild UP-TO-DATE
:react-native-fcm:preDebugUnitTestBuild UP-TO-DATE
:react-native-fcm:preReleaseUnitTestBuild UP-TO-DATE
:react-native-fcm:prepareComAndroidSupportAppcompatV72301Library UP-TO-DATE
:react-native-fcm:prepareComAndroidSupportRecyclerviewV72301Library UP-TO-DATE
:react-native-fcm:prepareComAndroidSupportSupportV42321Library UP-TO-DATE
:react-native-fcm:prepareComFacebookFrescoDrawee0110Library UP-TO-DATE
:react-native-fcm:prepareComFacebookFrescoFbcore0110Library UP-TO-DATE
:react-native-fcm:prepareComFacebookFrescoFresco0110Library UP-TO-DATE
:react-native-fcm:prepareComFacebookFrescoImagepipeline0110Library UP-TO-DATE
:react-native-fcm:prepareComFacebookFrescoImagepipelineBase0110Library UP-TO-DATE
:react-native-fcm:prepareComFacebookFrescoImagepipelineOkhttp30110Library UP-TO-DATE
:react-native-fcm:prepareComFacebookReactReactNative0310Library UP-TO-DATE
:react-native-fcm:prepareComFacebookSoloaderSoloader010Library UP-TO-DATE
:react-native-fcm:prepareComGoogleAndroidGmsPlayServicesBase900Library UP-TO-DATE
:react-native-fcm:prepareComGoogleAndroidGmsPlayServicesBasement900Library UP-TO-DATE
:react-native-fcm:prepareComGoogleAndroidGmsPlayServicesTasks900Library UP-TO-DATE
:react-native-fcm:prepareComGoogleFirebaseFirebaseAnalytics900Library UP-TO-DATE
:react-native-fcm:prepareComGoogleFirebaseFirebaseAnalyticsImpl900Library UP-TO-DATE
:react-native-fcm:prepareComGoogleFirebaseFirebaseCommon900Library UP-TO-DATE
:react-native-fcm:prepareComGoogleFirebaseFirebaseCore900Library UP-TO-DATE
:react-native-fcm:prepareComGoogleFirebaseFirebaseIid900Library UP-TO-DATE
:react-native-fcm:prepareComGoogleFirebaseFirebaseMessaging900Library UP-TO-DATE
:react-native-fcm:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:react-native-fcm:prepareReleaseDependencies
:react-native-fcm:compileReleaseAidl UP-TO-DATE
:react-native-fcm:compileReleaseRenderscript UP-TO-DATE
:react-native-fcm:generateReleaseBuildConfig UP-TO-DATE
:react-native-fcm:generateReleaseAssets UP-TO-DATE
:react-native-fcm:mergeReleaseAssets UP-TO-DATE
:react-native-fcm:generateReleaseResValues UP-TO-DATE
:react-native-fcm:generateReleaseResources UP-TO-DATE
:react-native-fcm:mergeReleaseResources UP-TO-DATE
:react-native-fcm:processReleaseManifest UP-TO-DATE
:react-native-fcm:processReleaseResources UP-TO-DATE
:react-native-fcm:generateReleaseSources UP-TO-DATE
:react-native-fcm:compileReleaseJavaWithJavac UP-TO-DATE
:react-native-fcm:extractReleaseAnnotations UP-TO-DATE
:react-native-fcm:mergeReleaseProguardFiles UP-TO-DATE
:react-native-fcm:packageReleaseRenderscript UP-TO-DATE
:react-native-fcm:packageReleaseResources UP-TO-DATE
:react-native-fcm:processReleaseJavaRes UP-TO-DATE
:react-native-fcm:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
:react-native-fcm:transformClassesAndResourcesWithSyncLibJarsForRelease UP-TO-DATE
:react-native-fcm:mergeReleaseJniLibFolders UP-TO-DATE
:react-native-fcm:transformNative_libsWithMergeJniLibsForRelease UP-TO-DATE
:react-native-fcm:transformNative_libsWithSyncJniLibsForRelease UP-TO-DATE
:react-native-fcm:bundleRelease UP-TO-DATE
:react-native-push-notification:preBuild UP-TO-DATE
:react-native-push-notification:preReleaseBuild UP-TO-DATE
:react-native-push-notification:compileReleaseNdk UP-TO-DATE
:react-native-push-notification:compileLint
:react-native-push-notification:copyReleaseLint UP-TO-DATE
:react-native-push-notification:checkReleaseManifest
:react-native-push-notification:preDebugAndroidTestBuild UP-TO-DATE
:react-native-push-notification:preDebugBuild UP-TO-DATE
:react-native-push-notification:preDebugUnitTestBuild UP-TO-DATE
:react-native-push-notification:preReleaseUnitTestBuild UP-TO-DATE
:react-native-push-notification:prepareComAndroidSupportAppcompatV72311Library UP-TO-DATE
:react-native-push-notification:prepareComAndroidSupportRecyclerviewV72301Library UP-TO-DATE
:react-native-push-notification:prepareComAndroidSupportSupportV42321Library UP-TO-DATE
:react-native-push-notification:prepareComFacebookFrescoDrawee0110Library UP-TO-DATE
:react-native-push-notification:prepareComFacebookFrescoFbcore0110Library UP-TO-DATE
:react-native-push-notification:prepareComFacebookFrescoFresco0110Library UP-TO-DATE
:react-native-push-notification:prepareComFacebookFrescoImagepipeline0110Library UP-TO-DATE
:react-native-push-notification:prepareComFacebookFrescoImagepipelineBase0110Library UP-TO-DATE
:react-native-push-notification:prepareComFacebookFrescoImagepipelineOkhttp30110Library UP-TO-DATE
:react-native-push-notification:prepareComFacebookReactReactNative0310Library UP-TO-DATE
:react-native-push-notification:prepareComFacebookSoloaderSoloader010Library UP-TO-DATE
:react-native-push-notification:prepareComGoogleAndroidGmsPlayServicesBase780Library UP-TO-DATE
:react-native-push-notification:prepareComGoogleAndroidGmsPlayServicesGcm780Library UP-TO-DATE
:react-native-push-notification:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:react-native-push-notification:prepareReleaseDependencies
:react-native-push-notification:compileReleaseAidl UP-TO-DATE
:react-native-push-notification:compileReleaseRenderscript UP-TO-DATE
:react-native-push-notification:generateReleaseBuildConfig UP-TO-DATE
:react-native-push-notification:generateReleaseAssets UP-TO-DATE
:react-native-push-notification:mergeReleaseAssets UP-TO-DATE
:react-native-push-notification:generateReleaseResValues UP-TO-DATE
:react-native-push-notification:generateReleaseResources UP-TO-DATE
:react-native-push-notification:mergeReleaseResources UP-TO-DATE
:react-native-push-notification:processReleaseManifest UP-TO-DATE
:react-native-push-notification:processReleaseResources UP-TO-DATE
:react-native-push-notification:generateReleaseSources UP-TO-DATE
:react-native-push-notification:compileReleaseJavaWithJavac UP-TO-DATE
:react-native-push-notification:extractReleaseAnnotations UP-TO-DATE
:react-native-push-notification:mergeReleaseProguardFiles UP-TO-DATE
:react-native-push-notification:packageReleaseRenderscript UP-TO-DATE
:react-native-push-notification:packageReleaseResources UP-TO-DATE
:react-native-push-notification:processReleaseJavaRes UP-TO-DATE
:react-native-push-notification:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
:react-native-push-notification:transformClassesAndResourcesWithSyncLibJarsForRelease UP-TO-DATE
:react-native-push-notification:mergeReleaseJniLibFolders UP-TO-DATE
:react-native-push-notification:transformNative_libsWithMergeJniLibsForRelease UP-TO-DATE
:react-native-push-notification:transformNative_libsWithSyncJniLibsForRelease UP-TO-DATE
:react-native-push-notification:bundleRelease UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72311Library UP-TO-DATE
:app:prepareComAndroidSupportRecyclerviewV72301Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV42321Library UP-TO-DATE
:app:prepareComFacebookFrescoDrawee0110Library UP-TO-DATE
:app:prepareComFacebookFrescoFbcore0110Library UP-TO-DATE
:app:prepareComFacebookFrescoFresco0110Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipeline0110Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipelineBase0110Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipelineOkhttp30110Library UP-TO-DATE
:app:prepareComFacebookReactReactNative0310Library UP-TO-DATE
:app:prepareComFacebookSoloaderSoloader010Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesBase900Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesBasement900Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesGcm900Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesIid900Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesTasks900Library UP-TO-DATE
:app:prepareComGoogleFirebaseFirebaseAnalytics900Library UP-TO-DATE
:app:prepareComGoogleFirebaseFirebaseAnalyticsImpl900Library UP-TO-DATE
:app:prepareComGoogleFirebaseFirebaseCommon900Library UP-TO-DATE
:app:prepareComGoogleFirebaseFirebaseCore900Library UP-TO-DATE
:app:prepareComGoogleFirebaseFirebaseIid900Library UP-TO-DATE
:app:prepareComGoogleFirebaseFirebaseMessaging900Library UP-TO-DATE
:app:prepareDNTAndroidAppReactNativeFcmUnspecifiedLibrary UP-TO-DATE
:app:prepareDNTAndroidAppReactNativePushNotificationUnspecifiedLibrary UP-TO-DATE
:app:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:processDebugGoogleServices
Parsing json file: /Users/kparikh1984/Downloads/DNT/DNTAndroidApp/android/app/google-services.json
:app:generateDebugResources
:app:mergeDebugResources UP-TO-DATE
:app:bundleDebugJsAndAssets SKIPPED
:app:processDebugManifest UP-TO-DATE
:app:processDebugResources UP-TO-DATE
:app:generateDebugSources UP-TO-DATE
:app:compileDebugJavaWithJavac UP-TO-DATE
:app:compileDebugNdk UP-TO-DATE
:app:compileDebugSources UP-TO-DATE
:app:prePackageMarkerForDebug
:app:transformClassesWithDexForDebug UP-TO-DATE
:app:mergeDebugJniLibFolders UP-TO-DATE
:app:transformNative_libsWithMergeJniLibsForDebug UP-TO-DATE
:app:processDebugJavaRes UP-TO-DATE
:app:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
:app:validateDebugSigning
:app:packageDebug UP-TO-DATE
:app:zipalignDebug UP-TO-DATE
:app:assembleDebug UP-TO-DATE
:app:installDebug
Installing APK 'app-debug.apk' on 'Google Nexus 6P - 6.0.0 - API 23 - 1440x2560 - 6.0' for app:debug
Installed on 1 device.

BUILD SUCCESSFUL

Total time: 27.533 secs

This build could be faster, please consider using the Gradle Daemon: https://docs.gradle.org/2.10/userguide/gradle_daemon.html
/bin/sh: adb: command not found
Starting the app (adb shell am start -n com.dntandroidapp/.MainActivity...
Kalpeshs-MacBook-Air:DNTAndroidApp kparikh1984$

**Comment by devekoperiOS** [comment]
I am not familiar with android environment. Please let me know if you are looking for anything else.

**Comment by evollu** [comment]
this is build log not logcat. I remember there is something like `react-native android log`. I use android studio myself.

**Comment by evollu** [comment]
BTW, android studio's emulator is better than Genymotion's free version

**Comment by devekoperiOS** [comment]
Can you guide me how to use catlog?

**Comment by devekoperiOS** [comment]
I can give my code.

**Comment by evollu** [comment]
I can take a look at your repo

**Comment by andfs** [comment]
sure @evollu 

https://github.com/andfs/zemo-react

**Comment by evollu** [comment]
I will take a look later today

**Comment by devekoperiOS** [comment]
I will send you link to my project.

**Comment by andfs** [comment]
Ok @evollu thanks in advance

**Comment by devekoperiOS** [comment]
@evollu following is link to my repo
https://github.com/devekoperiOS/myprojects/tree/master/DNTAndroidApp

**Comment by evollu** [comment]
@devekoperiOS I've tried your app and I'm able to log token from `FCM.getFCMToken()`. I'm building with android studio and android emulator running Lolipop

**Comment by evollu** [comment]
@andfs as we discussed in another issue, your problem probably lies in play service version lower than 3.0.

**Comment by andfs** [comment]
@evollu I think is not the version lower than 3.0 but multi declarations of google-play-services.
In your tutorial, you say to add com.google.gms:google-services:3.0.0 in the build.gradle of the app, but I have the packages react-native-maps and react-native-card-scan. These packages contains the following dependencies in build.gradle:
`compile 'com.google.android.gms:play-services-gcm:8.4.0'
  compile "com.google.android.gms:play-services-base:8.4.0"
  compile 'com.google.android.gms:play-services-maps:8.4.0'`

Do you know how to proceed? com.google.gms:google-services:3.0.0 replaces the others packages?

**Comment by evollu** [comment]
replace those 8.4.0 with +

**Comment by andfs** [comment]
Didn't work, I got the error:
`Unknown source file : com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/actions/ItemListIntents;`

I remove all google-services dependencies from react-native-maps and react-native-card-scan build.gradle but it doesn't work either

**Comment by andfs** [comment]
It seems that I found the solution 😄 
with this approach: 
https://github.com/lelandrichardson/react-native-maps/issues/249#issuecomment-229527188

My app didn't crash, now I'll try to implement the pushnotification

**Comment by devekoperiOS** [comment]
@evollu thank you for looking my problem. I am using Genymotion. I will try again and let you know if I still have problem.

**Comment by sibelius** [comment]
@evollu u can close this

**Comment by kaberibasu** [comment]
@evollu m getting different tokens in app delegate and FCM.getFCMToken(), also using token generated by FCM.getFCMToken() is showing invalid in Pusher app, plz help, its really urgent.

**Comment by kaberibasu** [comment]
@evollu in android build i get this issue... 
`* What went wrong:
A problem occurred configuring project ':app'.
> A problem occurred configuring project ':react-native-fcm'.
   > failed to find Build Tools revision 25.0.0

`
my build tool version in app.build.gradle is 23.0.1

**Comment by evollu** [comment]
If you upgrade tie android studio's SDK, you should get v25. There should be other ways to upgrade gradle version
As for badge count, my server persists the badge count for each user. Also when I clear badge, I send a post to server to update the badge
