### ISSUE TITLE
No Visible @Interface for RCTEventEmitter declares the selector addListener

### ISSUE THREAD

**Issue by airman00** [evollu/react-native-fcm#790]
In RNFIRMessaging.m

Running
react-native: 0.40.0
react-native-fcm:  13.1.0
Xcode 9.2 Beta

Getting this error when trying to compile:
Line 315 in RNFIRMessaging.m
"No Visible @ interface for RCTEventEmitter declares the selector addListener"
![image](https://user-images.githubusercontent.com/2061485/36066664-d9739400-0e7b-11e8-83aa-d43fa91f0597.png)

**Comment by philjoseph** [comment]
I have the same issue with RN 44.3 when I do upgrade to react-native-fcm: 13.1.0 from 10.0.
Running XCode 9.2

**Comment by evollu** [comment]
this has something to do we changes introduced in v13. let me look into it

**Comment by evollu** [comment]
for temporary fix, try add 
```
if([super respondsToSelector:@selector(addListener:)]){
```
around the problematic code

**Comment by FSAdam** [comment]
@evollu to clarify, should that code be added into the RNFIRMessaging.m file? 

I added it in on the line directly above the one throwing the error and added in a closing bracket, but the error remains the same.

**Comment by evollu** [comment]
It seems `addListener:` has been in react-native for 2 years. what version of RN are you using

**Comment by FSAdam** [comment]
I'm running react-native 0.43.4.

**Comment by evollu** [comment]
fixed in latest
