### ISSUE TITLE
error: cannot find symbol FirebaseApp

### ISSUE THREAD

**Issue by dhawaldev** [evollu/react-native-fcm#796]
Versions
RN: 0.53.0
react-native-fcm: 13.3.0
I made all the changes mentioned in the documentation. When I try to run the android app, it gives me the following error: " error: cannot find symbol FirebaseApp"
Location: class FIRMessagingModule
Note: I tried running the example in repo, facing same error for it.

**Comment by xmanemran** [comment]
Same here.

**Comment by baranbaygan** [comment]
Same here.

**Comment by baranbaygan** [comment]
Works when I pull firebase core version to 11.0.0

**Comment by dhawaldev** [comment]
Tried that. Still not resolved.

**Comment by xanderberkein** [comment]
#795 fixes this

**Comment by evollu** [comment]
fixed in 13.3.1

**Comment by dhawaldev** [comment]
Thank you. It worked!
