### ISSUE TITLE
About Listener in iOS

### ISSUE THREAD

**Issue by KwangsubAhn** [evollu/react-native-fcm#797]
When openning an issue, please include following information for better support

1. What version of RN and react-native-fcm are you running?  "^9.6.2"
2. What device are you using? (e.g iOS9 emulator, Android 6 device)? iOS Actual device, Android device
3. Is your app running in foreground, background or not running? running all

This is about listener issue when the app is in background and not running in case of iOS. What I am trying to do is, sending a message from server side, when get the message from mobile side. From server side, I didn't set notification payload because I am going to popup notification from mobile side using presentLocalNotification function. My question is why the listener is NOT triggered when app is background/not running in iOS? it works perfectly in Android as well as foreground in iOS.

If it's iOS system limit not allowing catch listener while not in foreground, I should setNotificationPayload. In that case, iOS get notification while in background BUT the listener (FCM.on(FCMEvent.Notification, async (notif) => { ... ) is not triggered which was triggered in Android version.

* MY MAIN CONCERN is that how can my listener keep working even if the app is swiped off by a user in iOS??
* Once I swipe off the app, listener never received message even in background which works before swiping off. This is weird too..

Here is code.
```
Server Side
// resend the incoming message to all participants
CcsOutMessage outMessage = new CcsOutMessage(senderRegId, messageId, inMessage.getDataPayload());
CcsClient client = CcsClient.getInstance();
client.sendBroadcast(outMessage, listRedIds);
```

```
Mobile Side

App.js
registerAppListener();
export default class App extends React.Component {
   ...
}

function registerAppListener(){
  FCM.on(FCMEvent.Notification, async (notif) => {
    //Need to get into this Listener. So I can popup using presentLocalNotification and do some stuffs.
    //Android is working perfectly fine fore/background, not running. However iOS works only in foreground but background/not running doesn't come into this trigger.
  }
}
```

**Comment by evollu** [comment]
this is frequently asked question. readme has some explanation.

iOS will wake up when receive notification in most cases and your JS callback will be triggered.
HOWEVER, if you swipe off your app, the app won't wake up anymore until launched by user again. System design.

in short, so don't use this approach for iOS.

**Comment by KwangsubAhn** [comment]
just a quick question. 

if iOS doesn't wake up the app, Does it mean, all the JS callback is ignored?

I have to store some data in mobile side whenever I get notifications which is done in my callback function.
