### ISSUE TITLE
Settings for iOS push notification (testing with postman)

### ISSUE THREAD

**Issue by KwangsubAhn** [evollu/react-native-fcm#798]
When openning an issue, please include following information for better support

What version of RN and react-native-fcm are you running? "^9.6.2"
What device are you using? (e.g iOS9 emulator, Android 6 device)? iOS Actual device, Android device
Is your app running in foreground, background or not running? running all

How can I prevent showing push notification when app is on foreground for iOS?
I am trying to test sending below message with postman and banner is always shown. I want it not to be shown WHEN app is foreground. Is there any setting?

```
{
"to":"my token",
  "content_available": true,
  "notification": {
      "title": "hello",
      "body": "kk",
      "click_action": "fcm.ACTION.HELLO"
  },
  "data": {
    "priority": "high"
  }  
}
```

**Comment by evollu** [comment]
https://github.com/evollu/react-native-fcm/blob/master/Examples/simple-fcm-client/app/Listeners.js#L51

returning `WillPresentNotificationResult.None` will prevent showing in foreground

**Comment by KwangsubAhn** [comment]
Thanks! it works great !!
