### ISSUE TITLE
subscribeToTopic unsubscribeToTopic Messages

### ISSUE THREAD

**Issue by arpu** [evollu/react-native-fcm#8]
i want server side send a push notification to all users of a app 

https://github.com/olucurious/PyFCM

is used to send to a Message topic "/topic/global"

or any other idea how i can send to all users?

**Comment by evollu** [comment]
I'm not using this feature so this is not implemented. However FCM library supports this feature, so all you need to do is adding some bridging.
Do you want to create a pull request?

**Comment by arpu** [comment]
ok thx a lot i will look at this 

firebase web console sends messages to User Segments and apps 
any idea how this can be done with server side code (http)?

**Comment by arpu** [comment]
@evollu  can you help in the implementation?

**Comment by evollu** [comment]
sure. I can do it this week.

the pub/sub feature is for GCM, I can't find any documentation for using firebase notification console via HTTP calls yet

**Comment by arpu** [comment]
https://firebase.google.com/docs/cloud-messaging/topic-messaging

**Comment by evollu** [comment]
working on it. should be published by tomorrow

**Comment by evollu** [comment]
@arpu done. please pull from master and see it is working

**Comment by evollu** [comment]
publish with 1.0.9

**Comment by arpu** [comment]
@evollu  works fine thx!
