### ISSUE TITLE
Clicking the notification with the app in foreground has data missing

### ISSUE THREAD

**Issue by rtman** [evollu/react-native-fcm#802]
@evollu  
I've been working on getting the on click working properly for my notifications, currently focusing on android. I have the on click for killed, and background working great but I'm having trouble when the app is in the foreground.  When the notification is first received, all the data I need is there but when I click on it all the data I need for my on click function is stripped out. Is there a solution for this?

Console log for when notification is received:
![notif_received](https://user-images.githubusercontent.com/20849135/36388858-880144f4-159d-11e8-818e-0199812283d5.PNG)

Console log for when that same notification is clicked:
![notif_clicked](https://user-images.githubusercontent.com/20849135/36388861-8b954502-159d-11e8-86c2-e3c541e61957.PNG)

My payload is:

```
           body = {
                "to": this.chat.token,
                "content_available": true,
                "priority": "high",
                //"click_action": "fcm.ACTION.OPEN_NOTIFICATION",
                "data": {
                    "senderUid": this.user.uid,
                    "chatDocId": this.chat.docId,
                    "messageDocId": messageDoc.id,
                    "show_in_foreground": true,
                    "companyName": this.chat.users[`${this.user.uid}`].companyName,
                    "groupChat": this.chat.groupChat,
                    "color":"#a7ffeb",
                    "priority":"high",
                    "id": this.chat.docId,
                    "show_in_foreground": true,
                    "sound": "default",
                    "click_action": "fcm.ACTION.HELLO",
                    "vibrate": 300,
                    "lights": true,
                    "senderUid": this.user.uid,
                    "chatDocId": this.chat.docId,
                    "messageDocId": messageDoc.id,
                    "body": messageText,
                    "title": this.user.displayName,
                    "icon": "notification_icon",
                },
                notification: {
                    "body": messageText,
                    "title": this.user.displayName,
                    "click_action": "fcm.ACTION.HELLO",
                    "sound": "default",
                    "vibrate": 300,
                    "lights": true,
                }
```

So to be clear the the important data that is missing is 

```
                    "senderUid": this.user.uid,
                    "chatDocId": this.chat.docId,
                    "messageDocId": messageDoc.id,
                    "companyName": this.chat.users[`${this.user.uid}`].companyName,
```

1. What version of RN and react-native-fcm are you running?
"react-native": "^0.49.3",
"react-native-fcm": "^12.0.0",

2. What device are you using? (e.g iOS9 emulator, Android 6 device)?
Android
3. Is your app running in foreground, background or not running?
foreground

**Comment by evollu** [comment]
since you are using FCM's SDK to build notification, try adding these information inside `notification` property?

**Comment by rtman** [comment]
@evollu sorry for the delay, got swamped.

If I added the information into the notification property, it still doesn't show.

**Comment by evollu** [comment]
just realized you are using android. `data` piece gets eaten by FCM when sent with `notification` and app is running. use `custom_notification`

**Comment by rtman** [comment]
Ok I will test this. I was actually using `custom_notification` before but switched to `notification` + `data` because something wasn't working. Will get back to you soon

**Comment by rtman** [comment]
@evollu 

Switching to this payload:

```
                "data":{
                    "custom_notification": {
                        "senderUid": this.user.uid,
                        "chatDocId": this.chat.docId,
                        "messageDocId": messageDoc.id,
                        "show_in_foreground": true,
                        "companyName": this.chat.users[`${this.user.uid}`].companyName,
                        "groupChat": this.chat.groupChat,
                        "color":"#a7ffeb",
                        "priority":"high",
                        "id": this.chat.docId,
                        "show_in_foreground": true,
                        "sound": "default",
                        "click_action": "fcm.ACTION.HELLO",
                        "vibrate": 300,
                        "lights": true,
                        "senderUid": this.user.uid,
                        "chatDocId": this.chat.docId,
                        "messageDocId": messageDoc.id,
                        "body": messageText,
                        "title": this.user.displayName,
                        "icon": "notification_icon",
                    }
                }
```

Fixed the issue, I can now receive the data in foreground and background when clicking the notification. But I'm not receiving a notification in the killed state anymore... Not sure what happened there.

**Comment by rtman** [comment]
@evollu 
NVM it was just the XIAO MI phone, I can now receive notifications on all 3 states as well as receive the data when clicking on the notification in all 3 states.

thanks!

**Comment by evollu** [comment]
cool

**Comment by sahil290791** [comment]
@rtman So, it does not work in killed state in a XiaoMi phone? As for me also it works in all 3 states in other phones except XiaoMi devices.

**Comment by rtman** [comment]
@sahil290791 

You have to enable AutoStart in Settings > Installed Apps > Your App Name > Autostart.

Really annoying that xiaomi does this.

**Comment by sahil290791** [comment]
@rtman I am seeing AutoStart option inside installed Apps > My App, do I need to add anything in AndroidManifest?

**Comment by sahil290791** [comment]
@rtman got it searched in settings, it was inside some security settings, may be its different in Mi phones running 7.0 .
