### ISSUE TITLE
when notification receive no vibrate and no sound in both ios and android

### ISSUE THREAD

**Issue by rjravijoshi** [evollu/react-native-fcm#803]
Before openning an issue
1. Reproduce it with the example project in this repo.
2. If you can't receive iOS notification, make sure you can receive notification using quickstart-ios project provided by Firebase team

When openning an issue, please include following information for better support

1. What version of RN and react-native-fcm are you running?
2. What device are you using? (e.g iOS9 emulator, Android 6 device)?
3. Is your app running in foreground, background or not running?

**Comment by rjravijoshi** [comment]
Plz give me any solution.

**Comment by evollu** [comment]
1. fill out the questions
2. try passing "default" first. invalid configuration will result in no sound

**Comment by sanjaymhj** [comment]
I am having same problem. 
No matter the app state, (foreground, background, killed). I do receive the push notification but no sound or vibration is played.
I am using the config, `{ badge: true, sound: true, alert: true }` while requesting the permission.

React Version: 16.3.0
React Native Version: 0.55.0
react-native-fcm: 14.1.4

**Comment by evollu** [comment]
@sanjaymhj what is your sound/vibrate settings in payload?

**Comment by sanjaymhj** [comment]
@evollu default

**Comment by evollu** [comment]
cool

**Comment by SunryTeang** [comment]
"notification": {
        "body": "1$ => 4100R",
        "title": "Monorom Exchange Rate",
        "visibility": "PUBLIC",
        "sound": "default",
        "badge": 1
    },
It work for both Android and IOS
