### ISSUE TITLE
I am getting fcm token before allowing for the permission of notification . I guess this is wrong

### ISSUE THREAD

**Issue by apurvaaggarwal** [evollu/react-native-fcm#804]
Before openning an issue
1. Reproduce it with the example project in this repo.
2. If you can't receive iOS notification, make sure you can receive notification using quickstart-ios project provided by Firebase team

When openning an issue, please include following information for better support

1. What version of RN and react-native-fcm are you running?
2. What device are you using? (e.g iOS9 emulator, Android 6 device)?
3. Is your app running in foreground, background or not running?

**Comment by evollu** [comment]
fcm token is assigned because it is actually firebase token used by all libraries in Firebase, e.g analytics. So it is generated no matter what.
The token will be associated with your iOS APNS token once you get permission
