### ISSUE TITLE
Invalid APNs certificate even if I used APNs Authentication Key

### ISSUE THREAD

**Issue by auxilioivy** [evollu/react-native-fcm#806]
"react-native": "^0.49.5",
"react-native-fcm": "^13.3.1",

    async componentDidMount() {
        await FCM.requestPermissions().then(()=>console.log('granted')).catch(()=>console.log('notification permission rejected'));

        FCM.getFCMToken().then(token => {
            console.log("TOKEN (getFCMToken)", token);
        });

        if(Platform.OS === 'ios'){
            FCM.getAPNSToken().then(token => {
                console.log("APNS TOKEN (getFCMToken)", token);
            });
        }

        FCM.getInitialNotification().then(notif => {
            console.log("INITIAL NOTIFICATION", notif)
        });

        FCM.on(FCMEvent.Notification, notif => {
            console.log("Notification", notif);
            if(notif.local_notification){
                return;
            }
            if(notif.opened_from_tray){
                return;
            }

            if(Platform.OS ==='ios'){
                switch(notif._notificationType){
                    case NotificationType.Remote:
                        notif.finish(RemoteNotificationResult.NewData) //other types available: RemoteNotificationResult.NewData, RemoteNotificationResult.ResultFailed
                        break;
                    case NotificationType.NotificationResponse:
                        notif.finish();
                        break;
                    case NotificationType.WillPresent:
                        notif.finish(WillPresentNotificationResult.All) //other types available: WillPresentNotificationResult.None
                        break;
                }
            }

        });
        FCM.enableDirectChannel();
        FCM.on(FCMEvent.DirectChannelConnectionChanged, (data) => {
            console.log('direct channel connected' + data);
        });
        setTimeout(function() {
            FCM.isDirectChannelEstablished().then(d => console.log(d));
        }, 1000);

        FCM.on(FCMEvent.RefreshToken, token => {
            console.log("TOKEN (refreshUnsubscribe)", token);
        });       
    }

I got an error on firebase  'Invalid APNs certificate. Check certificate in Settings'.

**Comment by evollu** [comment]
your Firebase Console is not configured properly
