### ISSUE TITLE
[Android] Notification not being received on device when app in background

### ISSUE THREAD

**Issue by pratomchaip** [evollu/react-native-fcm#807]
Notification is not being received on Android device when app is in background.
Notification is received when app is in foreground.

1. What version of RN and react-native-fcm are you running?
RN: 0.53.0 
react-native-fcm: 13.3.1

2. What device are you using? (e.g iOS9 emulator, Android 6 device)?
Samsung Galaxy S7 edge, Android 7 device

3. Is your app running in foreground, background or not running?
Background

Help, please.

**Comment by pratomchaip** [comment]
Hmm, so it seems as though the device does receive the notification but the notification dropdown doesn't display... it just goes straight into the notification list. You can see it when you swipe down the screen.

Does anyone know how to make the notification show up on the screen when the device receives it?

The Notification setting for the App is on and is not set to Silent.

**Comment by kyonzz** [comment]
In your server or where ever you use to send the notification, use custom notification instead of normal notification format. You can find custom notification format in example folder

**Comment by evollu** [comment]
let me know if @kyonzz 's solution doesn't work
