### ISSUE TITLE
[iOS] can't get notification banner when app is in foreground

### ISSUE THREAD

**Issue by n8stowell82** [evollu/react-native-fcm#809]
1. What version of RN and react-native-fcm are you running?
RN: 0.53.2 --- RN fcm: 13.3.1
2. What device are you using?
iOS 11 physical device
3. Is your app running in foreground, background or not running?
foreground

When I have the app running in the foreground, I get everything but the banner.  When in the background the banner will show up just fine.  However when in the foreground, I get the notification , vibration, and sound but no banner.  below is what I am sending in the local notification:

`FCM.presentLocalNotification({
              id: uniqueId,
              title: notif.aps.title,
              body: notif.aps.body,
              sound: "default",
              priority: "high",
              click_action: "com.willcalled.Chat",
              badge: 10,
              number: 10,
              show_in_foreground: true,
            });
`

I have set `FirebaseAppDelegateProxyEnabled` to both `Yes` and `No` with no difference. 

Not really sure where to go from here, and any help would be amazing.

thank you!

**Comment by evollu** [comment]
are you trying to build local notification for remote notification?

**Comment by n8stowell82** [comment]
yes. if I don't build the local notification, then I get nothing but the raw notification data when the app is in the foreground.  So the notification comes in just fine, and I can log out the contents of it, but I don't get a vibration, sound or banner unless I do the local notification.  When I build the local notification, I do get the vibration, sound and data, but no banner.  

Am I supposed to be getting the entire notification (banner and all) when the app is in the foreground without building a local notification?

**Comment by evollu** [comment]
you should get notification data when app is in foreground unless you return `WillPresentNotificationResult.None` in iOS 11

**Comment by n8stowell82** [comment]
correct.  I do get the notification data.  when I build the local notification so that the banner is shown while using the app, I only get the vibration and sound.  The banner is never shown.

**Comment by n8stowell82** [comment]
Ok that was the problem.  I was incorrectly setting notification result. Thank you for your help!

**Comment by witalobenicio** [comment]
@n8stowell82 you were to show a banner when app is in foreground? How?
