### ISSUE TITLE
Continuously getting duplicate push notifications for React native FCM

### ISSUE THREAD

**Issue by atitpatel** [evollu/react-native-fcm#810]
I keep on getting same Push Notification for single trigger from server.

I am using react-native-fcm(v13.x) for implementing PN on android. I am facing this issue on only some android devices(One Plus 5 and Samsung s5). [It is a device-specific issue. It works fine on some of the phones]

I have ensured following things :

- I am not registering listeners multiple times
- I have tried moving the code to another component
- There is no other receiver in AndroidMenifest file
- The server is sending a single notification for a single request from the app
React-native - 0.48.4

The issue occurs in both foreground and background mode.

**Comment by evollu** [comment]
try reproduce with FCM's native SDK.
have you installed multiple apps using this library?

**Comment by atitpatel** [comment]
I am using the library for 2 apps. But they are not installed together on a single device. These devices have a single app only. Can it still be a trouble?

**Comment by evollu** [comment]
then try reproduce with FCM's native SDK.

**Comment by atitpatel** [comment]
The issue got fixed. Unsure of the cause and resolution. Here is the combination which worked for me :

a) Removed dexOptions from build.gradle
b) Downgraded the react-native-fcm to v8.0.1 from 10.0.3 .
c) Changed version code

You can close the issue @evollu. Thanks for your help! :)

**Comment by anirban2015** [comment]
Its because of react-native link.

step 1:  react-native unlink react-native-fcm
step 2:  follow manual configuration

It solved my problem

**Comment by Kunalpaul12** [comment]
Please check settings.gradle file
My issues:- I was calling this twice
include ':react-native-fcm'
project(':react-native-fcm').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-fcm/android')

check this ones

**Comment by ishaqashraf** [comment]
@Kunalpaul12  thanks your solutions works
