### ISSUE TITLE
[Android] Notification doesn't show (not custom notification)

### ISSUE THREAD

**Issue by Yanaro** [evollu/react-native-fcm#817]
This is my payload:
`	
{
   "content_available": true,
   "notification": {
       "title": "hello",
       "body": "yo",
       "click_action": "fcm.ACTION.HELLO"
   },
   "data": {
       "extra":"juice"
   }
}
`

On android emulator, I can get drawn-over-app notifications from custom notifications, and I can then access the app by clicking on the banner on notification area. However, if I use normal notification as the payload shown, there won't be any notification pop out over other apps, and clicking on the banner simply removes it, there's no further action. 

Edit: I'm not using custom notification because it doesn't work on iOS, and I don't want to rewrite my backend just so I can make sure Android and web doesn't receive two different notifications because I have to send another message to iOS devices.

**Comment by sfm2222** [comment]
Are you testing notification on emulator? Try the real device.

**Comment by evollu** [comment]
@Yanaro yes. the default behavior on Android from FCM doesn't have banner. That is why I created custom_notification.
For now creating different types of payload is the only option. let me know if you find any other solution.
