### ISSUE TITLE
Example to Navigate user to some particular screen on notification click

### ISSUE THREAD

**Issue by sfm2222** [evollu/react-native-fcm#818]
@evollu  could you please add an example project to show what is the standard way of navigating users to some screen when notification is received using react-native-fcm library.

Because it is getting confusing/ complicated for no obvious reason. This is the list of issues I'm getting:

- Confuse where to get values in FCM.On event or in FCM.getInitialNotification.
- Notification data values not changed while received in getInitialNotification so navigating to the same screen when opening the app.
- Either defining event(FCM.ON & FCM.getInitialNotification) inside component lifecycle or outside.

and so many other questions. 

If you can do that it would be great. I'm ready to help in this regard to reproduce the above list, if needed.

1. What version of RN and react-native-fcm are you running?

2. What device are you using? (e.g iOS9 emulator, Android 6 device)?
all devices android/ios
3. Is your app running in foreground, background or not running?
foreground & background

**Comment by evollu** [comment]
there seems to be couple nav libraries.
which is more popular? react-navigation?

**Comment by sfm2222** [comment]
yes react-navigation is amongst the most popular one. If you can just provide one example project using it, it would be great,

**Comment by evollu** [comment]
example added

**Comment by sfm2222** [comment]
Thank you. I will update you if all issues are resolved.

**Comment by sfm2222** [comment]
@evollu  the example helped in this and issue is resolved.

**Comment by SatyamAccion** [comment]
@evollu can you please give me the example too ! i am also on the same place.

**Comment by Umar461386** [comment]
@evollu can you please give me the example. i am also on the same place please
