### ISSUE TITLE
Showing fcm notification message in JSON format when app is killed or in background in react-native-fcm

### ISSUE THREAD

**Issue by sanmish16** [evollu/react-native-fcm#822]
"react-native": "^0.52.3"
"react-native-fcm": "^13.3.3"
All android devices(5,6,7)

I am getting notification properly when my application is running, but when my application is in the background or killed then I am getting notification data in JSON format similarly in an image I shared here.
![screenshot_2018-02-28-15-18-10-587](https://user-images.githubusercontent.com/22679243/36786777-a2da1992-1cad-11e8-85b9-de0afa7c3afd.jpeg)

`componentDidMount() {
  
        FCM.requestPermissions().then(()=>console.log('granted')).catch(()=>console.log('notification permission rejected'));
      
        this.notificationListener = FCM.on(FCMEvent.Notification, async(notif) => {
            console.log('FCM notification', notif)
            this.sendRemote(notif)
        });

        FCM.getInitialNotification().then((notif: any) => {
           
            console.log("ifAny",notif)
            if (notif) {
                console.log("Any",notif)           
            }
        });
    }
`sendRemote(notif) {
    var data = notif.fcm.body;
    var title = notif.fcm.title;
    FCM.presentLocalNotification({
        title: 'App Name',
        body: title,
        big_text: title,
        large_icon: 'ic_launcher',
        priority: 'high',
        sound: "default",
        click_action: this.clickActions(notif),
        show_in_foreground: true,
        wake_screen: true,
        local: true,
        param: notif.notify_about,
        paramData: data
    });
}`

**notify_about:'', fcm:{action:null, body:"{data:'',time:''}", color:null, icon: '', tag:null, title:"Notification title"}**

this is my data format which I am sending from the server.

Here I want to show only data body. But when the app is killed or in the background, it shows the complete body in the notification.And Its working fine when the app is running.

**Comment by evollu** [comment]
the way you use looks weird. I assume you uses `notification` payload from server side. this will create a notification itself (notif 1). then your callback creates another notification (notif 2). Your code doesn't seem to remove any notification or override old notification, so I think you should see 2 notifications in list when app is foreground

You notification callback live in component lifecycle so when app is killed the notification callback is not registered. therefore you are just getting (notif 1)
