### ISSUE TITLE
Is there a way to ask again for permissions?

### ISSUE THREAD

**Issue by jaschaio** [evollu/react-native-fcm#828]
Hey there,
I couldn't find it in the readme so I am asking:

Any way I can ask again for the permissions if the user has initally rejected (for example accidentially) or if he has manually disabled them via the iOS Settings Menu?

Thanks

**Comment by evollu** [comment]
not as far as I know.

**Comment by alexdunne** [comment]
@jaschaio if you use something like https://github.com/yonahforst/react-native-permissions you can check if the user had denied the permission and if so use `openSettings()` to take the user to their permission settings.

**Comment by evollu** [comment]
sounds like a solution. can I close this?

**Comment by jaschaio** [comment]
Haven't come around to try it yet but will report afterwards
