### ISSUE TITLE
Multiple errors

### ISSUE THREAD

**Issue by andfs** [evollu/react-native-fcm#83]
1) Multiple Dex file error if there are some module using google services.
2) I removed the classpath 'com.google.gms:google-services:3.0.0' from my build.gradle (I'm using react-native-maps, that uses google services). Running on device after the method ComponentDidMount the app crash and close withou console errors or warnings.

**Comment by evollu** [comment]
com.google.gms:google-services:3.0.0 is required for firebase

**Comment by andfs** [comment]
@evollu How can I proceed with this errors? I use react-native-maps and react-native-cardscan that have some conflicts. I wasn't able to start my app with react-native-fcm. Any idea?

**Comment by evollu** [comment]
you can update the gms requirement in these 2 solutions to `+` so it doesn't lock down to lower version.
new version of gms should be backward compatible in most cases

**Comment by andfs** [comment]
you mean in react-native-cardscan and react-native-maps right?

**Comment by evollu** [comment]
yes

**Comment by andfs** [comment]
ok, I'll try

**Comment by evollu** [comment]
@andfs any updates?

**Comment by andfs** [comment]
@evollu I commented in other issue. The problem was the dependencies versions.
This worked for me

https://github.com/lelandrichardson/react-native-maps/issues/249#issuecomment-229527188


I'll close the issue.
