### ISSUE TITLE
react-native-fcm/ios/RNFIRMessaging.h:6:9: fatal error: 'Firebase.h' file not found

### ISSUE THREAD

**Issue by jthink0228** [evollu/react-native-fcm#830]
my project without Cocoapod,
correctly follow the README to link frameworks.

but still get the error:

RNFIRMessaging.h:6:9: fatal error: 'Firebase.h' file not found
#import <Firebase.h>

RNFIRMessaging.h:6:9: fatal error: Firebase file not found
@import Firebase

how can i fixed this issue?

    "react-native": "0.50.4",
    "react-native-fcm": "^14.0.1"

many thanks

**Comment by evollu** [comment]
there is no `#import <Firebase.h>` in `RNFIRMessaging.h` anymore
https://github.com/evollu/react-native-fcm/blob/master/ios/RNFIRMessaging.h#L4

are you sure you have got the latest version? check node_modules/react-native-fcm/package.json

**Comment by jthink0228** [comment]
yes
    "react-native": "0.50.4",
    "react-native-fcm": "^14.1.0",

react-native-fcm/ios/RNFIRMessaging.h:4:9: fatal error: module 'Firebase' not found
@import Firebase;

without Cocoapod still get this error..

i modify my project's User Header Search Paths and add $(PROJECT_DIR)/Frameworks

**Comment by jthink0228** [comment]
with Cocoapod get this issue,

ld: framework not found FirebaseAnalytics
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by evollu** [comment]
@jthink0228 can you post a public repo with the issue

**Comment by weathermanJM** [comment]
did this ever get resolved. I am having this issue as well.

**Comment by evollu** [comment]
@weathermanJM you shouldn't get this error if you use latest repo and follow readme

**Comment by weathermanJM** [comment]
ok well maybe i have put the frameworks folder in the wrong spot. does in go in my project or the node modules?

**Comment by evollu** [comment]
@weathermanJM check example in no-pod branch.

**Comment by weathermanJM** [comment]
I got this to work. Thanks

**Comment by VKGraphics** [comment]
give me solution .

**Comment by edritech93** [comment]
same
