### ISSUE TITLE
Android app crashes when receiving remote notification

### ISSUE THREAD

**Issue by wmonecke** [evollu/react-native-fcm#832]
I succesfully managed to implement the library and local notifications work fine :)

However, when I receive a Push notification from firebase, the app crashes when it is in foreground, or the app does not show the notification when in background.

I managed to get the following error using `adb logcat`:

```
 Rejecting re-init on previously-failed class java.lang.Class<com.evollu.react.fcm.MessagingService>: java.lang.NoClassDefFoundError:
Failed resolution of: Lcom/google/firebase/messaging/FirebaseMessagingService;
03-05 13:20:22.435 23810 23810 I art:
at java.lang.Class java.lang.VMClassLoader.findLoadedClass!(java.lang.ClassLoader, java.lang.String) (VMClassLoader.java:-2)

....

Caused by: java.lang.ClassNotFoundException:
Didn't find class "com.google.firebase.messaging.FirebaseMessagingService" on path:
DexPathList[[zip file "/data/app/com.lisdo-2/base.apk"],nativeLibraryDirectories=[/data/app/com.lisdo-2/lib/arm, /system/fake-libs, /data/app/com.lisdo-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
```

Any idea on how to fix this or what the cause may be?

```
"firebase": "^4.3.0",
"react-native": "^0.47.1",
"react-native-fcm": "^13.3.3",
```

**Comment by evollu** [comment]
looks like you didn't integrate the FCM SDK correctly.
have you tried search online
Didn't find class "com.google.firebase.messaging.FirebaseMessagingService" on path:

**Comment by wmonecke** [comment]
I missed adding `firebase-messaging` to my `app/build.gradle`!

Thank you!

**Comment by Ailton265** [comment]
I have the same problem. I have already tried to add firebase-messaging, but I isn't work. Any idea that how I can fix it? @evollu @wmonecke
