### ISSUE TITLE
Execution failed for task ':react-native-fcm:compileReleaseAidl'.

### ISSUE THREAD

**Issue by eng0mustafa** [evollu/react-native-fcm#841]
when i use react-native-fcm 
i got 
Execution failed for task ':react-native-fcm:compileReleaseAidl'.
> java.lang.IllegalStateException: aidl is missing
tried to change sdktools and gradle distribution but issue still

can you help me for that please
thank you

**Comment by evollu** [comment]
do you have any clue what aidl is?
I don't remember I have anything like this

**Comment by eng0mustafa** [comment]
thank you ..
this problem happened because an error with compatibility between gradle and sdktools
i solve it using this [https://github.com/facebook/react-native/issues/14733](url)
