### ISSUE TITLE
custom background notifications

### ISSUE THREAD

**Issue by tombaki** [evollu/react-native-fcm#843]
I use the example , when I'm in foreground I can edit the notifications because i'v sqlite db and when I received the notification I search in database then show it for user it's working fine in foreground .. but not work in background and when app killed .. it's only show the normal notification I sen't from the server i'v tested it on iPhoneX

**Comment by tombaki** [comment]
i'v fixed it on background too but still problem when app killed

**Comment by tombaki** [comment]
@evollu 
react-native-cli: 2.0.1
react-native: 0.53.3
react-native-fcm@14.1.0
iOS : 11.2.6
device: iPhoneX

**Comment by evollu** [comment]
when app is killed, no code is waken up on notification delivery. system limitation

**Comment by derit** [comment]
same issue on android, when app foreground the message work with call fcm event , but when app is killed only notify in tray, js code in gcm event  never  called
