### ISSUE TITLE
can`t get notification whan app is killed in real app 

### ISSUE THREAD

**Issue by eng0mustafa** [evollu/react-native-fcm#845]
hello sir,

i use the attached example
every thing is work good in android emulator 
but when i use real app (huawei honor 5x) it is not work when app killed or using clean 
is there any way or permission can i use for 

thank you

**Comment by evollu** [comment]
check if huawei has any phone settings limiting autostart or notificaiton

**Comment by stsiushkevich** [comment]
I have the same issue. I have tried Samsung Galaxy S5 and Huawei Y6 Pro. I think such problem is in all devices))) I opened this issue the past: https://github.com/evollu/react-native-fcm/issues/571

**Comment by eng0mustafa** [comment]
for huawie this solve it for me
[https://github.com/pgengoux/react-native-huawei-protected-apps](url)
