### ISSUE TITLE
Old notifications keep getting caught by `getInitialNotification`

### ISSUE THREAD

**Issue by xanderberkein** [evollu/react-native-fcm#847]
Hi,

I have following code in my componentDidMount (copied and adapted it from the example app)

```
async componentDidMount() {
    registerAppListener(this.props.rootNavigation);
    FCM.getInitialNotification().then(notif => {
      this.setState({
        initNotif: notif,
      });
      if (notif && notif.opened_from_tray) {
        console.log(notif);
        const navigateAction = NavigationActions.navigate({
          routeName: 'Root',
          action: NavigationActions.navigate({ routeName: 'MatchTab' }),
        });
        setTimeout(() => this.props.rootNavigation.dispatch(navigateAction), 500);
      }
    });
}
```

However, everytime I start my app now, the `getInitialNotification` still finds the newest notification (even if that notification is already opened), and it triggers the `navigate` again. Is there a way to let the `getInitialNotification` "forget" the latest notification if the app has been opened in the meantime?

So, to make it more clear:
- I get a notification
- I tap it
- I get redirected to the Root/MatchTab
- I close the app (background or killed, doesn't matter)
- I don't get a new notification
- I reopen the app
- I get redirected to the Root/MatchTab again, despite not receiving a new notification

Anything I can do to stop this behavior, and only redirect when a user enters the app by clicking the notification?

Running on a Android 7.1 device, with react-native 0.53.3, react-native-fcm 14.1.0

**Comment by xanderberkein** [comment]
The notification is weirdly enough almost completely empty though, when it gets picked up by `getInitialNotification` on app open (without clicking on one).

![image](https://user-images.githubusercontent.com/10937632/37412140-a1902d90-27a4-11e8-8b50-4d09cb206c00.png)

So, when I check if `notif.title` exist, I can distinguish *real* initialNotifications from the *fake* ones, that are picked up when just opening the app.

Is this the intended behavior?

**Comment by shekharskamble** [comment]
I am having the exact issue.....

**Comment by evollu** [comment]
@xanderberkein there is no way to clear the initial notification.
workaround would be adding a global variable outside of component lifecycle indicating if you have processed initial notification.

**Comment by ravishankar3961** [comment]
@evollu  is there any new way or any updates on this? I m facing this issue(or is it a behavior?) too.
