### ISSUE TITLE
Android not receiving notification when app is in foreground

### ISSUE THREAD

**Issue by nirajmchauhan** [evollu/react-native-fcm#852]
Hello,

My android app is not receiving notifications when the app is running and its in foreground. When I minimize the app or kill it, the notification appears.

I have added following listeners:

```js
FCM.getInitialNotification().then(notif => {
    if (notif && notif.someKey) {
        //do some action
    }
});

FCM.on(FCMEvent.Notification, notif => {
    console.log("Notification", notif);

    if (Platform.OS === 'ios' && notif._notificationType === NotificationType.WillPresent && !notif.local_notification) {
        // this notification is only to decide if you want to show the notification when user if in forground.
        // usually you can ignore it. just decide to show or not.
        notif.finish(WillPresentNotificationResult.All);
        return;
    }

    if (notif.opened_from_tray) {
        if (notif && notif.someKey) {
            //do some action
        }
    }

    if (Platform.OS === 'ios') {
        //optional
        //iOS requires developers to call completionHandler to end notification process. If you do not call it your background remote notifications could be throttled, to read more about it see the above documentation link.
        //This library handles it for you automatically with default behavior (for remote notification, finish with NoData; for WillPresent, finish depend on "show_in_foreground"). However if you want to return different result, follow the following code to override
        //notif._notificationType is available for iOS platfrom
        switch (notif._notificationType) {
            case NotificationType.Remote:
                notif.finish(RemoteNotificationResult.NewData) //other types available: RemoteNotificationResult.NewData, RemoteNotificationResult.ResultFailed
                break;
            case NotificationType.NotificationResponse:
                notif.finish();
                break;
            case NotificationType.WillPresent:
                notif.finish(WillPresentNotificationResult.All) //other types available: WillPresentNotificationResult.None
                // this type of notificaiton will be called only when you are in foreground.
                // if it is a remote notification, don't do any app logic here. Another notification callback will be triggered with type NotificationType.Remote
                break;
        }
    }
});
``` 

I tested this on RedMi 4 Phone

Version:  `14.1.1`

**Comment by mdsaddam** [comment]
Android shows notification only when app state is killed or background. To display notifications in app foreground, you need to show local notification. 

Sample code
```
FCM.on(FCMEvent.Notification, notif => {
    if (!notif.opened_from_tray) {
        showLocalNotification();
    }
});

showLocalNotification() {
    FCM.presentLocalNotification({
      id: new Date().valueOf().toString(),              // (optional for instant notification)
      title: "Test Notification with action",             // as FCM payload
      body: "Force touch to reply",                        // as FCM payload (required)
      show_in_foreground: true                              // notification when app is in foreground (local & remote)
    });
  }
```

For sample integration check react-native-fcm example app here https://github.com/evollu/react-native-fcm/blob/master/Examples/simple-fcm-client/app/App.js

**Comment by evollu** [comment]
@mdsaddam just pass `show_in_foreground` in your `data` property in remote notification. No need to build another local notification.
I've seen a lot of people doing that but it seems misleading.

**Comment by levsero** [comment]
@evollu I am also generating a local notification as I was not able to get the data field to work.

Setting the `show_in_foreground` does not appear to work as firebase requires that the values of the data field to be strings while to make it display in the foreground the field would have to be the bool true not a string.

**Comment by nirajmchauhan** [comment]
This only works in the android foreground with `presentLocalNotification`. Thank you

**Comment by evollu** [comment]
@levsero @nirajmchauhan just to keep in mind that presentLocalNotification approach won't work for iOS if user killed the app. If you are targeting only android it is ok

**Comment by nirajmchauhan** [comment]
@evollu On iOS I am getting the notifications even the app is killed. So this was only for android.

**Comment by evollu** [comment]
@nirajmchauhan ah you are using the `notification` property? in that case do you see duplicate notification in the notification list (pull down from tray)?

**Comment by nirajmchauhan** [comment]
@evollu Yes I am using `notification` property. I am not getting duplicate notifications.

**Comment by hardikmobileappsdev** [comment]
still this issue is happen!

did not solve yet?????
