### ISSUE TITLE
Handling on click with local notification

### ISSUE THREAD

**Issue by CptFabulouso** [evollu/react-native-fcm#856]
1. What version of RN and react-native-fcm are you running?
"react-native": "0.53.0"
"react-native-fcm": "14.1.0"

2. What device are you using? (e.g iOS9 emulator, Android 6 device)?
device - iPhone 5 - iOS 10.3.3
emulator - iPhoneX

3. Is your app running in foreground, background or not running?
foreground

Currently I find no way to figure out if local notification was clicked or just displayed, because method FCM.presentLocalNotification() and then clicking on the notification banner produces the same notif object in FCM.on(FCMEvent.Notification) listener. Value opened_from_tray is 0 in both cases here, because the app state does not change. Am I missing something?

**Comment by evollu** [comment]
just tried in example. you can click `Show Local Notification` button. and click the banner when it shows up. 
Alert shows and opened_from_tray is true

**Comment by vvusts** [comment]
@CptFabulouso what wa the issues did you solve it? I have same problem on ios

**Comment by CptFabulouso** [comment]
@vvusts No. Right now I do not even receive any callback if I tap the notification banner, so I have to first solve that.

**Comment by CptFabulouso** [comment]
@vvusts I think in my case there might be collision with `react-native-firebase`, do you use it? But I can't confirm it is responsible for `opened_from_tray` being always 0, because it behaves differently after I re-imported these libraries, right now 'react-native-fcm' does not receive any callbacks, seems like everything is consumed by `react-native-firebase'

**Comment by vvusts** [comment]
Yes I removed react-native-firebase from project then FCM function normally

**Comment by CptFabulouso** [comment]
Ok, After replacing `react-native-firebase` with `firebase` package, everything works fine, so it was package collision.

**Comment by jnrepo** [comment]
@CptFabulouso how did you fix this issue?

**Comment by CptFabulouso** [comment]
@jnrepo I removed `react-native-firebase` from my project.
