### ISSUE TITLE
Getting "Redefinition of module 'Firebase'" error while building

### ISSUE THREAD

**Issue by sarathvad1811** [evollu/react-native-fcm#862]
Issue: When trying to build we get this following error saying "Redefinition of module 'Firebase'" in module.modulemap file 

The errors looks like this
```
"ios/Pods/Firebase/Core/Sources/module.modulemap:1:8: Redefinition of module 'Firebase'"
```

My podsfile is as follows.

```
platform :ios, '8.0'

target 'App3Fcm' do
  use_frameworks!
  pod 'GoogleSignIn'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  
  pod 'Firebase/Messaging'

end

```

Was able to build successfully only after removing this file(ios/Pods/Firebase/Core/Sources/module.modulemap).

Please help. Thanks in advance

RN: 0.53.2
React: 16.2.0
react-native-fcm: 14.1.2
Platform: iOS 11

Device: Iphone 7 plus Real device

**Comment by evollu** [comment]
do you have `@import firebase` anywhere in your code?

**Comment by sarathvad1811** [comment]
Yeah... my bad copied the file module.modulemap manually in my IOS folder which was causing the issue

**Comment by MarcosVel** [comment]
Still having this issue, any help?
