### ISSUE TITLE
React native (Android)- Undefined is not an object (evaluating '_reactNativeFcm.FCM.requestPermissions') 

### ISSUE THREAD

**Issue by sritharanrbt** [evollu/react-native-fcm#866]
Hi , 
I am tring to install react-native-fcm 
I have followed and changed all the comments mentioned in this link 
https://github.com/evollu/react-native-fcm

but it shows like 

Please check the code for the NewsFeed component.
03-23 15:54:58.778   911  1002 W ReactNativeJS: Possible Unhandled Promise Rejection (id: 0):
03-23 15:54:58.778   911  1002 W ReactNativeJS: TypeError: TypeError: undefined is not an object (evaluating '_reactNativeFcm.FCM.requestPermissions') 

then i refer and tried react-native-link for multiple time but it does not help 

my react native version : "react-native": "0.51.0",
FCM : "react-native-fcm": "14.1.3",
Android SDK : compileSdkVersion 23

Plase do some help

**Comment by evollu** [comment]
integration issue.
are you using `import FCM from 'react-native-fcm'`?
check if FCM is undefined.

Also try comparing to the example project
https://github.com/evollu/react-native-fcm/tree/master/Examples/simple-fcm-client

**Comment by sritharanrbt** [comment]
thanks it's worked , i have just followed your code sample
