### ISSUE TITLE
Not getting permission alert in ios production but got alert permission in development. Is there any reason

### ISSUE THREAD

**Issue by arunravilla** [evollu/react-native-fcm#868]

**Comment by evollu** [comment]
shouldn't happen. have you granted/declined already?

**Comment by arunravilla** [comment]
@evollu I have tried deleting app multiple times
Sometimes it asks and sometimes it doesnt ask
Do I have to change any configuration for production?
I have already added production certificate

**Comment by evollu** [comment]
@arunravilla did you figure what was the cause?

**Comment by arunravilla** [comment]
@evollu This was issue with my implementation I was not using requestPermissions on right place
Thank you for your response

**Comment by wmonecke** [comment]
```
class App extends Component {
  componentWillMount() {
    
    FCM.requestPermissions();
  }
}
```

I am calling `.requestPermissions()` in componentWillMount with no parameters `i.e. badge, label`.

I wont ask for permissions, thus I cant get notifications in production. Do I need the parameters?

**Comment by wmonecke** [comment]
```
class App extends Component {
  componentWillMount() {
    
    FCM.requestPermissions();
  }
}
```

I am calling `.requestPermissions()` in componentWillMount with no parameters `i.e. badge, label`.

I wont ask for permissions, thus I cant get notifications in production. Do I need the parameters?

**Comment by wmonecke** [comment]
@arunravilla How can you not call `FCM.requestPermissions()` in the right place when it did work in development? Can you explain a bit more? I am having the same issue and I need to fix this ASAP.
