### ISSUE TITLE
[Feature Request] [Android] Auto Increment notification badge count

### ISSUE THREAD

**Issue by RossKinsella** [evollu/react-native-fcm#870]
Is there any interest in auto incrementing android badge count?

We could edit this to also accept a string of "Increment": https://github.com/evollu/react-native-fcm/commit/62dce36879de38157fb7091a57ef7534476343b9#diff-77f3859bd0bf7ddbde22431e14805fd3R37

Then in the BadgeHelper get the current badge count, increment it by one and set it back.

I'd PR in something myself but I'm not too familiar with working with Java / Open Source

**Comment by evollu** [comment]
@RossKinsella 
1. This feature can be achieved through JS callback easily. 
2. I prefer to keep behavior consistent between iOS and Android. and this can't be done though iOS
3. In some cases people will want to set badge count (even decrementing a bit?)

**Comment by RossKinsella** [comment]
> 1. This feature can be achieved through JS callback easily.

Oh! I didn't consider that I could just call something like
```
FCM.getBadgeNumber.then((badgeNumber) => FCM.setBadgeNumber(badgeNumber + 1))
```

One question on doing this via JS however. How do I increment the badge while the app is off?

My current setup is I have a helper class which gets instantiated when my root React component gets mounted. I then call a destroy method when the root component is getting dismounted. That destroy method removed my event listeners specific to FCM.

> 2. I prefer to keep behavior consistent between iOS and Android. and this can't be done though iOS

Ah - I was unaware of this. I was under the impression iOS is already automatically incrementing. I don't own an iOS device so have little oversight into whats happening there.

> 3. In some cases people will want to set badge count (even decrementing a bit?)

My intention was to create an optional auto increment specified by some value in the badge property of the notification payload

**Comment by evollu** [comment]
`One question on doing this via JS however. How do I increment the badge while the app is off?`
for android, the app will be wake up when getting notification. You can have another listener living outside of component lifecycle and only handles badge count.

`I don't own an iOS device so have little oversight into whats happening there.`
iOS won't wake up the app if the app has been killed by user manually. so this callback approach won't work

**Comment by RossKinsella** [comment]
Thanks for the advice, I'll close this off now
