### ISSUE TITLE
how unregister notification when logout app

### ISSUE THREAD

**Issue by Tiepbm** [evollu/react-native-fcm#874]
I don't want receive notification when I push notification to old token.

**Comment by evollu** [comment]
Firebase controls this.
If you want to enable/disable notification frequently, how about subscribe/unsubscribe user to a topic and only send notification to that topic?

**Comment by Tiepbm** [comment]
@evollu : 
My application has many users, each user will receive different notifications. If each user creates a topic, then too many.

**Comment by evollu** [comment]
you can use userId as topic. seems there is no limitation on topic number
https://stackoverflow.com/questions/38829466/limitations-for-firebase-notification-topics

**Comment by Tiepbm** [comment]
Thanks  @evollu!
