### ISSUE TITLE
On ios platform,await FCM.requestPermissions return nil

### ISSUE THREAD

**Issue by bobby4en** [evollu/react-native-fcm#878]
completionHandler:^(BOOL granted, NSError * _Nullable error) {
             if(granted){
                 resolve(@(granted));
             } else{

return should be resolve(@(granted));   but now the code is resolve(nil);

**Comment by evollu** [comment]
it is expected. if granted is false, the call will be rejected.

**Comment by bobby4en** [comment]
If ios version is 8 or 9, how can i get the @"Failed to grant permission" message?

**Comment by evollu** [comment]
@bobby4en you can't.
but you can check if permission is granted. react-native's own push notification library has the function
