### ISSUE TITLE
how to check if notification is in background or in foreground

### ISSUE THREAD

**Issue by sibelius** [evollu/react-native-fcm#88]
> if you pass content_available flag true, you will receive one when app is in background and another one when user resume the app.

How can I check if the `FCM.on('notification', (notif) => {})` was called on background or foreground?

**Comment by sibelius** [comment]
also how can I check if the user has clicked on my notification?

**Comment by sibelius** [comment]
On react-native-push-notification - https://github.com/zo0r/react-native-push-notification#handling-notifications

there is a field that show if it was received on foreground or not

foreground: false, // BOOLEAN: If the notification was received in foreground or not

**Comment by sibelius** [comment]
I've tried to use `AppState.currentState` but it is showing in background

**Comment by evollu** [comment]
do you mean when you receive the application when app is in foreground, `AppState.currentState` returns background?

**Comment by sibelius** [comment]
This is my scenario:

I close my app (send it to background)
I send a push notification with `content-available: true`, then I receive a notification on `FCM.on('notification', (notif) => {})`, in this case the `AppState.currentState` returns `background`

When I click the notification, it will receive another notification on `FCM.on`, and the `AppState.currentState` is `background` yet, so I don't know if the user clicked or not in my notification. the AppState changes after the FCM.on

I think that why react-native-push-notification (https://github.com/zo0r/react-native-push-notification#handling-notifications) has two flags to help with this scenario:

```js
foreground: false, // BOOLEAN: If the notification was received in foreground or not
userInteraction: false, // BOOLEAN: If the notification was opened by the user from the notification area or not
```

**Comment by sibelius** [comment]
what do think do use a `setTimeout` to check wait a little bit to appState to go active to check if the notification was clicked or not?

**Comment by evollu** [comment]
@sibelius timeout won't help because the delay is happening in native world.

**Comment by sibelius** [comment]
how r u handling this case for now?

**Comment by evollu** [comment]
I don't have a use case for now. But I will investigate how to do it the week.

**Comment by sibelius** [comment]
this kind of works for now

the first AppState.currentState it is in background, the one inside setTimeout is `active`
```js
this.notificationUnsubscribe = FCM.on('notification', (notif) => {
      console.log('APPSTATE: ', AppState.currentState);
      setTimeout(() => {
        console.log('APPSTATE TIME: ', AppState.currentState);
      }, 100)
})
```

My use case is send the user to a specific screen of my app when it click in the notification (deeplinking)

**Comment by evollu** [comment]
i guess it does take some time for app state for be updated. perhaps this check should happen inside module rather than relying on the javascript propery

**Comment by sibelius** [comment]
are you willing to review and accept a PR that makes this check inside native module?

similar to 

```js
foreground: false, // BOOLEAN: If the notification was received in foreground or not
userInteraction: false, // BOOLEAN: If the notification was opened by the user from the notification area or not
```

or `opened_from_tray` https://github.com/evollu/react-native-fcm/pull/87 ?

**Comment by evollu** [comment]
i think it will have the same issue as you have as it is just checking in javascript world

**Comment by evollu** [comment]
is `opened_from_tray` enough to solve your issue?

**Comment by sibelius** [comment]
when I click a notification on ios 10, it does not call FCM.on('notification', (notif) => {})

**Comment by evollu** [comment]
hmm.. let me try ios 10

**Comment by sibelius** [comment]
FCM.presentLocalNotification is not working on ios 10 either

**Comment by evollu** [comment]
have you tried ios 10 only or it works on ios 9?

**Comment by sibelius** [comment]
FCM.on('notification', (notif) => {}) is working fine on ios 9

I haven't tested presentLocalNotification on ios 9

**Comment by rturk** [comment]
@sibelius @evollu I can't run on IOS 10 either.

**Comment by evollu** [comment]
downloading ios 10

**Comment by rturk** [comment]
@evollu I can confirm that my app that is currently running the previous version works normally on IOS 9 and 10

**Comment by evollu** [comment]
@rturk you mean on('otification')?

**Comment by evollu** [comment]
@sibelius when you test local notification, is the app in foreground?

**Comment by sibelius** [comment]
it was in foreground

**Comment by evollu** [comment]
you can't won't see any notification when you are in foreground iOS. try sent a timeout and go background or use schedulelocalnotification

**Comment by sibelius** [comment]
it will only show if the app is in background?

**Comment by evollu** [comment]
yes. that is how remote notification work too. you won't see the banner

**Comment by sibelius** [comment]
so I can only use localNotification when the app is in background? 

could u add this info on README.md as well?

why it was working before?

**Comment by evollu** [comment]
no, you can only see notification when app is in background.
what is your use case? do you want to show a banner when app is in foreground? An alert makes more sense to me in this scenario.

**Comment by evollu** [comment]
@sibelius @rturk just tested in iOS 10, it is working for me (remote notification). What are your cases?

**Comment by sibelius** [comment]
For the local notification an alert makes more sense for sure!

If the app is in background, I wanna go to a specific screen when the user clicks the notification.
My problem is that FCM.on('notification') is not being called anymore when the user clicks in the notification

**Comment by evollu** [comment]
is that notification local or remote? local notification triggers FCM.on('localNotification')

**Comment by sibelius** [comment]
it is a remote notification

**Comment by evollu** [comment]
wired, mine gets triggered correctly

**Comment by sibelius** [comment]
r u in debugging mode?

**Comment by Kottidev** [comment]
AppState can tell you if the app is in the foreground or background, and notify you when the state changes.

https://facebook.github.io/react-native/docs/appstate.html

**Comment by sibelius** [comment]
fixed on master

tks for all the help @evollu
