### ISSUE TITLE
incorrect badge count in icon app

### ISSUE THREAD

**Issue by Tiepbm** [evollu/react-native-fcm#880]
When I push > 10 notifications to app, but App only show badge number = 10. 
How fix it?

**Comment by evollu** [comment]
does it happen to all devices/ os systems?

**Comment by Tiepbm** [comment]
@evollu : ip5s, iPad, xiaomi, samsung

**Comment by evollu** [comment]
so badge number is set by notification. which mean you have to set it as 11 manually though push notification. is your server code setting the badge count?

**Comment by Tiepbm** [comment]
this is my notification:
{
 "registration_ids" : ["fSFvWe0s_LE:APA91bEmCbaVprqAjXxa2ieIEK0kRh0a38ZuL4Es2Ox50KOGKrtcw8MGmG14RAKKRwS5_GhdNFEhjJFMOXnhFiueYqxtRjGYozjXBz_5aXprkIaTck8LCjdFCIovi_dUn3NtGik0A1EM"],
 "notification" : {
 "body" : "great match!",
 "title" : "Portugal vs. Denmark",
 "content_available" : true,
 "priority" : "high",
  "badge": 1,
  "show_in_foreground":true
 },
 "data" : {
"custom_notification":{
	"body" : "great match!",
 "title" : "Portugal vs. Denmark",
 "sound":"default",
 "opened_from_tray":true,
  "badge": 11,
  "show_in_foreground":true
}
 }}

but badge not work.

**Comment by evollu** [comment]
you can not use `notification` together with `custom_notification`.
custom_notification will get ignored

**Comment by Tiepbm** [comment]
thanks!
