### ISSUE TITLE
Apple Mach-O Linker (ld) Error Group [Compile error]

### ISSUE THREAD

**Issue by DiegoBittencourtOfficial** [evollu/react-native-fcm#889]
Hello, I'm trying to compile my project into an iPad Air 2 and I got this error:

![captura de tela 2018-04-07 as 11 03 12](https://user-images.githubusercontent.com/21102506/38455786-6b62455c-3a53-11e8-8d04-d4e37b3ae7b2.png)
![captura de tela 2018-04-07 as 11 04 53](https://user-images.githubusercontent.com/21102506/38455814-891f67c8-3a53-11e8-9435-c3a6d1beaa78.png)
![captura de tela 2018-04-07 as 11 07 35](https://user-images.githubusercontent.com/21102506/38455836-eb883afc-3a53-11e8-9aef-01a697c2e3d0.png)

My iPad uses iOS 11.3 and on xCode also I selected 11.3 on Deployment Target

Already deleted the DerivedData folder from Developer/xCode, also deleted the Build from myProject/iOS/Build

**Comment by evollu** [comment]
seems to be issue with FirebaseMessaging SDK itself.
Does it happen for enumerator or iphone?

**Comment by DiegoBittencourtOfficial** [comment]
I don`t know what do you mean by enumerator, but I was trying to compile to iPhone and iPad. Didin`t fixed the issue so I gave up trying to make it work without cocoapod and started the tutorial again with cocoapod. Compiled with success but none notification is showed on iOS, just on android. I'm trying to find what I did wrong now... Thanks for try help me

**Comment by evollu** [comment]
cool
