### ISSUE TITLE
[Android and IOS]When the app is closed,the notifications click is open app first page ,don't open specified page

### ISSUE THREAD

**Issue by YanYanLun** [evollu/react-native-fcm#89]

**Comment by sibelius** [comment]
@YanYanLun how r u handling navigation in your app?

could u post some code sample?

**Comment by YanYanLun** [comment]
@sibelius When the app is killed，When the notification is received, the notification FCM.on method does not listen to any data 



FCM.requestPermissions(); // for iOS
        FCM.getFCMToken().then(token => {
            console.log('----------***** 1111*', token)
            // store fcm token in your server
        });
        this.notificationUnsubscribe = FCM.on('notification', (notif) => {
            // there are two parts of notif. notif.notification contains the notification payload, notif.data contains data payload
            //点击事件
            console.log("--------------notif", notif)
            // clickNotification(notif);
            // Alert.alert(notif.title);
            singleton.setTitle("Crazy May Fest 2017");
            singleton.setRoute("DrawerMe");
            singleton.getNav().push({
                name: "SETTING"
            });
        });
        this.refreshUnsubscribe = FCM.on('refreshToken', (token) => {
            console.log('----------******', token)
            // fcm token may not be available on first load, catch it here
        });

        FCM.subscribeToTopic('/topics/foo-bar');
        FCM.unsubscribeFromTopic('/topics/foo-bar');

**Comment by sibelius** [comment]
U need to send the notification with content-available equals True

The problem is on iOS or android?

Could u post ur appdelegate.m?

U should also enable the capability in ur Xcode project to enable it to receive push notification when the app is in background

**Comment by YanYanLun** [comment]
@sibelius The problem is on android，

**Comment by saleeh93** [comment]
@YanYanLun @sibelius any update .?

**Comment by sibelius** [comment]
I'm not sure what is the problem/issue of @YanYanLun

**Comment by saleeh93** [comment]
The issue what he saying is when the app is closed ( not minimised ) when  user clicks on notification it does't fire the event 
```js
FCM.on('notification', (notif) => {
});
```

**Comment by evollu** [comment]
@saleeh93 then you should use FCM.getInitialNotification to get the notification that start the app

**Comment by saleeh93** [comment]
@evollu WIll check that

**Comment by sibelius** [comment]
`FCM.getInitialNotification` is not working on debug mode on iOS

**Comment by evollu** [comment]
any error log?

**Comment by sibelius** [comment]
it is hard to say, but it is working on Release mode

**Comment by sibelius** [comment]
it is not working on android even in release mode `FCM.getInitialNotification`

**Comment by sibelius** [comment]
@evollu do u mind sharing a repo example of ur setup using `react-native-fcm` ?

I think this would solve a lot of issues

**Comment by evollu** [comment]
ok i will create one.
are you using promise? `FCM.getInitialNotification.then(notif`?

**Comment by sibelius** [comment]
yep, I'm using the promise

I just wanna make sure all my iOS and Android configs matches yours

where do u put the `FCM.getInitialNotification.then((notif) => console.log('initial notif: ', notif))`?

**Comment by evollu** [comment]
in root component componentDidMount()

**Comment by sibelius** [comment]
@YanYanLun any process on this?

**Comment by ppsreejith** [comment]
Hey, I'm facing the same issue. FCM.getInitialNotification is undefined in both debug mode and release mode in iOS. Any update on this ?

**Comment by RocKhalil** [comment]
+1

**Comment by jonathanlie94** [comment]
+1 Having the same issue here. I use [https://github.com/aksonov/react-native-router-flux](react-native-router-flux) for my routing.

On the data payload, I put a category key to determine where to route when the user clicks the notification, however it seems that both the promise (getInitialNotification) and event listener (FCM.on) does not work for iOS for me.

Code looks like this: `
this.fcmNotificationUnsubscribe = FCM.on('notification', notification => {
      if (notification.category === 'new-article') {
        Actions.article({ type: ActionConst.RESET });
      } else if (notification.category === 'new-news') {
        this.props.dispatch(selectDate(new Date(notification.date)));
        Actions.news({ type: ActionConst.RESET });
      }
    });
`
and on componentDidMount: `
this.fcmNotificationUnsubscribe = FCM.on('notification', notification => {
      if (notification.category === 'new-article') {
        Actions.article({ type: ActionConst.RESET });
      } else if (notification.category === 'new-news') {
        this.props.dispatch(selectDate(new Date(notification.date)));
        Actions.news({ type: ActionConst.RESET });
      }
    });
`

**Comment by thphu** [comment]
Hi @evollu 
I'm facing the same issue. Let say, when I test on android, it perfect when minimize or in foreground. But when I close app or app killed by os (you can simulate by don't keep activity on device/setting/developer option). I received notification from fcm, tap and open, the FCM.on('notification',...) didn't trigger, but when I minimize (not close) the app and reopen by tap recent app (it doesn't have any notification at this time) the FCM.on('notification',...) triggered

**Comment by evollu** [comment]
@thphu the initial notification that triggers the app to launch lives in getInitialNotification
are you not getting anything there?

**Comment by evollu** [comment]
looking into it. seem there is race condition between the JS context vs native code
