### ISSUE TITLE
Listen to data message on backgroud

### ISSUE THREAD

**Issue by elad823** [evollu/react-native-fcm#891]
I am developing for iOS.

When a data message is sent, and the app is in background mode, FCM.on(FCMEvent.Notification...) is not triggered immediately but only when the app is going back to foreground mode.

How can the app be notify immediately when  data message is sent and the app is in background mode? I want to present Local notification when it happens .

* For notification message I do get immediate notification when the app is in Background. 
* I enabled FCM.enableDirectChannel()

**Comment by evollu** [comment]
do you have content_available:true?

**Comment by elad823** [comment]
Hi evollu,
Yes I do have.
I also added Listener to the direct channel: FCM.on(FCMEvent.DirectChannelConnectionChanged, (data) => {
        console.log('direct channel connected:' , data);
      });
and noticed that the status is changed to false when the app goes background.

**Comment by evollu** [comment]
` the status is changed to false when the app goes background.` that is expected.

do you have background mode feature flag turned on in xcode?

**Comment by elad823** [comment]
I am sorry my mistake, you was right. I put mistakely the content_available inside the data object. Now I moved it to the main object and I do get the notifiacations in background!
Thanks  a lot!

**Comment by evollu** [comment]
cool

**Comment by ttlpta** [comment]
@evollu @elad823 
{
	"to" : "dw3aUoEr...",

	"notification": {
	    "title": "Xxdd3333dh",
	    "body": "Clickadsdasdtail",
	    "show_in_foreground": true

    },
    "content_available" : true
}`
`
Sorry , for comment the closed issue.
But I still can not receive notification when ios app is in background.
Here is my body request. Is it true?

**Comment by evollu** [comment]
@ttlpta just to clarify here `"show_in_foreground": true` is part of `data`, not `notification`
you should receive notification however, try to add a breakpoint at https://github.com/evollu/react-native-fcm/blob/master/Examples/simple-fcm-client/ios/SimpleFcmClient/AppDelegate.m#L65
