### ISSUE TITLE
Can't change Android notification icon from default white square

### ISSUE THREAD

**Issue by stefanlenoach** [evollu/react-native-fcm#892]
I'm creating a local notification and would like to change the icon from the default white square to my app logo. I tried adding my white image with transparent background to the notification via the "icon" attribute but it doesn't work. Do I need to add this image to AndroidManifest.xml or something else?

**Comment by evollu** [comment]
are you setting `icon` property in payload?

**Comment by evollu** [comment]
try just `my_icon`
my_icon.png is in your mipmap folder right?

**Comment by stefanlenoach** [comment]
aha removing ".png" got it working. Thanks!!
