### ISSUE TITLE
I get a issue on Android side. The problem is, I can receive notification when it arrived (FCM.on(FCMEvent.Notification is called). But when I tap the notification banner, FCM.on(FCMEvent.Notification) did not get called. Anyone has the same problem? 

### ISSUE THREAD

**Issue by Lohins** [evollu/react-native-fcm#893]
Before openning an issue
1. Reproduce it with the example project in this repo.
2. If you can't receive iOS notification, make sure you can receive notification using quickstart-ios project provided by Firebase team

When openning an issue, please include following information for better support

1. What version of RN and react-native-fcm are you running?
2. What device are you using? (e.g iOS9 emulator, Android 6 device)?
3. Is your app running in foreground, background or not running?

**Comment by Lohins** [comment]
And on the console, I got some info:

- 04-12 11:26:20.393 562-992/? I/ActivityManager: START u0 {flg=0x20000000 cmp=com.dh_schedulerapp/.MainActivity (has extras)} from uid 10091 on display 0
- 04-12 11:26:20.393 562-992/? W/ActivityManager: startActivity called from non-Activity context; forcing Intent.FLAG_ACTIVITY_NEW_TASK for: Intent { flg=0x20000000 cmp=com.dh_schedulerapp/.MainActivity (has extras) }
- 04-12 11:26:20.399 188-606/? D/audio_hw_primary: select_devices: out_snd_device(2: speaker) in_snd_device(0: none)

**Comment by evollu** [comment]
@Lohins can you answer those questions?

**Comment by Lohins** [comment]
Sorry for replying late. I get it working. 
My scenario is that, I use 'react-native-navigation'. When I digged into this library, I found this library changes the running activity after starting the app, which means the running activity is no MainActivity yes, but NavigationActivity instead. Therefore, I change the attribute "setClassName" of Intent from 'YourPackageName.MainActivity' to 'YourPackageName.NavigationActivity'. And then add IntentFilter of NavigationActivity in  Manifest file. It works. !!!!!

**Comment by Lohins** [comment]
But I still have a question @evollu . 
When the app is killed in Android, and then I sent a fcm notification. I can see the notification in the status tray, but can  not receive notification. But when I click the msg in the tray and open the app. The notification is received. But the problem is that, the custom_notification filed is in its original format (the Json string). Like the following:

```
{ opened_from_tray: 1,
fcm: { action: 'android.intent.action.VIEW' },
collapse_key: 'com.dh_schedulerapp',
'google.message_id': '0:1523648179001615%486fccf4486fccf4',
from: '450553754457',
'google.ttl': 2419200,
'google.sent_time': 1523648178789,
custom_notification: '{"title" : "Dash Hudson", "priority": "high", "sound": "default", "body" : "You get a scheduled post.", "show_in_foreground": true, "type":"SHOW_POST", "post_id" : 239219}',
finish: [Function: finish] }
```

**Comment by evollu** [comment]
do you define your notification listener in component lifecycle?

**Comment by Lohins** [comment]
I try your demo and it did the same thing.

**Comment by evollu** [comment]
@Lohins yes it is a firebase behavior. it doesn't support nested objects. everything nested will be serialized into string

**Comment by Lohins** [comment]
Thanks a lot.

**Comment by illestrater** [comment]
@evollu I'm also experiencing the same issue.

I have sound: 'notification.mp3' in my payload. This worked when using react-native-push-notification, but I can't use that library any longer as it broke after I upgraded to SDK 27.

I've been trying to get the sound property to be set in the fcm: {} object, but to no avail
