### ISSUE TITLE
No longer receiving notifications after device updated to Android 8.0

### ISSUE THREAD

**Issue by ksegla** [evollu/react-native-fcm#898]
RN 0.54
react-native fcm 14.1.2

Notifications are working on all my devices, except the one who got updated to 8.0.
It could also be the gms 12.0 update. Both happen around the same time. Not sure which is causing this.

Anyone else on Android 8.0? (Unless the update messed up with the device fcm id?)

**Comment by evollu** [comment]
I assume you changed your SDK and build target to 8. in that case you have to create notification channels and use [this version of react-native-fcm](https://github.com/evollu/react-native-fcm/tree/sdk-26)

**Comment by ksegla** [comment]
@evollu Thanks a lot! Reverted to 25. All good, now :)
