### ISSUE TITLE
show_in_foreground is false but banner still showing when app is in foreground

### ISSUE THREAD

**Issue by vvusts** [evollu/react-native-fcm#908]
"react": "16.0.0-alpha.12",
"react-native": "0.52.1",
"react-native-fcm": "^14.1.3"

I don't want to show banner when I push notifications from server.
I thought this `show_in_foreground` would prevent it but it's still showing when app is in foreground.

For local notification I made: 
```
case NotificationType.WillPresent:
                notif.finish(WillPresentNotificationResult.None)
```
But for remote notifications this is not enough. 
How to stop showing banner when in foreground?
My use case is to show banner if app is not in foreground and do other things when it is.

This is how I send notification:
```
{
"to":"xxxxxxxxxxx",
"notification":
{
  "title":"Title", "body":"Description", "sound":"default"},
  "data":{"targetScreen":"details", "show_in_foreground": false},
  "priority":10
}
```

**Comment by sfm2222** [comment]
How you are able to show the notification when app was open.Kindly share more code of listener and other parts. I'm trying to do that.  https://github.com/evollu/react-native-fcm/issues/909

**Comment by evollu** [comment]
@vvusts if you don't want notification to be shown, use `data` message?

**Comment by vvusts** [comment]
@evollu not like that. Server should send notification but if app is in foreground I should show alert instead banner. Basically if app is in foreground alert and if app is closed or in background banner. Everything work fine there must be some trick to detect when notification arrived.

@sfm2222 what code part you want to see. I did everything like in doc and it worked.

**Comment by evollu** [comment]
you are having the issue with iOS only right?
```
case NotificationType.WillPresent:
                notif.finish(WillPresentNotificationResult.None)
``` 
should work for both remote and local notification in foreground.
