### ISSUE TITLE
iOS - Notification listener not working when app is not running

### ISSUE THREAD

**Issue by Strafer14** [evollu/react-native-fcm#918]
1. What version of RN and react-native-fcm are you running?  react: 16.3.1. react-native: 0.55.1, rect-native-fcm 12.0.0
2. What device are you using? (e.g iOS9 emulator, Android 6 device)? physical iPhone 7 with iOS11
3. Is your app running in foreground, background or not running? not running

Hello,
I'm trying to get my app to do something with accordance to data (chat-esque behaviour) from incoming FCM Messages. I'm sending FCM messages from a server with data payload and notification, everything works fine when the app is in foreground or background, but it does not work when app is not running and notification was swiped away (not clicked on).

I have tried using FCM.getInitialNotification() to catch the notification upon opening the app, however, it always yields undefined (unless app was opened from the notification itself).

I have also tried sending a message with just the data, but then it does nothing at all (when app is closed).

The listener itself (FCM.on(FCMEvent.Notification)) is in my index.js file (first file of the app).

Please let me know if any more information is needed, thanks!

**Comment by evollu** [comment]
"do something with accordance to data with message" are you trying to rely on chat message to sync data? it won't be reliable because user can disable notification
