### ISSUE TITLE
can we customize click action for redirecting to different pages ?

### ISSUE THREAD

**Issue by atul-forbinary** [evollu/react-native-fcm#920]
Before openning an issue
1. Reproduce it with the example project in this repo.
2. If you can't receive iOS notification, make sure you can receive notification using quickstart-ios project provided by Firebase team

When openning an issue, please include following information for better support

1. What version of RN and react-native-fcm are you running?
2. What device are you using? (e.g iOS9 emulator, Android 6 device)?
3. Is your app running in foreground, background or not running?

**Comment by evollu** [comment]
yes

**Comment by atul-forbinary** [comment]
click action example is there but i am not able to find navigation example on click action, i need it for both android and ios

**Comment by atul-forbinary** [comment]
solved issue , thanks @evollu

**Comment by DV31** [comment]
> solved issue , thanks @evollu

I'm facing the same issue please help me too for this.
