### ISSUE TITLE
How to conditionally disable IOS banner notification in foreground

### ISSUE THREAD

**Issue by rtman** [evollu/react-native-fcm#922]
Hi @evollu ,

I have notifications working in all app states, but I would like to conditionally disable the banner notification when on a certain screen. I have it working in Android since `FCM.presentLocalNotification` is what triggers the banner notification in foreground. But on IOS I can't it figure out, is it something to do with `notif.finish(WillPresentNotificationResult.All)` ?

I've searched quite a bit in the issues here and I still don't know. Can you please explain what part of the js code causes the banner to show in IOS when in foreground? Or better yet how to disable it conditionally?

This is a remote notification btw.

Thanks,

1. What version of RN and react-native-fcm are you running?

    "react-native": "^0.54.3",
    "react-native-fcm": "^12.0.0",

2. What device are you using? (e.g iOS9 emulator, Android 6 device)?

IOS iphone 6s

3. Is your app running in foreground, background or not running?

Foreground

**Comment by evollu** [comment]
check example code here
https://github.com/evollu/react-native-fcm/blob/master/Examples/simple-fcm-client/app/Listeners.js#L54
if you return notif.finish(WillPresentNotificationResult.None) it won't show notification

**Comment by rtman** [comment]
nice thanks!

**Comment by sfm2222** [comment]
@evollu  what   notif.finish(WillPresentNotificationResult.All) means?

**Comment by evollu** [comment]
@sfm2222 https://developer.apple.com/documentation/usernotifications/unusernotificationcenterdelegate/1649518-usernotificationcenter?language=objc
