### ISSUE TITLE
Could't receive push notification while app running in foreground only IOS.

### ISSUE THREAD

**Issue by AkilLis** [evollu/react-native-fcm#928]
It is any possible way to receive push notification in foreground ios. In android version configuring show_in_foreground set true succesfully received push notification. As a service backend using "firebase-admin" package.

1. react-native: 0.54.0, react-native-fcm: 11.2.0,
2. IOS5.1 Simulator
3. App running in foreground

**Comment by hugohenrique** [comment]
Same problem

**Comment by evollu** [comment]
foreground notification is only supported in iOS 10+

**Comment by AkilLis** [comment]
Thanks for your response. Next time double check on upper ios version too.

**Comment by evollu** [comment]
updated
