### ISSUE TITLE
Determinate if a user should get the notification or not

### ISSUE THREAD

**Issue by xristos3490** [evollu/react-native-fcm#93]
I was wondering, is there any way to limit the notification based on users preferences

ex.

```
this.notificationUnsubscribe = FCM.on('notification', (notif) => {
      // console.log(notif);
      if( user.dont.want.to.see.notifications ) {
           return false;
      }
    });
```

**Comment by sibelius** [comment]
this user preference should be handled by your application logic

you can store it on local storage on the app or in the server

after receiving the notification it is up to you to decide what should be done

**Comment by xristos3490** [comment]
We are in the same page here mate, what i actually asking is, what is the proper way to NOT show a notification... Is it to return false in the FCM.on('notification') callback? Or is another way? 

Documentation does not include enough information about this issue.

**Comment by sibelius** [comment]
if u send the notification with `notification` payload it will always shows the push notification for the user

u should send using only `data` in the payload you could decide to show using a local notification.
You can achieve this using this package: https://github.com/zo0r/react-native-push-notification#local-and-schedule-notifications

**Comment by holyxiaoxin** [comment]
if you want to use a library to show a notification: it can only be done when the app is opened right? what if you want to show notification when the app is closed? e.g. "you have received a new message"

**Comment by sibelius** [comment]
@xristos3490 how did u solve ur problem?

**Comment by ethan37** [comment]
I'm interested in this too...
