### ISSUE TITLE
Not able to access tapped notification from banner (android)

### ISSUE THREAD

**Issue by anish000kumar** [evollu/react-native-fcm#935]
## Info:
RN version: 0.50.3
react-native-fcm version:  14.2.0
Emulator: Android Google Nexus 5x 7.1.0 API 25
Issue encountered while app runs in background or is not running.

## Issue:
When I open the app by tapping on the notification banner, then:
```javascript
FCM.getInitialNotification().then(notif => {
       console.log(notif)
 });
```
`notif` is always `{ fcm: {action: null}, opened_from_tray: 1 }`. However, while the app is running in the foreground  `FCM.on(FCMEvent.Notification...` catches the notification perfectly with all the data attached to it.

**Comment by evollu** [comment]
do you have some splash screen implemented?

**Comment by anish000kumar** [comment]
@evollu yes, using https://github.com/crazycodeboy/react-native-splash-screen

**Comment by anish000kumar** [comment]
solved ! Just needed to pass data from spalshActivity to mainActivity , like so : ( line 13)
```java

    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        Intent intent = new Intent(this, MainActivity.class);
        intent.putExtra("payload", this.getIntent().getExtras());
        startActivity(intent);
        finish();

    }

```
