### ISSUE TITLE
Anyway to group messages?

### ISSUE THREAD

**Issue by DarrylD** [evollu/react-native-fcm#94]
For example, after 3 messages sent, opposed to showing 3, show one with some message saying it 3 available.

Not sure if this should be handled in this module or at the server layer (I'm leaning towards the app layer)

Thoughts?

**Comment by evollu** [comment]
android notification has grouping function that same kind of notification will be grouped into one bucket. Is that what you are looking for?

**Comment by DarrylD** [comment]
What makes it "the same kind"? I can send the same message 5 times and have 5 separate notifications.

**Comment by evollu** [comment]
https://firebase.google.com/docs/cloud-messaging/android/device-group

**Comment by holyxiaoxin** [comment]
I think what @DarrylD meant was, at time t0, user receives a message. and at time t0, user receives another message. at this point, can the message be combined into a single notification message? chat notification is a good example of this.

**Comment by evollu** [comment]
this sounds a very advanced usage. I think you need to maintain last notification sent time and skip programmatically either in client or server side. Do you know any app doing that?

**Comment by DarrylD** [comment]
> chat notification is a good example of this.

Chat is exactly what I'm doing . Best example app i can think of is facebook messenger.

I would maintain on the server and group messages but, then it's not "real time" anymore.

From the client side, is it a way to detect other active notifications?

**Comment by evollu** [comment]
yes, `getActiveNotifications` is supported in android. However it is not yet supported in this bridge module.

**Comment by DarrylD** [comment]
is it safe to say that would be the only way to achieve this functionality?

**Comment by evollu** [comment]
I don't know how facebook manage their notifications, but that is the only way I can think of for now.

**Comment by evollu** [comment]
@DarrylD hey something I find with Android. If you schedule notification manually, you can set a senderId and if the id is the same, the new notification will override the old one.

**Comment by DarrylD** [comment]
I think thats pretty convenient. I may have to manually check to see if the message has been opened or not before modifying the current message. I suppose I should be checking that anyway, lol.

**Comment by holyxiaoxin** [comment]
@evollu unless you can have a wake mechanism that wakes the app up for some time to do some background task like checking if a notification was received, you can't manually trigger a notification when the app is closed (not in the background).

**Comment by evollu** [comment]
@holyxiaoxin  notification can wake up apps even if app is not running, both iOS and android. However I haven't tested if js thread will start

**Comment by holyxiaoxin** [comment]
@evollu yes. Because notifications itself is native. But the jsthread only runs when the app starts. Or when you write a bridge to wake the app up to run some lines of code. There is a library for iOS that does it. But not yet for Android.

**Comment by evollu** [comment]
can you post a link to that library here? To me if i just want to build a custom notification, I will write some native code. That should be the most efficient way.

**Comment by holyxiaoxin** [comment]
@evollu yea I guess writing native code is fine. I could write native Android but not obj c for ios. I guess it helps alot to have a library that bridges this! Thanks for taking a look at this. Here it is https://github.com/transistorsoft/react-native-background-fetch

**Comment by DarrylD** [comment]
@holyxiaoxin that background fetch looks awesome, I've been looking for something like that for android for quite some time now. Know any other similar but, for android?

Closest thing i found is https://github.com/devfd/react-native-workers which suppose to have background services (which can run the js thread and any other react module) but, [isn't complete yet](https://github.com/devfd/react-native-workers/issues/5)

I would contribute but, my java skills are horrid.

**Comment by holyxiaoxin** [comment]
Just saw this section on FCM: https://firebase.google.com/docs/cloud-messaging/concept-options

Check this out guys!

**Comment by evollu** [comment]
nice `collapse_key`
thanks @holyxiaoxin

**Comment by holyxiaoxin** [comment]
I just tried it. It's not working. Can anyone confirm this?

**Comment by holyxiaoxin** [comment]
I think I've mistaken collapse_key. Just tested it out. 

When you set collapse_key:
It means that if your phone is not connected to 3G, it collapses the notifications into 1 (ignoring the rest) when it gets connected back on. 

When you do not set collapse_key:
You will receive multiple notifications!

Guess, it's not the "collapsible" we are looking for.

**Comment by evollu** [comment]
closing this as it is firebase/gcm problem
