### ISSUE TITLE
Xcode Archiving/Build Failing,Error Message ' Library not found for -lFirebaseCore'

### ISSUE THREAD

**Issue by Udbhav12** [evollu/react-native-fcm#942]
react-native version : 0.53.3
react-native-fcm version :  15.0.0

When I run react-native-run-ios command, my app builds successfully and is working fine

I use  Microsoft's AppCenter for testing apps on iPhones,even there app is building successfully

I need to deploy my app on App Store now, But when I build/Archive using Xcode,it fails and I get the error message '' Library not found for -lFirebaseCore'

I installed react-native-fcm using CocoaPods approach

Please find some screenshots which might be useful
![screen shot 2018-05-18 at 6 27 40 pm](https://user-images.githubusercontent.com/16081461/40235940-774160f6-5ac9-11e8-951b-f3c9f0d4d20e.png)
![screen shot 2018-05-18 at 6 27 01 pm](https://user-images.githubusercontent.com/16081461/40235959-8a9c859a-5ac9-11e8-8878-0e804f3d9812.png)

**Comment by SparkleFaerieCoder** [comment]
Could you say how you resolved this? I'm running into this issue as well

**Comment by Udbhav12** [comment]
@SparkleFaerieCoder I was using the .xcodeproj file instead of the .xcworkspace file. You just need to open the .xcworkspace file in Xcode

**Comment by ggendre** [comment]
On my side I was trying to build the project on an old device with ios9 but my deployment target was  ios11. I needed to run on an exmulator for xcode to tell me to lower my deployment target...

**Comment by kostyaVyrodov** [comment]
> @SparkleFaerieCoder I was using the .xcodeproj file instead of the .xcworkspace file. You just need to open the .xcworkspace file in Xcode

Thank you!
