### ISSUE TITLE
Possible incompatibility with react-native-firebase v4

### ISSUE THREAD

**Issue by jnrepo** [evollu/react-native-fcm#947]
Issue: clicking on the notification banner while the app in foreground will not trigger `FCM.on(FCMEvent.Notification, (notif) => {})`. 

I was able to reproduce the issue I was having on the sample project. All I had to do was install react-native-firebase (4.2.0) and the issue would start happening. When I revert react-native-firebase to version (3.3.1) the issue doesn't seem to happen. I'm wondering at this point if its better to completely migrate to using `Messaging` from `react-native-firebase` or if there was a workaround for this issue?

**Comment by evollu** [comment]
if you are using react-native-firebase, I would recommend migrating to them. I have created a migration example project https://github.com/evollu/react-native-fcm/tree/firebase/Examples/firebase-migration
