### ISSUE TITLE
App crashes when getting initial notification when debugging turned on

### ISSUE THREAD

**Issue by karlmosenbacher** [evollu/react-native-fcm#948]
# Issue
When calling getInitialNotification after application being terminated and reopened by the notification, the app crashes if the JS debugger is turned on. When I turn the debugger off the app doesnt crash anymore.

# Versions
react-native: 0.55.4
react-native-fcm: 15.0.2
Device/Simulator: Iphone 6 Simulator

**Comment by davidpricedev** [comment]
What is the error message when it crashes?

**Comment by karlmosenbacher** [comment]
@davidpricedev that a good question since I dont get any error messages. I just crashes. Will try to runt it with xcode and see if I get any messages from there.

**Comment by karlmosenbacher** [comment]
Looks like I can reproduce the issue, but I cant get any error messages after the app has been terminated. Closing it due to the lack of error messages.

**Comment by havinhthai** [comment]
Same issue on ios

**Comment by karlmosenbacher** [comment]
@havinhthai are you able to provide logs?

**Comment by havinhthai** [comment]
No, I haven't log. Just crash everytime I turn on React Native Debugger. 
I tried to remove react-natyive-fcm and relink but this time my app crash everytime run (on IOS).

**Comment by umerbaig** [comment]
same error on android
