### ISSUE TITLE
'FirebaseCore/FirebaseCore.h' file not found

### ISSUE THREAD

**Issue by somsin** [evollu/react-native-fcm#951]
why i am getting this issue any idea 'FirebaseCore/FirebaseCore.h' file not found

**Comment by karlmosenbacher** [comment]
On which platform have you installed the library on ? Ios ? Android?

**Comment by somsin** [comment]
'FirebaseCore/FirebaseCore.h in ios , and using react native

**Comment by somsin** [comment]
"react-native-fcm": "^15.0.2",
 "react-native-firebase": "^4.2.0",
this is in pod 
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'
  pod 'Firebase/Analytics'

**Comment by quangvo09** [comment]
I updated the Podfile and it worked for me.

pod 'Firebase/Core', '4.9.0'
pod 'Firebase/Messaging', '4.9.0'
pod 'FirebaseAnalytics', '4.0.9'

**Comment by somsin** [comment]
whats your "react-native-fcm":",
"react-native-firebase":  version in package.json

**Comment by uditalias** [comment]
@quangvo09 I love you man!

**Comment by Kottidev** [comment]
@quangvo09  Thank you man!

**Comment by ashleymills** [comment]
Check you've opened the `.xcworkspace` file before building, rather than the `.xcodeproj`
