### ISSUE TITLE
Remove listener FCM.on

### ISSUE THREAD

**Issue by ArthurAttout** [evollu/react-native-fcm#954]
I use `FCM.on(FCMEvent.Notification,...` to trigger custom actions when a notification is received. 

I cannot find a way to remove this listener, in order to make the device ignore any incoming notifications. Which method should I use ? 

The reason why I want to do that is because it seems that the FCM.on callback is registered on and on each time the app restarts. If the app restarts 3 times, the user will receive a notification duplicated 3 times (because all the callbacks are being stacked). 

Thanks !

**Comment by tiaaaa123** [comment]
What is the solution?

**Comment by ArthurAttout** [comment]
As far as I remember, I closed the issue because the problem was with my code. The listener were removed when the app is restarted, but I didn't find any way to remove them manually.

**Comment by never00miss** [comment]
is it simple, put count on your initFCM and if count is bigger than > 0, dont initFCM again
