### ISSUE TITLE
xcode 8 / ios 10: issue saving token

### ISSUE THREAD

**Issue by tijs** [evollu/react-native-fcm#96]
I am looking if the upcoming launch will cause issues for our app and one thing i found was an issue with saving the token. On start our app checks if we already have a token and requests one if not:
```
    FCM.requestPermissions(); // only needed on iOS
    FCM.getFCMToken().then(token => {
        setNotificationToken(user, token)
        .then(action => {
          dispatch(action); // save token locally
        })
        .catch(err => {
          Logger.logException(err, { token });
        });
    });
```
this worked fine but if build the same project on xcode 8 and run it in the simulator i see the following error in the xcode logs:

    <FIRInstanceID/WARNING> Error unable to save iid-token to keychain Error Domain=com.google.iid Code=-34018 "(null)

And the getFMCToken() method above then returns `undefined` instead of a token. Could this be an issue with certificates or is this an issue in the fcm package?

**Comment by tijs** [comment]
Ah already found it! For anyone else who runs into this. It is now necessary to add entitlements to the push notification capabilities as outlined here: http://stackoverflow.com/a/38543243/89443

**Comment by MaheshNandam** [comment]
@evollu ,

Facing the same issue as FCM.getFCMToken() is giving undefined token value, please look into this issue ASAP.
My Package:
"react": "16.0.0",
"react-native": "0.50.4",
"react-native-fcm": "^10.0.3",
