### ISSUE TITLE
No visible @interface for 'FIRQuery' declares the selector 'addSnapshotListenerWithIncludeMetadataChanges:listener:'

### ISSUE THREAD

**Issue by somsin** [evollu/react-native-fcm#960]
app was working randomly this error is started coming 

No visible @interface for 'FIRQuery' declares the selector 'addSnapshotListenerWithIncludeMetadataChanges:listener:'
<img width="743" alt="screen shot 2018-05-29 at 11 36 23 pm" src="https://user-images.githubusercontent.com/4973590/40676703-2e9f95d8-6399-11e8-99da-984ef1b56dec.png">

**Comment by evollu** [comment]
this seems to be react-native-firebase issue.
BTW, if you are using their library. you can build notification using their API.
I have a sample project https://github.com/evollu/react-native-fcm/tree/firebase/Examples/firebase-migration
