### ISSUE TITLE
[IOS Noti] Not show in background mode, only show when app is in foreground

### ISSUE THREAD

**Issue by ttlpta** [evollu/react-native-fcm#964]
1. I use "react": "16.3.1" and "react-native-fcm": "^15.0.2",
2.  iOS10 emulator
3. App running in background.

Here is my code

`FCM.on(FCMEvent.Notification, notif => {
      console.log("Notification", notif);
      
      if(notif.local_notification){
        return;
      }
      if(notif.opened_from_tray){
        return;
      }

      if(Platform.OS ==='ios'){
          //optional
          //iOS requires developers to call completionHandler to end notification process. If you do not call it your background remote notifications could be throttled, to read more about it see the above documentation link.
          //This library handles it for you automatically with default behavior (for remote notification, finish with NoData; for WillPresent, finish depend on "show_in_foreground"). However if you want to return different result, follow the following code to override
          //notif._notificationType is available for iOS platfrom
          switch(notif._notificationType){
            case NotificationType.Remote:
              notif.finish(RemoteNotificationResult.NewData) //other types available: RemoteNotificationResult.NewData, RemoteNotificationResult.ResultFailed
              break;
            case NotificationType.NotificationResponse:
              notif.finish();
              break;
            case NotificationType.WillPresent:
              notif.finish(WillPresentNotificationResult.All) //other types available: WillPresentNotificationResult.None
              break;
          }
        }
        FCM.presentLocalNotification({
          title: notif.notification.title,
          body: notif.notification.body,
          priority: "high",
          // click_action: notif.click_action,
          show_in_foreground: false
        });
  });`

**Comment by maggialejandro** [comment]
You need a real device to test Notifications

**Comment by ttlpta** [comment]
Yes, I already have used real device IP 8. I uploaded certificate to firebase setting, Turn flag FirebaseAppDelegateProxyEnable to false, add proprety content-avaiable to body request.
Everything did not help. :(
I can receive notification with pushtry with token which I log when debug.
But can not receive notification with firebase send message.

**Comment by maggialejandro** [comment]
I have a similar issue, https://github.com/evollu/react-native-fcm/issues/958
Check out my configuration
