### ISSUE TITLE
App is opening when notification arrives

### ISSUE THREAD

**Issue by igor-nm** [evollu/react-native-fcm#967]
Application opening when notification arrives, but this error happens just if app are dead. When app is foreground and minimized the flow is perfect.
Type notification: remote.

1. What version of RN and react-native-fcm are you running?
react-native: 0.52 | react-native-fcm: 15.0.2

2. What device are you using?
Android: 7.1.1 (device)

3. Is your app running in foreground, background or not running?
This error happens just when app are in background (dead), if app was minimized and not dead, this problem not happens.

**Comment by igor-nm** [comment]
Not that I remember, but I will go make a revision because I can have a done without perceive.
I would like of the explain that I maked the class MessagingService in my project, because I was need personalize the format notification and treat the apresentation, and this was done in Kotlin, i don't know if contribuite but it is interesing share with you.

Thank you so much.
Be right back when I'll have news.

**Comment by igor-nm** [comment]
Hello guys, sorry for the delay.
How @evollu  said, the problem was a piece of my code that brought the app to the foreground.
But I fixed  and now, it work usually!!!

**Comment by JonathanRufino** [comment]
@igor-nm Could you explain what you did to solve it? I'm having exactly the same behavior.
