### ISSUE TITLE
Display normal notification on Android when app is in foreground

### ISSUE THREAD

**Issue by mdamien** [evollu/react-native-fcm#97]
In the README, it says:

> When app is running in foreground
> 
> IOS will receive notification and **android won't** (better not to do anything in foreground for hybrid and send a seprate data message.)

This doesn't seems like it's the default android behavior and I would prefer the app not to "swallow" the notification.

Is it possible to disable this behavior ?

**Comment by evollu** [comment]
FCM sdk swallowed it, not me

**Comment by mdamien** [comment]
Thanks for the feedback, gonna report that to the FCM sdk then and implement the local notif.

**Comment by evollu** [comment]
cool BTW, local notification for this repo is on the way. should release this week

**Comment by ianbarber** [comment]
Saw the report through our docs feedback button!  https://firebase.google.com/docs/cloud-messaging/android/receive has the receiver code - if the app is in the background, it'll automatically create a notification, otherwise you'll get the message to the onMessageReceived of that service. 

If you're keen on the ability to disable it, you can request the feature here: https://firebase.google.com/support/contact/bugs-features/

Let me know if I'm completely misunderstanding the intention here though!

**Comment by mdamien** [comment]
Response from the Firebase team for the feature request:

> Hi Damien,
> 
> I'm very sorry for the delay here. Our internal discussion for this took quite some time. 
> 
> Right now, this is just how "notification messages" are designed. They are received by the system tray when app is in background, then in the onMessageReceived() method when app is in foreground. Thus, for now, you'd need to manually build your own notification to display your message while app is in foreground. Reference [here](https://firebase.google.com/docs/cloud-messaging/android/receive#handling_messages).
> 
> We can't share why it's designed like this, but we're continuing to work on the framework based on user feedback. So thanks for bringing this up!
> 
> Let me know if you have any additional concerns. 
> 
> Regards, 
> Kat

**Comment by sfm2222** [comment]
@evollu @mdamien   is this still the same for latest release? that notification don't show up when app is open and local notification is required.

**Comment by devabhi36** [comment]
@mdamien now we are in 2019, approximately 2.5 years ahead of the time when you wrote you are working on framework. Have you guys did it so that notifications can be received in notification tray when app is in foreground.

**Comment by mdamien** [comment]
@devabhi36 I'm a simple ~~peasant~~ library user like you, what you see pasted is just a reply I got from the Firebase team.
