### ISSUE TITLE
how can I attach image in notification in IOS app

### ISSUE THREAD

**Issue by kartavyaparekh96** [evollu/react-native-fcm#972]
I created a react native app for IOS and sending notification successfully through react native fcm.
But now I want to send image as well. Can someone guide me how to achieve this?

**Comment by kartavyaparekh96** [comment]
@evollu @benoist @moriyoshi @ibratoev @radev @zaro Someone guide me?

**Comment by evollu** [comment]
image in iOS notification? is it possible in native iOS?

**Comment by evollu** [comment]
dup of https://github.com/evollu/react-native-fcm/issues/719#issuecomment-395956329
closing this

**Comment by engin145** [comment]
@kartavyaparekh96 it works for me https://www.pluralsight.com/guides/creating-ios-rich-push-notifications. Good luck!

**Comment by evollu** [comment]
@engin145 that's helpful! Does this work after user force kill the app?

**Comment by kartavyaparekh96** [comment]
It is done in React-native-onesignal

**Comment by evollu** [comment]
@kartavyaparekh96 cool. is it possible for you to port it over?
