### ISSUE TITLE
Could not find com.google.firebase:firebase-analytics:12.0.1.

### ISSUE THREAD

**Issue by KBepo** [evollu/react-native-fcm#974]
Everything was working fine untill this morning. I have no idea what's wrong but it is across multiple projects. Didn't change anything I'm still in process of programming. Didn't add any new node modules or change any of the settings.

This was output:
`Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-fcm'.
      > Could not resolve all dependencies for configuration ':react-native-fcm:_debugPublishCopy'.
         > Could not find com.google.firebase:firebase-analytics:12.0.1.`

Just tried to run react-native run-android.

**Comment by arsal-wal** [comment]
I've the similar problem with version 14.1.3. It gives error:

> Could not find com.google.firebase:firebase-analytics:11.8.0.`

**Comment by noambonnie** [comment]
Google separated Play Services from Firebase on the latest release: https://developers.google.com/android/guides/releases

I'm no Android expert and got lost in the gradle files, but from the reading I did it looks like you now have to use the latest release of all firebase and gms libraries (their latest can be found here: https://mvnrepository.com).

In the rn-fcm library, @evollu uses the same version for both gms and firebase. As a temporary solution I changed the library's build.gradle to use the latest version:

```
    compile "com.google.firebase:firebase-core:+"
    compile "com.google.firebase:firebase-messaging:+"
```

I hope @evollu can update those files to support the new libraries from Google. I didn't create a pull request because I don't feel that I fully understand the implications but that solution seems to work for me.

**Comment by noambonnie** [comment]
Some more references: 
https://stackoverflow.com/questions/50182756/multiple-dex-files-define-lcom-google-android-gms-internal-measurement-zzabn

https://github.com/invertase/react-native-firebase/issues/1155

**Comment by linh1987** [comment]
I find that upgrading to firebase 16.0.1 and compileSDKversion to 27 and build tool to 27.0.3 solve the problem for me .

**Comment by noambonnie** [comment]
@KBepo I'm looking at the file on master and it seem that the version is set by googlePlayServicesVersion or defaults to 11.+:
https://github.com/evollu/react-native-fcm/blob/master/android/build.gradle 

@linh1987 I will try that (I've already set the version to the latest, but haven't checked reverting my manual change to the library's build.gradle.

**Comment by noambonnie** [comment]
Ok I've tried again. With the code as it is the build fails. I had to modify fcm's build.gradle as stated above.

**Comment by jacktv1** [comment]
When i change build.gradle to
`compile "com.google.firebase:firebase-core:+"
  compile "com.google.firebase:firebase-messaging:+"`
I have other problem

> Failed to apply plugin [id 'com.google.gms.google-services']
   > For input string: "+"
Any one known about this problem

**Comment by arsal-wal** [comment]
@jacktv1 I have the same problem. I guess what @noambonnie means is to leave app/build.gradle file as it is and change the build.gradle file of react-native-fcm in node modules.

**Comment by arsal-wal** [comment]
However by changing the the build.gradle file in node_modules/react-native-fcm/android/build.gradle to match the dependencies as:

compile "com.google.firebase:firebase-core:+"
compile "com.google.firebase:firebase-messaging:+"

I now face this error
`> Could not find method getCompileConfiguration() for arguments [] on object of type com.android.build.gradle.internal.api.ApplicationVariantImpl.`

**Comment by arsal-wal** [comment]
Got everything working by changing node_modules/react-native-fcm/android/build.gradle dependencies to:

```
compile "com.google.firebase:firebase-core:+"
compile "com.google.firebase:firebase-messaging:+"
```

and changing dependencies in project's build.gradle file to:

```
dependencies {
  classpath 'com.android.tools.build:gradle:2.2.3'
  classpath 'com.google.gms:google-services:3.2.1'
}
```

**Comment by jacktv1** [comment]
@arsal-wal what version of firebase core in android/app/build.gradle
here is my: compile 'com.google.firebase:firebase-core:10.0.1'

**Comment by arsal-wal** [comment]
@jacktv1 here are the firebase versions in my app build.gradle file:

```
compile project(':react-native-fcm')
compile "com.google.firebase:firebase-core:10.0.1"
compile "com.google.firebase:firebase-messaging:10.0.1"
```

Note: My react-native-fcm version in package.json is 14.1.3:

> "react-native-fcm": "^14.1.3",

**Comment by niranjan-b-prajapati** [comment]
@arsal-wal Thanks for pointing me to this issue as i have posted same issue at same time. But i am having following versions of RN :

> "react-native": "0.44.0",
> "react-native-fcm": "^7.2.0",

dependencies in android build.gradle:
```
dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'
        classpath 'com.google.gms:google-services:3.0.0'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
```
following are dependencies in my app build.gradle:
```
dependencies {
    compile project(':react-native-orientation')
    compile project(':react-native-fcm')
    compile 'com.google.firebase:firebase-core:10.0.1' //this decides your firebase SDK version
    compile project(':react-native-image-picker')
    compile project(':react-native-device-info')
    compile project(':react-native-google-analytics-bridge')
    compile project(':react-native-vector-icons')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
}
```
I am in a situation where i can't upgrade as i have a delivery date and this issue just appeared out of nowhere.

Can anyone help me with some other solution.

**Comment by arsal-wal** [comment]
@niranjan-b-prajapati did you try changing google-services version to 3.2.1 in android/build.gradle

        classpath 'com.google.gms:google-services:3.0.0'

**Comment by sagark1510** [comment]
I got it working by upgrading fcm to latest version.

**Comment by Srija-t2s** [comment]
@arsal-wal  I have set my android/build.gradle  to

`classpath 'com.google.gms:google-services:3.2.1'`

And my android/app/build.gradle is set to 
'com.google.firebase:firebase-core:10.0.1'

node_modules/react-native-fcm/android/build.gradle is set to 
compile "com.google.firebase:firebase-core:+"
compile "com.google.firebase:firebase-messaging:+"

I am using react-native:0.45.1
                  react-native-fcm - "^10.0.1"
But stiil I am getting this error:Could not resolve all dependencies for configuration ':react-native-fcm:_debugCompile'.

**Comment by jacktv1** [comment]
I have slove problem on android when upgrading fcm to latest version.
But i have orther problem in ios

**Comment by rajeshbhagat** [comment]
I tried everything from all the above mentioned solutions to upgrading fcm to latest version, nothing worked for me.

following is the solution which worked for me:
change this in your project's build.gradle file
```
allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            url "$rootDir/../node_modules/react-native/android"
        }
      }
}
```
to this 

```
allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            url "$rootDir/../node_modules/react-native/android"
        }
         maven {
             url 'https://maven.google.com'
         }
    }
}
```

**Comment by niranjan-b-prajapati** [comment]
@rajeshbhagat Thank you so much your solution worked for me seriously man you saved my day was struggling with this from last few days

**Comment by noambonnie** [comment]
@evollu, Thanks for your continued support on this project. 

Not sure why this is closed. The issue persists (and the commit doesn't seem to address the fact that the versions of Firebase and Play Services are no longer the same).

**Comment by evollu** [comment]
@noambonnie it seems to be a configuration issue and seems some people have provided some solutions.
What is your config?

**Comment by onusgit** [comment]
anyone plz add working project configuration of gradle file..

**Comment by root-developer** [comment]
Great,
i can fix my error, tnks @rajeshbhagat 
God Bless You.

**Comment by rjsingh12123** [comment]
Get learn from here , it solves error for me 
https://firebase.google.com/docs/analytics/android/start

**Comment by uendar** [comment]
I still get crash on notification received. 

**android/app/gradle**

`
android {

    compileSdkVersion 28
    buildToolsVersion '28.0.0'
    defaultConfig {
        applicationId "com.XXX"
        minSdkVersion 16
        targetSdkVersion 28
        versionCode 013
        versionName "XXXX"
        multiDexEnabled true


        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
        manifestPlaceholders = [manifestApplicationId: "${applicationId}",
                                onesignal_app_id: "XXX",
                                onesignal_google_project_number: "XXX"]
    }



packagingOptions {
       pickFirst 'lib/x86/libc++_shared.so'
       pickFirst 'lib/x86_64/libjsc.so'
       pickFirst 'lib/arm64-v8a/libjsc.so'
       pickFirst 'lib/arm64-v8a/libc++_shared.so'
       pickFirst 'lib/x86_64/libc++_shared.so'
       pickFirst 'lib/armeabi-v7a/libc++_shared.so'
   }

    signingConfigs {
         debug {
            if (project.hasProperty('MYAPP_RELEASE_STORE_FILE')) {
                storeFile file(MYAPP_RELEASE_STORE_FILE)
                storePassword MYAPP_RELEASE_STORE_PASSWORD
                keyAlias MYAPP_RELEASE_KEY_ALIAS
                keyPassword MYAPP_RELEASE_KEY_PASSWORD
            }
        }
        release {
            if (project.hasProperty('MYAPP_RELEASE_STORE_FILE')) {
                storeFile file(MYAPP_RELEASE_STORE_FILE)
                storePassword MYAPP_RELEASE_STORE_PASSWORD
                keyAlias MYAPP_RELEASE_KEY_ALIAS
                keyPassword MYAPP_RELEASE_KEY_PASSWORD
            }
        }
    }

    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
         release {
          manifestPlaceholders = [isDebug:false]
           minifyEnabled enableProguardInReleaseBuilds
           proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
           signingConfig signingConfigs.release
       }
       // added on 2/6/2019
         debug {
              manifestPlaceholders = [isDebug:true]
         }

    }


    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }


//     packagingOptions {
//        pickFirst '**/libjsc.so'
//     }
}

dependencies {
   compile project(':react-native-gesture-handler')
   compile project(':react-native-push-notification')
   implementation fileTree(dir: "libs", include: ["*.jar"])
   implementation "com.android.support:appcompat-v7:28.0.0"
   compile "com.android.support:support-core-utils:28.0.0"
   implementation project(':react-native-fcm')
   implementation 'com.google.firebase:firebase-core:16.0.8'
   implementation 'com.google.firebase:firebase-messaging:17.6.0'
   implementation ("com.facebook.react:react-native:+") { force = true }  // From node_modules
   implementation project(':realm')
   implementation project(':react-native-fs')
   implementation project(':react-native-vector-icons')
   implementation project(':react-native-image-picker')
   implementation project(':react-native-fetch-blob')
   implementation project(':react-native-image-crop-picker')
   implementation project(':react-native-exit-app')
   implementation project(':react-native-onesignal')
   implementation project(':react-native-sensor-manager')
   implementation project(':react-native-smart-barcode')
   implementation project(':react-native-push-notification')
   implementation project(':react-native-linear-gradient')
   implementation project(':react-native-file-picker')
   implementation project(':react-native-doc-viewer')
   implementation project(':react-native-svg')
   implementation project(":react-native-google-signin")
   implementation project(':react-native-spinkit')
   implementation project(':react-native-pdf')
}


task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}


configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def requested = details.requested
        if (requested.group == 'com.android.support') {
            if (!requested.name.startsWith("multidex")) {
                details.useVersion '25.3.1'
            }
        }
    }
}

apply plugin: 'com.google.gms.google-services'
`

**build/gradle**

`buildscript {
     ext {
        // googlePlayServicesAuthVersion = "15.0.1" // <--- use this version or newer
        firebaseVersion ="16.0.6"
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
    }
    repositories {
     google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.1'
        classpath 'com.google.gms:google-services:+'

    }
}

allprojects {
    repositories {
         google()
        mavenLocal()
        mavenLocal()
        // for modules depending on jitpack.io
        maven { url "https://jitpack.io" }
        // add this one
        maven {
            url "https://maven.google.com"
        }
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
             url "$rootDir/../node_modules/react-native/android"
          //   url 'https://maven.google.com'
        }
        jcenter()
    }
    }

subprojects {
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion 28
                buildToolsVersion "28.0.0"
                defaultConfig {
                    targetSdkVersion 28
                }
            }
        }
    }
}
`


**AndroidManifest**

`
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.xxxxx"
    android:versionCode="0.1.1"
    android:versionName="xxx">


<uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <permission
        android:name="${applicationId}.permission.C2D_MESSAGE"
        android:protectionLevel="signature" />
    <uses-permission android:name="${applicationId}.permission.C2D_MESSAGE" />




    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_INTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.WRITE_INTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
    <uses-permission android:name="android.permission.READ_CALENDAR" />
    <uses-permission android:name="android.permission.WRITE_CALENDAR" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
    <uses-feature android:name="android.hardware.camera" android:required="true"/>
    <uses-feature android:name="android.hardware.camera.autofocus" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>

     <uses-sdk
        android:minSdkVersion="16"
        android:targetSdkVersion="28" /> 



    <application
      android:name=".MainApplication"
      android:usesCleartextTraffic="true"
      android:allowBackup="true"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:theme="@style/AppTheme"
      android:launchMode="singleTop" >

        <meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_name"
                android:value="YOUR NOTIFICATION CHANNEL NAME"/>
        <meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_description"
                    android:value="YOUR NOTIFICATION CHANNEL DESCRIPTION"/>
        
        <meta-data  android:name="com.dieam.reactnativepushnotification.notification_color"
                    android:resource="@android:color/white"/>


        <receiver
            android:name="com.google.android.gms.gcm.GcmReceiver"
            android:exported="true"
            android:permission="com.google.android.c2dm.permission.SEND" >
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <category android:name="${applicationId}" />
            </intent-filter>
        </receiver>


     <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
            </intent-filter>
        </receiver>
        <service android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationRegistrationService"/>
        <service
            android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService"
            android:exported="false" >
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>

        <service
            android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService"
            android:exported="false" >
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>

      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustResize"
        android:screenOrientation="portrait"
        >


   <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>




</manifest>
`
