### ISSUE TITLE
Could not find com.google.firebase:firebase-analytics:12.0.1

### ISSUE THREAD

**Issue by niranjan-b-prajapati** [evollu/react-native-fcm#975]
@evollu  I was trying to create release build for my RN app today morning and suddenly the build failed giving me the following error:

> To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/2.14.1/userguide/gradle_daemon.html.
> Incremental java compilation is an incubating feature.
> Download https://jcenter.bintray.com/com/google/firebase/firebase-core/12.0.1/firebase-core-12.0.1.pom
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> A problem occurred configuring project ':app'.
> > Could not resolve all dependencies for configuration ':app:_debugApk'.
>    > A problem occurred configuring project ':react-native-fcm'.
>       > Could not resolve all dependencies for configuration ':react-native-fcm:_debugPublishCopy'.
>          > Could not find com.google.firebase:firebase-analytics:12.0.1.
>            Required by:
>                high_furtados_appv2:react-native-fcm:unspecified > com.google.firebase:firebase-core:12.0.1
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> BUILD FAILED

>Total time: 25.095 secs

I have not made changes to any node_modules folder or any other changes related to react-native-fcm library.
Following are my RN version and react-native-fcm version on project:

```
"react-native": "0.44.0",
"react-native-fcm": "^7.2.0"
```

When i opened project in android studio it gave following error :

`Failed to resolve: com.google.firebase:firebase-analytics:12.0.1`

**Comment by leshanative** [comment]
1. Have you changed your AndroidManifest.xml?
2. Can you make "git reset --hard" to the latest successful build and try to build your app again?

**Comment by snehasis** [comment]
Include this plugin to your cordova project to solve the issue.
Make sure delete the android platform before doing the Build once again.

https://github.com/dpa99c/cordova-android-play-services-gradle-release

**Comment by niranjan-b-prajapati** [comment]
@snehasis it is react-native project and not cordova one.

@leshanative No I have not made any changes to the manifest file.

**Comment by arsal-wal** [comment]
Could be similar to #974

**Comment by arsal-wal** [comment]
Similar to #974.  I've posted a solution there.
