### ISSUE TITLE
Notification when app is open on Oreo+

### ISSUE THREAD

**Issue by WilliamAlexander** [evollu/react-native-fcm#977]
**This is more of a how to. If this exists in a readme. I'll delete again**
If anyone is having issues getting a notification to appear (in tray) while the app is in the foreground and using Android Oreo+

- in your RN code call:
-- await FCM.createNotificationChannel({ id: "any_id", name: "any_name", priority: "high" });
- I called this after, let token = await FCM.getFCMToken().catch(console.error);

In you FCM paylod, in the **custom_notification** block, add:
-  "channel": "any_id" in

Now notification will appear in the tray while app is in foreground.

Using:
"react-native": "0.54.0",
"react-native-fcm": "git://github.com/evollu/react-native-fcm#sdk-26",

**Comment by evollu** [comment]
it is not in readme but it is in example project

**Comment by ShaileshPrajapati-BTC** [comment]
facing the same issue in oreo

**Comment by evollu** [comment]
have you setup notification channels and put notification channel in your notification payload?
https://github.com/evollu/react-native-fcm/blob/master/Examples/simple-fcm-client/app/App.js#L38

**Comment by 404sand808s** [comment]
@evollu I'm wondering about createNotificationChannel though: if we do it pre-Oreo will it be a problem, or should we check if version is Oreo and do it situationally and only then?

**Comment by evollu** [comment]
@404sand808s the method does version check so it will be safe
