### ISSUE TITLE
Notification popup does not appear on iOS

### ISSUE THREAD

**Issue by jadsonor** [evollu/react-native-fcm#983]
I've configurated my app like the examples, but when I send a notification from Firebase console the popup does not appear on iOS. Obs.: I received the payload normally.

**Comment by evollu** [comment]
`I received the payload normally` so you have got the push notification but just not seeing the banner?
Have you granted push notification permission?
Just in case, this is a real device, right?

**Comment by jadsonor** [comment]
Yes, just not seeing the banner. I've granted the permission on a real device.

**Comment by evollu** [comment]
if you are doing foreground, have you added "show_in_foreground: true"?
also is this iOS >= 10?

**Comment by jadsonor** [comment]
In the payload 'show_in_foreground' was set to true.

**Comment by evollu** [comment]
@jadsonor in that case, you should see notification even without calling `presentLocalNotification`

**Comment by jadsonor** [comment]
I'm not seeing even without it. Anyway, I've decided to migrate to react-native-firebase as you recommended. Maybe it's a problem with my project... I gonna check it all again. Thanks for your attention.
