### ISSUE TITLE
Difference between `FCM.on(FCMEvent.Notification)` and `FCM.getInitialNotification` ?

### ISSUE THREAD

**Issue by taichi-jp** [evollu/react-native-fcm#993]
1. What version of RN and react-native-fcm are you running?
0.53.3/14.1.3
2. What device are you using? (e.g iOS9 emulator, Android 6 device)?
iPhone6(iOS11) device & Xperia XZ Premium(Android 8) device
3. Is your app running in foreground, background or not running?
I tried all the patterns

-------------------------------------------------------------------------
I wanna to something when the app is launched from tapping notification in both iOS and Android.

I think when app is not running I have to use `FCM.getInitialNotification`, and when it's running `FCM.on(FCMEvent.Notification)`, like written in https://github.com/evollu/react-native-fcm#behaviour-when-sending-notification-and-data-payload-through-gcm. (Is this not through-gcm but through-fcm ?)

But the question is that my app in iPhone catches `FCM.on(FCMEvent.Notification)` even when the app is not running and launched from tapping notification!
My Android phone catches only `FCM.getInitialNotification`.

I wonder what is the difference of usages of these two methods.

**Comment by evollu** [comment]
it might be this case. perhaps iOS triggers remote notification handler. but FCM.getInitialNotification is still a more reliable way

**Comment by taichi-jp** [comment]
@evollu 
Thank you!
Since that behavior is expected, I close this issue.
